### ISSUE TITLE
Clarify WSL installation instructions

### ISSUE THREAD

**Issue by christerengman** [MicrosoftDocs/WSL#1003]
It was not clear that you had to _start_ the "Ubuntu 20.04 LTS" app after installing it with Add-AppxPackage.

Please clarify and also describe or refer to just double-clicking the appx file as the natural choice as that also offers starting the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by justinclift** [comment]
Yeah, the current instructions are incomplete without this final step.  I nearly just uninstalled it all to switch to VMware Workstation instead (might still do so).  But double clicking the downloaded appx seems to have gotten it to actually run and do things. :smile:

**Comment by niderhoff** [comment]
Thanks, I was wondering why wsl -l didn't show any distributions..

**Comment by mattwojo** [comment]
Thank you for point this issue out @christerengman! Apologies for the late reply - we're getting caught up on our backlog of issues. I've added a note about double-clicking to start the Appx package after downloading: https://github.com/MicrosoftDocs/WSL/commit/48385a820bb90bc64841ffab038bc24394fab6ec

Sorry to all for the confusion on that - hopefully this additional note will spare others from experiencing it.
