### ISSUE TITLE
ubuntu not showing after installation

### ISSUE THREAD

**Issue by saveriogzz** [MicrosoftDocs/WSL#1007]
Hi,

I followed the steps of downloading and installing and worked smoothly; however, when I run `wsl -l`, i still cannot see the ubuntu version that I downloaded and installed, even after a reboot.
May you help here?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
If you open the start menu and run the "Ubuntu" app it should install into WSL for the first time. After that you'll be able to create a user, and then from there you'll be able to run `wsl -l` and see it listed there. Does following those steps help fix you?

**Comment by saveriogzz** [comment]
I created the user correctly and ubuntu is woring, but I still cannot see the Ubuntu app when running `wsl -l`.  
The app I have is `Ubuntu 20.04 LTS`, installed through Microsoft store.

**Comment by craigloewen-msft** [comment]
Do you see any output at all for that command or just a blank list?
If you run `wsl.exe` what happens?

**Comment by saveriogzz** [comment]
my `wsl -l -v` gives back  

| NAME                | STATE   | VERSION |
|---------------------|---------|---------|
| * docker-desktop    | Stopped | 2       |
| docker-desktop-data | Stopped | 2       |  

`wsl.exe` prompts to  
`NameOfMyMachine:/mnt/host/c/WINDOWS/system32# `

**Comment by craigloewen-msft** [comment]
Are you running these commands inside of an Administrator prompt? If you open up a non admin prompt and run `wsl.exe -l -v` what do you see?

**Comment by saveriogzz** [comment]
I see Ubuntu is there! :)
|NAME|STAT|VERSION|
|---------|-------|--------------|
|Ubuntu-20.04|Stopped|1|
Thanks! How can I "switch" Ubuntu to wsl 2? That was actually my goal..

**Comment by craigloewen-msft** [comment]
You can run the command: `wsl --set-version Ubuntu 2`

**Comment by saveriogzz** [comment]
running both `wsl --set-version Ubuntu 2` and `wsl --set-version Ubuntu 2` gives me back  
`There is no distribution with the supplied name`

**Comment by craigloewen-msft** [comment]
Oh whoops, my mistake, I misread your distro name. It should be `wsl --set-version Uuntu-20.04 2`. Basically whatever distro name you see when you run `wsl -l -v` :)

**Comment by saveriogzz** [comment]
Yes... that's indeed has the same effect of not being working

**Comment by saveriogzz** [comment]
Thanks a lot! I see now that the version is 2 :)
Last clarification: why I still don't see Ubuntu if I run `wsl -l -v` in a powershell with admin rights? While if I run `wsl.exe -l -v` in a powershell without admin rights I don't see Docker.

**Comment by naveedshahji** [comment]
> Thanks a lot! I see now that the version is 2 :) Last clarification: why I still don't see Ubuntu if I run `wsl -l -v` in a powershell with admin rights? While if I run `wsl.exe -l -v` in a powershell without admin rights I don't see Docker.

have you solved the issue? i am facing exactly the same issue.
