### ISSUE TITLE
fix typo

### ISSUE THREAD

**Issue by dmitrii-esin** [MicrosoftDocs/WSL#1009]
Hi!
I see the mistake in this area of page (see point 2.):  https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

`1. You are still in old version of Windows which doesn't support WSL 2. Please check the WSL 2 requirements and upgrade to use WSL
2. 
3. Windows Subsystem for Linux is not enabled. Please follow the Windows Subsystem for Linux Installation Guide.
4. After you enabled Windows Subsystem for Linux, a reboot is required to take into effect, please reboot your machine and try again.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Updating the WSL 2 Linux kernel](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks for pointing this out @dmitrii-esin. I just redirected that kernel download page. It was a temporary placeholder for the main install page (which includes the kernel download step), so this issue is resolved.
