### ISSUE TITLE
FAQ contains obsolete advice saying you can't change Linux files from Windows tools

### ISSUE THREAD

**Issue by JohnRusk** [MicrosoftDocs/WSL#1013]
The advice in the FAQ is superceded by this: https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-windows-10-version-1903/

The section in the FAQ should be amended to remove the obsolete advice, or at least say that its obsolete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd5bfb4-8a38-1f09-0d36-6b9abe9b8b08
* Version Independent ID: 156d9535-c2a5-bc8d-af24-342a13832abf
* Content: [Frequently Asked Questions (FAQ)](https://docs.microsoft.com/en-us/windows/wsl/faq)
* Content Source: [WSL/faq.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Fixed!
