### ISSUE TITLE
WSL2 kernel update MSI download link does not work

### ISSUE THREAD

**Issue by todor-mutafov** [MicrosoftDocs/WSL#1014]
The link for WSL2 x64 MSI download redirects me back to the same page, leaving me with no way to download the MSI and thus now way to update to WSL2. Had to scour github for a direct download link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
I've reverted this change while we investigate why this might be the case. Thank you for reporting this! :)
https://github.com/MicrosoftDocs/WSL/commit/42eff29e6196dad7de003d211d3c1dec8b8430f6
