### ISSUE TITLE
Windows 10 Home vs Pro

### ISSUE THREAD

**Issue by mortenmoa** [MicrosoftDocs/WSL#1015]
For users using Windows 10 Home version it's not possible to update to WSL level 2.
They have to pay a licence and upgrade to Windows 10 Pro version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-2---update-to-wsl-2)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
WSL 2 is available on Windows 10 Home as well as pro.
