### ISSUE TITLE
RSS support

### ISSUE THREAD

**Issue by webuniverseio** [MicrosoftDocs/WSL#1018]
Hello, I like documentation page with release notes https://docs.microsoft.com/en-us/windows/wsl/release-notes - it gives short, but detailed overview of new features that are being added and addressed.
I wish to have a way to get notified of new features and I think adding RSS support would help with that. 

Do you think this is possible? Or is there existing alternative way to get updates?
Thanks

**Comment by Biswa96** [comment]
Just enable watch in this repository.

**Comment by webuniverseio** [comment]
@Biswa96 , I just realized I can only watch https://github.com/MicrosoftDocs/WSL/releases, this works well, thanks

**Comment by webuniverseio** [comment]
Actually I see a problem with https://github.com/MicrosoftDocs/WSL/releases, 2 release notes are missing from it so I guess due to duplication of effort it is not maintained as well. I don't want to receive info about corrections, pull requests, issues, so I think my ask for a convenient way to subscribe to release notes is still valid.

**Comment by craigloewen-msft** [comment]
Release notes can be found here: https://github.com/microsoft/wsl
