### ISSUE TITLE
Problem Upgrading from WSL 1 to WSL 2 (Resolved)

### ISSUE THREAD

**Issue by LucichM** [MicrosoftDocs/WSL#1020]
If you've followed the steps: Enable the Windows Subsystem for Linux, Enable Virtual Machine feature, enabled virtualization in the bios, etc. and still receive the message "Please enable the Virtual Machine Platform Windows feature..." when attempting to convert a distribution from version 1 to version 2, then check to ensure Hyper-V Windows feature turned on. The newest version of WSL uses Hyper-V architecture to enable its virtualization. If you've been running WSL 1 on an older system, you may need to turn on Hyper-V in order to use WSL 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by netstx** [comment]
I don't recall enabling Hyper-V feature after installing Windows 10 (fresh 20H2 install a few weeks ago), and this process went through. I wonder if it's an issue if you installed WSL1 before upgrading to a more recent version of Windows 10?

**Comment by LucichM** [comment]
Yes, something like that. My Windows 10 is an old install which has been
upgraded, Windows 7, 8, 8.1, 10, and I installed WSL 1 maybe months ago,
maybe years ago! I mainly wanted to point out that it's something to check
if one continues to receive the message. It took me about twenty minutes
and sleeping on it to figure it out. Feel free to use my report if/as you
see fit. The article is a good one! Just wanted to make you aware of my
experience. Thx! ...Mike

**Comment by craigloewen-msft** [comment]
We put some troubleshooting steps [here on the docs](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed) to help with this. I suspect you might not have virtualization enabled in your BIOS, please see the steps there on how to resolve it! :) 

Thank you for filing this!
