### ISSUE TITLE
Include links to the command troubleshooting steps earler in the install process

### ISSUE THREAD

**Issue by jonathanbossenger** [MicrosoftDocs/WSL#1022]
I recently attempted to install WSL2 on my Windows boot drive. As an experienced Ubuntu user, I was interested to see how WSL compared.

I got as far as Step 6 - Install your Linux distribution of choice, when I received the following error message

```
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.
```

Some searching later, it turned out I needed to enable virtualization in my BIOS.

Only after a conversation with Craig Loewen online, did I discover the Troubleshooting steps at the bottom of the document. I'd like to suggest that these steps be highlighted for the user, earlier in the install steps.

As I'm not a Windows Insider, and I was following the install steps, it might have been useful to see a link to the Troubleshooting steps after each of the install steps where these troubleshooting steps would apply.

Also, it might be useful to make a note about the BIOS setting requirement much earlier on, perhaps before Step 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks for the suggestion @jonathanbossenger. I just added a note at the top of the install page in hopes of better highlighting the troubleshooting section as you recommend. https://github.com/MicrosoftDocs/WSL/commit/49715464859b0760fca2a32682a9a08267f34db5

Sorry you ran into trouble. Hope it's all worked out and that you're enjoying WSL now. If you have any other feedback - please let us know!

**Comment by jonathanbossenger** [comment]
@mattwojo thanks, I do think that will help folks. Appreciate the feedback.
