### ISSUE TITLE
Run fails -- Django not installed

### ISSUE THREAD

**Issue by jhulance** [MicrosoftDocs/WSL#1026]
Running fails because Django is not installed in container image. This can be fixed at step 8) with the addition of "python3 -m pip install django" from the container shell. Shouldn't this be installed in the container, to ease the user experience?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 403a33a6-304c-2ded-9ea8-4d70bc5f17ba
* Version Independent ID: 93b6a9ef-08ba-be90-736e-27515fb0f4da
* Content: [Get started using Docker containers with Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers)
* Content Source: [WSL/tutorials/wsl-containers.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-containers.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by scolear** [comment]
Bump. 

I was under the assumption docker solves the whole "it works on my machine" problem, but alas

**Comment by craigloewen-msft** [comment]
I've added a PR to the example git project here that installs Django as part of the dev container set up!

https://github.com/mattwojo/helloworld-django/pull/2

@mattwojo would you be able to try my fix, merge the PR and then close out this issue? :)

**Comment by mattwojo** [comment]
My bad!!! Sorry all!

Yes - Docker solves the whole "it works on my machine" problem, but only if the container is set up correctly to install everything you need for the project. I just totally missed adding Django to the container!

It looks like Craig's fix, which is to uncomment this section in the .devcontainer/Dockerfile:
```
# [Optional] If your pip requirements rarely change, uncomment this section to add them to the image.
COPY requirements.txt /tmp/pip-tmp/	COPY requirements.txt /tmp/pip-tmp/
RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \	RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
&& rm -rf /tmp/pip-tmp && rm -rf /tmp/pip-tmp
```
and then add in the `requirements.txt` file that Django should be installed:

`Django>=3.0,<4.0`
