### ISSUE TITLE
Running both Windows and Linux containers simultaneously

### ISSUE THREAD

**Issue by adyanth** [MicrosoftDocs/WSL#1029]
[This link](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers) here says the below:
> By enabling the WSL 2 based engine, you can run both Linux and Windows containers in Docker Desktop on the same machine.

There is a need to clarify if both of them can happen at the same time, or is this referring to switching between windows and Linux containers, since windows containers need Containers feature turned on, not Windows Subsystem for Linux as needed for Linux containers.

If it is indeed possible to run both together, I am very interested in knowing how.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 403a33a6-304c-2ded-9ea8-4d70bc5f17ba
* Version Independent ID: 93b6a9ef-08ba-be90-736e-27515fb0f4da
* Content: [Get started using Docker containers with Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers)
* Content Source: [WSL/tutorials/wsl-containers.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-containers.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
It is possible to run them both at the same time. You can install Docker Desktop on Windows and use it with Windows containers, and then install a standalone solution of Docker straight into a WSL distro and interact with it there which will allow you to use Linux containers. However with this set up you'll lose the benefit of being able to interact with the same containers across both Windows and Linux.

**Comment by craigloewen-msft** [comment]
Let me know if you have more questions here! :)

**Comment by adyanth** [comment]
Hey @craigloewen-msft , thanks for the clarification, the docs seemed to say I could do it from docker for windows itself with the --platform switch. Some old Microsoft blogs like [this one](https://devblogs.microsoft.com/premier-developer/running-docker-windows-and-linux-containers-simultaneously/) say that was possible before, but that was using LCOW, not WSL. Is something similar possible now?

When you say:
> install a standalone solution of Docker straight into a WSL distro

Do you mean install docker engine inside WSL? Would that not have the disadvantage of not communicating between the containers on Windows and Linux? and as you said not being able to manage them from the same docker client. Maybe I can put them in a swarm, that's a nice idea!

**Comment by craigloewen-msft** [comment]
@adyanth yes that's correct I mean install the Docker engine inside of a WSL distro. And you're also correct this approach does contain the disadvantage of not being able to communicate with the same containers between Windows and Linux as easily as Docker Desktop exposes it.
