### ISSUE TITLE
[network] section seems to support hostname key which allows overriding of the auto generated hostname

### ISSUE THREAD

**Issue by MedAnd** [MicrosoftDocs/WSL#1030]
The [network ](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#network) section seems to support hostname as a key which allows overriding of the auto generated hostname.

This is important as the auto generated hostname can sometimes contain special characters and uppercase, not supported by some applications such as MicroK8s. 

Example wsl.conf:

```
[network]
generateHosts = false
generateResolvConf = true
hostname = mk8smaster
```

Please confirm and if correct update the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by MedAnd** [comment]
Hi @craigloewen-msft - was this issue closed for a specific reason, for example has this feature been removed from WSL2, documented etc? Thx.

**Comment by craigloewen-msft** [comment]
Yes this is closed as we've updated the docs! You can see we've documented the "hostname" parameter here:
https://docs.microsoft.com/en-us/windows/wsl/wsl-config#network-setting

Apologies for the close without comment, I'm going through this repo and trying to close out the 100s of older issues :) Thank you for following up!
