### ISSUE TITLE
Does the IP address of the Linux host VM persist across sessions and across Linuxes?

### ISSUE THREAD

**Issue by bcollin** [MicrosoftDocs/WSL#1031]
> However, if you are running an older version of Windows (Build 18945 or less), you will need to get the IP address of the Linux host VM (or update to the latest Windows version).

Also if localhost is already bound, as far as I can tell.

Does the IP address of the Linux host VM persist across sessions and across Linuxes? I.e. can I enter the IP address I found using your method in my host file without worrying that it won't work next time I restart the computer?

**Comment by bcollin** [comment]
To answer my own question, it does not. However I am using WSL for Docker and can map Linux port 80 to for example host port 8080, which seems to work just as well.

**Comment by mattwojo** [comment]
Thanks @bcollin!  It sounds like this would be worth making note of in the docs. Adding to my backlog.

**Comment by mattwojo** [comment]
Added. https://github.com/MicrosoftDocs/WSL/pull/1475
