### ISSUE TITLE
Confusing or misleading information at https://docs.microsoft.com/en-us/windows/wsl/interop#run-linux-tools-from-a-windows-command-line

### ISSUE THREAD

**Issue by DeV4Met** [MicrosoftDocs/WSL#1032]
Hello,
Confusing or misleading information.
The first example of https://docs.microsoft.com/en-us/windows/wsl/interop#run-linux-tools-from-a-windows-command-line starts with misleading indication:
C: \ temp> wsl ls -la
<- contents of C: \ temp ->
The command actually returns the contents of the default "home" directory of the user who launches the "ls" command.
The contents of the C: \ temp directory are not returned, as specified in the comment below the command.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea49528-e5c5-4f64-841e-9fe036de304e
* Version Independent ID: edeb7cb5-afcf-1410-4966-f48ce5f6a19a
* Content: [Windows interoperability with Linux](https://docs.microsoft.com/en-us/windows/wsl/interop)
* Content Source: [WSL/interop.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/interop.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This command should work as specified in the example. I wasn't able to find your problem when running it on my machine: 
![image](https://user-images.githubusercontent.com/42221804/103240292-cb091900-4904-11eb-8e9a-83265e6f2b44.png)

Would you be able to try the command again and see if you still see the same error? 

I'm closing this issue out as I don't believe there is an actionable item here for us to fix.

**Comment by vasiliub** [comment]
Thanks 👍
