### ISSUE TITLE
Will WSL 2 distros (distributions) show up in the Hyper-V Manager on Windows 10? Or are they treated and managed completely separately, even though they still "make use of" Hyper-V?

### ISSUE THREAD

**Issue by GrantRobertson** [MicrosoftDocs/WSL#1040]
Will WSL 2 distros (distributions) show up in the Hyper-V Manager on Windows 10? Or are they treated and managed completely separately, even though they still "make use of" Hyper-V?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
You're correct, they will not show up on the Hyper-V manager on Windows 10, as they are treated and managed completely separately but still make use of Hyper-V. :)
