### ISSUE TITLE
Under Linux subsystem, how to run stata installed in windows 

### ISSUE THREAD

**Issue by hehemin** [MicrosoftDocs/WSL#1044]
[Enter feedback here]
Hi~I am a phd student in economics. My frequent used software is Stata. Since it's costly to reinstall stata under Ubuntu subsystem (i.e. WSL2), I want to run stata which has been installed in my windows system with Linux subsystem. Could you please tell me how these two system interact with each other? Or may you provide some method to run stata installed in windows under Ubuntu subsystem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
I'm not too familiar with Stata itself, but you can call any Windows executable from the Linux command line using interop. E.g: you can run Powershell by typing in `powershell.exe`. So if you wanted to interact with Stata you can open it using its executable from the Linux prompt, or pipe in values to it, etc. 

This doc page should answer all your questions on interop!
https://docs.microsoft.com/en-us/windows/wsl/interop

**Comment by hehemin** [comment]
Thanks for your kind reply.&nbsp;
The link is really helpful although I still need time to figure it out how to make my stata.exe in D:\Install work with the path /mnt/f/Project/.&nbsp;


Sincerely,
Hemin
&nbsp;




------------------&nbsp;Original&nbsp;------------------
