### ISSUE TITLE
Error in Add-AppxPackage .\app_name.appx

### ISSUE THREAD

**Issue by cdvries** [MicrosoftDocs/WSL#1051]
[Enter feedback here]
Hallo,

I believe the following line on the page is incorrect

> Add-AppxPackage .\app_name.appx

However I was able to install using this (correct) line 
 
> Add-AppPackage https://aka.ms/wsl-kali-linux-new

Note, there is no x in Add-AppPackage

Chris
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual#feedback)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
`Add-AppxPackage` is also a working PowerShell cmdlet, and can install .appx files that are on your machine. :)
