### ISSUE TITLE
PowerShell message for `wsl --set-version 2` refers to wrong webpage

### ISSUE THREAD

**Issue by biegelk** [MicrosoftDocs/WSL#1052]
When you run `wsl --set-default-version 2` or `wsl --set-version 2` in PowerShell, an automatic helper message says:

"For more information on key differences with WSL 2 please visit https://aka.ms/ws12"

This link actually redirects to a [deprecated page about Windows Server](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh801901(v=ws.11)?redirectedfrom=MSDN). Would be helpful to have it point to the right page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Are you sure that that's the link it displays? The link should be: https://aka.ms/wsl2

Could you share a screenshot of what you're seeing please?

**Comment by biegelk** [comment]
Hahaha, I guess the 1 and the l in the terminal font look too similar... my bad then.

![image](https://user-images.githubusercontent.com/1432188/103947735-31105000-50fe-11eb-9244-517431b3cc38.png)

**Comment by biegelk** [comment]
resolved, because I am illiterate
