### ISSUE TITLE
wsl.exe --install not running

### ISSUE THREAD

**Issue by ylr-research** [MicrosoftDocs/WSL#1054]
The first instruction is to run wsl --install and instead of actually running that command it says that command doesn't exist:

```
Invalid command line option: --install
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d <Distro>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

Arguments for managing Windows Subsystem for Linux:

    --export <Distro> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

        Options:
            --version <Version>
                Specifies the version to use for the new distribution.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are currently
                being installed or uninstalled.

            --running
                List only distributions that are currently running.

            --quiet, -q
                Only show distribution names.

            --verbose, -v
                Show detailed information about all distributions.

    --set-default, -s <Distro>
        Sets the distribution as the default.

    --set-default-version <Version>
        Changes the default install version for new distributions.

    --set-version <Distro> <Version>
        Changes the version of the specified distribution.

    --shutdown
        Immediately terminates all running distributions and the WSL 2 lightweight utility virtual machine.

    --terminate, -t <Distro>
        Terminates the specified distribution.

    --unregister <Distro>
        Unregisters the distribution.

    --help
        Display usage information.
```
here's my build number

![image](https://user-images.githubusercontent.com/63487874/104027230-150bbd80-5195-11eb-9a4f-6c1f999619f8.png)

**Comment by ylr-research** [comment]
I got it to work. the correct way is `wsl.exe --install -d Ubuntu`.

**Comment by rhy-ama** [comment]
Doesnt work (``--install`` or ``--install -d Ubuntu``) on 10 N 1909 build 18363.1440

**Comment by mbehnasr** [comment]
i have same issue

**Comment by alistair0adams** [comment]
@rhy-ama, @mbehnasr: From https://docs.microsoft.com/en-us/windows/wsl/install-win10:
Install a preview build of Windows 10 (OS build 20262 or higher).

Thanks @ylr-research

**Comment by rhy-ama** [comment]
@alistair0adams thanks. linked doc was updated to include correct win10 build number since then. @ylr-research please close the issue.

**Comment by ylr-research** [comment]
Thank you all

**Comment by JasonHuang1213** [comment]
Thank you for solving my problem

**Comment by jcksnvllxr80** [comment]
yep thanks for solving my problem too

**Comment by febikamBU** [comment]
> I got it to work. the correct way is `wsl.exe --install -d Ubuntu`.
Thanks so much that worked for me also.

**Comment by ronytesler** [comment]
"wsl --install" still not working and the doc says "wsl --install".

**Comment by jcksnvllxr80** [comment]
I know very weird. But you just need to tell it what distro to use.

**Comment by aeropagz** [comment]
For me it just worked as I started the Powershell with admin rights

**Comment by b-hayes** [comment]
Issue closed but unresolved `wsl --install` still does nothing. Reading direct from MS documentation.

**Comment by michaelgwelch** [comment]
I'm running 21H1 (OS build 1943.928) and `wsl --install` still reports "invalid command line option: --install".

**Comment by Biswa96** [comment]
`wsl --install` command is just shortcut of the steps mentioned here https://docs.microsoft.com/en-us/windows/wsl/install-manual

**Comment by michaelgwelch** [comment]
> `wsl --install` command is just shortcut of the steps mentioned here [docs.microsoft.com/en-us/windows/wsl/install-manual](https://docs.microsoft.com/en-us/windows/wsl/install-manual)

Thanks @Biswa96, I was just looking forward to the new and improved way to install and for whatever reason my version of `wsl` does not appear to be up to date even those my version of Windows exceeds those specified. Even a manual install is not working due to issues with the store. Again, I don't know if I have a bad image from my IT dept or what?

**Comment by Biswa96** [comment]
> Even a manual install is not working due to issues with the store. 

WSL does not require Windows Store access (as of now). You can install distribution using `wsl --import` command or using the launcher exe which comes with the Appx package. There are ways to download Windows Store package without using Windows Store.

**Comment by bacchus101** [comment]
"wsl.exe --install" as is listed in the Microsoft docs, does not do what it is supposed to do per those docs. 
I am completely unable to get ubuntu installed on windows 11 at this point.

**Comment by craigloewen-msft** [comment]
@bacchus101 do these install steps work for you?
https://docs.microsoft.com/en-us/windows/wsl/install-manual

**Comment by gonzalo95050** [comment]
> Doesnt work (`--install` or `--install -d Ubuntu`) on 10 N 1909 build 18363.1440

thnx

**Comment by dwhitla** [comment]
Just uninstall Windoze and install Linux - all problems solved.

**Comment by categrame** [comment]
I had the same problem, i just did
`wsl --update`
then i restarted my computer and i ran
`wsl --install -d Ubuntu`

It works here

**Comment by DamianoSilverhand** [comment]
> I got it to work. the correct way is `wsl.exe --install -d Ubuntu`.

Thanks @ylr-research , this worked for me

**Comment by kgvizr** [comment]
> I got it to work. the correct way is `wsl.exe --install -d Ubuntu`.

Thanks for the help, it worked!

**Comment by JoshWeepie** [comment]
This is outrageous, update the docs lol

**Comment by escherstair** [comment]
I had to run `wsl --update` first of all.
This did the trick for me.
And, after `wsl.exe --install -d Ubuntu-22.04` run successfully.

**Comment by azelezni** [comment]
Nothing works, `wsl.exe --install -d Ubuntu`, WSL has no `--install` `--update` `--shutdown` command.
Easy fix, format and install Ubuntu, problem solved.

**Comment by KrynaAnna** [comment]
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80041002
Error: 0x80041002 (null)
Press any key to continue...

**Comment by Imrancham** [comment]
Running the following command ` wsl --install -d Ubuntu`
 I got:
Installing: Ubuntu
An error occurred during installation. Distribution Name: 'Ubuntu' Error Code: 0x8000ffff
I have tried different commands listed above none of them worde. Any help ??

**Comment by idkthisnik** [comment]
I once turned off Windows updates and many other services because they were unnecessary. 
It turned out that the wsl --install command did not work in any form because of this.
I've tried everything and lost few hours to find solution. Even wsl --install Ubuntu(or other distributive) --web-download didn't work for me. It seems like Ubuntu downloaded but in regedit path HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss it not shows.
So the solution is to turn on Windows Update - [https://answers.microsoft.com/ru-ru/windows/forum/all/%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0/ae5c9a26-ec42-475f-8a3c-31f15eec0b43](here).
I don't think it's best solution so ping me with answer if someone has better way.

**Comment by timgeekzy** [comment]
> @bacchus101 do these install steps work for you?
> https://docs.microsoft.com/en-us/windows/wsl/install-manual

I installed it manually but when I tried running it, it keeps saying this installation package could not be opened contact the application vendor to verify that this is a valid windows installerpackage

**Comment by WASEEM4978** [comment]
it works

**Comment by mhanon** [comment]
This is still happening.

Windows: Version 22H2 (OS Build 19045.4894)

**Issue:** 
`wsl --install` doesnt work and Microsoft pages specify that command https://learn.microsoft.com/en-us/windows/wsl/install
```
wsl --install
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.
    
    Continued...

```

**Details:**
`wsl --update` seems to be broken as well
```
PS C:\Windows\system32> wsl
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

PS C:\Windows\system32> wsl --install
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.
    
    Continued...

PS C:\Windows\system32> wsl --update
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.

PS C:\Windows\system32> wsl -l -v
Windows Subsystem for Linux has no installed distributions.
Use 'wsl.exe --list --online' to list available distributions
and 'wsl.exe --install <Distro>' to install.
Distributions can also be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
Error code: Wsl/WSL_E_DEFAULT_DISTRO_NOT_FOUND

#Only works when specifying a distribution
PS C:\Windows\system32> wsl.exe --install -d Ubuntu
Installing: Ubuntu
Ubuntu has been installed.
Launching Ubuntu...
Installing, this may take a few minutes...
```

**Comment by crramirez** [comment]
This is because wsl is already installed. Once it is installed you need to install a distribution. If --update is not working maybe you need to restart your PC or you don't have access to Microsoft Store. You can use --web-download to bypass the store block.

For example the Microsoft Dev Boxes come with wsl preinstalled and you need to install a distribution
