### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by axferch89** [MicrosoftDocs/WSL#1056]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e953ca-c1d6-68bc-097c-f750ae3d2852
* Version Independent ID: 9ca5e58c-5f05-f36f-242e-8b1bd1d113cb
* Content: [An overview on the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/)
* Content Source: [WSL/index.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/index.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Closing this blank feedback issue. :)
