### ISSUE TITLE
.wslconfig memory lower limit 

### ISSUE THREAD

**Issue by rallets** [MicrosoftDocs/WSL#1059]
Hi, due to constraint in my hw, I would like to set a low memory limit for wsl2, like 512MB and 2 processors, but below 1024MB "Docker Desktop WSL distro" fails in the startup process with `Docker Desktop WSL distro stopped: WSL distro stopped while waiting for Lifecycle server.`
Instead setting 756MB and 4 processors it can start . 
So I'm wondering the lower boundaries for the service, as in the doc page it's not mentioned. Is it possible to add this information?

The lower values in %USERPROFILE%/.wslconfig that allow docker to start are:
[wsl2]
memory=756MB
processors=4

Stacktrace:
```
WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:838
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:943
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:883
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:30
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
rootfs mountiso version-pack
main.setupRootFS
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:394
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:233
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:88
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:838
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:943
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:883
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:30
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
```
Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
There isn't a hard limit for the lower bound here. You'll be limited by what you're running inside of WSL. In this case since you're running Docker Desktop it will evidently run into errors when it has low enough resources. We don't really have a lower limit to add to the docs here! I'll close this issue out since I don't believe there is actionable work here for docs changes, but happy to answer any questions on this issue if you have more :)

**Comment by rallets** [comment]
@craigloewen-msft Thanks for the clarification
