### ISSUE TITLE
set default version for ubuntu fails

### ISSUE THREAD

**Issue by thuy48** [MicrosoftDocs/WSL#1061]
PS C:\Users\papat> wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Running         1
PS C:\Users\papat> wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
PS C:\Users\papat> wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Stopped         1
PS C:\Users\papat>]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
The `wsl --set-default-version 2` command sets your default preference for newly installed distributions. Please use `wsl --set-version Ubuntu 2` to change your specific instance of Ubuntu to version 2! :)

Check the docs here for more info: https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-your-distribution-version-to-wsl-1-or-wsl-2

Thanks!
