### ISSUE TITLE
Link to Ubuntu 20.04 is to .zip file, not .appx file, so installation instructions are wrong

### ISSUE THREAD

**Issue by bhagerty** [MicrosoftDocs/WSL#1062]
The instructions for manually downloading these distros say that clicking on one "will cause the `<distro>.appx` packages to download to a folder of your choosing. Follow the installation instructions to install your downloaded distro(s)." But if you click the link for [Ubuntu 20.04](https://aka.ms/wslubuntu2004) on this page, you get a `.zip` file. The installation instructions ([here](https://docs.microsoft.com/en-us/windows/wsl/install-manual#installing-your-distro)) are only for `.appx` files, so they can't be followed. 

Either the link to Ubuntu 20.04 should be changed to a `.appx` file, or the instructions should tell you what to do with a `.zip` file. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Clicking the link for Ubuntu 20.04 gives me a .appx file. Could you please try again and let me know if you see this same issue?

I believe this is already resolved, so I'll close the issue out for our bookkeeping. Please feel free to reopen it if you still see it!

**Comment by bhagerty** [comment]
Yes, it is resolved. Thanks!

**Comment by gitcnd** [comment]
You can get the .appx file out of the .appxbundle it arrives in by using the 7zip program.

https://aka.ms/wslubuntu2004

it also lets you upgrade to 22.04 ( even if you're using WSL1 )

`sudo do-release-upgrade`

```
$ lsb_release -a 
No LSB modules are available. 
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

$ uname -a
Linux DESKTOP-85QQM2L 4.4.0-17763-Microsoft #2268-Microsoft Thu Oct 07 16:36:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux 

```
