### ISSUE TITLE
`systeminfo | find "System Type"` does not work in some Code Pages

### ISSUE THREAD

**Issue by tzccinct** [MicrosoftDocs/WSL#1063]
On step 4 in install-win10.md,

> If you're not sure what kind of machine you have, open Command Prompt or PowerShell and enter: systeminfo | find "System Type".

This command does not work in some Code Pages, e.g Code Page 932 (Japanese), so to be updated.

First, "System Type" has to be translated into Japanese.

Second, find command behaves tricky on PowerShell for quotations. Double quotations are ignored unexpectedly so you need extra quotations as below:

> \> chcp 437  # The United States' Code Page
> \> systeminfo | find "Microsoft"
> FIND: Parameter format not correct
> \> systeminfo | find '"Microsoft"'
> OS Name:                   Microsoft Windows 10 Home
> OS Manufacturer:           Microsoft Corporation

Third, Japanese characters are gabled like below:
> \> chcp 932  # Japanese Code Page
> \> systeminfo | find '"システム"'  # Not found
> \> systeminfo | find '"?????"'
> OS ?????:          10.0.19041 N/A ??? 19041
> OS ??:                ??????? ?????????
> ...

Because of the second and third issues, even translating "System Type" into Japanese, the command does not work as is. I suggest that let readers execute `systeminfo` command only, and let readers find "System Type" string naively.

**Comment by mattwojo** [comment]
Thanks @tzccinct. I updated the note to clarify the issues you're pointing out. Please reopen if I didn't quite capture it accurately.

**Comment by tzccinct** [comment]
Thanks @mattwojo. The first and second issues I reported are resolved by 06a0162. The third issue is somehow not reproduced on my PC now. So it's OK to close the issue.
