### ISSUE TITLE
Listing available distributions

### ISSUE THREAD

**Issue by GrahamLikesGames** [MicrosoftDocs/WSL#1066]
The page says: "To see a list of available Linux distributions, enter wsl --list --online."

This command does not work for me. It produces the following:

```
PS C:\Users\username> wsl --list --online
--list: unrecognized option: online
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]
```
(followed by additional command line help information, which I won't post here because it's not relevant)

Maybe it should instead direct users to the Store?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
You need to be on Windows build 20262 or higher to use this command! You can check your Windows version by running `ver` in CMD. If you'd like to upgrade to a version that has this command please join the Windows Insiders program, otherwise you can install WSL using the manual steps on the install page :)
