### ISSUE TITLE
Import-Module: Operation is not supported on this platform. (0x80131539)

### ISSUE THREAD

**Issue by JohannesWiesner** [MicrosoftDocs/WSL#1067]
I followed the instructions to [install WSL2 on my windows machine](https://docs.microsoft.com/en-us/windows/wsl/install-win10). However I could not follow the [6th step](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-6---install-your-linux-distribution-of-choice) in this tutorial since my corporate Windows 10 machine does not allow to open the MicroSoft Store. Over [this thread on stackoverflow](https://stackoverflow.com/a/52512523/8792159) I landed on this [Microsoft Page](https://docs.microsoft.com/en-us/windows/wsl/install-manual). When I used the command `Add-AppxPackage .\app_name.appx` as [described in this step](https://docs.microsoft.com/en-us/windows/wsl/install-manual#installing-your-distro) I got the following error:

`Import-Module: Operation is not supported on this platform. (0x80131539)`

This issue is currently being discussed in [this issue on the PowerShell GitHub Page](https://github.com/PowerShell/PowerShell/issues/13138) and seems to have something to do with incompatibility issues using a newer Version of Powershell (I am using version `7.1.0`) and the `Import-Module Appx` command. 

I could solve this issue by first running the command as [described here](https://github.com/PowerShell/PowerShell/issues/13138#issuecomment-677972433): `import-module appx -usewindowspowershell`. 

Maybe the issue and solution should be mentioned on the [Microsoft-Page](https://docs.microsoft.com/en-us/windows/wsl/install-manual#installing-your-distro)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
If you don't mind, try to extract the Appx package as a ZIP file. This page may help https://docs.microsoft.com/en-us/windows/wsl/install-on-server

**Comment by JohannesWiesner** [comment]
The installation worked for me after running the command, but thanks for the link! I only wanted to raise awareness that the documented step [`Installing Your Distro`](https://docs.microsoft.com/en-us/windows/wsl/install-manual#installing-your-distro) might not work when the user uses a newer version of PowerShell, so just as in  https://docs.microsoft.com/en-us/windows/wsl/install-on-server one could add a `Caution` Textbox here

**Comment by craigloewen-msft** [comment]
I added a sentence here to point folks who run into an issue in the right direction:
https://github.com/MicrosoftDocs/WSL/commit/fe75d8d799434fb4ff05532baa7906cd6b625bda

Thank you for the suggestion here! :)
