### ISSUE TITLE
Moved vhdx file to new location by symlink, then got access denied

### ISSUE THREAD

**Issue by VanShelling** [MicrosoftDocs/WSL#1069]
`$ErrorActionPreference = "Stop"

$newLocation = "E:\VMs\WSL2\"

cd ~\AppData\Local\Docker\wsl\data
wsl --shutdown
Optimize-VHD .\ext4.vhdx -Mode Full
mkdir $newLocation -Force
mv ext4.vhdx $newLocation
cd ..
rm data
New-Item -ItemType SymbolicLink -Path "data" -Target $newLocation`

I ran the script and moved my vhdx to another disk. Somebody succeeded but I got an access denied problem.

**Comment by craigloewen-msft** [comment]
Please use `wsl --export` and `wsl --import` to move your WSL files to another drive. Thank you for filing!
