### ISSUE TITLE
Improvement to Accessing WSL 2 from local LAN section

### ISSUE THREAD

**Issue by didorothy** [MicrosoftDocs/WSL#1070]
I just upgraded to WSL2 and needed to have access from outside my computer to one of the WSL2 instances I am running. In reading the documentation here: https://docs.microsoft.com/en-us/windows/wsl/compare-versions#accessing-a-wsl-2-distribution-from-your-local-area-network-lan I could not get it to work as described.

Instead, the command I had to run is as follows:

```
netsh interface portproxy add v4tov4 listenport=8000 listenaddress=0.0.0.0 connectport=8000 connectaddress=localhost
```

The important detail here is that it works when I use 'localhost' as the `connectaddress` and not when I use the IP assigned to the WSL2 instance. I assume that the reason for this is that WSL2 is already redirecting the port on the WSL2 instance to localhost and it cannot or will not redirect to the IP of the WSL2 instance.

Whether you need to completely change the documentation or just update it so that both are options I do not know. I know that it cost me nearly 2.5 hours and a reset to my networking stack to figure it out. I'd like to help other avoid similar headache.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [Comparing WSL 2 and WSL 1](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Pawper** [comment]
@didorothy Hello :wave: Sorry for reviving this after so long, but I'm at a loss. So, after this modification to the `netsh` command, you were able to access from another device? I still cannot get it to work and I'm not sure if I am making a rookie mistake.

I am working on a frontend webpack project on WSL2 and I cannot access it from another device (my phone) on my LAN.

I tried following the instructions provided to no avail. Steps to recreate:
1. My workstation and my phone are connected via the same WiFi network.
2. In WSL, I have an npm script that serves my HTML at `http://0.0.0.0:3000` (using the webpack-dev-server package). I am able to access it fine on Windows using Chrome or Edge at `localhost:3000` or at `XXX.XX.XX.XX:3000` where the Xs are my WSL's private IP (found using `ip -4 addr show eth0` in WSL).
3. In PowerShell, entered `netsh interface portproxy add v4tov4 listenport=3000 listenaddress=0.0.0.0 connectport=3000 connectaddress=` and at the end added `localhost` per your instructions (I had tried my WSL private IP previously)
4. In PowerShell (Windows), entered `ipconfig` and found my IPv4 Address. At first I wasn't sure I got the right one, but I verified it was correct per my Windows WiFi properties. 
5. Entered the Windows private IP address into my phone's browser, with :3000 (the port number) at the end of it. No luck.
    - I also tried changing either/both port numbers to 8000 in the `netsh` command. With `listenport=8000` I could get `localhost:8000` to serve it on Windows but still no luck on my phone. 

For my sanity, I tried using the Live Server extension for VS Code in Windows (not WSL) and I was able to access the site. The live server extension uses local IP 127.0.0.1 & port 5500. On Windows it works at `127.0.0.1:5500` & `localhost:5500` and on my phone it works at `XXX.XX.XX.XX:5500` where the Xs are my Windows private IP. So it definitely seems to be WSL.

Any help appreciated, thanks!

**Comment by didorothy** [comment]
Sorry I’m not sure I can help. I actually had other unrelated issues due to a problem with Intel, Windows, and VLANs plus a frustration with WSL2 eating large quantities of RAM when run for long periods of time and I switched to using VSCode over SSH on a HyperV VM with a fixed amount of RAM and a static local IP. 

When I got this to work I never understood why it worked. It is possible that it worked for an unrelated reason. I was just reading the netsh docs and trying stuff that seemed to make sense. 

If I had to guess, I would also make sure you have opened the port in the windows firewall. I’m pretty sure that I had set a range of ports to be accessible in the firewall as I was working on about 10 different projects that I had to make available for initial review.

**Comment by autozimu** [comment]
Thanks a lot for the hint here!

I've been struggling for days and finally get this to work. What worked for me is this command
```
netsh interface portproxy add v4tov4 listenport=8000 listenaddress=0.0.0.0 connectport=7999 connectaddress=localhost
```
Notice the localhost and different port numbers (7999, 8000).

Those are other combinations tried and failed,
1. `netsh interface portproxy add v4tov4 listenport=8000 listenaddress=0.0.0.0 connectport=8000 connectaddress=localhost`
2. `netsh interface portproxy add v4tov4 listenport=8000 listenaddress=0.0.0.0 connectport=8000 connectaddress=172.18.226.206`

Most likely the behaviour of WSL2 networking (localhost, 127.0.0.1, ...) keeps changing with different versions of Windows. For reference, here is the version I'm using
```
Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎8/‎23/‎2022
OS build	19044.2006
Experience	Windows Feature Experience Pack 120.2212.4180.0
```

**Comment by akshat157** [comment]
@autozimu Thanks to your comment, I was able to make this work on my setup as well! Still unsure about why the difference in port numbers and `connectaddress=localhost` was the dealbreaker.

**Comment by craigloewen-msft** [comment]
The new networking doc that should address this. It's created here: https://learn.microsoft.com/en-us/windows/wsl/networking
