### ISSUE TITLE
WSL2 will require build 18917 

### ISSUE THREAD

**Issue by chantisnake** [MicrosoftDocs/WSL#1072]
It seems like WSL 2 on x86 will require build 18917 or greater according to this post: https://superuser.com/questions/1487354/invalid-command-line-option-set-version

Also, I have a friend who have Build 18362 and failed to install WSL2, she can only get WSL1 installed, and encountered the same problem as stated on the previous link. And after updating her system to the latest, she is able to install WSL2 follow the instruction.

Can anyone confirm this please? Thank you so much. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#manual-installation-steps)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
WSL 2 is supported on Windows 10 version 1903 and higher. That means it's supported on Windows 10 Build 18362 and higher. IF you're running into issues accessing it please take a look at these [troubleshooting steps](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#im-on-windows-10-version-1903-and-i-still-do-not-see-options-for-wsl-2) to help you out! :)
