### ISSUE TITLE
How do the ubuntu under wsl2 access usb devices, such as serial COMX ？

### ISSUE THREAD

**Issue by LinusZhao** [MicrosoftDocs/WSL#1075]
Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

**Comment by mattwojo** [comment]
Hi @LinusZhao - Thanks for contributing this issue. If I'm understanding your question correctly, the answer is that unfortunately WSL2 does not currently support USB flash drives. Learn more here: https://docs.microsoft.com/windows/wsl/wsl2-mount-disk#limitations

This issue in the product development repo is tracking progress on future support: https://github.com/microsoft/WSL/issues/6011

Please re-open if I've misunderstood your question.
Thanks!

**Comment by blockfeed** [comment]
@SeeDeer This may be relevant to you: https://github.com/microsoft/WSL/issues/4322
