### ISSUE TITLE
I will upgrade to wsl 2 when you fix hmr.

### ISSUE THREAD

**Issue by tajeddine-js** [MicrosoftDocs/WSL#1076]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [Comparing WSL 2 and WSL 1](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
I'll close this issue out as I don't see any direct feedback here. What is 'HRM' in this context?

**Comment by tajeddine-js** [comment]
@craigloewen-msft Hot module replacement, Basically when the server refresh on code change. wsl 2 doesn't automaticlly refresh.

**Comment by craigloewen-msft** [comment]
That is possible to do! If you make sure all of your files are in the Linux file system you can get hot module replacement and auto refresh.

**Comment by tajeddine-js** [comment]
Well it's not working as wsl1 then. will wsl2 supports hmr outside Linux file system ?

**Comment by craigloewen-msft** [comment]
Possibly! That work is on the product backlog and is being tracked here: https://github.com/microsoft/WSL/issues/4739

**Comment by tajeddine-js** [comment]
Thanks for your time that resolved my queries, Have a good day !
