### ISSUE TITLE
More than one instance

### ISSUE THREAD

**Issue by kgold2** [MicrosoftDocs/WSL#1083]
Is it possible to install and run more than one instance of a Linux distro.  For example, I have one instance that I don't want to risk corrupting.  So I want to install and run a 2nd instance to experiment.  When I'm done with the experiment, I will just delete that instance.

To be clear, I don't want to run them at the same time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
You have to install the same distribution manually twice with different name using `wsl.exe --install` command.

**Comment by Biswa96** [comment]
You have to install the same distribution manually twice with different name using `wsl.exe --import` command.

**Comment by craigloewen-msft** [comment]
Yes it's possible! I wrote a mini guide on how to do this that you can find here: https://craigloewen-msft.github.io/WSLTipsAndTricks/tip/duplicate-distro.html

**Comment by Biswa96** [comment]
Me too 😊 https://superuser.com/a/1515275/726810
