### ISSUE TITLE
Please create docs about WSL2 networking

### ISSUE THREAD

**Issue by feherzsolt** [MicrosoftDocs/WSL#1086]
Hi,
Could you please create documentation about how the WSL2 networking stack works. It is easy to run into networking issues with WSL2 and it is very hard to find solutions by myself since i was unable to find any detailed information how WSL2 networking stack is built ( how the virtual switch gets its ip, why is it changing, do you nat or how my wsl2 distro can see the network of my host, how do you configure this nat / whatever, how dns should work, how dns requests should work with the default resolv.conf which looks like targeting the ip of the virtual switch, how auto port forwarding works, where to configure, how access to host from distro works, etc)
I think if documentation would be available it would help people to understand the system and solve their networking issues by themselves also reducing the number of WSL2 network related issues.
Please let me know if this documentation exist and i just missed it. (Please also provide links to them)

Thank you in advance.

**Comment by wapmorgan** [comment]
+1

**Comment by craigloewen-msft** [comment]
Created here! https://learn.microsoft.com/en-us/windows/wsl/networking
