### ISSUE TITLE
Please, provide details how to use wslconfig parameter kernelCommandLine

### ISSUE THREAD

**Issue by PavelSosin-320** [MicrosoftDocs/WSL#1089]
The description of wslconfig parameter kernelCommandLine 
kernelCommandLine | string | Blank

is not clear, some examples are needed. as quoted list, comma-separated, etc.  Say I need to disable cgroup V1 or all legacy cgroup controllers. How it affects WSL2 kernel?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Tekh-ops** [comment]
GG

**Comment by PavelSosin-320** [comment]
The following .wslconfig:
_[wsl2]
memory=12GB
processors=4
kernelCommandLine=systemd.unified_cgroup_hierarchy=1_

moved me closer to my goal in using Fedora distro but completely prevents Ubuntu distro from starting - "Catastrophic failure" in few seconds after starting. How to add Kernel log error? Please, help your WSL team to get a usable Linux Kernel startup log!

**Comment by Biswa96** [comment]
> How to add Kernel log error?

Add anyone of these two in `%UserProfile%\.wslconfig` file:

```ini
[wsl2]
debugConsole=true
;debugConsoleLogFile=C:\\MyFiles\\WSL_Console_Log.txt
```

This is for WSL2 only.

**Comment by PavelSosin-320** [comment]
@Biswa96 Thank a lot! Now I see what is the root cause - The distro has "insufficient" wsl.conf file. Its [automount] section is incorrect. C drive is not mounted correctly and the log is full with _ERROR: UtilTranslatePathList:2670: Failed to translate C:\..._ I faced this issue with another distro and easily corrected it because that distro started and I could repair wsl.conf. But, how to repair wsl.conf if distro doesn't start? Could you advise?

**Comment by Biswa96** [comment]
> how to repair wsl.conf if distro doesn't start?

The quick step as I am thinking of right now is to convert WSL2 to WSL1, delete the wsl.conf manually, convert it back to WSL2. But there may be other brilliant ways. As you are testing things, you could install a temporary distribution which can be thrown away quickly.

**Comment by PavelSosin-320** [comment]
@Biswa96 Thanks! My Ubuntu Gorilla Groovy built from MS Ubuntu 20.04 is alive again. I  didn't find the reason why the "Catastrophic failure" appeared in the WSL startup log. There were some Errors during the system boot sequence after Kernel has been initialized but nothing "fatal" or Catastrophic".  But, anyway, the published documentation is insufficient for the proper configuration and troubleshooting. The wsl. conf along with generated hosts and resolv.conf files are obvious points-of-failure. Any small typo error can prevent Distro from starting. When it happens these files are inaccessible.
