### ISSUE TITLE
How to change default user without lxrun

### ISSUE THREAD

**Issue by Banananoops** [MicrosoftDocs/WSL#1097]
Please explain how to change the default user now that `lxrun` is deprecated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Create and update user accounts for Linux distributions](https://docs.microsoft.com/en-us/windows/wsl/user-support)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/user-support.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
You can use the `user.default` option in /etc/wsl.conf

Add this to your /etc/wsl.conf file:
```
[user]
default=<yourUsernamegoeshere>
```

More info here: https://docs.microsoft.com/en-us/windows/wsl/wsl-config#user
