### ISSUE TITLE
help

### ISSUE THREAD

**Issue by NadaAlyousef92** [MicrosoftDocs/WSL#1098]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 782a4458-6a56-63e5-efaf-d1868762ed06
* Version Independent ID: 312f71d9-db7d-52a5-b03d-9b6d4c680c2a
* Content: [Get started using VS Code with Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode#feedback)
* Content Source: [WSL/tutorials/wsl-vscode.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-vscode.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
There isn't enough info here for us to help with! I'll close the issue, please feel free to add any more info you have here and reopen it if you have a specific question. Thanks!
