### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by Kubo-SVK** [MicrosoftDocs/WSL#1101]
Link to microsoft store in 6th step is not working. Opens Store app but app stays blank and after a while there is message saying, that something went wrong on your side

EDIT:
Its this one https://aka.ms/wslstore

---
#### Podrobnosti o dokumente

⚠ *Neupravujte túto sekciu. Vyžaduje sa pre lokalitu docs.microsoft.com ➟ prepojenie na problém v službe GitHub.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/sk-sk/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
If you try this again now, is it fixed? 

Closing this issue as the link is fixed for me!
