### ISSUE TITLE
Illogical link names -> hard to find updated link to download

### ISSUE THREAD

**Issue by ssubraman** [MicrosoftDocs/WSL#1105]
Currently there doesn't seem to be any kind of logical connection between the Store URI and the manual download link.
For example Ubuntu 20.04 LTS, in Store part of its URL is "ubuntu-2004-lts".
But the manual download link name is wslubuntu2004 ?!?

So whenever something is updated in the store, it's not quite possible to make a logical guess as to the manual download link. And if the manual download link page should not have been updated, download is not possible by MS mechanisms*.
Could you please harmonize the link names?

( * there are 3rd party services resolving Store links into the actual download links, but one shouldn't have to resolve to this kind of hacks to download official MS content.)

Or better yet simply declare the manual download link directly on the Store page, as even the strictest organization (where Store might not be available to users) would probably let people access the Store web page.

This rant was inspired by the dreadful jungle of trying to download and install Ubuntu 20.04 LTS, Kali, Alpine, and Windows Terminal without Store access; for WT it turned out not even installing winget is enough, it seems to still fail if there's no Store as Windows Terminal icon in Start menu does nothing.
So my Windows Terminal is only an extracted folder of the original .msixbundle now, but seems to work.
This could be _a_lot_ smoother.

**Comment by craigloewen-msft** [comment]
Please see this link to download WSL distros not using the Store: https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions
