### ISSUE TITLE
Windows Insiders: Command not found wsl.exe --install

### ISSUE THREAD

**Issue by gbm** [MicrosoftDocs/WSL#1108]
I got a command not found for 
wsl.exe --install 
in admin cmd
with windows insiders documented process- my OS build not high enough so assume this the reason.  
Joined the windows insiders dev track and did an update but guess possible pro/home issue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
It does sound like your Windows build number isn't high enough. Please make sure you're on the right build to try this command, there are instructions on the docs page on how to do so.

**Comment by gbm** [comment]
OK thanks Craig - re-running windows update and looks like I am taking 21322.1000. I did run windows update according to instructions here https://insider.windows.com/en-us/for-business-getting-started
From memory it didn't pick up an update that I noticed - new to program so guess I missed that. 
I would suggest add a troubleshooting section - command not found : check build number.

Question: Is there a delay between joining the insiders program and windows update having permissions to pull dev builds down? If busy don't worry about answering this.

**Comment by craigloewen-msft** [comment]
Yes there is a slight delay from when you hit "Give me Windows Insiders builds" and then to when you actually get them :)

**Comment by gbm** [comment]
Also suggest mention troubleshooting section in the text here 
https://docs.microsoft.com/en-us/windows/wsl/install-win10
Not that obvious out there on the left bar - I skipped straight to manual instructions. 

Could mention delay between sign up and getting access to dev builds on getting started https://insider.windows.com/en-us/for-business-getting-started
"Go and make yourself a cup of tea" - something like that. Between steps 5 and 6. 

Also please make the text  "make sure your data settings are set to the right level," bold as in step 6 blue text - eye skips over step 5 otherwise

**Comment by gbm** [comment]
Sorry Craig throwing lots of non WSL stuff at you :)
But do you know what would be nice would be a teams channel or channels - even if it wasn't with MS employees (I guess they would admin) - but you know a bit of chit chat among testers. Build morale - windows too important etc. May be security implications of sharing there - but assume you have thoughts of all this :) Maybe there is one and it's just not jumping out at me. Anyway I shall get off this closed ticket and find a better feedback channel. Loved the quadcopter.

**Comment by gbm** [comment]
Thanks @craigloewen-msft those pages look good. I specifically in this case meant channel(s) for Windows Insiders dev testers - as opposed to WSL pages :) I guess we can't get access to TFS as a ticketing system - which is I think correct from an information security point of view - but I wonder if there is some way that Windows Internals Devs can chat in some MS moderated format - in a form beyond the reporting of issues via the Feedback Hub. I guess I could open a feature request via Feedback Hub but you would have more traction. I think it could be useful from a community building point of view.
