### ISSUE TITLE
Using this pages cmd line process Killed my hard drive.!! Win 10 wont boot. PC doesnt see hard Drive now. Great!

### ISSUE THREAD

**Issue by ormailbox1** [MicrosoftDocs/WSL#1111]
WHO MADE THIS PAGE??

 After running the command line from the page to enable the sub system for windows. I'm no programmer so I dont know what the command line does per say but I know what happened after running it from the admin command prompt. NO MORE PC. Now my machine doesn't boot because it doesn't recognize its own hardware., The hp pavilion laptop uns a hard disc/memory check instead of booting the result being that it doesn't see the hard drive any long. If ANYONE has some insight as to how recover my hard drive I would appreciate it. My supposed dual boot machine is presently a no boot machine. Is there some way to recover my Data at least? Lastly, I had just updated my windows to whatever build number was suggested ver 20 something. Any one with the power of knowledge in this area please speak your peace. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Joshua-Ashton** [comment]
lol

**Comment by craigloewen-msft** [comment]
Hi @ormailbox1 , this is a Hypervisor related problem that we are tracking on this thread: https://github.com/microsoft/WSL/issues/4784

Could you please follow the instructions and discussion there? There are some workarounds on how to enable yourself to boot again, and we are working on a fix.

Thank you!
