### ISSUE TITLE
WSL2 msi installer cannot connect

### ISSUE THREAD

**Issue by tristaaan** [MicrosoftDocs/WSL#1114]
For Step 4, the link to the MSI installer seems to be down

https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This seems up to me now, are you able to access this file now?

**Comment by tristaaan** [comment]
Yes, thank you!
