### ISSUE TITLE
open file in non-block mode

### ISSUE THREAD

**Issue by woshiZS** [MicrosoftDocs/WSL#1115]
[Enter feedback here]
I am new to wsl, and I want to open markdown file directly in my wsl, so I append 
```bash
alias typora = '$myPathtToTypora/typora.exe'
```
in my .bashrc file.
But I find that as long as you open md file in wsl, you can't enter other shell commands cause that shell is blocked(I guess).
After I closed the md file, it is okay for me to enter commands again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1281696-20d8-9bf7-5b7b-0a1d85a0190f
* Version Independent ID: 760f023a-2f59-a18f-d69a-44331c72e30d
* Content: [File Permissions](https://docs.microsoft.com/en-us/windows/wsl/file-permissions)
* Content Source: [WSL/file-permissions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/file-permissions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This is working as expected. If you run GUI applications in Linux from the command line (Like `nautilus` for example) in general they keep the file handle open in your Terminal Window. 

If you'd like to change it, I'd recommend changing your alias to be:  
`alias typora = '$myPathToTypora/typora.exe &'`

This will make it run in the background and free up your shell for you :)

**Comment by woshiZS** [comment]
thanks a lot.
