### ISSUE TITLE
Incorrect and misleading information on WSL2

### ISSUE THREAD

**Issue by phgmacedo** [MicrosoftDocs/WSL#1116]
On the page, it says WSL2 has a "small resource footprint" and uses a "smaller amount of memory". 

These are misleading statements. 

WSL2 uses lots of RAM, much more than WSL1, up to 8GB or 50% of available memory, and frequently does not free unused memory. 

I get that people who worked on WSL2 want to advertise it, but microsoft should at least be honest. 

There's also a section of "Exceptions for using WSL 1 rather than WSL 2", where there should be the use case of "You don't have lots of RAM to waste".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [Comparing WSL 2 and WSL 1](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
I've removed the 'Smaller memory usage in WSL 2' paragraph. The table at the top indicates that both WSL 2 and WSL 1 have smaller memory foot prints compared to other Linux solutions (like running a desktop VM etc.) so I've left that as is. This is a great suggestion, thanks for the comment!

https://github.com/MicrosoftDocs/WSL/commit/c11f03754b78ed9d22c60ce0c911b651fadc41a5

**Comment by phgmacedo** [comment]
> The table at the top indicates that both WSL 2 and WSL 1 have smaller memory foot prints compared to other Linux solutions (like running a desktop VM etc.)  

No it doesn't.

The table is a comparison between WSL2 and WSL1. 

If it meant that WSL1 and WSL1 have "smaller foot prints compared to other Linux solutions", then it would be written that they have "smaller footprints _compared to other Linux solutions_".

**Comment by craigloewen-msft** [comment]
Those are good points. I've added in some clarity to the points above in this commit:

https://github.com/MicrosoftDocs/WSL/commit/fc2080e418bb2ec9fe610acaf6fe148b1a11fea5

**Comment by phgmacedo** [comment]
@craigloewen-msft much clearer. 

Also, minor issue, the word experience in the new text has a typo.

**Comment by craigloewen-msft** [comment]
![Doh!](https://media.giphy.com/media/xT5LMzIK1AdZJ4cYW4/giphy.gif) 
Typing too fast :) Thanks again.

https://github.com/MicrosoftDocs/WSL/commit/e783507bf365ecae613ee3d8f95dad2da3af31c1
