### ISSUE TITLE
typo on this page

### ISSUE THREAD

**Issue by DrippingDumpsterJuice** [MicrosoftDocs/WSL#1117]
a few sections refer the reader to enter a linux command in powershell (blkid and lsblk) but i think the intention was to execute that command using wsl in front of it or from a linux terminal? i'm not fluent in this stuff, just giving feedback. keep up the good work!

https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e255b0-71c7-adc6-cac0-6df3b76a971f
* Version Independent ID: a9d73ca3-7026-5b5a-f3fe-3511e976cde4
* Content: [Get started mounting a Linux disk in WSL 2 (preview)](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk)
* Content Source: [WSL/wsl2-mount-disk.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-mount-disk.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Fixed here as part of this PR :) Thanks for the spot here!

https://github.com/MicrosoftDocs/WSL/commit/d0db4347127e2a580bca3e799eb3fff1fd4be721
