### ISSUE TITLE
WSL.conf docs introduces two sections but describes four

### ISSUE THREAD

**Issue by stvhwrd** [MicrosoftDocs/WSL#1118]
From: https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configuration-options

"Configuration Options

In keeping with .ini conventions, keys are declared under a section.

**WSL supports two sections: automount and network.**"

Should this, instead, be:

"Configuration Options

In keeping with .ini conventions, keys are declared under a section.

**WSL supports four sections: automount, network, interop, and user.**"

?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Great comment! Fixed here: https://github.com/MicrosoftDocs/WSL/commit/4c3101faeddf8ef6c484efbb1aa06ea3c993702d

Thank you!
