### ISSUE TITLE
WSL2 Kernel update link broken in docs

### ISSUE THREAD

**Issue by enisnazif** [MicrosoftDocs/WSL#1119]
In step 4 of the WSL2 install guide: https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package, the link appears to be broken:

https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

**Comment by Biswa96** [comment]
Works here. What error did you see?
