### ISSUE TITLE
Global wslconfig setting

### ISSUE THREAD

**Issue by mbesida** [MicrosoftDocs/WSL#1120]
It is said on [this page](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig) that ` .wslconfig` can be configured in  `C:\Users\<yourUserName>\.wslconfig`. But it is not mentioned that this is valid only for Windows 10 Pro/Enterprise. For Home edition it doen't work. I've done `wsl --shutdown` after creating that file, but after starting wsl again it doesn't pickup the new configuration for memory availabale for wsl
My system is of version **20H2(OS build 19042.867)**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This setting should work for Home edition as well!

Could you please share:
* Your Windows build number
* Your `.wslconfig` file
* And the result of `free -h` in WSL?

Thanks!

**Comment by mbesida** [comment]
Apologize, I misspelled the `GB`: my file has `memory=8Gb` instead of `memory=8GB`. Closing the issue
