### ISSUE TITLE
Unsupported feature requests / Backlog items - Please No!!? Rant!

### ISSUE THREAD

**Issue by salsysd** [MicrosoftDocs/WSL#1124]
Hi, was just reading up on wsl distributing and packaging! Super cool stuff! love it! But I couldn't help but noticed at the bottom of the [document ](https://url.sal.sh/mKpM60) these unsupported/feature requests...

- ~~Synchronizing the user inside WSL with the Windows user on the host machine~~
- Managing updates and patching of the Linux distributions and packages using Windows tools
- ~~Having Windows update also update WSL distro contents~~
- Controlling which distributions users in your Enterprise can access
- Running mandatory services (logging or monitoring) inside of WSL
- Monitoring Linux instances using Windows configuration manager tools such as SCCM or Intune
- ~~McAfee support~~

Now I am pretty new to WSL but not linux by any means, in fact WSL is making me become a Windows fan! First time ever! I am purely a *nix user and developer. Anyway, please for the love of *** can you dismiss the items above!? McAfee support?? Really WTF? why? Not all the items in the list, but just the items marked out...
I can probably think of 10 enterprise feature requests off the top of my mind that are better suited for WSL... Now I am basically just ranting out loud but if I had to guess if these were put thru a democratic process of voting (of sort), my requests would become quite favorable...

anyway, thanks for WSL developments and enterprise support! you guys rock!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4e9ad4b-3ca1-d8b9-23e3-fdfb8a232428
* Version Independent ID: 9da3bc76-b6c2-9b90-afc3-3c8539359271
* Content: [WSL for Enterprise](https://docs.microsoft.com/en-us/windows/wsl/enterprise)
* Content Source: [WSL/enterprise.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/enterprise.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This list was created based on direct customer requests that we've had! We call them out to let them know that these are unsupported. Overall these feature requests could come in a huge variety of ways, and we may prioritize other features over these ones in the future.

**Comment by craigloewen-msft** [comment]
And thanks so much for the kind words!

I've closed the issue for our own bookkeeping as I dont' think there's any actionable items for us here.
