### ISSUE TITLE
Documentation's suggested --set-default-version command missing required Distro parameter

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [MicrosoftDocs/WSL#1127]
I believe Step 5 on this page has an incorrect command.

as shown:
```
Step 5 - Set WSL 2 as your default version
Open PowerShell and run this command to set WSL 2 as the default version when installing a new Linux distribution:

PowerShell Copy
wsl --set-default-version 2
```

On my machine, `wsl --set-default-version 2` did nothing, while `wsl --set-default-version Ubuntu-20.04 2` successfully converted my wsl 20.04 distro from wsl1 to wsl2. running `wsl --help` from powershell also suggests the distro is needed by the `--set-default-version` subcommand: `--set-version <Distro> <Version>` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
`wsl --set-default-version 2` makes *any new distro you install be installed as a WSL 2 distro*.

You can use `wsl --set-version Ubuntu 2` to actively change your already installed distros. 

We tried to make this clear above when we say 'the default version when installing a new Linux distribution', and then later in that page go into details of `wsl --set-version`. 

https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-your-distribution-version-to-wsl-1-or-wsl-2

I'll close this issue out for our bookkeeping as I don't think we have any actionable items to change the docs here, but happy to keep discussing it. :)
