### ISSUE TITLE
Virtual Machine Platform step not feasible.

### ISSUE THREAD

**Issue by ruffyleaf** [MicrosoftDocs/WSL#1130]
Enabling "Virtual Machine Platform" seems to cause a BSOD on restart. If I just enable WSL, everything is ok.

C:\Users\ruffy>systeminfo.exe

Host Name:                 DESKTOP-0HS7EVQ
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          ruffyleaf@hotmail.com
Registered Organization:   N/A
Product ID:                00330-50000-00000-AAOEM
Original Install Date:     21/3/2021, 2:31:52 am
System Boot Time:          21/3/2021, 10:02:47 pm
System Manufacturer:       AFTERSHOCK PC
System Model:              Apex-15r lite
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 23 Model 96 Stepping 1 AuthenticAMD ~2900 Mhz
BIOS Version:              American Megatrends Inc. N.1.16AFT03, 31/8/2020
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+08:00) Kuala Lumpur, Singapore
Total Physical Memory:     15,789 MB
Available Physical Memory: 12,789 MB
Virtual Memory: Max Size:  18,733 MB
Virtual Memory: Available: 14,424 MB
Virtual Memory: In Use:    4,309 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-0HS7EVQ
Hotfix(s):                 7 Hotfix(s) Installed.
                           [01]: KB4601554
                           [02]: KB4562830
                           [03]: KB4577586
                           [04]: KB4580325
                           [05]: KB4589212
                           [06]: KB5001567
                           [07]: KB5000858
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6 AX200 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.86.1
                                 IP address(es)
                                 [01]: 192.168.86.168
                                 [02]: fe80::a07f:2f10:f799:64e8
                           [02]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
product

**Comment by craigloewen-msft** [comment]
Hi! This issue is a technical issue related to WSL. This repo is just for managing issues relating specifically to the WSL docs pages. If you're still experiencing this issue please file it at https://github.com/microsoft/WSL , the relevant info there will help us give you an actionable solution.

Thank you for filing!
