### ISSUE TITLE
Install a WSL2 distro to a data drive

### ISSUE THREAD

**Issue by kurienmathew** [MicrosoftDocs/WSL#1131]
My system drive (C:) has very little free space. How can I install a distro (for eg Ubuntu 20.04) to the data (D:) drive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Here's an informal guide: https://craigloewen-msft.github.io/WSLTipsAndTricks/tip/install-different-drive.html
