### ISSUE TITLE
Add more details to the release notes. 

### ISSUE THREAD

**Issue by WSLUser** [MicrosoftDocs/WSL#1132]
[Enter feedback here]

Currently, there is very little information actually stating what config changes get made or custom updates to the kernel. There should also be a reference link in each release to the offiicial kernel release notes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 657ce15d-3385-5d58-d836-2d147266e6bd
* Version Independent ID: bab7575b-205e-1700-2d7c-ff14c6cf4797
* Content: [Release Notes for Windows Subsystem for Linux kernel](https://docs.microsoft.com/en-us/windows/wsl/kernel-release-notes)
* Content Source: [WSL/kernel-release-notes.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/kernel-release-notes.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Full release notes can be found here: https://github.com/microsoft/wsl
