### ISSUE TITLE
Questions about disk mounting

### ISSUE THREAD

**Issue by ioweb-gr** [MicrosoftDocs/WSL#1136]
I was thinking of mounting an ext4 disk via wsl for usage in my projects. It is my understanding that if I mount a disk like this, it should work like the home directory or a mounted vhd in terms of speed right? 

Afterwards the disk should be accessible via the \\wsl$.

However what happens if the mounted disk is also mounted by windows using an ext4 driver like ext2fsd or Paragon's ext4 driver. Will both systems get native access to the disk or will the windows system be prevented from accessing the drive?

Will the changes be synced between the filesystem in each OS? 

What's the expected behaviour and the possible problems in such a setup?

**Comment by mattwojo** [comment]
Thank you for addressing this issue @ioweb-gr! I'll add a note in the docs to reflect this. If you'd like to file this as an issue in the WSL product development repo as something for the dev team to work on, you can do so here: https://github.com/microsoft/WSL/issues

It looks like this is a semi-related issue relating to only being able to access ext4 mounted drive as admin: https://github.com/microsoft/WSL/issues/6270
