### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by eaang** [MicrosoftDocs/WSL#1141]
Hi!
![image](https://user-images.githubusercontent.com/10687848/113560270-50534680-9635-11eb-8f80-f756ffcbde76.png)
Just wanted to mention a typo in the above image - it says 'inid.d' instead of 'init.d'. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 080023f0-501e-b638-b22c-9d2cbcbdb66a
* Version Independent ID: 88516d79-15be-0cf2-bb25-d20a17d1a37e
* Content: [Get started using MySQL MongoDB, PostgreSQL, SQLite, Microsoft SQL Server, or Redis to set up a database on Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database)
* Content Source: [WSL/tutorials/wsl-database.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-database.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by rhorber** [comment]
I took the liberty to make a PR. Thanks @eaang!

**Comment by craigloewen-msft** [comment]
Merged in! Thanks folks!
