### ISSUE TITLE
username

### ISSUE THREAD

**Issue by Josufst** [MicrosoftDocs/WSL#1145]
It is unclear to me what the rules are for the regex to form a username
[Voer hier feedback in]

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Create and update user accounts for Linux distributions](https://docs.microsoft.com/nl-nl/windows/wsl/user-support)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/user-support.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
WSL is running actual Linux distros... so it depends on the distribution that you're running, but user names are supported the same in WSL as they would be in whatever Linux distro you're using.

These might help? 

https://unix.stackexchange.com/questions/157426/what-is-the-regex-to-validate-linux-users

https://serverfault.com/questions/73084/what-characters-should-i-use-or-not-use-in-usernames-on-linux
