### ISSUE TITLE
WSL2 with 3rd party virtualization 

### ISSUE THREAD

**Issue by Tharindu-h** [MicrosoftDocs/WSL#1150]
So, I've been trying to find a way to use WSL2 as well as virtualbox and after trying many things I've come to the conclusion that as if right now virtualbox and wsl2 cannot co-exist...(except for the few people here that claims they had success doing so.)
However, VMware workstation CAN co-exist with wsl2! given that u have windows hypervisor platform installed.
I knew that VMware can co-exist but it was my understanding that VMware workstation was a paid application. But turns out there's a free version as well. Here's the download link https://www.vmware.com/ca/products/workstation-player/workstation-player-evaluation.html
Figured I'd make this post since I was struggling to find a way to have both wsl2 and a virtual machine running and wasted a lot of time figuring out how to get virtualbox to run not knowing that VMware had a free version.

**Comment by mattwojo** [comment]
Hi @Tharindu-h - Thanks for filing this issue. I'm going to close it as a duplicate to this thread discussing the same issue: https://github.com/MicrosoftDocs/WSL/issues/798

However, if there is something specific that you feel would be helpful to add to the FAQs about VirtualBox support, please feel welcome to reopen or submit a pull request.
