### ISSUE TITLE
add note to ensure that virtualization is enabled in BIOS when setting up WSL2

### ISSUE THREAD

**Issue by prcantwell** [MicrosoftDocs/WSL#1152]
I ran into a problem during Step 4 on this page while setting up Ubuntu for WSL2, and I'm wondering if you can add an instruction in Step 4 (or Step 3) to emphasize the importance of ensuring that virtualization is enabled in BIOS before running the Linux kernel update package?   I know that Step 3 mentions that your machine needs virtualization capability, so I should probably have checked to see if it was on, but I didn't.  Perhaps an explicit instruction to check would be helpful here.

This was a tough problem to solve, because after I ran Linux kernel update package the first time, everything seemed fine (no error message), but I wasn't able to set Ubuntu to version 2.  No error message while attempting to do that either, it just didn't work, and the only message it gave me referred me to a web page, maybe this one, but it didn't explain why.  I can't remember the exact message now, but it definitely didn't give me a clue that I should enable virtualization in BIOS.  Enabling it fixed the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This is fixed in the latest! Thank you for filing this!
