### ISSUE TITLE
How can I undo the WSL2 Linux kernel update?

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [MicrosoftDocs/WSL#1153]
I've been using WSL1 for quite some time now and recently tried to follow the instructions here to upgrade to WSL2:

https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package

However, I discovered that my OS build does not support WSL2, and my Windows Update doesn't appear to be working. The docs are actually misleading in this respect and should probably be updated since this is not true:

> For x64 systems: Version 1903 or higher, with Build 18362 or higher.

Anyway, I got all the way through Step 4 and downloaded the `wsl_update_x64.msi` package. Did the install and restarted my system.

WSL1 is still working fine generally, but it's causing issues with things like Webpack that I previously did not run into. My only assumption is that the kernel update broke something.

Is there any way I can roll that back? (Just to be clear, I'm still on WSL1, not 2.)

**Comment by zurgeg** [comment]
Sure! Use `wsl --set-version <Distro> <1/2>`

**Comment by AleksandrHovhannisyan** [comment]
Turned out to be an issue unrelated to the WSL update.
