### ISSUE TITLE
Change default user on custom named WSL instance not documented

### ISSUE THREAD

**Issue by visma-henriklarsen** [MicrosoftDocs/WSL#1154]
The  following scenario seems not to be  documented. 

Using wsl export/import I have cloned an Ubuntu-18.04 distro. I can see it using "ws -l":
Ubuntu-18.04 (Default)
Ubuntu-18.04-2

When I run Ubuntu-18.04 I get a prompt as my custom user MyUser
When I run Ubuntu-18.04-2 I get a prompt as root

I would like to permanently change the default user on Ubuntu-18.04-2 to MyUser. 

I can start the Ubuntu-18.04-2 instance as MyUser using
"wsl -u MyUser -d Ubuntu-18.04-2"

I can change default user on the Ubuntu-18.04 (Default) instance using:
ubuntu1804 config --default-user SomeUser

I cannot change default user on the cloned instance:
ubuntu1804-2 config --default-user MyUser

Is this not supported or not documented? I cannot find any documentation that allows me to do what I want to do in the above situation.

I've been studying this documentation:

https://docs.microsoft.com/en-us/windows/wsl/user-support
https://docs.microsoft.com/en-us/windows/wsl/wsl-config
https://social.technet.microsoft.com/Forums/en-US/89081275-04e3-4b34-8714-baba9836ebc9/ubuntu-1804-distribution-on-wsl-fail-to-set-default-user-via-config-command?forum=win10itprogeneral
https://www.tenforums.com/tutorials/128152-set-default-user-windows-subsystem-linux-distro-windows-10-a.html

**Comment by craigloewen-msft** [comment]
This is documented here:
https://docs.microsoft.com/en-us/windows/wsl/wsl-config#user-settings

Thanks for filing!
