### ISSUE TITLE
Command wsl --list --online is unrecognized

### ISSUE THREAD

**Issue by nickph7** [MicrosoftDocs/WSL#1162]
In the documentation, it says to enter the command `wsl --list --online` to see all available distribution. However when entering the command, I get `--list: unrecognized option: online`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Likely you are not on the correct Windows version. Please double check your Windows version before running that command!

**Comment by leon001** [comment]
I come across the same issue as nickph7 did. I am using Windows 11 inside with the latest updates.  The result is:
 wsl --list --online
The server name or address could not be resolved
