### ISSUE TITLE
"Change the default user for a distribution" section should mention /etc/wsl.conf

### ISSUE THREAD

**Issue by wombatonfire** [MicrosoftDocs/WSL#1164]
The method of changing the default user for a distribution, described in the "Change the default user for a distribution" section, will not work for imported distributions, because these distributions do not have an executable launcher. A related discussion can be found [here](https://github.com/microsoft/WSL/issues/3974).

In build 18980 the ability to set the default user was added to /etc/wsl.conf ([source](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18980)).

It would be nice to describe this method - which works for **any** distribution - in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks for contributing this issue @wombatonfire. I just added a warning to the Change default user instructions that points this out.
