### ISSUE TITLE
Is there an anticipated version of windows 10 this is going to be included in (non preview)?

### ISSUE THREAD

**Issue by proludiojon** [MicrosoftDocs/WSL#1167]
We are developing a product that needs to read ext2 and ext4 drives native to our .net app and web service.
In the preview version, it works great.
So now my team in trying to figure out how long we have to wait to use it in the real world, or if we need to come up with some sort of bridge technology.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e255b0-71c7-adc6-cac0-6df3b76a971f
* Version Independent ID: a9d73ca3-7026-5b5a-f3fe-3511e976cde4
* Content: [Get started mounting a Linux disk in WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk)
* Content Source: [WSL/wsl2-mount-disk.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-mount-disk.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hi @proludiojon - Thanks for your question. I think it would be better asked in the WSL product repo issues however: https://github.com/microsoft/WSL/issues/

I don't have this sort of release date information, but the product team over there may be able to help you(?). It looks like there is already an issue thread speific to ext4: https://github.com/microsoft/WSL/issues/6392

We would love to learn more about how you use the WSL disk mounting!

**Comment by proludiojon** [comment]
I would be glad to tell you more about how we are using it.
What is the best way offline (since it is still a product in development)

**Comment by craigloewen-msft** [comment]
This will be available in the next major Windows version!

**Comment by proludiojon** [comment]
Thanks @craigloewen-msft.
I small follow up question then.

"Windows 10 21H1, for the uninitiated, is a service pack-style update with the focus entirely on quality improvements and bug fixes".  I assume this is considered the next major version?  Or because it is not really supposed to contain new features, does it wait until fall?

**Comment by craigloewen-msft** [comment]
21H1 is not a next major Windows version, it's a minor build upgrade.

**Comment by proludiojon** [comment]
So reading into that, probably not until at least October 2021ish.
Unfortunately too long for me to wait for this mounting use, as I need it sooner (darn, because it works so well, and I dont have to pay and support a separate piece of software with other ext mounting solutions).

**Comment by tanguy-e** [comment]
Is there something new about this. I use win11 21H2 build 22000.348 without this feature.
