### ISSUE TITLE
Need option to install distro without Microsoft Store

### ISSUE THREAD

**Issue by Deduction42** [MicrosoftDocs/WSL#1168]
In many cases, Microsoft Store might not be available. This case needs to be dealt with.

Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

**Comment by Biswa96** [comment]
There is `wsl.exe --install` command to install online. List of distribution should be in `wsl.exe --list --online`.

**Comment by Repko** [comment]
For me, wsl --list --online does not work so my workaround is here
You can download the Distro you want from the link:
https://docs.microsoft.com/en-us/windows/wsl/install-manual

Change extension from .appx to .zip and extract to any location let's say C:\WSL
Start PowerShell or cmd.exe and go to that location
cd \wsl\distro...
After that, just your Distribution .exe file and installation will start.'s
You will be asked to create the user and set the password.

![image](https://user-images.githubusercontent.com/13117944/117860956-caa46580-b288-11eb-9bbd-9aa955c54442.png)

**Comment by craigloewen-msft** [comment]
This is added in the latest `wsl --install` version, there is a `--web-download` option for this in Insiders. Thank you for filing!
