### ISSUE TITLE
Step 3 instructions

### ISSUE THREAD

**Issue by ctaylor-ntirety** [MicrosoftDocs/WSL#1171]
[Step Three **Restart**   needs to be **BOLDER LARGER AND HIGHLIGHTED !** ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by frank-dutmers** [comment]
I agree.

**Comment by craigloewen-msft** [comment]
This is clearer in the latest and we added an inproduct ask for restart as well. Thanks for filing this!
