### ISSUE TITLE
Need clearer documentation on how to move WSL filesystem to another drive

### ISSUE THREAD

**Issue by stevekm** [MicrosoftDocs/WSL#1175]
The current docs give a nice overview of how to [increase the size of your WSL virtual hard disk](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#expanding-the-size-of-your-wsl-2-virtual-hard-disk). However, if you are at the point where you are needing more space, then you're probably considering moving WSL to a different larger drive as well. Its common these days to use a relatively small SSD as an OS boot disk so I suspect a lot of people might not have >256GB available on their Windows install drive which WSL installs into by default.

A quick Google search gives some [possible methods](https://stackoverflow.com/questions/38779801/move-wsl-bash-on-windows-root-filesystem-to-another-hard-drive), but the results are often conflicting, confusing, or contradictory since it seems like this feature might have changed over the years. So its not clear what is the current official way you should go about doing this.

I did not see any other official WSL docs on how to do this, so it would be really helpful to have. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [Comparing WSL 1 and WSL 2](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#feedback)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
I've written up a quick guide on an informal and unofficial "Tips and Tricks" site for WSL that may immediately unblock you: https://craigloewen-msft.github.io/WSLTipsAndTricks/tip/install-different-drive.html

I'll see if I can think of a good way to put this guidance on the official docs. Thanks!
