### ISSUE TITLE
WSL linux kernel

### ISSUE THREAD

**Issue by samseyi672** [MicrosoftDocs/WSL#1179]
Hello,
   This  guide  is good  but I cannot seem to  download the linux kernel update installer for wsl2 .As in, the site is not reachable.
So,  please  what  is the  link to download the installer because I cannot run docker  on my desktop as it is .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Querynalhabsyi** [comment]
do you mean? https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi 
I can download the link

**Comment by craigloewen-msft** [comment]
This link is reachable for me as well. If you are still having problems consider trying to install the store Version of WSL from here: https://aka.ms/wslstorepage
