### ISSUE TITLE
Why is USB not mentioned

### ISSUE THREAD

**Issue by gmos** [MicrosoftDocs/WSL#1180]
Still no USB support for WSL2.  This is a major difference with WSL1 that should be mentionned here.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 980273af-8e7f-23df-a68d-92895a49e100
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [FAQ's about Windows Subsystem for Linux 2](https://docs.microsoft.com/en-gb/windows/wsl/wsl2-faq)
* Content Source: [WSL/wsl2-faq.yml](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-faq.yml)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @gmos. 

Closing as it looks like it's called out that USB is unsupported here: https://docs.microsoft.com/en-gb/windows/wsl/wsl2-faq#can-i-access-the-gpu-in-wsl-2--are-there-plans-to-increase-hardware-support- and here: https://docs.microsoft.com/en-gb/windows/wsl/wsl2-mount-disk#limitations 

The issue of adding USB support in WSL is being discussed in the product development repo, here: https://github.com/microsoft/WSL/issues/6011

If I misunderstood and you believe this issue should be highlighted more clearly in the FAQs or have more detail included, please re-open. 

Thanks for contributing!

**Comment by kapad** [comment]
> If I misunderstood and you believe this issue should be highlighted more clearly in the FAQs or have more detail included, please re-open.

I do think this should be in the FAQs because it involves support for USB devices in general.

In fact, I think there should be an FAQ right after the existing "Who is WSL for?", titled "Who is WSL not for?", which can list scenarios where development work is not suited for WSL, including development work that requires connecting to USB devices. 

cc: @mattwojo
