### ISSUE TITLE
WSL command line reference page is missing "verbose" switch

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/WSL#1183]
The below mentioned chapter on the page is missing one of the most used command modifiers: `--verbose`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bc08c2-7a4c-8827-47b9-2729abf0a9e9
* Version Independent ID: 26e3819a-72d0-e8a8-7790-5551acede71b
* Content: [WSL Command Line Reference](https://docs.microsoft.com/en-us/windows/wsl/reference#arguments-for-managing-windows-subsystem-for-linux)
* Content Source: [WSL/reference.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/reference.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @SetTrend. Added! :) https://github.com/MicrosoftDocs/WSL/commit/f67de6bb7b28cd401ed308d62ecb746edb7fe2ef
