### ISSUE TITLE
wmic command has been deprecated

### ISSUE THREAD

**Issue by 0xbadfca11** [MicrosoftDocs/WSL#1185]
[wmic command has been deprecated, and might be removed in a future update.](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features)
It should be replaced with a command that can be used in the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e255b0-71c7-adc6-cac0-6df3b76a971f
* Version Independent ID: a9d73ca3-7026-5b5a-f3fe-3511e976cde4
* Content: [Get started mounting a Linux disk in WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk)
* Content Source: [WSL/wsl2-mount-disk.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-mount-disk.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks for raising this issue @0xbadfca11! Really appreciate you noticing this and bringing it to our attention!
We've replaced that wmic command with a WMI command that will accomplish the same goal of listing available physical drives. I just filed a PR with the update: https://github.com/MicrosoftDocs/WSL/pull/1224
