### ISSUE TITLE
If you describe operations a 'steps' or 'some number of steps' the steps must have sequential number

### ISSUE THREAD

**Issue by kimballjohnson** [MicrosoftDocs/WSL#1187]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Not quite sure what you mean here. Please feel welcome to re-open and be more specific about what sort of change or update you would like to see regarding the WSL installation steps. Thanks!
