### ISSUE TITLE
Vague/confusing documentation on 'memory' setting in .wslconfig 

### ISSUE THREAD

**Issue by bland328** [MicrosoftDocs/WSL#1189]
The [WSL 2 Settings documentation ](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#wsl-2-settings) is both lacking and confusing regarding the `memory` setting in `.wslconfig` .

The page says the user is to provide a `size` value which defaults to `50% of total memory on Windows or 8GB, whichever is less; on builds before 20175: 80% of your total memory on Windows` and notes that the value is `How much memory to assign to the WSL 2 VM.`

The problem is that it is unclear whether `size` is to be a percentage or units of memory, and _if_ units, if it is to be bytes, MB, GB or something else.

It would also be valuable to clarify whether this memory, however specified, is a usage _ceiling_, or if all of this memory is reserved for _exclusive_ use by WSL.

I would suggest some language, but don't have enough clarity myself to do so effectively.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#wsl-2-settings)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This size can be written in MB, or GB. We added an example to .wslconfig to make this clearer. Thank you for filing!
