### ISSUE TITLE
git for win official document recommend git-credential-manager-core.

### ISSUE THREAD

**Issue by takekazuomi** [MicrosoftDocs/WSL#1193]
This document use git-credential-manager.exe but after git for win 2.29 official document recommend to use git-credential-manager-core.

>Git Credential Manager for Windows is no longer being maintained. The cross-platform Git Credential Manager Core (GCM Core) is the official replacement.
>
>GCM Core is included as an optional component of Git for Windows 2.28 and will be made the default credential helper as of Git for Windows 2.29. GCM Core can also be manually installed from this page.

http://microsoft.github.io/Git-Credential-Manager-for-Windows/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31aade8d-62a2-6d91-b0bd-3bc5880042f8
* Version Independent ID: 12e275fa-8010-5e5a-af8c-120f11ab0932
* Content: [Get started using Git on WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup)
* Content Source: [WSL/tutorials/wsl-git.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-git.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by zedgamer9128** [comment]
its solved you can close this now

**Comment by takekazuomi** [comment]
Thank you. I confirmed it.
https://github.com/MicrosoftDocs/WSL/pull/1188
