### ISSUE TITLE
McAfee firewall disrupts DNS resolution on WSLv2 on Windows10-Pro (+ workaround)

### ISSUE THREAD

**Issue by LucDM** [MicrosoftDocs/WSL#1194]
Hello,

Like many others, I have had the DNS temporarily unavailable problem after upgrading to WSLv2.

Many suggestions advise to make your own resolv.conf config. In my case, that did work on one laptop but not on another identical laptop. The only difference was : working one uses windows-Home, NOT working one runs Windows-Pro.

To verify, I did a downgrade to WSLv1 and DNS worked again. Upgraded back to WSLv2 and back to no DNS again.

I found out that the problem is caused (in MY case) by "McAFee Endpoint Solution" FIREWALL. As a quick test, DISABLE the firewall and shutdown and restart the WSL. In my case the DNS worked and I could ping outside webservers again.

Further investigation to try and narrow down the problem proved that "enabling" the "adaptive" firewall setting (in the advanced settings) makes all the difference.
I now have a working laptop on WSLv2.

Googling on MCAFEE and WSL and DNS, I found out that McAfee does not support WSL at this time :
See here:
https://kc.mcafee.com/corporate/index?page=content&id=KB91411
and here
https://kc.mcafee.com/corporate/index?page=content&id=KB82450

Maybe you can include a warning for McAfee users that they may run into problems as McAfee seems to be a possible source of this DNS-not-available problem.

My solution may serve as a temporary workaround until McAfee does support WSL.

Regards,
Luc DM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by LucDM** [comment]
Hi, again,
I see my post created a new topic. Actually, I was trying to add a comment to this issue: (the install wsl thread):

https://docs.microsoft.com/en-us/windows/wsl/install-win10

So that is what I am refering to that a warning could be added to that install-win10 WSL thread.

Regards
Luc DM

**Comment by slonopotamus** [comment]
Why don't you just contact McAfee support and demand their software to be fixed so it doesn't break other software?

**Comment by craigloewen-msft** [comment]
Hi! This issue is a technical issue related to WSL. This repo is just for managing issues relating specifically to the WSL docs pages. If you're still experiencing this issue please file it at https://github.com/microsoft/WSL , the relevant info there will help us give you an actionable solution.

Thank you for filing!
