### ISSUE TITLE
spelling error: desk

### ISSUE THREAD

**Issue by laszewsk** [MicrosoftDocs/WSL#1196]
Spelling error: desk , should be disk

Was:
To list the available filesystems in WSL2, run: cat /proc/filesystems
When a desk has been mounted via WSL2 (Linux file system), it is no longer available to mount via an ext4 driver on the Windows file system

Should read 

To list the available filesystems in WSL2, run: cat /proc/filesystems
When a disk has been mounted via WSL2 (Linux file system), it is no longer available to mount via an ext4 driver on the Windows file system
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e255b0-71c7-adc6-cac0-6df3b76a971f
* Version Independent ID: a9d73ca3-7026-5b5a-f3fe-3511e976cde4
* Content: [Get started mounting a Linux disk in WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk)
* Content Source: [WSL/wsl2-mount-disk.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-mount-disk.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by zedgamer9128** [comment]
its solved you can close this now

**Comment by laszewsk** [comment]
we really would lik to mount sdcard readers ..;-)
