### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by spaceKelan** [MicrosoftDocs/WSL#1197]
Not as straight forward, as it could be. E.g. how to check your processor architecture. Lots of boxes with useful information but they are overloaded. having more text not formated in a box would feel like an instruction instead of a jungle of "Attention boxes"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
We've made this more straight forward with the `wsl --install` command. Thank you for filing this!

**Comment by spaceKelan** [comment]
Thank you, I appreciate it!
