### ISSUE TITLE
improvement on restarting imported distribution

### ISSUE THREAD

**Issue by vbatts** [MicrosoftDocs/WSL#1198]
the command in this states to run `wsl --shutdown`, but that affects all running distributions.
Since the examples are only relating to the imported Centos image, it may be better to run `wsl --terminate Centos`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38361991-7995-26b1-93b1-ff81d3ecb4ae
* Version Independent ID: a1c0c209-b14f-bf87-5d69-dee4b1ee9b23
* Content: [Import any Linux distribution to use with WSL](https://docs.microsoft.com/en-us/windows/wsl/use-custom-distro)
* Content Source: [WSL/use-custom-distro.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/use-custom-distro.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Agreed! I will add this to my list of future edits, and if you make a PR for this with this change I'll approve it. :) Thank you for the suggestion!
