### ISSUE TITLE
Uninstalling via Microsoft Store

### ISSUE THREAD

**Issue by wilsonzlin** [MicrosoftDocs/WSL#1202]
On the page, under **Unregister and reinstall a distribution**, it mentions that distros cannot be uninstalled from the Store.

But on [FAQ's about Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/faq#how-do-i-uninstall-a-wsl-distribution-), it explicitly mentions it can. Which one is correct? Or are they referring to different things?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Sorry for the confusion @wilsonzlin. We've been slowly working our way through the docs cleaning things up. You can find instructions on how to uninstall a distro here: https://docs.microsoft.com/en-us/windows/wsl/faq#how-do-i-uninstall-a-wsl-distribution-

**Comment by mattwojo** [comment]
To more directly address your question - they've been making lots of changes to the Microsoft Store. It looks like there isn't currently an 'uninstall' feature inside the store, but you can also just right-click on any installed WSL distribution and there will be an uninstall option if you prefer to use the GUI.

![image](https://user-images.githubusercontent.com/7566797/135686079-118700ee-16ef-4503-87cb-1a23c77e1ede.png)

**Comment by mattwojo** [comment]
*Just remember uninstalling will also remove all of the data/files in that distro!

**Comment by wilsonzlin** [comment]
Thanks @mattwojo!
