### ISSUE TITLE
Invoke-WebRequest not working with Ubuntu 2004

### ISSUE THREAD

**Issue by moheikal79** [MicrosoftDocs/WSL#1203]
I have tried to use the Invoke-WebRequest to download Ubuntu 2004 but it is not working while it is working with other Ubuntu versions. 

Here is the code I used for both versions using powershell.

Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu-1804 -OutFile ~/Ubuntu1804.zip -UseBasicParsing

Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu-2004 -OutFile ~/Ubuntu2004.zip -UseBasicParsing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual?WT.mc_id=thomasmaurer-blog-thmaure)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Sorry you're having trouble @moheikal79 .
Did you try: `Invoke-WebRequest -Uri https://aka.ms/wslubuntu2004 -OutFile Ubuntu.appx -UseBasicParsing`

We generally recommend installing Ubuntu via the Microsoft Store. Without more information, I'm not sure how to troubleshoot this issue, but I'm closing as it doesn't appear to require an update to the documentation. If I'm wrong on that, please feel welcome to reopen. Or just reply with more info and we can try to help figure out what's going wrong.
