### ISSUE TITLE
Installing WSL 2 on Windows 10

### ISSUE THREAD

**Issue by bosphoran** [MicrosoftDocs/WSL#1209]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-6---install-your-linux-distribution-of-choice)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by dopeghoti** [comment]
This seems to be the most pertinent Issue with which to ask this:

How does one get WSL2 on Windows 10 now that the required Insider Builds are no longer available through Windows Update?  The Dev channel now provides Windows 11, and the Release Preview build currently appears to max out at Build 19043.1083, which does not appear to have WSL2 support.

**Comment by craigloewen-msft** [comment]
Build 19043 has WSL 2 support. You can install it using the manual install instructions on our install docs: https://aka.ms/installwsl
