### ISSUE TITLE
wsl

### ISSUE THREAD

**Issue by bbannon** [MicrosoftDocs/WSL#1210]
I've followed all the steps. Several times. In an admin command window, wsl --install just says "invalid command line option --install

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
It sounds like you may just be on an older build of Windows. The `wsl --install` command will only work on Windows 10 version 2004 and higher (Build 19041 and higher) or Windows 11.
To check your version and build number, select Windows logo key + R, type winver, select OK.
You can update to the latest Windows version in the Settings menu or with Windows Update Assistant.

**Comment by mattwojo** [comment]
If you check your Windows build number and are up-to-date, but still having trouble, please feel welcome to reopen this @bbannon and I'll see if I can point you in the direction of some further help.
