### ISSUE TITLE
MongoDB for Ubuntu 20.04

### ISSUE THREAD

**Issue by cyraid** [MicrosoftDocs/WSL#1212]
[Enter feedback here]
Are there instructions for Ubuntu 20.04?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 080023f0-501e-b638-b22c-9d2cbcbdb66a
* Version Independent ID: 88516d79-15be-0cf2-bb25-d20a17d1a37e
* Content: [Add or connect a database with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database)
* Content Source: [WSL/tutorials/wsl-database.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-database.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
Does installation procedure differ between Ubuntu version?

**Comment by cyraid** [comment]
sudo apt-get install mongodb .. "mongodb" doesn't exist on Ubuntu 20.04. On the MongoDB site they don't recommend installing on WSL.. But there is a stackoverflow answer https://stackoverflow.com/a/62496101/2024228 that does help.

**Comment by mattwojo** [comment]
Updated these docs... and worked with the MongoDB site to remove the note about not supporting WSL... it does. :)
https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database#install-mongodb

Thanks @cyraid !

**Comment by cyraid** [comment]
You're welcome Matt. :)
