### ISSUE TITLE
"Install WSL on Windows 10" page mentions --online switch but it does not work

### ISSUE THREAD

**Issue by robert-matusewicz** [MicrosoftDocs/WSL#1215]
In the "Simplified Installation for Windows Insiders" section there is a text:
`To see a list of available Linux distributions, enter wsl --list --online.`

But when I try do execute the `wsl --list --online`` on my machine I get error:

`--list: unrecognized option: online`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10?WT.mc_id=-blog-scottha)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
What Windows version are you on? You need to be on build 20262 or higher to use those features.

![image](https://user-images.githubusercontent.com/42221804/124171369-5488d780-da5d-11eb-8ce1-2c6b4baabc8d.png)


I'll close this it out since it's likely that's the issue!
