### ISSUE TITLE
Run Linux GUI apps on WSL

### ISSUE THREAD

**Issue by ubhub** [MicrosoftDocs/WSL#1218]
[Enter feedback here]
I'm unable to find results for my display error when attempting to run nautilus. 
"
** (org.gnome.Nautilus:974): WARNING **: 07:40:59.322: Error on getting connection: Failed to load SPARQL backend: Cannot autolaunch D-Bus without X11 $DISPLAY
Unable to init server: Could not connect: Connection refused

(org.gnome.Nautilus:974): Gtk-WARNING **: 07:40:59.323: cannot open display:
"
I ran the Intel GPU update as advised. igfx_win10_100.8322.exe. And rebooted. There was no apparent change in my display device adaptor: "Intel(R) Iris(R) Plus Graphics" I have a new notebook.
Advice? I want to run the sqlite browser.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps?source=docs#install-support-for-linux-gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by ubhub** [comment]
I think the problem is I'm using windows home. No hyper-V.

**Comment by ubhub** [comment]
No. Still have the problem after upgrading to win 10 pro and checking the hyper-v option in apps and features. 
I later also checked the Windows hyper-v platform but I don't think this is related.
When opening a Gui, such as nautilus, till getting the message: 
...cannot autolaunch D-Bus without X11 $DISPLAY 
Unable to init server: Could not connect: Connection refused
(org.gnome.Nautilus:22): Gtk-WARNING **: 13:32:27.503: cannot open display:

**Comment by ubhub** [comment]
I'm running ver 21H1 (OS build 19043.1083) 
with Intel(R) Iris(R) Plus Graphics

**Comment by craigloewen-msft** [comment]
Please check out WSLg: https://aka.ms/wslg 

This feature will give you access to GUI apps out of the box on the latest WSL versions in Windows Insiders.
