### ISSUE TITLE
No Xserver

### ISSUE THREAD

**Issue by cvolpe** [MicrosoftDocs/WSL#1221]
Is there something missing in this article? WSL doesn't seem to have a built-in X-server, and when I start it up the DISPLAY env var (which perhaps might point to an x-server running outside of WSL/Ubuntu on the Windows host) is not set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
You need to be on the right Windows version to gain access to this feature.

Please see this: https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#prerequisites

And this: https://aka.ms/wslg 

For more info here!
