### ISSUE TITLE
WSL Apache using http://localhost

### ISSUE THREAD

**Issue by luisdev** [MicrosoftDocs/WSL#1225]
I followed the setup instructions and Ubuntu is now running under WSL on my Windows 10 v1909 computer. When I run ifconfig I always get a different IP address for the Apache web server after a computer reboot, so I can't use the IP address to install my web application. Please add instructions for getting Apache in Ubuntu to be accessible via http://localhost. I want to be able to access my web application via the http://localhost address (instead of via a http://192.168.xxx.yyy IP that changes each time I restart the computer).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hmm... I'm not sure there is a way to do this. Did you look through the networking doc? https://docs.microsoft.com/en-us/windows/wsl/networking#accessing-linux-networking-apps-from-windows-localhost

My recommendation is to file this issue on the WSL product repo (https://github.com/microsoft/WSL/issues) to see if it is supported.. if so, then I can help with getting the steps into the docs. 

Thanks @luisdev !
