### ISSUE TITLE
Documentation says "see step 4" for error 0x800701bc, however step 4 no longer exists

### ISSUE THREAD

**Issue by branpurn** [MicrosoftDocs/WSL#1226]
Documentation says "see step 4" for error 0x800701bc (kernel component) at bottom of article, however step 4 no longer exists 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
We've restructured the docs a bit, sorry for the confusion. You can find info on how to download the Linux kernel update package here: https://docs.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package
