### ISSUE TITLE
OpenVPN on WSL

### ISSUE THREAD

**Issue by X-THUNDER-X-IT** [MicrosoftDocs/WSL#1229]
![Screenshot (1)](https://user-images.githubusercontent.com/82824677/125793748-66e10c52-d19c-4dc7-9452-dea3ec4de2e6.png)
systemctl, and my new-vpn (with openvpn) do not work.
Solution, please.

**Comment by thehotery** [comment]
correct me if i'm wrong, but seems like systemd not available on WSL (only some dirty third-part workarounds). use **service <servicename> start** instead

**Comment by mattwojo** [comment]
Yes - Currently WSL does not have support for systemd (a service management system in Linux).

If a tutorial recommends using sudo systemctl, instead use: sudo /etc/init.d/. For example, sudo systemctl status docker, for WSL would be sudo /etc/init.d/docker status ...or you can also use sudo service docker status.

Closing this as I don't currently see an action item for updating the docs. If you continue experiencing an error that you believe is an issue with WSL, please file a bug on the WSL product repo, here: https://github.com/microsoft/WSL/issues
