### ISSUE TITLE
The Kernel file is still missing even though I've installed the `wsl_update_x64.msi`

### ISSUE THREAD

**Issue by harrychong2118** [MicrosoftDocs/WSL#1231]
I'm trying to update WSL1 to WSL2, met all requirements listed [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-2---check-requirements-for-running-wsl-2) yet encounter problem(s) at Step 4,5

**Problem** There is no `kernel.FILE` under the `C:\WINDOWS\system32\lxxs\tools` directory before and after installing `wsl_update_x64.msi` (tried uninstalling & installing for several times)

> Windows: Windows 10 Enterprise Version 21H1 with Build 19043.11110
> WSL: Ubuntu-20.04 VERSION 1
> Directory tree of `\lxxs\tools` (after installing `.msi`):
> ```bash
> C:\WINDOWS\SYSTEM32\LXSS
> │  LxssManager.dll
> │  LxssManagerProxyStub.dll
> │  wslhost.exe
> │
> ├─lib
> │      libcuda.so
> │      libcuda.so.1
> │      libcuda.so.1.1
> │      libnvidia-ml.so.1
> │      libnvwgf2umx.so
> │      nvidia-smi
> │
> └─tools
>         bsdtar
>         ext4.vhdx.gz
>         init
>         initrd.img
>         license
> ```

****
Same issue as #591, with reasons found (mentioned above)

**Comment by mattwojo** [comment]
Hi @harrychong2118 - I'm sorry to hear that it's giving you trouble. This looks like an issue that should be filed on the WSL product repo though as I don't see anything requiring an update to the docs. Here's a link to the WSL issues repo: https://github.com/microsoft/WSL/issues

Hope that you can get this resolved. Sounds like a weird one.
