### ISSUE TITLE
Unacceptable usernames.

### ISSUE THREAD

**Issue by Chris8top8he8r** [MicrosoftDocs/WSL#1232]
I'm new and just installed Linux and it wants a username.  I put in WMLUnixer and it failed by some rule I cannot understand.  It returned:
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: WMLUnixer
adduser: Please enter a username matching the regular expression configured
via the NAME_REGEX configuration variable.  Use the `--force-badname'
option to relax this check or reconfigure NAME_REGEX.
Enter new UNIX username:

So I could use --force-badname but why is it deemed bad in the first place, and where do I learn about NAME_REGEX without another search tab?  Unclear what to avoid.  But I'm very grateful it did return the URL to at least read about it, and then provide feedback.  Maybe it would be good to also have the NAME_REGEX URL link for novices like me.  I figured this was simply some light feedback without the need for tracking or responses, so I hope I'm doing this correctly.  Thanks for listening.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @Chris8top8he8r -- ha, yes, appreciate the 'light feedback'. 👍 
Username creation for a distro is on the Linux side, so not something we have any control over, but I see what you're saying in regard to providing a link out to learn more about good and bad usernames. Maybe this StackExchange article? https://serverfault.com/questions/73084/what-characters-should-i-use-or-not-use-in-usernames-on-linux
