### ISSUE TITLE
Grammatical mistake in README.md

### ISSUE THREAD

**Issue by Netherquark** [MicrosoftDocs/WSL#1234]
The README.md found [here ](https://github.com/microsoft/WSL/blob/master/README.md)says:
> This is your best ways to interact directly with the Windows Subsystem for Linux teams.

Instead, it should be:

> This is your best way to interact directly with the Windows Subsystem for Linux teams.

Its a minor issue, but a concern nonetheless.

**Comment by v-sreekesh** [comment]
Hi I have created a pull request with this typo fixed
