### ISSUE TITLE
Suggested filtering of system type in German does not produce correct output

### ISSUE THREAD

**Issue by sandroschwarz** [MicrosoftDocs/WSL#1236]
The first note for section 4 mentions to use localized search strings, when filtering for one's system type.
> Caveat: On non-English Windows versions, you might have to modify the search text, for example, in German it would be systeminfo | find "Systemtyp".

When trying to filter this way (e.g. using `systeminfo | find "Systemtyp"` on a German machine), find.exe will report a wrong parameter format

> PS C:\> systeminfo | find "Systemtyp"
> FIND: Parameterformat falsch

Using the non-localized `systeminfo | find "System Type"` does not yield this error message.

When the quotation marks are escaped beforehand, the filter works fine.
Examples would be either ```systeminfo | find `"Systemtyp`"``` or `systeminfo | find --% "Systemtyp"`

A somewhat similar issue has already been reported in #1063, however this issue focuses primarily on the suggested, but non-functioning, localized command.

It would be helpful if the article would mention the odd behavior of find.exe, or alternatively, provide either of the two mentioned or other workarounds for escaping in other localizations of Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @sandroschwarz. In https://github.com/MicrosoftDocs/WSL/commit/06a016256f5a90c257a3636a86458b1882ee83cd, I updated the note to clarify the issues you're pointing out. Please reopen if I didn't quite capture it accurately.
