### ISSUE TITLE
Git Credential Manager on WSL2 docs isn't clear

### ISSUE THREAD

**Issue by ihor-sviziev** [MicrosoftDocs/WSL#1238]
For the WSL2 base installation of Ubuntu, we should use Linux based Git Credential Manager. Currently, it's not shown in the docs, and not clear how to configure it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31aade8d-62a2-6d91-b0bd-3bc5880042f8
* Version Independent ID: 12e275fa-8010-5e5a-af8c-120f11ab0932
* Content: [Get started using Git on WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git)
* Content Source: [WSL/tutorials/wsl-git.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-git.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
I believe our recommendation in this tutorial is to tie your Linux git credential manager to Windows so you can use all the same credentials. We even link to a command to do it:

![image](https://user-images.githubusercontent.com/42221804/127199007-370052e2-7b28-4224-bf8c-04776b81cedb.png)

**Comment by ihor-sviziev** [comment]
@craigloewen-msft, so you mean I should install git credentials manager to windows, and then connect to it Ubuntu?
In such case, the git command will be used from Linux? Will it work with Linux gpg for signing commits?

**Comment by craigloewen-msft** [comment]
This is just one way of doing it. Using the command above is nice because all your credentials are stored in one place. It still uses Linux signing etc., but checks your access using Windows.

Docker containers are a different story. If git is running in Docker it has no clue about your permissions on the Linux host so you'd need to set permissions anyway.

**Comment by ihor-sviziev** [comment]
@craigloewen-msft thank you! Will check it tomorrow

**Comment by ihor-sviziev** [comment]
Hi @craigloewen-msft,
Just tried to install Git for Windows latest version, pressed next, next, next. After installation I executed that command and tried to execute git push.
As a result, I got the following exceptions:
![image](https://user-images.githubusercontent.com/1873745/127274093-c320b9c7-4415-4b52-bc2c-098401d22e76.png)

The next run git push showed me the same from the beginning:
![image](https://user-images.githubusercontent.com/1873745/127274163-37dc133d-b718-4233-b25b-4e5c1597bbab.png)

**Comment by ihor-sviziev** [comment]
I just restarted the windows terminal, and now everything works as expected.
Thank you so much!
