### ISSUE TITLE
Why does bash.exe exist?

### ISSUE THREAD

**Issue by isaac32767** [MicrosoftDocs/WSL#1242]
Why would I use bash.exe in place of wsl.exe?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bc08c2-7a4c-8827-47b9-2729abf0a9e9
* Version Independent ID: 26e3819a-72d0-e8a8-7790-5551acede71b
* Content: [WSL Command Line Reference](https://docs.microsoft.com/en-us/windows/wsl/reference)
* Content Source: [WSL/reference.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/reference.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
To be compatible with older Windows versions. The same reason goes with wslconfig.exe also.

**Comment by craigloewen-msft** [comment]
Yes as @Biswa96 mentioned you don't really need to use bash.exe, please use `wsl.exe` :)
