### ISSUE TITLE
sample command is invalid

### ISSUE THREAD

**Issue by jesschappleTR** [MicrosoftDocs/WSL#1243]
wsl --list --online

is invalid

PS C:\WINDOWS\system32> wsl --list --online
--list: unrecognized option: online
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hi @jesschappleTR - My best guess is that you're running an older version of Windows (?)

To check your version and build number, select Windows logo key + R, type winver, select OK.
You can update to the latest Windows version in the Settings menu or with Windows Update Assistant.
