### ISSUE TITLE
Hyper-V Clients also require ExposeVirtualizationExtensions set true from Hyper-V host.

### ISSUE THREAD

**Issue by wittelw** [MicrosoftDocs/WSL#1246]
For "Installation failed with error 0x80070003 or error 0x80370102" topic you should add that to solve this error on Hyper-V clients (Windows 10 and Windows 11) run the following from an Administrative PowerShell command:

Set-VMProcessor <VMName> -ExposeVirtualizationExtensions $true

Reference: https://www.altaro.com/hyper-v/enable-nested-virtualization/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Added a link to the Microsoft Hyper-V docs that shows how to set up that nested config.
Thanks for filing this @wittelw !
