### ISSUE TITLE
Kali Linux loggin in stuck

### ISSUE THREAD

**Issue by Mikec19** [MicrosoftDocs/WSL#1247]
[Enter feedback here]
When i type my new UNIX username its okey but then when i need to type my new password it just get stuck does anyone know what is the problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hi @Mikec19 - This doesn't sound like an issue that will require an update to the documentation, so I'm going to close it out and recommend that you use the WSL product repo to file this as a bug, here: https://github.com/microsoft/WSL/issues
The bug form will ask you for a bunch of details like what build # of Windows you're using, which version of WSL and the Linux kernel, etc.
