### ISSUE TITLE
[LOC]Back-Translation "Windows ターミナル"→"Windows Terminal" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/WSL#1252]
ja-jp:"https://docs.microsoft.com/ja-jp/windows/wsl/setup/environment#set-up-windows-terminal"
![environment#set-up-windows-terminal_j](https://user-images.githubusercontent.com/40815708/128658553-b902cb6b-71ca-4b11-a34b-049e1241c851.png)

en-us:"https://docs.microsoft.com/en-us/windows/wsl/setup/environment#set-up-windows-terminal"
![environment#set-up-windows-terminal_e](https://user-images.githubusercontent.com/40815708/128658559-e8edad19-daf5-4804-b1d7-a67f5d41db23.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8226ebd3-6c2a-17aa-3a27-cffb4a5d0a57
* Version Independent ID: 06d3a4ce-218a-d39d-4a71-60a3cb86e422
* Content: [Best practices for setting up a WSL 2 development environment](https://docs.microsoft.com/en-us/windows/wsl/setup/environment)
* Content Source: [WSL/setup/environment.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/setup/environment.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
I added a piece of code that should stop the translation of the name "Windows Terminal", but it will take a few weeks for the translation to update.
Thank you for filing this @hyoshioka0128 !
