### ISSUE TITLE
cant install linux headers on kali running on wsl kernel

### ISSUE THREAD

**Issue by aryanrh** [MicrosoftDocs/WSL#1253]
hey, I am trying to install linux headers for wsl.
i tried this command :-- 
```
┌──(root💀Aryan-RH)-[/]
└─# apt-get install linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package linux-headers-5.10.16.3-microsoft-standard-WSL2
E: Couldn't find any package by glob 'linux-headers-5.10.16.3-microsoft-standard-WSL2'
E: Couldn't find any package by regex 'linux-headers-5.10.16.3-microsoft-standard-WSL2'

```
i wanted to install [rtl8188eus](http://github.com/aircrack-ng/rtl8188eus)  drivers for my kali wsl but it depends on linux headers which is not available.... Please help me how to install these drivers other than running kali on virtualbox and vmware.

Please help me anybody.....

**Comment by craigloewen-msft** [comment]
Hey you won't be able to install headers that way since the Linux kernel headers for the WSL 2 kernel are not included in apt! You can get the headers by compiling the kernel yourself (Here's a link to the repo: https://github.com/microsoft/WSL2-Linux-Kernel )
We are also investigating adding Linux kernel headers to WSL by default. Thank you for filing this!

**Comment by aryanrh** [comment]
thank you also can I connect my tp link wireless adapter to wsl. PLease help how to do this.

**Comment by mesho-17** [comment]
maybe you can use this option and see if it will work out.
1. sudo apt-get install linux-headers-generic build-essential git
2. cd rtlwifi_new
3. make
4. sudo make install
5. sudo modprobe rtl8723be

**Comment by SweetPum** [comment]
> hey, I am trying to install linux headers for wsl. i tried this command :--
> 
> ```
> ┌──(root💀Aryan-RH)-[/]
> └─# apt-get install linux-headers-$(uname -r)
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package linux-headers-5.10.16.3-microsoft-standard-WSL2
> E: Couldn't find any package by glob 'linux-headers-5.10.16.3-microsoft-standard-WSL2'
> E: Couldn't find any package by regex 'linux-headers-5.10.16.3-microsoft-standard-WSL2'
> ```
> 
> i wanted to install [rtl8188eus](https://github.com/aircrack-ng/rtl8188eus) drivers for my kali wsl but it depends on linux headers which is not available.... Please help me how to install these drivers other than running kali on virtualbox and vmware.
> 
> Please help me anybody.....

**Comment by SweetPum** [comment]
i encountered the same problem but when i used command "uname -r" to check my kernel its was "5.10.16.3-microsoft-standard-WSL2" so do i need to install custom kernel or am i fine here?

**Comment by sajalkmr** [comment]
> Hey you won't be able to install headers that way since the Linux kernel headers for the WSL 2 kernel are not included in apt! You can get the headers by compiling the kernel yourself (Here's a link to the repo: https://github.com/microsoft/WSL2-Linux-Kernel ) We are also investigating adding Linux kernel headers to WSL by default. Thank you for filing this!

Update?
