### ISSUE TITLE
Cannot bind parameter

### ISSUE THREAD

**Issue by tmerrr** [MicrosoftDocs/WSL#126]
Hi, I'm trying to Install the Windows Subsystem for Linux by following step 1 on https://msdn.microsoft.com/en-us/commandline/wsl/install_guide?f=255&MSPPError=-2147217396#install-the-windows-subsystem-for-linux.

However I'm getting the following error message:

```
Enable-WindowsOptionalFeature : Cannot bind parameter because 'Online' is specified more than once. To provide multiple values to parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".
At line1: char115
+... -Windows-Subsystem-LinuxEnable-WindowsOptionalFeature -Online -Featur ...
+
+ CategoryInfo   :   Invalid Argument: (:) [Enable-WindowsOptionalFeature], ParameterBindingException
+ FullyQualifiedErrorId  :  ParameterAlreadyBound,Microsoft.Dism.Commands.EnableWindowsFeatureCommand
```

Any help would be great!  Thanks.

**Comment by bitcrazed** [comment]
Hey @tmerrr , could you make sure you pasted the command precisely as written, and only once?

    Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

I just ran on my machine and it works fine.
