### ISSUE TITLE
"Manually download Windows Subsystem for Linux distro packages" outdated link/package for Kali

### ISSUE THREAD

**Issue by NotTheDr01ds** [MicrosoftDocs/WSL#1264]
[Manually download Windows Subsystem for Linux distro packages](https://docs.microsoft.com/en-us/windows/wsl/install-manual) desperately needs an update with a link to the latest Kali version.  The package linked to there is 2019.2, but there's clearly a later package available since the Store version is currently at 2021.2.

The outdated version is pretty well borked on WSL (v1 or v2, doesn't matter).

It's old enough that the repo keys are expired, and since the package is "minimal", it doesn't even include `gpg` which is needed to update the repo keys.  Attempting to install `gpg` without `apt` gets into a number of dependency issues.

I noticed this today based on a [Stack Exchange question](https://unix.stackexchange.com/questions/666046/how-to-apt-update-for-kali-on-a-manually-installed-wsl), which led me to another [report](https://unix.stackexchange.com/q/660123/432493) with the same thing about a month earlier.  I've been able to reproduce the issue myself based on those reports.

If you can't locate the correct URL for the latest package, I would propose removing Kali from the list of distros that can be "manually installed" for now.

**Comment by mattwojo** [comment]
Thanks for filing this @NotTheDr01ds. We rely on the folks who keep up Kali to send new appx packages when they're available. We'll reach out or please consider filing an issue on their repo as well -- if we can get an updated package, we'll post it. If we can't, we'll remove it. Thanks for the ping on this.

**Comment by L0v3l4c3** [comment]
Indeed a quite messy situation, as gpg is not even installed... but here is a temporary fix anyways : 

```
sudo wget --no-check-certificate https://http.kali.org/kali/pool/main/k/kali-archive-keyring/kal
i-archive-keyring_2020.2_all.deb

sudo dpkg -i kali-archive-keyring_2020.2_all.deb
```

**Comment by neitrinoweb** [comment]
I do fix problem with GPG manual installing archive-keyring package.
`
wget --no-check-certificate https://http.kali.org/kali/pool/main/k/kali-archive-keyring/kali-archive-keyring_2022.1_all.deb
sudo dpkg -i kali-archive-keyring_2022.1_all.deb
`
though It does not allow me to upgrade my system, packages are too old to do it gracefully, `apt upgrade` ends up with an error.

Seems like old Kali WSL distributive is broken from the beginning. Please, update it!
