### ISSUE TITLE
Bad instructions - Powershell vs. Cmd

### ISSUE THREAD

**Issue by valhuber** [MicrosoftDocs/WSL#1267]
[Enter feedback here]
This command fails in Powershell, works in Cmd Shell

wsl --set-default-version 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hmm... that command doesn't fail for everyone in PowerShell. Could it be that you're running an older Windows build?
To check your version and build number, select Windows logo key + R, type winver, select OK.
You can update to the latest Windows version in the Settings menu or with Windows Update Assistant.
Sorry you had trouble with it @valhuber
