### ISSUE TITLE
get-wmiobject deprecated

### ISSUE THREAD

**Issue by nko321** [MicrosoftDocs/WSL#1268]
Hello, would request changing calls to get-wmiobject to get-ciminstance as the former has been deprecated and doesn't work in Powershell 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e255b0-71c7-adc6-cac0-6df3b76a971f
* Version Independent ID: a9d73ca3-7026-5b5a-f3fe-3511e976cde4
* Content: [Get started mounting a Linux disk in WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk)
* Content Source: [WSL/wsl2-mount-disk.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-mount-disk.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Done! :) Thanks @nko321 !!

**Comment by nko321** [comment]
Awesome!
