### ISSUE TITLE
Please link to specific Debian releases

### ISSUE THREAD

**Issue by AgentOren** [MicrosoftDocs/WSL#1269]
Link to Debian Linux was updated a few days ago to latest Debian 11 ("bullseye").
Few days earlier it was Debian 10 ("buster").
Please include links so we can choose between:

- Debian 11 / 10 ( / 9)

in the same way we can choose between

- Ubuntu 20.04 / 18.04 / 16.04

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual#feedback)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by FPS-Lightning** [comment]
+1. Need buster for a buster Raspbian based development project where some packages don't exist for bullseye yet.

**Comment by craigloewen-msft** [comment]
This is something that's chosen by the Debian team. We just provide a reflection of what they have available in the Microsoft Store. 

To get unblocked I'd recommend following the instructions here to make your own WSL distro with the specific version you'd like:
https://docs.microsoft.com/en-us/windows/wsl/use-custom-distro

And then for a long term solution, I'd recommend asking the Debian team for this (I will too) and if they'd like to we can determine if we can provide multiple versions. Thanks!

**Comment by Biswa96** [comment]
If you guys want to go with a DIY procedure you can download the rootfs.tar.xz file from here https://github.com/debuerreotype/docker-debian-artifacts/tree/dist-amd64/stable and import it in WSL with `wsl.exe --import` command.
