### ISSUE TITLE
"Command Line Reference":  Request to document the (extremely useful) ~ option for wsl.exe

### ISSUE THREAD

**Issue by NotTheDr01ds** [MicrosoftDocs/WSL#1272]
Currently the only mention of `~` in the [Command Line Reference](https://docs.microsoft.com/en-us/windows/wsl/reference) doc is for the "historic" (as that doc calls it) `bash.exe`.

However, this is also an option for the `wsl.exe` command to start in the user's home directory, but there is no mention of it in either the online doc nor the `wsl.exe --help` doc.  Please note when documenting the argument that the `~` must be the first argument.

**Comment by mattwojo** [comment]
Thanks @NotTheDr01ds. Added a ref for `~` -- did I capture it correctly? Please feel welcome to file an update PR or reopen if you feel that it needs more detail. Thanks again!
