### ISSUE TITLE
Docker Desktop for Windows is no longer free

### ISSUE THREAD

**Issue by frode-carlsen** [MicrosoftDocs/WSL#1273]
Docker Desktop for Windows is no longer free.
Maybe update description on how to run docker CLI directly on WSL2 without it?

https://www.docker.com/pricing/faq

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 403a33a6-304c-2ded-9ea8-4d70bc5f17ba
* Version Independent ID: 93b6a9ef-08ba-be90-736e-27515fb0f4da
* Content: [Get started with Docker containers on WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers)
* Content Source: [WSL/tutorials/wsl-containers.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-containers.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
Just wondering what holds you back from using an actual bare metal installation of GNU/Linux distribution.

**Comment by mattwojo** [comment]
Updated with a link to their FAQs - https://github.com/MicrosoftDocs/WSL/commit/65607e985e5048999e8bea5353c16f40fff0e4a1

Thanks @frode-carlsen !
