### ISSUE TITLE
Changing the resolution

### ISSUE THREAD

**Issue by DangerStu** [MicrosoftDocs/WSL#1275]
This was easy to setup, but I can't find any information on changing the DPI settings as by default on my UHD i feel like I'm looking at a postage stamp :D

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
This repo is only for doc updates -- could you please file this issue / request on the WSLg repo? https://github.com/microsoft/wslg/issues

It's DPI aware in incriments of 100% -- so at 100% / 200% is when you'll notice differences.
