### ISSUE TITLE
Docker Desktop is no longer free for commercial use

### ISSUE THREAD

**Issue by JessePelton** [MicrosoftDocs/WSL#1278]
Docker Desktop is no longer free for commercial use. If there's a reasonable free alternative for running Linux containers on Windows, it would be worth mentioning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 403a33a6-304c-2ded-9ea8-4d70bc5f17ba
* Version Independent ID: 93b6a9ef-08ba-be90-736e-27515fb0f4da
* Content: [Get started with Docker containers on WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers)
* Content Source: [WSL/tutorials/wsl-containers.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-containers.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @JessePelton - updated with a link. :) https://github.com/MicrosoftDocs/WSL/commit/65607e985e5048999e8bea5353c16f40fff0e4a1
