### ISSUE TITLE
Unable to get old versions of Debian in WSL

### ISSUE THREAD

**Issue by FPS-Lightning** [MicrosoftDocs/WSL#1279]
@craigloewen-msft Just checked with the Microsoft Store. Debian Bullseye is available there, however, the manual download link is now stuck at Buster.
I guess a lot of people would want both the links. Can you please suggest any long-term solution for this?

__Originally posted by @iranvir in https://github.com/MicrosoftDocs/WSL/issues/563#issuecomment-903682932__

I also see this, as I did not have WSL when buster was the main distro, but I am developing for RPi and need a buster distro, which appears to not exist any longer for WSL

**Comment by iranvir** [comment]
I don't really know if this is right and proper, but there are tools online to get the APPX file. Just browse the windows app store using your browser, and copy the app's URL.
This works for any generic app, not just WSL distros. I followed this guide: http://woshub.com/how-to-download-appx-installation-file-for-any-windows-store-app/ and it seems to work just fine for me.

Still it is a bit frustrating. Windows used to allow so much control with downloadable .exe files and complete user control. This whole app store philosophy is not for the PC.

**Comment by craigloewen-msft** [comment]
I've updated this package to the latest from the Microsoft Store, please check and let me know if this unblocks you! Thank you for your patience.

**Comment by craigloewen-msft** [comment]
We track what is up to date in the Microsoft Store, and so we keep our package current with whatever the Debian team provides to the Microsoft Store. I'd recommend asking the Debian team to provide an earlier version if possible. 

As well, if you want to use any Linux distribution you can grab any container and use that as a WSL distro. Here's our docs with the guide on how to do that:

https://docs.microsoft.com/en-us/windows/wsl/use-custom-distro

I'd recommend following that to use the right version of the distro you're interested in. Thanks for filing this!
