### ISSUE TITLE
WSLENV intended environment variable values clarification

### ISSUE THREAD

**Issue by JSn1nj4** [MicrosoftDocs/WSL#1281]
When I found the [blog post][blog] about `WSLENV`, I was looking for a way to pass general-purpose environment vars to WSL (in my case, `XDEBUG_CONFIG`). How I used it works, _but_ the blog post and the [WSL document][wsl-doc] both switch between mentioning env vars _generally_ and then assuming vars _will_ contain path strings.

Is this var only supposed to be used for sharing path string vars?

[blog]: https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/
[wsl-doc]: https://docs.microsoft.com/en-us/windows/wsl/interop#share-environment-variables-between-windows-and-wsl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea49528-e5c5-4f64-841e-9fe036de304e
* Version Independent ID: edeb7cb5-afcf-1410-4966-f48ce5f6a19a
* Content: [Windows interoperability with Linux](https://docs.microsoft.com/en-us/windows/wsl/interop#feedback)
* Content Source: [WSL/interop.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/interop.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Hi @JSn1nj4 in general we designed these for path strings to include automatic translation, but you can use regular variables for them as well. Thanks for filing this! :)

**Comment by JSn1nj4** [comment]
Thanks for clarifying! Just wanted to avoid anything weird caused by something other than a path being shared. :)
