### ISSUE TITLE
"Intel GPU driver for WSL" link is broken

### ISSUE THREAD

**Issue by alexei-osipov** [MicrosoftDocs/WSL#1282]
"Intel GPU driver for WSL" link is broken on the page https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps
The link points to a generic landing page now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by malhashemi** [comment]
Pull request #1291 solves this

**Comment by craigloewen-msft** [comment]
Merged the PR to fix this, thank you for filing this and putting in the change!
