### ISSUE TITLE
Docker licensing changes

### ISSUE THREAD

**Issue by zleight1** [MicrosoftDocs/WSL#1283]
Currently the page states that docker desktop is free with WSL, from what I understand this will no longer be the case for commercial usage. Please update accordingly to let users know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 403a33a6-304c-2ded-9ea8-4d70bc5f17ba
* Version Independent ID: 93b6a9ef-08ba-be90-736e-27515fb0f4da
* Content: [Get started with Docker containers on WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers)
* Content Source: [WSL/tutorials/wsl-containers.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-containers.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @zleight1 - updated: https://github.com/MicrosoftDocs/WSL/commit/2bcdb77662f593ec76813f0b224556c43a7278be#diff-a061e3ae1c09be2e69c7d788a5b30257369a6ce0a61f24fb391a5bb262b8049c
