### ISSUE TITLE
Enable virtualization step should be mention

### ISSUE THREAD

**Issue by Azkron** [MicrosoftDocs/WSL#1285]
You should add `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart` before `wsl --install` unless you want the installation to fail on 95% of earths machines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
Read the documentation again. It says:

> This command will enable the required optional components, download the latest Linux kernel, set WSL 2 as your default, and install a Linux distribution for you

Internally in wslapi.dll, both Microsoft-Windows-Subsystem-Linux and VirtualMachinePlatform feature is checked with DismGetFeatureInfo() and installed with DismEnableFeature() functions.

**Comment by Azkron** [comment]
> Read the documentation again. It says:
> 
> > This command will enable the required optional components, download the latest Linux kernel, set WSL 2 as your default, and install a Linux distribution for you
> 
> Internally in wslapi.dll, both Microsoft-Windows-Subsystem-Linux and VirtualMachinePlatform feature is checked with DismGetFeatureInfo() and installed with DismEnableFeature() functions.

Yeah, I had virtualization disabled in the BIOS. My bad.
