### ISSUE TITLE
what version of WSL does 'wsl --install' install?

### ISSUE THREAD

**Issue by NickPerezCarletonUniversity** [MicrosoftDocs/WSL#1286]
See title. It is unclear based off of the documentation I saw.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Agrover112** [comment]
"Install WSL | Microsoft Docs" https://docs.microsoft.com/en-us/windows/wsl/install

I think as per this it's for the newer kernel.

**Comment by NickPerezCarletonUniversity** [comment]
oh never mind, the documentation I linked actually says it is WSL 2. It should maybe list that as the title of the document. It just says 'Install WSL'. Should say 'Install WSL 2'.

**Comment by Agrover112** [comment]
Nice then I guess we close the issue then

**Comment by NickPerezCarletonUniversity** [comment]
well, there is still an issue with the documentation I would say. But i'll close this issue because I don't imagine anyone will bother changing something so minor.
