### ISSUE TITLE
I use wsl --install for wsl2, it is unuseful, then I use wsl --update, it success

### ISSUE THREAD

**Issue by hhhhack** [MicrosoftDocs/WSL#1287]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install WSL](https://docs.microsoft.com/zh-cn/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
It sounds like you may just be on an older build of Windows. Can you confirm what build # you are using?
To check your version and build number, select Windows logo key + R, type winver, select OK. 
You can [update to the latest Windows version in the Settings menu](ms-settings:windowsupdate) or with [Windows Update Assistant](https://www.microsoft.com/software-download/windows10).
