### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by BillEndow-nbcuni** [MicrosoftDocs/WSL#1289]
https://docs.microsoft.com/en-us/windows/wsl/basic-commands#list-install-linux-distributions

Should be:
**List installed linux distributions**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb425ee-c5e3-fc01-93a7-c87c9fa0b89a
* Version Independent ID: ea2f6a7b-28f2-2af8-e8fc-7f7b3624f88a
* Content: [Basic commands for WSL](https://docs.microsoft.com/en-us/windows/wsl/basic-commands)
* Content Source: [WSL/basic-commands.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/basic-commands.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @BillEndow-nbcuni !
