### ISSUE TITLE
HTTP requests from WSL2 not working

### ISSUE THREAD

**Issue by dhirlea** [MicrosoftDocs/WSL#1292]
[Enter feedback here]
I would add a comments for https requests not working when called from WSL2. To enable this functionality one must switch their network connection from public to private.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/troubleshooting.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Sorry @dhirlea - I'm not quite understanding what you're saying here. Could you provide a little more info / context for what you would like to see updated in the docs?

**Comment by mattwojo** [comment]
*It shouldn't be the case that everyone needs to switch their network connection from public to private when calling an https request from WSL2.  I'm going to close this for now, but please reopen if you think I'm wrong on this and can provide some further info / context to help me update info in the doc.

**For anyone who may have experienced this error and needs to know how to switch your network from public to private, here's a link explaining how: https://docs.microsoft.com/answers/questions/73866/how-to-change-network-settings-from-public-to-priv.html
