### ISSUE TITLE
Edge Dev URL is broken/outdated

### ISSUE THREAD

**Issue by schumatt-msft** [MicrosoftDocs/WSL#1295]
Looks like the Edge Dev package URL is no longer valid. This is the current one available from the Edge Insider site as of today:
https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_96.0.1028.0-1_amd64.deb

The [Edge Insider site](https://www.microsoftedgeinsider.com/en-us/download/?platform=linux-deb) also offers commands behind the **Get Instructions** button for getting the latest release via command line. Could this page be updated with these commands instead or possibly some other URL that always fetches the current build?

BTW, thanks for this great resource! It helped me get a basic GUI up & running to test some things in the Teams client on Linux for one of my customers. 👍

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @schumatt-msft! 
I updated the page to just point to that Edge command line instructions site. Look ok to you? 
https://github.com/MicrosoftDocs/WSL/commit/40b4a6673eb7841c200066055350d6e2f0e0b25b#diff-d6cef5a734dadb830ca1278042c6bc717d52277ee14371d6caeb969a7a1da526
