### ISSUE TITLE
''Run Linux GUI apps on the Windows Subsystem for Linux'' doesn't inform that you need a Windows X server

### ISSUE THREAD

**Issue by Acvale** [MicrosoftDocs/WSL#1297]
The guide is well written, but it does not explain that users need to configure a Windows X server in order to open the GUIs. I do not know if the process is already integrated in the Windows 11 build 22000, but I think it would be a nice touch to inform that if you are using Windows 10, you need to configure the server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#feedback)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
The WSL GUI feature uses RDP protocol and launches mstsc.exe from Windows side. Users don't need to install any X server programs in Windows.

**Comment by Acvale** [comment]
True, the issue happened with me because I deliberately deactivated a lot of Windows resources. My apologies.
