### ISSUE TITLE
Errors when installing Chrome and Edge

### ISSUE THREAD

**Issue by RobJacobson** [MicrosoftDocs/WSL#1298]
I received errors when I attempted to install both Google Chrome and MS Edge after following these instructions.

Here's the error message for Edge:
```rob@Flexo:/tmp$ sudo curl https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_91.0.852.0-1_amd64.deb -o /tmp/edge.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0    728      0 --:--:-- --:--:-- --:--:--   725
rob@Flexo:/tmp$ sudo apt install /tmp/edge.deb -y
Reading package lists... Error!
E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Could not read meta data from /tmp/edge.deb
E: The package lists or status file could not be parsed or opened.
```

I'm stuck on this one. Is there any way to fix this?

Here's the error message for Chrome:

```rob@Flexo:/tmp$ sudo dpkg -i google-chrome-stable_current_amd64.deb
Selecting previously unselected package google-chrome-stable.
(Reading database ... 68453 files and directories currently installed.)
Preparing to unpack google-chrome-stable_current_amd64.deb ...
Unpacking google-chrome-stable (94.0.4606.71-1) ...
dpkg: dependency problems prevent configuration of google-chrome-stable:
 google-chrome-stable depends on fonts-liberation; however:
  Package fonts-liberation is not installed.

dpkg: error processing package google-chrome-stable (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Errors were encountered while processing:
 google-chrome-stable
```

I was able to resolve this through the following:
`sudo apt install fonts-liberation`

Could this please be added to the instructions for installing Chrome?

Thanks! 🎉

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by iProgramMC** [comment]
Why would you install Chrome/Edge on WSL? You'll probably get faster results using native Windows builds.

If you really want to get it on WSL you may want to have WSL GUI installed

**Comment by craigloewen-msft** [comment]
Closing this for bookkeeping. If you're still seeing this error please file it at the microsoft/wsl repo. Thank you!
