### ISSUE TITLE
Need to clarify how to create users

### ISSUE THREAD

**Issue by PatrickLang** [MicrosoftDocs/WSL#1299]
I just did a clean Windows 11 install, then ran these steps to get Ubuntu 20.04 running:

1. ran `appwiz.cpl` - added `Hyper-V` and `Windows Subsystem for Linux` features, then rebooted

2. Finished setting up WSL from elevated powershell prompt:

```
wsl --update # to install the kernel
wsl --install -d Ubuntu-20.04 # install the distro
```

3. Then I ran `ubuntu2004.exe` in a non-admin prompt. Surprisingly, it didn't prompt me to create a user as I have seen before.

At this point, I still want to:

- Create a regular user `patrick`, and add it to the `wheel` or `sudoers` group so I can `sudo` later
- Switch WSL's default user to `patrick` from `root`

I would expect this to be here in the docs, but it's missing: https://github.com/MicrosoftDocs/WSL/blob/master/WSL/user-support.md

**Comment by PatrickLang** [comment]
The missing steps are something like this in WSL

```
useradd -G sudo,docker -m <newusername>
passwd <newusername>
```

Then you can run with `wsl.exe -u <newusername>` and test out the user settings. However, I still am not sure how to set the default user to something other than `root`

**Comment by mattwojo** [comment]
Thanks @PatrickLang! You can set the default user following these steps: 
https://docs.microsoft.com/en-us/windows/wsl/use-custom-distro#add-wsl-specific-components-like-a-default-user

Closing, as we don't use that user-support.md page any more -- the instructions for setting up a Linux username and password are now a part of the [Set up your WSL dev environment](https://docs.microsoft.com/windows/wsl/setup/environment#set-up-your-linux-username-and-password).

Please re-open if you feel this still requires an update to the docs.
