### ISSUE TITLE
wsl.conf: Documnent ldconfig option

### ISSUE THREAD

**Issue by mook-as** [MicrosoftDocs/WSL#1301]
https://github.com/MicrosoftDocs/WSL/blob/73e7582da51ece4e975022c28c471e0bcf181110/WSL/wsl-config.md#automount

There appears to be an undocumented `ldconfig` option that defaults to `true` (in the `[automount]` section).
When set, `init` appears to drop a file in `/etc/ld.so.conf.d` called `ld.wsl.conf` which adds `/usr/lib/wsl/lib` to the search path, then runs `/sbin/ldconfig`.  That file also mentions that `[automount]` `ldconfig = false` can be used to disable this behaviour.

Presumably this is similar to the `mountFsTab` option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Configure Linux distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#ways-to-run-wsl)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Agrover112** [comment]
@craigloewen-msft  Any update on this?

**Comment by craigloewen-msft** [comment]
This is a dev feature that isn't intended for public use, so we'll keep it undocumented but available. Thanks for the ping here!
