### ISSUE TITLE
'wsl --install' is not installing default distribution (Ubuntu)

### ISSUE THREAD

**Issue by vvavrychuk** [MicrosoftDocs/WSL#1303]
Page https://docs.microsoft.com/en-us/windows/wsl/install says that from Windows 10 version 2004 and higher (Build 19041 and higher) command `wsl --install` should install Ubuntu by default, but it is not the case for me

```
C:\Users\vvavr>wsl --install
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --cd <Directory>
        Sets the specified directory as the current working directory.
        If ~ is used the Linux user's home path will be used. If the path begins
        with a / character, it will be interpreted as an absolute Linux path.
        Otherwise, the value must be an absolute Windows path.

    --distribution, -d <Distro>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

    --system
        Launches a shell for the system distribution.

Arguments for managing Windows Subsystem for Linux:

    --help
        Display usage information.

    --install [Options]
        Install additional Windows Subsystem for Linux distributions.
        For a list of valid distributions, use 'wsl --list --online'.

        Options:
            --distribution, -d [Argument]
                Downloads and installs a distribution by name.

                Arguments:
                    A valid distribution name (not case sensitive).

                Examples:
                    wsl --install -d Ubuntu
                    wsl --install --distribution Debian

    --set-default-version <Version>
        Changes the default install version for new distributions.

    --shutdown
        Immediately terminates all running distributions and the WSL 2
        lightweight utility virtual machine.

    --status
        Show the status of Windows Subsystem for Linux.

    --update [Options]
        If no options are specified, the WSL 2 kernel will be updated
        to the latest version.

        Options:
            --rollback
                Revert to the previous version of the WSL 2 kernel.

Arguments for managing distributions in Windows Subsystem for Linux:

    --export <Distro> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

        Options:
            --version <Version>
                Specifies the version to use for the new distribution.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are
                currently being installed or uninstalled.

            --running
                List only distributions that are currently running.

            --quiet, -q
                Only show distribution names.

            --verbose, -v
                Show detailed information about all distributions.

            --online, -o
                Displays a list of available distributions for install with 'wsl --install'.

    --set-default, -s <Distro>
        Sets the distribution as the default.

    --set-version <Distro> <Version>
        Changes the version of the specified distribution.

    --terminate, -t <Distro>
        Terminates the specified distribution.

    --unregister <Distro>
        Unregisters the distribution and deletes the root filesystem.

    --mount <Disk>
        Attaches and mounts a physical disk in all WSL2 distributions.

        Options:
            --bare
                Attach the disk to WSL2, but don't mount it.

            --type <Type>
                Filesystem to use when mounting a disk, if not specified defaults to ext4.

            --options <Options>
                Additional mount options.

            --partition <Index>
                Index of the partition to mount, if not specified defaults to the whole disk.

    --unmount [Disk]
        Unmounts and detaches a disk from all WSL2 distributions.
        Unmounts and detaches all disks if called without argument.
```

On the other hand, `wsl --install -d Ubuntu` works fine.

I have windows version dev (os build 21390.2025).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by SimpleSamples** [comment]
Thank you! I got the same using `wsl --install` and the workaround works for me too. This is with 20H2.

**Comment by slonopotamus** [comment]
> On the other hand, `wsl --install -d Ubuntu` works fine.

No, it doesn't. Page says:

> This command will **enable the required optional components**, **download the latest Linux kernel**, **set WSL 2 as your default**, and install a Linux distribution for you (Ubuntu by default, see below to change this).

`wsl --install -d Ubuntu` does neither of those three items on Windows 20H2.

**Comment by slonopotamus** [comment]
Okay, things are *even more complicated*.

With **clean** Windows 20H2, no-arg `wsl --install`** does work** from an elevated console. But if you have WSL1 (`Microsoft-Windows-Subsystem-Linux` feature) or WSL2 (`VirtualMachinePlatform` feature) installed, no-arg `wsl --install` no longer works.

**Comment by slonopotamus** [comment]
I'd score quality of implementation of this feature as -2 on 0-10 scale.

**Comment by crramirez** [comment]
@slonopotamus, I still don't understand your point. `wsl --install` with no arguments is made to install WSL. If you already have WSL installed, you don't need no-arg  `wsl --install`; you need only to install distros. If you want to update the kernel run `wsl --update`

`wsl --install` as you are requesting would be very difficult to implement and error-prone. For example, if you already have WSL1 installed and run `wsl --install`, why it would assume that you want to install WSL2. If you have WSL2, why does running `wsl --install` would make WSL2 by default, etc.

"@microsoft please, hire better programmers and QA." it is not a bug; the command is made on purpose in that way.

**Comment by crramirez** [comment]
Also check this comment for clarifications: https://github.com/MicrosoftDocs/WSL/issues/1408#issuecomment-1004291466

**Comment by slonopotamus** [comment]
If I don't have network connection, `wsl --install` installs `VirtualMachinePlatform` and then... Stops. Now you have half-installed WSL2, without kernel and without distro. And you can't `wsl --install` anymore, because (remember?) `wsl --install` only works when you don't have WSL at all.

> if you already have WSL1 installed and run wsl --install, why it would assume that you want to install WSL2

It doesn't need to assume anything. Don't try to outsmart the user. I'll quote again:

> This command will enable the required optional components, **download the latest Linux kernel**, **set WSL 2 as your default**, and install a Linux distribution for you (Ubuntu by default, see below to change this).

So, your docs clearly indicate that no-arg `wsl --install` is a way to get WSL2.

**Comment by craigloewen-msft** [comment]
As others have said this is because WSL is already installed! We put in a note on the main page to make sure that this is seen by other users, and have fixed this error code in later versions of the product.
https://github.com/MicrosoftDocs/WSL/pull/1433

Thanks for filing this!
