### ISSUE TITLE
Linux and Windows platform containers can't run at the same time

### ISSUE THREAD

**Issue by gthvidsten** [MicrosoftDocs/WSL#1304]
The [documentation](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers) states that:

> By enabling the WSL 2 based engine, you can run both Linux and Windows containers in Docker Desktop on the same machine.

This appears to be untrue, as if you set Docker to use Windows Containers, then you can't start a linux container and you are given the following error:

```
C:\> docker run <someimage>
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (windows/amd64) and no specific platform was requested
```

Manually switching to Linux Containers makes this image work but then Windows images stops working.

This is quite similar to what was asked in #1029, but the solution given there (install a separate docker instance inside the linux distro) is quite unsatisfactory (i.e. containers can then not talk to eachother) and doesn't match the original statement of running both Linux and Windows containers.

So either this original statement needs to be written differently (or more information added), or the entire page needs to be updated to tell us how to actually run both Windows and Linux containers at the same time in the same Docker installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 403a33a6-304c-2ded-9ea8-4d70bc5f17ba
* Version Independent ID: 93b6a9ef-08ba-be90-736e-27515fb0f4da
* Content: [Get started with Docker containers on WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers)
* Content Source: [WSL/tutorials/wsl-containers.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-containers.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks for raising this issue @gthvidsten. While the statement is true that Docker Desktop can run both Linux and Windows containers, it's also true what you're pointing out that they cannot run simultaneously. I added a note to the document pointing this out: https://github.com/MicrosoftDocs/WSL/pull/1445

Thanks for bringing this issue to our attention.
