### ISSUE TITLE
Linux distributions MS Store link is broken

### ISSUE THREAD

**Issue by KdB13** [MicrosoftDocs/WSL#1306]
The below link cannot be opened: https://aka.ms/wslstore.

![image](https://user-images.githubusercontent.com/36751623/136656388-2712d92a-6e3e-45ca-80e5-3dad839c3659.png)

It displays the following message:

![image](https://user-images.githubusercontent.com/36751623/136656450-d63e4309-5219-4962-ae7e-a230fb3bb3c9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3be148fb-e4a9-83b5-5b5a-7834eed7052f
* Version Independent ID: f583bc11-fe60-bb2c-af2b-dc0dae9fe81f
* Content: [What is Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about)
* Content Source: [WSL/about.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/about.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Agrover112** [comment]
Yup it's bwoken.
@mattwojo  Hmm, seems like the aka.ms link is broken? And if i'm not wrong only an Ms employee can generate that link?

**Comment by craigloewen-msft** [comment]
I'm unable to reproduce this issue, it works for me. Are you still seeing this issue?

**Comment by mattwojo** [comment]
Seems to work for me too. This link does aim to open the Microsoft Store _app_ ...so if you're not on a Windows machine where the Microsoft Store app is installed, you may not be able to open the link.

**Comment by Agrover112** [comment]
> I'm unable to reproduce this issue, it works for me. Are you still seeing this issue?

Well it does pompt to open MS Store @mattwojo  and thus fails. Idk even the link fails for me on the web.
