### ISSUE TITLE
WSL Version 1 is installed when following simple installation instructions

### ISSUE THREAD

**Issue by generaldamras** [MicrosoftDocs/WSL#1312]
When I use these new instructions, instead of the old manual method, the WSL 1 version of the distribution gets installed. What I have been running is:

```wsl --install -d  Ubuntu-20.04```

It runs successfully, but when checking the version of WSL installed, using 

```wsl -l -v```

I see that Ubuntu-20.04 is installed as WSL1. Clearly, that shouldn't be the intent of this new approach (and the docs clearly state WSL 2 should be installed).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install#manual-installation-steps)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by iamoverit** [comment]
same here 
![image](https://user-images.githubusercontent.com/4696087/148812786-5ad9c602-a344-41a2-9a69-fd444d741d8b.png)

**Comment by crramirez** [comment]
Hello @generaldamras,

Check this and see if it matches your case: https://github.com/MicrosoftDocs/WSL/issues/1303#issuecomment-1008342599

Regards,
Carlos

**Comment by craigloewen-msft** [comment]
This is because you already have WSL installed and WSL is respecting your current default setting which is WSL 1 distros.

To change this please run: `wsl --set-default-version 2` and now any new WSL installs will give you a WSL 2 distro. (YOu can also use `wsl --set-version <distroname> 2` to set a distro manually.

Thanks for filing!
