### ISSUE TITLE
Windows 11 install broke Kali Linux

### ISSUE THREAD

**Issue by CoolGames** [MicrosoftDocs/WSL#1313]
Note that this repo's issue tracker is only for reporting issues that require an update to the WSL documentation.

Other related issue repo's:

* WSL product repo (for reporting WSL issues, bugs, or feature requests): https://github.com/microsoft/wsl/issues
* WSLg repo (for reporting issues related to WSL GUI apps): https://github.com/microsoft/wslg/issues
* Windows Terminal repo (for reporting issues related to the Terminal shell): https://github.com/microsoft/terminal/issues
* Windows Console repo (For reporting issues with CMD): https://github.com/MicrosoftDocs/Console-Docs/issues

**Need additional section in DOCUMENTATION for issues with Windows 11**

$  wsl
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization

$ wsl --status
Default Distribution: kali-linux
Default Version: 2
WSL version: 0.47.1.0
Kernel version: 5.10.60.1
WSLg version: 1.0.29
Windows version: 10.0.22000.194

$  Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

FeatureName      : Microsoft-Windows-Subsystem-Linux
DisplayName      : Windows Subsystem for Linux
Description      : Provides services and environments for running native user-mode Linux shells and tools on Windows.
RestartRequired  : Possible
State            : Enabled
CustomProperties :
                   ServerComponent\Description : Provides services and environments for running native user-mode Linux
                   shells and tools on Windows.
                   ServerComponent\DisplayName : Windows Subsystem for Linux
                   ServerComponent\Id : 1033
                   ServerComponent\Type : Feature
                   ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
                   ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux

**Comment by mattwojo** [comment]
Thanks @CoolGames -- Closing this as it doesn't appear to relate to a WSL docs update. You can file an issue in the WSL product repo at https://github.com/Microsoft/wsl/issues if Kali install is something related to WSL breaking with Windows 11 and the issue template will ask for more info.
