### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by friedpa** [MicrosoftDocs/WSL#1314]
I would really love to use this feature, which is long time overdue, but I have a Microsoft Surface Pro, which is unfortunately not compatible with Microsoft Windows 11, but I guess tough luck for a Microsoft customer ....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Hi this is a common support request that we have for WSLg, and we're investigating the best way to support this. You can follow at this thread here: 
https://github.com/microsoft/wslg/issues/414

Thank you for filing!
