### ISSUE TITLE
You don't need to install another Linux distribution for Docker to work

### ISSUE THREAD

**Issue by joemeree** [MicrosoftDocs/WSL#1315]
[Enter feedback here]
To get the Docker Desktop installed and working, I only had to enable WSL in the control panel.  I didn't have to install a Linux distribution.  The little one that comes by default worked.  The big things: 
1. Enable virtualization in the bios
2. Enable hyper-v in the control 
3. Enable wsl in the control panel
4. Install the Docker Desktop for Windows. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 403a33a6-304c-2ded-9ea8-4d70bc5f17ba
* Version Independent ID: 93b6a9ef-08ba-be90-736e-27515fb0f4da
* Content: [Get started with Docker containers on WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers)
* Content Source: [WSL/tutorials/wsl-containers.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-containers.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @joemeree. I'm not sure that I'm understanding exactly what you're suggesting we update in this doc. Could you be more specific in how you feel this should be updated?

**Comment by joemeree** [comment]
Sorry,
That was so long ago I forgot.
Joe

Joe Meree  703-967-4730  ***@***.******@***.***>

**Comment by mattwojo** [comment]
No worries @joemeree  - closing this, but please feel welcome to reopen if you run into this issue again and think it could use better documentation.
*I deleted your response as it had your personal contact info in it and guessing you didn't mean to include that. :)
