### ISSUE TITLE
Date jumps to 08-07-3209 in Windows 11 Recent Builds with Virtual Machine Platform feature enables for WSL, 22000.258 no fix yet.

### ISSUE THREAD

**Issue by adamlahbib** [MicrosoftDocs/WSL#1316]
It occurs on every boot up, restart, wake up from sleep, sometimes randomly and exactly just after the first hour of up time is reached.
The issue still happens on Builds 22000.194 and 22000.258

The only workaround for now, is to disable Virtual Machine Platform which in turn will disable access to WSL 😢
Looking for a better solution...

I thought since the issue is related to Virtual Machine Platform maybe I can replace that feature files/version with older well working one from Windows 10, I am willing to take a bit of risk over here for WSL since I use it a lot, how can I proceed?

**Comment by craigloewen-msft** [comment]
Can you please file Windows Feedback for this, to the Hyper-V section via feedback hub? (You can open that up using Windows Key +F). That would ensure that the relevant engineers for this issue would be able to see this. (This doc is just for the documentation). Thanks!

More info here:
[Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332)

**Comment by aq1sept** [comment]
22000.318 no fix yet(
