### ISSUE TITLE
Confusion with supported Windows version

### ISSUE THREAD

**Issue by garetho-starwind** [MicrosoftDocs/WSL#1317]
Notes in the text state that this only works with Windows 11, yet the screen shots at the top of the page clearly show Windows 10 running the Linux GUI apps,

Is there a way to get the Linux GUI apps in Windows 10?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Linux GUI apps are not supported in Win10, only Windows 11, we will work on fixing the screenshots! Thank you!

/dupe #1324
