### ISSUE TITLE
This page seems out of date - there is no --mount option for wsl in powershell

### ISSUE THREAD

**Issue by MarioAtTrimble** [MicrosoftDocs/WSL#1318]
using powershell to try to execute a `wsl --mount \\.\PHYSICALDRIVE0` against my installed wsl2/ubuntu 20.04, I cannot perform the command.  I get `Invalid command line option: --mount`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e255b0-71c7-adc6-cac0-6df3b76a971f
* Version Independent ID: a9d73ca3-7026-5b5a-f3fe-3511e976cde4
* Content: [Get started mounting a Linux disk in WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk)
* Content Source: [WSL/wsl2-mount-disk.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-mount-disk.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
Read the Prerequisites again:

> You will need to be on Windows 11 Build 22000 or higher to access this feature. You can join the Windows Insiders Program to get the latest preview builds.

**Comment by craigloewen-msft** [comment]
@Biswa96 is correct, this is due to your Windows version, please upgrade to Win11 to use wsl --mount!
