### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by leechen** [MicrosoftDocs/WSL#1320]
I am getting the follow error:

PS C:\Windows\WinSxS> wsl --install
wsl : The term 'wsl' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At line:1 char:1
+ wsl --install
+ ~~~
    + CategoryInfo          : ObjectNotFound: (wsl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
I made sure I am using powershell (not x86). Is there pre-requisite to run this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by SimpleSamples** [comment]
What version of Windows? Probably not a relevant version. I got the same message and then I turned on WSL but I won't provide details of that since that will not make `wsl --install` work either. You need to either join the Insiders Program and install a relevant version or wait until a version of Windows is released that supports that option of the command.

**Comment by craigloewen-msft** [comment]
This error is due to you being on too low of a Windows version to have this --install feature. Please ensure you're on the latest Win11 or Win10 builds, or use the manual install instructions: https://docs.microsoft.com/en-us/windows/wsl/install-manual
