### ISSUE TITLE
invalid command line option

### ISSUE THREAD

**Issue by leechen** [MicrosoftDocs/WSL#1321]
[Enter feedback here]

After I manually turn on Windows Subsystem Linux and restart my PC, I tried the command to install a Linux distribution. Now I get:

PS C:\WINDOWS\system32> wsl --install
Invalid command line option: --install
Usage: wsl.exe [option] ...
Options:
    -d, --distribution <DistributionName>
        Launch the specified distribition.

    -e, --exec <CommandLine>
        Execute the specified Linux command. The remainder of the arguments are
        used as the command line to execute.

    -u, --user <UserName>
        Run as the specified user.

    --help
        Display this usage information.

    --
        Stop parsing arguments and pass the remainder to the Linux process.
PS C:\WINDOWS\system32>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by SimpleSamples** [comment]
What version of Windows? I got the same when I was using the current release of Windows. You need to either join the Insiders Program and install 20H2 or wait until it is released (soon).

**Comment by craigloewen-msft** [comment]
This error is due to you being on too low of a Windows version to have this `--install` feature. Please ensure you're on the latest Win11 or Win10 builds, or use the manual install instructions: https://docs.microsoft.com/en-us/windows/wsl/install-manual
