### ISSUE TITLE
Win10 Home WSL install finish and create account, but use powershell input "wsl" not auto login in Ubuntu

### ISSUE THREAD

**Issue by owen9928338** [MicrosoftDocs/WSL#1322]
Win10 Home WSL install finish and create user("owen"), but use powershell input "wsl" not auto login in Ubuntu
Can someone help to solve it?

![image](https://user-images.githubusercontent.com/22093272/137581756-4458654f-0a78-485f-a254-ef0bf7e886dd.png)

But I use change Ubuntu system，this user ("owen") is already.

![image](https://user-images.githubusercontent.com/22093272/137581933-2b02fad1-a171-4bd1-b630-147bafe28fcc.png)

**Comment by Biswa96** [comment]
Set Ubuntu-20.04 as default distribution. According to your provided screenshot, the current default distribution is docker-desktop-data.

**Comment by craigloewen-msft** [comment]
@Biswa96 is correct! Please run `wsl -s Ubuntu-20.04` to set Ubuntu-20.04 as your default distro and that will resolve you.
Thanks!
