### ISSUE TITLE
WSL2 Neo4j

### ISSUE THREAD

**Issue by GoncaloAC** [MicrosoftDocs/WSL#1323]
I have been trying to install Neo4j in WSL2 but since there is no Microsoft official tutorial i can't seem to be able to.
Im following a tutorial that gives me every step but its for Ubuntu, not WSL2 Ubuntu. Could this be an issue? The steps are:

- sudo apt update
- sudo apt install apt-transport-https ca-certificates curl software-properties-common
- curl -fsSL https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
- sudo add-apt-repository "deb https://debian.neo4j.com stable 4.1"
- sudo apt install neo4j
- sudo systemctl enable neo4j.service
- sudo systemctl status neo4j.service
And then connecting. I have seen that systemctl isn't supported or wasnt at the time i saw the issue here. Is this still the case? If so how can i get arround this to make it work?

**Comment by Agrover112** [comment]
Are you sure this is a WSl problem? or a Neo4J problem?

**Comment by Agrover112** [comment]
@GoncaloAC  Did you try https://askubuntu.com/questions/1132230/unable-to-run-any-systemd-services-in-wsl
Also found this https://github.com/lqst/neo4j-wsl2 hope this answers your question?

**Comment by mattwojo** [comment]
THanks for filing this @GoncaloAC. These commands are trying to use systemctl, which requires systemd and isn't supported by WSL. Please try instead using `sudo service <servicename> start`.  If this doesn't work, try filing this issue in the wsl product repo: https://github.com/Microsoft/wsl/issues 
Closing. Please reopen if you feel this needs further discussion or an update to the docs. Thanks!
