### ISSUE TITLE
Update screenshots to use Windows 11 screenshots for clarification

### ISSUE THREAD

**Issue by Poopooracoocoo** [MicrosoftDocs/WSL#1324]
Someone thought that you could run Linux apps with GUI on Windows 10 release builds. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Good call. Windows 11 wasn't released yet when I made these screenshots. I was running a developer build and we wanted to get this out so that Windows Insiders could try it. Time for an update!!

**Comment by Agrover112** [comment]
@mattwojo Added a new SS.
