### ISSUE TITLE
Driver links do not open in new window

### ISSUE THREAD

**Issue by kw217** [MicrosoftDocs/WSL#1329]
Hi - the links to drivers (e.g., "Intel GPU driver for WSL") have the "open in new window" icon next to them, but they do not open in a new window - instead they open in the same window, meaning I have to click "back" to get back to this page.

Please make them open in a new window.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hi @kw217 - That icon is indicating that the link points to a site outside of the docs.microsoft.com site, not that it will open in a new tab. I was told that the docs.microsoft platform did a study and found that developers would prefer not to have links forced into a new tab, but would rather have the option to open in same tab or you can have them open in a new tab by holding the 'Ctrl' key when you click or right-click, "Open in new tab".
