### ISSUE TITLE
Updated link to Setup Windows Terminal > Powerline

### ISSUE THREAD

**Issue by gohelh-adsk** [MicrosoftDocs/WSL#1331]
In the section [Setup Windows Terminal](https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup), link to [Powerline](https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup) is broken. Correct link may be https://docs.microsoft.com/en-us/windows/terminal/tutorials/custom-prompt-setup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8226ebd3-6c2a-17aa-3a27-cffb4a5d0a57
* Version Independent ID: 06d3a4ce-218a-d39d-4a71-60a3cb86e422
* Content: [Best practices for setting up a WSL 2 development environment](https://docs.microsoft.com/en-us/windows/wsl/setup/environment#set-up-your-linux-user-info)
* Content Source: [WSL/setup/environment.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/setup/environment.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Good catch. Thanks @gohelh-adsk!  Updated the link to point to the new Terminal tutorial.
