### ISSUE TITLE
Typo in example command

### ISSUE THREAD

**Issue by Kuzirashi** [MicrosoftDocs/WSL#1333]
`/dev/sbd` should be `/dev/sdb` : )

"Using the example from above, we changed the vhd size to 512000, so the command would be: sudo resize2fs /dev/sbd 512000M."

If you use wrong command state currently you'll get error:
```
sudo resize2fs /dev/sbd 512000M
resize2fs 1.45.5 (07-Jan-2020)
open: No such file or directory while opening /dev/sbd
```

`/dev/sdb` works correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c96a605e-9f3c-41b4-b964-412572fccd41
* Version Independent ID: 6734e772-029a-9d2c-fef7-435faf8e0cac
* Content: [Expand the size of your WSL 2 Virtual Hard Disk](https://docs.microsoft.com/en-us/windows/wsl/vhd-size)
* Content Source: [WSL/vhd-size.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/vhd-size.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Kuzirashi** [comment]
It's harder the other way around, because this issue is 17 days old and the other is 1 day old :D but thanks for taking a look!

**Comment by craigloewen-msft** [comment]
Haha you're right of course! This was just because of how we did triage yesterday :)
