### ISSUE TITLE
WSL Server execution failed

### ISSUE THREAD

**Issue by emrood** [MicrosoftDocs/WSL#1335]
* WSL  has stopped since last update.  Windows 11 (OS Build 22483.1011)
![Screenshot 2021-10-29 122537](https://user-images.githubusercontent.com/29743781/139470214-13d1782e-56f0-4b80-b7d4-a65da2eb2e0d.jpg)

**Comment by craigloewen-msft** [comment]
Can you please file this at https://github.com/microsoft/wsl with the template info? That will help us determine what your problem is and how to fix it.
Thank you!
