### ISSUE TITLE
Came here for 7th million time from notification in vscode about performance ...storage...

### ISSUE THREAD

**Issue by menjic** [MicrosoftDocs/WSL#1336]
THIS PAGE DOES NOT CONTAIN ANYTHING ABOUT THIS !!!! 
Or not anything exactly but it does not contain anything to solve the problem if it is the problem in the first place !!!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f5d8ca6-c500-72ca-60ae-73ef0ac489ad
* Version Independent ID: 10a6919c-5152-2aa3-4d90-ccfa45cbbcc5
* Content: [Comparing WSL 1 and WSL 2](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#performance-across-os-file-systems)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
What notification are you seeing? Does the error say that you should store your files in the Linux file system instead?

**Comment by craigloewen-msft** [comment]
Tagging @bamurtaugh, can we change the VS Code notification to point to this link instead?

https://docs.microsoft.com/windows/wsl/setup/environment#file-storage

**Comment by menjic** [comment]
Yes, but they are if I am seeing it correctly ??

**Comment by bamurtaugh** [comment]
Thanks for the awareness @craigloewen-msft! Looking at this now.
