### ISSUE TITLE
How do we access service listening on loopback IPv4 address other than 127.0.0.1

### ISSUE THREAD

**Issue by JiandongRuan** [MicrosoftDocs/WSL#1337]
[Enter feedback here]
[RFC 3330](https://www.rfc-editor.org/rfc/rfc3330) reserve entire 127.0.0.0/8 block for loopback. It looks like WSL2 expose only 127.0.0.1

Are other loopback addresses, for example, 127.0.0.12 supported? If so, how can one enable it? The `netsh interface portproxy add v4tov4 ...` doesn't seem to work. If not, can you make this as a feature request for the future WSL2 release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5f3211d-52bd-3566-874a-5c78cb01ddd0
* Version Independent ID: f9e21bfa-6316-7d45-3b34-834a78bcaf0f
* Content: [Accessing network applications with WSL](https://docs.microsoft.com/en-us/windows/wsl/networking)
* Content Source: [WSL/networking.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/networking.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Right now 127.0.0.1 is the only loopback address that's supported. 

Could you please file this as a feature request at: https://github.com/microsoft/wsl ? 

Thank you!
