### ISSUE TITLE
I got access denied when I tried to mount a USB drive 

### ISSUE THREAD

**Issue by chenblueridge** [MicrosoftDocs/WSL#1338]
I got "access denied" when I tried to mount a USB drive. The USB drive can be listed in the query with the right size. 

I tried to mount the drive when the WSL2 was running or in shutdown mode. The USB disk is ext4, and I tested this in a powershell as Admin
#### Document Detail
⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e255b0-71c7-adc6-cac0-6df3b76a971f
* Version Independent ID: a9d73ca3-7026-5b5a-f3fe-3511e976cde4
* Content: [Get started mounting a Linux disk in WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk)
* Content Source: [WSL/wsl2-mount-disk.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-mount-disk.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Is it a flash drive or USB disk? We do not have support for certain kinds of USB devices, which is listed in the doc

**Comment by mattwojo** [comment]
Closing. If you feel this issue needs further discussion or should result in an update to the docs, please re-open. Thanks for contributing @chenblueridge!
