### ISSUE TITLE
What is the unit used to specify the memory allocation?

### ISSUE THREAD

**Issue by imanabu** [MicrosoftDocs/WSL#1340]
[Enter feedback here]
The document (and in general many other documents) is not immediately clear as to the unit of memory allocation. Please qualify any numeric values in documentation with a unit, or when different units are possible like "2 GB" or "10 ms" then what units are possible as well. Specific to the memory allocation, is it in the unit of bytes, kb, mg or gb?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Configure Linux distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hi @imanabu - I'm not sure that I understand. It looks like this document does provide the unit used to specify memory allocation (GB). Are you asking for further clarity on whether this can be fine-tuned to use MB or KB? Or am I maybe missing another place where I should add more clarity to this doc?  Thanks for filing this issue - if you could provide a little more context for how you would like to see the doc updated, I'll see what I can do.

![image](https://user-images.githubusercontent.com/7566797/141203067-90623c92-298b-4156-ba2a-094833843e9b.png)

![image](https://user-images.githubusercontent.com/7566797/141203202-b91aa63a-2fc0-43bd-a8ee-4d14a2d28c17.png)

**Comment by mattwojo** [comment]
Closing - please reopen if you can provide more context or let me know a few more specifics about what sort of doc update would be helpful. Thank you!
