### ISSUE TITLE
Seems like steps are missing from this document.

### ISSUE THREAD

**Issue by EbcdicZ** [MicrosoftDocs/WSL#1341]
I am getting this after following the examples and directions in this document.

$ gedit ~/.bashrc
Unable to init server: Could not connect: Connection refused

(gedit:1033): Gtk-WARNING **: 09:09:02.241: cannot open display:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
You're seeing this issue since you don't have GUI apps enabled in your WSL instance. Please see this URL for instructions on how to set it up:
https://github.com/microsoft/wslg#pre-requisites

**Comment by EbcdicZ** [comment]
Thanks. Sent from Mail for Windows From: Craig LoewenSent: Thursday, November 11, 2021 1:14 PMTo: MicrosoftDocs/WSLCc: EbcdicZ; AuthorSubject: Re: [MicrosoftDocs/WSL] Seems like steps are missing from this document. (Issue #1341) Closed #1341.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
