### ISSUE TITLE
Installation commands insufficient

### ISSUE THREAD

**Issue by Michagogo** [MicrosoftDocs/WSL#1343]
I tried to enable WSL on a new machine, ran the commands listed on the page (the two `dism.exe` commands), but was unable to continue - the `wsl` command didn’t exist. Turns out I needed to use `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux` as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manual installation steps for older versions of WSL](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
The command with dism.exe is exact equivalent of Enable-WindowsOptionalFeature cmdlet.

**Comment by craigloewen-msft** [comment]
This is likely due to versioning, and says so at the top of the --install page. Glad you got this sorted out, we expect this to improve as more people move to later Windows versions!
