### ISSUE TITLE
Changing hyperlink to more correct location

### ISSUE THREAD

**Issue by itayporezky** [MicrosoftDocs/WSL#1345]
Fixing link to be more correct,
there is a hyperlink [here](https://docs.microsoft.com/en-us/windows/wsl/install-on-server#download-a-linux-distribution) which points to [here](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
change the hyperlink to [here](https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-on-server.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Done: https://github.com/MicrosoftDocs/WSL/commit/4221c0733f88561db8143f0cd2f1babecc42f472
Thanks @itayporezky. Appreciate the contribution and effort to make things easier and more direct.
