### ISSUE TITLE
Open PowerShell as Administrator

### ISSUE THREAD

**Issue by Temps-William** [MicrosoftDocs/WSL#1347]
How do I do that? Why assume that the reader knows how to do that? Isn't the purpose of documentation to explain how to do things for people who don't already know? Start menu, find "Windows PowerShell", right-click, select "Run as Administrator". How hard would it be to add that?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manual installation steps for older versions of WSL](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @Temps-William. Ha... you're right, not hard... added with https://github.com/MicrosoftDocs/WSL/commit/2372fe0584e12a4147a82c5f231ae8bfd5795928

It can be easy to forget to be explicit about things like this for those of us immersed in it. Thanks for the reminder.
