### ISSUE TITLE
The requested operation requires elevation

### ISSUE THREAD

**Issue by Temps-William** [MicrosoftDocs/WSL#1348]
[Enter feedback here]
The very first command in the process, "wsl --install", immediately gave me an error message: "The requested operation requires elevation". That error is not explained or even acknowledged anywhere on this page. It isn't even mentioned in the Troubleshooter page. "From the Windows Start menu, scroll down to Windows PowerShell, right click on it, and select Run as Administrator. Then enter wsl --install in the PowerShell window." How hard is that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This is a great suggestion! I've updated the issue here:
https://github.com/MicrosoftDocs/WSL/commit/64e792dd2674a644ecc9d51f568aa15022b329a5
