### ISSUE TITLE
Installation command doesn't work

### ISSUE THREAD

**Issue by mkiaei** [MicrosoftDocs/WSL#1350]
WSL installation command does nothing. Other people seem to have the same issue. The following workaround worked for me:

wsl.exe --install -d Ubuntu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install#feedback)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
Check if your OS version meets the prerequisites.

**Comment by mkiaei** [comment]
It does. I'm running Windows 10.

**Comment by craigloewen-msft** [comment]
What command were you running before? `wsl --install` should always work.

Closing this issue out as I wasn't able to repro it, please reopen if you're still seeing this.

**Comment by mkiaei** [comment]
I used "wsl --install", but it doesn't work.

Not being able to repro the bug is not a good reason to close it! Please
update the documentation as it is a common issue among other users. Check
this thread for other users facing the same issue.

https://github.com/MicrosoftDocs/WSL/issues/1054

Thanks,
Mohammad

**Comment by michaelgwelch** [comment]
Yeah, I'm running Windows 21H1 and `wsl --install` just says invalid command line option: --install. Running `wsl help` shows no install option. There must be some other prerequisite needed other than minimum version of Windows.

```bash
> wsl --help
Copyright (c) Microsoft Corporation. All rights reserved.
Usage: wsl.exe [Argument] [Options...] [CommandLine]
Arguments for running Linux binaries:
    If no command line is provided, wsl.exe launches the default shell.
    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.
    --
        Pass the remaining command line as is.
Options:
    --distribution, -d <Distro>
        Run the specified distribution.
    --user, -u <UserName>
        Run as the specified user.
Arguments for managing Windows Subsystem for Linux:
    --export <Distro> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.
    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.
        Options:
            --version <Version>
                Specifies the version to use for the new distribution.
    --list, -l [Options]
        Lists distributions.
        Options:
            --all
                List all distributions, including distributions that are currently
                being installed or uninstalled.
            --running
                List only distributions that are currently running.
            --quiet, -q
                Only show distribution names.
            --verbose, -v
                Show detailed information about all distributions.
    --set-default, -s <Distro>
        Sets the distribution as the default.
    --set-default-version <Version>
        Changes the default install version for new distributions.
    --set-version <Distro> <Version>
        Changes the version of the specified distribution.
    --shutdown
        Immediately terminates all running distributions and the WSL 2 lightweight utility virtual machine.
    --terminate, -t <Distro>
        Terminates the specified distribution.
    --unregister <Distro>
        Unregisters the distribution.
    --help
        Display usage information.
```

would be helpful if the help option included the version of `wsl`.
