### ISSUE TITLE
Small typo in WSL>Expand virtual hard disk size

### ISSUE THREAD

**Issue by L61** [MicrosoftDocs/WSL#1351]
In the line "Using the example from above, we changed the vhd size to 512000, so the command would be: sudo resize2fs /dev/sbd 512000M", there is a typo in the name of the device: it should be "sdb", and not "sbd"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c96a605e-9f3c-41b4-b964-412572fccd41
* Version Independent ID: 6734e772-029a-9d2c-fef7-435faf8e0cac
* Content: [Expand the size of your WSL 2 Virtual Hard Disk](https://docs.microsoft.com/en-us/windows/wsl/vhd-size)
* Content Source: [WSL/vhd-size.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/vhd-size.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @L61! Fixed in https://github.com/MicrosoftDocs/WSL/commit/317bb177241112ae8c6371adc0541f0d0a1061c6
