### ISSUE TITLE
Latest WSL cannot connect to server

### ISSUE THREAD

**Issue by 123Alpha** [MicrosoftDocs/WSL#1358]
I just installed the latest WSL for Windows 11, but am still unable to run any of the GUI applications I have installed. Maybe I don't know how to do it correctly, or maybe I have something wrong. I have tried to follow the steps outlined in the various videos, but nothing seems to work.  I thought that this was supposed to be easy, but so far I am unable to get it working. Last attempt with Ubuntu 20.04 LTS message says: Gtk-WARNING **: 07:30:59.144: cannot open display:
I am running insider edition Windows 11 Pro Version 21Hw OS build 22000.346 Windows Feature Experience Pack 1000.22000.346.0

Can anyone clearly explain how to get this working?  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Have you run `wsl --update` in an elevated prompt? 

Could you also see the install instructions at: https://aka.ms/wslg and follow those? 

Doing those should give you access! Thanks!

**Comment by johnmcfarlane** [comment]
Following instructions did not help. However, removing previously-installed X11 server, VcXsrc seemed to be what was necessary for `wsl --update` to pull down the necessary updates.
