### ISSUE TITLE
wsl --install doesn't actually install anything (?)

### ISSUE THREAD

**Issue by jasonpolites** [MicrosoftDocs/WSL#1361]
Documentation states:

_"You can now install everything you need to run Windows Subsystem for Linux (WSL) by entering this command in an administrator PowerShell or Windows Command Prompt and then restarting your machine."_

`wsl --install` does not actually install anything, it simply lists the help for the wsl CLI

I'm trying to update to WSL 2, but it's pretty difficult to find out how to do that. There are instructions on how to [install an "older"](https://docs.microsoft.com/en-us/windows/wsl/install-manual) version (which is not really what I want)

How does one actually install WSL 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
You already have WSL installed. We've put in a fix to show a more useful help message when you run `wsl --install` with WSL already installed. To upgrade to WSL 2 please see these install steps:

https://docs.microsoft.com/en-us/windows/wsl/install-manual#step-2---check-requirements-for-running-wsl-2

Thanks!
