### ISSUE TITLE
Guide should include instructions for upgrading an existing Linux distribution

### ISSUE THREAD

**Issue by jasonpolites** [MicrosoftDocs/WSL#1362]
I had a WSL v1 installation, and wanted to upgrade to v2. After poking around, I realized that the guide for [Manual installation steps for older versions of WSL](https://docs.microsoft.com/en-us/windows/wsl/install-manual#step-2---check-requirements-for-running-wsl-2) is, somewhat unexpectedly, what I needed.

It seems that the last step of _upgrading_ one's existing Linux distribution is missing from this guide however. I recommend adding a note to Step 6 in the guide for *Upgrading an Existing Distribution*. For me, this involved executing the following command:

```
wsl --set-version Ubuntu-20.04 2
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manual installation steps for older versions of WSL](https://docs.microsoft.com/en-us/windows/wsl/install-manual#step-2---check-requirements-for-running-wsl-2)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
The `--set-version` command line option is already documented here https://docs.microsoft.com/en-us/windows/wsl/basic-commands

**Comment by jasonpolites** [comment]
Sure.. I guess the suggestion was to put this in the guide that tells folks how to update to WSL 2. I found I had to do a bunch of Google searches and found the info on an external site. Reading the full CLI docs to try to infer what is needed is not always easy.

**Comment by Biswa96** [comment]
Your query maybe somewhat misleading. The `--set-version` option is not "upgrading" or "updating" the GNU/Linux distribution in WSL environment. It is just converting from WSL1 to WSL2 or vice-versa.

**Comment by jasonpolites** [comment]
For a user moving from WSL 1 to WSL 2, I suspect many might think of this as an _upgrade_. But regardless, _converting_ the existing distribution is a necessary step for anyone who already has a distro in v1 and wants to use v2, but this step is not currently included in the docs.

Look.. I don't mind either way. I'm just a user out here who struggled with the steps in the process and thought I'd make a suggestion to improve them.  🤷‍♂️

**Comment by craigloewen-msft** [comment]
I like the suggestion of making a clearer path for users to "Upgrade to WSL 2" on our docs. Tagging @mattwojo here for visibility!

**Comment by mattwojo** [comment]
Yep -- this is my ongoing struggle, LOL -- how do I make the content in our docs the most straight-forward and easy to find based on what our users are searching for -- not an easy task and sometimes I do better than others. :)  Really appreciate your feedback @jasonpolites!  And your clarifications are always helpful @Biswa96! Thank you both.

I'll add an "Upgrade to WSL 2" section in that manual install section and see if I can do some better search engine optimization   to ensure that anyone seeking this is lead straight to the right answer.

**Comment by mattwojo** [comment]
I've started a new PR where I'm planning to make several updates to the WSL docs in hopes of improving discoverability and make it easier for WSL users to find answers to their most common tasks and questions. > https://github.com/MicrosoftDocs/WSL/pull/1365

I welcome any suggestions or feedback and thanks again!

**Comment by mattwojo** [comment]
Added you recommendation: https://github.com/MicrosoftDocs/WSL/pull/1365/files
Closing this issue.
