### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by anorm** [MicrosoftDocs/WSL#1366]
In the first paragraph, it says:

> Case-insenstive: FOO.text = foo.txt = Foo.txt

(I think) it should say:

> Case-insenstive: FOO.txt = foo.txt = Foo.txt

The extension on the first filename should be `.txt`, not `.text`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55bfa87f-2977-009e-1a13-c844aec74d4c
* Version Independent ID: f34957bd-4973-b87a-b0c4-095790c7add4
* Content: [Case Sensitivity](https://docs.microsoft.com/en-us/windows/wsl/case-sensitivity)
* Content Source: [WSL/case-sensitivity.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/case-sensitivity.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Fixed! Thank you for the feedback!
https://github.com/MicrosoftDocs/WSL/commit/fde5a29cf2aafb6ebaf9498b6b06e8f5d09f1340
