### ISSUE TITLE
unknown filesystem type 'devtmpfs'

### ISSUE THREAD

**Issue by Leander250** [MicrosoftDocs/WSL#1367]
Hi, i got a problem with one of the documentation steps. I get the error:
```
mount: /dev: unknown filesystem type 'devtmpfs'
```
after executing:
```
sudo mount -t devtmpfs none /dev
```
Then
```
mount | grep ext4
```
was executed succesfully without output.
But then the "/dev" folder contains nothing that begins with "sd". 

I use WSL 2 with Ubuntu 20.04 LTS.

**Comment by Biswa96** [comment]
Why do you want to mount /dev? It's alrwdy mounted by init process.

**Comment by Leander250** [comment]
I just execute all commands step by step from this doc page (step 6): https://docs.microsoft.com/en-us/windows/wsl/vhd-size

What should i use instead of /dev?

**Comment by Biswa96** [comment]
Alright. Understood. Make sure your distribution is running in WSL2 environment. The `wsl.exe -l -v` or `wsl.exe --list` command shows the details.

**Comment by Leander250** [comment]
You were absolutley right! I was actually using WSL 1 even though i was sure i am using WSL 2. Thank you!

**Comment by mattwojo** [comment]
Added a reminder in the walk-through. https://github.com/MicrosoftDocs/WSL/commit/e0ccc1581ca0684b4100fc66c57b336e06bc2e6e

Closing - thanks for filing @Leander250!
