### ISSUE TITLE
Please clarify if these apps can interact with the rest of Windows 11?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/WSL#1368]
I installed flameshot, which is like the Windows snipping tool. Upon launch, it seems to go nowhere. Are there some types of apps that cannot interact with the rest of the Windows environment? If so, can this limitation be described?

Other related issue repo's:

* WSL product repo (for reporting WSL issues, bugs, or feature requests): https://github.com/microsoft/wsl/issues
* WSLg repo (for reporting issues related to WSL GUI apps): https://github.com/microsoft/wslg/issues
* Windows Terminal repo (for reporting issues related to the Terminal shell): https://github.com/microsoft/terminal/issues
* Windows Console repo (For reporting issues with CMD): https://github.com/MicrosoftDocs/Console-Docs/issues

**Comment by mattwojo** [comment]
Thanks for filing this issue @Mike-Crowley. 
Support for GUI apps on WSL does not provide a full desktop experience. It relies on Windows desktop, so installing desktop-focused tools like this may not be supported. It looks like that's what you're running into here from what I can tell. You can request support for this app by filing an issue in the [WSLg repo on GitHub](https://github.com/microsoft/wslg/issues) if you'd like. 
I also added a note to clarify this in the WSL GUI doc:  
https://github.com/MicrosoftDocs/WSL/commit/1fbbdfbe1861f6369daa0923bb698bc8b8c3d09b

Thanks again!
