### ISSUE TITLE
Docker Desktop is not free anymore in enterprise context, change to native docker under WSL?

### ISSUE THREAD

**Issue by zerweck** [MicrosoftDocs/WSL#1369]
Since Docker Desktop is not free anymore in an enterprise context, maybe this page could refer to installing the docker daemon under WSL natively?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 403a33a6-304c-2ded-9ea8-4d70bc5f17ba
* Version Independent ID: 93b6a9ef-08ba-be90-736e-27515fb0f4da
* Content: [Get started with Docker containers on WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers)
* Content Source: [WSL/tutorials/wsl-containers.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-containers.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks for filing this @zerweck.  I just added a note about directly installing a container engine on Linux rather than using Docker Desktop: https://github.com/MicrosoftDocs/WSL/commit/7227be6d104ba7d3600aa696f1a1b6f6e17f318d
Appreciate the suggestion. :)
