### ISSUE TITLE
The teams instructions may be missing some dependencies

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/WSL#1370]
This article may be making some assumptions about the order of events. I installed WSL and then tried to immediately install teams per the instructions here but teams would never appear, after typing 'teams' in the wsl terminal. Only after I installed gedit did teams start working.

When I installed gedit, using the commands provided, it took 5 minutes to download all the content necessary for a text editor. I assume there may be some desktop elements that Teams relies on as part of this package, but the instructions here don't include those prerequisites.

**Comment by mattwojo** [comment]
Thanks for filing @Mike-Crowley. Hmm... I'll investigate this. I'm not sure why installing gedit would make the Teams app install work..? I'm not aware of any prerequisites, but will see what I can find out.

**Comment by Mike-Crowley** [comment]
Yeah, I'm sure its not related to gedit, but installing it pulled in some prerequisites that teams seems to need. If you do a new WSL install and try to install teams immediately, it won't work. or at least it didn't when I made this post last year.

**Comment by mattwojo** [comment]
Well I finally got around to trying a WSL GUI + Teams fresh install and it seemed to work fine. Maybe a bug that was resolved since you first filed back in November..? 
I'm going to close, but please reopen if this issue comes up again. ...and thanks for contributing this issue!
