### ISSUE TITLE
Windows10 21H2 Supports for GPU in WSL

### ISSUE THREAD

**Issue by Sherry520** [MicrosoftDocs/WSL#1371]
Windows10 21 H2 have sipported for "GPU accelerated machine learning training in the Windows Subsystem for Linux"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30014605-59f7-d46f-fb2a-2d377e1b35dd
* Version Independent ID: 79e03484-4087-6c87-3a9f-9c0dab188fd2
* Content: [GPU accelerated ML training in WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gpu-compute)
* Content Source: [WSL/tutorials/gpu-compute.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gpu-compute.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Yes we do have support for GPU compute in that version! :)
