### ISSUE TITLE
How do I revert the upgraded Intel Graphic driver 

### ISSUE THREAD

**Issue by wwang2016** [MicrosoftDocs/WSL#1372]
I followed the article (https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps) to upgrade intel graphic driver and upgrade WSL to allow Linux app to start from WSL.

However, I found out that user experience is very bad:
(1) I am experiencing Task manager flickering every day
(2) The apps like Eclipse started from WSL exits many times during a day. It is a lot worse than when I used X server to support Linux app

How do I revert the upgrade?

Thx!
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Oh Bummer! This is the first that I've heard about the flickering Task manager and Eclipse dropping out. Sounds frustrating - sorry you're having that issue. I don't know that there's anything much that can be done on our side, but might be worth letting Intel know (?): https://www.intel.com/content/www/us/en/support/articles/000005848/graphics.html

In regard to uninstalling an Intel driver, you can find instructions to do this on the Intel site here: https://www.intel.com/content/www/us/en/support/articles/000005598/graphics.html
Closing - but please feel welcome to re-open if you think we need to add something to what Intel offers in the WSL docs. 
Thanks for filing @wwang2016
