### ISSUE TITLE
Please mention about adding to the sudoers file

### ISSUE THREAD

**Issue by D-Moonesinghe** [MicrosoftDocs/WSL#1374]
In your line that says: "create a user account, and set it as the default user." It makes no mention of adding the username to the sudoers file.  I wasn't familiar with the wheel group. By omitting that  -G wheel.  I got myself to trouble by not being able to do 'sudo'.
I think just adding a line @ "adduser -G wheel $myUsername" that mentions what this -G wheel does would enormously help users not familiar with the group wheel.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38361991-7995-26b1-93b1-ff81d3ecb4ae
* Version Independent ID: a1c0c209-b14f-bf87-5d69-dee4b1ee9b23
* Content: [Import any Linux distribution to use with WSL](https://docs.microsoft.com/en-us/windows/wsl/use-custom-distro)
* Content Source: [WSL/use-custom-distro.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/use-custom-distro.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Tagging Matt here, leaving it up to your judgement to add it Matt!

**Comment by mattwojo** [comment]
Added a note about this: https://github.com/MicrosoftDocs/WSL/commit/9e0c8c48f765fc65641debd256ce9c27bbcf76db

Thanks for contributing this recommendation!
