### ISSUE TITLE
should mention selecting WSL version before running wsl --install -d Ubuntu-20.04

### ISSUE THREAD

**Issue by therobyouknow** [MicrosoftDocs/WSL#1378]
problem with instructions on page: https://docs.microsoft.com/en-us/windows/wsl/install

first of all, parameters need to be specified, as per issue https://github.com/MicrosoftDocs/WSL/issues/1375

and also best to specify WSL 2 version (which is the best and fastest, improvements on WSL 2), _before_ running the install command

and to specify the specific Ubuntu version (related issue https://github.com/MicrosoftDocs/WSL/issues/1377 )

So to get a specific recent version of Ubuntu, e.g. 20.04 installed with WSL 2, do:

`wsl --set-default-version 2`

then

`wsl --install -d Ubuntu-20.04`

(in Administrator Power Shell)

tip:

if from
`wsl -l -v `  you find that you had installed a distro like Ubuntu with WSL1 (listed as 1 under VERSION) then you can uninstall it in the standard uninstaller.

```
PS C:\Windows\system32> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Stopped         1
  docker-desktop         Running         2
  docker-desktop-data    Running         2
  Ubuntu-20.04           Running         2
PS C:\Windows\system32>

```

in the uninstall apps windows window ('Apps & Features') click on the app you want to uninstall to reveal the uninstall button.

before uninstall of superfluous wsl1 and distro

![image](https://user-images.githubusercontent.com/1080646/144602186-e93dcefa-0af0-44d7-ae6e-397816269916.png)

after

![image](https://user-images.githubusercontent.com/1080646/144603422-d184784b-2d12-4cbc-85eb-319c8cdc21bc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
We've improved this in the Microsoft Store version of WSL! https://aka.ms/wslstorepage
