### ISSUE TITLE
Is this page still accurate? All I had to do is: \\wsl$\Ubuntu-20.04 - easy path string to access file system in windows explorer

### ISSUE THREAD

**Issue by therobyouknow** [MicrosoftDocs/WSL#1379]
Is this page still accurate? https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk

All I had to do to access my Ubuntu 20.04 LTS linux 64bit WSL2 instance file system was type this into a Windows Explorer window:

`\\wsl$\Ubuntu-20.04`

![image](https://user-images.githubusercontent.com/1080646/144626513-f620fbb1-ebe0-4f7f-9d0c-72e5e10011cd.png)

and I got:

![image](https://user-images.githubusercontent.com/1080646/144626655-ceac5607-07fd-42af-a7a2-0334672884d5.png)

So I'm not sure if the steps on https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk are required.

Caveat/Disclaimer:
I installed wsl2/ubuntu20.04/docker on one user account. I then repeated the process on a separate account. It was this 2nd account where I was able to do `\\wsl$\Ubuntu-20.04` without any other steps, as was the same for the first account. I will try to go through my notes but I don't recall going through any steps like on https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk so it does seem that `\\wsl$\Ubuntu-20.04` is out of the box ready to use without further setup, hence my query.

My setup:
Windows 10 Pro 64bit
Docker Desktop
Standard WSL2 Ubuntu 20.04 LTS 64bit running

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e255b0-71c7-adc6-cac0-6df3b76a971f
* Version Independent ID: a9d73ca3-7026-5b5a-f3fe-3511e976cde4
* Content: [Get started mounting a Linux disk in WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk)
* Content Source: [WSL/wsl2-mount-disk.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-mount-disk.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
That link is to mount and access actual installation of Linux (ext4) filesystem. In the screenshot, the file explorer is showing the file system of GNU/Linux distribution inside WSL2.

**Comment by therobyouknow** [comment]
> That link is to mount and access actual installation of Linux (ext4) filesystem. In the screenshot, the file explorer is showing the file system of GNU/Linux distribution inside WSL2.

Thank you @Biswa96 I think I see what it means.  The above link is about a _separate_ file Linux file system, separate from, i.e., not the Linux filesystem within WSL2.  The link is for mounting storage devices formatted in a format that Linux understands, like ext4, that Windows itself by default would not normally understand.

For example such a separate filesystem could be the filesystem of a Linux installation in a different partition,  where that Linux installation can be selected at boot time from a boot menu to boot into and run, with Windows also an option, e.g. using the GRUB menu, so called 'dual boot'.  

Another example could be an external drive that is formatted as ext4.

So the page is correct, I'd say, thanks for your help on clarifying.  What I was looking for was how to, from Windows, mount the filesystem of Linux (Ubuntu 20.04) within WSL2 such that I can see it as a Windows Explorer folder (or drive), to be able easily put files into that Linux filesystem, from Windows and vice versa, to copy files out of that Linux filesystem into Windows.

So I'll close this issue now that you've helped clarify what the page is for.  It was Google that brought me there, Google doesn't seem to be able to handle ordering or precedent of search terms so it brought me to that page which seemed to be what I wanted, but wasn't.

On a related note, interesting to note that NTFS ius being supporting in 5.15 version of Linux kernel - https://www.theregister.com/2021/10/13/how_ntfs_finally_made_it/
- which, as the article and some have commented said, that one can install a linux distro within the same NTFS file system as the Windows operating system, on the basis that Linux's top level folder names don't tend to clash with those of Windows.
