### ISSUE TITLE
Windows server installation download locations

### ISSUE THREAD

**Issue by ciwchris** [MicrosoftDocs/WSL#138]
In install-on-server.md there are links to download the appx for the three supported distributions. The current link to Ubuntu downloads version 1604.2017.711. The current version in the store is 1604.2017.904. Can the document be updated so that all versions of all the supported distributions can be viewed. Or can the links be continuously updated so the latest version is always downloaded?

**Comment by zavedctg** [comment]
Thanks

**Comment by DarthSpock** [comment]
just `apt update` and `apt upgrade -y`. You'll be at the latest version of Xenial after that which you can check by doing `uname -a`.

**Comment by Fake4d** [comment]
but this will not help if i need the kali release..

**Comment by tara-raj** [comment]
Closing as dup - https://github.com/MicrosoftDocs/WSL/issues/174.

Update - we're working on getting the proper packages from our distro partners
