### ISSUE TITLE
usbipd: error: The specified WSL distribution is not running.

### ISSUE THREAD

**Issue by hirooih** [MicrosoftDocs/WSL#1380]
First I had a error.

```
PS C:\WINDOWS\system32> usbipd wsl attach --busid 1-1
usbipd: error: The specified WSL distribution is not running.
```

The Linux distribution to be attached must be default distribution.

```
PS C:\WINDOWS\system32> wsl --list --all --verbose
  NAME                   STATE           VERSION
* Ubuntu                 Stopped         2
  Ubuntu-20.04           Running         2
PS C:\WINDOWS\system32> wsl --set-default Ubuntu-20.04
PS C:\WINDOWS\system32> wsl --list --all --verbose
  NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
  Ubuntu                 Stopped         2
PS C:\WINDOWS\system32> usbipd wsl attach --busid 1-1
[sudo] password for myid:
PS C:\WINDOWS\system32>
```

This should be described on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99de78d-d27a-664d-98ba-91116b7157c8
* Version Independent ID: e99de78d-d27a-664d-98ba-91116b7157c8
* Content: [Connect USB devices](https://docs.microsoft.com/en-us/windows/wsl/connect-usb)
* Content Source: [WSL/connect-usb.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/connect-usb.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
A fair ask! Maybe we can add a quick bullet point at the bottom in a "Troubleshooting" section

**Comment by mattwojo** [comment]
Added a note: https://github.com/MicrosoftDocs/WSL/commit/fb6fd843f01cde3b0b050321ce56dd03756602ab

Can add this to the troubleshoot doc later too... but seemed like this needs to be addressed in the primary how-to instructions.

Thanks for pointing this out @hirooih!!

**Comment by hirooih** [comment]
Thanks.  I hope it will help other users.

BTW after I posted this issue ticket, I found the command has `--distribution` (or `-d`) option.

```
PS C:\Users\hiroo> usbipd wsl attach -b 2-1 -d Ubuntu-20.04
```

Using this option may be better than changing the default distribution.

>  The Linux distribution to be attached must be your default distribution. (See the [Basic comands for WSL](./basic-commands.md#set-default-linux-distribution) doc to change your default distribution).

This can be simplified to:

>  You may have to specify the Linux distribution to be attached by using `--distribution` (or `-d`) option.
