### ISSUE TITLE
Manual outdated

### ISSUE THREAD

**Issue by corradin** [MicrosoftDocs/WSL#1383]
The wsl --install command requires additional parameters and cannot be run without those.
Please update the manual to reflect this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This is because WSL is already installed when trying to run those commands, we've fixed this in the Microsoft Store version: https://aka.ms/wslstorepage
