### ISSUE TITLE
WSL2 networking

### ISSUE THREAD

**Issue by lagunary** [MicrosoftDocs/WSL#1393]
Hi Guys,

Firstly, I wanna say big thank you for the WSL.

I have a little problem with WSL2 networking.
The randomized IP address for WSL (Hyper-V) network sometimes generates same IP range what we are using in our LAN (furhter in this cases under VPN connection there is no communication for WSL cause of VPN routing).
This means I have to reboot the computer once or more (personal record is 6 times) when I can get a suitable IP address for WSL.
Do you plan to communicate with Microsoft and give a solution for users to avoid them from similar cicumstances?
Thanks in advance.
BR,
Viktor

**Comment by craigloewen-msft** [comment]
Overall we're working on improving our networking story. If you see this error again please try rebooting just WSL instead using `wsl --shutdown`.
