### ISSUE TITLE
You don't download manually the latest Debian GNU/Linux

### ISSUE THREAD

**Issue by MontecaE** [MicrosoftDocs/WSL#1394]
Hi,
if you want to download Debian GNU/Linux manually and you click this [link](https://aka.ms/wsl-debian-gnulinux) you don't download the latest version [1.12.1.0](https://salsa.debian.org/debian/WSL/-/tree/v1.12.1.0) but the previous one, 1.11.1.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manual installation steps for older versions of WSL](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
We track the latest Debian version that is in the Microsoft Store. Currently this is uploaded manually and so it is possible that we can be a few versions behind. We have a fix incoming that will improve this for `wsl --install` cases to download automatically from the Store. Our recommendation is to download this version and upgrade it using Linux tools in your distro. Thank you for filing this!
