### ISSUE TITLE
description of **wsl hostname -I** is missing.

### ISSUE THREAD

**Issue by ComputerDoktor** [MicrosoftDocs/WSL#1396]
description of **wsl hostname -I** is missing.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb425ee-c5e3-fc01-93a7-c87c9fa0b89a
* Version Independent ID: ea2f6a7b-28f2-2af8-e8fc-7f7b3624f88a
* Content: [Basic commands for WSL](https://docs.microsoft.com/en-us/windows/wsl/basic-commands)
* Content Source: [WSL/basic-commands.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/basic-commands.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
`wsl.exe hostname` is running the Linux binary `hostname` as you can see here:
<img width="293" alt="image" src="https://user-images.githubusercontent.com/42221804/146812024-6bb88775-94c2-4ae4-907a-b5e11d757feb.png">

This page only provides references to wsl.exe specific commands. This above command falls under the umbrella of "executing a Linux binary using wsl.exe".
