### ISSUE TITLE
The command "wsl --install" needs to be updated

### ISSUE THREAD

**Issue by ashishsinghbhu** [MicrosoftDocs/WSL#1397]
There is discussion on https://github.com/MicrosoftDocs/WSL/issues/1054 about multiple users running into issues while running wsl --install. The fix is to specify wsl --install -d {distro}. Kindly update the doc. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Yes this has been updated in the latest WSL version already. `wsl --install` will show an appropriate message when WSL is already installed. You can try out this functionality with WSL on the Microsoft Store today. https://aka.ms/wslstorepage

<img width="526" alt="image" src="https://user-images.githubusercontent.com/42221804/146978883-f82d819d-fd59-44ff-a0fc-6a8aeec4b0a5.png">

**Comment by keith555** [comment]
It's still not working. It just displays the usage screen.

![wsl install](https://user-images.githubusercontent.com/1978986/147834153-142699a5-3f4d-4e76-aed3-d4f0d3f81e7e.jpg)

**Comment by keith555** [comment]
> @keith555 you already have wsl installed if you're seeing that message. Try running `wsl.exe` !

I'm pretty sure that's not the case. I reran the command with `wsl --install -d ubuntu `and it ran through as expected. I have only one distro installed, so the above command didn't install a second distro.
