### ISSUE TITLE
older versions approach is not appropriate title 

### ISSUE THREAD

**Issue by GerbenJdeBoer** [MicrosoftDocs/WSL#1398]
The WSL manual installation steps for older versions is also needed when you're running an up-to-date build (winver 20H2, OS Build 19042.867), and want to use the install command, but you can't because your IT department apparently left out certain windows components. Simply said, all cases when `wsl --install` does not work. The OLDER in the page name 'Manual installation steps for older versions of WSL' is therefore not appropriate. Please update the prerequisites section to include that developers mode should have been switched on, and that hyperv should have been enabled. And if not, do the stepwise installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
When you say that "your IT department" left out certain Windows components, did they remove the Hyper-V optional component from the Windows image?

The challenge with naming this page is that `wsl --install` is the new and recommended way that exists on the latest and newest builds. It's also the easiest way to install WSL that works for the majority of folks, and our earlier methods to install WSL are much more lengthy and difficult. Are there any other names for this doc that would make it clearer for you?

**Comment by mattwojo** [comment]
Closing. Please re-open if you would like to discuss further and feel the docs need an update. Thanks for contributing!
