### ISSUE TITLE
wsl install fails due to omission developers mode and hyperv

### ISSUE THREAD

**Issue by GerbenJdeBoer** [MicrosoftDocs/WSL#1399]
The steps on this page do not work, it fails at step 4. I get a wsl access denied after this step. This did work for winver 20H2 (OS Build 19042.867).

1. ok
2. ok
3. ok
4. fails, I get a wsl access denied error, even if if start it from PS or CMD in admin mode.
4. enable Developers mode in start menu
5. enable hyper-V with `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
6. install Ubuntu from Microsoft Store
7. `wsl --set-version Ubuntu 2` instead of `wsl --set-default-version 2`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manual installation steps for older versions of WSL](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Have you tried just using the [wsl --install](https://docs.microsoft.com/windows/wsl/install) command? It will handle all of these steps for you. 
So you enabled the WSL option in Windows Settings, checked that your machine meets all of the requirements for running WSL 2, enabled the Virtual Machine Platform option, and then you weren't able to download and update the kernel .msi package?
I'm getting a bit confused by your steps 5 and 6. 
It might be worth looking up the error code you're receiving in the WSL product repo issues to see whether anyone else has encountered this: https://github.com/Microsoft/wsl/issues 
Closing as this doesn't appear to require an update to the WSL docs, but please feel welcome to re-open if this is not the case.

**Comment by Nkensa** [comment]
once kali is launched I always come across this error : WslRegisterDistribution failed with error: 0x80004005

Please help me.
