### ISSUE TITLE
usbip not found for kernel

### ISSUE THREAD

**Issue by danjwait** [MicrosoftDocs/WSL#1400]
Following instructions on setting up usbipd w/ Windows 11 WSL2; when trying to attach I get a warning about a usbipd version mismatch:

PS C:\Users\...> usbipd wsl attach --busid 1-2
[sudo] password for ...:
WARNING: usbip not found for kernel 5.10.74.3-microsoft

  You may need to install the following packages for this specific kernel:
    linux-tools-5.10.74.3-microsoft-standard-WSL2
    linux-cloud-tools-5.10.74.3-microsoft-standard-WSL2

  You may also want to install one of the following packages to keep up to date:
    linux-tools-standard-WSL2
    linux-cloud-tools-standard-WSL2
usbipd: error: Failed to attach device with ID '1-2'.

Checking the WSL version w/i powershell:

C:\Users\...> wsl --list --all --verbose
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2

Checking the linux version within the WSL guest:

:~$ uname -a
Linux VOSTRO 5.10.74.3-microsoft-standard-WSL2 #1 SMP Mon Oct 18 19:27:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Is there something else users need to configure? I notice the linux-tools version points to 5.4 , not 5.10?: 

sudo apt install linux-tools-5.4.0-77-generic hwdata
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99de78d-d27a-664d-98ba-91116b7157c8
* Version Independent ID: e99de78d-d27a-664d-98ba-91116b7157c8
* Content: [Connect USB devices](https://docs.microsoft.com/en-us/windows/wsl/connect-usb)
* Content Source: [WSL/connect-usb.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/connect-usb.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Make sure you run these commands, you're missing the usbip binary in Linux!

https://docs.microsoft.com/en-us/windows/wsl/connect-usb#install-the-usbip-tools-and-hardware-database-in-linux

<img width="530" alt="image" src="https://user-images.githubusercontent.com/42221804/147133686-433b9790-49da-4aea-832a-bf7f8b386f98.png">

**Comment by danjwait** [comment]
I did run all those steps. Data dump below from checking versions:

PS C:\Users\dwait> wsl --version
WSL version: 0.50.2.0
Kernel version: 5.10.74.3
WSLg version: 1.0.29
Windows version: 10.0.22000.376
PS C:\Users\dwait> wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)
PS C:\Users\dwait> wsl
djwait@VOSTRO:/mnt/c/Users/dwait$ which usbipd
/usr/bin/usbipd
djwait@VOSTRO:/mnt/c/Users/dwait$ usbipd --version
WARNING: usbipd not found for kernel 5.10.74.3-microsoft

  You may need to install the following packages for this specific kernel:
    linux-tools-5.10.74.3-microsoft-standard-WSL2
    linux-cloud-tools-5.10.74.3-microsoft-standard-WSL2

  You may also want to install one of the following packages to keep up to date:
    linux-tools-standard-WSL2
    linux-cloud-tools-standard-WSL2
djwait@VOSTRO:/mnt/c/Users/dwait$ sudo apt install linux-tools-5.4.0-77-generic hwdata
[sudo] password for djwait:
Reading package lists... Done
Building dependency tree
Reading state information... Done
hwdata is already the newest version (0.333-1).
linux-tools-5.4.0-77-generic is already the newest version (5.4.0-77.86).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by danjwait** [comment]
Found it, I'd transposed a . and - in the 5.4.0-77-generic: edit. My bad.

**Comment by aldairandre** [comment]
I'm having the same problem, so far I can't find any answers
