### ISSUE TITLE
Why is the screenshot showing windows 10 while prerequisites list windows 11?

### ISSUE THREAD

**Issue by gk2000** [MicrosoftDocs/WSL#1402]
[Enter feedback here]
It is a little misleading to have a screenshot of a windows 10 desktop running Linux GUI apps, while the prerequisites mention that Windows 11 is required to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Agrover112** [comment]
@gk2000 That's Windows 11, and it's my screenshot lol.
Maybe it's not yet merged with deploy branch?

**Comment by gk2000** [comment]
@Agrover112  Yes you are right. The content source has a windows 11 screenshot but the website shows a windows 10 one.

**Comment by Agrover112** [comment]
I think since the PR has been merged we should close this issue.

**Comment by gk2000** [comment]
Agreed.

**Comment by Agrover112** [comment]
GG
