### ISSUE TITLE
I am getting sudo error in powershell while running attach command with usbipd

### ISSUE THREAD

**Issue by ninja-tech** [MicrosoftDocs/WSL#1403]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/10086568/147371857-4de36e62-6365-44af-be9f-0a50d326fda6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99de78d-d27a-664d-98ba-91116b7157c8
* Version Independent ID: e99de78d-d27a-664d-98ba-91116b7157c8
* Content: [Connect USB devices](https://docs.microsoft.com/en-us/windows/wsl/connect-usb)
* Content Source: [WSL/connect-usb.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/connect-usb.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
It looks like you're using a WSL instance that doesn't have sudo. 
What WSL distro are you using? If you try the above workflow with a distro like Ubuntu does it work?
