### ISSUE TITLE
Missing prerequisite info about 

### ISSUE THREAD

**Issue by ncarandini** [MicrosoftDocs/WSL#1404]
On my new Windows 11 laptop the Windows Hypervisor wasn't enabled by default so the docs instructions failed to work.
Please adfd this info as a prerequisite:
![image](https://user-images.githubusercontent.com/139274/147382790-478bdc17-9a69-4d48-a937-953f75b1214d.png)
discaimer note: please use the english version of the image. :-)
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
The `wsl --install` command will enable the `Virtual Machine Platform` optional component as part of its install process, meaning this isn't a required pre-requisite. I'll close this issue for our bookkeeping (as on the docs I don't think we need to make any changes) but did you see any errors or messages when using `wsl --install`?

**Comment by ncarandini** [comment]
@craigloewen-msft yes, I wasn't able to execute the command until I manually enabled the Virtual Machine Platform optional component. That's why I've opened the issue.
My machine info:

Processore	11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   3.00 GHz
RAM installata	32,0 GB (31,7 GB utilizzabile)
Tipo sistema	Sistema operativo a 64 bit, processore basato su x64
Penna e tocco	Supporto tocco con 10 punti tocco
----------------
Edizione	Windows 11 Home
Versione	21H2
Data installazione:	‎23/‎11/‎2021
Build sistema operativo	22000.376
Esperienza Pacchetto delle esperienze delle funzionalità Windows 1000.22000.376.0

**Comment by craigloewen-msft** [comment]
Got it! Thanks for making us aware. It seems like this is a one off issue, so if you run into this error again please let us know the details of it so we can help dive in and take a better look (though I hope next time `wsl --install` works for you just out of the box!).

Thank you for filing this.

**Comment by kneumei** [comment]
I also was not able to able to install wsl without manually turning on Virtual Machine Platform. 

The message I received was `An unrecoverable error occurred during installation. Component: 'Virtual Machine Platform Error Code: 0xc004000d' 

![image](https://user-images.githubusercontent.com/1694376/184424441-d349d07b-2255-43a4-a3dc-6057141b4937.png)
