### ISSUE TITLE
Documentation to install docker in wsl2 without docker desktop

### ISSUE THREAD

**Issue by amitoverflow-ui** [MicrosoftDocs/WSL#1407]
Please share steps to install docker inside wsl2 without using docker desktop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 403a33a6-304c-2ded-9ea8-4d70bc5f17ba
* Version Independent ID: 93b6a9ef-08ba-be90-736e-27515fb0f4da
* Content: [Get started with Docker containers on WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers)
* Content Source: [WSL/tutorials/wsl-containers.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/tutorials/wsl-containers.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Please use the docs at Docker to do this:
https://docs.docker.com/engine/install/ubuntu/
