### ISSUE TITLE
WSLg install of Visual Studio Code

### ISSUE THREAD

**Issue by K2AAE** [MicrosoftDocs/WSL#1412]
Looking for Visual Studio Code on WSLg installation - nothing here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 782a4458-6a56-63e5-efaf-d1868762ed06
* Version Independent ID: 312f71d9-db7d-52a5-b03d-9b6d4c680c2a
* Content: [Get started using VS Code with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode)
* Content Source: [WSL/tutorials/wsl-vscode.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/tutorials/wsl-vscode.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Here's our recommended tutorial for using VS Code with WSL:
https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode

For running the actual Linux version of VSCode please follow their Linux guide here:
https://code.visualstudio.com/docs/setup/linux

Thanks for filing!
