### ISSUE TITLE
What's the difference between these two SUSE12 distro?

### ISSUE THREAD

**Issue by zhufeizzz** [MicrosoftDocs/WSL#1416]
![image](https://user-images.githubusercontent.com/4591255/148875317-ebcf7891-31d5-4057-9385-89eb23a8d1b7.png)

The first one I got from here.
https://docs.microsoft.com/zh-cn/windows/wsl/install-manual#downloading-distributions
https://aka.ms/wsl-sles-12

The second one is on the Windows Store.

What's the difference? I want to install SUSE12 offline, how can I download the same version with Windows Store manually?

**Comment by craigloewen-msft** [comment]
This is a question best fit for the SUSE team who manages those distros! On the WSL team we don't manage them. 

If you want to download a WSL distro without the store please use the link that you had above.

Thanks!
