### ISSUE TITLE
Can not manual install WSL offline.

### ISSUE THREAD

**Issue by zhufeizzz** [MicrosoftDocs/WSL#1417]
I flow this guide to install WSL2+SUSE12, but installation blocked when I try to start suse.
https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions

See this issue, I don't know if this is a documentation mistake or a program bug.
https://github.com/microsoft/WSL/issues/7870

**Comment by craigloewen-msft** [comment]
This seems like a program bug, so we'll close this issue and track it over at microsoft/WSL. 

Thank you for filing!
