### ISSUE TITLE
WSL 2 VPN Issues

### ISSUE THREAD

**Issue by bevin0708** [MicrosoftDocs/WSL#1419]
This page does not address the inability of WSL2 to work over VPN 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f5d8ca6-c500-72ca-60ae-73ef0ac489ad
* Version Independent ID: 10a6919c-5152-2aa3-4d90-ccfa45cbbcc5
* Content: [Comparing WSL 1 and WSL 2](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
WSL 2 should work over VPNs, and on the latest versions of VPNs does work. What VPN issues are you running into? 

I'll close this issue for bookkeeping, but will keep an eye on it if you have any follow up questions!
