### ISSUE TITLE
wsl --install doesn't work

### ISSUE THREAD

**Issue by ramanova** [MicrosoftDocs/WSL#1422]
The first command from the document doesn't work:
wsl --install

Getting:
`Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by crramirez** [comment]
https://github.com/MicrosoftDocs/WSL/issues/1410#issuecomment-1005894224

**Comment by craigloewen-msft** [comment]
Closing this , as @crramirez pointed out please see the comments he provided for an answer here!
