### ISSUE TITLE
not working for win10 19044

### ISSUE THREAD

**Issue by jkujovic** [MicrosoftDocs/WSL#1423]
[Enter feedback here]
not working for win10 19044

Edition	Windows 10 Pro
Version	21H2
Installed on	‎1/‎13/‎2022
OS build	19044.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0

error:
PS C:\Windows\system32> wsl --install
wsl : The term 'wsl' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ wsl --install
+ ~~~
    + CategoryInfo          : ObjectNotFound: (wsl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Can you please open a CMD prompt and try accessing WSL? Does this fix it?

Please see the instructions here on how to file a technical issue (This repo is just for docs):
https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#file-an-issue-bug-report-feature-request
