### ISSUE TITLE
Cannot start GUI applications on WSL2

### ISSUE THREAD

**Issue by Tiksagol** [MicrosoftDocs/WSL#1427]
Followed the docs, but still cannot start GUI applications, even simple ones like xeyes, got `Cannot open display ...`

Trying to set DISPLAY to the local IP (as in the output of `ip addr`) doesn't help.
Will be useful if you can add `Troubleshooting` section to the docs.

Thanks !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by crramirez** [comment]
Hello, 

Please send me the output of the command `wsl.exe --list --verbose` and tell me if you have Windows 10 or Windows 11

Regards,
Carlos

**Comment by Tiksagol** [comment]
Hi,

```
wsl.exe --list --verbose
  NAME                   STATE           VERSION
* Ubuntu-18.04           Running         2
  docker-desktop-data    Stopped         2
  docker-desktop         Stopped         2

```

Windows version:
```
>ver

Microsoft Windows [Version 10.0.22000.434]
```

Thanks !

**Comment by crramirez** [comment]
OK. It should work out of the box.

Run:
wsl.exe --update
wsl.exe --shutdown

Be sure that

echo $DISPLAY

Returns

:0.0

If not execute

export DISPLAY=:0.0

and search if the DISPLAY variable is defined in .bashrc file and if it does, delete that line.

**Comment by Tiksagol** [comment]
It did the trick. Thanks a lot !
