### ISSUE TITLE
how to install ubuntu with ext4 file?

### ISSUE THREAD

**Issue by nenge123** [MicrosoftDocs/WSL#1429]
I reinstall window , but forget " --export" the tar.only have the ext4 file, in "d:\wsl\ubuntu\ext4"

so how to install the ubuntu20.04 with ext4 file？

**Comment by craigloewen-msft** [comment]
You can use `wsl --import` to import this file! 

https://craigloewen-msft.github.io/WSLTipsAndTricks/tip/install-different-drive.html
