### ISSUE TITLE
Use atp not get-apt

### ISSUE THREAD

**Issue by softwarepronto** [MicrosoftDocs/WSL#1432]
Modern Linux uses apt not get-apt:

this: sudo apt-get install git

should be: sudo apt install git
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31aade8d-62a2-6d91-b0bd-3bc5880042f8
* Version Independent ID: 12e275fa-8010-5e5a-af8c-120f11ab0932
* Content: [Get started using Git on WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git)
* Content Source: [WSL/tutorials/wsl-git.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/tutorials/wsl-git.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by slonopotamus** [comment]
> Modern Linux uses apt not get-apt

\[citation needed]

**Comment by softwarepronto** [comment]
This is the apt man page:
http://manpages.ubuntu.com/manpages/jammy/en/man8/apt.8.html

Your article is not batch processing (apt-get) and targets
interactive users setting up WSL. From the man page

*apt* provides a high-level commandline interface for the package
management system. It is
       intended as an end user interface and enables some options
better suited for interactive
       usage by default compared to more specialized APT tools like
*apt-get <http://manpages.ubuntu.com/manpages/jammy/en/man8/apt-get.8.html>*(8)
and *apt-cache <http://manpages.ubuntu.com/manpages/jammy/en/man8/apt-cache.8.html>*(8).

       Much like *apt* itself, its manpage is intended as an end user
interface and as such only
       mentions the most used commands and options partly to not
duplicate information in
       multiple places and partly to avoid overwhelming readers with a
cornucopia of options and
       details.

apt has been around for nearly 8 years

https://linuxhint.com/diff_apt_vs_aptget/#:~:text=The%20old%20apt%2Dget%20upgrade,currently%20exist%20in%20your%20system.&text=However%2C%20the%20new%20apt%20upgrade,packages%20that%20were%20previously%20installed
.

The apt command-line utility was introduced in 2014 for the .deb packages
of Debian distribution. It was first used in the unstable version of Debian
and then became standard in Debian 8. Initially, it did not gain much
attention from users, and they kept using the old and familiar apt-get
command. However, after the release of Ubuntu 16.04, it start gaining
popularity and somehow replaced the apt-get.

The difference between the apt and apt-get is not limited to just the
commands. Another visual feature has been added to the new apt command to
make it pleasant for end users. Whenever a package is updating while using
an apt upgrade, apt full-upgrade, or apt dist-upgrade, you will see a
progress bar informing you of the progress of the process. It also appears
when you remove the package using apt remove or apt purge.


https://itsfoss.com/apt-vs-apt-get-difference/

One of the noticeable new features of Ubuntu 16.04
<https://itsfoss.com/features-ubuntu-1604/> was the ‘introduction’ of apt
command <https://itsfoss.com/apt-command-guide/>. The reality is that the
first stable version of apt was released in the year 2014 but people
started noticing it in 2016 with the release of Ubuntu 16.04.

It became common to see apt install package instead of the usual apt-get
install package. Eventually, many other distributions followed Ubuntu’s
footsteps and started to encourage users to use apt instead of apt-get.

**Comment by craigloewen-msft** [comment]
These are functionally the same command, `apt-get` has more compatibility and `apt` is more modern. We use either or command as both work effectively the same for our use case.
