### ISSUE TITLE
Error: 0x8007023e {Application Error} 

### ISSUE THREAD

**Issue by ktisakib** [MicrosoftDocs/WSL#1434]
Note that this repo's issue tracker is only for reporting issues that require an update to the WSL documentation.

Other related issue repo's:

* WSL product repo (for reporting WSL issues, bugs, or feature requests): https://github.com/microsoft/wsl/issues
* WSLg repo (for reporting issues related to WSL GUI apps): https://github.com/microsoft/wslg/issues
* Windows Terminal repo (for reporting issues related to the Terminal shell): https://github.com/microsoft/terminal/issues
* Windows Console repo (For reporting issues with CMD): https://github.com/MicrosoftDocs/Console-Docs/issues

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007023e
Error: 0x8007023e {Application Error}
The exception s (0x
Press any key to continue...

Every time it is happening

**Comment by craigloewen-msft** [comment]
Can you please try installing the version of WSL from the Store and see if you still have this issue?
https://aka.ms/wslstorepage

If you do, please file it as an issue on the WSL Github which you linked above! :)
