### ISSUE TITLE
Does this article talk about WSL1 or WSL2?

### ISSUE THREAD

**Issue by Schreini** [MicrosoftDocs/WSL#1435]
Does this article talk about WSL1 or WSL2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install-on-server.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by crramirez** [comment]
Hello @Schreini,

Only WSL 1. WSL 2 is not supported on Windows Server any version.

Regards,
Carlos

**Comment by Schreini** [comment]
Thanks for the quick response.

**Comment by crramirez** [comment]
Hello @Schreini,

I found this: https://github.com/microsoft/WSL/issues/6301#issuecomment-1024521788 looks like WSL 2 can be enabled in Windows Server 2004 and 20h2

Regards,
Carlos
