### ISSUE TITLE
Bad example link

### ISSUE THREAD

**Issue by rdinit** [MicrosoftDocs/WSL#1437]
[Enter feedback here]

Link "https://aka.ms/wsl-ubuntu-2004" in curl example is not working. Right is "https://aka.ms/wslubuntu2004"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manual installation steps for older versions of WSL](https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distros)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Fixed! Thank you for flagging this!
https://github.com/MicrosoftDocs/WSL/commit/a1d6f1a01c4b800131a5b8b62f532d904604ffe9
