### ISSUE TITLE
docs do not mention wsl.conf must have unix line endings

### ISSUE THREAD

**Issue by abg1979** [MicrosoftDocs/WSL#1439]
I was tying to configure wsl2 using wsl.conf but it did not work. I had created the file in windows so it had windows line endings. Only after i changed to unix line endings using dos2unix, wsl started using the wsl.conf.

Tested this in Ubuntu 20 available on store and a custom Fedora distribution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Advanced settings configuration in WSL](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Added a line to make this clear!
https://github.com/MicrosoftDocs/WSL/commit/24cb31cd58cdb699f5a4b8d9d064398130823b2c
