### ISSUE TITLE
Page does not actually explain how to run Linux GUI apps

### ISSUE THREAD

**Issue by dementeddr** [MicrosoftDocs/WSL#1440]
This doesn't actually explain how to configure or run the X11 server, or what the recommended drivers do. All it really tells you to do is update windows and wsl and it should apparently just... work. Except it doesn't. I went through all the steps and installed a couple of the suggested programs (x11-apps and vlc) and both fail. VLC fails to it's own CLI. The xapps just fail to start with "Error: Can't open display: 192.168.1.72:0" The IP is the current IP of my host windows machine, which I set the $DISPLAY  envar to. Is that the right way to do it with WSL? I don't know; this page doesn't say, so that's what other things I googled seemed to indicate. It doesn't work when I leave the var unset either. Does this mean I also need to install something like VcXsrv? The page makes it sound like you can do this from a completely fresh linux instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
WSLg does not need VcxSrv. Also remove the command that sets DISPLAY variable. It is automatically set to `:0` by init binary.

**Comment by Agrover112** [comment]
@dementeddr Hey so WSL2 supports GUI apps out of the box. You need not worry setting up an X server .
If you are facing problems then probably you haven't upgraded to WSL2 or maybe try installing a new distro just to check if you haven't messed up the current distro in anyway.

**Comment by craigloewen-msft** [comment]
As the comments above have said, you do not need a X server for this it's already all built in! If you follow the tutorial steps you will get set up. Feel free to remove your set for the DISPLAY variable, ensure that you have Windows 11 running and you should be good! :)
