### ISSUE TITLE
Gimp No Longer Available

### ISSUE THREAD

**Issue by MAIHfly** [MicrosoftDocs/WSL#1442]
[Enter feedback here]
Gimp doesn't seem to work what do I do if I want to get this gui fix to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
If you're running into a technical issue with gui apps please file it at this repo: https://github.com/microsoft/wslg and fill out the issue template there so we can have the right info to help you!
