### ISSUE TITLE
wsl --mount \\.\PHYSICALDRIVE0 --bare doesn't work

### ISSUE THREAD

**Issue by 1nekomata** [MicrosoftDocs/WSL#1447]
I can't mount my real drive with a linux partition on it to wsl. running wsl --help doesn't show the --mount option and wsl --mount \\.\PHYSICALDRIVE0 --bare is not recognized. I am on Windows 10 Version 21H1 OS build 19043.1466. WSL2 Kernel version is 5.10.60.1 and i'm only using Debian WSL

**Comment by bcneese** [comment]
In [the docs](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#prerequisites) it looks like this is only available on Windows 11

> You will need to be on Windows 11 Build 22000 or higher to access this feature. You can join the [Windows Insiders Program](https://insider.windows.com/) to get the latest preview builds.
