### ISSUE TITLE
Extract and install a Linux distribution

### ISSUE THREAD

**Issue by steveoh** [MicrosoftDocs/WSL#1451]
> Run the distribution launcher application in the target folder. The launcher is typically named <DistributionName>.exe (for example, ubuntu.exe).

The current ubuntu distro's do not contain an exe distribution launcher.

![image](https://user-images.githubusercontent.com/325813/153269549-b922004f-510c-42df-b08a-28dc6518a4f4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install-on-server.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
You are looking at the bundled Appx package. The *_ARM64.appx and *_x64.appx contain the installed files.

**Comment by steveoh** [comment]
The instructions say to rename the appxbundle to a zip and extract it, then run an exe. The exe does not exist. Add-AppxPackage seems to work from instructions on another page after extraction but either way the instructions on this page are incorrect.

**Comment by mattwojo** [comment]
Thank you for pointing this out @steveoh! Updated the doc: https://github.com/MicrosoftDocs/WSL/pull/1460
Appreciate the contribution.

**Comment by rupertpaulson** [comment]
It seems as if it hasn't been fixed yet, I ran into the same problem and I couldn't find the ubuntu.exe after renaming and extracting the bundled Appx package.

**Comment by nandoverona** [comment]
The correct steps to install WSL2 in Windows Server 2019 are documented here, Microsoft, please udate the documentation.
https://serverfault.com/questions/1128068/how-to-install-linux-distro-on-windows-server-2019-and-wsl-version-1#answer-1128508
