### ISSUE TITLE
Is there a way to config wsl's folder path 

### ISSUE THREAD

**Issue by xiangqunXiao** [MicrosoftDocs/WSL#1452]
[Enter feedback here]

in [this part](https://docs.microsoft.com/en-us/windows/wsl/setup/environment#file-storage), it is recomend to store file in linux system for better performance when using wsl2.

While the default wsl folder is located at C  disk. And I've installed 2 windows 10 system on my laptop. So if I clone a repo in system A and store it insidel wsl folder（such as `/mnt/wsl`）, it's hard to access and using the repo I've cloned in system A when I am using system B.

Maybe it's a good idea to support config my wsl path on other disk like D disk, so that I just need to clone once and be able to use  the same repo file  in different win10 system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8226ebd3-6c2a-17aa-3a27-cffb4a5d0a57
* Version Independent ID: 06d3a4ce-218a-d39d-4a71-60a3cb86e422
* Content: [Set up a WSL development environment](https://docs.microsoft.com/en-us/windows/wsl/setup/environment#feedback)
* Content Source: [WSL/setup/environment.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/setup/environment.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
You can install/register a GNU/Linux distribution for WSL in another drive/partition using `wsl --import` command. Alternatively, it is also possible to mount the VHDX file from another drive/partition in a running WSL2 instance.

**Comment by xiangqunXiao** [comment]
> You can install/register a GNU/Linux distribution for WSL in another drive/partition using `wsl --import` command. Alternatively, it is also possible to mount the VHDX file from another drive/partition in a running WSL2 instance.

Thanks and I'll try it after reading docs.

**Comment by craigloewen-msft** [comment]
This would be a feature request, could you please file this as a feature request on the WSL github repo? https://github.com/microsoft/wsl 

I'll close this issue out as this repo is just for tracking docs related issues and this is product related.
