### ISSUE TITLE
mounting SD not working

### ISSUE THREAD

**Issue by bcneese** [MicrosoftDocs/WSL#1453]
I have an SD card that has Ubuntu on it (I pulled it out of my Raspberry Pi) which I would like to edit a few files on.

The output of 
```PowerShell
GET-CimInstance -query "SELECT * from Win32_DiskDrive"
```
or 
```cmd
wmic diskdrive list brief
```
is 
```
Caption                   DeviceID            Model                     Partitions  Size
SDHC Card                 \\.\PHYSICALDRIVE1  SDHC Card                 2           31914086400
```
However when I try to mount the drive:
```PowerShell
wsl --mount \\.\PHYSICALDRIVE1
```
I get `The system cannot find the drive specified.`

Are SD cards not supported? I've tried using an SD to USB adapter as well as the native SD card slot on my Surface with not luck. I've also attempted to add `--bare` to the above command without any luck.

I followed the steps on the [Connect USB Devices](https://docs.microsoft.com/en-us/windows/wsl/connect-usb) page, but then I still can't find the files on the SD card, it just shows up as a USB device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e255b0-71c7-adc6-cac0-6df3b76a971f
* Version Independent ID: a9d73ca3-7026-5b5a-f3fe-3511e976cde4
* Content: [Get started mounting a Linux disk in WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk)
* Content Source: [WSL/wsl2-mount-disk.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/wsl2-mount-disk.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
SD Cards are not supported by `wsl --mount`, if you are able to see your SD card reader as a USB device using the USB device workflow are you able to install Linux tools to interact with and get files from your SD Card reader?

I'll close this issue as this repo is just for managing issues about the WSL docs and there aren't any docs changes required for this problem. Thank you!
