### ISSUE TITLE
Cant able to convert distribution from wsl1 to wsl2

### ISSUE THREAD

**Issue by KarthikCM-92** [MicrosoftDocs/WSL#1461]
After installing the WSL2 and restarting the system. i set the default version to version 2. later when i try to execute below command

**wsl --set-version Ubuntu-18.04 2**

i am getting the below error
==========================================================
**Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Access is denied.**

**Comment by craigloewen-msft** [comment]
Are you able to access your C:\Users\<username>\AppData\Local folder (Replacing <username> with your username?). This is indicating that you don't have access to that folder. 

If you're still seeing this issue can you please file it at https://github.com/microsoft/wsl instead? This repo is just for the docs
