### ISSUE TITLE
Why does performance improve by storing files in \\wsl and by how much?

### ISSUE THREAD

**Issue by dfoverdx** [MicrosoftDocs/WSL#1463]
> When you see /mnt/ in the file path of a WSL command line, it means that you are working from a mounted drive. So the Windows file system C:/ drive (C:\Users\<user name>\Project) will look like this when mounted in a WSL command line: /mnt/c/Users/<user name>/Project$. It is possible to store your project files on a mounted drive, but **your performance speed will improve if you store them directly on the \\wsl$ drive.**

Why, and by how much?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f557b94b-429d-87e8-43dd-77291e39509b
* Version Independent ID: 4e35ecde-38e2-f0d3-1f63-0efccf02b059
* Content: [Working across file systems](https://docs.microsoft.com/en-us/windows/wsl/filesystems#file-storage-and-performance-across-file-systems)
* Content Source: [WSL/filesystems.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/filesystems.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Please see the architecture explanation here on why performance will differ:
https://youtu.be/lwhMThePdIo?t=1919

It depends on your use case, but it can differ anywhere from 0% (If you don't use file access at all) to a normal range of 6-8x faster (For something like sudo apt update) to 20x faster.
