### ISSUE TITLE
WSL2 need support to add external wifi adapters

### ISSUE THREAD

**Issue by name-is-cipher** [MicrosoftDocs/WSL#1464]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e953ca-c1d6-68bc-097c-f750ae3d2852
* Version Independent ID: 9ca5e58c-5f05-f36f-242e-8b1bd1d113cb
* Content: [Windows Subsystem for Linux Documentation](https://docs.microsoft.com/en-us/windows/wsl/)
* Content Source: [WSL/index.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/index.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
I'm not sure I understand this ask. Could you please clarify? We should work well with external wifi adapters?

**Comment by name-is-cipher** [comment]
What do you mean by working, How do we connect External WiFi Adapter to WSL2?
The same goes for any Flash Drive.

If you are telling me to use USBIPD, I tried it. This is what happened ->
I can detect the device using **lsusb**, But when I check for external WiFI adapters using **iwconfig** or  **ifconfig** I don't see any device listed. Did I miss something?

My aim is to use the external wifi adapter in the monitor mode in WSL2, please show me a way to do that?

**Comment by name-is-cipher** [comment]
And even the networking in WSL2 is pretty crazy, Why don't you use simple IP space like 172.20.0.1/24  :

172.20.0.1 For Main WSL2 Virtual Adapter and 172.20.0.(100 - 255) for subsequent WSL2 Distros. And why can't the IP address assigned to WSL2 Distros be static instead of Some Random?

**Comment by crramirez** [comment]
@name-is-cipher have you tried this? https://devblogs.microsoft.com/commandline/connecting-usb-devices-to-wsl/

**Comment by crramirez** [comment]
I got it. If the device shows in lsusb but doesn't work my first question is have you tested it in bare metal Linux?

The other thing is that WSL2 has its own network stack I doubt that even if it recognizes the adapter correctly it will be able to work properly.

**Comment by name-is-cipher** [comment]
Hmm, Bear metal Linux that is what is I missed I guess, ill come back to you once I try.

Thanks @crramirez
