### ISSUE TITLE
Ubuntu doesn't appear in the start menu.

### ISSUE THREAD

**Issue by d3jv** [MicrosoftDocs/WSL#1465]
In the first step it tells me to launch ubuntu from the start menu but it's not in the goddamn start menu. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8226ebd3-6c2a-17aa-3a27-cffb4a5d0a57
* Version Independent ID: 06d3a4ce-218a-d39d-4a71-60a3cb86e422
* Content: [Set up a WSL development environment](https://docs.microsoft.com/en-us/windows/wsl/setup/environment#set-up-your-linux-username-and-password)
* Content Source: [WSL/setup/environment.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/setup/environment.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Please try opening a CMD prompt and running `wsl.exe -l -v` to see a list of distros available and if Ubuntu isn't listed there please run `wsl --install -d Ubuntu`
