### ISSUE TITLE
Typo in section "Filename and directory case sensitivity"

### ISSUE THREAD

**Issue by atomic-7** [MicrosoftDocs/WSL#1468]
There is a typo in the section on case sensitivity, the part "Windows is _case-insenstive_" is missing an i in case-insensitive. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f557b94b-429d-87e8-43dd-77291e39509b
* Version Independent ID: 4e35ecde-38e2-f0d3-1f63-0efccf02b059
* Content: [Working across file systems](https://docs.microsoft.com/en-us/windows/wsl/filesystems)
* Content Source: [WSL/filesystems.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/filesystems.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by atomic-7** [comment]
The typo should be fixed now , I hope I did not mess up the pull request as I have never done this before.

**Comment by craigloewen-msft** [comment]
Merged! Thank you for the fix!
