### ISSUE TITLE
How to I display a remote linux xclient on the local wsl?

### ISSUE THREAD

**Issue by bjbeare** [MicrosoftDocs/WSL#1470]
Running Windows 11 (local system).
Running Ubuntu (remote system).
What I want to do...

ssh my_linux_system.local  DISPLAY=my_windows_wsl_system.local:0.0 xterm

**Comment by craigloewen-msft** [comment]
I'd look at using an XClient on Windows (Like XMing).

**Comment by bjbeare** [comment]
OK... so the built-in X server that WSL uses can't support remote connection? ty
