### ISSUE TITLE
someone please help me when i was running wsk for kali linux and i launched beef i get an error saying that system has ot been booted with initial pd can't connect to bus host is down someone please help me fast

### ISSUE THREAD

**Issue by scriptkittty123** [MicrosoftDocs/WSL#1471]
Note that this repo's issue tracker is only for reporting issues that require an update to the WSL documentation.

Other related issue repo's:

* WSL product repo (for reporting WSL issues, bugs, or feature requests): https://github.com/microsoft/wsl/issues
* WSLg repo (for reporting issues related to WSL GUI apps): https://github.com/microsoft/wslg/issues
* Windows Terminal repo (for reporting issues related to the Terminal shell): https://github.com/microsoft/terminal/issues
* Windows Console repo (For reporting issues with CMD): https://github.com/MicrosoftDocs/Console-Docs/issues

**Comment by craigloewen-msft** [comment]
I can't interpret this issue, please could you file an actionable issue for us?
