### ISSUE TITLE
The command wsl --install does not install WSL

### ISSUE THREAD

**Issue by syeda-git** [MicrosoftDocs/WSL#1473]
I followed the prerequisites. But when i run the above install command, it just prints all the wsl arguments/options

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Please see this help text:
<img width="495" alt="image" src="https://user-images.githubusercontent.com/42221804/156257190-777f8eb5-3484-4213-ad16-d403d421561d.png">

Please try running `wsl --install -d Ubuntu` to install a specific distribution.

**Comment by MatsSvenssonNewseed** [comment]
Please move information about why wsl --install doesn't work, up before or right after.

Its stuff like this that makes following these kind step-by-step descriptions a horrible time wasting experience.

Also, why doesn't running wsl --install when wsl already is installed, simply just tell you that you that **that** is the problem?

This would have saved me days of work.
