### ISSUE TITLE
FAQ page has contradictory answers on WSL networking

### ISSUE THREAD

**Issue by TheRedshift** [MicrosoftDocs/WSL#1483]
### Documentation Issue

In the section [How do I access a port from WSL in Windows? ](https://docs.microsoft.com/en-us/windows/wsl/faq#how-do-i-access-a-port-from-wsl-in-windows-), there's this - 

> WSL shares the IP address of Windows, as it is running on Windows. As such you can access any ports on localhost e.g. if you had web content on port 1234 you could https://localhost:1234 into your Windows browser.

But further down the page, in the section [Can WSL 2 use networking applications?](https://docs.microsoft.com/en-us/windows/wsl/faq#can-wsl-2-use-networking-applications-), there's this -

> Yes, in general networking applications will work better and be faster with WSL 2 since it offers full system call compatibility. However, the WSL 2 architecture uses virtualized networking components, which means that WSL 2 will behave similarly to a virtual machine -- **WSL 2 distributions will have a different IP address than the host machine (Windows OS)**.

Unless I'm misunderstanding something, these seem to contradict each other, with one saying WSL shares the same IP address of Windows, and the second saying WSL distributions will have a different IP address. 

The section on the linked networking page [here](https://docs.microsoft.com/en-us/windows/wsl/networking#accessing-linux-networking-apps-from-windows-localhost) seems to indicate this behaviour depends on the version of Windows you're running. If this is correct, the FAQ page should probably be updated.

### Suggested Improvements

If my understanding about the Windows version affecting whether you need to use an IP specific to the Linux VM is correct, the FAQ should be updated to explain that difference (probably just by Windows versions > Build 18945 don't need to use a different IP, but earlier ones do), and link to the appropriate part of the WSL Networking page.

**Comment by Biswa96** [comment]
The first one applies to WSL1. It's not specific to any Windows 10/11 version.

**Comment by TheRedshift** [comment]
Fair enough, seems like it would still be a good idea to specify in that first section that the behaviour described there is limited to WSL v1, since it's just under the "WSL" heading.

**Comment by craigloewen-msft** [comment]
These are both true actually! We forward over ports to Windows in WSL 2, and but still have separate IP addresses. So yes you can connect using `localhost` or you can use the IP address of your WSL 2 VM. Because of this different addressing not all networking scenarios might be the same (We use NAT for example) and so that's why the docs state it in this way.
