### ISSUE TITLE
Need an official network setup guide for WSL

### ISSUE THREAD

**Issue by vmanoj1996** [MicrosoftDocs/WSL#1485]
### Documentation Issue

Please write up a detailed documentation to illustrate how to access internet from WSL.
cover different scenarios including VPN case.

I had to search a lot of internet posts to arrive at the two fixes,
1.  Edit the resolv.conf to few IP addresses in right order.
2.  Do this in powershell: Get-NetAdapter | ? {$_.InterfaceDescription -like "*Cisco*" } |Set-NetIPInterface -InterfaceMetric 6000

Both hardly made sense to me.

**Comment by craigloewen-msft** [comment]
Added! https://learn.microsoft.com/en-us/windows/wsl/networking
