### ISSUE TITLE
Import Location Clarity

### ISSUE THREAD

**Issue by OhNoPleaseHelp** [MicrosoftDocs/WSL#1486]
### Documentation Issue

From the doc page: https://docs.microsoft.com/en-us/windows/wsl/use-custom-distro. It is unclear to a naïve reader (such as myself) why you would create E:\wslDistroStorage\CentOS instead of creating a CentOS folder under \AppData\Local\Packages where it seems the default WSL distros are stored

### Suggested Improvements

Perhaps a small explanation on why the location in the documentation was chosen, or an added option to create a folder in a similar location to the default WSL storage. Or, if that is not a possibility, a small explanation why.

**Comment by Biswa96** [comment]
The `\AppData\Local\Packages` path is for Windows Store apps only.

**Comment by OhNoPleaseHelp** [comment]
Clear and concise, thank you! I MUST create a different location for distributions I get outside of the Windows Store.
