### ISSUE TITLE
Some issues about install WSL in the documentation

### ISSUE THREAD

**Issue by wingdi** [MicrosoftDocs/WSL#1488]
### Documentation Issue
This is some steps need to do before install.

1 Before install , need enable WSL  from Control Panel --> program --> open or close Windows function --> enable Windows Subsystem for Linux. 

2 Before install , need check if there are some waiting for update packages from Setting --> Update and Security --> Windows update

**Comment by Biswa96** [comment]
Your provided step is documented here https://docs.microsoft.com/en-us/windows/wsl/install-manual.

It is not required to check for update always because Microsoft Windows is good at that 😉

**Comment by craigloewen-msft** [comment]
`wsl --install` should enable everything you need to run WSL!

If you're seeing issues please try filing a technical issue on the WSL repo. /product
