### ISSUE TITLE
Some wsl distro links are outdated!

### ISSUE THREAD

**Issue by Noino** [MicrosoftDocs/WSL#1497]
### Documentation Issue

Attempted to install Kali linux, initially with wsl --install, however that installed a broken/outdated version that even after adding apt keys couldn't update.
I read that people who have access to the Store app are able to install a relatively recent version that works well, but the link on https://docs.microsoft.com/en-us/windows/wsl/install-manual is the same, old, outdated, and broken version that the wsl command got me. 

### Suggested Improvements

pls fix links & wsl command

**Comment by SubSystemD** [comment]
Can confirm, the reliability of "exotic distros" beside Ubuntu is flaky at best when it comes to the out-of-the-box experience. MS does not see to care about keeping the images up to date. Sadly that means that deploying WSL to do serious network admin/pentesting work is out of the question. It's a shame.

**Comment by craigloewen-msft** [comment]
Fixed in latest, and the distro file list is also open sourced here: https://github.com/microsoft/WSL/blob/master/distributions/DistributionInfo.json
