### ISSUE TITLE
Intel driver link for WSL2 preview leads to nonfunctioning driver download page

### ISSUE THREAD

**Issue by gurgalex** [MicrosoftDocs/WSL#1502]
### Documentation Issue

https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#prerequisites

Clicking on "Intel GPU driver for WSL" leads to an Intel driver download pages with download buttons that don't function (clicking them doesn't download anything)

![image](https://user-images.githubusercontent.com/28968644/164729755-38c59d8b-169d-40e1-920c-2a842b8ed718.png)

Linked page
![image](https://user-images.githubusercontent.com/28968644/164729842-61100a83-cbdf-4072-817d-dd5b9809870d.png)

### Suggested Improvements

Change intel graphics driver URL
https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-10-windows-11-dch-drivers.html
to

https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html
![image](https://user-images.githubusercontent.com/28968644/164729944-b811884b-03be-43cb-aa70-63884f5ff9ae.png)

**Comment by mattwojo** [comment]
Thanks for contributing this issue @gurgalex! Looks like the link was fixed in https://github.com/MicrosoftDocs/WSL/commit/e3b8ab515e75b037bfe6e85dce87f9aaee074d2c

Just tried the Intel driver links and they appear to be working so closing this as resolved.
