### ISSUE TITLE
please add ubuntu 22.04 WSL direct download link

### ISSUE THREAD

**Issue by sonix07** [MicrosoftDocs/WSL#1507]
### Documentation Issue

please add ubuntu 22.04 WSL direct download link in the ```Downloading distributions``` section. This would be helpfull when Windows Store is blocked by company policy.

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/install-manual

**Comment by Biswa96** [comment]
* Link https://cloud-images.ubuntu.com/releases/22.04/release/
* File [ubuntu-22.04-server-cloudimg-amd64-wsl.rootfs.tar.gz](https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64-wsl.rootfs.tar.gz)
