### ISSUE TITLE
Installation failed on build 19044

### ISSUE THREAD

**Issue by dluc** [MicrosoftDocs/WSL#1512]
### Documentation Issue

On a freshly installed Win10 (build 19044) desktop I ran the `wsl --install` command and rebooted as requested. After the reboot when the installation attempts to complete, I got this error:

![image](https://user-images.githubusercontent.com/371009/167016226-bf47c287-5f18-45f0-a5e5-0b08e98bdeb0.png)

Windows version:

![image](https://user-images.githubusercontent.com/371009/167016376-627ba530-b55a-4f5b-9a31-74a2d8ee3f47.png)

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/install

### Suggested Improvements

There might be some more prerequisites, e.g. installing the kernel update mentioned in the link. I would double check with a new machine, and see if installing the kernel update upfront is a requirement to avoid the error.
Link to the kernel update docs: https://docs.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package

**Comment by craigloewen-msft** [comment]
Please update to the latest and try again, there have been many fixes for errors like these. I'm closing this issue for bookkeeping, if you see another error please file it at microsoft/wsl repo!
