### ISSUE TITLE
Add raw blob urls to Ubuntu 22.04

### ISSUE THREAD

**Issue by b1thunt3r** [MicrosoftDocs/WSL#1513]
### Documentation Issue

Cannot find the URL to download Ubuntu 22.04. 
Microsoft Store is disabled by IT, therefore I am not able to download WSL(2) distros from the Microsoft Store.

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions

### Suggested Improvements

If the URL to the blob for 22.04 is provided alongside older Ubuntu versions, I can install it manually.

**Comment by Biswa96** [comment]
It is possible to install Ubuntu 22.04 from official cloud images. Direct link https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64-wsl.rootfs.tar.gz.

**Comment by b1thunt3r** [comment]
@Biswa96 thanks.
This works for me, but you will need a bit more setup after manually importing it.

I am trying to help some non Linux users setup an environment for machine learning... 
An appx package would be easier for them.

**Comment by Biswa96** [comment]
AFAIK, the actual Ubuntu appx package is provided by Canonical Inc. So, this request should be directed to them somehow.

**Comment by Biswa96** [comment]
Or, download the Ubuntu 22.04 appx package from Windows Store using winget tool or https://store.rg-adguard.net/ website. Then install it with Add-AppxPackage command in Powershell. But it needs admin privilege.

**Comment by b1thunt3r** [comment]
> AFAIK, the actual Ubuntu appx package is provided by Canonical Inc. So, this request should be directed to them somehow.

Didn't know about that. The reason I posted it here was, there is a aka.ms link for 18.04, which was pointing to a (presumably) Microsoft owned blob storage.

Also just found out I didn't go through the previously created issues.
Closing it as duplicate of #1507.

**Comment by b1thunt3r** [comment]
> AFAIK, the actual Ubuntu appx package is provided by Canonical Inc. So, this request should be directed to them somehow.

Didn't know about that. The reason I posted it here was, there is a aka.ms link for 18.04, which was pointing to a (presumably) Microsoft owned blob storage.

Also just found out I didn't go through the previously created issues.
Closing it as duplicate of #1507.
