### ISSUE TITLE
Link is missing for ubuntu 22.04

### ISSUE THREAD

**Issue by anirugu** [MicrosoftDocs/WSL#1514]
### Documentation Issue

The page doesn't contain  the link to 22.04 Ubuntu file for WSL2.

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions

**Comment by mnacken** [comment]
Need this link aswell. In my company I dont have access to Windows Store.

**Comment by craigloewen-msft** [comment]
Fixed in latest!
