### ISSUE TITLE
Git Credential Manager install path changed

### ISSUE THREAD

**Issue by si618** [MicrosoftDocs/WSL#1517]
### Documentation Issue

GCM path has changed in git for windows 2.36.1, resulting in documentation error for `git config credential.helper ...` example

### Link to documentation page

[git-credential-manager-setup](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup)

### Suggested Improvements

Change path to:

``` bash
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"
```

**Comment by craigloewen-msft** [comment]
Fixed in latest!
