### ISSUE TITLE
path to Git for Windows credential manager has changed

### ISSUE THREAD

**Issue by briesenberg07** [MicrosoftDocs/WSL#1519]
### Documentation Issue

The WSL doc for [Git Credential Manager Setup](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup) is hugely helpful.  

But the location of the Git Credential Manager `.exe` file [has changed](https://github.com/git-for-windows/build-extra/pull/406) in a recent version of Git for Windows.  

So, I believe that the example `git config` command included in this doc is now out-of-date.

### Link to documentation page

[Get started using Git on Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git) > [Git Credential Manager Setup](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup)

### Suggested Improvements

Update the Bash git config command shown in the documentation

**Comment by craigloewen-msft** [comment]
Fixed in latest!
