### ISSUE TITLE
Git for Windows 2.36.1 changes path for Git Credential Manager

### ISSUE THREAD

**Issue by wbeeftink** [MicrosoftDocs/WSL#1520]
### Documentation Issue

Git for Windows 2.36.1 contains a breaking change moving the Git Credential Manager executable from `/libexec/git-core/` to `/bin`. It's mentioned in the changelog here:

> Git Credential Manager's binaries https://github.com/git-for-windows/build-extra/pull/406. This separates more clearly the core Git executables from the Git executables provided by third-parties.

This causes the credentials manager not te be found when following the instructions to setup the manager inside WSL.

Release notes:
https://github.com/git-for-windows/git/releases/tag/v2.36.1.windows.1

Change in code:
https://github.com/git-for-windows/build-extra/pull/406

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup

### Suggested Improvements

To reflect this change, the documentation should be updated from:
```
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe"
```

To this for Git `>= 2.36.1`:
```
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"
```

Or contain both suggestions per version.

**Comment by frank-digirati** [comment]
or even 

`git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-wincred.exe"`

**Comment by craigloewen-msft** [comment]
Fixed in latest!
