### ISSUE TITLE
Path to credential manager exe is outdated

### ISSUE THREAD

**Issue by danielcranford** [MicrosoftDocs/WSL#1522]
### Documentation Issue

Path to git-credential-manager-core.exe has changed. Recent versions of Git for Windows appear to place the file in `/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe` instead of the older `/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe` making the command to update the credential helper incorrect

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git

### Suggested Improvements

Suggest listing both paths or encouraging a search to ensure you have a path that works for your Git for Windows installation

**Comment by KyleRAnderson** [comment]
I ran into the same issue. In [Git for windows 2.36.0](https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#new-features-1), this binary was moved to what would now be `/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe`.

Suggested contents of the code snippet:
```bash
# For Git for Windows 2.36.0 and greater
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"
# For Git for Windows before 2.36.0
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe"
```

**Comment by craigloewen-msft** [comment]
Fixed in latest!
