### ISSUE TITLE
Would like to know if any debug level logs configuration, such as for the error message of 0x80370102

### ISSUE THREAD

**Issue by widuan** [MicrosoftDocs/WSL#1530]
### Documentation Issue

Thank you guys!

One of our recent installation on Windows 10, we repeated the error message of 0x80370102. We did find discussions in some issue threads, while we are not able to figure the issue.
We tried to look inside the backend progress, and we didn't find a way to get more valuable debug information.
Any possible that we can configure and output logs at debug level. That will help us to further invetigate root cause.

### Link to documentation page

https://github.com/microsoft/WSL/issues/7879

### Suggested Improvements

Thanks again! This issue is just for logs at debug level.

**Comment by widuan** [comment]
This was identified if the system enabled secure boot and vTPM, then there will be failure like the issue description.

**Comment by craigloewen-msft** [comment]
Please see the troubleshooting docs for this, or the microsoft/wsl GitHub repo
