### ISSUE TITLE
Documentation for Git Credential Manager setup has wrong path

### ISSUE THREAD

**Issue by abrthel** [MicrosoftDocs/WSL#1531]
### Documentation Issue

When describing how to setup Git Credential Manager using Git for Windows, the documentation says

```
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe"
```

as of Git for Windows build **2.36.1** that path no longer works as `git-credential-manager-core.exe` has been moved to `mingw65/bin`. See https://github.com/git-for-windows/build-extra/pull/406

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup

### Suggested Improvements

Another snippet such as the one below should be added to direct users to the correct path if they have an updated copy of git for windows.

```
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"
```

**Comment by craigloewen-msft** [comment]
Fixed in latest!
