### ISSUE TITLE
New version of Git stores credential manager at different location

### ISSUE THREAD

**Issue by ericmuijs** [MicrosoftDocs/WSL#1534]
### Documentation Issue

New location for credential manager : C:\Program Files\Git\mingw64\bin

Reference: https://github.com/git-for-windows/build-extra/pull/406

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git

### Suggested Improvements

git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe"

to:
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"

**Comment by craigloewen-msft** [comment]
Fixed in latest!
