### ISSUE TITLE
Git Credential Manager Core path has changed

### ISSUE THREAD

**Issue by ChrisFulstow** [MicrosoftDocs/WSL#1535]
### Documentation Issue

It appears the path to Git Credential Manager Core has changed in the latest Git For Windows release 2.36.1

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git

### Suggested Improvements

In section **Git Credential Manager setup**, update the path to GCM:
```
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe"
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"
```

**Comment by craigloewen-msft** [comment]
Fixed in latest!
