### ISSUE TITLE
WSL git using windows git credential manager

### ISSUE THREAD

**Issue by sduzair** [MicrosoftDocs/WSL#1541]
### Documentation Issue

The article says to use the following to link WSL git with the Windows GIT credential manager this didn't work for me:
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe"

This did:
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-wincred.exe"

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup

**Comment by Biswa96** [comment]
There are multiple issues about this topic.

**Comment by Agrover112** [comment]
This seems to have been updated in the Docs as of 16/7/2022 (accessing)
