### ISSUE TITLE
Git Credential Manager binary path changed in Git for Windows 2.36.1

### ISSUE THREAD

**Issue by simoncalvin** [MicrosoftDocs/WSL#1543]
### Documentation Issue

The instructions for configuring Git in WSL to use the Git Credential Manager are incorrect as of Git for Windows 2.36.1. Here's the relevant PR from the Git for Windows repository: https://github.com/git-for-windows/build-extra/pull/406

The binary is now installed at `/mnt/c/Program Files/Git/mingw64/bin/git-credential-manager-core.exe`, so the command to configure Git from the command line should be changed to:
```
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"
```

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git

**Comment by simoncalvin** [comment]
Here's the [Git Credential Manager documentation for WSL](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/wsl.md#configuring-wsl-with-git-for-windows-recommended) which has been updated to reflect the new location.

**Comment by krishnacx** [comment]
@craigloewen-msft We can close the issue.
