### ISSUE TITLE
WSL setup wiki is inaccurate

### ISSUE THREAD

**Issue by Pyr3z** [MicrosoftDocs/WSL#1546]
### Documentation Issue

The docs say to simply run
```shell
wsl --install
```
in an administrator Power Shell, but on a fresh Windows 10 machine (OS Build 19042.630) this yields:
```
wsl : The term 'wsl' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ wsl --install
+ ~~~
    + CategoryInfo          : ObjectNotFound: (wsl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Clearly something is missing from the documentation, probably in the "Prerequisites" section.

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/install

**Comment by Pyr3z** [comment]
I found the fix. This should be added to the "Prerequisites" section of the wiki.

From https://docs.microsoft.com/en-us/windows/wsl/troubleshooting :
> Ensure that the [Windows Subsystem for Linux Optional Component is installed](https://docs.microsoft.com/en-us/windows/wsl/install-manual#step-3---enable-virtual-machine-feature). Additionally, if you are using an ARM64 device and running this command from PowerShell, you will receive this error. Instead run wsl.exe from [PowerShell Core](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows), or Command Prompt.

**Comment by crramirez** [comment]
Hello @Pyr3z

This is not the prerequisite. The prerequisite is to install every update before trying to install WSL by this method.

I agree that this line should be added to the docs.

**Comment by craigloewen-msft** [comment]
This was due to an old issue from backport, now that most users are on the latest `wsl.exe --install` will be available to many users.
