### ISSUE TITLE
WSL Git Credential Manager configuration path is incorrect

### ISSUE THREAD

**Issue by bugsalexander** [MicrosoftDocs/WSL#1562]
### Documentation Issue

The WSL Git docs says to run the following command, 

```bash
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe"
```

but the `git-credential-manager-core.exe` file does not exist at the specified path:

![image](https://user-images.githubusercontent.com/22948432/174503427-d02fab70-3140-4bf2-9c2c-e30c9be7dd8f.png)

This is because the `git-credential-manager-core.exe` binary does not exist at the path specified in the WSL documentation. Here is what I see in the `/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/` folder: 

![image](https://user-images.githubusercontent.com/22948432/174503495-8a394481-cdbd-421b-96d7-21e5fe465cb6.png)

Visiting the[ GCM documentation ](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/wsl.md#configuring-wsl-with-git-for-windows-recommended
)however solved the problem, as they specify the correct path. It appears the `git-credential-manager-core.exe` file has moved to the `bin` folder.

```bash
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"
```

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup

### Suggested Improvements

Update the documentation with the new path to the `git-credential-manager-core.exe` file, and also perhaps link to the GCM documentation (in case the path changes again in the future)

**Comment by SaadAnsari17** [comment]
The command differs depending on the versions as mentioned in the doc 
![image](https://user-images.githubusercontent.com/94478736/185973669-8ede083a-98a8-43e5-bc5f-d54ca52fb91a.png)

**Comment by bugsalexander** [comment]
Closed as this seems to be fixed
