### ISSUE TITLE
command of usbip should be updated

### ISSUE THREAD

**Issue by bamboowh** [MicrosoftDocs/WSL#1579]
### Documentation Issue

the command does not work on ubuntu 22.04
```
sudo apt install linux-tools-5.4.0-77-generic hwdata
sudo update-alternatives --install /usr/local/bin/usbip usbip /usr/lib/linux-tools/5.4.0-77-generic/usbip 20
```
as described on the page [https://github.com/dorssel/usbipd-win/wiki/WSL-support#usbip-client-tools](url) the command should be
```
sudo apt install linux-tools-virtual hwdata
sudo update-alternatives --install /usr/local/bin/usbip usbip `ls /usr/lib/linux-tools/*/usbip | tail -n1` 20
```

### Link to documentation page

[https://docs.microsoft.com/en-us/windows/wsl/connect-usb#install-the-usbip-tools-and-hardware-database-in-linux](url)

**Comment by SaadAnsari17** [comment]
#1589  PR made.

**Comment by TonalidadeHidrica** [comment]
Hi, I tried your new command in Ubuntu 22.04 @ WSL2, but `usbipd list` ended up in:

```
WARNING: usbipd not found for kernel 5.15.74.2-microsoft

  You may need to install the following packages for this specific kernel:
    linux-tools-5.15.74.2-microsoft-standard-WSL2
    linux-cloud-tools-5.15.74.2-microsoft-standard-WSL2

  You may also want to install one of the following packages to keep up to date:
    linux-tools-standard-WSL2
    linux-cloud-tools-standard-WSL2
```

There's no such package listed above.  Do you have an idea what I am getting wrong?

**Comment by mattwojo** [comment]
Looks like this was fixed in https://github.com/MicrosoftDocs/WSL/pull/1589

**Comment by s-ol** [comment]
I just had USBIP forwarding break in my *running* WSL distro with the `usbipd not found kernel ...` message until I re-ran the `update-alternatives` command. It seems that the kernel that Linux sees was updated while the distro was running?

I need to ship software that relies on USB forwarding working predictably. I don't see any windows updates for today except for a "Security Intelligence Update for Microsoft Defender Antivirus" (KB2267602) and the Microsoft Store says the Ubuntu distro package hasn't been updated for over a week either. Does anyone know what update caused this, and if there is some way I can detect or disable these kind of updates?
