### ISSUE TITLE
Steps for running WSL as root user

### ISSUE THREAD

**Issue by DeclareHigh** [MicrosoftDocs/WSL#1583]
### Documentation Issue

The process for launching WSL as the root user is out of date:

> To change the default user to root use this command in PowerShell: C:\> lxrun /setdefaultuser root and then run Bash.exe to log in: C:\> bash.exe. Reset your password using the distributions password command: $ passwd username and then close the Linux command line: $ exit. From Windows command prompt or Powershell, reset your default user back to your normal Linux user account: C:\> lxrun.exe /setdefaultuser username.

Running lxrun.exe in PS or Command prompt return the below error message.

```
PS C:\WINDOWS\system32> lxrun.exe
lxrun.exe : The term 'lxrun.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ lxrun.exe
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (lxrun.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Instead, in order to launch a WSL session as the root user you run:

`wsl --user root`

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#using-older-versions-of-windows-and-wsl

### Suggested Improvements

Update the process for launching a WSL session as the root user to the correct command.

**Comment by Agrover112** [comment]
@DeclareHigh  This  command assumes you have the older WSL installation before 2017 creators update as clearly stated there.

**Comment by craigloewen-msft** [comment]
Yes this command is older, you should instead user  `wsl --user root` thank you for filing!
