### ISSUE TITLE
We need a WSL logo

### ISSUE THREAD

**Issue by linuxbckp** [MicrosoftDocs/WSL#1585]
### Documentation Issue

There's no logo of WSL until now.

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/about

### Suggested Improvements

I will design a WSL logo, put that into 'about' page and request a PR later.

**Comment by Biswa96** [comment]
There is already a logo, the blue penguin icon, with WSL Store version.

**Comment by linuxbckp** [comment]
BTW how can I access this logo? I will change the proposed logo later after
I access it.

Biswapriyo Nath ***@***.***> 于2022年8月16日周二 21:13写道：

**Comment by linuxbckp** [comment]
BTW if that blue penguin logo is not approved by Microsoft, I will also
give this logo a try.

Linux BCKP ***@***.***> 于2022年8月16日周二 21:19写道：

**Comment by craigloewen-msft** [comment]
WSL has an existing logo, as mentioned here: https://github.com/MicrosoftDocs/WSL/issues/1585#issuecomment-1216642344

Thank you for the feedback!
