### ISSUE TITLE
requires elevation

### ISSUE THREAD

**Issue by eastonrobotics-jeff** [MicrosoftDocs/WSL#1588]
### Documentation Issue

I typed wsl --install and got "the requested operation requires elevation."  No mention of this error in the instructions.

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/install
need a tip for "requested operation requires elevation" please

### Suggested Improvements

this has to be a pretty common error.

**Comment by Biswa96** [comment]
See the line:

> You can now install everything you need to run Windows Subsystem for Linux (WSL) by entering this command in an administrator PowerShell or Windows Command Prompt and then restarting your machine.

"Requires elevation" means the Command Prompt or Powershell need to be run as administrator.

**Comment by eastonrobotics-jeff** [comment]
thanks.  you might want to add that note in the instructions.
