### ISSUE TITLE
WSL Networking page uses a vague example to connect to a Windows side with no steps to reproduce it.

### ISSUE THREAD

**Issue by AlexFroio** [MicrosoftDocs/WSL#1590]
### Documentation Issue

In this example, a WSL instance is attempting to talk to a windows hosted node app, and are shown in order to give an example of network communication to windows from WSL. This example is wrong and conflicts with the next section's instructions with the need to bind the server to `0.0.0.0`.

Simply running a node app to `127.0.0.1` or `localhost` results in refused connections. 

To put up an example node server, I used the following code:
```js
const http = require('node:http');

const hostname = '0.0.0.0';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello, World!\n');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

if `const hostname` is set to `127.0.0.1`, the address will not resolve for the WSL instance. 

![image](https://user-images.githubusercontent.com/17257643/185461552-d0d2a66d-0efe-4141-b94f-ff013aeafe0e.png)

This was already resolved in https://github.com/MicrosoftDocs/WSL/issues/1328 as a needed step and the documentation does not reflect that.

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/networking#accessing-windows-networking-apps-from-linux-host-ip

### Suggested Improvements

Clarify the steps needed to bind a webserver so that the namespace resolves into a proper connection to the windows side, or move the section about binding to `0.0.0.0` before the example and fix the screenshot.

The following is an example of the correct version of said screenshot:
![image](https://user-images.githubusercontent.com/17257643/185462127-b441d388-a017-49dc-86fd-b093734165b7.png)

**Comment by AlexFroio** [comment]
Does anyone actually watch this issues page? I see the page I complained about gets updated with tidbits, but this still has not been addressed.

**Comment by craigloewen-msft** [comment]
Hi @AlexFroio , apologies as this got buried. This should be working now in the latest versions of WSL, and the networking docs page has had tons of improvements since then. Thank you for filing this!
