### ISSUE TITLE
Windows Store Page doesn't mention the requirement of having "Virtual Machine Platform optional component" enabled

### ISSUE THREAD

**Issue by vendors-c101** [MicrosoftDocs/WSL#1595]
### Documentation Issue

The page has a great description on what it is and how it's different, but misses a critical component being you can't "just" install it via the Windows Store page. 

You need to have the Virtual Machine Platform component installed before/after installation of the Windows Store version of the Windows Subsystem for Linux Preview.

### Link to documentation page

https://www.microsoft.com/store/productId/9P9TQF7MRM4R

### Suggested Improvements

Adding in that you need to have that installed before/after installation of the Windows Subsystem for Linux Preview would make it a much quicker and easier install for users using the Windows Store to install. Having the link to documentation being there still would be good too for further exploration of the software.

**Comment by craigloewen-msft** [comment]
This store page isn't searchable anymore, and so we have all the relevant info on the docs instead. Thank you for filing this!
