### ISSUE TITLE
"wsl --install" command is not enough

### ISSUE THREAD

**Issue by kleenkanteen** [MicrosoftDocs/WSL#1596]
### Documentation Issue

I get the error same as this: https://github.com/MicrosoftDocs/WSL/issues/1054

The command should be "wsl.exe --install -d Ubuntu", that worked.

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/install

**Comment by craigloewen-msft** [comment]
This is now fixed in latest!
