### ISSUE TITLE
WSL needs a Quickstart section

### ISSUE THREAD

**Issue by richardcl1** [MicrosoftDocs/WSL#1597]
### Documentation Issue

I've managed to install WSL 2 using the manual installation steps (because I wanted to take the slow route and see the scenery) and it seems to have completed successfully. But now I'm stuck and I don't know what to do.
I would like to open a Bash window and look at my Linux operating system. I can't see anywhere in the documentation how to do this. I've Googled and not come up with an answer yet, but I expect with time and perseverance I will.
My background is that I'm an experienced Windows developer, certified in C#, SQL Server, Power BI, etc. I can do  basic stuff with Linux on Raspberry Pi and Azure CLI Bash. I am studying for AZ-220 IoT exam, and I want to learn to develop modules for IoT Edge. Hence, I need WSL 2 and Docker Desktop.

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/about

### Suggested Improvements

A new Quickstart section would be very helpful. It could show people (like myself) what to do once they have installed WSL 2.
1. How do you open a Bash window and execute some simple Linux commands to see the operating system works.
2. How do Linux and Windows coexist from a user's perspective?
3. Any dangers to avoid? eg Could I damage my Windows files by accessing them through Linux?
4. What about backups? I'm running Azure backup on my Windows computers. How will this be affected by WSL 2 and Linux?
5. How much disk space does WSL 2 and Linux take up?
6. Can I use GUI with Linux? If so, how?

**Comment by craigloewen-msft** [comment]
Added, thank you for the suggestion!
https://learn.microsoft.com/en-us/windows/wsl/setup/environment
