### ISSUE TITLE
Incorrect information for WSL command line options

### ISSUE THREAD

**Issue by TGH-TH** [MicrosoftDocs/WSL#1598]
### Documentation Issue

https://docs.microsoft.com/en-us/windows/wsl/basic-commands

out of the dozen or so command line switches literally every single one fails with an 'Invalid command line option:' error with the exception of the --help option

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/basic-commands

### Suggested Improvements

Correct the documentation and if you have versioning issues surrounding the wsl.exe version please make this clear and concise to the end user

**Comment by krishnacx** [comment]
There could be a chance that there is a inbox version of WSL. Try installing WSL available from the releases and check.

**Comment by craigloewen-msft** [comment]
Please try running `wsl --update` or `wsl --install` to get to the latest version!
