### ISSUE TITLE
Is there an easy (PowerShell?) way to get more information about WSL?

### ISSUE THREAD

**Issue by jypeter** [MicrosoftDocs/WSL#1599]
### Documentation Issue

The WSL installation documentation (link below) does not mention how to **easily determine by typing a command in a PowerShell**:
- the **installed version of WSL**. And I have not found an alternative way for determining this (but I'm not a _Windows internals_ expert): WSL does not appear in `Win-I + Applications`, and the `Windows Subsystem for Linux Update` application version you get there is just the kernel version. And the panel for activating Windows features does not mention versions
- or even **if you have never user WSL**,
- or if you have installed WSL 1 and **if you need to follow the required steps to upgrade to WSL 2**

Basically you have to _try to use `wsl`_ and analyze some slightly confusing results. That's probably the reason of the _kind of strange_ note in [Install WSL command](https://docs.microsoft.com/en-us/windows/wsl/install#install-wsl-command): `The above command only works if WSL is not installed at all, if you run wsl --install and see the WSL help text [...]`

It's not easy to explain this feeling but:
- if `wsl --update` works,  and gives you a kernel version
- **and** if `wsl --status` tells you that the default WSL version is 2, but gives you the https://aka.ms/wsl2-install link instead of the kernel version, then you know that WSL 1 is installed

I'd rather have a more direct way to get this information!

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/install#install-wsl-command

### Suggested Improvements

- maybe `wsl --status` could give more information, and don't report that the default version is 2, when WSL 2 is not activated 

- I see lots of other information that could be usefully displayed by `--status` or `--status -v`, like the base installation directory (`C:\Users\your_login\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc`), the location of the the system and swap _vhdx_ files, and their current and [max](https://docs.microsoft.com/en-us/windows/wsl/vhd-size) size, ...

- I'm more a Linux+Python user and I can only copy-paste PowerShell commands listed on the WSL pages. Could `Dism` be used and for answering some of my questions?

**Comment by craigloewen-msft** [comment]
We have included a `wsl --version` in latest which should help address this! Thank you!
