### ISSUE TITLE
The path to the mounted partition via windows is slightly incorrect

### ISSUE THREAD

**Issue by makoConstruct** [MicrosoftDocs/WSL#1600]
### Documentation Issue

Using windows 11. The page says the path to a mounted linux filesystem will be at `\\wsl$\\<Distro>\\<Mountpoint>`, but really it is at `\\wsl$\Ubuntu\<Mountpoint>`. (I was only able to find the path as a result of the run dialog's autocomplete suggestions for `\\wsl$`)

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk

**Comment by craigloewen-msft** [comment]
Fixed! Thank you!
https://github.com/MicrosoftDocs/WSL/commit/83b8a2e67615874e6529a11ebd023d89a70e53dc
