### ISSUE TITLE
Can't install WSL 2

### ISSUE THREAD

**Issue by OscarCarrilloTR** [MicrosoftDocs/WSL#1601]
### Documentation Issue

https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

### Link to documentation page

https://docs.microsoft.com/es-mx/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package

### Suggested Improvements

Review how can I download msi to being able to install WSL 2 Linux kernel in Windows 10.

**Comment by mikaello** [comment]
Do you mean that the download link is not working? Seems to be some issues about it (https://github.com/MicrosoftDocs/WSL/issues/1713, https://github.com/MicrosoftDocs/WSL/issues/1635, https://github.com/MicrosoftDocs/WSL/issues/1119), but it seems to be working fine now.
