### ISSUE TITLE
Gettng error in Microsoft Store while downloading Ubuntu.

### ISSUE THREAD

**Issue by zklim** [MicrosoftDocs/WSL#1609]
### Documentation Issue

The download starts and stops in the half way saying error with Code: 0x80080204.
I have turned on Windows Subsystem for Linux in Windows Features.

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/

**Comment by kadomcevi** [comment]
Same error 0x80080204 for me when I tried install Ubuntu 20.04.5LTS from Microsoft Store.
Download started and stop after 2-3 sec.

**Comment by Biswa96** [comment]
Try to use winget or `wsl --install` command.

**Comment by kadomcevi** [comment]
> Try to use winget or `wsl --install` command.

Thanks "winget" seems works

**Comment by zklim** [comment]
> Try to use winget or `wsl --install` command.

got this error using winget, I'm on Windows 10 `wsl --install` command not available for me.

![Capture](https://user-images.githubusercontent.com/53001910/190176974-c442e6cd-b989-4497-9a0e-823470911bed.PNG)

**Comment by Biswa96** [comment]
According to winerror.h, 0x80080204 means the manifest file of the Appx package is invalid. That may be a bug in the Ubuntu package. But kadomcevi said winget worked.

If nothing worked there are multiple ways to install it manually https://docs.microsoft.com/en-us/windows/wsl/install-manual

**Comment by zklim** [comment]
> According to winerror.h, 0x80080204 means the manifest file of the Appx package is invalid. That may be a bug in the Ubuntu package. But kadomcevi said winget worked.
> 
> If nothing worked there are multiple ways to install it manually https://docs.microsoft.com/en-us/windows/wsl/install-manual

Tried windows update and reinstall using winget works. Might be incompatible Microsoft Store version before this. Thanks!
