### ISSUE TITLE
DevBlog announcement says Systemd support will be made "available to all users" (I think you mean Windows 11 users?)

### ISSUE THREAD

**Issue by NotTheDr01ds** [MicrosoftDocs/WSL#1622]
### Documentation Issue

The [DevBlog announcement regarding 0.67.6 Systemd support](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/) says:

> This version of WSL is now available in the Microsoft Store to users on Windows Insiders build for initial testing, and then after a few weeks we will make it available to all users to ensure quality. You can run wsl --update to check for any WSL updates.

I believe this will be limited to Windows 11 users.  Might want to avoid confusion by stating that explicitly.

Not sure if this goes to the Doc team or if DevBlog changes need to be suggested elsewhere, but I figure someone here can get it the right visibility (if needed).

### Link to documentation page

https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/

### Suggested Improvements

Assuming that this is a Windows 11 feature-only, state that explicitly.

**Comment by aservedio** [comment]
This [ms store link](https://aka.ms/wslstorepage) to get WSL is also adding to the same kind confusion. I get a green checkmark on the System Requirements section, saying product should work on my device (Windows 10). It installs without error but opening it gives:

```
Windows version 10.0.19045.2251 does not support the packaged version of Windows Subsystem for Linux.
For information please visit https://aka.ms/wslinstall
``

It would be nice to clarify it there too.

**Comment by Biswa96** [comment]
Technically speaking, Windows 10 only added in AppxManifest.xml file in latest WSL Preview release. But the actual bits required for Windows 10 are not public yet, hence that error message + confusion.

**Comment by aservedio** [comment]
Thanks for the update!
I actually went ahead and signed up for insider preview in my windows 10, applied the extra upgrades and ran wsl --update at the end.
It works! :)

**Comment by NotTheDr01ds** [comment]
With the release of 1.0.0 in the Store, it's clear I was wrong about this.  Systemd support via is now available under Windows 10 22H2 with KB5020030 and WSL 1.0.0 or later.

**Comment by NotTheDr01ds** [comment]
With the release of 1.0.0 in the Store, it's clear I was wrong about this.  Systemd support via is now available under Windows 10 22H2 with KB5020030 and WSL 1.0.0 or later.
