### ISSUE TITLE
systemd support

### ISSUE THREAD

**Issue by RobMahn** [MicrosoftDocs/WSL#1629]
### Documentation Issue

Under "systemd support", the statement is made "You will need version 0.67.6+ of WSL to enable systemd. Check your WSL version with command wsl --version. If you need to update, you can grab the [latest version of WSL in the Microsoft Store](https://aka.ms/wslstorepage)."

1. My version of WSL didn't support the command wsl --version.
2. After updating from the Microsoft Store, I was at WSL version: 0.66.2.0, which is less than the stated required version.
3. I had to search for WLS releases and download the latest from https://github.com/microsoft/WSL/releases

### Link to documentation page

[](https://learn.microsoft.com/en-us/windows/wsl/wsl-config)

**Comment by NotTheDr01ds** [comment]
Good points:

* `wsl --version` is only available in Preview versions (it arrived in the first Preview release, [0.47.1](https://github.com/microsoft/WSL/releases/tag/0.47.1)

    It's got to be tough writing one set of docs that cover how to do things across all releases.  *Eventually*, the `--version` command will be on the majority of systems, but today I would say it's quite rare (since fewer people are running Preview than GA builds).

    And, of course, it wouldn't make sense to specify there in that doc that `--version` is available on 0.47.1 or later since you'd need `--version` to tell you that! ;-)

* All of the Systemd releases are currently "pre-release", meaning they are only in the Store for Insiders at the moment.  According to the [blog post](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/), that will change soon:

    > This version of WSL is now available in the Microsoft Store to users on Windows Insiders build for initial testing, and then after a few weeks we will make it available to all users to ensure quality.

    So I'm thinking that this should resolve soon enough on its own rather than require what would be a temporary doc fix.
