### ISSUE TITLE
WSL 2 Kernel Update Link not Available.

### ISSUE THREAD

**Issue by roberwil** [MicrosoftDocs/WSL#1635]
### Documentation Issue

The link does load, so the update cannot be dowloaded and there aren't alternate links.

### Link to documentation page

https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

**Comment by crramirez** [comment]
Hello @roberwil,

Could you test again? I just tested and the link is valid.

Regards,
Carlos

**Comment by Biswa96** [comment]
https://www.catalog.update.microsoft.com/Search.aspx?q=wsl can also be used.

**Comment by roberwil** [comment]
Thanks a lot, both answers helped.
