### ISSUE TITLE
Correct bash command: sudo apt install linux-tools-generic

### ISSUE THREAD

**Issue by russnowell** [MicrosoftDocs/WSL#1642]
### Documentation Issue

The suggested command to install Ubuntu linux USB tools is incorrect.

**Suggested command:** sudo apt install linux-tools-5.4.077-generic hwdata

**Ubuntu response:** 

E: Unable to locate package linux-tools-5.4.0.77-generic
E: Couldn't find any package by glob 'linux-tools-5.4.0.77-generic'

**Correct command:** sudo apt install linux-tools-generic hwdata

Please correct this in code box for following section:

(https://github.com/MicrosoftDocs/WSL/tree/main/WSL)/connect-usb.md

Thanks.

### Link to documentation page

(https://github.com/MicrosoftDocs/WSL/tree/main/WSL)/connect-usb.md

### Suggested Improvements

The suggested command: 

sudo apt install linux-tools-5.4.077-generic hwdata

should be corrected to read: 

sudo apt install linux-tools-generic hwdata

**Comment by craigloewen-msft** [comment]
Fixed in the latest version of the docs.
