### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by rashidjeffreysky** [MicrosoftDocs/WSL#1643]
### Documentation Issue

> ... due to it's integration with Windows and Windows Subsystem for Linux
should read 
> ... due to its integration with Windows and Windows Subsystem for Linux

> ...and it's specific microservices
should read 
> ...and its specific microservices

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers

### Suggested Improvements

Please ask techies to have their documentation proof read.

https://www.grammarly.com/blog/its-vs-its/

> It’s is a contraction of “it is” or “it has.” Its is a possessive determiner we use to say that something belongs to or refers to something.

**Comment by krishnacx** [comment]
Fixed already. @craigloewen-msft may close this issue.
