### ISSUE TITLE
sudo service docker start gives error "unrecognized service"

### ISSUE THREAD

**Issue by davetaflin** [MicrosoftDocs/WSL#1648]
### Documentation Issue

The following command issued, as instructed, in a WSL 2 Bash shell:

sudo service docker start

results in the error:

docker: unrecognized service

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/use-custom-distro

### Suggested Improvements

Provide instructions on making the docker service available within WSL 2 Linux environments (please note that I have followed the instructions on the Docker website for installing the Windows Docker Desktop and enabling WSL 2 therein; none of that made a docker service available within my Ubuntu 18 WSL 2 environment).

**Comment by craigloewen-msft** [comment]
If you are using Docker Desktop you can just run the docker commands without needing to start the docker service :) 

Thank you for filing!
