### ISSUE TITLE
wsl --version

### ISSUE THREAD

**Issue by louigi600** [MicrosoftDocs/WSL#1649]
### Documentation Issue

As suggested on the documentatuion @ https://learn.microsoft.com/en-us/windows/wsl/wsl-config
Section regarding systemd:
"You will need version 0.67.6+ of WSL to enable systemd. Check your WSL version with command wsl --version."

This does not work on windows 10 well at least it does not work on my Microsoft Windows [Version 10.0.19044.2251]
If I try wsl --version I get the help but no hint on what version I have.
Mind you I'm not interested to know if my linux subsystems are version 1 or 2, I want to know the version of WSL itself.
I did a wsl --update but to my understanding that just update the kernel.

From "apps & features" I get reported I have
Windows Subsystem for Linux update 5.10.102.1

This seems to be > than  0.67.6 and yet wsl --version does not work as many of the features described on  https://learn.microsoft.com/en-us/windows/wsl/wsl-config

The link for updating
"If you need to update, you can grab the [latest version of WSL in the Microsoft Store](https://aka.ms/wslstorepage)."
takes you to windows subsystem for linux preview ... and even it it was right place to go it wont open on my pc:
"Windows version 10.0.19044.2130 does not support the packaged version of Windows Subsystem for Linux.
For information please visit https://aka.ms/wslinstall
Press any key to continue..."

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/wsl-config

### Suggested Improvements

Please update and specify on which version of wsl/windows the features described woek.
In some places it does mention that you need wsl2 or windows 11, iv it is not mentioned what you need then reader will assume any combination of wsl/windows is valid.

**Comment by Swiftly1** [comment]
```
wsl --version
Invalid command line option: --version
```

So I went here: `https://aka.ms/wslstorepage`

and tried to install WSL but it tells me `Windows 10.0.19044.2251 does not support the packaged version of Windows Subsystem for Linux.` meanwhile Windows Update tells me that I'm up to date

What's going on?

**Comment by masaharu-kato** [comment]
WSL (Preview) Version 1.0.0 was released today, but in "Windows Subsystem for Linux" on the Microsoft Store, system requirements are set to "Windows 10 Version 19041.0 or later".
Is it fake? 😅

**Comment by buanzo** [comment]
Same here. I have been using WSL for a long time. I run build 10.0.19044.2251 but I get this when installing from store; "Windows version 10.0.19044.2251 does not support the packaged version of Windows Subsystem for Linux."

I expect this will soon be fixed.

**Comment by masaharu-kato** [comment]
> Same here. I have been using WSL for a long time. I run build 10.0.19044.2251 but I get this when installing from store; "Windows version 10.0.19044.2251 does not support the packaged version of Windows Subsystem for Linux."
> 
> I expect this will soon be fixed.

Oh, I forgot this thread.
My issue  #9157  solved the problem.
Please refer!
👇
> Please make sure that your machine is fully up to date. The Windows Update required is KB5020030.

**Comment by TomwKang** [comment]
Windows：10.0.19045.2251
WSL kernal：5.10.102.1
I run the "wsl --version" also has the error  "Invalid command line option: --version"
hope you can fix it 👍

**Comment by MirceaAurelian** [comment]
Any update on this?

**Comment by sbaum2s** [comment]
I fully updated my Win 10 to 22H2 and every possible update. It didnt work out. Then i tried to install every available version of KB5020030. Every version refused to be installed. Then i type a `wsl --status` and it told me my wsl was outdated and i needed to run `wsl --update`.

I did and after that `wsl --version` worked.

**Comment by Chealer** [comment]
For background, see #1663

**Comment by craigloewen-msft** [comment]
We've now updated this experience in backports so if you run `wsl --update` you should get put onto the Store version of WSL which does support the `wsl --version` command. I'll close this issue out as it is now addressed, thank you for filing this!
