### ISSUE TITLE
Install distributions in new hard-drive

### ISSUE THREAD

**Issue by mamanunu** [MicrosoftDocs/WSL#1650]
### Documentation Issue

Would you consider giving instructions for installing linux distributions in non C-drives.

From a search online, I found the following references: 
https://superuser.com/questions/1572834/is-there-any-way-to-install-wsl-on-non-c-drive
https://helloglenn.me/blog/installing-wsl-distro-in-different-drive-win/
https://damsteen.nl/blog/2018/08/29/installing-wsl-manually-on-non-system-drive
https://kontext.tech/article/308/how-to-install-windows-subsystem-for-linux-on-a-non-c-drive
https://medium.com/@ntbperst/install-wsl-ubuntu-20-04-in-other-non-c-drive-8c7fe020fc23

### Link to documentation page

The new procedure could be listed in a subsection of https://learn.microsoft.com/en-us/windows/wsl/install

### Suggested Improvements

The procedure appears to be [for D-drive]:
```

cd D:\
mkdir WSL
cd WSL

Invoke-WebRequest -Uri https://aka.ms/wslubuntu2004 -OutFile Ubuntu.appx -UseBasicParsing

move .\Ubuntu.appx .\Ubuntu.zip
Expand-Archive .\Ubuntu.zip
cd .\Ubuntu\
Rename-Item .\Ubuntu_2004.2021.825.0_x64.appx -Newname Ubuntu2004.zip
Expand-Archive .\Ubuntu2004.zip
.\ubuntu.exe
```

Best Regards

**Comment by Biswa96** [comment]
`wsl --import` command will help. See https://learn.microsoft.com/en-us/windows/wsl/use-custom-distro

**Comment by mamanunu** [comment]
I will also assume that:
```
curl.exe -L -o ubuntu-2004.appx https://aka.ms/wslubuntu2004
Add-AppxPackage .\ubuntu-2004.appx
```
can also do the trick once the file is located in D: drive

**Comment by Biswa96** [comment]
That is also documented here https://learn.microsoft.com/en-us/windows/wsl/install-manual
