### ISSUE TITLE
WSL install manual should contain a CLI command to download images

### ISSUE THREAD

**Issue by upr-kmd** [MicrosoftDocs/WSL#1652]
### Documentation Issue

WSL install manual should contain a CLI command to download images

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install-manual

### Suggested Improvements

Add a step, ie.:
wsl --install -d Ubuntu

**Comment by mattwojo** [comment]
We say in the intro to the manual install page that we recommend using the install command with a link.
