### ISSUE TITLE
Which steps must be run without admin privileges

### ISSUE THREAD

**Issue by jinhale** [MicrosoftDocs/WSL#1655]
### Documentation Issue

There are two steps that specify that PowerShell must be accessed with administrator privileges. There are no steps that specify when PowerShell must be accessed with normal privileges. 

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package

### Suggested Improvements

Please specify where admin privileges are incorrect here. The Troubleshooting [page](https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#installation-issues) already has some information: "... you should ensure that you aren't accidentally running the built-in Administrator account that comes with Windows."

**Comment by mattwojo** [comment]
I think youre misinterpreting that troubleshooting page. Any of the steps on the manual install can be run with elevated admin permission.
