### ISSUE TITLE
Incorrect command example

### ISSUE THREAD

**Issue by jinhale** [MicrosoftDocs/WSL#1656]
### Documentation Issue

A command is incorrectly lacking `wsl`. The following command will not run: `ipconfig.exe | grep IPv4 | cut -d: -f2`.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/setup/environment?source=recommendations

### Suggested Improvements

Please prefix with `wsl` as so: `ipconfig.exe | wsl grep IPv4 | wsl cut -d: -f2`.

**Comment by mattwojo** [comment]
The instruction is written for use from a Bash command line, which will work as-is, but I'll add some clarity, as well as this version for doing the same in PowerShell. Thanks!

**Comment by mattwojo** [comment]
https://github.com/MicrosoftDocs/WSL/commit/5e5d9c1e2dd5cd199661fc85bbeaf46d059b8bd2
