### ISSUE TITLE
git-credential-manager.exe location change

### ISSUE THREAD

**Issue by piratebriggs** [MicrosoftDocs/WSL#1657]
### Documentation Issue

The example command to setup git credential manager in wsl doesn't work anymore. It looks like the exe has changed from
`git-credential-manager.exe`
to
`git-credential-wincred.exe`

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-git

### Suggested Improvements

`git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-wincred.exe"`

tested in `git version 2.38.1.windows.1`

**Comment by piratebriggs** [comment]
Ah, I miss-read the two example commands - I've tried using the `git-credential-manager-core.exe` version and that works also.

**Comment by Jimimaku** [comment]
> ### Documentation Issue
> The example command to setup git credential manager in wsl doesn't work anymore. It looks like the exe has changed from `git-credential-manager.exe` to `git-credential-wincred.exe`
> 
> ### Link to documentation page
> https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-git
> 
> ### Suggested Improvements
> `git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-wincred.exe"`
> 
> tested in `git version 2.38.1.windows.1`
