### ISSUE TITLE
Please add information on how to update "wsl.exe" itself

### ISSUE THREAD

**Issue by 62mkv** [MicrosoftDocs/WSL#1663]
### Documentation Issue

I am reading https://learn.microsoft.com/en-us/windows/wsl/basic-commands, and it looks like my own `wsl.exe` is ... some other command entirely. It rejects `--import-in-place` subcommand, it rejects `--vhdx` option; damn, it even rejects `--version` command: 

```
Invalid command line option: --version

Copyright (c) Microsoft Corporation. All rights reserved.



Usage: wsl.exe [Argument] [Options...] [CommandLine]



Arguments for running Linux binaries:



    If no command line is provided, wsl.exe launches the default shell.



    --exec, -e <CommandLine>

        Execute the specified command without using the default Linux shell.



    --

        Pass the remaining command line as is.



Options:

    --cd <Directory>

        Sets the specified directory as the current working directory.

        If ~ is used the Linux user's home path will be used. If the path begins

        with a / character, it will be interpreted as an absolute Linux path.

        Otherwise, the value must be an absolute Windows path.



    --distribution, -d <Distro>

        Run the specified distribution.



    --user, -u <UserName>

        Run as the specified user.



Arguments for managing Windows Subsystem for Linux:



    --help

        Display usage information.



    --install [Options]

        Install additional Windows Subsystem for Linux distributions.

        For a list of valid distributions, use 'wsl --list --online'.



        Options:

            --distribution, -d [Argument]

                Downloads and installs a distribution by name.



                Arguments:

                    A valid distribution name (not case sensitive).



                Examples:

                    wsl --install -d Ubuntu

                    wsl --install --distribution Debian



    --set-default-version <Version>

        Changes the default install version for new distributions.



    --shutdown

        Immediately terminates all running distributions and the WSL 2

        lightweight utility virtual machine.



    --status

        Show the status of Windows Subsystem for Linux.



    --update [Options]

        If no options are specified, the WSL 2 kernel will be updated

        to the latest version.



        Options:

            --rollback

                Revert to the previous version of the WSL 2 kernel.



Arguments for managing distributions in Windows Subsystem for Linux:



    --export <Distro> <FileName>

        Exports the distribution to a tar file.

        The filename can be - for standard output.



    --import <Distro> <InstallLocation> <FileName> [Options]

        Imports the specified tar file as a new distribution.

        The filename can be - for standard input.



        Options:

            --version <Version>

                Specifies the version to use for the new distribution.



    --list, -l [Options]

        Lists distributions.



        Options:

            --all

                List all distributions, including distributions that are

                currently being installed or uninstalled.



            --running

                List only distributions that are currently running.



            --quiet, -q

                Only show distribution names.



            --verbose, -v

                Show detailed information about all distributions.



            --online, -o

                Displays a list of available distributions for install with 'wsl --install'.



    --set-default, -s <Distro>

        Sets the distribution as the default.



    --set-version <Distro> <Version>

        Changes the version of the specified distribution.



    --terminate, -t <Distro>

        Terminates the specified distribution.



    --unregister <Distro>

        Unregisters the distribution and deletes the root filesystem.
```

I did `wsl --update` (both before and after running `wsl --shutdown`) and it seems to have applied some updates, but it does not change _anything_ of the above! 

Currently `wsl --status` provides this: 
```
Default Distribution: Ubuntu-20.04

Default Version: 2


Windows Subsystem for Linux was last updated on 27.11.2022

The Windows Subsystem for Linux kernel can be manually updated with 'wsl --update', but automatic updates cannot occur due to your system settings.

To receive automatic kernel updates, please enable the Windows Update setting: 'Receive updates for other Microsoft products when you update Windows'. 

For more information please visit https://aka.ms/wsl2kernel.


Kernel version: 5.10.102.1
```

this is all with `wsl.exe` from `C:\Windows\system\wsl.exe`

Windows OS/build info:

```
Microsoft Windows [Version 10.0.19045.2251]

Edition	Windows 10 Pro
Version	22H2
Installed on	‎17.‎11.‎2020
OS build	19045.2251
Experience	Windows Feature Experience Pack 120.2212.4180.0
```

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/basic-commands

### Suggested Improvements

Please add information to the abovementioned page on how to update `wsl.exe` to latest version

**Comment by Biswa96** [comment]
There is already an installation instruction here https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by 62mkv** [comment]
well, I obviously have it installed, and I was using WSL 2 for many months, no issues. how do I _update_ it?

**Comment by Biswa96** [comment]
You probably have not installed the WSL from Store. 
* More info here https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/
* Windows Store link https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R?hl=en-us&gl=us
* Direct download link https://github.com/microsoft/WSL/releases

**Comment by Stabledog** [comment]
It would still be good if there was a version number available for `wsl.exe` itself.  An odd omission.

**Comment by Biswa96** [comment]
The wsl.exe from Store version of WSL has version number.

**Comment by Biswa96** [comment]
Both wsl.exe from system and Windows Store WSL have version number.

**Comment by 983510** [comment]
@Biswa96 thank you very much  for links.
@Stabledog there was no command '--version' in old releases, but you can see version in other outputs

After updated via [link](https://github.com/MicrosoftDocs/WSL/issues/1663#issuecomment-1328256589) to WinStore my wsl works perfectly as documented.

**Comment by mattwojo** [comment]
Added a note on the Basic Commands page about getting the Microsoft Store installed version of WSL in order to receive the latest updates in hopes of reducing other having the same issue. Thanks for filing @62mkv. Closing this as there doesn't seem to be any other updates needed to the docs, but please re-open if you find this is not the case.

**Comment by Chealer** [comment]
> You probably have not installed the WSL from Store.
> 
>     * More info here https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/
> 
>     * Windows Store link https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R?hl=en-us&gl=us
> 
>     * Direct download link https://github.com/microsoft/WSL/releases

I'm afraid this direct download link does not actually update `wsl.exe`. Even after installing `wsl.2.2.4.0.x64.msi`, one can get (depending on the Windows version):

> PS C:\WINDOWS\system32> (get-item wsl.exe).VersionInfo.FileVersion
> 10.0.19041.1151 (WinBuild.160101.0800)
