### ISSUE TITLE
Suggestion: add a "howto" on using a bind mount in `/mnt/wsl/` to access a distro's files from another distro

### ISSUE THREAD

**Issue by phil-blain** [MicrosoftDocs/WSL#1671]
### Documentation Issue

It would be nice to document how to share a folder between distros, or access a distro's filesystem from another distro, basically what is explained here:

https://github.com/microsoft/WSL/issues/5177#issuecomment-624926928 (`mount --bind`), or the equivalent fstab entry.

Currently the only mention of the shared tmpfs `/mnt/wsl` is on the ["Mount a Linux disk in WSL 2"](https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk) page:

> #### Access the disk content
> 
> Once mounted, the disk can be accessed under the path pointed to by the config value: `automount.root`. The default value is `/mnt/wsl`.

(by the way this seems wrong, should that just be `/mnt` here?

### Link to documentation page

Somewhere under https://learn.microsoft.com/en-us/windows/wsl

**Comment by craigloewen-msft** [comment]
We have a section in the docs here which addresses this: 
https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#:~:text=You%20can%20also%20use%20this%20technique%20to%20mount%20and%20interact%20with%20the%20virtual%20hard%20disks%20of%20other%20WSL%20distros%2C%20as%20each%20WSL%202%20distro%20is%20stored%20via%20a%20virtual%20hard%20disk%20file%20called

Thank you for filing!

**Comment by computator** [comment]
That seems pretty sparse and doesn't talk about bind mounts or anything like that as far as I see? It pretty much only covers where a VHD gets mounted by default is all. I don't think this ticket should be closed yet.
