### ISSUE TITLE
Sentence duplication in WSL Install page

### ISSUE THREAD

**Issue by slippuu** [MicrosoftDocs/WSL#1672]
### Documentation Issue

Sentence duplication under Install/Install WSL

"If you're running an older build, or just prefer not to use the install command and would like step-by-step directions, see [WSL manual installation steps for older versions](https://learn.microsoft.com/en-us/windows/wsl/install-manual)."

appears twice

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install

### Suggested Improvements

Remove one of the offending paragraphs

**Comment by phil-blain** [comment]
duplicate of #1660

**Comment by craigloewen-msft** [comment]
Fixed in latest!
