### ISSUE TITLE
Outdated Windows 10 instructions in the "Connect USB devices" How-to

### ISSUE THREAD

**Issue by adamrehn** [MicrosoftDocs/WSL#1675]
### Documentation Issue

The [Connect USB devices](https://learn.microsoft.com/en-us/windows/wsl/connect-usb) How-to page currently states that Windows 10 users will need to compile the WSL kernel from source in order to have access to a recent kernel version (>= 5.10.60.1) that includes USB/IP support:

> **Important**
>
> Windows 11 is recommended for connecting USB devices to a Linux distribution running on WSL 2. However, Windows 10 can be used to connect USB devices by building your own USBIP enabled WSL 2 kernel following the [instructions in the USBIPD-WIN project repo](https://github.com/dorssel/usbipd-win/wiki/WSL-support).

This was true up until very recently, but the [transition to the Windows Store version of WSL as the default under both Windows 10 and Windows 11](https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/) announced two weeks ago means that Windows 10 users now have access to up-to-date kernel versions without the need to compile from source! :tada:

In the interests of due diligence, I confirmed this by performing a manual update of WSL on a machine running Windows 10 version 22H2:

```
PS C:\WINDOWS\system32> wsl --update
Checking for updates...
Downloading updates...
Installing updates...
This change will take effect on the next full restart of WSL. To force a restart, please run 'wsl --shutdown'.
Kernel version: 5.10.102.1
```
After restarting WSL, the new kernel version is reported as expected:

```
$ uname -a
Linux DESKTOP-EVM723C 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/connect-usb

### Suggested Improvements

The text of the existing alert should be updated to instead direct Windows 10 users to update their WSL kernel to the latest version, with instructions for performing a manual update. A link to @craigloewen-msft's blog post [*The Windows Subsystem for Linux in the Microsoft Store is now generally available on Windows 10 and 11*](https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/) might also be helpful, since it includes instructions for verifying that the user's version of Windows 10 has the required updates to access the Windows Store version of WSL.

**Comment by mattwojo** [comment]
Thanks for filing this issue @adamrehn! Super helpful. I've made the update in https://github.com/MicrosoftDocs/WSL/commit/ee8080f71abd6ad803eeb8a6eef6092fa3cca588
