### ISSUE TITLE
Doesn't work unless you enable HyperV feature

### ISSUE THREAD

**Issue by valentijnscholten** [MicrosoftDocs/WSL#1676]
### Documentation Issue

On top of WSL feature and Virtual Machine feature also HyperV feature must be enabled. Otherwise no Distro will be able to start. Also see https://github.com/microsoft/WSL/issues/4951#issuecomment-1072259851

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install-manual

### Suggested Improvements

Add HyperV enablement step

**Comment by craigloewen-msft** [comment]
WSL requires the Virtual Machine Platform optional component which enables a subset of the Hyper-V features. The Hyper-V optional component is not required, but the hypervisor being enabled on the system is required. Thank you for the feedback!
