### ISSUE TITLE
WSL documentation mentions non-existent command line option

### ISSUE THREAD

**Issue by illbebach** [MicrosoftDocs/WSL#1679]
### Documentation Issue

In the [Basic commands for WSL](https://learn.microsoft.com/en-us/windows/wsl/basic-commands#set-wsl-version-to-1-or-2) web page, the documentation mentions.

```
Check WSL version

wsl --version

Check the version information about WSL and its components.
```

When I enter `wsl --version` from a powershell prompt, the command states `--version` is not recognized.

```
PS C:\> wsl --version
Invalid command line option: --version
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]
```

For reference, here's the output of `wsl --status`
```
PS C:\> wsl --status
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 8/30/2022
WSL automatic updates are on.

Kernel version: 5.10.102.1
```

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/basic-commands#set-wsl-version-to-1-or-2

**Comment by swagshaw** [comment]
I use to meet the same issue. And I use `wsl --update` to update my wsl. Then I can use `wsl --version`. Maybe you can have a try.

**Comment by ross-p-smith** [comment]
What version of Powershell are you using? I have just tried this on 7.3.2 and it works.

**Comment by gian1200** [comment]
I had the same issue and `wsl --update` solved it.

I went from `Kernel version: 5.10.102.1` to:
```
>wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1992
```

**Comment by mwentz** [comment]
I'm experiencing this as well. It seems that if your user account doesn't have the necessary permissions and you have to use a different user for the elevated Powershell this is what happens.
Powershell version 5.1.19041.3031
