### ISSUE TITLE
GUI Windows build requirement different than page for troubleshooting cannot connect open display

### ISSUE THREAD

**Issue by compinche** [MicrosoftDocs/WSL#1680]
### Documentation Issue

The WSL GUI page requires 19xxx, while the troubleshooting connect open display says is a 21xxx build that is required.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps
https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg

**Comment by craigloewen-msft** [comment]
Gui apps are available on Windows 10 builds (19XXX) so please take the docs here as accurate. I will follow up to correct the number on the WSLG wiki.

Thank you for filing!
