### ISSUE TITLE
Incorrect Link To MongoDB 

### ISSUE THREAD

**Issue by mariorecinos** [MicrosoftDocs/WSL#1682]
### Documentation Issue

The installation directions for mongodb need update the instructions indicate to use 

wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -

this gives a GNUPG Error in the terminal however when running 

wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -

this fixes the error and the rest of the documentation is great

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-database#install-mongodb

### Suggested Improvements

wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -

**Comment by mattwojo** [comment]
Resolved: https://github.com/MicrosoftDocs/WSL/commits/main/WSL/tutorials/wsl-database.md
Thanks for filing this issue!
