### ISSUE TITLE
Remove link to GPU preview driver from Linux GUI documentation

### ISSUE THREAD

**Issue by linghengqian** [MicrosoftDocs/WSL#1684]
### Documentation Issue

- The latest drivers from all vendors already support WSLg and should not continue to flag preview drivers.
- Refer to https://github.com/microsoft/wslg/issues/429 and https://github.com/microsoft/wslg/issues/776 .

### Link to documentation page

- https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#prerequisites
- ![image](https://user-images.githubusercontent.com/20187731/207004931-1f2f57e0-06ec-44aa-85b1-0aca9247a7fa.png)

### Suggested Improvements

- Removed link to GPU preview driver from Linux GUI documentation.

**Comment by linghengqian** [comment]
- I am working on this issue.

**Comment by Biswa96** [comment]
Instead of removing the link, should not those direct user to vendors' page about latest driver or how to download/install those?

**Comment by linghengqian** [comment]
> Instead of removing the link, should not those direct user to vendors' page about latest driver or how to download/install those?

- I have updated the PR. This issue itself does not need to change anything.
