### ISSUE TITLE
Problem with "Run Linux Gui apps with WSL tutorial"

### ISSUE THREAD

**Issue by MrPottery** [MicrosoftDocs/WSL#1688]
### Documentation Issue

The tutorial: [Run Linux GUI apps with WSL](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)  indicates that there are two prerequisites, the appropriate graphics driver and also

> **You will need to be on Windows 10 Build 19044+ or Windows 11 to access this feature**

Following the directions from the tutorial on my system (which is currently running Version 10.0.19044.2251) failed to work.  When I looked in the [link provided in the Troubleshooting section](https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg), it said:

> **You must be running on Windows build version 21364+ for WSLg to work.**

It would appear that one of these documents is incorrect.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps says a minimum version of 19044 is required, but https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg says that a minimum of 21364 is required.

### Suggested Improvements

If in fact, you must be running at least Windows 10 build 21364, please update the tutorial to reflect this.

**Comment by kiranpradeep** [comment]
I was thinking same. But it appears possible on win10. [link](https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/#comment-5812)
