### ISSUE TITLE
Duplicate instruction sentence

### ISSUE THREAD

**Issue by Aouatef-Djeghri** [MicrosoftDocs/WSL#1689]
### Documentation Issue

On the instructions page on how to [**Install Linux on Windows with WSL** ](https://learn.microsoft.com/en-us/windows/wsl/install), in section [**Install WSL command**](https://learn.microsoft.com/en-us/windows/wsl/install#install-wsl-command) there is a duplicate sentence. 
The sentence bellow is written twice :
If you're running an older build, or just prefer not to use the install command and would like step-by-step directions, see [WSL manual installation steps for older versions](https://learn.microsoft.com/en-us/windows/wsl/install-manual).

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install

### Suggested Improvements

Deleting the duplicate sentence.

**Comment by phil-blain** [comment]
duplicate of #1660

**Comment by mattwojo** [comment]
Issue has been resolved. Thanks for filing!
