### ISSUE TITLE
Note for "Add the init script to start MongoDB as a service"

### ISSUE THREAD

**Issue by AlexStormwood** [MicrosoftDocs/WSL#1690]
### Documentation Issue

The steps regarding running MongoDB as a service are failing even when followed correctly, due to a change to the MongoDB `init.d/mongodb` script that MongoDB has made. 

Specifically, this command is pulling a broken file: 

`curl https://raw.githubusercontent.com/mongodb/mongo/master/debian/init.d | sudo tee /etc/init.d/mongodb >/dev/null`

Digging through Mongo's repo and trying to get that `init.d` file at different points in time has shown this one marked with the green tick as working, while the recent commits are not working: 

![image](https://user-images.githubusercontent.com/22165407/209126313-687f9afe-5342-44e7-8dca-96681dc623c5.png)

### Link to documentation page

https://learn.microsoft.com/en-gb/windows/wsl/tutorials/wsl-database#add-the-init-script-to-start-mongodb-as-a-service

### Suggested Improvements

Update the documentation to either refer to the specific last working commit in the MongoDB script file, or to specifically state the curl command that uses the last working commit:

For example, instead of:

`curl https://raw.githubusercontent.com/mongodb/mongo/master/debian/init.d | sudo tee /etc/init.d/mongodb >/dev/null`

Use:

`curl https://raw.githubusercontent.com/mongodb/mongo/cad54eb5ebdff24ecec53b56788cd151d8d64272/debian/init.d | sudo tee /etc/init.d/mongodb >/dev/null` 

Using that command allows me to run MongoDB v5 as a service in WSL2 with Ubuntu 20.04.

~~Haven't tried with Ubuntu 22 yet as it looks like that has other issues related to MongoDB v6, and I can see at least one other issue addressing that already.~~ Update ~30 minutes later, this workaround does not work for MongoDB v6 on Ubuntu 22 for WSL2.

I can't see how to log issues into Mongo's repo for this, and am not familiar enough with the coding needed to fix things up anyway -- I just know that using the command with a specific version of that file gets things working, and the WSL docs don't reflect that right now.

**Comment by Biswa96** [comment]
The latest WSL from Windows Store supports systemd. Is it required to add those init script in WSL's documentation? For example, this page has systemctl commands https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/

**Comment by AlexHolderDeveloper** [comment]
I did try that briefly -- WSL2 from the Windows Store with Ubuntu 22 -- but I couldn't get things working. In fact, it seems unrelated as that page does also have commands for "System V Init (service)" which use `system service [service name] start`-type commands as per the MS Docs.

**Comment by limyod** [comment]
Alex, Thanks for mentioning the broken link/command. I couldn't get this to work for a long time, and your note saved me from more confusion.

**Comment by AlexHolderDeveloper** [comment]
> Did this ever get figured out? I've tried a few different versions of the this debian init.d file and they all cause "sudo service mongodb start" to fail.

Are you using Windows 11 (latest) and WSL2 with Ubuntu 20 and aiming to install MongoDB v5, @Livingnight ? The version numbers of _everything_ matter here. 

I had to do a fresh install of everything about a week ago (replacing my OS SSD, yay!) and the steps still worked for me there. 

Here's the quick summary of steps that I give my uni students when they also have this issue:

- Go back to WSL2 with Ubuntu 20, stay away from Ubuntu 22 / Ubuntu. In Powershell, you can check what you have with wsl -l -v 
- Uninstall any not-wanted Ubuntu versions in Powershell with wsl --unregister [distribution name], such as wsl --unregister Ubuntu or wsl --unregister Ubuntu-22.04 
- Use the Microsoft Store to find and install Ubuntu 20.04. Specifically that version -- the MS Store listing that just says "Ubuntu" is the latest LTS, which is currently Ubuntu 22.04. 
- Follow installation steps as per the MS docs: https://learn.microsoft.com/en-gb/windows/wsl/tutorials/wsl-database#install-mongodb 
- Follow the init script steps as per the MS Docs BUT step 1 must use the command below: https://learn.microsoft.com/en-gb/windows/wsl/tutorials/wsl-database#add-the-init-script-to-start-mongodb-as-a-service 

`curl https://raw.githubusercontent.com/mongodb/mongo/cad54eb5ebdff24ecec53b56788cd151d8d64272/debian/init.d | sudo tee /etc/init.d/mongodb >/dev/null`

The commands like `sudo service mongodb start` and `mongosh` will be working after that. 

So no, beyond the hacky workaround for the installation steps, this hasn't been figured out officially by Microsoft or MongoDB. But we have these steps! If they don't work, you gotta provide more info.

**Comment by AlexHolderDeveloper** [comment]
Ah cool, great info there @Livingnight! First thing I'd try would be to try the steps on an Ubuntu installation instead of Debian. I don't know much about Linux stuff but from what I understand, Debian is "Ubuntu but with less stuff or older stuff pre-installed" so that may be impacting things.

But other than that, it could be a case of just trying different commit versions of that `init.d` file, as I had the same not-very-descriptive stuff happen when I was trying to find a working `init.d` file to use in the modified curl command.

**Comment by AlexHolderDeveloper** [comment]
Just as a "bump" for this repo, my current class of students is facing this same hassle now - a full 6 months later - and the same hacky workaround gets things working again.

As a teacher I try to wipe my own OS and make sure I do the installation of software alongside my students and we have new classes going through this every 3-4 months. I've been continuously going through this and nothing has changed. No new Ubuntu version or new MongoDB version gets things working consistently.

**Comment by mattwojo** [comment]
I believe that this issue is resolved now that WSL 2 supports systemd ([you do need to enable it](https://learn.microsoft.com/windows/wsl/systemd)), bringing MongoDB into alignment with the Linux instructions on the Mongo docs, but please re-open if you find that this is not the case.
