### ISSUE TITLE
Wrong command for installing a specific linux distribution

### ISSUE THREAD

**Issue by alexandrebcaruso** [MicrosoftDocs/WSL#1698]
### Documentation Issue

The docs mention this command `wsl --install <Distribution Name>` which doesn't work. 
It should be `wsl --install --distribution <Distribution Name>`

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/basic-commands#install

### Suggested Improvements

`wsl --install --distribution <Distribution Name>`

![image](https://user-images.githubusercontent.com/6711738/210141399-526e7d51-4f5a-49a5-8898-43053427b0b8.png)

**Comment by mattwojo** [comment]
In current versions of WSL and PowerShell this version of the install command works without the -d flag.
