### ISSUE TITLE
WSL: Invalid command

### ISSUE THREAD

**Issue by leandrobsilva** [MicrosoftDocs/WSL#171]
**Ways to run WSL**

wsl.exe or bash.exe [False]
wsl [command] or bash -c [command] [False]

**Review Request**

Options 2 and 3 are not valid in the environment below. 
![ev-01](https://user-images.githubusercontent.com/26843636/37362551-498428b6-26d4-11e8-946d-03b333ec6631.PNG)

Nome do sistema operacional:               Microsoft Windows 10 Pro
Versão do sistema operacional:             10.0.16299 N/A compilação 16299

**Comment by leandrobsilva** [comment]
**Solved** 
lxrun /install

**Comment by DarthSpock** [comment]
Note: Lxrun is deprecated in build 16299+. Officially listed as such in the Release Notes for Spring Creator's Update.
