### ISSUE TITLE
WSL Linux Kernel update can not be reached

### ISSUE THREAD

**Issue by mtunell** [MicrosoftDocs/WSL#1713]
### Documentation Issue

https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi does not seem to be reachable, I reached it last Thursday/Friday but this morning when I directed a colleague to download the update neither of us can reach it.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package

**Comment by mikaello** [comment]
The link seems to be working fine for me now. 

Similar issue to https://github.com/MicrosoftDocs/WSL/issues/1635
