### ISSUE TITLE
diskpart GB to MB needs to multiply by 1024 and not 1000

### ISSUE THREAD

**Issue by darren-stults-sp** [MicrosoftDocs/WSL#1722]
### Documentation Issue

> Virtual size: 512 GB, convert this to 512000. The new value you enter must be greater than this original value. For example, to double the virtual size of 512 GB to 1024 GB, you would convert to MB and enter the value: 1024000

If following this, the user will end up with 1000 GB (1024000 / 1024 = 1000) instead of 1024.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/disk-space

### Suggested Improvements

It should say:

> Virtual size: 512 GB, multiply by 1024 to convert this to 524288. The new value you enter must be greater than this original value. For example, to double the virtual size of 512 GB to 1024 GB, you would convert to MB and enter the value: 1048576

**Comment by mattwojo** [comment]
Added a bit more context to clarify this bit in https://github.com/MicrosoftDocs/WSL/pull/1848
