### ISSUE TITLE
Incorrect instructions on the doc page for usb under wsl

### ISSUE THREAD

**Issue by MichaelXt** [MicrosoftDocs/WSL#1725]
### Documentation Issue

```
sudo apt install linux-tools-5.4.0-77-generic hwdata
sudo update-alternatives --install /usr/local/bin/usbip usbip /usr/lib/linux-tools/5.4.0-77-generic/usbip 20
```
this does not work for WSL2/Win11. `E: Unable to locate package linux-tools-5.4.0-77-generic`

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/connect-usb

**Comment by craigloewen-msft** [comment]
Fixed in a PR!
