### ISSUE TITLE
specify to run command in elevated command prompt

### ISSUE THREAD

**Issue by maul0r** [MicrosoftDocs/WSL#1726]
### Documentation Issue

Trying to get WSL2 to work, Terminal prompted me with this link: 

https://aka.ms/enablevirtualization

Consequently I attempted to run `bcdedit /set {current} hypervisorlaunchtype Auto`. The documentation sates: 

> If you see hypervisorlaunchtype Off, then the hypervisor is disabled. To enable it run in an elevated powershell:

From my experience, this is wrong and it is not working. This needs to be run in the command prompt and specifically not powershell. 

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed

### Suggested Improvements

> If you see hypervisorlaunchtype Off, then the hypervisor is disabled. To enable it run in an elevated powershell:

Should be changed to "To enable it run in elevated command prompt:" "Note: If this command is run in Powershell, this includes the terminal, the following error will occur: 

```
PS C:\Users\username> bcdedit /set {current} hypervisorlaunchtype Auto
The set command specified is not valid.
Run "bcdedit /?" for command line assistance.
The parameter is incorrect.
```

**Comment by craigloewen-msft** [comment]
Both of these commands work correctly as stated from the docs using PowerShell:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/42221804/232900575-00fd2d11-64fe-4d6a-9324-29f6e2ee514c.png">


Thank you for the feedback!
