### ISSUE TITLE
The MS Teams Link returns 404

### ISSUE THREAD

**Issue by tikicoder** [MicrosoftDocs/WSL#1727]
### Documentation Issue

https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#install-microsoft-teams-for-linux
The documentation does not work. When you download the file it returns a 404. If you try to follow the url paths nothing appears to be there.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

### Suggested Improvements

deploy a version of teams for linux

**Comment by craigloewen-msft** [comment]
Fixed, removed the Teams section of this tutorial.
