### ISSUE TITLE
Confusing disk space commands

### ISSUE THREAD

**Issue by davidgilbertson** [MicrosoftDocs/WSL#1728]
### Documentation Issue

The disk space page suffers from quite a lot of assumed knowledge. For context, I landed on the page from a Google search, I'm not reading the docs end-to-end.

It gives the example:
```
wsl.exe --system -d <distribution-name> df -h /mnt/wslg/distro
```

I'm sure this makes perfect sense to veterans, but for me, I don't know what my distribution name is, and don't know what that path refers to. Is that path the same for everyone, or the person who wrote the docs page and it's something I need to change?

I found my distribution name after some further searching, but am yet to work out what that path is.

It also isn't clear if I'm supposed to be doing this in Windows, or from within WSL.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/disk-space

### Suggested Improvements

* If the path is not the same for everyone, docs could have `<your path here>` and tell me how to find what the path is.
* If 99% of distributions have the name `Ubuntu` then that would useful info at this point, or at least how to find it (since the people with the lowest knowledge of WSL probably have the simplest setups, you can be helpful without having to worry about all the edge cases)
* It would be good if the docs said where I was supposed to type this!

As with most examples, having an actual working example is always useful. Like "if your distribution name is X and your directory is Y you would type blah".

**Comment by davidgilbertson** [comment]
I've found that I do have a `/mnt/wslg` directory, but no `/distro` directory.
![image](https://user-images.githubusercontent.com/4443482/221714360-7c2bbd0a-f2d8-4caf-8863-03dd16d7b091.png)

**Comment by Biswa96** [comment]
> Is that path the same for everyone

That path is same for any Linux distribution in WSL2 irrespective of the distro name. The distributions in WSL2 have their own mount namespace. So, `/mnt/wslg/distro` points to their own root directory.

```
$ mount | grep -i /dev/sdc
/dev/sdc on / type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
/dev/sdc on /mnt/wslg/distro type ext4 (ro,relatime,discard,errors=remount-ro,data=ordered)
```

> I do have a /mnt/wslg directory, but no /distro directory.

`/mnt/wslg/distro` path is valid only in recent WSL versions from Windows Store.

**Comment by craigloewen-msft** [comment]
Fixed this with an additional command:
https://github.com/MicrosoftDocs/WSL/commit/32b28d6397662027b337ddb2641074e383c2d03d
