### ISSUE TITLE
Mounting USB disks doesn't specify non-Flash drives

### ISSUE THREAD

**Issue by ndemarco** [MicrosoftDocs/WSL#1729]
### Documentation Issue

This [page](https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk) explains how to mount a USB disk in WSL. The [Prerequisites](https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk) section does not include an important prerequisite / limitation; The feature does not support Flash disks.

A [long bug report](https://github.com/microsoft/WSL/issues/6011) is open on this topic.

### Link to documentation page

https://github.com/microsoft/WSL/issues/6011

### Suggested Improvements

Add a note stating the limitations of what types of disk/drive is supported.
Suggest adding a note of what types are explicitly not supported.
Suggest adding a link to the [issue ](https://github.com/microsoft/WSL/issues/6011)in GitHub.

**Comment by mattwojo** [comment]
Thanks for posting this issue @ndemarco. Updated the doc to address this in https://github.com/MicrosoftDocs/WSL/commit/1bad5506524a3b3ff68f006a70c67462bdcae478
