### ISSUE TITLE
Update Git Credential Manager setup code snippet to reflect Git Credential Manager Rename

### ISSUE THREAD

**Issue by zbillman** [MicrosoftDocs/WSL#1730]
### Documentation Issue

Text on the page says to use the following command: (emphasis wrapped in ** mine)

`git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager**-core**.exe"`

However, it listed on the [Git Credential Manager Rename](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/rename.md) page that "In November 2021, "Git Credential Manager Core" was https://github.com/GitCredentialManager/git-credential-manager/pull/541 to simply "Git Credential Manager", dropping the "Core" moniker."

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup

### Suggested Improvements

I recommend changing the documentation to use the modern naming convention.

`git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager.exe"`

This works on my WSL2 openSUSE Tumbleweed distribution from the Microsoft Store.

**Comment by mattwojo** [comment]
https://github.com/MicrosoftDocs/WSL/commit/f428a2ff9cfa5d35099a4cd2cf41049a2855c22e

**Comment by mattwojo** [comment]
Thanks for posting this issue @zbillman! Updated the docs to fix this in https://github.com/MicrosoftDocs/WSL/commit/f428a2ff9cfa5d35099a4cd2cf41049a2855c22e
