### ISSUE TITLE
[BUG] Wrong command to check your available disk space

### ISSUE THREAD

**Issue by turbotimon** [MicrosoftDocs/WSL#1733]
### Documentation Issue

> To check available disk space, open a PowerShell command line and enter this command (replacing <distribution-name> with the actual distribution name):
wsl.exe --system -d <distribution-name> df -h /mnt/wslg/distro

Gives me:
```
PS C:\Users\username> wsl.exe --system -d Ubuntu df -h /mnt/wslg/distro
Ungültige Befehlszeilenoption: --system
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Verwendung: wsl.exe [Argument] [Options...] [CommandLine]
...
```

Translation:
```
PS C:\Users\username> wsl.exe --system -d Ubuntu df -h /mnt/wslg/distro
Invalid command line option: --system
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine].
...
```

---
Distro info:
```
PS C:\Users\username> wsl --list --verbose
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop         Stopped         2
  docker-desktop-data    Stopped         2
```

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/disk-space

**Comment by Biswa96** [comment]
That `--system` command line option is valid if you are using Windows 11 or WSL from Windows Store. You could probably use `wsl -d ubuntu df -h /` command instead.

**Comment by turbotimon** [comment]
Well then I recommend adding this very important information. I think Windows 10 is still more common than Windows 11

**Comment by Biswa96** [comment]
Using `--system` option may have a reason. That documentation page is about expanding the vhdx file. So, one can not or should not do any operation on that vhdx file while the distro is being used.

**Comment by Biswa96** [comment]
Yeah, agree, that info should be added. Though WSL from Windows Store can be installed in latest Windows 10 versions.

**Comment by turbotimon** [comment]
> Though WSL from Windows Store can be installed in latest Windows 10 versions

I'm using an Windows Image with WSL preinstalled. I also do not understand why the same tool has different CLI commands depending on installation Source. And if so, again, I think it should be mentioned on this page 😀

**Comment by craigloewen-msft** [comment]
Fixed!
https://github.com/MicrosoftDocs/WSL/commit/32b28d6397662027b337ddb2641074e383c2d03d

Thank you for the feedback.
