### ISSUE TITLE
Old version of MongoDB in "Get started with databases" tutorial

### ISSUE THREAD

**Issue by lplawlor** [MicrosoftDocs/WSL#1734]
### Documentation Issue

The **Install MongoDB** section of the **Get started with databases on Windows Subsystem for Linux** tutorial uses version 5.0 of MongoDB. The current version of MongoDB is 6.0. Attempting to install MongoDB 5.0 on Ubuntu 22.04 causes unmet dependencies issues.

See https://askubuntu.com/a/1403683/1678519.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-database#install-mongodb

### Suggested Improvements

Steps 3 and 4 of this tutorial should be changed to use the MongoDB 6.0 public key and list file.
See the official MongoDB tutorial for installation on Ubuntu: https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/

**Comment by mattwojo** [comment]
https://github.com/MicrosoftDocs/WSL/commit/538469ff7984638248c7bfb8f88989445db1a67c

**Comment by mattwojo** [comment]
Thanks for raising this issue @lplawlor! Updated the docs to remove instructions with specific MongoDB dependencies and point to the MongoDB docs instead as the source of truth. Now that WSL supports systemd, the instructions for Linux distributions should work exactly the same on WSL. :)
Resolved in https://github.com/MicrosoftDocs/WSL/commit/538469ff7984638248c7bfb8f88989445db1a67c
