### ISSUE TITLE
[ENHANCEMENT] Documentation about how to publish your WSL image on Microsoft Store

### ISSUE THREAD

**Issue by D3vil0p3r** [MicrosoftDocs/WSL#1735]
### Documentation Issue

I have a Microsoft developer account for developing apps, games and Edge resources but in the Dashboard I don't see any content related to the publishing of a WSL image to the Microsoft Store.

Opened here as requested in https://github.com/microsoft/WSL/issues/9761

### Link to documentation page

Non existing

### Suggested Improvements

It could be very useful if a documentation could describe how to publish to Microsoft Store a WSL image (for example a Linux distribution).

**Comment by Biswa96** [comment]
The README of WSL-DistroLauncher project may help https://github.com/Microsoft/WSL-DistroLauncher

**Comment by craigloewen-msft** [comment]
As @Biswa96 mentioned, the README of the WSL-DistroLauncher is the right place, and we direct users to that repo for instructions.
