### ISSUE TITLE
Add new distributions download links

### ISSUE THREAD

**Issue by clatini** [MicrosoftDocs/WSL#174]
How to install Debian or Kali Linux WSL distros on Windows Server? Please add the related download links to doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install the Linux Subsystem on Windows Server | Microsoft Docs](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-on-server.md)
* Service: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by scooley** [comment]
I’m waiting to get a link to the download.  I’ll update as soon as I have that.

**Comment by benmp** [comment]
Also curious on the movement on this, specifically the Debian link.  Thanks!

**Comment by clatini** [comment]
Windows Server 1803 is out of beta, please add Debian and other distros download links to this doc.

**Comment by Fake4d** [comment]
Is there any update on this case?

**Comment by stardust38** [comment]
I'm very interested by the link for Debian :-D. Have you any update on this topic? Thanks!

**Comment by gavenkoa** [comment]
Existing URLs also mentioned in: https://blogs.msdn.microsoft.com/commandline/2018/05/15/build-2018-recap/

**Comment by Mr-SMG** [comment]
Work around:
-Use a Windows 10 machine to download Debian from the Windows Store
-Open %ProgramFiles%\WindowsApps (need to change ownership of folder)
-Copy the Debian folder over to your server 
-Run Debian.exe

**Comment by rhaist** [comment]
thanks to the MSF team debian is now available for download: 

https://aka.ms/wsl-debian-gnulinux

**Comment by clatini** [comment]
better late than never … :-)

**Comment by tara-raj** [comment]
Updated all distros available in the store woo! - https://docs.microsoft.com/en-us/windows/wsl/install-manual
