### ISSUE TITLE
Reversed information on git credential manager core/git credential manager for Git 2.36.1 above/below.

### ISSUE THREAD

**Issue by pedershk** [MicrosoftDocs/WSL#1740]
### Documentation Issue

On this page, the instructions for Git >=2.36.1 (greater than or equal to 2.36.1) in fact contain the instructions for Git <=2.36.1 (less than or equal to 2.36.1). In the next section, the instructions are also reversed (naturally).

Git Credential Manager Core (git-credential-manager-core.exe) was replaced by Git Credential Manager (git-credential-manager.exe) in version 2.36.1 of GIT.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup

### Suggested Improvements

Reverse the examples provided at https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup

**Comment by craigloewen-msft** [comment]
Related https://github.com/MicrosoftDocs/WSL/issues/1730

**Comment by mattwojo** [comment]
https://github.com/MicrosoftDocs/WSL/commit/f428a2ff9cfa5d35099a4cd2cf41049a2855c22e

**Comment by mattwojo** [comment]
Fixed this: https://github.com/MicrosoftDocs/WSL/pull/1779/commits/f428a2ff9cfa5d35099a4cd2cf41049a2855c22e

Thanks for bringing it to our attention!
