### ISSUE TITLE
Manual installation links for Ubuntu 20.04 LTS and 22.04 are wrong

### ISSUE THREAD

**Issue by alessiot89** [MicrosoftDocs/WSL#1741]
### Documentation Issue

The download links for x64 version of Ubuntu 20.04 LTS and the link for 22.04 LTS are wrong: they will point to an appx bundle of auto-upgradeable version (20.04 it will upgrade through store to last version, so far 22.04 and I guess the 22.04 to a next one when available) while it is supposed to be just the non-auto-upgrade versions. 

Correct download link for x64 version is this instead (guessed from ARM64 download) https://wsldownload.azureedge.net/Ubuntu_2004.2020.424.0_x64.appx

Cannot get the correct download links for x64 and ARM64 of 22.04 LTS.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install-manual?source=docs#downloading-distributions

### Suggested Improvements

Provides non-auto ugprade installation links for for 20.04 LTS and 22.04 LTS for both x64 and ARM64, in non-auto-ugpradable versions (for auto-upgrade version there is already the generic "ubuntu" version in both direct download and MS store).

**Comment by alessiot89** [comment]
I just saw the correct and direct download links can be obtained reading this json https://github.com/microsoft/WSL/blob/master/distributions/DistributionInfo.json

**Comment by craigloewen-msft** [comment]
Yes! We should examine replacing that list with the DistributionInfo.json page
