### ISSUE TITLE
WSL distro installation

### ISSUE THREAD

**Issue by zHessian** [MicrosoftDocs/WSL#175]
My company blocks access to the Windows Store. Can the distro install files be downloaded manually from another location?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install the Linux Subsystem on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by Biswa96** [comment]
@zhessian Now you can make your own distribution and install it. And can be download manually.

**Comment by Juniorn1003** [comment]
HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\

Change RemoveWindowsStore 1 to 0

Probably this will allow access to it.....
Do it fast though

**Comment by DarthSpock** [comment]
@Juniorn1003 You're not suggesting zHessian break his corporate policy rules are you? Acceptable ways are listed above. To explicitly show the links: https://github.com/Microsoft/WSL-distrolauncher/
https://docs.microsoft.com/en-us/windows/wsl/install-on-server

The Ubuntu appx does need updating. Debian and Kali aren't on there yet, it's been filed as an actionable item.

**Comment by tara-raj** [comment]
All distro manual insallation links are now up-to-date here - https://docs.microsoft.com/en-us/windows/wsl/install-manual
