### ISSUE TITLE
Need to enable systemd in wsl.conf

### ISSUE THREAD

**Issue by olaekdahl** [MicrosoftDocs/WSL#1750]
### Documentation Issue

Running `sudo service docker start` is not going to work unless you run these commands first:

```
sudo -i
vi /etc/wsl.conf
```
Add these two line:
```
[boot]
systemd=true
```

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/use-custom-distro

**Comment by craigloewen-msft** [comment]
`sudo service docker start` works with or without systemd support. Thanks for the feedback!

**Comment by olaekdahl** [comment]
I must be an edge case then. I get `docker: unrecognized service` without systemd.
