### ISSUE TITLE
Error code: Wsl/Service/CreateVm/ERROR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by bratherem** [MicrosoftDocs/WSL#1752]
### Documentation Issue

When run  `wsl --import docker-desktop C:\VM\DockerDesktop .\wsl-bootstrap.tar --version 2`
Result return `Error code: Wsl/Service/CreateVm/ERROR_FILE_NOT_FOUND`

Microsoft Windows [Version 10.0.19044.2486]

### Link to documentation page

not found

**Comment by craigloewen-msft** [comment]
Please file this as an issue at github.com/microsoft/wsl and include all the info there! This page is specifically for the docs, whereas that repo will be able to help you with technical issues.

Thank you!
