### ISSUE TITLE
Incorrect path to WSL folders

### ISSUE THREAD

**Issue by felixtsem5** [MicrosoftDocs/WSL#1753]
### Documentation Issue

Under the **Trouble finding docker image storage folder** section,
I believe it's \\\\$wsl\\ instead of \\wsl$\\ (the two bullet points, with single-backslash), and \\\\wsl\\ (after **Enter:**, no dollar sign).

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers

**Comment by mikaello** [comment]
Hm, on my computer™ it is another option that seems to be correct:

* `\\wsl$\docker-desktop`
* `\\wsl$\docker-desktop-data`

**Comment by craigloewen-msft** [comment]
The usage of `\\wsl$\` is correct, you can also use `\\wsl.localhost\`

**Comment by mikaello** [comment]
But the problem was also single slash, is that correct?

![Screenshot_20230419_082054_Chrome](https://user-images.githubusercontent.com/2505178/232984177-55c93da2-4053-4919-b8d4-6f6bb4488404.jpg)
