### ISSUE TITLE
Explain what the "Linux kernel update package" does

### ISSUE THREAD

**Issue by mikaello** [MicrosoftDocs/WSL#1758]
### Documentation Issue

In step 4 in [the manual install guide for WSL](https://learn.microsoft.com/nb-no/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package) the user is told to download and install the Linux kernel update package.

But what exactly is this, is this just an upgrade from the kernel you already got to the latest kernel version?

Is this instruction just the same as running `wsl --update` or `wsl --update --web-download`?

Would it be the same to download the latest stable release from https://github.com/microsoft/WSL/releases?

### Link to documentation page

https://github.com/MicrosoftDocs/WSL/blob/main/WSL/install-manual.md#step-4---download-the-linux-kernel-update-package

### Suggested Improvements

Add a short comment about the "why" and if it is the same as `wsl --update`, inform about that. Also, compare the difference between installing the kernel update and download the latest release from Store or https://github.com/microsoft/WSL/releases.

**Comment by craigloewen-msft** [comment]
Yes we should add a sentence that says "This page installs the in-Windows version of WSL, not the Store version of WSL" and link to our Store WSL info: aka.ms/wslstoreinfo
