### ISSUE TITLE
mounting an external disk: a simpler way is not mentioned

### ISSUE THREAD

**Issue by jungshik** [MicrosoftDocs/WSL#1760]
### Documentation Issue

The page below does not mention the simplest (and more importantly, actually working) method. 

Not sure what I'm doing wrong, but ```wsl --mount``` after getting the physical drive does not work. I keep getting the error message that the disk is in use even though I make sure that no other program (including File Explorer) is accessing it. 

However, in Linux shell, ```sudo mount -t drvfs e: /mnt/e``` works like charm. 

This method should be mentioned. 

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk

### Suggested Improvements

 ```sudo mount -t drvfs e: /mnt/e```  : the simplest alternative should be mentioned.

**Comment by mattwojo** [comment]
Thanks for bringing this up @jungshik. I added more context to the WSL mount doc and included more details about when to use `sudo mount -t drvfs` vs `wsl --mount` in: https://github.com/MicrosoftDocs/WSL/commit/1bad5506524a3b3ff68f006a70c67462bdcae478

The main diff is whether the drive you are mounting is formatted for Windows (NTFS) or for Linux (Ext4).
