### ISSUE TITLE
List AlmaLinux

### ISSUE THREAD

**Issue by bbaassssiiee** [MicrosoftDocs/WSL#1761]
### Documentation Issue

We dearly miss our favorite AlmaLinux in the instructions to install WSL manually.
https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-1---enable-the-windows-subsystem-for-linux

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-1---enable-the-windows-subsystem-for-linux

### Suggested Improvements

Please List AlmaLinux 8-9 as they are available in the Microsoft Store which is blocked by the corporate admins, while corporate developers need to develop for AlmaLinux with WSL.

**Comment by mattwojo** [comment]
Added in https://github.com/MicrosoftDocs/WSL/commit/ad1bfb81471d89a7083687fa3748c8dc97278b44.
