### ISSUE TITLE
Install Linux on Windows with WSL recommend bullet list instead of enumerated

### ISSUE THREAD

**Issue by aditijms** [MicrosoftDocs/WSL#1762]
### Documentation Issue

For https://learn.microsoft.com/en-us/windows/wsl/install#ways-to-run-multiple-linux-distributions-with-wsl I think a bullet list might be better here. Right now it presents as an ordered list. Thanks.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install#ways-to-run-multiple-linux-distributions-with-wsl

**Comment by mattwojo** [comment]
This correction was made in https://github.com/MicrosoftDocs/WSL/commit/9d10c38ac6f2e94c9ca678cee675133f06f4292e

Thanks for filing!
