### ISSUE TITLE
Punctuation: “its” does not take an apostrophe when used in the possessive

### ISSUE THREAD

**Issue by zgpmax** [MicrosoftDocs/WSL#1763]
### Documentation Issue

“WSL 2 uses a Network Address Translation (NAT) service for it's virtual network”

Pretty sure that [“its” does not take an apostrophe when used in the possessive](https://www.grammarly.com/blog/its-vs-its/).

### Link to documentation page

https://learn.microsoft.com/en-gb/windows/wsl/compare-versions#exceptions-for-using-wsl-1-rather-than-wsl-2

### Suggested Improvements

Remove apostrophe

**Comment by craigloewen-msft** [comment]
Fixed! Thank you for the feedback :)
