### ISSUE TITLE
The MS Store workaround is not self-contained

### ISSUE THREAD

**Issue by afilina** [MicrosoftDocs/WSL#1764]
### Documentation Issue

Under "Downloading distributions", the packages require dependencies, which cannot be downloaded if one doesn't have access to the MS Store due to aggressive security policies.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install-manual

### Suggested Improvements

Add self-contained installation files that include all dependencies and don't try to access the MS Store at any point.

**Comment by Biswa96** [comment]
Could you provide which package requires dependencies from MS Store?

**Comment by afilina** [comment]
The error message doesn't say. It just says that a package is missing and to contact the package developer (which is whoever packaged the distro as .appx)

**Comment by craigloewen-msft** [comment]
This should be fixed in the latest! This was an error with Ubuntu but should now be resolved.
