### ISSUE TITLE
Typo in a 'Note' section on the WSL basic commands wiki

### ISSUE THREAD

**Issue by JCK07115** [MicrosoftDocs/WSL#1766]
### Documentation Issue

In one of the `Note` sections, the `--install` directive is missing its second 'l'.

![typo-wsl-basic-commands-wiki](https://github.com/MicrosoftDocs/WSL/assets/9576322/bddbfc29-d182-48fa-8308-db030057a331)

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/basic-commands

### Suggested Improvements

Including the missing character, 'l'.

**Comment by craigloewen-msft** [comment]
Fixed in latest!
