### ISSUE TITLE
not able to complete my wsl documentation

### ISSUE THREAD

**Issue by Harsh00100** [MicrosoftDocs/WSL#1770]
### Documentation Issue

hello, 
I am trying to install linux on windows using wsl but i am unable to do due to the error:

WslRegisterDistribution failed with error: 0x80370114
Error: 0x80370114 The operation could not be started because a required feature is not installed.

kindly help me out as soon as possible

the instructions to sort out this error is not given in the documentation page
kindly add the above as well as help me out to resolve this error

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#installation-issues

**Comment by craigloewen-msft** [comment]
Please run `wsl --install` or verify that the WSL and Virtual Machine Platform optional component are installed. For further technical issues please file them at www.github.com/microsoft/wsl
