### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by NAGESHGOWDA1993** [MicrosoftDocs/WSL#1774]
### Documentation Issue

PS C:\Users\Administrator> wsl --install -d Ubuntu-22.04
Downloading: Ubuntu 22.04 LTS
Installing: Ubuntu 22.04 LTS
Ubuntu 22.04 LTS has been installed.
Launching Ubuntu 22.04 LTS...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization
Press any key to continue...
The installation process for distribution 'Ubuntu-22.04' failed with exit code: 1.
Error code: Wsl/InstallDistro/WSL_E_INSTALL_PROCESS_FAILED

### Link to documentation page

window

**Comment by craigloewen-msft** [comment]
Please run `wsl --install` to install WSL fully, and for any further technical issues please file them at www.github.com/microsoft/wsl
