### ISSUE TITLE
WSL disk space, "Read-only fallback error" when dealing with the main disk

### ISSUE THREAD

**Issue by arsu-leo** [MicrosoftDocs/WSL#1775]
### Documentation Issue

While this section allowed me to fix the issue I was having, I had to face the situation where the disk to repair belongs to the default distro. If you follow the mount instructions you will end up having a "ext file in use" when tring to perform the step 3 (wsl.exe lsblk) as any command will run on the default distro.

I had to install another Distro, set it as default and then I could run everything else fine.

At the end I changed the default back to main one.

### Link to documentation page

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/disk-space.md#read-only-fallback-error

### Suggested Improvements

Would be good if there was any insigh about what to do when the disk to fix is the default distro one otherwise you are locking yourself out when mounting.

**Comment by craigloewen-msft** [comment]
Adding @OneBlue for review!

**Comment by mattwojo** [comment]
Added a note about the requirement for a second distro to be installed: https://github.com/MicrosoftDocs/WSL/commit/d7dd0cc2e5a153cb9d9e8abc9cb9615361355790

**Comment by mattwojo** [comment]
Thanks for bringing this issue to our attention!
