### ISSUE TITLE
Customers receive error 0x80370102 if Trusted Launch is enabled for Azure VM. 

### ISSUE THREAD

**Issue by DerekHerman-MSFT** [MicrosoftDocs/WSL#1776]
### Documentation Issue

If Trusted Launch feature for Azure Virtual Machines is enabled customers will receive the error 0x80370102. This is a known compatibility issue since Nested Virtualization is not supported and documented on the Trusted Launch page [here.](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch#unsupported-features)
Request that you add this information to the Troubleshooting section so users can self resolve the issue.

https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed

### Suggested Improvements

State something like: "If you are receiving this error on your Azure Virtual Machine. Please check to ensure that [Trusted Launch](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch) is disabled." Please message me on teams if you have further questions.

**Comment by mattwojo** [comment]
Thanks @DerekHerman-MSFT. I added this statement about Azure VM Trusted Launch support to the Troubleshooting doc: https://github.com/MicrosoftDocs/WSL/pull/1779/files
Thanks for identifying this issue and please let me know if you see anything else.
