### ISSUE TITLE
Bash Command Error

### ISSUE THREAD

**Issue by Xie-Gustav** [MicrosoftDocs/WSL#1780]
### Documentation Issue

Bash command for "Install Gnome Text Editor" as following doesn't work.

sudo apt install gnome-text-editor -y

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#install-gnome-text-editor

### Suggested Improvements

Bash command for "Install Gnome Text Editor" should be as following.

sudo apt install gedit -y

**Comment by crramirez** [comment]
But the package **gnome-text-editor** does exists and is different from Gedit. If you issue `sudo apt info gnome-text-editor` it will say in the description:

```
Description: simple text editor for GNOME
 GNOME Text Editor is a simple editor for GNOME focused on being a good
 general purpose default editor.
 .
 It works hard to keep track of changes and state even if you quit the
 application. You can come back to your work even if you've never saved
 it to a file.
 .
 It is simpler than gedit.
```
_ It is simpler than gedit._

Which distro and version are you using?

**Comment by Xie-Gustav** [comment]
Hi,

I’m using Ubuntu 20.04 LTS now. Following CLI output is for your reference also.

~$ lsb_release -dc
Description:    Ubuntu 20.04.6 LTS
Codename:       focal

~$ apt list | grep gnome-text
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
plymouth-theme-ubuntu-gnome-text/focal 20.04.1 all

Seems gnome-text-editor becomes the default text editor after 22.04 LTS. Let me try to do a release upgrade first. Thanks for the prompt reply!



Kind regard,

Gustav
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mattwojo** [comment]
Thanks for pointing this out @Xie-Gustav. @crramirez is correct -- Gnome Text Editor has replaced gedit as the default in 22.04. I added a note with a link and instructions for installing gedit if you're running an older version of Ubuntu. > https://github.com/MicrosoftDocs/WSL/pull/1779/files
Thanks again.

**Comment by Xie-Gustav** [comment]
Thanks Matt for the confirmation and update work!!


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
