### ISSUE TITLE
Minor verbiage / grammar fix

### ISSUE THREAD

**Issue by kmmiles** [MicrosoftDocs/WSL#1781]
### Documentation Issue

> If you launch a distribution (ie. Ubuntu), modify the configuration file, close the distribution, and then re-launch it. You might assume that your configuration changes have immediately gone into effect.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/wsl-config

### Suggested Improvements

Use `e.g.` instead of `ie.` and make it one sentence.

> If you launch a distribution (e.g. Ubuntu), modify the configuration file, close the distribution, and then re-launch it, you might assume that your configuration changes have immediately gone into effect.

**Comment by mattwojo** [comment]
Good call! Fixed it: https://github.com/MicrosoftDocs/WSL/pull/1779/files
