### ISSUE TITLE
Page https://learn.microsoft.com/en-us/windows/wsl/networking#accessing-a-wsl-2-distribution-from-your-local-area-network-lan needs more information!

### ISSUE THREAD

**Issue by znmeb** [MicrosoftDocs/WSL#1784]
### Documentation Issue

I'm trying to run a web server in WSL2 and connect to it from another machine on my LAN. The section ["Accessing a WSL 2 distribution from your local area network"](https://learn.microsoft.com/en-us/windows/wsl/networking#accessing-a-wsl-2-distribution-from-your-local-area-network-lan) does not contain enough information to enable a user to successfully complete that task.

Specifically, on the `netsh` coomand, it does not tell the user how to obtain the IP address at the end of the command, nor does it tell the user what IP address to browse to from the client machine. Both pieces of information are necessary to successfully configure and test the web server.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/networking#accessing-a-wsl-2-distribution-from-your-local-area-network-lan

### Suggested Improvements

Add the information specified above.

**Comment by mattwojo** [comment]
Added more info: https://github.com/MicrosoftDocs/WSL/pull/1779/files
