### ISSUE TITLE
Which Git is referred here?

### ISSUE THREAD

**Issue by vikumbha-outlook** [MicrosoftDocs/WSL#1785]
### Documentation Issue

In https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-git page Git Credential Manager setup section has a line that says "If GIT installed is >= v2.39.0" which is unclear as to whether Git here is referring to Git in WSL Linux or Windows.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-git

**Comment by Biswa96** [comment]
The paragraph starts with "open your distribution and enter this command". Does not that mean git in WSL?

The best performance would be achieved -
1. Use git in WSL when the git repository is cloned in WSL.
2. Use git in Windows when the git repository is cloned in Windows.

_Not_ vice-versa.

**Comment by craigloewen-msft** [comment]
The line before says "Open up your WSL distribution and enter this command" indicating that this should be run within WSL. I think it's clear enough that it should be the git in WSL, without adding too much text to the doc. Thanks for the submission!
