### ISSUE TITLE
Docs description is not as the same as the setttings in example

### ISSUE THREAD

**Issue by counter2015** [MicrosoftDocs/WSL#1793]
### Documentation Issue

doc link: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#example-wslconfig-file

It says
```
# Turn off default connection to bind WSL 2 localhost to Windows localhost
localhostforwarding=true

# Disables nested virtualization
nestedVirtualization=false

# Turns on output console showing contents of dmesg when opening a WSL 2 distro for debugging
debugConsole=true
```

It should be **Turns on** default connection to bind WSL 2 localhost to Windows localhost 

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/wsl-config#example-wslconfig-file

### Suggested Improvements

```
# Turns on default connection to bind WSL 2 localhost to Windows localhost
localhostforwarding=true

# Disables nested virtualization
nestedVirtualization=false

# Turns on output console showing contents of dmesg when opening a WSL 2 distro for debugging
debugConsole=true
```

**Comment by mattwojo** [comment]
Thank you for identifying this issue @counter2015! Fixed in https://github.com/MicrosoftDocs/WSL/pull/1848
