### ISSUE TITLE
What should we substitue for <VMName>

### ISSUE THREAD

**Issue by dlech** [MicrosoftDocs/WSL#1795]
### Documentation Issue

In the following command, it appears that `<VMName>` is meant as a placeholder, but the surrounding documentation does not say what to replace it with.

>     Set-VMProcessor -VMName <VMName> -ExposeVirtualizationExtensions $true

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed

**Comment by Biswa96** [comment]
The name is shown in the Hyper-V Manager (image is just an example).

![image](https://github.com/MicrosoftDocs/WSL/assets/31443074/357fb67e-3552-45b5-b8c1-8eca1e61abf8)


That command is only required if you are running WSL inside of a Windows VM.

**Comment by dlech** [comment]
Thanks. The docs aren't clear if the command should be run on the host or the guest. Since the error occurs on the guest, I assumed the command needed to be run there as well, but now I see that it needs to be run on the host system.

**Comment by mattwojo** [comment]
Thanks for filing this issue @dlech and for the assist @Biswa96! Updated the doc with more context to resolve this in https://github.com/MicrosoftDocs/WSL/pull/1848
