### ISSUE TITLE
.wslconfig doesn't exist by default - docs page should mention to create it if needed

### ISSUE THREAD

**Issue by toxicbubble** [MicrosoftDocs/WSL#1798]
### Documentation Issue

It should be made more obvious that if the .wslconfig file doesn't exist in the profile, it will need to be created. This would help some people with less experience.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig

**Comment by mattwojo** [comment]
Thanks for posting this issue @toxicbubble! I've added a note about this to the docs in https://github.com/MicrosoftDocs/WSL/pull/1848
