### ISSUE TITLE
List item

### ISSUE THREAD

**Issue by samirgunic** [MicrosoftDocs/WSL#180]
```html
<li>
  <p>
    <a href="https://www.microsoft.com/store/apps/9MSVKQC78PK6" data-linktype="external">Debian GNU/Linux</a>
  </p>
  <p>
    <img src="media/ubuntustore.png" alt="" data-linktype="relative-path">
  </p>
</li>
```

No need to wrap it in another set of block elements. If you want styling, use CSS rules.

```html
<li>
  <a href="https://www.microsoft.com/store/apps/9MSVKQC78PK6" data-linktype="external">Debian GNU/Linux</a>
  <img src="media/ubuntustore.png" alt="" data-linktype="relative-path">
</li>
```

By the way, that screenshot is of Ubuntu, not Debian. So you may want to switch places of the Ubuntu and Debian list item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install the Linux Subsystem on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by samirgunic** [comment]
Then we have a bigger problem than we originally thought; we have a tool that has no taste for good design. 😄

Yes, I understood that. Unlike a computer, I can **goto** and understand intentions. There is no need for screenshots for each app. Just make that one screenshot display the contextually correct app, which in this case is Debian, or Ubuntu if you flip the list items around like I suggested. Or better yet, make the [WSL short link](https://github.com/MicrosoftDocs/WSL/issues/181) work and take a screenshot of all available Linux apps as displayed in the store.

**Comment by scooley** [comment]
Fixed the image issues :). Screenshots and text now match.  It was also a good excuse to clean up our metadata for better accessibility.
