### ISSUE TITLE
.wslconfig error

### ISSUE THREAD

**Issue by wuqijian-site** [MicrosoftDocs/WSL#1801]
Recently I was configuring WSL2's network, but recently when I started WSL2, I got the following error:"
The virtual machine or container JSON document is invalid.
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/0x8037010d”

.wslconfig file:

[wsl2]
networkingMode=bridged
vmSwitch=Kali
ipv6=true

The system is Win10
The linux is Kali

**Comment by OneBlue** [comment]
@wuqijian-site: Bridged networking is not supported on Windows 10. If you remove those 3 configuration values the issue should be resolved.
