### ISSUE TITLE
Documentation fails to fully describe windows OS requirements

### ISSUE THREAD

**Issue by ketchup201** [MicrosoftDocs/WSL#1804]
### Documentation Issue

The documentation states specific build numbers for Windows 10 and 11. It does not state anything about Windows Server versions. 

### Link to documentation page

https://docs.docker.com/desktop/install/windows-install/
Requirements:

- WSL version 1.1.3.0 or later.
- Windows 11 64-bit: Home or Pro version 21H2 or higher, or Enterprise or Education version 21H2 or higher.

- Windows 10 64-bit: Home or Pro 21H2 (build 19044) or higher, or Enterprise or Education 21H2 (build 19044) or higher.

- Turn on the WSL 2 feature on Windows. For detailed instructions, refer to the [Microsoft documentationopen_in_new](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

The following hardware prerequisites are required to successfully run WSL 2 on Windows 10 or Windows 11:

- 64-bit processor with [Second Level Address Translation (SLAT)open_in_new](https://en.wikipedia.org/wiki/Second_Level_Address_Translation)
- 4GB system RAM
- BIOS-level hardware virtualization support must be turned on in the BIOS settings.

### Suggested Improvements

If WSL is only supported on specific combinations of OS and versions, the OS and version list should cover all supported Windows OS, including Windows Server. If Windows Server is considered as "Windows 10" or "Windows 11", then this should be stated.

**Comment by mattwojo** [comment]
Thanks for posting this issue @ketchup201! I've updated the prereqs in the WSL Docker tutorial and linked to that install page in the Docker docs as that will be the source of truth for any Docker updates. I've also added a link to the Windows Server install doc instructions. > https://github.com/MicrosoftDocs/WSL/pull/1848
