### ISSUE TITLE
WSL1 and WSL2 comparison table - add row about Systemd and IPv6 support (critical features for many)

### ISSUE THREAD

**Issue by polarlightning** [MicrosoftDocs/WSL#1806]
### Documentation Issue

Please add these important WSL1 WSL2 comparison rows to compare against native physical machine Linux installation capabilities:
* Systemd support
* IPv6 support 

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/compare-versions

### Suggested Improvements

To the "Comparing features" table, please add rows describing support for these central and often critical Linux-features:

* Systemd support 
* IPv6 support

**Comment by mattwojo** [comment]
Great suggestion @polarlightning - Thank you! Updated in https://github.com/MicrosoftDocs/WSL/pull/1848

**Comment by hyanggi** [comment]
This change is not correct. IPv6 **IS** supported by WSL1.

As an evidence, please look at this blog post from 2017 and look for "IPv6" on that page:

https://devblogs.microsoft.com/commandline/windows-10-creators-update-whats-new-in-bashwsl-windows-console/

**Comment by tjayz** [comment]
Followed the bread crumbs in the links made the wsl.conf and can indeed confirm, in wsl1, ipv6 working. Verified with
 `curl -g -6 'https://[fe80::3ad1:35ff:fe08:cd%eth0]:443/'`
Unfortunately I learned I need to redo all my certs as the ipv6 was not listed in the SANs ;-)
