### ISSUE TITLE
Documentation does not say how to run WSL

### ISSUE THREAD

**Issue by HarcourtHamsa** [MicrosoftDocs/WSL#1811]
### Documentation Issue

The documentation does not say how to run the WSL

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install

### Suggested Improvements

Add a paragraph that explains how to run the WSL

**Comment by mattwojo** [comment]
Not sure what you mean here @HarcourtHamsa. You just need to check that your device meets the prerequisites and then use the `wsl --install` command to run WSL and install the default Ubuntu Linux distribution. Please feel welcome to reopen this issue and offer more clarification on what you would like to see updated.
