### ISSUE TITLE
Add Flatpak/Snapcraft installation instructions for mentioned GUI applications

### ISSUE THREAD

**Issue by linghengqian** [MicrosoftDocs/WSL#1813]
### Documentation Issue

- https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps mentioned some Gnome applications, they are `gnome-text-editor`, `gimp`, `nautilus` and `gedit`.

- In fact, Flatpak has long been the recommended way to install some Gnome applications. Refer to the following link.
    - https://apps.gnome.org/en/TextEditor/
    - ![image](https://github.com/MicrosoftDocs/WSL/assets/20187731/2e0b017b-0064-4535-9bcf-b178af934453)
    - https://www.gimp.org/downloads/
    - ![image](https://github.com/MicrosoftDocs/WSL/assets/20187731/cc35301c-14fd-48fd-a61a-74f99e7bb0bd)

- As for the vlc mentioned in the document, it is recommended to install through Snapcraft on Ubuntu. Refer to https://www.videolan.org/vlc/download-ubuntu.html .
- ![image](https://github.com/MicrosoftDocs/WSL/assets/20187731/d8fa2fbe-fcb3-49e5-a0c2-31f9cbc21ed5)

- Perhaps the documentation should mention both apt-get and flatpak/snapcraft installation? After all, snapcraft is installed on Ubuntu by default, and flatpak only requires one line of operation to install.

### Link to documentation page

- https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

### Suggested Improvements

- Add additional flatpak installations for `gnome-text-editor` and `gimp`.
- Add additional snapcraft installations for `vlc`.

**Comment by linghengqian** [comment]
@craigloewen-msft I just want to know your opinion.  Maybe I can submit a PR?

**Comment by craigloewen-msft** [comment]
Hi @linghengqian , yes please feel free to submit a PR! The point of this tutorial is just to get users up and started quickly, so as long as it works out of the box with the latest Ubuntu by default and everything can be input as a one liner then I think the changes will be very welcome. I'll close this issue and look out for a PR :)
