### ISSUE TITLE
add Server 2019 to the supported list

### ISSUE THREAD

**Issue by marypcbuk** [MicrosoftDocs/WSL#182]
now that the insider preview of Windows Server 2019 is available, worth explicitly noting that it's supported but that the Store is not available (because LTSC) - so the direct download links for other distros are needed even more

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install the Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-on-server.md)
* Service: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by scooley** [comment]
#199 Fixes this :).  Thanks!
