### ISSUE TITLE
`wsl/tutorials/wsl-database#install-postgresql` instructions result in a `psql (PostgreSQL) 14.9` installation

### ISSUE THREAD

**Issue by hamirmahal** [MicrosoftDocs/WSL#1822]
### Documentation Issue

https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-database#install-postgresql gives instructions that result in a `psql (PostgreSQL) 14.9` installation.

```
$  psql --version
psql (PostgreSQL) 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
```

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-database#install-postgresql

### Suggested Improvements

I think it'd be nice if the docs explicitly specified how to get version 15, or 16, of PostgreSQL installed in WSL2.

**Comment by mattwojo** [comment]
Thanks for sharing this feedback @hamirmahal. The WSL docs just refer to whatever version PostgreSQL is aligning to for the general `install postgresql` command. We don't have the resources to continually update these commands as PostgreSQL versions continue to update, but we do link out to the PostgeSQL docs, which should be the main resource.. the install in WSL will be the same as any of the Linux distros.

**Comment by hamirmahal** [comment]
You're welcome @mattwojo. Thanks for the additional context.
