### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by DrorHarari** [MicrosoftDocs/WSL#1827]
### Documentation Issue

In the paragraph:

> If you have mounted a NTFS-formatted drive on your Windows file system, you can access that drive from your Linux distribution using WSL by creating a mounted directory (sudo mkdir /mnt/d, replacing 'd' with whatever drive letter you'd like to use) and then using the **drfs** file system interop plugin, with the command:

Should be **drvfs** file system.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk

**Comment by mattwojo** [comment]
Thanks for fixing this. :) https://github.com/MicrosoftDocs/WSL/pull/1828
