### ISSUE TITLE
WSL Documentation incorrect about  'WSL' and 'Virtual Machine Platform components' Windows features being auto-enabled by wsl --install command

### ISSUE THREAD

**Issue by JAffleck** [MicrosoftDocs/WSL#1833]
### Documentation Issue

https://learn.microsoft.com/en-us/windows/wsl/setup/environment
The first bullet point says
"Enables the optional WSL and Virtual Machine Platform components"
This isn't true, I had to manually enable these in the 'Turn Windows Features on or off' or I ran into an error when it was installing Ubuntu.

Resolving Error: 0x80370114 The operation could not be started because a required feature is not installed.
This is resolved by enabling in the 'Turn Windows Features on or off' and enabling both  'Virtual Machine Platform' and 'Windows Subsystem for Linux' per https://learn.microsoft.com/en-us/answers/questions/1187339/resolving-error-0x80370114-the-operation-could-not.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/setup/environment

### Suggested Improvements

Correct "Enables the optional WSL and Virtual Machine Platform components", so it says that before running this command you will need to enable these 2 features in 
'Turn Windows Features on or off' and enabling both  'Virtual Machine Platform' and 'Windows Subsystem for Linux'

**Comment by mattwojo** [comment]
Hmm.. thanks for filing this issue @JAffleck. The install command should enable those Windows features for you.  Are you running Windows 10 version 2004 and higher (Build 19041 and higher) or Windows 11? 
I'll ask around to see whether anyone is familiar with this issue happening for others, but the docs are correct. This must connect to another issue.
