### ISSUE TITLE
wsl hostname -i or -I

### ISSUE THREAD

**Issue by byroniac** [MicrosoftDocs/WSL#1834]
### Documentation Issue

It says "hostname -i" here but should it be "hostname -I" instead? The example seems to be correct. But the paragraph mentions "hostname -i" which is different, and I think this is incorrect?

### Link to documentation page

[Accessing a WSL 2 distribution from your local area network (LAN)](https://learn.microsoft.com/en-us/windows/wsl/networking#accessing-a-wsl-2-distribution-from-your-local-area-network-lan)

**Comment by akshat157** [comment]
Just noticed this issue myself and found https://github.com/MicrosoftDocs/WSL/issues/1818 which seems to be related, as well as confirms that `wsl hostname -i` (lowercase "i") is incorrect while `wsl hostname -I` (uppercase "i") is correct.

The docs need correction.

**Comment by mattwojo** [comment]
Thanks for pointing out this issue @byroniac and @akshat157! Fixed in https://github.com/MicrosoftDocs/WSL/pull/1848
