### ISSUE TITLE
some word choices in wsl configuration page causes big misundertanding

### ISSUE THREAD

**Issue by yilmazdurmaz** [MicrosoftDocs/WSL#1835]
### Documentation Issue

There are two files to store configurations, and all seems well understood at first until users start to see "wsl: Unknown key" errors or other issues directly related to this misunderstanding. (I had that too)

At the very top we got this:

> [.wslconfig](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig) to configure settings globally across all installed distributions running on WSL 2.
> [wsl.conf](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconf) to configure settings per-distribution for Linux distros running on WSL 1 or WSL 2.

the use of words directly imprints the image "so, I can set things globally instead of troubling myself editing each copy I installed". And then this newly built wrong impression is enhanced with the links above and with paragraphs on each main entry points having the "global/local" wording.

I have seen many issues opened over the years. I too fell into this trap because of these word choices and got these errors recently:
wsl: Unknown key 'boot.systemd' in C:\Users\durmaz\.wslconfig:7
wsl: Unknown key 'user.default' in C:\Users\durmaz\.wslconfig:10

I checked other issues with this same occurence, and saw these two statements:
> .wslconfig is not a globalization of wsl.conf.

and

> AFAIK, no options have been moved from .wslconfig to wsl.conf. The user.default settings was in wsl.conf since its addition.

getting back to this documentation page, now I can tell it is the choice of words and the links are the silent culprits here.
- "configure settings globally and locally" has the meaning of having the same options for both files
- there is no way to discriminate them unless one carefully reads the whole page for options in both files
- the two links on the page get you back to the statements at the top instead of their respective sections, thus they boost the wrong impression that they are the same

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/wsl-config

### Suggested Improvements

1. the two links must point to the actual sections where settings options are explained in detail
  - https://learn.microsoft.com/en-us/windows/wsl/wsl-config#configuration-settings-for-wslconf
  - https://learn.microsoft.com/en-us/windows/wsl/wsl-config#configuration-setting-for-wslconfig

2. "to configure settings globally/locally" parts (they are repeated in many places) should be replaced by cleaner ones to distinguish the difference. These two simple edits just by reordering of the words change the meaning dramatically.
- "to configure global settings"
- "to configure local settings"

3. in addition, somewhere at the top (and on occasional places) there must be a clean warning with a meaning "options that can be used in these files are (almost?) all different, do not confuse".

**Comment by mattwojo** [comment]
Thanks for raising this issue @yilmazdurmaz. I've reorganized the page a bit and updated some of the wording in https://github.com/MicrosoftDocs/WSL/pull/1848

**Comment by yilmazdurmaz** [comment]
@mattwojo I see you have changed a lot and it looks great. Thanks for the nice work.

Small bits are inevitable to miss, though, when you have a lot to do. There is one more of "configure settings globally" at line 188 of current document. Not that urgent compared to what you have already done, but you may want to have a look while you are still hot on it.

Thanks again.
