### ISSUE TITLE
my f ki/ng  ram

### ISSUE THREAD

**Issue by Naiml007** [MicrosoftDocs/WSL#1837]
### Documentation Issue

5000mb + ram i want to set my wsl ram limit to 3gb
![image](https://github.com/MicrosoftDocs/WSL/assets/90306726/5ef10f6d-5d39-4526-a7a4-d21256c1d928)

### Link to documentation page

null

### Suggested Improvements

add ram config feature

**Comment by da-mask** [comment]
Did you try adding `memory=3GB` to your .wslconfig file? What have you tried?

**Comment by craigloewen-msft** [comment]
Please try this as well: https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/#automatic-memory-reclaim
