### ISSUE TITLE
useWindowsDnsCache: Incorrect or confusing notes notes

### ISSUE THREAD

**Issue by ralish** [MicrosoftDocs/WSL#1840]
### Documentation Issue

The description for the `useWindowsDnsCache` setting states setting it to `true` will bypass the the Windows DNS cache, but this appears to be the opposite of what the setting does based on its name. Either the documentation is wrong, or additional details should be added to make it clear this is correct despite the misleading setting name.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/wsl-config?source=docs#experimental-configuration-settings

### Suggested Improvements

Verify the accuracy of the documentation for the `useWindowsDnsCache` setting and update as appropriate. It may be the default setting is also incorrect as a result and is in fact `true`.

**Comment by mattwojo** [comment]
Thanks for pointing this out @ralish. Fixed in https://github.com/MicrosoftDocs/WSL/pull/1838
