### ISSUE TITLE
initialAutoProxyTimeout: Specify the unit of measurement

### ISSUE THREAD

**Issue by ralish** [MicrosoftDocs/WSL#1841]
### Documentation Issue

The `initialAutoProxyTimeout` setting has a default value of `1000` but the unit isn't specified. I'm guessing it's milliseconds, making for a default timeout of 1 second, but this should be made explicit.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/wsl-config?source=docs#experimental-configuration-settings

### Suggested Improvements

Add the unit of measurement to the description of the setting and verify accuracy of the default setting.

**Comment by mattwojo** [comment]
Thanks @ralish -- Yes, milliseconds. Just made that explicit in the doc -- good call. https://github.com/MicrosoftDocs/WSL/commit/b33d59240eb349460da6e3744b2ab37ca0f72e11
