### ISSUE TITLE
experimental: Windows 11 requirements are unclear

### ISSUE THREAD

**Issue by ralish** [MicrosoftDocs/WSL#1842]
### Documentation Issue

Multiple documented settings in the `[experimental]` section indicate a Windows 11 requirement:

> Entries with an * after the value type are only available on Windows 11.
> Entries with an ** after the value type are only available on the [Windows Insiders Program](https://www.microsoft.com/windowsinsider/).

For the entries marked with a single asterisk, it's not clear if this means *any* release of Windows 11 since the original 21H2, or if there are requirements on a more recent release (e.g. at least 22H2).

For the entries marked with two asterisks, there's no build number referenced and so it's unclear what the minimum required Windows Insiders build is for support. It's possible that a pre-release build is no longer required as the [blog post](https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/) announcing the new settings references [Windows 11 Build 22621.2359](https://blogs.windows.com/windows-insider/2023/09/14/releasing-windows-11-build-22621-2359-to-the-release-preview-channel/) as the requirement.

The latest preview update for Windows 11 22H2 and 23H2 is a newer build and so participation may no longer be required:

- [Windows 11 22H2: October 31, 2023 — KB5031455 (OS Build 22621.2506) Preview](https://support.microsoft.com/en-us/topic/october-31-2023-kb5031455-os-builds-22621-2506-and-22631-2506-preview-6513c5ec-c5a2-4aaf-97f5-44c13d29e0d4)
- [Windows 11 23H2: October 31, 2023 — KB5031455 (OS Build 22631.2506) Preview](https://support.microsoft.com/en-us/topic/october-31-2023-kb5031455-os-builds-22621-2506-and-22631-2506-preview-6513c5ec-c5a2-4aaf-97f5-44c13d29e0d4)

### Link to documentation page

https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/

### Suggested Improvements

Verify and document the minimum required Windows 11 release/build for settings marked with one or two asterisk.

**Comment by mattwojo** [comment]
Thanks for posting this issue @ralish! Updated to represent these experimental features moving out of Windows Insiders and into the 22H2 release. > https://github.com/MicrosoftDocs/WSL/pull/1848
