### ISSUE TITLE
Install wsl error on Windows 10

### ISSUE THREAD

**Issue by dal-dataDS** [MicrosoftDocs/WSL#1843]
### Documentation Issue

I woulld like install wsl on windows 10 by typing wsl --install, the following command the following error is generated
wsl --install 'wsl' n'est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes

### Link to documentation page

wsl --install 'wsl' n'est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes

**Comment by mattwojo** [comment]
@dal-dataDS -- You must be running Windows 10 version 2004 or higher (Build 19041 and higher) or Windows 11 to use the the wsl --install command. If you are running an older version of Windows 10 and cannot update, you can follow the manual install instructions: https://learn.microsoft.com/windows/wsl/install-manual
