### ISSUE TITLE
`useWindowsDnsCache` documented behavior seems to be inverted

### ISSUE THREAD

**Issue by tedjp** [MicrosoftDocs/WSL#1844]
### Documentation Issue

The description of `useWindowsDnsCache` indicates that setting `useWindowsDnsCache = true` will bypass the cache for all requests, and `useWindowsDnsCache = false` will use the cache. I expect the behavior is the opposite: true: use cache; false: bypass cache.

> useWindowsDnsCache
> Default: false
> Only applicable when `experimental.dnsTunneling` is set to `true`. When this option is set to `True`, DNS requests tunneled from Linux will bypass cached names within Windows to always put the requests on the wire.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/wsl-config#experimental-settings

### Suggested Improvements

Consult implementation determine what the actual behavior is. Likely change the description to say that when set to true, tunneled DNS requests will use the Windows DNS cache.

**Comment by mattwojo** [comment]
Thanks for pointing this out @tedjp!
Fixed in https://github.com/MicrosoftDocs/WSL/pull/1838
