### ISSUE TITLE
Where is Linux installed?

### ISSUE THREAD

**Issue by stamminator** [MicrosoftDocs/WSL#186]
I have installed Ubuntu through the Windows Store, but there is nothing located at `%localappdata%\lxss\` on my machine/user. Where is it located?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install the Linux Subsystem on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mavaddat** [comment]
Try `%programfiles%\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1604.2017.922.0_x64__79rhkp1fndgsc`

**Comment by stamminator** [comment]
@mavaddat So that's where the application is installed, but what about the files I create in Linux?

![image](https://user-images.githubusercontent.com/10633170/38956237-056119ce-4325-11e8-8c87-8d6844e0d54b.png)

**Comment by pcounts** [comment]
%userprofile%\AppData\Local\Packages\SomeFolderDependingOnYourLinuxDistro

https://www.howtogeek.com/261383/how-to-access-your-ubuntu-bash-files-in-windows-and-your-windows-system-drive-in-bash/

**Comment by mavaddat** [comment]
For me, it was in 
`%userprofile%\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState`
![https://i.imgur.com/ZKDhddw.png](https://i.imgur.com/ZKDhddw.png)

**Comment by lqueryvg** [comment]
Perhaps Microsoft should provide an *easy* way to find these files from Windows ?

**Comment by DarthSpock** [comment]
They purposely don't because they don't want you manipulating Linux files with Windows until officially supported. That said, there is more ability in this arena with upcoming Spring Creator's Update due to new WSL features such as enabling `metadata -o` to extend Linux attributes to Windows. But until it's explicitly stated, modifying Linux files from Windows is unsupported.

**Comment by lqueryvg** [comment]
@DarthSpock, thanks that's useful info.

**Comment by bitcrazed** [comment]
BE WARNED: If you access/modify any of your Linux files using Windows apps/tools, you may well end up with corrupted files! Be sure to read this for more details: https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/

**Comment by craigloewen-msft** [comment]
Fixed in [Windows version 1903](https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-windows-10-version-1903/)!
