### ISSUE TITLE
Include pointers/work-around for brittleness in "usbipd wsl attach"

### ISSUE THREAD

**Issue by darrenhearn** [MicrosoftDocs/WSL#1864]
### Documentation Issue

The "[Attach a USB device](https://learn.microsoft.com/en-us/windows/wsl/connect-usb#attach-a-usb-device)" section of the "Connect USB devices" WSL How-to uses the Windows/PowerShell convenience command `usbipd wsl attach`. As outlined in the discussion of [usbipd-win issue #588](https://github.com/dorssel/usbipd-win/issues/588), there are at least a few ways the convenience command can be broken. Troubleshooting the issue requires digging into bug reports (which I personally wish I'd been able to avoid).

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/connect-usb

### Suggested Improvements

IMO, the possible improvement options (from minimal to "best") are:
1. Include a pointer to [usbipd-win issue #588](https://github.com/dorssel/usbipd-win/issues/588) for "WSL distribution cannot be reached via the WSL virtual switch" errors on the Troubleshooting page.
2. Include a pointer to the issue/error as a note box inline with step 2 of "Connect USB Devices" (i.e. the step with the `usbipd wsl attach` command).
3. Skip use of the `usbipd wsl attach` convenience command - break step 2 of "Connect USB Devices" into its two underlying parts (first `usbipd bind` in Windows/PowerShell and second `usbip attach` in WSL/bash).

**Edit:** It looks like the issues (and corresponding documentation updates) are already going to be addressed - see [usbipd-win discussion #774](https://github.com/dorssel/usbipd-win/discussions/774), particularly [the comment from benmcmorran](https://github.com/dorssel/usbipd-win/discussions/774#discussioncomment-7644104). Depending on the timeline for those changes (sounds like they're coming soon?) it may not be worth making the intermediate changes suggested here.

**Comment by mattwojo** [comment]
Thanks for filing @darrenhearn! This is being fixed in https://github.com/MicrosoftDocs/WSL/pull/1870.
