### ISSUE TITLE
documentation list installation commands which no longer work wsl2

### ISSUE THREAD

**Issue by freakedenough** [MicrosoftDocs/WSL#1865]
### Documentation Issue
https://learn.microsoft.com/en-us/windows/wsl/connect-usb

besitzer@MSI:~$ sudo apt install linux-tools-generic hwdata
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  linux-tools-5.15.0-71 linux-tools-5.15.0-71-generic linux-tools-common
The following NEW packages will be installed:
  hwdata linux-tools-5.15.0-71 linux-tools-5.15.0-71-generic linux-tools-common linux-tools-generic
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 8268 kB of archives.
After this operation, 28.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 hwdata all 0.357-1 [26.6 kB]
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 linux-tools-common all 5.15.0-71.78
Ign:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 linux-tools-5.15.0-71 amd64 5.15.0-71.78
Ign:4 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 linux-tools-5.15.0-71-generic amd64 5.15.0-71.78
Ign:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 linux-tools-generic amd64 5.15.0.71.69
Err:2 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 linux-tools-common all 5.15.0-71.78
  404  Not Found [IP: 185.125.190.39 80]
Err:3 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 linux-tools-5.15.0-71 amd64 5.15.0-71.78
  404  Not Found [IP: 185.125.190.39 80]
Err:4 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 linux-tools-5.15.0-71-generic amd64 5.15.0-71.78
  404  Not Found [IP: 185.125.190.39 80]
Err:5 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 linux-tools-generic amd64 5.15.0.71.69
  404  Not Found [IP: 185.125.190.39 80]
Fetched 26.6 kB in 1s (31.3 kB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-tools-common_5.15.0-71.78_all.deb  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-tools-5.15.0-71_5.15.0-71.78_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-tools-5.15.0-71-generic_5.15.0-71.78_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux-meta/linux-tools-generic_5.15.0.71.69_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by mattwojo** [comment]
Thanks for filing this @freakedenough. This issue is being fixed in https://github.com/MicrosoftDocs/WSL/pull/1870.
