### ISSUE TITLE
Skip-Ahead 17650

### ISSUE THREAD

**Issue by WSLUser** [MicrosoftDocs/WSL#187]
Can you list what's new for Skip-Ahead 17650?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2faa612c-2d90-b3c4-0f01-e5d23c42bc04
* Version Independent ID: 3ed15eb4-f9d4-ae63-c0e6-354674e301b2
* Content: [Release Notes](https://docs.microsoft.com/en-us/windows/wsl/release-notes#feedback)
* Content Source: [WSL/release-notes.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md)
* Service: **windows-subsystem-for-linux**
* GitHub Login: @benhillis

**Comment by Brian-Perkins** [comment]
Unfortunately we have not had any changes included in the Insider build recently. There are some changes queued, but unfortunately the git branch structure we are in sometimes means our changes get delayed for reasons beyond our control. We don't merge directly into the Insider Build branch, but rather go through various staging branches until we finally get to the Insider Build. At a couple of different levels of this hierarchy there have been recent issues that have slowed merges way down. This should all be resolved shortly, but even when operating normally it takes a few days to move a change from our branch to the Insider Build branch. I would be surprised if the build next week didn't have WSL changes included. Unlikely to be any changes this week, but we will be sure to include release notes whenever appropriate.

**Comment by Biswa96** [comment]
There are some changes I've observed. But I'm not sure about that.
1. LxssManager.dll gets a third resource in RCDATA which is a GZIP/CPIO compressed `init`.
2. LxssManagerProxyStub.dll has 14th object/method in COM vtable.
3. WslRegisterDistribution() may requires admin privileges.
4. Init gets bigger ~94KB.
5. Bash.exe may work without `/etc/passwd`.

**Comment by DarthSpock** [comment]
There were a couple fixes for 17674 but aren't identified on the Release Notes. I doubt there's anything else to report but if there is, an update would be nice.

**Comment by DarthSpock** [comment]
Anything new for 17677?

**Comment by sunilmut** [comment]
@DarthSpock - Release notes posted for [17677](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17677)
