### ISSUE TITLE
The latest version of usbipd(v4) has change its command line interface

### ISSUE THREAD

**Issue by zjhken** [MicrosoftDocs/WSL#1878]
### Documentation Issue

`usbipd wsl list` should change to `usbipd list`
and before attach to wsl, should bind the device first, run `usbipd bind -b <BUSID>` in admin mode.
and the attach command changed as well, the new one is `usbipd attach -w --busid <BUSID>`

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/connect-usb

### Suggested Improvements

`usbipd wsl list` should change to `usbipd list`
and before attach to wsl, should bind the device first, run `usbipd bind -b <BUSID>` in admin mode.
and the attach command changed as well, the new one is `usbipd attach -w --busid <BUSID>`

**Comment by mattwojo** [comment]
Thanks for filing. Resolved in https://github.com/MicrosoftDocs/WSL/pull/1870
