### ISSUE TITLE
I want to use WSL1, but the information is well hidden

### ISSUE THREAD

**Issue by ThirtyNineWinks** [MicrosoftDocs/WSL#1888]
### Documentation Issue

No errors, but it only tells you how to upgrade from WSL1 to WSL2, but I HATE WSL2. It's slow. It freezes up. It hogs resources. I want to get WSL1. How can I do that???

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/compare-versions

### Suggested Improvements

Tell how to get WSL1 and not get the crummy WSL2.

**Comment by CybCom** [comment]
Duplicate with #1889
