### ISSUE TITLE
I want WSL1. How do I get it?

### ISSUE THREAD

**Issue by ThirtyNineWinks** [MicrosoftDocs/WSL#1889]
### Documentation Issue

The title is "Manual installation steps for older versions of WSL" It tells me how to install WSL2. I HATE WSL2, I WANT WSL1. HOW CAN I GET IT?  You admit that the shared file IO is unusable in WSL2 because it is so slow, but I need that. So how can I get the "older version" and get WSL1?

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install-manual

### Suggested Improvements

Tell how to get WSL1, because it can be used.

**Comment by CybCom** [comment]
Maybe there are these words on exactly the page you quoted. 

> We recommend now moving on to step #2, updating to WSL 2, but if you wish to only install WSL 1, you can now restart your machine and move on to [Step 6 - Install your Linux distribution of choice](https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-6---install-your-linux-distribution-of-choice). To update to WSL 2, wait to restart your machine and move on to the next step.

Doesn't it works?

**Comment by ThirtyNineWinks** [comment]
The text is there, but it is unclear. I already have WSL2. I needed to change FROM WSL2 back to WSL1. Telling me that when I Install WSL I can stop at the stage where I only have WSL1 didn't seem to address my issue.

**Comment by mattwojo** [comment]
https://learn.microsoft.com/en-us/windows/wsl/basic-commands#set-wsl-version-to-1-or-2
