### ISSUE TITLE
wsl subcommand has been removed.

### ISSUE THREAD

**Issue by nethomas1968** [MicrosoftDocs/WSL#1891]
### Documentation Issue

I came to this site because usbipd PowerShell command told me that the "wsl" subcommand has been removed. Go to this site to learn the new syntax - and what do I see - instructions still using the "wsl" subcommand.
Looks like the docs need updating.

### Link to documentation page

It's still using the "wsl" subcommand - which is no longer present.

### Suggested Improvements

Update the docs.

**Comment by mattwojo** [comment]
The update is in a PR, but the product manager assigned to review has been out of office. This was a recent change, but should be live within the next day or two.
