### ISSUE TITLE
Documentation not updated for usbipd-win 4.0.0

### ISSUE THREAD

**Issue by lucasholzen** [MicrosoftDocs/WSL#1892]
### Documentation Issue

Need to update the code examples for usbipd-win 4.0.0 as the syntax has changed.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/connect-usb

### Suggested Improvements

1. `usbipd wsl list` should now be `usbipd list`
2. `usbipd wsl attach --busid <busid>` should now be `usbipd attach --wsl --busid <busid`

I didn't test 3. and 4.

**Comment by craigloewen-msft** [comment]
This has now been updated. Thank you for filing this!
