### ISSUE TITLE
Documentation incorrect for usbipd 4.0.0

### ISSUE THREAD

**Issue by Alpvax** [MicrosoftDocs/WSL#1898]
### Documentation Issue

Running the specified command (`usbipd wsl list`) results in the error: `usbipd: error: The 'wsl' subcommand has been removed. Learn about the new syntax at https://learn.microsoft.com/windows/wsl/connect-usb#attach-a-usb-device.`
Following the specified link sends you to the page telling you to use the failed command.

### Link to documentation page

https://learn.microsoft.com/windows/wsl/connect-usb#attach-a-usb-device.

### Suggested Improvements

Fix or clarify the documentation on the page

**Comment by craigloewen-msft** [comment]
The docs are now updated. Thank you for filing this!
