### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by brunofranx** [MicrosoftDocs/WSL#1899]
### Documentation Issue

PS C:\Users\bruno> wsl --update
Verifica della disponibilità di aggiornamenti.
Aggiornamento sottosistema Windows per Linux alla versione: 2.0.14.
Aggiornamento fallito (codice di uscita: 1603).
File di log: C:\Users\bruno\AppData\Local\Temp\wsl-install-logs.txt
Error code: Wsl/UpdatePackage/E_ABORT

### Link to documentation page

PS C:\Users\bruno> wsl --update
Verifica della disponibilità di aggiornamenti.
Aggiornamento sottosistema Windows per Linux alla versione: 2.0.14.
Aggiornamento fallito (codice di uscita: 1603).
File di log: C:\Users\bruno\AppData\Local\Temp\wsl-install-logs.txt
Error code: Wsl/UpdatePackage/E_ABORT

### Suggested Improvements

PS C:\Users\bruno> wsl --update
Verifica della disponibilità di aggiornamenti.
Aggiornamento sottosistema Windows per Linux alla versione: 2.0.14.
Aggiornamento fallito (codice di uscita: 1603).
File di log: C:\Users\bruno\AppData\Local\Temp\wsl-install-logs.txt
Error code: Wsl/UpdatePackage/E_ABORT

**Comment by craigloewen-msft** [comment]
This looks like a technical issue, if you're still seeing this issue please file it at github.com/microsoft/wsl where we answer technical problems. This repo is just for the docs page. Thank you!
