### ISSUE TITLE
The 'Advanced settings configuration'

### ISSUE THREAD

**Issue by dbrowneihg** [MicrosoftDocs/WSL#1900]
### Documentation Issue

The 'Advanced settings configuration' documentation page incorrectly lists support for GUI applications (WSLg) as being Win11 only. However, the WSLg git page indicates Win10 is supported.

https://github.com/microsoft/wslg?tab=readme-ov-file#pre-requisites
"WSLg is supported on both Windows 11 and Windows 10. Windows 10 users must ensure their Windows 10 installation is fully up to date by visiting Windows Update and installing all available updates."

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/wsl-config#main-wsl-settings

![image](https://github.com/MicrosoftDocs/WSL/assets/134965122/be8f38f5-9e07-4710-9675-49fe38b5154d)

### Suggested Improvements

Remove the ' * ' and 'Only available for Windows 11.' note from this section of the documentation.

**Comment by craigloewen-msft** [comment]
Fixed here! Thank you
https://github.com/MicrosoftDocs/WSL/pull/1949
