### ISSUE TITLE
"Attach a USB device" guide out of date

### ISSUE THREAD

**Issue by Emoun** [MicrosoftDocs/WSL#1903]
### Documentation Issue

The guide for attaching USB devices is out of date with the `usbipd` binary.

Running the first command to list devices returns the error: `usbipd: error: The 'wsl' subcommand has been removed. Learn about the new syntax at https://learn.microsoft.com/windows/wsl/connect-usb#attach-a-usb-device.`

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/connect-usb#attach-a-usb-device

### Suggested Improvements

The fix as far as I can tell is to just remove `wsl`

**Comment by JS3910** [comment]
Just came here to report this... Very useful to have a link explicitly to the "new syntax" but the page in question has absolutely nothing about it 😒.

**Comment by craigloewen-msft** [comment]
Now updated, thank you for the feedback!
