### ISSUE TITLE
Attach a USB Device Instructions are outdated and do not work

### ISSUE THREAD

**Issue by mt-xing** [MicrosoftDocs/WSL#1904]
### Documentation Issue

The documentation says to run `usbipd wsl list` in an admin Powershell window.
![image](https://github.com/MicrosoftDocs/WSL/assets/6147405/b4484604-ff15-4cff-8118-361bd5f2d0a0)

However, running that command spits out an error that the command has been removed, and then links right back to the same page on which that command was listed:
![image](https://github.com/MicrosoftDocs/WSL/assets/6147405/ae707e75-8906-439b-9e7e-95b940eb4110)

### Link to documentation page

https://learn.microsoft.com/windows/wsl/connect-usb#attach-a-usb-device

**Comment by craigloewen-msft** [comment]
Now updated, thank you for the feedback!
