### ISSUE TITLE
Read-only file system unable to fix.

### ISSUE THREAD

**Issue by viswacareer1** [MicrosoftDocs/WSL#1905]
### Documentation Issue

My Ubuntu distribution has ran into read only file system state, so to resolved the issue I have followed the steps provided  at https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-repair-a-vhd-mounting-error.

while performing the activity, I am getting the following error message while running .
```
wsl.exe sudo e2fsck -f /dev/sdd
```
Error Message: 

**e2fsck 1.46.5 (30-Dec-2021)
/dev/sdd is mounted.
e2fsck: Cannot continue, aborting.**

**Please refer the below images for more details:**

![image](https://github.com/MicrosoftDocs/WSL/assets/78254506/8aedacc1-9244-49dd-a745-228525198251)

![image](https://github.com/MicrosoftDocs/WSL/assets/78254506/c7eed1f6-d36c-47c4-b64f-7c1f6b7e724f)

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-repair-a-vhd-mounting-error

**Comment by craigloewen-msft** [comment]
You need to mount another distro to interact with that VHD. I recommend using `wsl --install Debian` to quickly install Debian and then that will allow you to interact with it. 

Thanks!

For all further technical problems: This looks like a technical issue, if you're still seeing this issue please file it at github.com/microsoft/wsl where we answer technical problems. This repo is just for the docs page. Thank you!
