### ISSUE TITLE
Need clarification on filesystems supported by WSL

### ISSUE THREAD

**Issue by xantari** [MicrosoftDocs/WSL#1906]
### Documentation Issue

This statement needs more info: Only filesystems that are natively supported in the kernel can be mounted by wsl --mount

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk

### Suggested Improvements

How do you know what the kernel supports?

Is there a link to which file systems the kernel supports?

**Comment by Biswa96** [comment]
> How do you know what the kernel supports?

This is a typical command to find supported filesystems in Linux: `cat /proc/filesystems`

**Comment by xantari** [comment]
Thanks @Biswa96 !
