### ISSUE TITLE
Will this be updated for newer version of Ubuntu (18.04)?

### ISSUE THREAD

**Issue by klauern** [MicrosoftDocs/WSL#191]
I am trying to run this on my laptop, as our corporate policy blocks access to the Windows Store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install the Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server#feedback)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-on-server.md)
* Service: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by DarthSpock** [comment]
Not at this time. See https://github.com/Microsoft/WSL/issues/2874 as that will be where it should be noted it's available.  WSL currently can't support much of 18.04 due to many changes in how it operates compared to 16.04. See their release notes, listed on at the WSL issue linked above. You'll find the appx in the Docs is also not up to date and is up to Canonical to publish a new appx. Recommend Tweeting them.

**Comment by AlastairBateman** [comment]
Alternatively you can run:
```
sudo do-release-upgrade -d
```
And it seems to run fine. At least on a couple of machines I've attempted it on.

**Comment by webprofusion-chrisc** [comment]
Hi, our access to the the store app is also blocked, that seems like it would be a pretty common situation for enterprise IT. It also seems pretty common that developers will be in enterprise organisations,  Please problem an alternative fallback to update the distribution. 

Currently can only fallback to lxrun, and that complains about being legacy.

It doesn't matter if it involves a command you can only run as admin.

**Comment by Fake4d** [comment]
I would love to see the new "offline"-download links as well. 
I tried https://aka.ms/wsl-ubuntu-1804 instead of https://aka.ms/wsl-ubuntu-1604 but it is not set up to now.
Maybe you can officially release the appx files. 

I just have a linux internet pc.. It is not possible for me to get the internal lab windows machines to the internet.

**Comment by ky0ncheng** [comment]
https://mega.nz/#!pspkiZ6T!uH-cv4BCX2X0DIFnu8FDgMqTqaXEai0ZmhAQmobkjv8

M$ so lazy.

**Comment by Woznet** [comment]
Thanks for the mega link, that worked great for me.
I did run into one difficulty, how do I rerun the installation after moving the directory to another location?

**Comment by thedonquixotic** [comment]
Hey is it possible to install Ubuntu 18.04 from powershell using get-appx add-appx commands? I'm not entirely clear on the available ways of installing it through scripting.

**Comment by timothies** [comment]
The instructions don't work on Windows 2019.  

PS C:\> Expand-Archive ~/Ubuntu.appx ~/Ubuntu
Expand-Archive : .appx is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:1
+ Expand-Archive ~/Ubuntu.appx ~/Ubuntu
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (.appx:String) [Expand-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive

**Comment by kiazhi** [comment]
Yes, @timothies.

in fact,`Expand-Archive` is meant for compressed file or `.zip` file extension. You can use `Rename-Item` to rename the `.appx` file. For more information refer to [this](https://kiazhi.github.io/blog/Getting-Ubuntu-distro-environment-on-Windows-for-DevOps/#installation-for-windows-server).

**Comment by tara-raj** [comment]
Link updated for Ubunut 18.04 in our documentation here - https://docs.microsoft.com/en-us/windows/wsl/install-manual

**Comment by DarthSpock** [comment]
@tara-raj Great update! I like how you also accounted for the new curl as well. Just need the Kali appx to be put into the document and we'd have the full suite available.
