### ISSUE TITLE
Old usbipd syntax

### ISSUE THREAD

**Issue by tom-mohr** [MicrosoftDocs/WSL#1911]
### Documentation Issue

Command should be `usbipd list` instead of `usbipd wsl list`.

### Link to documentation page

[https://learn.microsoft.com/en-us/windows/wsl/connect-usb#attach-a-usb-device](https://learn.microsoft.com/en-us/windows/wsl/connect-usb#attach-a-usb-device)

**Comment by craigloewen-msft** [comment]
This is updated now. Thank you!
