### ISSUE TITLE
Update usbipd command

### ISSUE THREAD

**Issue by witodev** [MicrosoftDocs/WSL#1912]
### Documentation Issue

Powershell commands for usbipd refers to old version, eg:
`usbipd wsl list`
now should be:
`usbipd list`

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/connect-usb

### Suggested Improvements

`usbipd wsl list` => `usbipd list `
`usbipd wsl attach --busid <busid>` => `usbipd attach -w --busid <busid>`
`usbipd wsl detach --busid <busid>` => `usbipd detach -w --busid <busid>`

**Comment by craigloewen-msft** [comment]
This is updated now, thank you for filing!
