### ISSUE TITLE
Connect USB devices commands are wrong

### ISSUE THREAD

**Issue by stevebroshar** [MicrosoftDocs/WSL#1916]
### Documentation Issue

several if not all of the commands are wrong. the list command does not understand 'wsl' arg; not needed. the attach command requires --wsl switch. and so on

### Link to documentation page

[what? I did above. and what does 'list out' mean? This page needs an editor.]

### Suggested Improvements

fix commands

**Comment by craigloewen-msft** [comment]
This is now updated, thank you for filing!
