### ISSUE TITLE
WSL and usbipd-win documentation out of date for latest usbipd-win version

### ISSUE THREAD

**Issue by colinvm** [MicrosoftDocs/WSL#1918]
### Documentation Issue

The instructions for using `usbipd-win` to connect USB devices to WSL ([here](https://learn.microsoft.com/en-us/windows/wsl/connect-usb)) are out of date for the newest release of `usbipd-win 4.0.0` ([here](https://github.com/dorssel/usbipd-win)).

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/connect-usb

### Suggested Improvements

Update documentation to reflect changes in `usbipd-win-4.0.0` 
Breaking changes made to `usbipd-win 4.0.0` can be seen [here](https://github.com/dorssel/usbipd-win?tab=readme-ov-file#wsl-2).

**Comment by craigloewen-msft** [comment]
This is now updated! Thank you for filing.
