### ISSUE TITLE
Indicate required Linux kernel version for USBIPD

### ISSUE THREAD

**Issue by Lotharyx** [MicrosoftDocs/WSL#1922]
### Type of issue

Missing information

### Feedback

The page indicates how to check Linux kernel version with the `uname` command, but does not list what kernel version is required to support USBIP.  In my case, all attempts to attach are met with 'WSL kernel is not USBIP capable' even though I've updated.  Knowing what kernel version is required would be helpful in troubleshooting this.

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/connect-usb

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/connect-usb.md

### Author

@craigloewen-msft

### Document Id

e99de78d-d27a-664d-98ba-91116b7157c8

**Comment by craigloewen-msft** [comment]
This looks like a technical issue, if you're still seeing this issue please file it at github.com/microsoft/wsl where we answer technical problems. This repo is just for the docs page. Thank you!

We've updated this in recent times to help fix this Linux kernel issue as well.
