### ISSUE TITLE
Can I install GUI-desktop in Linux subsystem?

### ISSUE THREAD

**Issue by aoxiangwu** [MicrosoftDocs/WSL#193]
I want to install LXDE in my Debian subsystem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install the Linux Subsystem on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by bitcrazed** [comment]
WSL doesn't officially support running X/GUI apps. However, many people enjoy running various Linux desktops/apps on WSL via one of the several available Windows XServers.

**Comment by PTrenholme** [comment]
Look at the Kali site. They show how to install and run an X-window system as a remote desktop connected through localhost. (With a video of it working.) I haven't (yet) tried it, but it seem an approach that should work.

**Comment by volehuy1998** [comment]
Download and Install Xming. Then type "export DISPLAY=:0" on Linux and start your GUI soft each time you use GUI soft.

**Comment by aspadistra** [comment]
It is not over until it is over, trying the Xming trick but so far having to do this ...

8964@DESKTOP~$ sudo cinnamon
Cinnamon warning: Software rendering detected: llvmpipe (LLVM 6.0, 256 bits)
Failed to connect to session bus: Failed to execute child process “dbus-launch” (No such file or directory)hack8964@DESKTOP-HDIVCI5:~$

8964@DESKTOP~$
8964@DESKTOP~$ dbus-launch

Command 'dbus-launch' not found, but can be installed with:

sudo apt install dbus-x11

hack8964@DESKTOP-HDIVCI5:~$ sudo apt install dbus-x11
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  dbus-x11
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.

**Comment by mscraigloewen** [comment]
Lots of advice on how to get GUI working in WSL, so I'll mark this issue as closed. Thanks!
