### ISSUE TITLE
thiago

### ISSUE THREAD

**Issue by thiagofontora** [MicrosoftDocs/WSL#1938]
### Type of issue

Typo

### Feedback

lo vi por yutube

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/about

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/about.md

### Author

@craigloewen-msft

### Document Id

f583bc11-fe60-bb2c-af2b-dc0dae9fe81f

**Comment by krishnacx** [comment]
Can you point the typo being referred here ?
