### ISSUE TITLE
“Microsoft 内置内核提供的收件箱” 翻译是否不妥？

### ISSUE THREAD

**Issue by PelerYuan** [MicrosoftDocs/WSL#1940]
### Type of issue

Typo

### Feedback

![image](https://github.com/MicrosoftDocs/WSL/assets/163710604/9496a54b-4af4-4e25-8eab-98a5b71d68b9)
![image](https://github.com/MicrosoftDocs/WSL/assets/163710604/9db6137f-bedd-4f9d-9748-4f3d10d14d57)

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/wsl-config

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/wsl-config.md

### Author

@craigloewen-msft

### Document Id

9f406c77-415c-80db-d596-0a7fa4ea2ba9

**Comment by craigloewen-msft** [comment]
Hi sorry I don't read this language and am unsure what the feedback is here. I'll close this, if you file again please file in English (Or in plain text and not using an image) so I can understand and triage your feedback. Thank you!
