### ISSUE TITLE
WSD doesn't work

### ISSUE THREAD

**Issue by AlexGudman** [MicrosoftDocs/WSL#1944]
### Type of issue

Other (describe below)

### Feedback

I've spent a lot of time in search of problems, messing with files, doing something, I even updated Windows to version 11 and still nothing, the same problem: "There is no access to this file from the system"

PS C:\Users\User> wsl
Доступ к этому файлу из системы отсутствует.
PS C:\Users\User> wsl.exe
Доступ к этому файлу из системы отсутствует.
PS C:\Users\User>

### Page URL

https://learn.microsoft.com/ru-ru/windows/wsl/install

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md

### Author

@craigloewen-msft

### Document Id

7ed8fb81-5b8f-4d56-7b89-bf600ce6080a

**Comment by AntonAndreevichMoroz** [comment]
I also get this error. Previously everything worked and I used wsl. After some time, I returned to use and began to show the error “This file cannot be accessed from the system.” I tried reinstalling the component, but that didn't help. Is there a solution?

**Comment by craigloewen-msft** [comment]
This looks like a technical issue, if you're still seeing this issue please file it at github.com/microsoft/wsl where we answer technical problems. This repo is just for the docs page. Thank you!
