### ISSUE TITLE
Mounting an unpartitioned disk: wording/explaining the situation

### ISSUE THREAD

**Issue by crackwitz** [MicrosoftDocs/WSL#1945]
### Type of issue

Other (describe below)

### Feedback

It took me writing this issue to figure out what you're trying to show. The "unpartitioned" confused me.

The disk is "unpartitioned" in the sense that the file system spans the entire disk, without any partitioning to frame the file system. The example does *not* show a disk that is *empty* ("unpartitioned").

I'd appreciate pointing out that this example is supposed to show a disk without partitioning, but with a file system. I think the typical example of that is USB drives and memory cards.

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/wsl2-mount-disk.md

### Author

@craigloewen-msft

### Document Id

a9d73ca3-7026-5b5a-f3fe-3511e976cde4

**Comment by craigloewen-msft** [comment]
For disks, the concept of partitioning versus 'empty' can be a bit confusing. Our best approach is saying 'unpartitioned' to indicate that a disk has no partitions inside of it. I believe the wording is as clear as can be for this, if you have a specific suggestion on how you'd like to improve it please open a PR and I can review it. Thank you for filing feedback!
