### ISSUE TITLE
WSL中pytorch不能识别电脑上全部4张GPU

### ISSUE THREAD

**Issue by HELLONVIDIA** [MicrosoftDocs/WSL#1947]
### Type of issue

Other (describe below)

### Feedback

WSL下的Ubuntu中运行torch.cuda.is_available()报错；我电脑上有4张显卡，假如用CUDA_VISIBLE_DEVICES=##命令来指定任意三个显卡对pytorch可见，运行torch.cuda.is_available()就不报错，一旦启用全部四个显卡，就报错；该硬件在实体机Ubuntu上可正常运行

### Page URL

https://learn.microsoft.com/zh-cn/windows/wsl/install-manual

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install-manual.md

### Author

@craigloewen-msft

### Document Id

3fd655c2-9bb3-67d7-c369-545f38f805d8

**Comment by craigloewen-msft** [comment]
This looks like a technical issue, if you're still seeing this issue please file it at github.com/microsoft/wsl where we answer technical problems. This repo is just for the docs page. Thank you!
