### ISSUE TITLE
Can't Enable WSL

### ISSUE THREAD

**Issue by Arthasasyan** [MicrosoftDocs/WSL#195]
When trying to enable WSL via PowerShell. It can't reed data from the register. However, I still can use Disable- and Get- functions. Turning WSL on with Control Panel doesn't help too.
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install the Linux Subsystem on Windows 10](https://docs.microsoft.com/ru-ru/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by Jezuke** [comment]
You have to run the PowerShell as an administrator. Right-click on PowerShell and run it as admin.

**Comment by bboy12s** [comment]
I have a similar problem even when I run Powershell as admin

**Comment by polushindenis** [comment]
i have the simillar problem
 Имя компонента "Microsoft-Windows-Subsystem-Linux" неизвестно.

**Comment by polushindenis** [comment]
Error Message : "Component Name Microsoft-Windows-Subsystem-Linux" unknown".
What am I doing wrong?

**Comment by mscraigloewen** [comment]
Please make sure you're running PowerShell as an administrator. 

For any WSL specific issues please file them at [the WSL repo](https://github.com/microsoft/wsl). This repo is only for issues with the documentation. Thanks!
