### ISSUE TITLE
Manual installation links for Ubuntu 24.04 needs to be available

### ISSUE THREAD

**Issue by kms0219kms** [MicrosoftDocs/WSL#1952]
### Documentation Issue

Ubuntu 24.04 has been released. Therefore, Manual installation links for Ubuntu 24.04 needs to be available, i.e) https://aka.ms/wslubuntu2404.
Also, https://aka.ms/wslubuntu also needs to be updated to Ubuntu 24.04's link.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install-manual?source=docs#downloading-distributions

**Comment by kms0219kms** [comment]
https://github.com/microsoft/WSL/blob/master/distributions/DistributionInfo.json#L64

**Comment by craigloewen-msft** [comment]
Added a PR for this!
https://github.com/MicrosoftDocs/WSL/pull/1981

**Comment by mattwojo** [comment]
Merged: https://github.com/MicrosoftDocs/WSL/pull/1982
