### ISSUE TITLE
One ambiguous point about Chinese translation

### ISSUE THREAD

**Issue by Skiye** [MicrosoftDocs/WSL#1953]
### Type of issue

Other (describe below)

### Feedback

I'm searching a way to run one Debian code on my Windows11 system and find WSL which I just know for the first time. It seems nice. But there's a small question when I'm reading this document. Factually I'm viewing the Chinese language page and I find that the translation of "the Windows Subsystem for Linux" to Chinese seems to appear in an ambiguous way. We can see that WSL is running an  Linux environment on the Windows machine without any separate virtual machine. In another word, Windows system is base, and Liunx environment is its subpart(or may say second floor?). However, the translation "适用于 Linux 的 Windows 子系统" means opposite, specially, one Windows environment on Linux mechine. In Chinese grammar we usually get this meaning from these words which seems questionable. Maybe a translation like "适用于 Windows 系统的 Linux 子系统环境" can be better.
I'm a normal college student and I'm unsure if I was totally correct. Maybe you can collect other Chinese staff's opinions or consult professional language experts to get a proper conclusion.
Salute to you everyone and your work. Thank you so much.

### Page URL

https://learn.microsoft.com/zh-cn/windows/wsl/about

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/about.md

### Author

@craigloewen-msft

### Document Id

f583bc11-fe60-bb2c-af2b-dc0dae9fe81f

**Comment by mattwojo** [comment]
@Skiye - Thank you for filing this issue. Unfortunately, we are currently at the mercy of machine translation, so many of the language subtleties like this are unfortunately lost and we don't currently have the resources for human translation. :(
