### ISSUE TITLE
 Wsl/InstallDistro/E_UNEXPECTED

### ISSUE THREAD

**Issue by vinezhang** [MicrosoftDocs/WSL#1960]
### Type of issue

Typo

### Feedback

${user}/AppData\Local\Packages was remove by manual.when i run wsl ,it printed out below message:
AppData\Local\Packages\CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc\LocalState\ext4.vhdx”附加到 WSL2： 系统找不到指定的路径。
Error code: Wsl/Service/CreateInstance/MountVhd/HCS/ERROR_PATH_NOT_FOUND

 then ,  i unregister it by wslconfig ,and executed "wsl --unmount" command. but when i run "wsl --install  Ubuntu-22.04" it still printed out an another Error:Error code: Wsl/InstallDistro/E_UNEXPECTED
How to fix it?

### Page URL

https://learn.microsoft.com/zh-cn/windows/wsl/disk-space

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/disk-space.md

### Author

@craigloewen-msft

### Document Id

73eaaa84-4649-3c39-6116-1c62b713a4c3

**Comment by craigloewen-msft** [comment]
Please file this is a technical issue on the Microsoft/WSL repo!
https://github.com/microsoft/WSL/issues/new?template=Bug_Report.yaml

Thank you!
