### ISSUE TITLE
WslRegisterDistribution failed with error: 0x8007273f

### ISSUE THREAD

**Issue by kadsoc** [MicrosoftDocs/WSL#1961]
### Type of issue

Typo

### Feedback

WslRegisterDistribution failed with error: 0x8007273f
0x8007273f ?????????
when I use wsl to install ubuntu, it will fail with error

### Page URL

https://learn.microsoft.com/zh-cn/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install-manual.md

### Author

@craigloewen-msft

### Document Id

3fd655c2-9bb3-67d7-c369-545f38f805d8

**Comment by craigloewen-msft** [comment]
This is a technical issue, please file it here at the microsoft/wsl repo!

https://github.com/microsoft/WSL/issues/new?template=Bug_Report.yaml

Thank you.
