### ISSUE TITLE
Ubuntu 24.04 LTS missing from list of manual download locations

### ISSUE THREAD

**Issue by ralphhendriks** [MicrosoftDocs/WSL#1963]
### Type of issue

Missing information

### Feedback

- The list of URLs for manual download of distros in the _Downloading distrubitions_ section of the page is missing Ubuntu 24.04 LTS as an option, although this is now available from the Store-based installation.
- Also, the top entry in the list, _Ubuntu_, redirects to 22.04 LTS. I believe this should now point to 24.04 LTS instead as it is the current LTS version.
- Furthermore, the article describes that these links will download a file names `<distro>.appx`, whereas in my case a file called `Ubuntu2204-221101.AppxBundle` got downloaded. The file extension is not matching.
- Lastly, it is not clear to me in this section of the page whether the `Add-AppxPackage` must be run before double-clicking the file, or that these two actions have the same result. The 'Once the Appx package has finished downloading' sentence is causing me confusion.

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-5---set-wsl-2-as-your-default-version

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install-manual.md

### Author

@craigloewen-msft

### Document Id

3fd655c2-9bb3-67d7-c369-545f38f805d8

**Comment by ralphhendriks** [comment]
Partly duplicate of #1952. Other points still might need taking a look ;-)

**Comment by craigloewen-msft** [comment]
Fixing this PR: 
https://github.com/MicrosoftDocs/WSL/pull/1981

Will track using the other issue :) Thank you for filing!
