### ISSUE TITLE
Add to section information to reset the default user after importing a WSL distro

### ISSUE THREAD

**Issue by adriantorrie** [MicrosoftDocs/WSL#1965]
### Type of issue

Missing information

### Feedback

For the [section related to moving a WSL distro](https://learn.microsoft.com/en-us/windows/wsl/faq#how-can-i-move-my-wsl-distribution-to-a-different-drive-or-location-), please also include the information to set the default user, or at least a reference and link to [Advanced settings configuration in WSL: User settings](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#user-settings).

I had to hunt around StackOverflow to find the finishing touches to move my WSL2 distro.

The example in the "Advanced setttings" also has an [example wsl.conf](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#example-wslconf-file) with the section:

```sh
# Set the user when launching a distribution with WSL.
[user]
default = DefaultUser
```

This information could be directly included here.

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/faq

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/faq.yml

### Author

@craigloewen-msft

### Document Id

156d9535-c2a5-bc8d-af24-342a13832abf

**Comment by craigloewen-msft** [comment]
Made a PR here!
https://github.com/MicrosoftDocs/WSL/pull/1982

**Comment by mattwojo** [comment]
Merged: https://github.com/MicrosoftDocs/WSL/pull/1982
