### ISSUE TITLE
wsl issue

### ISSUE THREAD

**Issue by Daani672** [MicrosoftDocs/WSL#1969]
### Type of issue

Outdated article

### Feedback

check my issue does not work in my comuter

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/compare-versions

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/compare-versions.md

### Author

@craigloewen-msft

### Document Id

10a6919c-5152-2aa3-4d90-ccfa45cbbcc5

**Comment by mattwojo** [comment]
We will need more details in order to take action on this issue. Closing, but please re-open if you can explain what you're finding that needs to be updated.
