### ISSUE TITLE
Typing Error on the landing page

### ISSUE THREAD

**Issue by PrakashMohit** [MicrosoftDocs/WSL#1973]
### Documentation Issue

Hello team there is a typo on the very first Landing page of WSL documentation on first bullet point line where it is written.

[https://learn.microsoft.com/en-us/windows/wsl/about](url)

Use WSL to run varoius linux distribution on your windows machine or create your own CUSTOMER distribution.
it should be CUSTOM Distribution.

![asdfasdsadas](https://github.com/MicrosoftDocs/WSL/assets/75770160/42b2acdd-22e8-4eab-ae8e-810d664d61b2)

Thanks for adressing my feedback in advance.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/about

Error is Highlited with Yellow colour

![asdfasdsadas](https://github.com/MicrosoftDocs/WSL/assets/75770160/0e9a5657-0fa9-4d07-a45b-391ae4ec7aad)

### Suggested Improvements

The Word CUSTOMER distribution should be changed .
It should be CUSTOM distribution

**Comment by craigloewen-msft** [comment]
Madea  PR for this! Thank you for filing!
https://github.com/MicrosoftDocs/WSL/pull/1983
