### ISSUE TITLE
surface pro 11 and wsl

### ISSUE THREAD

**Issue by MaQu42** [MicrosoftDocs/WSL#1974]
### Type of issue

Other (describe below)

### Feedback

New surface pro 11, was using wsl with ubuntu 24.04. needed to Reset PC (don't ask).

now, no wsl... enabled features, restart, powershell and cmd (as administrator) both kick out ClassNotReg or some such.

wsl --install, wsl -l -o both give same error.

online search for help provides no clear solution. windows home vs. pro? cloud reset vs. local disk yields same results (no worky).

any ideas?

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/faq

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/faq.yml

### Author

@craigloewen-msft

### Document Id

156d9535-c2a5-bc8d-af24-342a13832abf

**Comment by craigloewen-msft** [comment]
For this issue please try downloading the `msi` package and install that manually. This might fix you!
https://github.com/microsoft/WSL/releases/tag/2.2.4

For future technical issues please file them at www.github.com/microsoft/wsl as this repo is for documentation issues only. Thank you!
