### ISSUE TITLE
windows subsystem for linux

### ISSUE THREAD

**Issue by asraful3g** [MicrosoftDocs/WSL#1979]
### Type of issue

Missing information

### Feedback

microsoft app store dont have this linux app

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/enterprise

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/enterprise.md

### Author

@craigloewen-msft

### Document Id

9da3bc76-b6c2-9b90-afc3-3c8539359271

**Comment by craigloewen-msft** [comment]
WSL is serviced through the Microsoft Store but isn't available in search in the Microsoft Store. If you'd like to install the app please use `wsl --install` and if you'd like to download the app please use the GitHub release page: 
https://github.com/microsoft/WSL/releases

Thank you for filing!
