### ISSUE TITLE
REGDB_E_CLASSNOTREG

### ISSUE THREAD

**Issue by artvabasDev** [MicrosoftDocs/WSL#1993]
### Type of issue

Typo

### Feedback

Try to install WSL, but get this message:
PS C:\Users\xxx> wsl --install
Klasse is niet geregistreerd (means: class not registered)
Error code: Wsl/CallMsi/Install/REGDB_E_CLASSNOTREG

### Page URL

https://learn.microsoft.com/nl-nl/windows/wsl/install

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md

### Author

@craigloewen-msft

### Document Id

7ed8fb81-5b8f-4d56-7b89-bf600ce6080a

**Comment by mattwojo** [comment]
Hi @artvabasDev - I don't believe this is an issue with the WSL documentation, so I'm going to refer you to the product repo. It looks like this may align with the issue you're encountering: https://github.com/microsoft/WSL/issues/10882
They recommend that you try running the command: `wsl.exe --update --pre-release`

**Comment by rn0x7f** [comment]
It seems that everyone who reinstalls Windows from scratch starts having that problem with wsl, it is happening to everyone recently. The same error appears for any command that starts with "wsl", i have been trying for 6 hours but I haven't been able to fix it either, i'm about to reset my computer for the third time today...

**Comment by artvabas** [comment]
I have installed the latest release from github, and the problem didn't occurred anymore.

**Comment by rn0x7f** [comment]
> I have installed the latest release from github, and the problem didn't occurred anymore. 
LMAO Thank you, a problem that was solved in just 10 seconds...
https://github.com/microsoft/WSL/releases
