### ISSUE TITLE
powershell  wsl 系统找不到指定的文件。

### ISSUE THREAD

**Issue by hepeng000** [MicrosoftDocs/WSL#1997]
### Type of issue

Typo

### Feedback

powershell  wsl 系统找不到指定的文件。

### Page URL

https://learn.microsoft.com/zh-cn/windows/wsl/install

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md

### Author

@craigloewen-msft

### Document Id

7ed8fb81-5b8f-4d56-7b89-bf600ce6080a

**Comment by mattwojo** [comment]
@hepeng000 We will need more information to be able to help you with this WSL install issue. This also does not appear to be a documentation issue, rather a support issue with your particular device. One suggestion - if you are working in an Enterprise environment, your permission to install WSL may be blocked or limited. If you are in a restricted business setting and need access to WSL, you may want to check with your IT Admin. You can find recommended Intune settings for using WSL in this context at: https://learn.microsoft.com/en-us/windows/wsl/intune

If this does not resolve the issue, I recommend that you open a new issue at https://github.com/microsoft/WSL/issues and provide more context and log data to help with understanding the problem.

我们需要更多信息才能帮助您解决此 WSL 安装问题。这似乎也不是文档问题，而是特定设备的支持问题。一项建议 - 如果您在企业环境中工作，您安装 WSL 的权限可能会被阻止或限制。如果您处于受限的业务环境中并且需要访问 WSL，您可能需要咨询您的 IT 管理员。您可以在以下位置找到在这种情况下使用 WSL 的推荐 Intune 设置：https://learn.microsoft.com/en-us/windows/wsl/intune

如果这不能解决问题，我建议您在 https://github.com/microsoft/WSL/issues 上打开一个新问题，并提供更多上下文和日志数据以帮助理解问题。
