### ISSUE TITLE
Need more information about error messages and possible solutions for that

### ISSUE THREAD

**Issue by MortenHaensch** [MicrosoftDocs/WSL#2005]
### Documentation Issue

When I tried to install WSL, I got the following error message during the installation process of WSL:
"Installation: Windows-Subsystem für Linux
Schwerwiegender Fehler"
The error message "Installation: Windows-Subsystem für Linux
Schwerwiegender Fehler" is not listed in the documentation.

### Link to documentation page

https://learn.microsoft.com/de-de/windows/wsl/troubleshooting

### Suggested Improvements

I hope, that it's possible to provide a possible solution for the error message "Installation: Windows-Subsystem für Linux
Schwerwiegender Fehler". Thank you very much!

**Comment by mattwojo** [comment]
I'm sorry you're having trouble installing WSL @MortenHaensch. I believe that the troubleshooting section you want to reference is https://learn.microsoft.com/de-de/windows/wsl/troubleshooting#installation-issues.

I'm closing this issue as it does not seem to require an update to the WSL documentation. If you continue to receive an error message when trying to install WSL, I recommend first that if you are in a business / enterprise work environment, you may want to check with your IT administrator to see if permissions to use WSL are enabled. If you're at a company that utilizes Intune, you can find more about setting up permissions here: https://learn.microsoft.com/en-us/windows/wsl/intune. If this is not the case, you may want to file an issue on the WSL product repo here: https://github.com/Microsoft/WSL/issues Be sure to include as many details as you can, such as what version of Windows operating system you are using, the method that you are using to install WSL, any error code numbers you receive, and a log if possible.
