### ISSUE TITLE
 Microsoft Store for Business is retired

### ISSUE THREAD

**Issue by likp** [MicrosoftDocs/WSL#2008]
### Type of issue

Outdated article

### Feedback

The [Microsoft Store for Business](https://businessstore.microsoft.com/) seams to be retired. Should one download WSL images from the regular Microsoft Store instead? 

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/enterprise

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/enterprise.md

### Author

@craigloewen-msft

### Document Id

9da3bc76-b6c2-9b90-afc3-3c8539359271

**Comment by mattwojo** [comment]
Good catch! Thank you for bringing this to our attention @likp.  Yes - just download WSL images from the regular Microsoft Store instead. Fixing the documentation now. Thanks again.
