### ISSUE TITLE
List distributions

### ISSUE THREAD

**Issue by ddieppa** [MicrosoftDocs/WSL#201]
Reading this section [List distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#list-distributions) and follow the instructions there I got this output:
`Windows Subsystem for Linux Distributions: 
Legacy (Default)`
Do I have to go inside the [WSL](https://docs.microsoft.com/en-us/windows/wsl/about) and ask directly for the distribution in this case or I have to update something in my windows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#list-distributions)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl-config.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by scooley** [comment]
That means you're running the distribution we bundled with WSL when it launched (Ubuntu 16.04).  If you download distros from the store, they'll appear along side the legacy distro and will have a proper name.  Functionally, there's nothing wrong with the default distro - it's Ubuntu 18.04 - but it doesn't have all of the same launch options as the store distros (specifically 'ubuntu.exe').

I'll update the doc to include this info as well :)
