### ISSUE TITLE
Pi Network

### ISSUE THREAD

**Issue by ChamraeunRan** [MicrosoftDocs/WSL#2011]
### Type of issue

Code doesn't work

### Feedback

31400, 31401, 31402, 31403, 31404
31405, 31406, 31407, 31408, 31409

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/wsl-config#experimental-settings

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/wsl-config.md

### Author

@craigloewen-msft

### Document Id

9f406c77-415c-80db-d596-0a7fa4ea2ba9
```[tasklist]
### Tasks
```

**Comment by Hamdan0i** [comment]
Validatorkyc
