### ISSUE TITLE
Linux and macOS versions of wsl.exe

### ISSUE THREAD

**Issue by ericcurtin** [MicrosoftDocs/WSL#2019]
### Documentation Issue

I think it would be useful if we build Linux and macOS versions of wsl.exe (obviously my preference is Linux).

Doesn't have to support the same level of features, but if it could download a wsl artefact and convert to a .qcow2 even that would be very useful to boot via qemu on Linux and macOS.

### Link to documentation page

I think it would be useful if we build Linux and macOS versions of wsl.exe (obviously my preference is Linux).

Doesn't have to support the same level of features, but if it could download a wsl artefact and convert to a .qcow2 even that would be very useful to boot via qemu on Linux and macOS.

**Comment by mattwojo** [comment]
Hey @ericcurtin - Could you expand a bit on how a Linux and macOS version of wsl.exe would be helpful? WSL is specifically a tool for running Linux distributions on Windows devices, so I'm not quite tracking with the need.

**Comment by ericcurtin** [comment]
WSL has a catalog of ready to use VMs...

Even if there was a wsl2 image puller for macOS/Linux that would be useful...

Maybe the community could figure out how to convert them to .qcow2 or whatever if there was a start via a WSL2 puller...

**Comment by mattwojo** [comment]
This is more of a feature request than an update to the docs. Could you file this suggestion here in the WSL product repo for the dev team to review? > https://github.com/microsoft/WSL/issues

**Comment by crramirez** [comment]
@ericcurtin maybe what you are looking for already exists https://github.com/lima-vm/lima also you can use docker containers to have the almost the same functionality
