### ISSUE TITLE
Guy

### ISSUE THREAD

**Issue by Gsahj** [MicrosoftDocs/WSL#2020]
### Type of issue

Typo

### Feedback

[_`](url)
[Uploading Safety_information_Rev.2.0.0_231013.pdf…]()

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/install

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md

### Author

@craigloewen-msft

### Document Id

7ed8fb81-5b8f-4d56-7b89-bf600ce6080a

**Comment by mattwojo** [comment]
Please do not open issues unless you actually have a contribution.
