### ISSUE TITLE
WSL must be installed as normal user

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/WSL#2024]
### Type of issue

Code doesn't work

### Feedback

Using elevation does not work.
But it might be wise to update WSL as suggested by https://learn.microsoft.com/en-us/windows/wsl/install-manual#installing-your-distro
That made sure that I got error codes that could be googled.

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/install

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md

### Author

@craigloewen-msft

### Document Id

7ed8fb81-5b8f-4d56-7b89-bf600ce6080a

**Comment by mattwojo** [comment]
Hey @Tarjei-stavanger - Could you expand a bit on the issue that you're encountering? It's not clear from this description. Are you trying to install WSL from within an Enterprise business environment where there are permission restrictions?
Closing this issue as it doesn't appear to have any necessary doc updates currently, but please feel welcome to reopen and expand on the issue that you've encountered. Thanks!
