### ISSUE TITLE
WSL install instructions don't contain the necessary prerequisites

### ISSUE THREAD

**Issue by johnmreynolds** [MicrosoftDocs/WSL#2025]
### Type of issue

Missing information

### Feedback

The install instructions say just to run wsl --install

but this doesn't work without additional windows features being switched on.

In particular I think it needs hyper v and indeed 'Windows Subsystem for Linux' in the features selection.

It's also not clear how that latter feature interacts with the command line install.

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/install

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md

### Author

@craigloewen-msft

### Document Id

7ed8fb81-5b8f-4d56-7b89-bf600ce6080a

**Comment by mattwojo** [comment]
Hey @johnmreynolds - Running `wsl --install` actually turns on those features (enabling WSL and Hyper-v) for you. See: https://learn.microsoft.com/en-us/windows/wsl/setup/environment#get-started

**Comment by johnmreynolds** [comment]
Didn’t work for me - instead it failed with and obscure error until I manually enabled them.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Matt Wojciakowski ***@***.***>
Sent: Monday, September 23, 2024 7:22:41 PM
To: MicrosoftDocs/WSL ***@***.***>
Cc: John Reynolds ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [MicrosoftDocs/WSL] WSL install instructions don't contain the necessary prerequisites (Issue #2025)


[Caution] This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hey @johnmreynolds<https://github.com/johnmreynolds> - Running wsl --install actually turns on those features (enabling WSL and Hyper-v) for you. See: https://learn.microsoft.com/en-us/windows/wsl/setup/environment#get-started
