### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by daniela2000111** [MicrosoftDocs/WSL#2035]
### Type of issue

Missing information

### Feedback

bug report

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/about

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/about.md

### Author

@craigloewen-msft

### Document Id

f583bc11-fe60-bb2c-af2b-dc0dae9fe81f

**Comment by mattwojo** [comment]
No issue identified. Feel welcome to reopen and describe the issue related to WSL documentation.
