### ISSUE TITLE
gelcollection

### ISSUE THREAD

**Issue by Angel1869** [MicrosoftDocs/WSL#2046]
### Type of issue

Code doesn't work

### Feedback

Yes, it is correct to write "Please find attached the following reports." This phrase is commonly used in professional and formal correspondence to inform the recipient that documents or reports are included with the email or letter. It clearly indicates that the sender has attached specific files and lists them for easy reference.

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/about#what-is-wsl-2

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/about.md

### Author

@mattwojo

### Document Id

f583bc11-fe60-bb2c-af2b-dc0dae9fe81f

**Comment by mattwojo** [comment]
Please feel welcome to reopen and explain
