### ISSUE TITLE
how to install wsl when it not working it is showing"C:\Users\>wsl --install The system cannot find the path specified."

### ISSUE THREAD

**Issue by Aryanyogeeshkapu** [MicrosoftDocs/WSL#2048]
### Type of issue

Code doesn't work

### Feedback

![Screenshot 2024-10-19 112958](https://github.com/user-attachments/assets/5c2d8e0e-7f36-40f1-8451-32df5e77191d)

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/install#install-wsl-command

### Content source URL

https://learn.microsoft.com/en-us/windows/wsl/install#install-wsl-command

### Author

https://learn.microsoft.com/en-us/windows/wsl/install#install-wsl-command

### Document Id

https://learn.microsoft.com/en-us/windows/wsl/install#install-wsl-command

**Comment by mattwojo** [comment]
The `System32` folder is reserved for system files... not a place to install WSL. Use your `Program Files` folder instead.

**Comment by Aryanyogeeshkapu** [comment]
no working 
#mattwojo
