### ISSUE TITLE
root@DESKTOP-JALKA9A:~#

### ISSUE THREAD

**Issue by spaarti1997** [MicrosoftDocs/WSL#2057]
### Type of issue

Other (describe below)

### Feedback

Ihave installed ubantu first time but i only see root user insted of any specific username or password prompt. How can I set up my own user account for daily use. Following types of information sown when open ubantu -
"root@DESKTOP-JALKA9A:~#"

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/compare-versions#wsl-in-the-microsoft-store

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/compare-versions.md

### Author

@mattwojo

### Document Id

10a6919c-5152-2aa3-4d90-ccfa45cbbcc5

**Comment by mattwojo** [comment]
https://learn.microsoft.com/en-us/windows/wsl/setup/environment#set-up-your-linux-username-and-password
