### ISSUE TITLE
how to backup wsl(debian) in win10 1803

### ISSUE THREAD

**Issue by ChowhaoHQD** [MicrosoftDocs/WSL#206]
I need to backup wsl , I try to used rsync, but it's display error. what should I do?

**Comment by Amitie10g** [comment]
Ensure everything in the environment is not running (kill the "init" process if necessary).

**Comment by DarthSpock** [comment]
`rsync` works just fine if you're syncing to a Linux server. But if you want a copy in Windows then you want to use `cp`. Make sure you enable metadata in the backup directory via `wsl.conf`. Also while Docs may be a great place for this, they do blogs over the most important stuff such as using `wsl.conf` and enabling `metadata` to preserve Linux permissions. So questions like this should go to https://github.com/Microsoft/WSL, where you're more likely to get an answer more quickly from the WSL community.

**Comment by mscraigloewen** [comment]
This can be done easily using the `wsl --export` and `wsl --import` commands. You can find them [here at our reference page](https://docs.microsoft.com/en-us/windows/wsl/reference).
