### ISSUE TITLE
Errno 13

### ISSUE THREAD

**Issue by escape160** [MicrosoftDocs/WSL#207]
Hi, I got an issue after install ubuntu.  tying to run some simple script in the classroom, however it is denied every time...with this error message " python3: can't opent file 'simple.py': [Errno 13] permission denied"; 
then trying to chmod 764 simple.py; it was denied again: "chmod: change permissions of 'simple.py': operation not permitted"  

could someone please help me? very frustrating...thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install the Linux Subsystem on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by Amitie10g** [comment]
Have you used sudo?

**Comment by mscraigloewen** [comment]
As @Amitie10g said I recommend using sudo. 

For any further WSL specific issues please file them at [the WSL repo](https://github.com/microsoft/wsl). This repo is only for issues with the documentation. Thanks!
