### ISSUE TITLE
Which one has higher permissions, .wslconfig global configuration or WSL Settings.exe configuration? How to view the parameter names of WSL Settings.exe configuration items?

### ISSUE THREAD

**Issue by sunsboyxu** [MicrosoftDocs/WSL#2072]
### Type of issue

Missing information

### Feedback

After I successfully installed wsl2 and Ubuntu, I created a wsl2 global configuration file .wslconfig in C:\Users\<UserName> and made relevant configurations, but suddenly I found that there is a WSL Settings.exe that can also configure wsl2. In Windows 11 computer, select Start Menu -> Search Application WSL Settings, then click WSL Settings. A panel that controls wsl2 settings will pop up. I want to know the specific parameters set in this panel. After setting, which one has a higher weight, it or the global configuration file .wslconfig?
![1](https://github.com/user-attachments/assets/1be137fd-6f0b-49b2-8e39-d730cb1a341c)
wsl settings control panel
![2](https://github.com/user-attachments/assets/7793f0de-a7ed-4022-8ac8-3acf6fde1589)

### Page URL

https://learn.microsoft.com/zh-cn/windows/wsl/wsl-config

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/wsl-config.md

### Author

@mattwojo

### Document Id

9f406c77-415c-80db-d596-0a7fa4ea2ba9

**Comment by craigloewen-msft** [comment]
The `WSL Settings App` will configure and control values in the `.wslconfig` app, so they are one in the same thing at the end of the day. If you edit your settings and then open the file you will see it edited there. Thanks for filing this!
