### ISSUE TITLE
The linux folder in explorer.exe doesn't work

### ISSUE THREAD

**Issue by HYC-madao** [MicrosoftDocs/WSL#2073]
### Type of issue

Other (describe below)

### Feedback

![螢幕擷取畫面 2024-11-27 164942](https://github.com/user-attachments/assets/41888606-8bfb-4562-a71c-2d1a926295d1)
As you can see, I have a hollow penguien.

I've tried `wsl --shutdown` and reboot computer,  install debian/kali, or repair and reset in windows system component. But nothing works.

![螢幕擷取畫面 2024-11-27 225729](https://github.com/user-attachments/assets/b47f17ba-002f-4771-bcb4-a2b30f7eca97)

Do I lost miss some steps in install process?

### Page URL

https://learn.microsoft.com/zh-tw/windows/wsl/install

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md

### Author

@mattwojo

### Document Id

7ed8fb81-5b8f-4d56-7b89-bf600ce6080a

**Comment by crramirez** [comment]
Could you confirm what happens with you run `explorer.exe . ` from Ubuntu. Watch the dot in the command

**Comment by HYC-madao** [comment]
Thank you for noting what I forgot mention.  `$explorer.exe ` it works.

All the  WSL function works except the Penguin folder.

________________________________
寄件者: Carlos Rafael Ramirez ***@***.***>
寄件日期: 2024年11月29日 上午 12:09
收件者: MicrosoftDocs/WSL ***@***.***>
副本: HYC-madao ***@***.***>; Author ***@***.***>
主旨: Re: [MicrosoftDocs/WSL] The linux folder in explorer.exe doesn't work (Issue #2073)


Could you confirm what happens with you run explorer.exe . from Ubuntu. Watch the dot in the command

**Comment by crramirez** [comment]
By any chance after you run the command, your Linux folder doesn't get updated with your distro? This is what used to happen to me. 

You didn't do anything bad. Check with an `wsl --update` and install every windows update patch. Just to be sure you have the latest. And with luck it will get solved.

If not you can fill an issue on the main project Microsoft/WSL. This repo is only regarding the documentation.

**Comment by HYC-madao** [comment]
https://github.com/user-attachments/assets/0da57ba1-3ff4-4951-928c-1c63d3705bdd

I record a video. At the end, I don't know what i've done or what happen. These two WSL folders suddenly appear.

**Comment by craigloewen-msft** [comment]
Are you still seeing this issue? If so can you please file this at github.com/microsoft/wsl ? This repository just tracks issues with the docs.
