### ISSUE TITLE
I cannot open my WSl  server on my windows 11 Machine

### ISSUE THREAD

**Issue by awoto2000** [MicrosoftDocs/WSL#2079]
### Type of issue

Typo

### Feedback

I cannot open my WSl  server on my windows 11 Machine

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#uninstall-legacy-version-of-wsl

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/troubleshooting.md

### Author

@mattwojo

### Document Id

91d93e7d-8206-77bf-ace0-f8c44810bf17

**Comment by craigloewen-msft** [comment]
If you're still seeing this technical issue please file it at github.com/microsoft/wsl this repository is just for issues with the docs. Thank you!
