### ISSUE TITLE
Passing windows paths to windows executables in wsl

### ISSUE THREAD

**Issue by abeck70** [MicrosoftDocs/WSL#208]
I noted this does not work:
~$ notepad.exe /mnt/c/temp/foo.txt

But this does work and is equivalent to /mnt/c being prepended:
~$ notepad.exe /tmp/foo.txt

Understanding this was critical to getting a gnu make in WSL running a compiler that is a windows executable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea49528-e5c5-4f64-841e-9fe036de304e
* Version Independent ID: edeb7cb5-afcf-1410-4966-f48ce5f6a19a
* Content: [Windows interoperability with Linux](https://docs.microsoft.com/en-us/windows/wsl/interop)
* Content Source: [WSL/interop.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/interop.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by sunilmut** [comment]
This repo is for WSL documentation. The repo which you are looking for is https://github.com/Microsoft/WSL/issues/ . Please post the issue there.

**Comment by abeck70** [comment]
Sorry for not being more direct. There is a gap in the documentation. It makes no mention on how windows executables manage Linux path formats.

**Comment by sunilmut** [comment]
@abeck70 - Windows executables cannot work with Linux paths. Hopefully that clarifies the documentation issue. If you are looking for something specific, please open a issue in the WSL issues git hub repo with specific instructions.
