### ISSUE TITLE
you cant access window host `localhost:port` in wsl with host real ip

### ISSUE THREAD

**Issue by samegek** [MicrosoftDocs/WSL#2084]
### Type of issue

Typo

### Feedback

in windows , you run node app, 127.0.0.1:5000
in wsl, windows host ip is 192.168.96.193
in wsl you execute `curl -v 192.168.96.193:5000` is bad, no response

### Page URL

https://learn.microsoft.com/zh-cn/windows/wsl/networking

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/networking.md

### Author

@mattwojo

### Document Id

f9e21bfa-6316-7d45-3b34-834a78bcaf0f

**Comment by taoyouh** [comment]
I just met this problem and I think these 2 steps are necessary to make it work:
1. Listen on 0.0.0.0 instead of 127.0.0.1
2. Add a firewall rule to allow inbound access

If these are true, we shall update the doc.
