### ISSUE TITLE
How to do elevation for first step? - 

### ISSUE THREAD

**Issue by mtjoy747** [MicrosoftDocs/WSL#209]
When I try the powershell command, it comes back with "this command requires elevation", how is that done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install the Linux Subsystem on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by sunilmut** [comment]
Couple of ways to do that. Either launch powershell as administrator or you can use something like `'runas.exe /noprofile /user:Administrator <command>`
