### ISSUE TITLE
MS Store disabled after Enable-WindowsOptionalFeature ...

### ISSUE THREAD

**Issue by fametrano** [MicrosoftDocs/WSL#212]
MS Store is disabled after the command
_Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux_

I've been following https://docs.microsoft.com/en-us/windows/wsl/install-win10

I discovered the problem when on my Dell XPS13 9370 I could not download Ubuntu after the above command: mconfig had switched to selective startup and it could not be changed back to normal startup; this in turn prevented any installation from MS Store

I got crazy in trying to switch back to normal startup with no luck. Out of frustration and assuming it might have been a Dell configuration problem I did a fresh clean install of Windows 10 avoiding the Dell install tool and using the MS install tool
Then, by chance I first downloaded Ubuntu from MS Store, issuing the Enable-WindowsOptionalFeature command only later. Now, Ubuntu works, but selective startup is back, and MS Store does not work again.

please help

I've also asked the Dell community:
https://www.dell.com/community/XPS/MS-Store-disabled-after-Enable-WindowsOptionalFeature/td-p/6093606

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install the Linux Subsystem on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by Oldsouldier** [comment]
This workaround worked for me: 
https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_store-insiderplat_pc/microsoft-store-application-broken-or-missing/a0a92c3c-4ea3-4748-bb90-9991ec22dd3e

**Comment by ryall** [comment]
Also have this problem The workaround didn't fix it.
