### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by statup-github** [MicrosoftDocs/WSL#214]
This is not working on 1803. You're still logged in as your own user.

Per 
https://askubuntu.com/questions/772050/reset-the-password-in-linux-bash-in-windows
the best (only?) solution is to edit the Linux /etc/shadow from Windows (even though MS discourages doing that)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Linux User Account and Permissions](https://docs.microsoft.com/en-us/windows/wsl/user-support)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/user-support.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by keithAtGerber** [comment]
I encountered this issue also, but I found that the advice of a certain commenter on one of the SO answers worked. `ubuntu config --default-user` fails silently (for me) if I already have an instance of Ubuntu running.  After closing all Ubuntu instances, the command worked.

https://askubuntu.com/questions/772050/reset-the-password-in-linux-bash-in-windows#comment1652292_808425

**Comment by kobenauf** [comment]
Thank you @keithAtGerber!  I have spent so much time trying to get this to work, and it was because I had other ubuntu sessions running.

**Comment by alokprasad2020** [comment]
While installing ubuntu it asked for the username and password. I typed the username but whenever it comes to type the password the keypad always stops working.
Any help would be really appreciated.

**Comment by craigloewen-msft** [comment]
We've added better guidance for users to reset their passwords. [See here](https://docs.microsoft.com/en-us/windows/wsl/user-support#forgot-your-password). Thank you for filing this! :)
