### ISSUE TITLE
An easier way to get the Windows build number

### ISSUE THREAD

**Issue by q--** [MicrosoftDocs/WSL#215]
Simply press Windows key + R, type "winver" and hit enter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting the Windows Susbystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/troubleshooting.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by gjonespf** [comment]
Or if scripting, a more reliable version check across different OS versions:
```powershell
[Version](Get-CimInstance Win32_OperatingSystem).version
```

**Comment by mscraigloewen** [comment]
Thank you for the feedback!
