### ISSUE TITLE
lxrun is deprecated

### ISSUE THREAD

**Issue by thesmart** [MicrosoftDocs/WSL#216]
`lxrun.exe /setdefaultuser username` results in:
```
Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

Error: 0x80070002
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Linux User Account and Permissions](https://docs.microsoft.com/en-us/windows/wsl/user-support)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/user-support.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by thesmart** [comment]
`ubuntu config --default-user ` works for ubuntu at least...

**Comment by JaimeChavarriaga** [comment]
This page may state clearly that `lxrun.exe` was deprecated after the Fall Creators Update.
* It may include a note at the beginning of the explanation
* It includes instructions for versions before and after that Fall Creators Update

**Comment by james28909** [comment]
i have wsl installed, but not from the windows store. how do i access this ubuntu command?

**Comment by JaimeChavarriaga** [comment]
If you have installed WSL, you may [use `wsl`, `bash` or the distro name](https://blogs.msdn.microsoft.com/commandline/2017/11/28/a-guide-to-invoking-wsl/).

**Comment by solarkraft** [comment]
It sure would be nice to have a hint in the lxrun docs at what to do now that it is gone. wslconfig seems to work for some tasks, while the distro name is needed for some other ones.

**Comment by mscraigloewen** [comment]
I've updated the `reference.md` page to have up to date information about command line options for WSL.
