### ISSUE TITLE
Keyword PowerShell can be removed

### ISSUE THREAD

**Issue by devvasu** [MicrosoftDocs/WSL#217]
Confirm WSL enabled command has an additional keyword PowerShell that could be removed.

**_PowerShell_
Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux** 

can be changed to
**Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux**

**Comment by mscraigloewen** [comment]
Fixed!
