### ISSUE TITLE
no network connectivity once connected to a VPN

### ISSUE THREAD

**Issue by boahen55** [MicrosoftDocs/WSL#220]
I have install kali Linux app from the app store, but it seems there is no internet connectivity when I run eg: (apt-get update) command when ever I connect to VPN in windows, everything works fine when I stop VPN connection. Can I tunnel WSL traffic to work with the VPN or even through localhost

**Comment by ssnyder** [comment]
I have the same issue - I must edit the /etc/resolv.conf file every time to use the dns server my computer is using (as provided by my vpn).  The setting in /etc/wsl.conf does not seem to work either (generateResolvConf = false)

**Comment by EugeneFractal** [comment]
Same here.

> The setting in /etc/wsl.conf does not seem to work either (generateResolvConf = false)

When set to `false` it does not create the file (thus no name can be resolved at all), neither it allows to manually create the file.

**Comment by actonDev** [comment]
puting a `nameserver x.x.x.x` indeed fixes the internet problems inside wsl2 in my case as well. (obtaining the x.x.x.x ip by for example running `nslookup` in a windows terminal.

**HOWEVER**
With the VPN connected, I can no longer access my host machine (windows) from inside WSL2. (I use this to have a X server in my windows machine).
Any idea about this?

**Comment by DDtKey** [comment]
> 
> 
> **HOWEVER**
> With the VPN connected, I can no longer access my host machine (windows) from inside WSL2. (I use this to have a X server in my windows machine).
> Any idea about this?

Maybe it's too late and not the best solution, but as an option, you can configure it like this:
```
nameserver x.x.x.x
nameserver y.y.y.y

options rotate
options timeout:2
options attempts:1
```
where `x.x.x.x` - this is your DNS without VPN, and `y.y.y.y `- DNS provided by VPN (You can get it in the same way, after connecting to VPN)
This will allow you to switch between different DNS.

**Comment by craigloewen-msft** [comment]
We've made some significant changes to networking on WSL behind the scenes. IF you're still experiencing a networking issue could you please file a bug on the [WSL Github repo](https://github.com/microsoft/wsl) describing your issue? We'd be happy to follow up over there. Thank you!
