### ISSUE TITLE
Microsft-Windows-Subsystem-Linux everytime 

### ISSUE THREAD

**Issue by atulkumarpccs** [MicrosoftDocs/WSL#221]
![image](https://user-images.githubusercontent.com/13286642/42012218-736a8a62-7ada-11e8-84d2-a77a697eee71.png)

Facing the above issue (also followed the given steps)

1. https://docs.microsoft.com/en-us/windows/wsl/install-win10

2. https://docs.microsoft.com/en-us/windows/wsl/install-win10#for-anniversary-update-and-creators-update-install-using-lxrun

**Comment by quiret** [comment]
Is WSL even meant to be available for Home editions of Windows 10?

**Comment by mscraigloewen** [comment]
For any WSL specific issues please file them at [the WSL repo](https://github.com/microsoft/wsl). This repo is only for issues with the documentation. Thanks!
