### ISSUE TITLE
Ambiguous Description: Share environment variables between Windows and WSL

### ISSUE THREAD

**Issue by FBoyne** [MicrosoftDocs/WSL#222]
The section on [Share environment variables between Windows and WSL][1] says "Available in Windows Insider builds 17063 and later".  It is not clear whether or not "and later" includes the April 2018 Update (build 17134) or not.

On the one hand build 17134 is definitely later than build 17063 but on the other hand the April 2018 Update is not an Insider build.  

Typically (but not always) one would expect Insider build features to appear in the subsequent Update release.  However an experiment on build 17134 seems to show the WSLENV environment variable has no effect.  Of course that may be due to a flawed experiment on my part.  [Several non-Microsoft sites claim WSLENV is available in the April 2018 update][2] but I have not found a Microsoft site that makes the claim.

If the WSLENV feature is **not** available in the April 2018 update it would be helpful if this page made that unambiguously clear.  For example: perhaps the "Updated for Fall Creators Update." section at the top of the page might be updated to mention the April 2018 Update; and the "Available in Windows Insider builds 17063 and later." caveat could also be updated?

[1]: https://docs.microsoft.com/en-us/windows/wsl/interop#share-environment-variables-between-windows-and-wsl
[2]: https://www.bing.com/search?q=%2BWSLENV%20%2B%22April%202018%20Update%22%20-site%3Amicrosoft.com%20&qs=n&form=QBRE&sp=-1&pq=%2Bwslenv%20%2B%22april%202018%20update%22%20-site%3Amicrosoft.com%20&sc=0-49&sk=&cvid=7E06F34171D049E4BCF7961B74F692BE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea49528-e5c5-4f64-841e-9fe036de304e
* Version Independent ID: edeb7cb5-afcf-1410-4966-f48ce5f6a19a
* Content: [Windows interoperability with Linux](https://docs.microsoft.com/en-us/windows/wsl/interop#share-environment-variables-between-windows-and-wsl)
* Content Source: [WSL/interop.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/interop.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by deepakSP** [comment]
i also tried today but was not able to get it work ! can someone confirm that wslenv is available or not ?
