### ISSUE TITLE
Warn That Case Matters in "Share environment variables between Windows and WSL"

### ISSUE THREAD

**Issue by FBoyne** [MicrosoftDocs/WSL#223]
It would be helpful if the section [Share environment variables between Windows and WSL][1] warned the reader that the case of environment variable names is significant.  

In particular: the WSLENV environment variable name must be defined using all upper-case while the case of the environment variable names used in WSLENV must match the case used when the environment variable was first defined.

For example the following Win32 commands … 
```
    set RED=C:\USERS
    set wslenv=RED/p
    ubuntu
```
… will fail to create a Linux environment variable called `RED` because 'wslenv' is defined using lower-case.

Similarly, the following Win32 commands...
```
    set RED=C:\USERS
    set WSLENV=Red/p
    ubuntu
```
… will fail to create a Linux environment variable called `Red` or `RED` because the environment variable was created using all upper-case while the entry in the WSLENV string uses mixed-case.

The names 'RED', 'red' and 'Red' identify three different Linux environment variables but only one Windows environment variable name.  In Windows whichever case was used to first define the environment variable will be preserved but all three cases (and other combinations of case) may be used to set or query the environment variable's value.
 
**Note**:  the above was arrived at experimentally using **Windows 10 Insider Preview Build 17704**.  It is possible my experiments are flawed or that my interpretation of the experimental results is flawed.

[1]: https://docs.microsoft.com/en-us/windows/wsl/interop#share-environment-variables-between-windows-and-wsl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea49528-e5c5-4f64-841e-9fe036de304e
* Version Independent ID: edeb7cb5-afcf-1410-4966-f48ce5f6a19a
* Content: [Windows interoperability with Linux](https://docs.microsoft.com/en-us/windows/wsl/interop)
* Content Source: [WSL/interop.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/interop.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by craigloewen-msft** [comment]
Added! Thank you for filing this. https://github.com/MicrosoftDocs/WSL/commit/386d47a1c53a85b91f5a2b0f1f99ce2c46b20a77
