### ISSUE TITLE
AF_Unix windows

### ISSUE THREAD

**Issue by irtazasheikh** [MicrosoftDocs/WSL#224]
I tried the example given in 'af_unix_win_server.cpp' to setup a server over AF_UNIX in windows. 
I am using windows build 17134 and insider preview sdk 17704. 
The issue is that the socket fails to bind with error 10022. I have tired a bunch of things but the provided example doesn't seem to work. Also, I'm linking the ws2_32.lib library to the code.

**Comment by DarthSpock** [comment]
This isn't the right forum. Maybe filing an issue (with tight repro steps) over at https://github.com/Microsoft/wsl/ can help but it's not technically related to WSL either. Best bet is Feedback Hub.
