### ISSUE TITLE
Feature name Microsoft-Windows-Subsystem-Linux is unknown

### ISSUE THREAD

**Issue by mbloem-Steelcase** [MicrosoftDocs/WSL#226]
I get this error when I try to run the command. Any ideas how to fix this?

PS C:\WINDOWS\system32&gt; Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Enable-WindowsOptionalFeature : Feature name Microsoft-Windows-Subsystem-Linux is unknown.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install the Linux Subsystem on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mbloem-Steelcase** [comment]
Hello,

Here’s what version of Windows I’m using:

[cid:image001.png@01D41EDD.0F0330A0]

Best,

Michael

--
Michael Bloem, PhD | Consulting Analyst | Advanced Analytics | Steelcase.com | 650.762.5636

**Comment by bitcrazed** [comment]
@mbloem-Steelcase - don't think images attached to emails survive conversion into GitHub comments - could you either apply your image to the message above, or type the version number? Thanks.

**Comment by bitcrazed** [comment]
1511? That's Threshold 2 - which was released in Nov 2015 ... and is [no longer supported](https://en.wikipedia.org/wiki/Windows_10#Updates_and_support)!! 

Is there a reason you're not running a current and supported version of Win10?

You can't enable WSL on 1511 because _**it's not in 1511**_ - [WSL was first introduced](https://blogs.msdn.microsoft.com/commandline/2016/04/06/bash-on-ubuntu-on-windows-download-now-3/) in April 2016, as a beta feature in Insiders builds released in the lead-up to Win10 1609 (Anniversary Update). WSL has received HUGE updates with each subsequent release, dramatically improving its ability to run ever more Linux tools and binaries. 

* [Windows 10 Creators Update: What’s new in Bash/WSL & Windows Console](https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/)
* [What’s new in WSL in Windows 10 Fall Creators Update](https://blogs.msdn.microsoft.com/commandline/2017/10/11/whats-new-in-wsl-in-windows-10-fall-creators-update/)
* And many of the other posts on our blog: https://blogs.msdn.microsoft.com/commandline

The current latest, supported version of WSL is available in Win10 1803 (Spring 2018 Update), and the next major Win10 release later this year will include yet more improvements and fixes.

If you're going to run WSL, we **_STRONGLY_** encourage you to run the latest version of Windows that you can in order to get the best experience.

**Comment by Crozon29** [comment]
Hi, I have exactly the same command written as @mbloem-Steelcase but I'm running on windows 10 (familial) x64 and with the 1803 version. Can someone help me? 
Thanks!

**Comment by bitcrazed** [comment]
@Crozon29 - are you running Windows 10 LTSB?

Please reply with the (suitably redacted) output of running `systeminfo` from a PowerShell/Cmd prompt.

**Comment by Crozon29** [comment]
Hi @bitcrazed I don't really know, when I run "gwmi win32_operatingsystem | select OperatingSystemSKU" it says 101 so I don't think so. 
I actually managed to run : Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux tonight after several attempts but I don't have the possibility to restart my computer as said in the development to follow. 
I have in output: 
Path:
Online: True
RestartNeeded: False

Thank you for your help and sorry as you can see I am a beginner in this kind of stuff!

**Comment by bitcrazed** [comment]
@Crozon29 `gwmi win32_operatingsystem|select Version` would be more useful ;)

My guess (based on the number of times I've gotten it wrong myself) is that when this failed in the past, you may have omitted the `-Online` argument.

You must be sure to reboot your computer after enabling WSL though: WSL needs to start-up very early in the Windows bootup sequence, before any 3rd party code is loaded, to ensure a solid "chain of trust". Once enabled, you should be able to download and install your chosen distro(s) from the Windows Store.

**Comment by Crozon29** [comment]
@bitcrazed Thank you for the command. 
Unfortunately I used the command " Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux " without omitting the -Online but it doesn't work. 
It's to put in the Bash command (found on the search bar and runned as an admin)?

**Comment by AMKUM78** [comment]
Hi all,
I got following message, any recommendation what to do next:

Enable-WindowsOptionalFeature : The requested operation requires elevation.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

**Comment by AMKUM78** [comment]
Sorry: the answer is to run PowerShell as admin - it does not run by default even if you are the admin - https://superuser.com/questions/1168451/how-can-i-provide-elevation-to-an-operation

**Comment by hoangpx** [comment]
I got the same error 
```
Enable-WindowsOptionalFeature : Feature name Microsoft-Windows-Subsystem-Linux is unknown.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

```
I'm running on Windows Server 2016 Datacenter 64-bit (10.0, Build 14393) (14393.rs1_release.170602-2252)

**Comment by bitcrazed** [comment]
@hoangpx As per [the post announcing WSL on Windows Server](https://blogs.windows.com/buildingapps/2017/08/08/windows-subsystem-linux-windows-server):
> Windows Subsystem for Linux arrived in Windows Server Insider Build 16237

You'll need to update your Server to a more recent build to access WSL.

**Comment by bitcrazed** [comment]
Closing this issue: For anyone else who see's this error, note that you need to be running:

* Windows 10 x64 build 14316 or later (note - LTSB builds do not currently support WSL)
* Windows Server build 16237 or later

For the best WSL experience, we encourage you to run the most recent build of Windows that you can since WSL has improved CONSIDERABLY since its early releases.

**Comment by hiperriper** [comment]
> Closing this issue: For anyone else who see's this error, note that you need to be running:
> 
> * Windows 10 x64 build 14316 or later (note - LTSB builds do not currently support WSL)
> * Windows Server build 16237 or later
> 
> For the best WSL experience, we encourage you to run the most recent build of Windows that you can since WSL has improved CONSIDERABLY since its early releases.

hello. i have a same problem.
I use 17763 insider prew build. And could not turn on case sensitive feature

**Comment by juso** [comment]
Same issue on Windows 10 Pro 10.0.17134. WSL is missing in "turn windows features on and off" as well as getting the error as in the OP message.

**Comment by bitcrazed** [comment]
@Juso - Are you running Windows 10 LTSB?

**Comment by juso** [comment]
@bitcrazed - no, it's not LTSB to my understand
```
PS C:\> gwmi win32_operatingsystem | select OperatingSystemSKU

OperatingSystemSKU
------------------
                48
```
and value at **HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProductName** is **Windows 10 Pro**

**Comment by Adarshreddyash** [comment]
Same problem here !

**Comment by cmprima** [comment]
Same issues here:

<gwmi win32_operatingsystem | select OperatingSystemSKU

OperatingSystemSKU
------------------
                48
>

<Betriebsystemname	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134

Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

Enable-WindowsOptionalFeature : Der Featurename "Microsoft-Windows-Subsystem-Linux" ist 
unbekannt.
>

**Comment by baselbj** [comment]
Same here also

**Comment by eNipu** [comment]
Having similar issue in
Windows 10 Pro, Version 1903. OS build: 18362.295 
```
Enable-WindowsOptionalFeature : Feature name Mircrosoft-Windows-Subsystem-Linux is unknown.
At line:1 char:1
+ Enable-WindowsOptionalFeature -online -FeatureName Mircrosoft-Windows ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
```

**Comment by craigloewen-msft** [comment]
@eNipu could you try using the GUI approach to install WSL? Open the start menu and search for `Turn Windows Features On or Off` and then check the `Windows Subsystem for Linux` option. 

If that doesn't work please open an issue on our WSL Github repo: https://github.com/microsoft/wsl/issues and we will help you out there.

**Comment by eNipu** [comment]
> @eNipu could you try using the GUI approach to install WSL? Open the start menu and search for `Turn Windows Features On or Off` and then check the `Windows Subsystem for Linux` option.
> 
> If that doesn't work please open an issue on our WSL Github repo: https://github.com/microsoft/wsl/issues and we will help you out there.

Fixed the problem for GUI. Thanks !

**Comment by jerrycaffe** [comment]
Windows Subsystem for Linux is not listed in the turn windows On or Off dialogue box

**Comment by bitcrazed** [comment]
@eNipu - just spotted that you're trying to install `Mircrosoft-Windows-Subsystem-Linux` ... which is mis-spelled.

Please run the following from an elevated PowerShell Console/Terminal: 

`Enable-WindowsOptionalFeature -Online -FeatureNameMicrosoft-Windows-Subsystem-Linux`

**Comment by bitcrazed** [comment]
@jerrycaffe What build/SKU of Windows are you running?

**Comment by vixalien** [comment]
Hey I have the problem, too, this is what happens when I run `systeminfo`

```
Host Name:                 ALIENMACHINE
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00331-10000-00001-AA033
Original Install Date:     3/27/2020, 6:29:23 AM
System Boot Time:          4/15/2020, 1:07:57 AM
System Manufacturer:       Hewlett-Packard
System Model:              HP ProBook 6450b
System Type:               X86-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: x64 Family 6 Model 37 Stepping 5 GenuineIntel ~2400 Mhz
BIOS Version:              Hewlett-Packard 68CDE Ver. F.03, 10/4/2010
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-gb;English (United Kingdom)
Time Zone:                 (UTC+02:00) Cairo
Total Physical Memory:     2,991 MB
Available Physical Memory: 257 MB
Virtual Memory: Max Size:  12,207 MB
Virtual Memory: Available: 6,009 MB
Virtual Memory: In Use:    6,198 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\ALIENMACHINE
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB4534170
                           [02]: KB4537759
                           [03]: KB4545706
                           [04]: KB4541738
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) 82577LC Gigabit Network Connection
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Broadcom 4313 802.11b/g/n
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.8.1
                                 IP address(es)
                                 [01]: 192.168.8.113
                                 [02]: fe80::d193:1076:4f7a:d19b
                                 [03]: fd90:2bd2:2993:7200:75cc:2e41:d01a:2e0c
                                 [04]: fd90:2bd2:2993:7200:d193:1076:4f7a:d19b
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: No
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```

**Comment by sambragg** [comment]
Having this same issue, I am running LTSC in Bootcamp:
```PS C:\Windows\system32> gwmi win32_operatingsystem|select Version

Version
-------
10.0.17763

**Comment by bitcrazed** [comment]
@sambragg According to [the LTSC page](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/), you're not running LTSC:

LTSC release | Equivalent SAC release | Availability date
-- | -- | --
Windows 10 Enterprise 2015 LTSC | Windows 10, Version 1507 | 7/29/2015
Windows 10 Enterprise 2016 LTSC | Windows 10, Version 1607 | 8/2/2016
Windows 10 Enterprise 2019 LTSC | Windows 10, Version 1809 | 11/13/2018

17763 was the fall 2018 Win10 release. 

If you copy this: `Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`, and paste it into an ELEVATED Terminal, you should see something like the following:

![image](https://user-images.githubusercontent.com/961950/80252077-7f8ec480-862b-11ea-9d3d-a2faa0c3bbb9.png)

If not, please follow @craigloewen-msft's instructions [above](https://github.com/MicrosoftDocs/WSL/issues/226#issuecomment-523546280).

**Comment by gibsonjc1** [comment]
@bitcrazed I'm having a similar issue... running Server 2106 latest build:



![2020-04-24 15_51_43-ta-jump1 - Remote Desktop Connection](https://user-images.githubusercontent.com/40771787/80264149-fdf95f80-8647-11ea-8bb5-e7ffad62acd9.png)

**Comment by bitcrazed** [comment]
@gibsonjc1 - Windows Server 2016 was released before WSL was first released (fall 2017).

**Comment by allencarvallo** [comment]
Sir

But in turn on/off windows features, the box for Windows Subsystem for
Linux was not there

**Comment by craigloewen-msft** [comment]
I think we'd need more info to solve the problem then. Could you please open an issue on the official WSL repo [here](https://github.com/microsoft/WSL/issues/new?assignees=&labels=&template=bug_report.md&title=) describing your problem? 

Thanks!

**Comment by madhakun** [comment]
> Closing this issue: For anyone else who see's this error, note that you need to be running:
> 
> * Windows 10 x64 build 14316 or later (note - LTSB builds do not currently support WSL)
> * Windows Server build 16237 or later
> 
> For the best WSL experience, we encourage you to run the most recent build of Windows that you can since WSL has improved CONSIDERABLY since its early releases.

i have same issue but i run it in Windows 10 x32 build 19042

**Comment by madhakun** [comment]
> @eNipu could you try using the GUI approach to install WSL? Open the start menu and search for `Turn Windows Features On or Off` and then check the `Windows Subsystem for Linux` option.
> 
> If that doesn't work please open an issue on our WSL Github repo: https://github.com/microsoft/wsl/issues and we will help you out there.

i don't have `Windows Subsystem for Linux` option there

**Comment by bermudezmt** [comment]
Hello, I'm running into the same issue and am trying the GUI method with the following selections:

**Role-based or feature-based installation** > Microsoft Windows Server 2016 OS (for the Server Pool)

I don't see Windows Subsytem for Linux there either.
