### ISSUE TITLE
packages installed in windows using pip are not able to be accessed in subsystem

### ISSUE THREAD

**Issue by saitejach127** [MicrosoftDocs/WSL#229]
Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

**Comment by mscraigloewen** [comment]
For any WSL specific issues please file them at [the WSL repo](https://github.com/microsoft/wsl). This repo is only for issues with the documentation. Thanks!
