### ISSUE TITLE
Duplicate question

### ISSUE THREAD

**Issue by YisroelTech** [MicrosoftDocs/WSL#232]
The admin requirement issue for Ping is repeated twice: "Why does ping require admin privileges?" and "Why do I get a Permission Denied error when using ping?" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd5bfb4-8a38-1f09-0d36-6b9abe9b8b08
* Version Independent ID: 156d9535-c2a5-bc8d-af24-342a13832abf
* Content: [Frequently Asked Questions (FAQ)](https://docs.microsoft.com/en-us/windows/wsl/faq)
* Content Source: [WSL/faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/faq.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
This looks fixed to me, I only see ping mentioned once in the docs.
