### ISSUE TITLE
Enabling WSL feature fails; unclear which channel to submit that feedback.

### ISSUE THREAD

**Issue by maphew** [MicrosoftDocs/WSL#233]
I get stopped at the first step, enabling the WSL optional feature. It's unclear to me which Feedback channel is/was the most appropriate, [Product Feedback] or [Content feedback]. I chose 'product' and opened https://github.com/Microsoft/WSL/issues/3413. Feel free to close that and ask me to follow up here if this is the more correct channel.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install the Linux Subsystem on Windows 10](https://docs.microsoft.com/en-ca/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by DarthSpock** [comment]
your created issue was the proper way to get the issue addressed. Feedback Hub would be good when discussing features as well as UserVoice for features not yet supported (Be sure to check if an idea already exists before creating one)

**Comment by mscraigloewen** [comment]
For any WSL specific issues please file them at [the WSL repo](https://github.com/microsoft/wsl). This repo is only for issues with the documentation. Thanks!
