### ISSUE TITLE
Step 1 of "Extract and install a Linux distro fails"

### ISSUE THREAD

**Issue by timothies** [MicrosoftDocs/WSL#241]
On Windows Server 2019 the command "Expand-Archive ~/Ubuntu.appx ~/Ubuntu"  fails as .appx is not a supported file format.
It can be changed to a .zip and then Expand-Archive will work (as pointed out by @therealkenc).    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install the Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-on-server.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
This is now reflected in the documentation. Thank you!
