### ISSUE TITLE
lxrun instructions

### ISSUE THREAD

**Issue by swert-hon** [MicrosoftDocs/WSL#243]
The lxrun instructions referred to at the top of this page were wiped out in a [recent commit](https://github.com/MicrosoftDocs/WSL/commit/26e532ca9c3407742a0fd2061a26987b333f382e#diff-38a0140e4b75406b7b199c0e21b2428a), leaving a dead link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by TheDarkerPhantom** [comment]
The correct link is https://docs.microsoft.com/en-us/windows/wsl/install-legacy
