### ISSUE TITLE
Include an example for the "WSLENV" environment variable

### ISSUE THREAD

**Issue by JaimeChavarriaga** [MicrosoftDocs/WSL#244]
An example of the `WSLENV` is missing in the [Share environment variables between Windows and WSL](https://docs.microsoft.com/en-us/windows/wsl/interop#share-environment-variables-between-windows-and-wsl). The documentation may include examples such as the presented in the ["Windows Command Line" blog post](https://blogs.msdn.microsoft.com/commandline/2017/12/22/share-environment-vars-between-wsl-and-windows/). The FAQ included in that blog post can be also included here.

---
For instance, a WSLENV could be something like this:
- `WSLENV=FORWSL/u:FORWIN/w:GOPATH/l:TMPDIR/p`

In the example,
- the `FORWSL` variable is included in the WSL linux environment when it is invoked from Windows.
- `FORWIN` is included in the environment for Windows commands when they are invoked from WSL Linux.
- `GOPATH` is a list of paths shared in both environments. The list elements are separated by `:` in Windows and `;` in Linux.
- `TMPDIR` is a path shared in both environments. It must be translated from Windows to WSL paths, e.g., `C:\Users` in Windows must be translated to `/mnt/c/Users` in WSL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea49528-e5c5-4f64-841e-9fe036de304e
* Version Independent ID: edeb7cb5-afcf-1410-4966-f48ce5f6a19a
* Content: [Windows interoperability with Linux](https://docs.microsoft.com/en-us/windows/wsl/interop#share-environment-variables-between-windows-and-wsl)
* Content Source: [WSL/interop.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/interop.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by datocrats-org** [comment]
More info on how the path translation flags work would help too. This should be included in the example.
```sh {cmd.exe}
set USERNAME
USERNAME=MyUsername
set WSLENV=USERNAME/p 
wsl -e "echo $USERNAME"
/MyUsername
```
Note when the default Windows %USERNAME% is translated to WSL it shows up as being prefixed with `/`

**Comment by beltaurus** [comment]
I have the same desire for some practical use examples;
**I can not figure out the difference between the '/l' flag and the 'p' flag:**
Both of them will take single directories or a list of directories, and transform the path syntax as well as the separator correctly:
![image](https://user-images.githubusercontent.com/54114043/78949253-ecc52600-7a7f-11ea-8e99-add1665c3458.png)
![image](https://user-images.githubusercontent.com/54114043/78949362-25fd9600-7a80-11ea-85b8-97d2d676c460.png)


So I was experimenting with just 'lists' (no directories); but now the flags reduces the content to blank (testing the export of environment variables from Win to WSL):
![image](https://user-images.githubusercontent.com/54114043/78948935-d8ccf480-7a7e-11ea-8e75-5d0714960b7e.png)

**Comment by craigloewen-msft** [comment]
We now include a section with details on WSLENV and a link to a blog post with examples! 

https://docs.microsoft.com/en-us/windows/wsl/interop#wslenv-flags

**Comment by ivanstepanovftw** [comment]
batch: works
```batch
C:\Users\Ivan>set HI=hello
C:\Users\Ivan>wsl echo $HI

C:\Users\Ivan>set WSLENV=HI
C:\Users\Ivan>wsl echo $HI
hello
```
Powershell: does not works
```shell
PS C:\Users\Ivan> $env:HI = "hello"
PS C:\Users\Ivan> wsl echo $HI

PS C:\Users\Ivan> $env:WSLENV = "HI"
PS C:\Users\Ivan> wsl echo $HI

```

**Comment by ivanstepanovftw** [comment]
Could you please provide instructions for powershell users?

**Comment by wzis** [comment]
From which file can we set the values for the FORWSL/u as we need to include other paths for the WSL?
