### ISSUE TITLE
Please Update

### ISSUE THREAD

**Issue by cgray-ncsoft** [MicrosoftDocs/WSL#245]
Please update to include the Ubuntu 18.04.1 LTS build that's available on the store, and please add the Debian uri.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by tara-raj** [comment]
Ubunutu 18.04 updated here - https://docs.microsoft.com/en-us/windows/wsl/install-manual

**Comment by rhaist** [comment]
Debian is now available.

**Comment by janhoeve** [comment]
The included certificate for "Ubuntu 18.04" seems invalid, so I cannot install it on my PC @ work.
When inspecting the Digital Signatures, I get the msg: Root certificate is not trusted.
Please have a look :)

Ubuntu 16.04 seems to be valid though.

**Comment by tara-raj** [comment]
The Ubuntu 18.04 link has been updated. Should be fine now (cert was off). Debian and Kali are also now live. Thanks for the feedback everyone! Closing this issue. Please re-open if you hit additional problems

**Comment by AlisterH** [comment]
Should there also be a link for a plain "Ubuntu"?  "Ubuntu 18.04" installs an ubuntu1804.exe, rather than an ubuntu.exe
Or can the exe just be renamed or something?
