### ISSUE TITLE
The "visit the command reference" links to a deprecated command

### ISSUE THREAD

**Issue by JaimeChavarriaga** [MicrosoftDocs/WSL#246]
The "about" page has a link (visit the command reference) that points to documentation of the `lxrun` deprectaed documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3be148fb-e4a9-83b5-5b5a-7834eed7052f
* Version Independent ID: f583bc11-fe60-bb2c-af2b-dc0dae9fe81f
* Content: [Learn about the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about)
* Content Source: [WSL/about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/about.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
Fixed!
