### ISSUE TITLE
For Fall Creators Update and later only for Ubuntu

### ISSUE THREAD

**Issue by Boltzmann** [MicrosoftDocs/WSL#247]
I'd like to recover my password for openSUSE subsystem. However, this article does not help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Linux User Account and Permissions](https://docs.microsoft.com/en-us/windows/wsl/user-support)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/user-support.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
You can now run as the root user using `wsl -u root` and that will let you modify user accounts which will be the easiest way to restore a password. Please see [the reference page](https://docs.microsoft.com/en-us/windows/wsl/reference) for details.
