### ISSUE TITLE
please fix OpenSUSE Leap 42 default user logic

### ISSUE THREAD

**Issue by absente** [MicrosoftDocs/WSL#248]
the default init config need to create a new user. However, after you create one, you don't have the root password for grant to the sudo level. And then, the lxrun is deprecated after version 1803, and you need to type `opensuse-42.exe` and to run its config operation for cmd.
Moreover, for now, its the best way to first close the shell when it ask you to create a user at initial. And then you will login as root account, so that you can change root password and then create a new user.

The main problem is, not anywhere the docs tells you the exactly name of OpenSUSE，you should find it from taskmgr detail by yourself.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Linux User Account and Permissions](https://docs.microsoft.com/zh-cn/windows/wsl/user-support)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/user-support.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
The WSL team does not control the initialization logic of OpenSUSE. However I am able to access root user after creating an account, so I'm unable to repro your issue. 

For any WSL specific issues please file them at [the WSL repo](https://github.com/microsoft/wsl). This repo is only for issues with the documentation. Thanks!
