### ISSUE TITLE
unable to install despite following above instructions

### ISSUE THREAD

**Issue by ricky8077** [MicrosoftDocs/WSL#254]
Hey guys, I have enabled the developer options on my windows but the cmd still doesn't recognize the bash command. What to do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df13cc0f-9f70-c507-d70d-ed8b3c4735ea
* Version Independent ID: 821b82b7-5b0a-ec6c-4a89-cf58843f66a8
* Content: [Install or remove the Linux Subsystem on Windows 10 Anniversary Update or Creators Update](https://docs.microsoft.com/en-us/windows/wsl/install-legacy)
* Content Source: [WSL/install-legacy.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-legacy.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by mscraigloewen** [comment]
Please refer to the [latest install instructions](https://docs.microsoft.com/en-us/windows/wsl/install-win10).
