### ISSUE TITLE
Feature request: `rm` integration with Windows FS Recycle Bin

### ISSUE THREAD

**Issue by vitorsr** [MicrosoftDocs/WSL#257]
Or really an alternative command that'd do just that. Or am I being naïve?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by mscraigloewen** [comment]
This is a WSL feature request. It's something that isn't currently implemented. For any WSL specific issues please file them at [the WSL repo](https://github.com/microsoft/wsl) and we'll follow up with you there! This repo is only for issues with the documentation. Thanks!
