### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by thegrizz** [MicrosoftDocs/WSL#259]
on startup of ubuntu i get error 8007019e and no idea as to a cause

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting the Windows Susbystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#feedback)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/troubleshooting.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
For any WSL specific issues please file them at [the WSL repo](https://github.com/microsoft/wsl) and we'll follow up with you there! This repo is only for issues with the documentation. Thanks!
