### ISSUE TITLE
Cyclical dependency

### ISSUE THREAD

**Issue by Vitali-Dettling** [MicrosoftDocs/WSL#265]
Installation leads to the previouse page and the previous page leads to this one without showing how to install via powershell. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by aes-grave** [comment]
Try this

add-appxpackage C:\path-to-app.appx

**Comment by repdetec04** [comment]
This 'add-appxpackage' command is what was missing from the official instructions and worked for me. thank you.

**Comment by Cacadril** [comment]
This problem struck me too. This page says "For instructions on how to install your downloaded distro(s), please refer to the Windows Desktop or Windows Server installation instructions." But the page linked to as "Windows Desktop" does not tell what to do with the downloaded file. It just refers to this page if you don't want or can't use the Store to download the package. Then it tells you what to do AFTER you have installed the download.

The Server page, however, does instruct you to rename the download with a ".zip" extension and then user powershell to unpack it. I guess that the desktop versions of windows require add-appxpackage instead.

**Comment by vladimirhasko** [comment]
I have same issue, Windows 10 version 1607 build 14393.2368.
We don't have windows store as it's company's policy.
When installing the Ubuntu linux manually I'm able to enable linux subsystem:
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
but I'm not able to install manually downloaded distribution (tried Ubuntu 18.04 and Ubuntu 16.04)
When tried to use:
PS C:\Distros> Add-AppxPackage .\Ubuntu-1604.appx
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.
Deployment Add operation with target volume C: on Package
CanonicalGroupLimited.UbuntuonWindows_1604.2017.711.0_x64__79rhkp1fndgsc from:  (Ubuntu-1604.appx)  failed with error
0x80073CFD. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
NOTE: For additional information, look for [ActivityId] bb5f4b3b-b22b-0002-6a8d-5fbb2bb2d401 in the Event Log or use
the command line Get-AppxLog -ActivityID bb5f4b3b-b22b-0002-6a8d-5fbb2bb2d401
At line:1 char:1
+ Add-AppxPackage .\Ubuntu-1604.appx
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Distros\Ubuntu-1604.appx:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
When tried to rename it to zip and install manually via Ubuntu.exe
then I got:
PS C:\Distros\Ubuntu> .\ubuntu1804.exe
The Windows Subsystem for Linux optional component is not enabled. Please enable it and try again.
See https://aka.ms/wslinstall for details.
Press any key to continue...

but Linux subsystem is enabled:
PS C:\Distros\Ubuntu> Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux


FeatureName      : Microsoft-Windows-Subsystem-Linux
DisplayName      : Windows Subsystem for Linux (Beta)
Description      : Provides services and environments for running native user-mode Linux shells and tools on Windows.
RestartRequired  : Required
State            : Enabled
CustomProperties :

Any idea where can be an issue?

**Comment by LeslieGerman** [comment]
Hi @vladimirhasko,

On your build probably only the "legacy" fixed-distro WSL is available.
See section "Troubleshooting" [on this page:](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)

> You're running Windows build 16215 or later.

Try the [`lxrun` command line utility](https://docs.microsoft.com/en-us/windows/wsl/reference) instead.

**Comment by valerysntx** [comment]
@vladimirhasko
>  Any idea where can be an issue?
...
"RestartRequired : Required"

**Comment by phillipjohnston** [comment]
@craigloewen-msft: Why is this closed when it is still happening? The documentation should at least be updated if the steps need to change. I can reproduce on 11/13.

**Comment by craigloewen-msft** [comment]
@philipjohnston what issue are you running into?

This issue page is referring to the fact that the documentation used to be cyclical (one page pointed you to a page that pointed you back to the same page), which we've now changed to have clearer instructions, which is why this issue is now closed.
