### ISSUE TITLE
where is distro installation folder

### ISSUE THREAD

**Issue by skierpage** [MicrosoftDocs/WSL#268]
"you can launch your distro's launcher executable &lt;distro&gt;.exe from the distro installation folder." But how do I find this? In desktop Windows I had to run a command prompt as administrator, then `cd \Program Files\WindowsApps`, and in there I found a folder for Debian GNU/Linux that I installed from the Windows Store (TheDebianProject.DebianGNULinux_1.1.4.0_x64__76v4gfsz19hv4). Rather than give all these instructions, maybe link to documentation on finding a Windows Store app's folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Initialize a new WSL Linux distro](https://docs.microsoft.com/en-us/windows/wsl/initialize-distro)
* Content Source: [WSL/initialize-distro.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/initialize-distro.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by skierpage** [comment]
This is a duplicate of #251 (where I added my workaround as a comment). I ran into the problem on a different doc page.

**Comment by webtop** [comment]
Your distro appears as a start menu item, so for ease-of-access you can simply pin it to the taskbar.

**Comment by bitcrazed** [comment]
Closing since there's no more to do here.
