### ISSUE TITLE
Other computer in LAN can not access WSL?

### ISSUE THREAD

**Issue by zhidelin** [MicrosoftDocs/WSL#273]
compuer 1 and WSL ip: 192.168.1.100, WSL have public port 5000, 
compuer 2 ip: 192.168.1.101, can not access WSL port 5000.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9bd5bfb4-8a38-1f09-0d36-6b9abe9b8b08
* Version Independent ID: 156d9535-c2a5-bc8d-af24-342a13832abf
* Content: [Frequently Asked Questions (FAQ)](https://docs.microsoft.com/zh-cn/windows/wsl/faq)
* Content Source: [WSL/faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/faq.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by redbrick1357** [comment]
@zhidelin, just trying to rule out the Windows Firewall (on computer 1): have you opened the port in the Windows Firewall?

**Comment by praveenmak** [comment]
Hi,
I am using Windows 10 Enterprise.

PS C:\> systeminfo | Select-String "^OS Name","^OS Version"
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18362 N/A Build 18362

When I run this wsl -l -v (it shows a help page)
And when I run wsl --export .. ( it says "access denied").

Can you please help?

**Comment by craigloewen-msft** [comment]
WSL has gone through many updates and revisions, and this issue may be fixed in the latest version. We're cleaning out some of our older issues, and will mark this as closed. If you are still experiencing this issue on the latest version please feel free to reopen this! Thank you!
