### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by LuyiLi** [MicrosoftDocs/WSL#276]
I type down the update commands in the guide then Ubuntu went like this:

root@DESKTOP-528A0LA:~# sudo apt update && sudo apt upgrade
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
  403  Forbidden [IP: 111.11.80.233 80]
Err:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  403  Forbidden [IP: 111.11.80.233 80]
Err:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  403  Forbidden [IP: 111.11.80.233 80]
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists... Done
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic InRelease' is no longer signed.
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  403  Forbidden [IP: 111.11.80.233 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  403  Forbidden [IP: 111.11.80.233 80]
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-updates InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  403  Forbidden [IP: 111.11.80.233 80]
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Does it have something to do with vpn? Not many seemed to come across this problem

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting the Windows Susbystem for Linux](https://docs.microsoft.com/zh-cn/windows/wsl/troubleshooting)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/troubleshooting.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by shaswat-dharaiya** [comment]
Having the same issue

**Comment by shaswat-dharaiya** [comment]
Try changing the network, like from wifi to hotspot. It worked for me.

**Comment by Berrysoft** [comment]
Try mirrors like [tuna](https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/).

**Comment by LuyiLi** [comment]
I solved the issue by changing the network. Then it worked out. Many thanks.
