### ISSUE TITLE
First step

### ISSUE THREAD

**Issue by devadingdong** [MicrosoftDocs/WSL#277]
The stated process to enable the Windows subsystem for Linux is broken
1- go to settings &gt;update and security 
2- under &gt;for developers enable developer mode
Open control panel and go to programs
1- enable and disable programs option
2- enable windows subsystem for Linux
it will look online for packages and prompt for restart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by EmilyCrossette** [comment]
When I run `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux` I get an error "The requested operation requires elevation" I tried the steps above but get the same error. I am the administrator of my system.

**Comment by kennethjf** [comment]
I'm running PowerShell as administrator, but WSL can't be found:

PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Enable-WindowsOptionalFeature : The referenced assembly could not be found.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

Please advise

**Comment by benjibex** [comment]
Thanks devadingdong, the only change for me is that in Programs in Control panel my option is called Turn Windows features on and off.

**Comment by mattwojo** [comment]
We've updated the WSL install instructions, please try them again and see if your issue is resolved. Closing this, but if it appears that this is still an issue, please re-open.
