### ISSUE TITLE
Include a note about shutting down any running instance of WSL

### ISSUE THREAD

**Issue by bryder** [MicrosoftDocs/WSL#290]
I had ubuntu running when I changed the default user to root from a separate CMD instance. 

When I started up ubuntu from CMD it logged me in as the original default user.

I had to shut down the other running instance of ubuntu before the default user change took effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Linux User Account and Permissions](https://docs.microsoft.com/en-us/windows/wsl/user-support)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/user-support.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mattwojo** [comment]
Thanks @bryder. I just tried to reproduce and from what I can tell this is no longer an issue. Closing, but please reopen if you still find this issue to be true and in need of documentation. 
Thanks again for contributing! (and appologies this took so long to respond to -- doing my best to catch up on these past WSL doc issues) ~Matt
