### ISSUE TITLE
Translations 🌐

### ISSUE THREAD

**Issue by 73VW** [MicrosoftDocs/WSL#291]
Hello everyone,

It is sad that this documentation isn't available in other languages. 😿 

I can work a bit on French translation if you tell me how to start.

I really would like to help on this because (of Hacktoberfest first 😉) this is a great tool and I really appreciate it. 🎉 

Have a nice day!

**Comment by howiezhao** [comment]
I can work a bit on Chinese translation

**Comment by mscraigloewen** [comment]
Translations are available, please look at the bottom left of the page and you can select your language for the documentation.
