### ISSUE TITLE
rm -Recurse $env:localappdata/lxss/ does not uninstall kali or ubuntu subsystems

### ISSUE THREAD

**Issue by hingston** [MicrosoftDocs/WSL#300]
Following all instructions on https://docs.microsoft.com/en-us/windows/wsl/install-legacy does not uninstall Kali or Ubuntu on Windows Version 10.0.17763 Build 17763.

```
PS C:\WINDOWS\system32> rm -Recurse $env:localappdata/lxss/
rm : Cannot find path 'C:\Users\Will\AppData\Local\lxss\' because it does not exist.
At line:1 char:1
+ rm -Recurse $env:localappdata/lxss/
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Will\AppData\Local\lxss\:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df13cc0f-9f70-c507-d70d-ed8b3c4735ea
* Version Independent ID: 821b82b7-5b0a-ec6c-4a89-cf58843f66a8
* Content: [Install or remove the Linux Subsystem on Windows 10 Anniversary Update or Creators Update](https://docs.microsoft.com/en-us/windows/wsl/install-legacy)
* Content Source: [WSL/install-legacy.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-legacy.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by NickChlam** [comment]
best way to do this is to 

show what distros you have installed -
wslconfig /list /all

unregister that distro 
wslconfig /unregister <DistributionName>

this will delete the distro and all user data including anything you installed
source: https://docs.microsoft.com/en-us/windows/wsl/wsl-config

**Comment by prof79** [comment]
@hingston I do not understand your point - the doc/section explicitly talks about WSL legacy which was an early version with different mechanisms. Kali and the new Ubuntu are proper Store/WSL-based apps and should be able to be properly uninstalled by their shortcut context menus and/or "Apps and Features". Alternatively use the WSL tools as @NickChlam explained, kudos to him.
Your Windows version is 1809. They are talking about a beta/preview version of WSL included BEFORE 1709. So if you hadn't a version earlier 1709 with WSL you upgraded from then you have no legacy WSL/this does not apply to you.
I suspect you may have misread or misunderstood the article, In my opinion a change of the article/section is not warranted.
