### ISSUE TITLE
Needs some documentation of how to install duplicates of distros

### ISSUE THREAD

**Issue by henrik-jensen** [MicrosoftDocs/WSL#301]
When using VMs it's usually easy to just install a base distro and then "fork" that same distro into several branches, (e.g. "**base** 'DistroName 123 LTS'  vm", "WebDevStack vm based on **base**", "Wild experiment 1 based on **WebDevStack**", "Wild experiment 2 ... etc.).

How is that accomplished with wsl? The Windows Store does not give a possibility to install a new copy of a distro if you've already installed it, just gives the opportunity to start the distro.

Note:
I did find a 3rd party tool, [LxRunOffline](https://github.com/DDoSolitary/LxRunOffline), claiming to do this, but I would prefer there was some 1st party documentation and tools to accomplish this. ([Found through this SO question ](https://stackoverflow.com/questions/51584765/how-do-you-install-multiple-separate-instances-of-ubuntu-in-wsl) which also presents another method siting [WSL-DistroLauncher](https://github.com/Microsoft/WSL-DistroLauncher))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by craigloewen-msft** [comment]
This is now possible using `wsl --import` and `wsl --export`!

You can find my personal instructions on setting this up here: https://craigloewen-msft.github.io/WSLTipsAndTricks/tip/duplicate-distro.html

**Comment by henrik-jensen** [comment]
@craigloewen-msft 👍 
Yeah,- thanks,- import/export has really been an excellent addition to wsl. Here is a lot of 👍 👍 👍 and a 🥇 to the devs from me.
