### ISSUE TITLE
Include `sc stop LxssManager` and `sc start LxssManager` in docs

### ISSUE THREAD

**Issue by dfoverdx** [MicrosoftDocs/WSL#302]
`ubuntu config --set-default-user root` did not work for me until I reset the `LxssManager` service.  It would be helpful if this article mentioned that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Linux User Account and Permissions](https://docs.microsoft.com/en-us/windows/wsl/user-support)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/user-support.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by shellfyred** [comment]
👍 thank you for this @dfoverdx. I ran into this issue as well on 1803, fwiw.

**Comment by craigloewen-msft** [comment]
WSL has gone through many updates and revisions, and this issue may be fixed in the latest version. We're cleaning out some of our older issues, and will mark this as closed. If you are still experiencing this issue on the latest version please feel free to reopen this! Thank you!
