### ISSUE TITLE
Correct typo

### ISSUE THREAD

**Issue by pldg** [MicrosoftDocs/WSL#303]
`Rename-Item ~/Ubuntu.appx ~/Ubuntu.zip` print out an error: `Rename-Item : Cannot rename the specified target, because it represents a path or device name.` - It should be changed to `Rename-Item ~/Ubuntu.appx Ubuntu.zip`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install the Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-on-server.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by domoaligato** [comment]
I also incurred this issue with the instructions being wrong. it should be a period not a tilda

**Comment by mscraigloewen** [comment]
Fixed these changes to show `./Ubuntu.appx` , not `~/Ubuntu.appx`. Thanks for filing this!
