### ISSUE TITLE
I got Windows10Pro Build 18272.rs_prerelease.181026-1425 and now bash wont start

### ISSUE THREAD

**Issue by fenchu** [MicrosoftDocs/WSL#304]
Hi when I start bash.exe I get the following:
PS C:\Users\morten.sensio&gt; bash.exe
Det er ingen støtte for dette grensesnittet
(translated: No support for this interface)

I've tries removing my $env:localappdata/lxss/
and both installing ubuntu 16.04 and ubuntu 18.04 from windows appstore: same error:
Installing, this may take a few minutes...
Det er ingen støtte for dette grensesnittet
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: mortenb
Det er ingen støtte for dette grensesnittet
Enter new UNIX username: morten
Det er ingen støtte for dette grensesnittet
Enter new UNIX username:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df13cc0f-9f70-c507-d70d-ed8b3c4735ea
* Version Independent ID: 821b82b7-5b0a-ec6c-4a89-cf58843f66a8
* Content: [Install or remove the Linux Subsystem on Windows 10 Anniversary Update or Creators Update](https://docs.microsoft.com/en-us/windows/wsl/install-legacy)
* Content Source: [WSL/install-legacy.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-legacy.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by MaximoTrinidad** [comment]
Known Issue! https://github.com/MicrosoftDocs/WSL/issues/308

Proceed to the next Windows 1o Insider Build 18277.  It's working again!\
:)
