### ISSUE TITLE
Fail to create new account with "No such interface supported" message

### ISSUE THREAD

**Issue by rdcoe** [MicrosoftDocs/WSL#306]
I am repeatedly being told that I have "No such interface supported" when launching Ubuntu Bash.  I just reset Windows, hoping to fix that problem.  Now, with a clean 18272 build, I cannot create a new UNIX username.  The Bash shell responds with that message.  When I close the Bash window, I can not reopen it.  It immediately closes.  No error message is displayed.

I had been using Ubuntu successfully until the last Fast Ring push this past weekend.  There seems to be no fix, if a clean reinstallation doesn't fix the problem.

This is a serious show stopper.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by garytube** [comment]
https://github.com/MicrosoftDocs/WSL/releases/tag/18272
