### ISSUE TITLE
Error: 0x8007001

### ISSUE THREAD

**Issue by ArsenioDev** [MicrosoftDocs/WSL#307]
When I try to follow this for any of the distros, all I get is the following
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070001
Error: 0x80070001 Incorrect function.

Press any key to continue...

I'm unable to download via the store due to lacking a stable internet connection at deployment location 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install the Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-on-server.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by dazhoudotnet** [comment]
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070001
Error: 0x80070001 Incorrect function.

Press any key to continue...

**Comment by kitingChris** [comment]
Same for me. Tried to install it on a Windows Server 2019

**Comment by larde** [comment]
Same Issue on Windows Server 2019. I have followed https://docs.microsoft.com/en-us/windows/wsl/install-on-server

**Comment by mscraigloewen** [comment]
This repo is for issues with the Microsoft Docs, could you please collect some detailed logs (Instructions [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs)) and post this issue on the WSL repo page: https://github.com/microsoft/wsl

Thank you!
