### ISSUE TITLE
Ubuntu1804 stopped working after Windows 10 Insider update to Build 18272

### ISSUE THREAD

**Issue by MaximoTrinidad** [MicrosoftDocs/WSL#308]
Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

Unfortunately I can't use "Settings" application "Repair" or "Reset".  

I also tried to do "Uninstall" and "Install" Ubuntu 18.04.

In both "Reset" or "Install", now I'm getting a following message when entering a new UNIX username:
```
No such interface supported
```
All this happened when upgrading Windows 10 Insider version to build 18272.

![ubuntu1804_msg_2018-11-06_22-41-26](https://user-images.githubusercontent.com/19892435/48109370-34091080-e215-11e8-9f92-ed366bca98c8.jpg)

**Comment by garytube** [comment]
You need to rollback or wait a week for the fix

https://github.com/MicrosoftDocs/WSL/releases/tag/18272

**Comment by MaximoTrinidad** [comment]
I can wait for the next upgrade. 
For what I use it for... everything can be rebuild in a couple of hours.

Thanks for the update!  

:)

**Comment by MaximoTrinidad** [comment]
Yes!! Windows Insider update to Build 18277 did fix the issue for WSL.
Unfortunately, I had to re-install WSL as I did a "reset" prior the build that did work.  

It work this time!
:)

**Comment by MaximoTrinidad** [comment]
I'm closing this issue!
