### ISSUE TITLE
Instructions do not work on my system

### ISSUE THREAD

**Issue by zenntenn** [MicrosoftDocs/WSL#309]
Does not work.  I have Ubuntu installed and can run it by running bash.exe, but there is no lxrun command, nor is there a lxss folder (or bash, or ubuntu, or wsl folder) in %localappdata%

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df13cc0f-9f70-c507-d70d-ed8b3c4735ea
* Version Independent ID: 821b82b7-5b0a-ec6c-4a89-cf58843f66a8
* Content: [Install or remove the Linux Subsystem on Windows 10 Anniversary Update or Creators Update](https://docs.microsoft.com/en-us/windows/wsl/install-legacy)
* Content Source: [WSL/install-legacy.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-legacy.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by HenkPoley** [comment]
If you installed Ubuntu from the Store you have installed it from a much newer Windows subsystem for Linux version than mentioned here. The instructions here do not apply.

For example if `wsl --list` shows `Legacy`, then the instructions would apply. With a legacy install there would certainly be a directory called "%localappdata%\lxss\"

**Comment by zenntenn** [comment]
If the instructions are only for the legacy system shouldn't it say so somewhere on them, with a link to the current instructions?

**Comment by gojimmypi** [comment]
fwiw - I don't have a %localappdata%\lxss directory. My Ubuntu is installed in C:\Users\gojimmypi\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\ and the rootfs is in C:\Users\gojimmypi\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\

I'm running Windows 10 1809 (upgraded since the initial install of WSL)

**Comment by mscraigloewen** [comment]
I'll be fixing the lxrun commands to indicate they're deprecated soon. Tracking this in #425
