### ISSUE TITLE
Error: 0x80070057 The parameter is incorrect.

### ISSUE THREAD

**Issue by githubenterprise** [MicrosoftDocs/WSL#310]
I'm running build 18272 and get the following error in powershell:

PS C:\WINDOWS\system32&gt; ubuntu config --default-user root
Error: 0x80070057 The parameter is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Linux User Account and Permissions](https://docs.microsoft.com/en-us/windows/wsl/user-support)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/user-support.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by robcomptec69** [comment]
I ran into the same issue.
I opened the 'cmd' in Admin mode, and that solved it.

**Comment by mscraigloewen** [comment]
Hi, this is a WSL technical issue, could you please search to see if it's already posted on the [WSL Github repo](https://github.com/microsoft/wsl) and if it isn't could you file an issue there? This issue page is specifically for the WSL docs. Thanks!
