### ISSUE TITLE
centos linux  in window store

### ISSUE THREAD

**Issue by changhe626** [MicrosoftDocs/WSL#313]
why there is no centos  in the windows store, it is a great linux from server ,i  want try it in window ,thank you 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Linux User Account and Permissions](https://docs.microsoft.com/zh-cn/windows/wsl/user-support)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/user-support.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by dEhiN** [comment]
Perhaps you could contact the Centos Linux developers and suggest to them about creating an appx for WSL distribution?

**Comment by mscraigloewen** [comment]
We do not provide the distros in the store, those are provided by distro maintainers. However you can install any distro using `wsl --import` in Windows version 1903 and above.
