### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by Mujaddadi** [MicrosoftDocs/WSL#318]
`sudo apt update && sudo apt upgrade
`
gives 

```
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
  Connection failed [IP: 2001:67c:1560:8001::14 80]
```

it's not able to connect with the internet

**Comment by mscraigloewen** [comment]
Hi, this is a WSL technical issue, could you please search to see if it's already posted on the [WSL Github repo](https://github.com/microsoft/wsl) and if it isn't could you file an issue there? This issue page is specifically for the WSL docs. Thanks!
