### ISSUE TITLE
extra ; when changing PATH

### ISSUE THREAD

**Issue by dpareit** [MicrosoftDocs/WSL#319]
An extra ; should be added when changing the PATH. This will avoid wrong PATH when performing this multiple times (eg once for WSL Ubuntu and once for WSL Debian).

Thus, documentation should read:
[System.Environment]::SetEnvironmentVariable("PATH", $userenv + "C:\Distros\Ubuntu;", "User")
instead of 
[System.Environment]::SetEnvironmentVariable("PATH", $userenv + "C:\Distros\Ubuntu", "User")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install the Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-on-server.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by marckassay** [comment]
And to be safe and clean, just one semi-colon should be between `$userenv` and the new value:
```
$userenv = [System.Environment]::GetEnvironmentVariable("Path", "User")
[System.Environment]::SetEnvironmentVariable("PATH", $userenv.TrimEnd(';') + ";C:\Distros\Ubuntu;", "User")
```

**Comment by mscraigloewen** [comment]
Fixed!
