### ISSUE TITLE
Add information (references) for Newbies

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/WSL#322]
Today I installed *WSL* for the first time. At the same time I'm installing *Linux* for the first time. So don't have *any clue* on how to give a proper user name to the Ubuntu distribution. All I get is this error message:

```
Installing, this may take a few minutes...
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: MyName
adduser: Please enter a username matching the regular expression configured
via the NAME_REGEX[_SYSTEM] configuration variable.  Use the `--force-badname'
option to relax this check or reconfigure NAME_REGEX.
Enter new UNIX username:
```

What's this fuzz all about?

So, can you please add a reference to a 101 for setting up WSL properly, including setting up the Linux distribution? I don't want to dig into Linux. All I want is to be able to compile GitHub projects, like [webpack/webpack.js.org](/webpack/webpack.js.org).

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Initialize a new WSL Linux distro](https://docs.microsoft.com/en-us/windows/wsl/initialize-distro)
* Content Source: [WSL/initialize-distro.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/initialize-distro.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by SetTrend** [comment]
Ah, I see.

Still, shouldn't this information be referenced somewhere, probably by linking to a web page already having solved this issue, in a primer for WSL/Linux beginners?

**Comment by webtop** [comment]
This is for the Windows Subsystem for Linux...distro agnostic. If you want information about Ubuntu or any other flavor of Linux, there are literally millions of websites devoted to them...for beginners and all other levels.
Information on such should not be placed at the responsibility of Microsoft. They did not create the distro, they created the ability to run the distro in Windows.

**Comment by mscraigloewen** [comment]
We try and keep the docs as WSL specific as possible. If you'd like a primer on getting set up with Linux and using WSL I'd recommend checking out the [Getting Started with WSL course!](https://aka.ms/wsl-course).
