### ISSUE TITLE
Missing notes how to move existing Linux root-file-system to Win10-Linux-Subsystem

### ISSUE THREAD

**Issue by Blindleistung** [MicrosoftDocs/WSL#326]
It would be nice to see a documentation how to move an existing Linux RFS onto the windows 10 Linux Subsystem. Starting with the existing root-filesystem lying around somewhere as a tarfile. This would also help when creating a new RFS using debootstrap or similar tools.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install the Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-on-server.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by DarthSpock** [comment]
Here: https://github.com/Microsoft/WSL-DistroLauncher

**Comment by mscraigloewen** [comment]
This has also been added as a command using `wsl --import` in 1903 and later. I'll be updating the reference documentation for this soon.

**Comment by WSLUser** [comment]
Love to see the magic behind --import and --export. Is the DistroLauncher project used in backend for import? Or is it some other method. If that could be documented, that would be great (though in a different section most likely).

**Comment by mscraigloewen** [comment]
The [command line reference docs](https://docs.microsoft.com/en-us/windows/wsl/reference) now show the command on how to import a distribution from a tarball of a Linux root file system.
