### ISSUE TITLE
Update with paid distros

### ISSUE THREAD

**Issue by WSLUser** [MicrosoftDocs/WSL#328]
Links for the Store page is good for the free distros but Wlinux, Wlinux Enterprise, and WSLFedoraRemix are missing. Please add these links to the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by mscraigloewen** [comment]
These are now added!

**Comment by WSLUser** [comment]
I guess I should updated this issue. They now have the old names. Now it's PengWin and PengwinEnterprise. The Fedora name should be fine.

**Comment by WSLUser** [comment]
And I submitted PR to fix it up. That was my first doc contribution and it was a quick and easy experience! Not sure where to file issue but the way the fork and update process appeared should be made an option for regular code bases too! Especially when intent is to fix typos or fix similar things (such as README.md)

**Comment by mscraigloewen** [comment]
Good catch, thanks for the PR! And I think that feedback would go to regular Github, as the fork and PR process is part of Microsoft docs.
