### ISSUE TITLE
Needs some documentation about replacing legacy lxrun.exe bash on windows with ubuntu on windows with Store

### ISSUE THREAD

**Issue by soroshsabz** [MicrosoftDocs/WSL#329]
ITNOA

Hi,

I think it is very critical to describe about what is difference between bash on windows and ubuntu on windows, and how to remove each of them, and how to replace each of them.

lxrun.exe is disappeared in new windows 10, and I don't know which of them is better, bash on windows or ubuntu on windows? what command or application alternative for lxrun? and how to provide same functionality?

please describe it, and document it

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by dmitry-borzov** [comment]
It seems like you should use wslconfig instead of lxrun

Get more information:
wslconfig --help

**Comment by soroshsabz** [comment]
@dmitry-borzov no, my suggestion is we need good documentation in docs.microsoft.com to how to migrate from lxrun to wslconfig? and how to replace it?

thx

**Comment by mscraigloewen** [comment]
I'll be updating the documentation to indicate that lxrun is deprecated and you should be using `wsl` to interact with your distros. Tracking this in issue #425
