### ISSUE TITLE
Missing link for openSUSE Leap 15

### ISSUE THREAD

**Issue by RafneQ** [MicrosoftDocs/WSL#330]
There is missing link for openSUSE Leap 15 which was published in the MS Store some time ago: https://www.microsoft.com/en-us/p/opensuse-leap-15/9n1tb6fpvj8c

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by WSLUser** [comment]
This has been fixed for awhile

**Comment by RafneQ** [comment]
I don't think so - there is still link to OpenSuse Leap 42, which is not supported anymore (EOL Jan 2018). There should be link do .appx file of current version (which is Leap 15.1 - [link to MS Store](https://www.microsoft.com/pl-pl/p/opensuse-leap-15-1/9njfzk00fgkv?activetab=pivot:overviewtab))

**Comment by michaelsstuff** [comment]
does anyone has the link?

**Comment by paddymills** [comment]
I couldn't find it at the usual https://aka.ms/ repo, but Leap 15.1 is hosted by openSUSE.org:

https://download.opensuse.org/repositories/Virtualization:/WSL/openSUSE_Leap_15.1/openSUSE-Leap-15.1-x64-Build6.11.appx

Add-AppxPackage failed until I manually installed the certificate.

**Comment by RafneQ** [comment]
@paddymills thanks for the link, I was not aware that this is available in official openSUSE repository. Anyway it appears that SUSE team is deleting old builds and the only one available is the recent one (Build6.13) so it is better to link all the repo for WSL and version 15.1:
https://download.opensuse.org/repositories/Virtualization:/WSL/openSUSE_Leap_15.1/

**Comment by ShalokShalom** [comment]
>So, how to fix this now?

**Comment by pyy** [comment]
more details can be found here:
https://en.opensuse.org/WSL/Manual_Installation

**Comment by mattwojo** [comment]
Resolved. All the links for distros available in Microsoft Store should be up to date now.
