### ISSUE TITLE
Windows application called from WSL don't open with correct working directory

### ISSUE THREAD

**Issue by wazzujoel** [MicrosoftDocs/WSL#331]
WSL Ubuntu 18.04 LTS installation. If I issued the following

cd ~
echo hello &gt; hello.txt
cat hello.txt
notepad.exe ~/hello.txt

Then i receive the following error upon notepad opening "Cannot find the hello.txt file. Do you want to create a new file?". If I select no and then do a file open then the current working directory is "C:/Windows/System32/"

Help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3be148fb-e4a9-83b5-5b5a-7834eed7052f
* Version Independent ID: f583bc11-fe60-bb2c-af2b-dc0dae9fe81f
* Content: [Learn about the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about)
* Content Source: [WSL/about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/about.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
You can only access Linux files from Windows when running Windows version 1903 or later. Please check your version number. 

This is a WSL technical issue, if you're still running into issues could you please search to see if it's already posted on the [WSL Github repo](https://github.com/microsoft/wsl/issues) and if it isn't could you file an issue there? This issue page is specifically for the WSL docs. Thanks!
