### ISSUE TITLE
Error 0x80070005 from Administrator default built account

### ISSUE THREAD

**Issue by eamonnkenny** [MicrosoftDocs/WSL#332]
Top of this page should start by clearly stating that you must be a normal user to install WSL successfully. If you run these commands in Windows 10 pro from the default Administrator account you obtain the 0x80070005 error and the documentation for removal of that error is preposterous!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by RADGASM** [comment]
Hi, I'm seeing the same error though I am the administrator. What should I do next?
This is what I see using the powershell:

Enable-WindowsOptionalFeature : The requested operation requires elevation.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

Appreciate your help please.

**Comment by mattwojo** [comment]
Closing as this seems to be a duplicate issue that was resolved in the WSL product repo: https://github.com/microsoft/WSL/issues/4514 and that doesn't require any specific update to documentation.
Please reopen if this is not the case. ~Matt
