### ISSUE TITLE
Downloaded package extension now .appxBundle and cannot rename downloaded file

### ISSUE THREAD

**Issue by amnuaym** [MicrosoftDocs/WSL#337]
I just recently download and extension now *.appxBundle
Renamce operaiton cannot be done as it always freeze windows explorer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install the Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-on-server.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
Hi @amnuaym this doesn't seem to be something that the WSL team could help you with, as it's not WSL specific (we don't own renaming files). I'd recommend you try the commands in PowerShell as well to rename a file. Thanks!
