### ISSUE TITLE
Manual installation instructions are circular

### ISSUE THREAD

**Issue by mattgif** [MicrosoftDocs/WSL#340]
The "Installing your distro" section from this (the manual download page) links to instructions to install via the Windows store. That page links back to this one for manual install instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual#installing-your-distro)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by james3126** [comment]
I think it's meant to guide you here. Not very clear though.

https://docs.microsoft.com/en-us/windows/wsl/install-on-server

**Comment by jdotb** [comment]
Add-AppxPackage .\Ubuntu.appx

**Comment by jdotb** [comment]
Then run ubuntu1804.exe (or ubuntu1604.exe or ubuntux.xx.exe)

**Comment by elliot12** [comment]
I figured it out after about an hour, much easier way to install the distro of your choice.

1. Make sure you have the Linux Subsystem Feature installed and enabled 
2. Download the distro appx of your choosing 
3. Rename the file with extension .zip 
4. Unzip file 
5. Run exe file as admin (in my case I was using Debian so it was debian.exe)
6. Boom done

**Comment by venkatasreekanth** [comment]
Thank you @elliot12

**Comment by mscraigloewen** [comment]
These are no longer circular, and have now been fixed! Thank you for filing this.
