### ISSUE TITLE
sshd on Fedora Remix

### ISSUE THREAD

**Issue by cshabazian** [MicrosoftDocs/WSL#342]
In order to start the ssh server on the Fedora Remix image, you must first generate the keypair (only the first time):
ssh-keygen -A

Then you can start the ssh server:
/usr/sbin/sshd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting the Windows Susbystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/troubleshooting.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by terwer** [comment]
Tnanks, it works

**Comment by mscraigloewen** [comment]
Thank you for this feedback, we'll leave up the generic instructions for troubleshooting the OpenSSH server in Ubuntu.
