### ISSUE TITLE
Unable to run Mininet inside the terminal: 

### ISSUE THREAD

**Issue by hakiri** [MicrosoftDocs/WSL#344]
Unable to run Mininet inside the terminal: 

# sudo mn --nat -v debug
*** errRun: ['which', 'controller']
/usr/local/bin/controller
  0*** errRun: ['grep', '-c', 'processor', '/proc/cpuinfo']
8
  0*** Setting resource limits
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** errRun: ['which', 'mnexec']
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig']
/sbin/ifconfig
  0_popen ['mnexec', '-cd', 'env', 'PS1=\x7f', 'bash', '--norc', '--noediting', '-is', 'mininet:c0'] 25*** c0 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
*** errRun: ['which', 'telnet']
/usr/bin/telnet
  0*** c0 : ('echo A | telnet -e A 127.0.0.1 6653',)
Telnet escape character is 'A'.
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
*** Adding hosts:
*** errRun: ['which', 'mnexec']
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig']
/sbin/ifconfig
  0_popen ['mnexec', '-cdn', 'env', 'PS1=\x7f', 'bash', '--norc', '--noediting', '-is', 'mininet:h1'] 32

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

![capture](https://user-images.githubusercontent.com/4204278/51791035-794a3800-219d-11e9-85b8-b8c14ca95ed2.JPG)

**Comment by mscraigloewen** [comment]
Hi there, this is a WSL technical issue, could you please search to see if it's already posted on the [WSL Github repo](https://github.com/microsoft/wsl/issues) and if it isn't could you file an issue there? This issue page is specifically for the WSL docs. Thanks!
