### ISSUE TITLE
manual install for W10 desktop

### ISSUE THREAD

**Issue by dvescovi1** [MicrosoftDocs/WSL#346]
doc states manual install for W10 desktop and Windows server. My corp blocks MS-Store access so I manually downloaded distro .appx file but there is no info on how to install on W10 desktop … only Windows server. I it the same? Links take you in circles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by reihaneab** [comment]
@descovi Could you install on W10 desktop with Windows Server installation document?

**Comment by dvescovi1** [comment]
finally got it. On w10 you just have to click the appx file and it installs. Doc's don't mention this but I guess it should be obvious.  Silly me.

**Comment by manish-tadvi** [comment]
But what if you dont have app installer
since my corp won't allow me to download app installer

**Comment by manish-tadvi** [comment]
Never mind got it I used powershell to install the distro instead of app installer
PS C:\> Add-AppxPackage -Path "C:\Users\user1\Desktop\MyApp.appx" modify the command details according to your information. Just for reference

**Comment by xy0** [comment]
Running the manual PS APPX installer returns a prerequisite error.
