### ISSUE TITLE
Blue Screen Issue

### ISSUE THREAD

**Issue by kisoo** [MicrosoftDocs/WSL#348]
I'm using Ubuntu 18.04 with Windows Subsystem for Linux.

Windows System Crash Issue.

Help me!!!

follow the step

1. delete Ubuntu 18.04 & Windows Subsystem for Linux 
2. reboot --> reinstall Windows Sybsystem for Linux 
3. reboot --> reinstall Ubuntu 18.04 using Microsoft Store 
4. reboor --> sudo apt update 
5. sudo apt upgrade --> Windows System Crash (Blue Screen)

Env: Windows 10 Enterprise, Core i7 with 8GB RAM

Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

**Comment by maym2104** [comment]
I had the same issue when I used rsync and recently, scp. Ubuntu 18.04 as well. Do you have McAfee? This might be related: https://community.mcafee.com/t5/Endpoint-Security-ENS/blue-screen-mfeepmpk-wsl-git/td-p/616729. I do not have McAfee on another machine and I never ran into the issue. But I have Ubuntu 16.04 on the other one.

**Comment by mscraigloewen** [comment]
Hi @maym2104 this is a WSL technical issue, could you please search to see if it's already posted on the [WSL Github repo](https://github.com/microsoft/wsl/issues) and if it isn't could you file an issue there? This issue page is specifically for the WSL docs. Thanks!

**Comment by maym2104** [comment]
Sorry for my late response, as I said in a comment on the other issue page, a Windows update fixed the problem. Thanks anyway.
