### ISSUE TITLE
WSL + restart = wifi drivers disabled

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/WSL#352]
I'm on build 17134, and WSL was not enabled.
Run the script above. Restart. Bam! no wifi drivers.
Uninstall WSL. Restart. Wifi active.
How to diagnose what's going on? How to fix it?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-au/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by OzBob** [comment]
Also posted here:https://answers.microsoft.com/en-us/windows/forum/windows_10-hardware/windows-10-subsystem-for-linux-wireless-drivers/7202916e-f529-4920-b314-0233d2073bf2?tm=1549784200777

**Comment by OzBob** [comment]
and also posted here:
https://social.technet.microsoft.com/Forums/en-US/f0c4e63a-ce40-4ac6-b859-2b0628facabd/windows-10-subsystem-for-linux-wireless-drivers-missing?forum=win10itprosetup

**Comment by mscraigloewen** [comment]
Hi @OzBob, this is a WSL technical issue, could you please search to see if it's already posted on the [WSL Github repo](https://github.com/microsoft/wsl/issues) and if it isn't could you file an issue there? This issue page is specifically for the WSL docs. Thanks!
