### ISSUE TITLE
lxrun command not fun

### ISSUE THREAD

**Issue by m4tt72** [MicrosoftDocs/WSL#353]
I tried reinstalling WSL by running `lxrun /uninstall /full /y` but the lxrun is not found.
Running it on powershell.exe (as admin)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by liudonghua123** [comment]
I have the same problem.

**Comment by dmitry-borzov** [comment]
wslconfig /unregister Legacy

Get more information:
wslconfig --help

**Comment by liudonghua123** [comment]
@dmitry-borzov Thanks, however I have removed via `rm -Recurse $env:localappdata/lxss/` according to https://superuser.com/questions/1357266/deleting-wsl-after-installing-ubuntu-from-windows-store

**Comment by mscraigloewen** [comment]
lxrun is deprecated, I'll be fixing the docs shortly. I'm tracking this in issue #425
