### ISSUE TITLE
How to Uninstall Ubuntu on Windows Server 2019?

### ISSUE THREAD

**Issue by gaspardpetit** [MicrosoftDocs/WSL#356]
Hello,

> Run the distro launcher 
> To complete installation, run the distro launcher application in the target folder

Is it possible to have a bit more information about what happens when the distro launcher runs? I am trying to figure out how to uninstall/reset the linux distribution.  Most of the documents I currently find are referring to `lxrun` which is deprecated (and not even found on my Windows 2019 Servers)

**Comment by gaspardpetit** [comment]
Finally found what I was looking for at https://docs.microsoft.com/en-us/windows/wsl/wsl-config

It seems like `lxrun` got deprecated, then replaced by `wslconfig` which is about to get replaced by `wsl` in 1903 :)

**Comment by mscraigloewen** [comment]
That's correct! I'm in the process of updating the docs to show that lxrun is deprecated, (tracking that in issue #425 ). Looks like your issue is solved, thanks for the feedback!
