### ISSUE TITLE
USB joystick for Windows Subsystem for Linux?

### ISSUE THREAD

**Issue by mshong0320** [MicrosoftDocs/WSL#357]
Hello all,

I am using Windows Subsystem for Linux(WSL) to use ROS for a graduate course, and I need to use a usb joystick for the joy tutorial. However, when I plug in the joystick to my computer it doesn't show on /dev/. The joystick uses Windows' xusb22.sys driver, and it's showing that it's connected to Port_#0001.Hub_#0001. How can I access this joystick usb through the WSL?

**Comment by Cen-XIN** [comment]
Hi. You should first check if there is the serial device in your device manager (on WIN10). The serial device may own a certain port called "COM_". Then go to your WSL, the one named "ttyS_" under "/dev/*" is exactly what you want.
("_" stands for a certain number shown on your WIN10)

**Comment by mscraigloewen** [comment]
I agree with @Cen-XIN 's advice. 

If your issue is still not resolved , could you please search to see if it's already posted on the [WSL Github repo](https://github.com/microsoft/wsl/issues) and if it isn't could you file an issue there? This issue page is specifically for the WSL docs. Thanks!

**Comment by Saminhasan5220** [comment]
> Hello all,
> 
> I am using Windows Subsystem for Linux(WSL) to use ROS for a graduate course, and I need to use a usb joystick for the joy tutorial. However, when I plug in the joystick to my computer it doesn't show on /dev/. The joystick uses Windows' xusb22.sys driver, and it's showing that it's connected to Port_#0001.Hub_#0001. How can I access this joystick usb through the WSL?



Sir,is your issue solved?I found a workaround,Please let me know.

**Comment by dariocast** [comment]
> > Hello all,
> > I am using Windows Subsystem for Linux(WSL) to use ROS for a graduate course, and I need to use a usb joystick for the joy tutorial. However, when I plug in the joystick to my computer it doesn't show on /dev/. The joystick uses Windows' xusb22.sys driver, and it's showing that it's connected to Port_#1.Hub_#1. How can I access this joystick usb through the WSL?
> 
> Sir,is your issue solved?I found a workaround,Please let me know.

I have not resolved yet, is there a solution?
