### ISSUE TITLE
The referenced assembly could not be found

### ISSUE THREAD

**Issue by Adrriii** [MicrosoftDocs/WSL#358]
Fails on first step.
Powershell output : https://puu.sh/COa0w/75d9fba5b6.png

Tried this method as well : https://puu.sh/COa1M/e32f8ec022.png
Did not find a corresponding error on the following help given.
Tried several fixes mentioning this error code.

edit: forgot to mention system details : https://puu.sh/COa5z/aba37683f9.png

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/fr-fr/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by shayanardi** [comment]
this is exactly what happen to me 😑😑😑

**Comment by YTRE3045** [comment]
Me too. I tried a lot of methods but I can't resolve this problem.

**Comment by martinKosturkov** [comment]
The same problem happened to me. Did you guys find the solution?

**Comment by dnight71** [comment]
Same problem here too.... seems to be a trend. Maybe their article has errors in the CL instructions.

**Comment by deadpoolknows** [comment]
Have you tried running it in administrator mode. That worked for me.

**Comment by craigloewen-msft** [comment]
The main thread for this issue is here: https://github.com/MicrosoftDocs/WSL/issues/368
That thread is closed, if you do see this error please file an issue at https://github.com/microsoft/wsl
