### ISSUE TITLE
SO_NO_CHECK Protocol not available

### ISSUE THREAD

**Issue by lznzhou33zzz** [MicrosoftDocs/WSL#362]
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

Language : C++
SocketFD = createUdpSocket(host_info_.host_ip.c_str(), host_info_.host_port);
setsockopt(SocketFD, SOL_SOCKET, SO_NO_CHECK, (void*)&disable, sizeof(disable))

Error Info:
Protocol not available

we need UDP communication without CRC checking, is it possible?

**Comment by mscraigloewen** [comment]
This is a technical issue with WSL, and not one with its documentation. Please search to see if this issue is on the [WSL Issues page](https://github.com/microsoft/wsl/issues) and if it's not file a new one.

Thanks!
