### ISSUE TITLE
Should note that wsl.exe respects the login shell set in /etc/passwd

### ISSUE THREAD

**Issue by jcotton42** [MicrosoftDocs/WSL#364]
As the title says

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl-config.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
This is a Linux implementation detail, and we don't generally go over those in the WSL docs page. We try to keep our docs to WSL specific items. Thank you for your feedback!

**Comment by jcotton42** [comment]
I mean sure but it's worth noting, IMO, that bash.exe will always use bash, and that wsl.exe will use whatever shell you've set.

**Comment by mscraigloewen** [comment]
That's fair! I'm changing `reference.md` soon and I will add in that detail. Thank you.
