### ISSUE TITLE
start command and command line completion

### ISSUE THREAD

**Issue by sflanders95** [MicrosoftDocs/WSL#365]
Hi, Thanks for this article!  I'm running into an annoyance.  While in a bash session, and I type vi \~/.bash_a[tab]   it auto-completes to vi \\\~/.bash_aliases which does not work until I unescape the tilde.  So it knows I want the .bash_aliases file because it completed the name, but it screws up by escaping the tilde.  Is there a workaround for this? 

My other question is more of a "the best way to...".  If I am in bash, and a pdf file is in the current directory, I have created an alias to open it:  alias start='cmd.exe /c start'  then I can run commands like:  start myFile.pdf   
Is this the best way to emulate the dos "start" command and others like it?

edit 3/7/19:  fixed some of the markdown above so the issue displays correctly here. 
Also I found a work-around, I Blame the coreutils team for this line in my .bashrc.

`export QUOTING_STYLE=literal`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea49528-e5c5-4f64-841e-9fe036de304e
* Version Independent ID: edeb7cb5-afcf-1410-4966-f48ce5f6a19a
* Content: [Windows interoperability with Linux](https://docs.microsoft.com/en-us/windows/wsl/interop#feedback)
* Content Source: [WSL/interop.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/interop.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
It seems like your bash autocomplete issue is already resolved by editing your .bashrc file, and yes your start alias seems to work great to have a start command in your bash prompt.
