### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by Plegsd** [MicrosoftDocs/WSL#367]
Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

**Comment by mscraigloewen** [comment]
I believe this issue was posted in error, I'll mark it as closed. Please reopen if you still are experiencing an issue!
