### ISSUE TITLE
no lxrun on 1809

### ISSUE THREAD

**Issue by dpb657** [MicrosoftDocs/WSL#369]
I would like to remove the existing Linux environment completely and reinstall it. I have tried removing the feature through the GUI when I reenable it the same environment is there. I cannot find the lxrun command nor any directory lxss besides the one in system32. Any breadcrumbs on where the folder containing the Linux environment is are appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df13cc0f-9f70-c507-d70d-ed8b3c4735ea
* Version Independent ID: 821b82b7-5b0a-ec6c-4a89-cf58843f66a8
* Content: [Install or remove on Windows 10 Anniversary Update or Creators Update](https://docs.microsoft.com/en-us/windows/wsl/install-legacy#feedback)
* Content Source: [WSL/install-legacy.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-legacy.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by binaryfunt** [comment]
Have you unticked "Hide protected operating system files" in the File Explorer options?

**Comment by mscraigloewen** [comment]
lxrun is deprecated, please use the `wsl` command to interact with WSL. If you wish to remove your distributions please use the command: `wsl --unregister <Distro>` which will allow you to reset your environment. Disabling the Windows optional component will remove the necessary Windows files that support WSL.
