### ISSUE TITLE
Error : 0x8007007e

### ISSUE THREAD

**Issue by tkurosaka** [MicrosoftDocs/WSL#370]
ubuntu.exe failed to install the ubuntu image with the following error messages. What does the error code mean and what do I do? I'm trying to enable WSL on the newly created Server 2016 Datacenter VM on Azure.

``` 
PS C:\Users\bhladmin> .\Ubuntu\ubuntu.exe
Installing, this may take a few minutes...
Installation Failed!
Error: 0x8007007e
Press any key to continue...
```

**Comment by mscraigloewen** [comment]
Hi @tkurosaka , could you please open an issue on our WSL github page? We'll be able to help you over there, since this page is just for issues with the WSLDocs.

Thanks!
-Craig
