### ISSUE TITLE
Update issue 

### ISSUE THREAD

**Issue by Nalve** [MicrosoftDocs/WSL#373]
When i try "sudo apt update && apt full-upgrade -y" i have blue screen 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual#feedback)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by mscraigloewen** [comment]
Hi @Nalve , could you please open an issue on our WSL github page? We'll be able to help you over there, since this page is just for issues with the WSLDocs.

Thanks!
-Craig
