### ISSUE TITLE
(WSL) Console - Problems with some applications when resizing console. For example; editing text files with nano ...

### ISSUE THREAD

**Issue by steve007iii** [MicrosoftDocs/WSL#374]
Problems with some applications when resizing console. for example; editing text files with nano ...

It is not practical to edit a configuration with (WSL and the Windows console) with a console text editor

[https://i.imgur.com/HN843zJ.gifv](img)
This happens if you use the key to move to the right. 
![alt tag](https://i.imgur.com/HN843zJ.gif)
### **Unfortunately the console is not consistent**

**Comment by mscraigloewen** [comment]
Hi @steve007iii , this issue is best posted to the [Windows Terminal repo](https://github.com/microsoft/terminal). They control the rendering in WSL and will be able to resolve this issue! Thank you!
