### ISSUE TITLE
bash executable left in System32 after manually deleting the legacy distro

### ISSUE THREAD

**Issue by binaryfunt** [MicrosoftDocs/WSL#377]
I tried manually deleting my `%localappdata%\lxss\` folder using File Explorer, which worked. I then reinstalled from the Windows Store. However, `bash.exe` from the old distro was left remaining in my `System32\`, and I can't delete it - I get a dialog saying

> File access denied
>
> You need permission to perform this action
>
> You require permission from TrustedInstaller to make changes to this file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df13cc0f-9f70-c507-d70d-ed8b3c4735ea
* Version Independent ID: 821b82b7-5b0a-ec6c-4a89-cf58843f66a8
* Content: [Install or remove on Windows 10 Anniversary Update or Creators Update](https://docs.microsoft.com/en-us/windows/wsl/install-legacy)
* Content Source: [WSL/install-legacy.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-legacy.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by binaryfunt** [comment]
I was able to remove `bash.exe` by unticking WSL in the "Turn Windows features on or off" settings dialog.

**Comment by binaryfunt** [comment]
Also, if you reinstall Ubuntu from the Microsoft Store, you may need to use `wslconfig`; see https://github.com/Microsoft/WSL/issues/3960

**Comment by mscraigloewen** [comment]
It seems you already found the solution: Turn off the 'Windows Subsystem for Linux' optional feature. 
I'll mark this issue as closed since I believe it's been resolved. Thank you!
