### ISSUE TITLE
When launching Error: 0x87E10BC6

### ISSUE THREAD

**Issue by agSant01** [MicrosoftDocs/WSL#378]
I successfuly enabled WSL and restarted my PC afterwards (a Surface Book):

```bash
PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux


Path          :
Online        : True
RestartNeeded : False
```

But when launching the ubuntu image it throws this error: 
        `"Something happened on our end. Here’s the error code, in case you need it: 0x87E10BC6"`

I tried with Ubuntu 16, 18 and Kali Linux. All of them show the same error. Since the Microsoft Store was unavailable I downloaded the images from [here](https://docs.microsoft.com/en-us/windows/wsl/install-manual), the official Microsoft site.

## PC specs
- OS Name:                   Microsoft Windows 10 Pro
- OS Version:                10.0.17763 N/A Build 17763
- System Type:              x64-based PC
 - Processor:                  Intel i5

*** I changed the log file extension to `.txt` because it would not let me upload them in here otherwise. Their original format is `.etl`.

[lxcore_kernel.etl.txt](https://github.com/MicrosoftDocs/WSL/files/3050916/lxcore_kernel.etl.txt)
[lxcore_service.etl.txt](https://github.com/MicrosoftDocs/WSL/files/3050917/lxcore_service.etl.txt)
[lxcore_user.etl.txt](https://github.com/MicrosoftDocs/WSL/files/3050918/lxcore_user.etl.txt)

**Comment by mscraigloewen** [comment]
Hi @agSant01 , could you please open an issue on our [WSL github page](https://github.com/microsoft/wsl/issues)? We'll be able to help you over there, since this page is just for issues with the WSLDocs. 

Thanks! 
-Craig
