### ISSUE TITLE
Confirm WSL Enabled

### ISSUE THREAD

**Issue by Gamecock** [MicrosoftDocs/WSL#381]
The example says to type this command.  But it does not say how to interpret the result.  Does this mean WSL *is* or *isnot* enabled.
 
```
PS C:\Users\ADMINI~1\Ubuntu18_04> PowerShell
>>; Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\ADMINI~1\Ubuntu18_04>;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting the Windows Susbystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#feedback)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/troubleshooting.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by feliperomero3** [comment]
@Gamecock the first line "PowerShell" is not part of the command, ignore it.

The command is:
>Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

And you should get the next output (assuming the feature is enabled)
>FeatureName      : Microsoft-Windows-Subsystem-Linux
DisplayName      : Subsistema de Windows para Linux
Description      : Proporciona servicios y entornos para ejecutar herramientas y shells de Linux de modo de usuario
                   nativo en Windows.
RestartRequired  : Possible
State            : Enabled
CustomProperties :
                   ServerComponent\Description : Proporciona servicios y entornos para ejecutar herramientas y shells
                   de Linux de modo de usuario nativo en Windows.
                   ServerComponent\DisplayName : Subsistema de Windows para Linux
                   ServerComponent\Id : 1033
                   ServerComponent\Type : Feature
                   ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
                   ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux

**Comment by mscraigloewen** [comment]
@feliperomero3 is correct, we've removed the 'PowerShell' line at the top of that command. I'll mark this issue as closed as I believe we've addressed your issue. Thanks!
