### ISSUE TITLE
Impossible to connect WSL to Internet

### ISSUE THREAD

**Issue by BaptisteGavalda** [MicrosoftDocs/WSL#384]
I'm am using OpenSuse Leap 42, I try to get access to internet to update my packages. I follwed this part https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#bash-loses-network-connectivity-once-connected-to-a-vpn but doesn't change anything.
What could be other solution than changing resolv.conf file ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting the Windows Susbystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#feedback)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/troubleshooting.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
Hi @BaptisteGavalda , could you please open an issue on our WSL github page? We'll be able to help you over there, since this page is just for issues with the WSLDocs.

Thanks!
-Craig
