### ISSUE TITLE
How to protect Linux volumes from Windows tools?

### ISSUE THREAD

**Issue by yecril71pl** [MicrosoftDocs/WSL#385]
I do not want my malware scanner to mess with my Linux volumes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd5bfb4-8a38-1f09-0d36-6b9abe9b8b08
* Version Independent ID: 156d9535-c2a5-bc8d-af24-342a13832abf
* Content: [Frequently Asked Questions (FAQ)](https://docs.microsoft.com/en-us/windows/wsl/faq)
* Content Source: [WSL/faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/faq.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by Amitie10g** [comment]
Just add exclusions for the directory used by the distro (usually found at %LOCALAPPDATA%\Packages)

**Comment by yecril71pl** [comment]
I cannot see it there.

**Comment by yecril71pl** [comment]
Thank you, I found it.  Could you add this information to the documentation?

**Comment by mscraigloewen** [comment]
Hi @yecril71pl this actually isn't a question that we get that often, if we get more issues or questions about it I'll add it to the FAQ. Thanks for asking! :)
