### ISSUE TITLE
Incorrect link \mnt\c\dev\myproj

### ISSUE THREAD

**Issue by thernstig** [MicrosoftDocs/WSL#386]
https://docs.microsoft.com/sv-se/windows/wsl/faq#how-do-i-use-a-windows-file-with-a-linux-app incorrectly shows the link `\mnt\c\dev\myproj`. The correct link should be `\mnt\c\dev\myproj`

---
#### Document information

* ID: 9bd5bfb4-8a38-1f09-0d36-6b9abe9b8b08
* Version Independent ID: 156d9535-c2a5-bc8d-af24-342a13832abf
* Content: [Frequently Asked Questions (FAQ)](https://docs.microsoft.com/sv-se/windows/wsl/faq#feedback)
* Content Source: [WSL/faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/faq.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by mscraigloewen** [comment]
This has been fixed to have the correct forward slashes!
