### ISSUE TITLE
-bash: syntax error near unexpected token `'PATH','

### ISSUE THREAD

**Issue by haydrionrayel** [MicrosoftDocs/WSL#387]
$userenv = [System.Environment]::GetEnvironmentVariable("Path", "User")
[System.Environment]::SetEnvironmentVariable("PATH", $userenv + "C:\Users\Administrator\Ubuntu", "User")

get

-bash: syntax error near unexpected token `'PATH','

**Comment by mscraigloewen** [comment]
I've added a fix to these docs from a helpful pull request #349 !
