### ISSUE TITLE
my installation stop, and return error message

### ISSUE THREAD

**Issue by lailabeauty** [MicrosoftDocs/WSL#388]
i can't install ubuntu?? it stop downloading from Microsoft store on 55% and then i got error message? why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by mscraigloewen** [comment]
Hi @lailabeauty , could you please open an issue on our [WSL github page](https://github.com/microsoft/wsl/issues)? We'll be able to help you over there, since this page is just for issues with the WSLDocs. 

Thanks! 
-Craig
