### ISSUE TITLE
Missing executable

### ISSUE THREAD

**Issue by iloretoLLU** [MicrosoftDocs/WSL#389]
Missing executable file on Kali distro. Expanded the compressed archive per instructions but nothing to run. Binaries for Ubuntu and Debian packages are found OK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual#feedback)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by Amitie10g** [comment]
You need to contact the package maintainer.

**Comment by mscraigloewen** [comment]
@Amitie10g is correct, this is an issue for Kali Linux to resolve as they provide all of the bits inside of the appx. Since we're not able to help with your issue I'll close the one here, please open one with Kali Linux!
