### ISSUE TITLE
DrvFS options not listed and no link provided

### ISSUE THREAD

**Issue by sskeirik** [MicrosoftDocs/WSL#391]
The various DrvFS options that can be set via `automount.options` is not documented and no reference link is provided. The best reference I found is this blogpost which lists some of them:

https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#feedback)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl-config.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by Brassfield** [comment]
This! a thousand times this.

One other option is:
case = {off / dir}
https://devblogs.microsoft.com/commandline/improved-per-directory-case-sensitivity-support-in-wsl/

**Comment by mattwojo** [comment]
This is now all in the docs: https://docs.microsoft.com/windows/wsl/wsl-config#automount-options
Also just added a brief explainer for DrvFs: https://github.com/MicrosoftDocs/WSL/pull/1474

Please reopen if you notice anything missing.
