### ISSUE TITLE
The requested operation requires elevated privelages

### ISSUE THREAD

**Issue by cmcjacob** [MicrosoftDocs/WSL#393]
PS C:\Users\cmcja> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
>>
Enable-WindowsOptionalFeature : The requested operation requires elevation.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

**Comment by cmcjacob** [comment]
I also don't see an 'administrator' account at my windows 10 login.

**Comment by benhillis** [comment]
You have to "run as Administrator"
