### ISSUE TITLE
Open C:drive files 

### ISSUE THREAD

**Issue by IasonArgyrakis** [MicrosoftDocs/WSL#394]
hi, I would like to be able to access the root directory from the windows explorer is that possible somehow?

Thank you in advance

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3be148fb-e4a9-83b5-5b5a-7834eed7052f
* Version Independent ID: f583bc11-fe60-bb2c-af2b-dc0dae9fe81f
* Content: [Learn about the Windows Subsystem for Linux](https://docs.microsoft.com/en-gb/windows/wsl/about#feedback)
* Content Source: [WSL/about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/about.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
Yes! It's possible in Windows Version 1903. [Here](https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-windows-10-version-1903/) are the details.
