### ISSUE TITLE
manual install instruction missing - refers back to this page

### ISSUE THREAD

**Issue by koolhand** [MicrosoftDocs/WSL#395]
> To download and install your preferred distro(s), you have three choices:
> 1. ...
> 2. Download and install from the Command-Line/Script ([read the manual installation instructions](https://docs.microsoft.com/en-us/windows/wsl/install-manual))

...which links to https://docs.microsoft.com/en-us/windows/wsl/install-manual which says...

> Installing your distro
> For instructions on how to install your downloaded distro(s), please refer to the [Windows Desktop](https://docs.microsoft.com/en-us/windows/wsl/install-win10) or Windows Server installation instructions.

...which links back here. No manual installation step is given, only manual download.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by justbennett** [comment]
I noticed this too. Just run the file you downloaded. "Ubuntu.appx" (or whatever distro you chose) from the command line.

**Comment by koolhand** [comment]
Thanks @justbennett. I also found that renaming the .appx to .zip, unzipping, and running the contained .exe did the trick too. I’m not sure which method is most likely to succeed in a restricted corporate environment with no Store access: Launch the .appx? Unzip it and run the .exe? Install with PowerShell AppX module cmdlets? Hopefully the WSL documentation people catch that...

**Comment by mscraigloewen** [comment]
Hi! I'd be the WSL documentation people, and I'm editing the docs to fix the cyclic install instructions. Thanks for filing the issue!

**Comment by koolhand** [comment]
Excellent! Thanks @mscraigloewen

**Comment by mscraigloewen** [comment]
This has now been fixed.

**Comment by koolhand** [comment]
Cool!
