### ISSUE TITLE
Debian wsl bash crashes at startup

### ISSUE THREAD

**Issue by ashiwalv** [MicrosoftDocs/WSL#399]
Hi,

I was trying to Install WSL for Debian on Window 10 and encountering the problem of crashing whenever I start debian.exe file.

Things I have done for WSL:
1) Enable Developer Mode but it encounters with Error no 0x800f0954 as "Developer mode is turned on. However, remote development and Windows Device Portal couldn't be found in Window Update, so they're not available. Error Code 0x800f0954 ", my window store is blocked from IT department so I guess this error is because of that.
![Error_DeveloperMode](https://user-images.githubusercontent.com/3264554/59045348-318c9900-8880-11e9-9de7-32a1093f1f82.PNG)
![PowerShell_Output01](https://user-images.githubusercontent.com/3264554/59045394-49641d00-8880-11e9-9226-2a93bc1a0ea6.PNG)

2) Checked "Windows Subsystem for Linux" at "Turn Window features on and off" and rebooted the PC.
3) Followed process as per "https://docs.microsoft.com/en-us/windows/wsl/install-on-server" until unzip.
4) Now after double clicking on debian.exe, the bash get crash.
5) I tried same procedure with OpenSuSe and Ubuntu and it worked with them but it does not work with Debian.

6) I saw some forum entries and found to uninstall by lxrun command in power shell or cmd promt but my system can not recognize lxrun cmd too!

Any command or experience with debian will be helpful.

Thanks!

**Comment by mscraigloewen** [comment]
Hi @ashiwalv , could you please open an issue on our [WSL github page](https://github.com/microsoft/wsl/issues)? We'll be able to help you over there, since this page is just for issues with the WSLDocs. 

Thanks! 
-Craig

**Comment by ashiwalv** [comment]
Hi Craig,

Thanks! I have created it at https://github.com/microsoft/WSL/issues/4110

Best Regards,
Virendra
