### ISSUE TITLE
Incorrect product name for alternative VM software

### ISSUE THREAD

**Issue by spotlightishere** [MicrosoftDocs/WSL#402]
VirtualBox is the proper application name (instead of Virtual Box). This casing was taken from how Wikipedia uses it (https://en.wikipedia.org/wiki/VirtualBox) and their official site (https://www.virtualbox.org/). Super low priority but spacing is a personal irk.

Additionally to mix another minor detail in, the markdown `'&lt;VMName&gt;'` renders as `''` on the last line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#feedback)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-faq.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by mscraigloewen** [comment]
Fixed! Thanks for letting us know.
