### ISSUE TITLE
can't enable the virtual machine platform

### ISSUE THREAD

**Issue by jplew** [MicrosoftDocs/WSL#403]
In case anyone gets the following error on step 1:
```
PS C:\Users\jplew&gt; Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform                            
Enable-WindowsOptionalFeature : The requested operation requires elevation.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
```

That means you're running Powershell as a non-administrator. Make sure to run it again with admin privileges.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by heidricha** [comment]
Same error here, I definitely run PowerShell as administrator. 
The machine is a domained, I am local admin, not domain admin. does it matter? I was able to install wsl1 earlier.
