### ISSUE TITLE
`explorer.exe /` only opens Documents. Use `explorer.exe .` instead

### ISSUE THREAD

**Issue by nstrelow** [MicrosoftDocs/WSL#407]
`explorer.exe /` only opens Documents. Use `explorer.exe .` instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [UX Changes between WSL 1 and WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#feedback)
* Content Source: [WSL/wsl2-ux-changes.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-ux-changes.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by mscraigloewen** [comment]
Fixed this detail! Thank you for pointing it out. :)

**Comment by boan-jfm** [comment]
It still opens Documents when using `explorer.exe .` on my machine - os build: 18985.1.
