### ISSUE TITLE
A few pictures of the architecture would be nice

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/WSL#413]
As the subject says, a diagram or two explaining the architecture and show how WSL runs inside WIndows would be useful.

Also - what is the "the latest and greatest in virtualization technology"?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c94eeb-5969-cb2d-fc63-1d4074070812
* Version Independent ID: def2349f-07a2-e772-0583-e5e3ce5983d4
* Content: [About WSL 2](https://docs.microsoft.com/en-gb/windows/wsl/wsl2-about)
* Content Source: [WSL/wsl2-about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-about.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by mscraigloewen** [comment]
More details into the architecture are coming! We have some general info available online like in [our BUILD talk](https://youtu.be/lwhMThePdIo?t=1775) but we plan to add more to these doc pages in the future, thank you for the suggestion!

Also 'Latest and greatest in virtualization technology' means we're using tech that has been recently developed.

**Comment by doctordns** [comment]
I have watched the talk and agree that those diagrams and the associated commentary would make an excellent addition to this page.

Regarding the second point - when I searched for "Latest and greatest in virtualization technology" I found references to XEN, VMware Workstation, etc. :-)  

The point I was making was that it would be good to name the feature and provide references to more information on 'how does WSL2 do that'.  I'd like to understand more fully just how this VM is created and how it differs from a Hyper-V VM (call me curious!) so references and consistent feature naming is useful.

**Comment by AngelMunoz** [comment]
Hi there!
The phrase
>"Latest and greatest in virtualization technology"

sounds like marketing stuff and not really describing what's the real deal :)

Also while this section
>Brief overview of the WSL 2 architecture

tries to convince the  reader that while _it's a VM it shouldn't feel like a VM_
I can only see myself understanding "hey it's a vm but with a sticker of not vm, so... a vm then".
I saw comments on the windows devblog that if in the end it's a vm why bother and better improving hyper-v

that's why I agree with @doctordns pictures explaining what are some of the medium/low levels explaining on why this is different from a traditional VM

**Comment by mscraigloewen** [comment]
Agreed! I think adding more details about the architecture of the VM would be a great addition to the docs. It's on our backlog :)

**Comment by craigloewen-msft** [comment]
Hey! The best place to find our architecture is in this talk: https://www.youtube.com/watch?v=lwhMThePdIo&t=1813s
