### ISSUE TITLE
The example codeline to unregister is wrong.

### ISSUE THREAD

**Issue by menzo2003** [MicrosoftDocs/WSL#414]
the example says: wsl -unregister Ubuntu
It should be: wsl --unregister Ubuntu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#feedback)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl-config.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by benhillis** [comment]
Thanks, I've fixed this.
