### ISSUE TITLE
Cannot run with --set-version option

### ISSUE THREAD

**Issue by shamoons** [MicrosoftDocs/WSL#415]
I am running Windows 10 Pro for Workstations 1903

Here's what I get:
```
PS C:\WINDOWS\system32> wsl --set-version Ubuntu 2
Invalid command line option: --set-version
```

I've already run `Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform` and rebooted.

**Comment by mscraigloewen** [comment]
Hi shamoons, it seems like you're not running a Windows Insiders build. If you open up command prompt and type in the command `ver` what's the output? 

To become a Windows Insider go to Settings > Update > Windows Insider program and switch to Active Development + Fast

**Comment by shamoons** [comment]
`Microsoft Windows [Version 10.0.18362.175]`

**Comment by mscraigloewen** [comment]
Yes you need to be on build 18917 and up, please update via the Windows Insider program.

**Comment by shamoons** [comment]
Any downside to being in the Windows Insider program? Are things generally buggy?

**Comment by mscraigloewen** [comment]
You're getting the newest builds of Windows and so yes you are more likely to experience bugs, but you also get first access to more tech like WSL 2!

**Comment by dodicandra** [comment]
I am running Windows 10 Pro 1903
Here's what I get:

PS C:\Users\DODICANDRA> wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu-18.04 (Default)
PS C:\Users\DODICANDRA> wsl --set-version Ubuntu-18.04 2
Invalid command line option: --set-version
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments to run Linux binaries:...
.
.
.
.

I've already run Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform and rebooted.
