### ISSUE TITLE
Docker on WSL 2

### ISSUE THREAD

**Issue by purplefeetguy** [MicrosoftDocs/WSL#416]
This only worked for me using an elevated powershell session:

PS C:\WINDOWS\system32&gt; wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Stopped         2
PS C:\WINDOWS\system32&gt;

└──☻ sudo service docker status
 * Docker is not running

└──☻ sudo service docker start
 * Starting Docker: docker

└──☻ sudo service docker status
 * Docker is running

└──☻ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
1b930d010525: Pull complete                                                                                                                                                         Digest: sha256:41a65640635299bab090f783209c1e3a3f11934cf7756b09cb2f1e02147c6ed8
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by mscraigloewen** [comment]
Instead of using the `sudo service docker start` command please try using: `/etc/init.d/docker start`. 

This shouldn't require you to use an elevated powershell instance. Does this solve your problem?

**Comment by riparino** [comment]
Out of curiosity, are you running a guest using WSL with a docker container inside? VMception?

**Comment by purplefeetguy** [comment]
no, Hyper-V, WSL 2 with docker installed in WSL 2. I have tried to convert existing WSL deployments on 2 different systems now and both required an elevated powershell session to successfully convert. Once converted, the "service" commands worked fine within WSL 2.

**Comment by mscraigloewen** [comment]
@purplefeetguy it seems like your original issue is resolved so I'll close out this issue. :) If it isn't, please re-open!
