### ISSUE TITLE
after import centos7.tar, I can't get in it.

### ISSUE THREAD

**Issue by echofool** [MicrosoftDocs/WSL#417]
```cmd
C:\Windows\System32>wsl --list -v
  NAME       STATE           VERSION
* centos7    Running         2

C:\Windows\System32>wsl

C:\Windows\System32>
```
I run `wsl --list -v`, I can see centos7 is running, but when run `wsl`, it just returm empty but nothing...

**Comment by benhillis** [comment]
Could you try installing another distro to WSL 2 and sharing dmesg output when you try to launch centos?

**Comment by echofool** [comment]
I don't know how to get `dmesg output`.

**Comment by benhillis** [comment]
I'll give this a try today.

**Comment by echofool** [comment]
thanks a lot!

**Comment by craigloewen-msft** [comment]
Closing this issue out since it's been open for a while, if seen again please feel free to refile it. Thank you for filing!
