### ISSUE TITLE
Static IP on WSL 2

### ISSUE THREAD

**Issue by yanyan33333** [MicrosoftDocs/WSL#418]
hello, I use WSL 2 in windows 10 insider
and I found that the ip address on WSL 2 change everytime when I restart windows
can I use the static ip on WSL 2?

also how can I start ssh service on boot?
thx~

**Comment by WSLUser** [comment]
You'll need to create an init script for ssh to auto start when you launch WSL (doesn't matter WSL1 or WSL2). Pengwin will automatically do this for you if you ask it from penguin-setup. As far as IP address goes, you can make the IP address static just like on Linux. Here's a quick look from a recent article: https://danielmiessler.com/study/manually-set-ip-linux/

**Comment by WSLUser** [comment]
@mscraigloewen It may be a good idea to create a new doc going over common configurations such as creating the init script for ssh and others that are common. Anyone could go to the Pengwin repo to get the ssh script, I linked to a few others in the FedoraRemix repo (such as memcached and nginx) but I'm sure it would ease a lot of developers to just have an authoritative doc that goes over standard practices and procedures. Init scripts are just a part of it. Linking to the dev-box-setup repo would also be a good idea for that doc.

**Comment by mscraigloewen** [comment]
@WSLUser yes that's a good idea! I'll look into making some of those docs.

**Comment by yanyan33333** [comment]
> You'll need to create an init script for ssh to auto start when you launch WSL (doesn't matter WSL1 or WSL2). Pengwin will automatically do this for you if you ask it from pengwin-setup. As far as IP address goes, you can make the IP address static just like on Linux. Here's a quick look from a recent article: https://danielmiessler.com/study/manually-set-ip-linux/

It`s not working, the Hyper-V Switch IP change everytime when the windows reboot,  so the gateway in wsl 2 also need to change

**Comment by yanyan33333** [comment]
@mscraigloewen Is it no way to make the IP in  Hyper-V Switch on windows and linux on WSL 2 not to change every reboot right now ？

**Comment by WSLUser** [comment]
There's a technical issue with WSL2 in that regard. I saw there was an issue about it on https://github.com/Microsoft/WSL/issues/ but I don't recall the issue number unfortunately. From what I remember, you'll need something like a script right now that automatically runs when you launch a WSL2 instance.

**Comment by mscraigloewen** [comment]
As of right now I'm not aware of a way to make the IP of the Hyper-V switch static. 

We are working on improving our networking story so you can connect using 'localhost' instead of a remote IP address which should address your issue!

**Comment by kpeters-cbsi** [comment]
There's a workaround posted, but I haven't tried it.

https://github.com/microsoft/WSL/issues/4150#issuecomment-504209723

**Comment by peidaqi** [comment]
@mscraigloewen it doesn't work when you need to access Windows resources from Linux, say, you want to run a Linux app to access the SQL Server running on Windows host.

**Comment by WSLUser** [comment]
> say, you want to run a Linux app to access the SQL Server running on Windows host.

I think the 9P server would probably be able to work for it. Granted perf will likely not be great but assuming 9P works as intended in WSL2, it should provide you an workaround option.

**Comment by peidaqi** [comment]
@WSLUser Not sure what you mean by 9P server. If you're refering to the MSSQL Server for Linux, yes it works but I also hope to be able to use the Management Studio to easily explore my data...

**Comment by WSLUser** [comment]
No, 9P is a network share feature for allowing Windows to access Linux files that’s built into `init`. A separate feature from the networking story discussed in this issue. You can find out more about it in a [MS blog](https://devblogs.microsoft.com/commandline/a-deep-dive-into-how-wsl-allows-windows-to-access-linux-files/).

**Comment by mscraigloewen** [comment]
@peidaqi what do you mean by it doesn't work? If you follow the [instructions here](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#accessing-windows-applications-from-linux) (make sure to read the 'Other networking considerations section as well as that might be where the error comes from!) does it still not work?

If it still doesn't work please consider opening an issue on our WSL Github repo: https://github.com/microsoft/wsl

**Comment by peidaqi** [comment]
@mscraigloewen I mean "localhost" would only work if you're running a linux server binded to "localhost" and access it from WSL.

If you need to access something running on the Windows host from linux you obviously need the host IP address. And there's no non-trivial way to get that host IP from the WSL environment. There's also the problem with Windows firewall - say I want to allow all access from WSL guest.

That's where static IP on both WSL and the host would come in handy.

**Comment by yanyan33333** [comment]
@mscraigloewen thx
the last build version 18945  solaved
https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-insiders-preview-build-18945/

**Comment by yanyan33333** [comment]
@mscraigloewen Is there any solution to start wsl when windows booting?

**Comment by mscraigloewen** [comment]
@yanyan33333 there's a program called 'Task Scheduler' on Windows that can start programs on log on. You can set this up to run `wsl.exe` on login. I'd encourage you to take a look online on how to do so, if you aren't able to do get it working please let me know!

**Comment by protang** [comment]
I give you a new idea: Instead of changing the IP, add a designated IP.

In Windows 10, run CMD or Powershell with administrator privilege, and then execute the following two commands:

:: Add an IP address in Ubuntu, 192.168.50.16, named eth0:1
`wsl -d Ubuntu -u root ip addr add 192.168.50.16/24 broadcast 192.168.50.255 dev eth0 label eth0:1`

:: Add an IP address in Win10, 192.168.50.88
`netsh interface ip add address "vEthernet (WSL)" 192.168.50.88 255.255.255.0`


In the future, you will use 192.168.50.16 when you access Ubuntu, and 192.168.50.88 when you access Win10.

**Comment by samgithub** [comment]
protang -- Ths works "temporarily".  Sometimes, it persists after a reboot.  Sometimes after 3-4 days the IP vanishes.

**Comment by AkhilJalagam** [comment]
Hyper-V bridged mode

```
wsl --shutdown
wsl -d Ubuntu -u root bash -c "sudo ip a flush dev eth0; sudo ip r del default; ip addr add 192.168.1.50/24 broadcast 192.168.1.255 dev eth0; sudo ip r add default via 192.168.1.1"
```

Don't forget to update /etc/resolv.conf

**Comment by litecart-cs** [comment]
Still impossible to set a static IP?

**Comment by kangaroonote1972** [comment]
wsl -d kali-linux01 -- ifconfig eth0 add 172.31.155.100 netmask 255.255.240.0 broadcast 172.31.159.255

**Comment by explogx** [comment]
Hey @craigloewen-msft do you have any news on that?

I recently tried to assign a static IP to my wsl instance and I noticed the IP get randomized at each wsl reboot, this is mainly because the wsl vSwitch is deleted when wsl is not running. It would be really, really great if the wsl vSwitch could be permanently configured, along with the NAT settings associated with the Windows host and the hyper-v wsl instance.

Thanks in advance.

**Comment by craigloewen-msft** [comment]
We don't yet have any concrete news here. I can tell you that we are working on improving WSL's networking story and are taking in static IP as a consideration, but we don't yet have anything to share in this area. Thanks for being patient!

**Comment by Falseclock** [comment]
1. create any executable script on wsl2
```
#!/bin/bash

/sbin/ip addr add 192.168.101.161/24 broadcast 192.168.101.255 dev eth0 label eth0:1
/mnt/c/Windows/System32/netsh.exe interface ipv4 add address "vEthernet (WSL)" 192.168.101.162 255.255.255.0
```

2. edit crontab and add your script
```
@reboot /path/to/the/script
```

3. add to /etc/sudoers
```
%sudo ALL=NOPASSWD: /etc/init.d/cron *
```

4. on windows side create vbs script
```
Set oShell = CreateObject ("Wscript.Shell") 

Dim strArgs
strArgs = "C:\Windows\System32\wsl.exe -d Debian sudo /etc/init.d/cron start"
oShell.Run strArgs, 0, false
```

5. put this script to windows autostart

**Comment by wanderleihuttel** [comment]
Hello

Is there any update regarding this? It's awful have to look for the IP every time you need to access the WSL. 
This should be something trivial.

**Comment by tomrus88** [comment]
@craigloewen-msft Its been years since users are asking for this feature. Why does it take so long to implement? I'm like many others out there want to have static IP (and also static MAC address) in WSL2...

Why can't we just have an access to those Hyper-V network adapters used by WSL2 (i've tried to find them without success) and be able to configure them the way we want it (assign ip, assign mac etc)?

**Comment by nmydt** [comment]
@Falseclock If I copy a Ubuntu 18.04, modify one of the static IP will lead to another Ubuntu18.04 IP will also change, I want to make these two have static IP, what is a good way
