### ISSUE TITLE
Invalid command line options

### ISSUE THREAD

**Issue by narosis** [MicrosoftDocs/WSL#419]
Enable the 'Virtual Machine Platform' optional component
Open PowerShell as an Administrator and run:
Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
completes without incident

Set a distro to be backed by WSL 2 using the command line
In PowerShell run:
wsl --set-version &lt;Distro&gt; 2 = wsl --set-version Ubuntu 2
generates the following error:
Invalid command line option: --set-version

wsl --set-default-version 2
generates the following error
Invalid command line option: --set-default-version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by maccam912** [comment]
Check which build of windows you are on. I had this error when I was on builds less than 18917. You can find this in your "System Information" application.

**Comment by mscraigloewen** [comment]
Yes please make sure that you are on Build 18917 or higher, and if you aren't you can always upgrade via the Windows Insiders program.

**Comment by chooky19** [comment]
Me too on Build 18917. Windows Home Insider Preview

**Comment by vivekmanju** [comment]
I am on 18917 build, but I still get the The term 'wsl' is not recognized as the name of a cmdlet.

**Comment by obbap1** [comment]
I am on version 1903(os build 18362.175) and it says invalid command line options

**Comment by golemarms** [comment]
I get the same error: 
Invalid command line option: --set-version
My system is on Version 10.0.18362 Build 18362

**Comment by elithrar** [comment]
@golemarms - You need to be on build 18917 or greater; 18362 doesn't meet that requirement.

**Comment by narosis** [comment]
this is my issue, my current build: 18362.175

**Comment by elithrar** [comment]
18362 is less than 18917, and doesn't satisfy the constraint. You'll likely want to be on the "Fast" ring to get 18917 or greater as of today.

**Comment by narosis** [comment]
Now that I have upgraded, the commands are valid and act as expected. Thanks for all your assistance this can now be closed

**Comment by tristanbarcelon** [comment]
wsl is not a recognized command if only VirtualMachinePlatform feature is enabled and that is with build 18922. Documentation appears to be missing an installation step for WSL 1.

![image](https://user-images.githubusercontent.com/5810165/59812993-ec378500-92dd-11e9-90ae-191a1c313685.png)

**Comment by mscraigloewen** [comment]
@tristanbarcelon the [WSL 2 install documentation](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install) has been updated to include links to instructions on how to install WSL 1.
