### ISSUE TITLE
 Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.

### ISSUE THREAD

**Issue by maccam912** [MicrosoftDocs/WSL#420]
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0xc03a001a
Error: 0xc03a001a The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.

When trying to install Ubuntu with WSL2 as the default I am getting the above error on first launch. I have turned off encryption and compression, at least I think so, but still get this error after a reboot.

**Comment by benhillis** [comment]
Duplicate https://github.com/microsoft/WSL/issues/4103.
