### ISSUE TITLE
Can't open linux file after reboot

### ISSUE THREAD

**Issue by anjiawei1991** [MicrosoftDocs/WSL#423]
distro: Ubuntu-18.04
WSL Version: 2

After I reboot my WLS (with `ctrl+D` and then input cmd `bash`). I can't visit my linux file （with `explore.exe .`）:

![image](https://user-images.githubusercontent.com/48538419/59564439-4be12680-9079-11e9-81e7-839abd367deb.png)

**Comment by anjiawei1991** [comment]
it get back to normal after i reboot my windows

**Comment by anjiawei1991** [comment]
just now, I opened my golang project in vscode, and golang tools work busy , and then the problem reappeared. 

so i think it's the continual file reading instead of reboot WSL  cause the problem

**Comment by WSLUser** [comment]
This isn't a doc issue. This is a technical issue. Please check https://github.com/Microsoft/WSL/issues/ as this may of been reported already. If not, file the issue there (or MS can move this one to there).
