### ISSUE TITLE
lxrun deprecated

### ISSUE THREAD

**Issue by arpita-singh** [MicrosoftDocs/WSL#425]
Is lxrun still valid or depracated and replaced with wsl?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bc08c2-7a4c-8827-47b9-2729abf0a9e9
* Version Independent ID: 26e3819a-72d0-e8a8-7790-5551acede71b
* Content: [Windows Subsystem for Linux Command Reference](https://docs.microsoft.com/en-au/windows/wsl/reference#feedback)
* Content Source: [WSL/reference.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/reference.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
You should use `wsl.exe` to interact with everything WSL. I'll update this section of the docs!

**Comment by mscraigloewen** [comment]
I've updated the reference section to reflect the current state of the command line.

**Comment by Vino-Bala** [comment]
Using WSL. Still facing the issue:

>wsl
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

>

**Comment by craigloewen-msft** [comment]
@Vino-Bala have you tried to install a distribution from the Microsoft store? If you go to this link: https://aka.ms/wslstore it will take you to the WSL store page. Otherwise you can just search for a distro like "Ubuntu".

**Comment by yashverma2110** [comment]
This URL directs me to the Microsoft store but it shows an error. I have waited for 5 minutes and restarted and what not.
![Screenshot (20)](https://user-images.githubusercontent.com/42317408/73868555-afb99900-486e-11ea-820c-974049f44ddf.png)

**Comment by craigloewen-msft** [comment]
Try this link: https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6

**Comment by zklim** [comment]
> @Vino-Bala have you tried to install a distribution from the Microsoft store? If you go to this link: https://aka.ms/wslstore it will take you to the WSL store page. Otherwise you can just search for a distro like "Ubuntu".

you know why I keep getting error Code: 0x80080204 while downloading Ubuntu?

**Comment by Biswa96** [comment]
Please explain the steps to reproduce your issue.
