### ISSUE TITLE
Docs for WSL2 contain a lot of references to VHD but do not define the term

### ISSUE THREAD

**Issue by orta** [MicrosoftDocs/WSL#426]
I'm new to Windows, and WSL (and WSL2, what a time to be alive) so maybe this is common TLA but I thought it would be worth noting here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [UX Changes between WSL 1 and WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#feedback)
* Content Source: [WSL/wsl2-ux-changes.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-ux-changes.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by mscraigloewen** [comment]
You're right! I'll make sure to go in and write out the acronym at least once for each page. 
Thanks for your suggestion

**Comment by mscraigloewen** [comment]
This is now fixed, thank you @WSLUser for the pull request.
