### ISSUE TITLE
WSL is not supported on LTSB

### ISSUE THREAD

**Issue by pleonex** [MicrosoftDocs/WSL#431]
According to the Microsoft and WSL statements in this GitHub issue: https://github.com/Microsoft/WSL/issues/1281
WSL is NOT supported on LTSB, it was left by mistake and disable with one of the latest security updates.
The first paragraph of this page says that it can be installed on LTSB. I guess it should be reviewed the support on LTSC too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual#feedback)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by megaslowpoke** [comment]
2019 LTSC everything works. For the 2016 LTSB the Ubuntu example cannot be executed due to the system requirements "Windows 10 version 16237.0 or higher": https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:regionofsystemrequirementstab

**Comment by mscraigloewen** [comment]
Fixed this to only reference LTSC
