### ISSUE TITLE
Mr.

### ISSUE THREAD

**Issue by fumanbest** [MicrosoftDocs/WSL#432]
How connect Linux with any X - display on Windows

**Comment by fumanbest** [comment]
How connect Linux with any X - display on Windows

**Comment by mscraigloewen** [comment]
Hi @fumanbest , in general all you need to do is run the command: `export DISPLAY=:0` and WSL will be ready to communicate with an X server. For some sample instructions this blog: [Running Linux desktop apps on the Windows Subsystem for Linux by Daniel Aleksandersen](https://www.ctrl.blog/entry/how-to-x-on-wsl.html) has some good instructions and overview (Thank you for the article Daniel!).

We try to keep our docs focused just on WSL, and adding X servers right now is out of the scope of WSL. Thank you for your submission!

**Comment by fumanbest** [comment]
Thanks!
And can i connect ubuntu poker bot with bet365 poker Windiws Desktop klient
from WSL terminal ? Or can i connect some sport bot from WSL terminal with
bet365 site in Windows browser from my sport account ?

На нд, 23.06.2019 г., 0:53 Craig Loewen <notifications@github.com> написа:

**Comment by mscraigloewen** [comment]
I'm unfamiliar with those tools, but in general if they communicate over the internal loopback address (127.0.0.1) then most likely you can connect them. 

I'd recommend trying out if you can, and if you run into a technical problem when doing so please search online and on our Github issues page for a resolution, and if that doesn't work file an issue on our WSL github page: https://github.com/microsoft/wsl 

Thank you!

**Comment by fumanbest** [comment]
Thanks

На пн, 24.06.2019 г., 19:48 Craig Loewen <notifications@github.com> написа:
