### ISSUE TITLE
Update for WSL2: Accessing ports from WSL in Windows

### ISSUE THREAD

**Issue by WSLUser** [MicrosoftDocs/WSL#433]
This currently refers to WSL1 but we need to account for the differences in WSL2. This portion specifically: 

> How do I access a port from WSL in Windows?
> WSL shares the IP address of Windows, as it is running on Windows. As such you can access any ports on localhost e.g. if you had web content on port 1234 you could https://localhost:1234 into your Windows browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd5bfb4-8a38-1f09-0d36-6b9abe9b8b08
* Version Independent ID: 156d9535-c2a5-bc8d-af24-342a13832abf
* Content: [Frequently Asked Questions (FAQ)](https://docs.microsoft.com/en-us/windows/wsl/faq#feedback)
* Content Source: [WSL/faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/faq.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by mscraigloewen** [comment]
You're right! 

However, WSL 2 is currently in preview, only for Windows Insiders, and is expected to have lots of changes and iterations. We'll be looking at overhauling all of the documentation more as WSL 2 gets closer to an official release. For now the UX differences page will suffice. :)
