### ISSUE TITLE
The offline installer instructions don't actually tell you how to install it

### ISSUE THREAD

**Issue by whyiseverythingmadesocomplicated** [MicrosoftDocs/WSL#435]
The page loops to another page, neither of which say how to install once you have downloaded the appx file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by WSLUser** [comment]
> Installing your distro
If you're using Windows 10 you can install your distro with PowerShell. Simply navigate to folder containing the distro downloaded from above, and in that directory run the following command where app_name is the name of your distro .appx file.

> Add-AppxPackage .\app_name.appx

You do know how to scroll right?

**Comment by mscraigloewen** [comment]
Sorry this was an issue that was left open, this issue was opened before I made the changes above. Closing this as it's now resolved!
