### ISSUE TITLE
Error: Undo key "ctrl + z" now working

### ISSUE THREAD

**Issue by thesachinmittal** [MicrosoftDocs/WSL#437]
Went through the documents of troubleshooting, and made changes in properties. All ticked! Still undo key is not working...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by mscraigloewen** [comment]
What do you mean by 'undo?' Are you trying to hit CTRL+Z to undo typing in a character or undo issuing a command? 

If that's the case, then that's not a supported scenario inside of the console.

**Comment by thesachinmittal** [comment]
Ofcourse, I am trying to undo the typed character!

**Comment by mscraigloewen** [comment]
This is something that's as design in the console. CTRL + Z is a key stroke that is used for many different features, and in bash it stops the current running process. So there isn't really an 'undo typing' key.
