### ISSUE TITLE
Installing WSL2, says "--set-version" option invalid

### ISSUE THREAD

**Issue by swun90** [MicrosoftDocs/WSL#438]
`wsl -l` gave `Ubuntu-18.04` and I did use WSL for years.
Today I updated to 1903, and tried to use WSL2. According to the document, run `Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform` in Powershell(Admin), reboot, and run `wsl --set--version Ubuntu-18.04 2`.
But it showed that
"the option --set-version is not valid". (My system is not English, so that is what I translated.)

**Comment by mscraigloewen** [comment]
Please note that you'll need a build newer than version 1903. You can get these builds as part of the [Windows Insiders program](https://insider.windows.com/en-us/). In the install instructions we say you need Windows build version 18917 or higher.

So please upgrade and then you can use WSL 2!

**Comment by swun90** [comment]
Sorry my bad. I thought WSL2 came with this May update
