### ISSUE TITLE
I lost access to disk C: from WSL as I recover it?

### ISSUE THREAD

**Issue by NerioVillalobos** [MicrosoftDocs/WSL#440]
after making installations of several products in wsl when turning off and on equipment and doing a "df" I notice that the unit "/ c" is not mounted and I can not find a way to mount it that I can do to recover its connection and use it again?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by mscraigloewen** [comment]
Can you please paste the output of your `df` command?

As well if you run: `sudo mount -t drvfs C: /mnt/c` you'll mount your C drive to /mnt/c .

**Comment by NerioVillalobos** [comment]
Thank you very much, the indicated command worked, what I do not understand is that I must apply it every time I enter it does not keep it even though it closes the environment.

**Comment by mscraigloewen** [comment]
What are the contents inside of this file: `/etc/wsl.conf` ? You can turn off auto mounting in that file which might be why you aren't seeing it.

**Comment by craigloewen-msft** [comment]
Closing this issue out as we're cleaning up this repository. Thanks for filing!
