### ISSUE TITLE
No lxrun and manual deletion doesn't work (1903)

### ISSUE THREAD

**Issue by charlesroper** [MicrosoftDocs/WSL#441]
I'm using 1903 and was attempting to remove my legacy installation using the above instructions. The `lxrun` command no longer exists and the manual deletion methods would not work (the files would not delete using the commands given).

What I had to do instead is run `wslconfig /u Legacy`. I discovered the distro name by running `wslconfig /l`. Given these instructions refer to "Uninstalling/Removing the legacy distro", can the new commands be included here or on the [new](https://docs.microsoft.com/en-us/windows/wsl/install-win10) page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df13cc0f-9f70-c507-d70d-ed8b3c4735ea
* Version Independent ID: 821b82b7-5b0a-ec6c-4a89-cf58843f66a8
* Content: [Install or remove on Windows 10 Anniversary Update or Creators Update](https://docs.microsoft.com/en-us/windows/wsl/install-legacy)
* Content Source: [WSL/install-legacy.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-legacy.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by mscraigloewen** [comment]
Fixed!
