### ISSUE TITLE
Rename Windows Store to Microsoft Store

### ISSUE THREAD

**Issue by johmarkMSFT** [MicrosoftDocs/WSL#442]
This:
1. Download and install from the Windows Store (see below)
Should be renamed to "Microsoft Store". I opened Windows 10 search, typed Windows Store and got no results because it's called the Microsoft Store.
There are other places in the article where it's referred to as Windows Store too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by mscraigloewen** [comment]
Fixed!

**Comment by mwjo** [comment]
Thanks @mscraigloewen 😊
