### ISSUE TITLE
error: A device attached to the system is not function

### ISSUE THREAD

**Issue by mrdsh** [MicrosoftDocs/WSL#443]
Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/
![image](https://user-images.githubusercontent.com/21301309/60504143-a5cf2680-9cde-11e9-9a8a-2606a34ad26e.png)

**Comment by Biswa96** [comment]
Duplicate #4155

**Comment by Biswa96** [comment]
Duplicate https://github.com/microsoft/WSL/issues/4155
