### ISSUE TITLE
WSL 2 requires manual management of VHD

### ISSUE THREAD

**Issue by lornova** [MicrosoftDocs/WSL#444]
It is false that "WSL 2 will NOT be a traditional VM experience. A traditional VM experience [...] requires your time to manage it. WSL 2 does not have these attributes.". In fact, we have to manually manage the VHD if it reaches its max size.
Personally, I'm very sad that you give up on WSL 1, which was very clever. WSL 2 is just a VM, no matter how you try to manage it "behind the scenes". I will use WSL 1 as long as possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c94eeb-5969-cb2d-fc63-1d4074070812
* Version Independent ID: def2349f-07a2-e772-0583-e5e3ce5983d4
* Content: [About WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-about#feedback)
* Content Source: [WSL/wsl2-about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-about.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by mscraigloewen** [comment]
We currently [have no plans to give up on, or deprecate WSL 1](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#what-will-happen-to-wsl-1-will-it-be-abandoned). 

Yes, WSL 2 uses a VM. And yes there are cases when you will run into its VM behaviour, especially in these early builds! However, our goal is to improve these experiences to make it feel the same as WSL 1. When I use WSL 2 I don't worry about starting up or stopping it, or worry about its idle CPU usage, or worry about 'How will I access my files' when doing work inside of it. For these reasons alone I would describe the experience as 'Not a traditional VM experience', and this will only continue with further improvements. 

Thank you for your feedback!
