### ISSUE TITLE
WSL 2 docs: Hyper-V should be enabled

### ISSUE THREAD

**Issue by taoyichen** [MicrosoftDocs/WSL#445]
When I first tried to use WSL 2, I got the error:
Error: 0x80370109 The operation timed out because a response was not received from the virtual machine or container.
This issue was solved by enabling hyper-v.
I was also reading that WSL 2 needs hyper-v.

So, making sure hyper-v is enabled should be included in the docs page at:
https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

**Comment by mscraigloewen** [comment]
You don't need Hyper-V to use WSL 2. You just need the `Virtual Machine Platform` component. Did you have this component enabled and still WSL 2 didn't work?

**Comment by taoyichen** [comment]
I've got it working only after enabled hyper-v.
Well, I've read it here which says you use hyper-v:
https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq

_Does WSL 2 use Hyper-V? Will it be available on Windows 10 Home?
WSL 2 will be available on all SKUs where WSL is currently available, including Windows 10 Home.

The newest version of WSL **uses Hyper-V** architecture to enable its virtualization. This architecture will be available in an optional component that is a subset of the Hyper-V feature. This optional component will be available on all SKUs. You can expect to see more details about this experience soon as we get closer to the WSL 2 release._

**Comment by taoyichen** [comment]
Although, I still don't have network connectivity on wsl 2. Had them on wsl 1.

**Comment by Biswa96** [comment]
HyperV isn't fully same as VM platform. In short, see this YouTube video about [the different types of containers and usages](https://m.youtube.com/watch?v=rIfH8ouEctk).

**Comment by mscraigloewen** [comment]
I've adjusted the FAQ to mention `Virtual Machine platform` explicitly, and I'll keep an eye on issues to see if enabling Hyper-V fixes it for anyone else. Thanks for filing this!

**Comment by davevs** [comment]
I did some more digging on the minimal configuration and I got it working after enabling these 3 features:

Hyper-V > Hyper-V Platform > Hyper-V Services
Virtual Machine Platform
Windows Hypervisor Platform

So enabling the full Hyper-V feature is not necessary.

**Comment by nguyenvulong** [comment]
from [Microsoft docs](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq)

`The newest version of WSL uses _**Hyper-V architecture**_ to enable its virtualization`
So yes, WSL2 only uses **some** services from Hyper-V. The text can be easily misread though.

**Comment by diegosasw** [comment]
I have Ubuntu on WSL 2 running on windows 10, and docker for desktop using WSL 2
and I have removed HyperV from Windows completely.
I've got enabled Virtual Machine Platform though as @craigloewen-msft suggests.

**Comment by jefmes** [comment]
Interesting conundrum here on an AMD Ryzen system using WSL2. I just installed Android Studio's latest release (as of 2/4/2022) and the "Android Emulator Hypervisor Driver for AMD Processors" is required (or at least recommended). I followed their directions to get it installed after the first attempt failed, and discovered that... "Hyper-V must be disabled. Refer to this page for more information."  So...if you're an AMD user and use WSL2, I guess you can't also use Android Studio's emulation driver? That's very...unfortunate, and irritating. Just sharing in case someone else runs into a similar thing and stumbles into this WSL issue.

**Comment by taoyichen** [comment]
Please start your own thread.

**Comment by jefmes** [comment]
> Please start your own thread.

The issue is already closed and this is certainly related, and I will be trying some of the recommendations by @craigloewen-msft  and @davevs because other users may find it helpful, too. That's why we share this information with each other.
