### ISSUE TITLE
VMware Workstation doesn't work anymore after installed WSL 2

### ISSUE THREAD

**Issue by ogrishman** [MicrosoftDocs/WSL#446]
I followed the document and installed WSL 2. After that, I found all my VMware Workstation virtual machines can't start up. I'm not sure if this is caused by WSL 2 and I just want to get some suggestions from you guys. Thanks.

**Comment by mscraigloewen** [comment]
Currently VMWare is incompatible with WSL 2, meaning you won't be able to use them at the same time. Please see our [WSL 2 FAQ page](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#will-i-be-able-to-run-wsl-2-and-other-3rd-party-virtualization-tools-such-as-vmware-or-virtualbox) for why that is the case.

**Comment by Biswa96** [comment]
As a workaround, you can create a BCD entry with `bcdedit` tool where one with hypervisor enabled and another one with disabled. In the first, run WSL2 and use VMware or VirtualBox (or any type 2 hypervisor) in the later.

**Comment by n3rd4i** [comment]
One could do this from command line:
`choco install boot-no-hyperv`

Which will create BCD entry default to NoHyperV (could potential be changed later)

**Comment by 00f0uchmybone5** [comment]
Same thing happened to me and now I’m mad at myself for ever even installing WSL. Is there anyway I can uninstall WSL entirely? I just want virtualbox back.
