### ISSUE TITLE
WSL2 UX docs - mention Linux LAN binding requirement

### ISSUE THREAD

**Issue by Oxylibrium** [MicrosoftDocs/WSL#449]
In the WSL2 UX changes doc, there is a mention of how to access Linux network apps from Windows, but I think it'd also help to mention that the app needs to be exposed to the LAN from the Linux perspective, (i.e. bound to `0.0.0.0`) for you to be able to see it from Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [UX Changes between WSL 1 and WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#feedback)
* Content Source: [WSL/wsl2-ux-changes.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-ux-changes.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by mscraigloewen** [comment]
And fixed! Thanks for filing this. :)
