### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by blueharvest-ben** [MicrosoftDocs/WSL#450]
run [a] GNU/Linux environment -- including most command-line tools, utilities, and applications -- directly on Windows. 

OR

run GNU/Linux environment[s] -- including most command-line tools, utilities, and applications -- directly on Windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3be148fb-e4a9-83b5-5b5a-7834eed7052f
* Version Independent ID: f583bc11-fe60-bb2c-af2b-dc0dae9fe81f
* Content: [Learn about the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about#feedback)
* Content Source: [WSL/about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/about.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
Added in a fix for the typo. Thanks for filing this!
