### ISSUE TITLE
Add command for checking Windows version

### ISSUE THREAD

**Issue by lanatmwan** [MicrosoftDocs/WSL#451]
Since this is dependent on a minimal version of Windows. It is probably worth mentioning on the page how you can check it. 

[version]::Parse($PSVersionTable.OS.Split()[2]) -gt '10.0.18917.0'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by mscraigloewen** [comment]
We try to keep the Windows docs as short and straight forward as possible. It's very easy to find out how to check your Windows build version via any search engine. and so I believe this change may add some unnecessary text. Thank you for the suggestion, but in the interest of keeping the docs short I won't be adding instructions on checking your Windows Build number.

**Comment by marckassay** [comment]
@craigloewen-msft, I suppose intentions to keep documentation concise are to guide the reader without him or her losing focus on the docs objective. And with this intention docs are designed to target (at least what you think) the majority of reader's environments are. As for other readers, they'll need to switch their focus from the doc to another external resource such as what you mentioned. My point I'm making here is to consider having additional resource(s) in a step that is in perhaps a 'collapsed' div which the user can expand if needed. Perhaps having a link that will expand, this div I'm referring to, with a label of, 'Having issues with this step?'.

I hope that helps.
