### ISSUE TITLE
Getting an error when I try set my default user

### ISSUE THREAD

**Issue by ZamzamMumin** [MicrosoftDocs/WSL#452]
PS C:\Users\zmumin\Documents\WSLDistro\CentOS> ./CentOS config --default-user zmumin
ERROR
HRESULT:0x80004005
Press any key to continue...

That is the error am getting! Anyone please help.

I am using CentOS WSL Distro so kindly help me.

**Comment by mscraigloewen** [comment]
Hi @ZamzamMumin  , 

This repo is for the Microsoft Docs page. Please post your technical issue [on the WSL github repo](https://github.com/microsoft/wsl/issues) and we will support you there!
