### ISSUE TITLE
System has not been booted with systemd as init system (PID 1). Can't  operate

### ISSUE THREAD

**Issue by werewolf666** [MicrosoftDocs/WSL#457]
system:win10Pro-1903-18362.239
subLinux:ubuntu1804

when is input 【sudo systemctl start docker】but i can not start docker-daemon ,it show me 
this:【System has not been booted with systemd as init system (PID 1). Can't 
operate】
so,is i did wrong?

**Comment by mscraigloewen** [comment]
Instead of using `sudo systemctl start docker` use: `sudo /etc/init.d/docker start` , as of right now we do not have systemd in WSL 2.

**Comment by imdpkmr** [comment]
The same is not working when trying to start mongodb service.

**Comment by craigloewen-msft** [comment]
@imdpkmr are you trying to use `systemctl`? Please try using the mongo equivalent of the command I put above, or `sudo service mongod start` , does that fix your issue?

**Comment by cankush625** [comment]
I have also faced the same issue when I'm using the `systemctl` command for starting the puppet service.

Instead of that, I had used the `service puppet start ` command on ubuntu and it just worked fine for me. I hope someone gets help from this.

**Comment by ZhengxunWu** [comment]
I also face the same issue with postgresql. do you have any idea how to solve it? thanks

**Comment by cankush625** [comment]
> I also face the same issue with postgresql. do you have any idea how to solve it? thanks

@ZhengxunWu Try the command `service postgresql start` for starting the postgresql service instead of `sudo systemctl start postgresql`

**Comment by ZhengxunWu** [comment]
> > I also face the same issue with postgresql. do you have any idea how to solve it? thanks
> 
> @ZhengxunWu Try the command `sudo service postgresql start` for starting the postgresql service instead of `sudo systemctl start postgresql`

problem solved.

**Comment by abmruman** [comment]
Some services like docker (standalone, ubuntu version, installed using bash) still might not run even if you use `sudo /etc/init.d/docker start` or `sudo service docker start` or `/etc/init.d/docker start`.

What you have to do is, run the linux subsystem as administrator by right clicking from start menu.
This will solve the issue and `sudo service` command will execute as it should, as a sudo user.

**Comment by scotkrauseverint** [comment]
@abmruman  You nailed it, thank you!  Now when I open the Windows 10 command window as administrator, and then I start wsl, I am able to run systemctl enable docker successfully.  Thank you!

> Some services like docker (standalone, ubuntu version, installed using bash) still might not run even if you use `sudo /etc/init.d/docker start` or `sudo service docker start` or `/etc/init.d/docker start`.
> 
> What you have to do is, run the linux subsystem as administrator by right clicking from start menu.
> This will solve the issue and `sudo service` command will execute as it should, as a sudo user.

**Comment by abmruman** [comment]
Glad I could help, @scotkrauseverint

**Comment by willyjchen** [comment]
May I ask is there suggested command for `systemctl enable` equivalent?

**Comment by ragvri** [comment]
Also one for `sudo systemctl daemon-reload`?

**Comment by CoderMonkie** [comment]
## Can not start service of firewalld (WSL Ubuntu 18.04.3 LTS)

```bash
$ sudo service firewalld start
 * Starting dynamic firewall daemon firewalld                       [ OK ]

$ sudo service firewalld status
 * firewalld is not running
```

there's no error, but it seems there should be...

---

```bash
$ sudo firewall-cmd --list-ports
FirewallD is not running

$ sudo irewall-cmd --list-services
FirewallD is not running
```

**Comment by estape** [comment]
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to talk to init daemon.

I got this when I try to run
![Anotação 2020-04-18 232009](https://user-images.githubusercontent.com/13343583/79677784-2c4fe880-81cb-11ea-821c-fa6862a4a494.png)
 sudo tasksel

I was try the methodo to install the GUI of Ubuntu.

**Comment by xiaomi-yaojingwei** [comment]
> Some services like docker (standalone, ubuntu version, installed using bash) still might not run even if you use `sudo /etc/init.d/docker start` or `sudo service docker start` or `/etc/init.d/docker start`.
> 
> What you have to do is, run the linux subsystem as administrator by right clicking from start menu.
> This will solve the issue and `sudo service` command will execute as it should, as a sudo user.

it   

> Some services like docker (standalone, ubuntu version, installed using bash) still might not run even if you use `sudo /etc/init.d/docker start` or `sudo service docker start` or `/etc/init.d/docker start`.
> 
> What you have to do is, run the linux subsystem as administrator by right clicking from start menu.
> This will solve the issue and `sudo service` command will execute as it should, as a sudo user.

it works for me, run subsystem as administrator,   and  use 'sudo /etc/init.d/docker start'.

**Comment by xd003** [comment]
`hostnamectl set-hostname xyz`
I am getting this same error while using the above mentioned - System has not been booted with systemd as init system (PID 1). 
Does someone know of a alternative working command for this ?

**Comment by cypherstream** [comment]
I can't upgrade InfluxDB because part of the script in apt-get install infludb results in an error determining the current runlevel.  There are also a lot of other packages that just wont run.

I'm going back to Hyper-V for the time being until you all get it worked out, ok?

**Comment by danielcinome** [comment]
> Es posible que algunos servicios como docker (versión independiente, ubuntu, instalada con bash) aún no se ejecuten, incluso si usa `sudo /etc/init.d/docker start`or `sudo service docker start`o `/etc/init.d/docker start`.
> 
> Lo que debe hacer es ejecutar el subsistema de Linux como administrador haciendo clic derecho en el menú de inicio.
> Esto resolverá el problema y el `sudo service`comando se ejecutará como debería, como usuario de sudo.

Hola, he seguido los pasos para resolver mi problema sin embargo esto no ha funcionado para mi. cuando ejecuto  `sudo /etc/init.d/docker start` obtengo ` sudo: /etc/init.d/docker: command not found` . Que podria hacer en ese caso. Gracias

**Comment by bisomaticc** [comment]
# when I run sudo /etc/init.d/docker start I get sudo: /etc/init.d/docker: command not found. What could I do in that case. same error for me

**Comment by itechbear** [comment]
> 
> # when I run sudo /etc/init.d/docker start I get sudo: /etc/init.d/docker: command not found. What could I do in that case. same error for me

Are you using the `docker.io` package from the official ubuntu repository? In that case, just run `sudo dockerd`.

**Comment by felipementel** [comment]
I had this problem running WSL 2

the solution was the command

     $ sudo dockerd

if after that you still have a problem with permission, run the command:

     $ sudo usermod -aG docker your-user

**Comment by TheTechOddBug** [comment]
@felipementel Your answer is the most near to solve my problem. I can run docker commands but now I'm getting a "docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:319: getting the final child's pid from pipe caused \"EOF\"": unknown. ERRO[0006] error waiting for container: context canceled". Could you help me with this? Thank you very much in advance for your help.

**Comment by felipementel** [comment]
Hi @TheTechOddBug !
i think that i can help you, sure!

So, tell me what are you doing to construction this error?
And tell me about your environment ...

**Comment by buildhigh20** [comment]
> Instead of using `sudo systemctl start docker` use: `sudo /etc/init.d/docker start` , as of right now we do not have systemd in WSL 2.

Still it is showing me /etc/init.d/docker : command not found

**Comment by buildhigh20** [comment]
it still showing /etc/init.d/docker: command not found.

**Comment by TheTechOddBug** [comment]
> Hi @TheTechOddBug !
> i think that i can help you, sure!
> 
> So, tell me what are you doing to construction this error?
> And tell me about your environment ...

Well @felipementel, I upgrade my system to Windows 10 2004, enabled WSL2 and installed an Ubuntu distribution. I set WSL v2 as default. I installed docker inside that Ubuntu distribution and follow your comments to make docker commands work but when I try to run the hello-world simple container with docker run, I got the previously commented error. Again, thank you for your help!

**Comment by firjan** [comment]
hi @TheTechOddBug,

Check this --> https://success.docker.com/article/error-oci-runtime-create-failed-docker-1809

**Comment by felipementel** [comment]
hi @TheTechOddBug,

check this --> https://success.docker.com/article/error-oci-runtime-create-failed-docker-1809

**Comment by andremeiras** [comment]
> ```
> **sudo dockerd**
> ```

Thank you Felipe. It worked for me!

**Comment by Jont828** [comment]
Is there any equivalent to `sudo systemctl enable docker` at the moment? I'd like to be able to start the service automatically on boot.

**Comment by eaglegoboom** [comment]
so how does docker help u fix issues with the System has not been booted with systemd as init system (PID 1), having same issue on kali linux wsl during the setup of openvas, when I do the openvas-setup or the openvas-check-setup gives me that and everything else is running.

**Comment by MemphisMeng** [comment]
> > > I also face the same issue with postgresql. do you have any idea how to solve it? thanks
> > 
> > 
> > @ZhengxunWu Try the command `sudo service postgresql start` for starting the postgresql service instead of `sudo systemctl start postgresql`
> 
> problem solved.

service is unrecognized in my scenario.

**Comment by c0x65o** [comment]
For people looking for ways to enable services, I did find this and it was helpful to me https://github.com/shayne/wsl2-hacks/blob/master/README.md

**Comment by jjxtra** [comment]
Is enabling systemd / systemctl on the roadmap anytime soon? Going back to Ubuntu VM until then...

**Comment by Biswa96** [comment]
Recently, there is something added. See my comment here https://github.com/microsoft/WSL/issues/994#issuecomment-698927438

**Comment by vimalpanchal88** [comment]
I am also getting this error while i am starting any service in docker debian_10_buster container. Actully i had install debian_10_buster image in docker and i want to restart some services like ntpd, networking, freeswitch using systemctl cmd but it's throwing an error like this. someone can help me to resolve this issue.
**Error :- System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down**

**Comment by ankitkhalaur** [comment]
> @imdpkmr are you trying to use `systemctl`? Please try using the mongo equivalent of the command I put above, or `sudo service mongod start` , does that fix your issue?
@craigloewen-msft 
This returns `mongod: unrecognized service`. I understand that this is because mongodb is not installed yet. But the error in the issue title appears when I try to install mongodb itself. How do I come out of this loop?

**Comment by achourali** [comment]
> 
> 
> May I ask is there suggested command for `systemctl enable` equivalent?

did you find an equivalent ?

**Comment by Ravineesh** [comment]
If you are having WSL2, and running Ubuntu on Windows,

In Windows, start the Ubuntu terminal as Administrator
then run `sudo service docker start`

**Comment by achourali** [comment]
> If you are having WSL2, and running Ubuntu on Windows,
> 
> In Windows, start the Ubuntu terminal as Administrator
> then run `sudo service docker start`

i have docker desktop on windows and wsl2 and ubuntu too 
i followed what you said but i get this error on ubuntu 
`docker: unrecognized service`

**Comment by linuxadmin25** [comment]
Hi,
I am facing the same issue, and when I'm starting docker service on WS2[Ubuntu Interface], docker service immediately starting and shutting down.
This is when I'm trying to reboot the centos image ::
System has not been booted with systemd as init system (PID 1). Can't operate.

From Ubuntu Interface ::
tanmayroot@DESKTOP-S3H1OVS:/var/tmp/dock$ sudo service docker start
[sudo] password for tanmayroot:
 * Starting Docker: docker                                                                                                                                           [ OK ]
tanmayroot@DESKTOP-S3H1OVS:/var/tmp/dock$ sudo service docker status
 * Docker is not running

Ami missing something? or doing some blunder?

Regards,
Tanmay

**Comment by linuxadmin25** [comment]
> Hi @TheTechOddBug !
> i think that i can help you, sure!
> 
> So, tell me what are you doing to construction this error?
> And tell me about your environment ...

I ran **sudo dockerd**, and i ended up on ::
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.4 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)

Any thoughts to it?
PS :: After sudo dockerd, I ran "sudo apt-get update -y".

**Comment by Ravineesh** [comment]
> Hi,
> I am facing the same issue, and when I'm starting docker service on WS2[Ubuntu Interface], docker service immediately starting and shutting down.
> This is when I'm trying to reboot the centos image ::
> System has not been booted with systemd as init system (PID 1). Can't operate.
> 
> From Ubuntu Interface ::
> tanmayroot@DESKTOP-S3H1OVS:/var/tmp/dock$ sudo service docker start
> [sudo] password for tanmayroot:
> 
> * Starting Docker: docker                                                                                                                                           [ OK ]
>   tanmayroot@DESKTOP-S3H1OVS:/var/tmp/dock$ sudo service docker status
> * Docker is not running
> 
> Ami missing something? or doing some blunder?
> 
> Regards,
> Tanmay

Try this, 
Once the installation of docker is finished, do the following commands in order
1.  `sudo groupadd docker` 
2. `sudo usermod -aG docker 'your_user_name'` 
3.  su `'your_user_name'`
4. `sudo service docker start`
5. `docker version` (check whether the docker client and server engine is running)

Reference:- https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket.

**Comment by burgerking12** [comment]
Just closed this, even you got no answer!! You can't make this works af. Idk why we need docker?!!?!>!!?!?!?!?!, search everywhere to solve this f*, no one works, Im betting you guys this is not just me! almost one years to find how to solve this. idk just... idk. Cargo and  substrate saving my hole life.

**Comment by danigrayston** [comment]
Hello, I am having this issue with rpcbind.
I'm running Ubuntu 20.04.1 under Windows 10 (WSL2) and am trying to mount a directory in the filesystem. Trying to solve issues with doing this I've realised I can't restart rpcbind from the command line.

```
$ sudo /etc/init.d/rpcbind start
 * Starting RPC port mapper daemon rpcbind                                                                              ln: failed to create symbolic link '/run/sendsigs.omit.d/rpcbind': No such file or directory
                                                                                                                 [fail]
$ sudo service rpcbind start
 * Starting RPC port mapper daemon rpcbind                                                                              ln: failed to create symbolic link '/run/sendsigs.omit.d/rpcbind': No such file or directory
                                                                                                                 [fail]
$ systemctl start rpcbind
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```
In my process list rpcbind shows as:
_rpc      1783   266  0 14:47 ?        00:00:00 /sbin/rpcbind -w

Which if I compare to a linux box:
root       941     1  0 Nov03 ?        00:00:01 /sbin/rpcbind -f -w

So for some reason rpc isn't a root process, I'm guessing because it's not using systemd.
I'm not really familiar with this area and keep going around in circles. Googling so far hasn't bore fruit. Anyone have any ideas?

**Comment by albasyir** [comment]
systemd still not working until now?

**Comment by absentm** [comment]
It works on my machine with WSL2:

1.  Install daemonize  and fontconfig
`$ sudo apt install -y fontconfig daemonize`

2. Edit /etc/profile
`SYSTEMD_PID=$(ps -ef | grep '/lib/systemd/systemd --system-unit=basic.target$' | grep -v unshare | awk '{print $2}')

if [ -z "$SYSTEMD_PID" ]; then
   sudo /usr/bin/daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target
   SYSTEMD_PID=$(ps -ef | grep '/lib/systemd/systemd --system-unit=basic.target$' | grep -v unshare | awk '{print $2}')
fi

if [ -n "$SYSTEMD_PID" ] && [ "$SYSTEMD_PID" != "1" ]; then
    exec sudo /usr/bin/nsenter -t $SYSTEMD_PID -a su - $LOGNAME
fi`

3. Edit /etc/sudoers 
`%sudo ALL=(ALL) NOPASSWD: /usr/sbin/daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target
%sudo ALL=(ALL) NOPASSWD: /usr/bin/nsenter -t [0-9]* -a su - [a-zA-Z0-9]*`

4. Restart WSL2 or source profile
`$ sudo source /etc/profile`

[Support by Running Snaps on WSL2 (Insiders only for now)](https://forum.snapcraft.io/t/running-snaps-on-wsl2-insiders-only-for-now/13033)

**Comment by jjxtra** [comment]
`sudo: source: command not found`

**Comment by Fleetingold** [comment]
> It works on my machine with WSL2:
> 
> 1. Install daemonize  and fontconfig
> 
> ```
> $ sudo apt install -y fontconfig daemonize
> ```
> 
> 1. Edit /etc/profile
> 
> ```
> SYSTEMD_PID=$(ps -ef | grep '/lib/systemd/systemd --system-unit=basic.target$' | grep -v unshare | awk '{print $2}')
> 
> if [ -z "$SYSTEMD_PID" ]; then
>    sudo /usr/bin/daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target
>    SYSTEMD_PID=$(ps -ef | grep '/lib/systemd/systemd --system-unit=basic.target$' | grep -v unshare | awk '{print $2}')
> fi
> 
> if [ -n "$SYSTEMD_PID" ] && [ "$SYSTEMD_PID" != "1" ]; then
>     exec sudo /usr/bin/nsenter -t $SYSTEMD_PID -a su - $LOGNAME
> fi
> ```
> 
> 1. Edit /etc/sudoers
> 
> ```
> %sudo ALL=(ALL) NOPASSWD: /usr/sbin/daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target
> %sudo ALL=(ALL) NOPASSWD: /usr/bin/nsenter -t [0-9]* -a su - [a-zA-Z0-9]*
> ```
> 
> 1. Restart WSL2 or source profile
> 
> ```
> $ sudo source /etc/profile
> ```
> 
> [Support by Running Snaps on WSL2 (Insiders only for now)](https://forum.snapcraft.io/t/running-snaps-on-wsl2-insiders-only-for-now/13033)

Yes,it works.I know this from https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/#minikube-enabling-systemd
same from  Daniel Llewellyn.

**Comment by mcr-web** [comment]
how do i boot in systemd mode im using ubuntu on windows 10 since its not booted in systemd mode apt doesnt work everything doesnt work and my windows 10 is crashing alot now this is day 3 using this new thing so i dont know what im doing it all started when i wanted to use ble.recon but to get there u need bettercap then it said hci socket not there now its not booting in  systemd mode and ya it crashed fast for my first time use so did i wreck everything in my way or can i save my mess and boot in systemd mode (and side note when i start ubuntu it says -bash: /usr/bin/locale-check: no such file or directory) should i be consernded about that

**Comment by heidemn** [comment]
> The same is not working when trying to start mongodb service.

@imdpkmr @ankitkhalaur I came across this issue, and wrote a SysV init script that allows to start and stop MongoDB without Systemd. Seems to work fine, even after the MongoDB installation with `apt-get` has returned an error.  
In case that it's useful for somebody: https://github.com/heidemn/mongod-sysv

Of course the above-mentioned generic systemd workaround might be the better approach.

**Comment by maximus-primo** [comment]
> > I also face the same issue with postgresql. do you have any idea how to solve it? thanks
> 
> @ZhengxunWu Try the command `sudo service postgresql start` for starting the postgresql service instead of `sudo systemctl start postgresql`

Thank you very much! Worked like a charm <3

**Comment by prasadpattanshetty** [comment]
> Some services like docker (standalone, ubuntu version, installed using bash) still might not run even if you use `sudo /etc/init.d/docker start` or `sudo service docker start` or `/etc/init.d/docker start`.
> 
> What you have to do is, run the linux subsystem as administrator by right clicking from start menu.
> This will solve the issue and `sudo service` command will execute as it should, as a sudo user.

**Comment by prasadpattanshetty** [comment]
Thank you very much, This solved my issue.

**Comment by zkkxu** [comment]
> Instead of using `sudo systemctl start docker` use: `sudo /etc/init.d/docker start` , as of right now we do not have systemd in WSL 2.

that's great! it works for me

**Comment by harem234** [comment]
service --status-all

service memcached status

**Comment by amantayal6797** [comment]
> Some services like docker (standalone, ubuntu version, installed using bash) still might not run even if you use `sudo /etc/init.d/docker start` or `sudo service docker start` or `/etc/init.d/docker start`.
> 
> What you have to do is, run the linux subsystem as administrator by right clicking from start menu.
> This will solve the issue and `sudo service` command will execute as it should, as a sudo user.

This works for me

**Comment by amantayal6797** [comment]
This works for me

**Comment by himalayashinde** [comment]
> Some services like docker (standalone, ubuntu version, installed using bash) still might not run even if you use `sudo /etc/init.d/docker start` or `sudo service docker start` or `/etc/init.d/docker start`.
> 
> What you have to do is, run the linux subsystem as administrator by right clicking from start menu.
> This will solve the issue and `sudo service` command will execute as it should, as a sudo user.

@abmruman Thanks for your valuable comment it helped me to solve my issue for WSL 2 windows ubuntu

**Comment by abmruman** [comment]
> > Some services like docker (standalone, ubuntu version, installed using bash) still might not run even if you use `sudo /etc/init.d/docker start` or `sudo service docker start` or `/etc/init.d/docker start`.
> > What you have to do is, run the linux subsystem as administrator by right clicking from start menu.
> > This will solve the issue and `sudo service` command will execute as it should, as a sudo user.
> 
> @abmruman Thanks for your valuable comment it helped me to solve my issue for WSL 2 windows ubuntu

@himalayashinde Happy to be able to help.

**Comment by yipliu** [comment]
Hi @Biswa96,
Could you make it clearer? 
I'm new here.  And I occuer the issue:
```bash
System has not been booted with systems as init system (PID 1)..
```
when I run this command
```bash
sudo systemctl restart docker
```
Thank you!

**Comment by hoangdacviet** [comment]
Try Shutdown everything: Build 18917+

wsl.exe --shutdown

Terminate specific distro: Windows 1903+

wsl.exe -t <DistroName>

**Comment by anotcat** [comment]
```bash
 [in] sudo systemctl status mariadb
[out] System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```
wsl debian10

how can fix it？

**Comment by Saurabhdaswant** [comment]
> @imdpkmr are you trying to use `systemctl`? Please try using the mongo equivalent of the command I put above, or `sudo service mongod start` , does that fix your issue?

I used this command but i got the answer : mongod: unrecognized service

**Comment by Saurabhdaswant** [comment]
> Instead of using `sudo systemctl start docker` use: `sudo /etc/init.d/docker start` , as of right now we do not have systemd in WSL 2.

does this work with mongod?

**Comment by Saurabhdaswant** [comment]
> sudo /etc/init.d/docker start

i did this with mongod but it said : sudo: /etc/init.d/mongod: command not found

**Comment by Saurabhdaswant** [comment]
> I have also faced the same issue when I'm using the `systemctl` command for starting the puppet service.
> 
> Instead of that, I had used the `service puppet start ` command on ubuntu and it just worked fine for me. I hope someone gets help from this.

i used this for mongod but intead i got this error : mongod: unrecognized service

**Comment by Saurabhdaswant** [comment]
> > Some services like docker (standalone, ubuntu version, installed using bash) still might not run even if you use `sudo /etc/init.d/docker start` or `sudo service docker start` or `/etc/init.d/docker start`.
> > What you have to do is, run the linux subsystem as administrator by right clicking from start menu.
> > This will solve the issue and `sudo service` command will execute as it should, as a sudo user.
> 
> it
> 
> > Some services like docker (standalone, ubuntu version, installed using bash) still might not run even if you use `sudo /etc/init.d/docker start` or `sudo service docker start` or `/etc/init.d/docker start`.
> > What you have to do is, run the linux subsystem as administrator by right clicking from start menu.
> > This will solve the issue and `sudo service` command will execute as it should, as a sudo user.
> 
> it works for me, run subsystem as administrator, and use 'sudo /etc/init.d/docker start'.

again i got this error : sudo: /etc/init.d/mongod: command not found

**Comment by craigloewen-msft** [comment]
@Saurabhdaswant mongo doesn't include a /etc/init.d/mongod script by default. But here are docs on how to do this:
https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database#add-the-init-script-to-start-mongodb-as-a-service

**Comment by heidemn** [comment]
@thewackyindian @gaur-abhi524 Find here a script for the full installation of MongoDB 5.0 in WSL2, Ubuntu 20.04:
https://github.com/heidemn/mongod-sysv#full-installation-of-mongodb

**Comment by Mayor294** [comment]
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down


Am having this issue now in my termux 🤦🏽‍♂️🤦🏽‍♂️🤦🏽‍♂️ how can i solve this?

**Comment by vimalpanchal88** [comment]
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> 
> 
> Am having this issue now in my termux 🤦🏽‍♂️🤦🏽‍♂️🤦🏽‍♂️ how can i solve this

Use:-

docker container run -d --hostname <hostname> --name <name> privileged=true <image_name> /sbin/init

**Comment by SneedLOL** [comment]
sneed

**Comment by d1mnewz** [comment]
If you wish to run systemctl, there is a way for it in WSL2. You can follow the gist https://gist.github.com/djfdyuruiry/6720faa3f9fc59bfdf6284ee1f41f950

**Comment by AllanOricil** [comment]
For some reason, my WSL has not been updated to 2, and my windows build is 19043. Can anyone help me to know how I can do it? I have already tried to set the default version to 2, downloaded a new image, but it started on version 1. I already tried to convert an image to version 2, it says it will take a while, but it actully did nothing.

**Comment by stonkeep** [comment]
> May I ask is there suggested command for `systemctl enable` equivalent?

systemctl enable docker
Saved my life

**Comment by oonsamyi** [comment]
> @Saurabhdaswant mongo doesn't include a /etc/init.d/mongod script by default. But here are docs on how to do this: https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database#add-the-init-script-to-start-mongodb-as-a-service
It helped usage mongo on WSL2. Thank you!

**Comment by alifarabi** [comment]
if you use wsl, at  first please be sure you run docker windows and then try wsl for docker command

**Comment by thenrique88** [comment]
> Instead of using `sudo systemctl start docker` use: `sudo /etc/init.d/docker start` , as of right now we do not have systemd in WSL 2.

March, 2022. Your answer helped me! Worked for me!

**Comment by ycllz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
已收到

**Comment by jerrychong25** [comment]
> Instead of using `sudo systemctl start docker` use: `sudo /etc/init.d/docker start` , as of right now we do not have systemd in WSL 2.

Thanks @craigloewen-msft !

**Comment by ycllz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
已收到

**Comment by franciskinyuru** [comment]
I have deployed a flask application on wsl 20.04.4, create the service under /etc/systemd/system but the command

>  sudo service myservice

 start does not work 
Also the service not in the /etc/init.d since have created it myself

**Comment by doncadavona** [comment]
How do we manage timezones in WSL 2 Ubuntu 22.04?

$ `timedatectl`

Getting this error:
```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

**Comment by felipetssilva** [comment]
I was trying to install k3s on wsl and was running into this issue....

Simply execute /etc/init.d$ curl -sfL https://get.k3s.io | sudo bash - (from /etc/init.d ) and it works like magic!!!

**Comment by whitedevil-369** [comment]
I can't start the snapd service also without systemctl. there is no init file in /etc/init.d directory so cant use /etc/init.d/snapd start. what can I do to start the snapd service in wsl?

**Comment by DanielAKAOi** [comment]
try:

update-alternatives --config iptables > type "1" >  "enter"

\====================
\#######################
\====================

┌──(root㉿darkside)-[~]
└─# update-alternatives --config iptables
There are 2 choices for the alternative iptables (providing /usr/sbin/iptables).

Selection    Path                       Priority   Status
------------------------------------------------------------
  *0            /usr/sbin/iptables-nft    20        auto mode
  1            /usr/sbin/iptables-legacy   10        manual mode
  2            /usr/sbin/iptables-nft      20        manual mode

Press <enter> to keep the current choice[*], or type selection number: 1

┌──(root㉿darkside)-[~]
└─# update-alternatives --config iptables
There are 2 choices for the alternative iptables (providing /usr/sbin/iptables).

  Selection    Path                       Priority   Status
------------------------------------------------------------
 0            /usr/sbin/iptables-nft      20        auto mode
 \*1            /usr/sbin/iptables-legacy   10        manual mode
 2            /usr/sbin/iptables-nft      20        manual mode

Press <enter> to keep the current choice[*], or type selection number: 1

┌──(root㉿darkside)-[~]
└─# /etc/init.d/docker start

┌──(root㉿darkside)-[~]
└─# docker ps
CONTAINER ID   IMAGE                                                     COMMAND                  CREATED        STATUS                                     PORTS                                                                      NAMES
b770f6f2e0f3   nginx:alpine                                              "/docker-entrypoint.…"   6 months ago   Up Less than a second                      0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   rengine_proxy_1
169d47efc1eb   peterdavehello/tor-socks-proxy                            "/usr/bin/tor -f /et…"   6 months ago   Up Less than a second (health: starting)   8853/udp, 9150/tcp                                                         rengine_tor_1
7ad0a5db13bc   docker.pkg.github.com/yogeshojha/rengine/rengine:latest   "/usr/src/app/entryp…"   6 months ago   Up Less than a second                      0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                  rengine_web_1
94bbfec90492   rengine_celery                                            "/usr/src/app/celery…"   6 months ago   Up Less than a second                                                                                                 rengine_celery_1
1d6e19307810   postgres:12.3-alpine


\====================
\#######################
\====================

**Comment by SeniorSupportEngineer** [comment]
[DanielAKAOi](https://github.com/DanielAKAOi) that worked for me thank you

**Comment by scruel** [comment]
When WSL2 can support systemd?

**Comment by liudonghua123** [comment]
I have the same problems recently, I update the `/etc/wsl.conf` (append the following configures) and the restart wsl via `wsl --shutdown`.

```conf
[boot]
systemd=true
```

I also checked the process name of pid 1.

```
liudonghua@DESKTOP-DELL:~$ ps -ef|more
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 15:12 ?        00:00:00 /sbin/init
root           2       1  0 15:12 ?        00:00:00 /init
root           5       2  0 15:12 ?        00:00:00 plan9 --control-socket 6 --log-level 4 --server-fd 7 --pipe-fd 9 --
log-truncate
root          75       1  0 15:12 ?        00:00:00 /lib/systemd/systemd-journald
root         103       1  0 15:12 ?        00:00:00 /lib/systemd/systemd-udevd
root         116       1  0 15:12 ?        00:00:00 snapfuse /var/lib/snapd/snaps/lxd_22923.snap /snap/lxd/22923 -o ro,
nodev,allow_other,suid
root         117       1  0 15:12 ?        00:00:00 snapfuse /var/lib/snapd/snaps/snapd_15534.snap /snap/snapd/15534 -o
 ro,nodev,allow_other,suid
root         118       1  0 15:12 ?        00:00:00 snapfuse /var/lib/snapd/snaps/core20_1405.snap /snap/core20/1405 -o
 ro,nodev,allow_other,suid
systemd+     141       1  0 15:12 ?        00:00:00 /lib/systemd/systemd-networkd
systemd+     303       1  0 15:12 ?        00:00:00 /lib/systemd/systemd-resolved
......
```

Although the process of pid 1 is not `systemd`, I found some `systemd` related process. and some daemons like redis worked then.

**Comment by YuriGeinishO** [comment]
I've enabled systemd in WSL per https://learn.microsoft.com/en-us/windows/wsl/wsl-config instructions. `wsl --shutdown` executed. I'm getting this:
```
$ cat /etc/wsl.conf
[automount]
enabled = false

[network]
generateResolvConf = false

[boot]
systemd = true

$ sudo systemctl start docker.service
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

$
```

**Comment by SeniorSupportEngineer** [comment]
wsl --update solved allot of problems, 
Only the mtu of my vpn is different, so I have to run "sudo ifconfig eth0 mtu 1350"
now I can access internet over vpn connection.
But when I start a docker container, inside the container I still don't have internet.
There I found the solution in docker-compose.yml

`networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1350`

**Comment by sevi-kun** [comment]
For people looking at this down the road:
[Systemd support is now available in WSL!](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/)

**Comment by TofuWand** [comment]
> Instead of using `sudo systemctl start docker` use: `sudo /etc/init.d/docker start` , as of right now we do not have systemd in WSL 2.

In Termux, I got this:
/etc/init.d/docker: 86: ulimit: error setting limit (Operation not permitted)

**Comment by TofuWand** [comment]
> I've enabled systemd in WSL per https://learn.microsoft.com/en-us/windows/wsl/wsl-config instructions. `wsl --shutdown` executed. I'm getting this:
> 
> ```
> $ cat /etc/wsl.conf
> [automount]
> enabled = false
> 
> [network]
> generateResolvConf = false
> 
> [boot]
> systemd = true
> 
> $ sudo systemctl start docker.service
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> 
> $
> ```
> 
> SOLVED: After running `wsl --update` and restarting WSL.

Nice, but this doesn't work in Termux.p, unfortunately so.
