### ISSUE TITLE
Unspecified error

### ISSUE THREAD

**Issue by hamdio** [MicrosoftDocs/WSL#458]
Upgrading the existing distro version failied with an `Unspecified error` message as below:
```
PS C:\WINDOWS\system32> wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Unspecified error
```
- Win10 Pro
- OS Build: 18936.100

**Comment by mscraigloewen** [comment]
We're tracking this issue over in the WSL repo with issue [4102](https://github.com/microsoft/WSL/issues/4102). 

Fixes are inbound in an upcoming insiders build!

I'll be marking this issue as closed, if you're still experiencing the issue please follow up on the linked thread as this repo is just for the docs. Thank you!
