### ISSUE TITLE
Workaround for dynamic hostname

### ISSUE THREAD

**Issue by pauloscardine** [MicrosoftDocs/WSL#459]
I would like to share this small workaround I'm using to automatically update %WINDIR%\System32\drivers\etc\hosts with the WSL dynamic IP address, so I can refer to the WSL instance using the hostname `wsl`:

```
PS C:\Users\paulos> cat .\hosts.py
import subprocess
import re

output = subprocess.check_output('wsl.exe ifconfig')
match = re.search(r"\sinet\s+(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\s", output.decode('utf-8'))
if match:
    ip = match.group(1)
    with open(r"C:\Windows\System32\drivers\etc\hosts") as i:
        content = i.read()
        new_content = re.sub(r"(\d+.\d+\.\d+\.\d+)\s+wsl$", f"{ip} wsl", content, re.M)
    if new_content != content:
        try:
            with open(r"C:\Windows\System32\drivers\etc\hosts", "w") as o:
                o.write(new_content)
        except PermissionError:
            print(new_content)
else:
    print("no match")
```

I use the Windows Scheduler to start the SSH daemon in the default WSL instance and then run this script at login. Works like a charm with the "remote shell" from my IDE, without it I would have to always figure out the IP address of the WSL instance and update the IDE settings.

**Comment by mscraigloewen** [comment]
Awesome! Thank you for sharing. :) I'll mark this issue as closed since there isn't any further action take on our part.
