### ISSUE TITLE
Virtualization platfrom (Conflicts or incompatibliites with vmware ect.??)

### ISSUE THREAD

**Issue by stevebovy** [MicrosoftDocs/WSL#460]
Does enabling this new virtualization platform conflict with other VM installed technology like VM-Ware 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by mscraigloewen** [comment]
Unfortunately yes it will! You can see our full answer [here on the WSL 2 FAQ page](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#will-i-be-able-to-run-wsl-2-and-other-3rd-party-virtualization-tools-such-as-vmware-or-virtualbox).
