### ISSUE TITLE
New devices (Android VM emulater devices??)  (Network tun/tap devices ??)

### ISSUE THREAD

**Issue by stevebovy** [MicrosoftDocs/WSL#461]
Will there be consideration given to add New Hardware devices?  For example:

1) Network tun/tap devices
2) Android VM-Emulater devices (i.e. use native Linux vm technology??)  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-faq.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by mscraigloewen** [comment]
Yes we are keeping those requests in consideration! 

For future reference please post feature requests on our [WSL Github repo](https;//github.com/microsoft/wsl) or our [uservoice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l). Thank you!

**Comment by stevebovy** [comment]
Thanks;   

I mention this for two reasons

1) Android developers platform requires VM technology for test/debug, and looks for certain "devices"

There is another well known open source VM technology for IBM called Hercules :)
Hercules is very useful for developing and testing Linux apps that run on IBM-Linux machines. 
Hercules uses tun/tap devices for networking.   The windows version of herc is difficult to use and configure because of the lack of these tun/tap devices

**Comment by stevebovy** [comment]
Thanks Craig for your help.  :)  

 

BTW:  the imbedded  githup repo link in this email is incorrect

**Comment by mscraigloewen** [comment]
Whoops, here's the actual link: https;//github.com/microsoft/wsl

**Comment by stevebovy** [comment]
Yes, thanks; I did figure it out,   but I have some questions

 

I read that I should  go to the other site  for  “new-features”,   but  the other site confusingly states that   I should goto   the git site 

 

And round and round we go  circular logic  :)    

 

Plus  (what the heck)   Yet-Another   web-site   with Yet-Another  Login and Password  ??????

Please save me from the stupid   login password hell   !!!

**Comment by mscraigloewen** [comment]
You can post your feature request on our github page, as that seems easiest.

**Comment by stevebovy** [comment]
Thanks
