### ISSUE TITLE
/proc/bus/ is empty and includes no devices

### ISSUE THREAD

**Issue by pbathuk** [MicrosoftDocs/WSL#463]
I have WSL 2 setup with the Ubuntu distro running,
I managed to get it up and running, however when I come to look for the devices on /proc/bus there are none, to me, since we can mount the HDD, pci/pcie devices should be there as well. I can't see anything that says we can't, so assume it's a bug.
Happy to provide logs etc if that will help.

**Comment by craigloewen-msft** [comment]
Please see the mount docs for mounting drives into WSL: https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk
