### ISSUE TITLE
Running docker on Ubuntu 18.04.2 LTS (WSL Enabled)

### ISSUE THREAD

**Issue by Kundan22** [MicrosoftDocs/WSL#468]
I am trying to install docker on Linux Subsystem for Windows10. After following all the steps mentioned in this [official documentation](https://docs.docker.com/install/linux/docker-ce/ubuntu/) but I am getting following error while running docker commands.

```
$docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Any suggestions? Am I missing anything here?

Is docker on Ubuntu (WSL) supported??

**Comment by ieaglle** [comment]
Make sure Docker is running:
`sudo service docker status`

Docker requires root access. Could you try this:
`sudo docker ps`

There's also [Post-installation steps for Linux](https://docs.docker.com/install/linux/linux-postinstall/) worth reading.

**Comment by neo-clon** [comment]
In WSL v1 it is complicated to work with docker, you need to install docker on windows and then configure the docker cli to communicate by tcp

Instead, with WSL v2 things change, you can install full docker in linux the only detail is that you can't do a systemctl enable to start alone

![image](https://user-images.githubusercontent.com/12282168/62484046-e4914a00-b77e-11e9-973e-beeef2e7b8c6.png)

**Comment by mscraigloewen** [comment]
This repo is for issues with the Microsoft Docs, if you have any further issues please post them to the WSL repo page: https://github.com/microsoft/wsl

Try running the command:
`sudo /etc/init.d/docker start` to start the docker service then run your docker commands.

**Comment by Kundan22** [comment]
~$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
hello-world         latest              fce289e99eb9        7 months ago        1.84kB

~$ sudo docker run hello-world
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:303: getting the final child's pid from pipe caused \"EOF\"": unknown.
ERRO[0002] error waiting for container: context canceled

**Comment by Kundan22** [comment]
bdw I tried on 3 different machines but every time I got the same result. Also on all 3 machines ```wsl.exe -l -v``` doesn't return anything.. must be something is not correct.

**Comment by mscraigloewen** [comment]
Seems to me that you are not on the correct version of Windows. You need to be running build 18917 or higher to have access to WSL 2. Please make sure you are on the Windows Insider program fast ring.
