### ISSUE TITLE
How do I uninstall ubuntu and then uninstall WSL on Server Core?

### ISSUE THREAD

**Issue by EdiWang** [MicrosoftDocs/WSL#470]
I would like to revert my install of ubuntu 18.04 LTS and also uninstall WSL on Windows Server 2019 Datacenter Server Core. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install the Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-on-server.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by mscraigloewen** [comment]
To uninstall a distribution use the command: `wsl --unregister <DistroName>` in your case it would be: `wsl --unregister Ubuntu`. Please note that this will *delete all your files in that distro!* So please use it with caution. 

To uninstall WSL entirely simply turn off the `Windows Subsystem for Linux` optional feature.

**Comment by loveexword** [comment]
wslconfig -l
wslconfig -u

**Comment by crramirez** [comment]
@pdkaman because Server 2019 uses a wsl version too old

**Comment by pdkaman** [comment]
@crramirez  Somewhat rhetorical as I spent a few days trying to research before I got the right search phrase and landed on this issue...
