### ISSUE TITLE
wsl --set-default-version 2 is an "Invalid command line option"

### ISSUE THREAD

**Issue by botschool-scott** [MicrosoftDocs/WSL#471]
PS C:\WINDOWS\system32&gt; wsl --set-default-version 2
Invalid command line option: --set-default-version
Copyright (c) Microsoft Corporation. All rights reserved.

I'm running Windows 10 Pro for Workstations Version 1903 OS build 18362.239

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by mscraigloewen** [comment]
You need to be on the Windows Insiders program with the 'Fast Ring' selected. 

![image](https://user-images.githubusercontent.com/42221804/62744139-2b3ea880-b9fa-11e9-9f87-4c581cbd80bb.png)
![image](https://user-images.githubusercontent.com/42221804/62744164-427d9600-b9fa-11e9-91bb-6033eb282d39.png)

**Comment by pantasio** [comment]
Still Dont work.
another solution?

**Comment by craigloewen-msft** [comment]
@pantasio please open up cmd and run `ver`. It will show you your Windows build number. If your build number is less than 18917 then you don't have access to WSL 2 related bits. What version number do you have?

Also, if you've selected fast ring make sure you've updated. After you've selected the fast ring you'll need to go to the Settings -> Updates -> and then click 'Check for Updates'. It may take some time for the update to reach your computer, but you'll need to update there to get onto the latest build.
