### ISSUE TITLE
what if I want to start a service which can be accessed from other PCs

### ISSUE THREAD

**Issue by breadbread1984** [MicrosoftDocs/WSL#476]
I know WSL2 now can start service which is accessible from my own PC. how can I make it visible to other PCs in the same LAN?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [UX Changes between WSL 1 and WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#feedback)
* Content Source: [WSL/wsl2-ux-changes.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-ux-changes.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by sionicion** [comment]
Also curious about this.. For example, let's say I want to access my VSCode running in WSL not only from the host PC, but also from other computers. I think I'd just need an SSH connection, but I'm not a networking expert to figure out if it is currently possible. I see the port is open but it's coming from a loopback adapter. I changed some rules for ssh so it listens on 0.0.0.0, no dice.

**Comment by DrMiaow** [comment]
You will be out of luck until the bridge the networking in later releases. It's the one thing stopping me from upgrading.

**Comment by craigloewen-msft** [comment]
@DrMiaow is correct, as of right now this isn't something that's possible but is something that we're interested in doing. I'll close this issue out since the original question has been answered, if it does become possible you can expect updates to the documentation detailing how to do it.

**Comment by jdgregson** [comment]
@craigloewen-msft I'm a bit confused. Above you stated that it isn't currently possible to access the WSL 2 VM's services over the LAN, but in the [documentation](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#other-networking-considerations
) it says:

> Please keep security in mind when making these changes, as this will allow connections from your LAN.

Is the previous sentence currently just a placeholder with the expectation that it will be true at a later time?

**Comment by craigloewen-msft** [comment]
Sorry for the confusion! I can completely see where you are coming from.

What I meant by: 
>Please keep security in mind when making these changes, as this will allow connections from your LAN.

Is that that app will now be able to ACCEPT connections from the LAN, and not just the machine. Binding to 127.0.0.1 will ONLY allow connections from that specific machine (connections only coming from 127.0.0.1), while binding to 0.0.0.0 will allow connections from any address, including ones from your LAN. As of right now you aren't able to access your WSL 2 VM on your LAN out of the box. 

I'll look at editing that sentence in the docs to make it clearer, thank you!

**Comment by ericblade** [comment]
That's still pretty much clear as the proverbial mud.  The ask is to find a way to accept incoming connections from other machines on the LAN within the WSL2 VM.  So while binding to 0.0.0.0 will technically allow connections from the LAN, there's no way to actually *connect* to the service from the LAN, as the WSL2 VM does not have an IP address on your network, and networking doesn't know how to get there from here.

that also sounds unclear, too. :-D
