### ISSUE TITLE
How to setup the bash with multirow and column layout

### ISSUE THREAD

**Issue by Baalkikhaal** [MicrosoftDocs/WSL#477]
Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

In the bash preview image shared at the [Initializing a newly installed distro](https://docs.microsoft.com/en-us/windows/wsl/initialize-distro#update--upgrade-your-distros-packages) page, there is a beautiful layout with a bash terminal of various rows and columns. How does one achieve it?

**Comment by Biswa96** [comment]
It's [tmux](https://en.wikipedia.org/wiki/Tmux).

**Comment by craigloewen-msft** [comment]
The following apps were used to make that graphic:

- lolcat
- cowsay
- fortune
- [Weather forecasting app](https://winaero.com/blog/get-weather-forecast-linux-console/)
- tmux

That should give you a great starting point on how you can build it!

Also worthwhile to check out are:

- cmatrix
- caca-utils (use cacafire or cacademo after you install it)

Enjoy!
