### ISSUE TITLE
AVAST Solution for No internet access in WSL without turning off the firewall

### ISSUE THREAD

**Issue by uniibu** [MicrosoftDocs/WSL#481]
I just want to share that when Avast Firewall is blocking internet access of WSL2, all you have to do is go to Settings -&gt; Protection -&gt; Firewall -&gt; Check the Internet Connection Sharing Mode. You can now access the internet on WSL2 without disabling Avast Firewall.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#no-internet-access-in-wsl)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/troubleshooting.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by craigloewen-msft** [comment]
Thanks for filing this! If I see any firewall issues with WSL2 and Avast I'll direct them here.

**Comment by marcin2x4** [comment]
Thanks @uniibu !!!

**Comment by IgnusG** [comment]
Many thanks @uniibu!

**Comment by doozyOwl** [comment]
saved my day.. thanks a bunch.

**Comment by alignwebs** [comment]
Thanks man!

**Comment by ALonelySheep** [comment]
Thank you soooo much, you saved my day!

**Comment by Mika571** [comment]
You da best!

**Comment by masptj** [comment]
In Portuguese!
Para conseguir que o WSL funcione com o **Avast Premium Security**, ativo, seguir os passos de Uni Sayo, ou seja;
Abir painel, Configurações -> Proteção -> Firewall -> Check, **Permitir modo de Compartilhamento de Conexão com a internet**. Com isso, poderá acessar a no WSL2 sem ter de desabilitar o Firewall.

![image](https://user-images.githubusercontent.com/79266/151048564-37c0974f-4b21-4601-8821-6f0687bd8955.png)

![image](https://user-images.githubusercontent.com/79266/151048440-1c50dd87-7598-4b74-a287-57ba7f7140c5.png)

**Comment by junyorff12** [comment]
works fine, tks
