### ISSUE TITLE
WSL with a native Linux and virtual Win-10

### ISSUE THREAD

**Issue by IBMbonizak** [MicrosoftDocs/WSL#483]
Does the WSL extension work with a native linux ( Ubuntu ) running a virtual Windows 10 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3be148fb-e4a9-83b5-5b5a-7834eed7052f
* Version Independent ID: f583bc11-fe60-bb2c-af2b-dc0dae9fe81f
* Content: [Learn about the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about)
* Content Source: [WSL/about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/about.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by Biswa96** [comment]
WSL1 works as usual but WSL2 needs virtualization feature, that is nested virtualzation feature should be present.

**Comment by IBMbonizak** [comment]
And since I wouldn't have the virtualization feature, no it won't work.
Thanks.
