### ISSUE TITLE
Add a reference link to left hand navigation

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/WSL#484]
Please add a dedicated link for the reference in the left hand navigation as it may be obvious to the team working on this, but for a end users, its not straight forward. At least I could not navigate to it easily while searching for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bc08c2-7a4c-8827-47b9-2729abf0a9e9
* Version Independent ID: 26e3819a-72d0-e8a8-7790-5551acede71b
* Content: [Windows Subsystem for Linux Command Reference](https://docs.microsoft.com/en-us/windows/wsl/reference)
* Content Source: [WSL/reference.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/reference.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by craigloewen-msft** [comment]
Committed! 

Thank you for making the docs a better place. :)
