### ISSUE TITLE
About this "lightweight VM"

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/WSL#485]
Does this "lightweight VM" require the Hyper-V role, SLAT, Intel VT-x and such?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c94eeb-5969-cb2d-fc63-1d4074070812
* Version Independent ID: def2349f-07a2-e772-0583-e5e3ce5983d4
* Content: [About WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-about)
* Content Source: [WSL/wsl2-about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-about.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by craigloewen-msft** [comment]
Yes! It uses the Hyper-V architecture.

**Comment by skycommand** [comment]
Thanks for the incomprehensive answer. It felt more like a polite "get out of my face!"

**Comment by craigloewen-msft** [comment]
Hi @skycommand I'm sorry that I came off that way! That was not my intention at all.

The Hyper-V lightweight VM is enabled using the 'Virtual Machine Platform' feature, which enables the Hyper-V architecture (so it does enable a Hyper Visor on your machine), that means we do use SLAT. 

I'm happy to answer any more questions that you might have. :)

**Comment by skycommand** [comment]
@craigloewen-msft Hi. Thanks for reaching back. 😊 It is a pleasant surprise. To be honest, I actually have many questions.

Since the word "etc." at the end of my question did not quite do justice, let me paraphrase the whole question: "What are the system requirements of WSL?" So far, I know that it is an x64 machine, an x64 Windows 10 SKU, and Hyper-V. (The later implied Intel VT-d and SLAT.) Okay, that can't be just it. Even WSL 1 has more prerequisites. So, what else?

Another question is: WSL is a feature of the Home edition too. But Hyper-V isn't. That means even if WSL 2 came with Windows 10 Home edition, it would be totally useless. Or does it? What am I missing here?

The third question is: What is this "Virtual Machine Platform"? It is currently included with Windows 10 v1809 and later, but there is no explanation of what it is, what it does, and why it is separated from other virtualization and containerization features. If I am to enable it in the future for the sake of WSL 2, I need to be able to explain its function to the management.

**Comment by craigloewen-msft** [comment]
I've done a little paraphrasing and tried to break up the questions: 

## What are the system requirements for WSL 2?

To put it succinctly, any machine that can run WSL 1 that can also use virtualization (i.e: can run Hyper-V, which means it has Intel VT-d and SLAT) can run WSL 2. WSL 2 works on server, Windows 10 Home edition, Windows 10 Pro, etc. And that machine needs to be running Windows build 18917 or higher. 

## How can WSL 2 run on Windows 10 Home?

You're correct, Hyper-V isn't an optional feature in Windows 10 Home. Luckily we use the Virtual Machine Platform optional feature to enable WSL 2, and not the Hyper-V optional feature.

## WSL 2 uses the Hyper-V architecture with the 'Virtual Machine Platform' optional component, how does that work? What is the 'Virtual Machine Platform' component?

The virtual machine platform feature basically contains a subset of virtualization features that allows applications to use virtual machines. I agree, I think we (Microsoft) can improve our documentation on this feature, and I'll investigate how to make that possible, but I hope that answer is satisfying enough for management!

**Comment by skycommand** [comment]
Thanks a billion, Mr. Loewen. Your last answer was simply golden. It connected the dots. I spoke to my superior about it. (Not because I want to deploy WSL 2 right; but because I wanted to impress her.) I explained that "Virtual Machine Platform" to "Hyper-V" is analogous to "IIS Express" to "IIS", or "Device Encryption" to "BitLocker".

**Comment by weeix** [comment]
If WSL2 requires SLAT. I think mentioning it somewhere in the documentation would be great.

(from a user who wasted hours finding out why error 0x80370102 persisted even though the virtualization is enabled)

**Comment by ohault** [comment]
Documenting what is a "Hyper-V lightweight VM" would be great too.
