### ISSUE TITLE
There is no distribution with the supplied name. "Ubuntu"

### ISSUE THREAD

**Issue by nicobrinkkemper** [MicrosoftDocs/WSL#487]
Following documentation it is suggested that "Ubuntu" is a valid name, however I found that I needed the LTS version number as well "Ubuntu-18.04". See these logs:

```
PS C:\WINDOWS\system32> wsl --set-version Ubuntu 2
There is no distribution with the supplied name.
PS C:\WINDOWS\system32> wsl --list --all
Windows Subsystem for Linux Distributions:
Ubuntu-18.04 (Default)
PS C:\WINDOWS\system32> wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
```

Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

**Comment by craigloewen-msft** [comment]
This is because you've installed [Ubuntu-18.04](https://www.microsoft.com/en-us/p/ubuntu-1804-lts/9n9tngvndl3q) from the Microsoft Store. If you install regular [Ubuntu](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?SilentAuth=1) the distro will be called Ubuntu! :)

**Comment by nicobrinkkemper** [comment]
Makes too much sense, I forgot I made that choice. They seemed like the same thing. Thanks

**Comment by onacit** [comment]
I uninstalled `Ubuntu 18.04` and installed `Ubuntu` yet I see the same error message.

**Comment by craigloewen-msft** [comment]
@onacit Please make sure you've run `Ubuntu` at least once! It should show up in when you run `wsl -l`

**Comment by chriscupas** [comment]
@craigloewen-msft , Is there a way to set the version even if it is installed from Microsoft store ?

**Comment by fscelliott** [comment]
I ran wsl --set-version Ubuntu-18.04 2, and I got a message back: "conversion in progress, this may take a few minutes..." So I think it's possible to update from the MIcrosoft store installed version! (update could take a couple hours, I hear)

**Comment by charlesx163** [comment]
> I ran wsl --set-version Ubuntu-18.04 2, and I got a message back: "conversion in progress, this may take a few minutes..." So I think it's possible to update from the MIcrosoft store installed version! (update could take a couple hours, I hear)

Are you successful? I also get this message.

**Comment by hossamsherif** [comment]
> I ran wsl --set-version Ubuntu-18.04 2, and I got a message back: "conversion in progress, this may take a few minutes..." So I think it's possible to update from the MIcrosoft store installed version! (update could take a couple hours, I hear)

confirm for the version Ubuntu 20.04 on Microsoft store use:
`wsl --set-version Ubuntu-20.04 2` 
It took a couple of seconds to complete successfully.

**Comment by mrexodia** [comment]
For me the issue was that I was using quotes. Without quotes everything works fine:

```
C:\Users\Admin>wsl --set-version "Ubuntu-18.04" 2
There is no distribution with the supplied name.

C:\Users\Admin>wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
```

**Comment by samheyman** [comment]
```
PS C:\WINDOWS\system32> wsl -l
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
```

**Comment by The-Risen-wizard** [comment]
> > I ran wsl --set-version Ubuntu-18.04 2, and I got a message back: "conversion in progress, this may take a few minutes..." So I think it's possible to update from the MIcrosoft store installed version! (update could take a couple hours, I hear)
> 
> confirm for the version Ubuntu 20.04 on Microsoft store use: `wsl --set-version Ubuntu-20.04 2` It took a couple of seconds to complete successfully.

There is no distribution with the supplied name. This is the messsage I am getting for Ubuntu version 20.04. Please can you tell where I am going wrong?

**Comment by Biswa96** [comment]
Distribution name can be found with `wsl.exe -l -v` command.

**Comment by The-Risen-wizard** [comment]
> Distribution name can be found with `wsl.exe -l -v` command.

Ok I will try it. Thanks

**Comment by thatux** [comment]
```
wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Running         1
  Ubuntu          Stopped         1
```

```

C:\Users\user>wsl --unregister -d Ubuntu
Unregistering.
There is no distribution with the supplied name.
Error code: Wsl/Service/WSL_E_DISTRO_NOT_FOUND

C:\Users\user>wsl --unregister -d "Ubuntu"
Unregistering.
There is no distribution with the supplied name.
Error code: Wsl/Service/WSL_E_DISTRO_NOT_FOUND

C:\Users\user>wsl --set-version Ubuntu-20.04 2
There is no distribution with the supplied name.
Error code: Wsl/Service/WSL_E_DISTRO_NOT_FOUND

C:\Users\user>wsl --set-version Ubuntu-22.04 2
There is no distribution with the supplied name.
Error code: Wsl/Service/WSL_E_DISTRO_NOT_FOUND

C:\Users\user>wsl --set-version Ubuntu 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion in progress, this may take a few minutes.
```

unregister does not work on `Ubuntu` but `wsl --set-version` does :S

**Comment by m15kh** [comment]
i run my ubuntu as run as administer
and work for me
