### ISSUE TITLE
wsl 2 on arm linux on build18980.1 

### ISSUE THREAD

**Issue by ericvh** [MicrosoftDocs/WSL#488]
I'm getting  0x80370102: could not be started because a required feature is not installed.

Went through and confirmed VM enabled and WSL enabled (wsl1 worked fine) -- assuming this is a BIOS problem on WOS, but no clear way to set any BIOS settings on HPE Envy (Snapdragon 835) nor Lenovo Yoga (Snapdragon 850).  Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by craigloewen-msft** [comment]
We used the [Samsung Galaxy Book 2](https://www.samsung.com/us/mobile/tablets/galaxy-book-2/) for testing.

**Comment by craigloewen-msft** [comment]
Closing this issue out as we do a repo clean up, if you still see this please file it at https://github.com/microsoft/wsl
