### ISSUE TITLE
No USB devices seen 

### ISSUE THREAD

**Issue by jerryjavelin** [MicrosoftDocs/WSL#493]
Using WSL and Ubuntu 18.04 LTS  with OS build 18362.356 and kernel 4.4.0-18362-Microsoft cannot see a USB camera.  Tried everything I could find on net including trying to install different kernel,( wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.12/linux-headers-4.12.0-041200_4.12.0-041200.201707022031_all.deb), but then the last step , sudo update-grub would not work for all the reasons listed on the web, failed to get canonical path, lsusb retruned nothing but no error,, lshw listed hardware but no usb devices also did not show internal PC camera, dmesg returned Microsoft 4.4.0-18362.1-Microsoft 4.4.35,
udevadm monitor hung the terminal, I reran in power shell then enable-windowoptional... command to ensure it was still active, I read the web sites about mounting (https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/) and about the serial coms (https://blogs.msdn.microsoft.com/wsl/2017/04/14/serial-support-on-the-windows-subsystem-for-linux/).  I can't believe this is all that hard to "see/ enable USB devices".  What am I missing?  I'm not an experienced linux user and not experienced at all in WSL. Please help I need to be able to access a usb camera or the internal PC camera running a python program under Linux.  Either would meet my needs.  If you could please just list the step by step commands to make either the usb camera visible or the internal PC camera I would really appreciate it.  Thanks, Jerry

**Comment by craigloewen-msft** [comment]
It's currently not possible to access a USB camera with WSL. This is a feature that we're aware of and it's on our backlog! You can get updates on the landing issue for it here on our WSL github repo: https://github.com/Microsoft/WSL/issues/412

Thanks!
