### ISSUE TITLE
Ubuntu always get "Hash sum mismatch" when using WSL 2

### ISSUE THREAD

**Issue by ajipw** [MicrosoftDocs/WSL#495]
Hello.

I'm Trying to use WSL 2 with Ubuntu Distro, but when update, upgrade and install always get "Hash sum mismatch", On WSL 1 is normal and can update, upgrade and install.

This is when using WSL 2 :
![image](https://user-images.githubusercontent.com/25083343/65837419-65a13380-e321-11e9-8cb0-3029d6d2e17e.png)

This is when using WSL 1 : 
![image](https://user-images.githubusercontent.com/25083343/65837431-86698900-e321-11e9-956b-942f7ea195d9.png)

I don't know is this bug or not, but it annoy me.

Thanks before.

**Comment by craigloewen-msft** [comment]
Closing this issue out as we do a repo clean up, if you still see this please file it at https://github.com/microsoft/wsl
