### ISSUE TITLE
wsl -l refers user to the Store

### ISSUE THREAD

**Issue by danderson3** [MicrosoftDocs/WSL#496]
wsl -l doesn't list available distributions, even though this page says it does

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This is since `wsl -l` was a command that was shipped with WSL2, and is only available in WSL2 builds (18917 or higher).

I added a quick disclaimer to that page to help make that point clearer. Thanks for filing! :)
