### ISSUE TITLE
Easy to follow

### ISSUE THREAD

**Issue by Betlista** [MicrosoftDocs/WSL#497]
...it's not so often it is so easy ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual#feedback)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
@Betlista is the feedback here to make the document more easy to follow? What ways would make it easier for you?

**Comment by Betlista** [comment]
Sorry, no (no changes requested). In this case, I really meant that it was easy to follow the instructions.

**Comment by craigloewen-msft** [comment]
Oh gotcha! Thank you so much for the kind feedback. :)
