### ISSUE TITLE
'wsl --set-default-version 2' throws generic asssitance

### ISSUE THREAD

**Issue by inbay** [MicrosoftDocs/WSL#500]
I am unclear why or how this is occurring, but in any case the 'wsl --set-default-version 2' powershell command throws generic assistance as below and does not appear to be an appropriate option set;
PS C:\WINDOWS\system32&gt; wsl --set-default-version 2
Invalid command line option: --set-default-version
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments to run Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e &lt;CommandLine&gt;
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d &lt;DistributionName&gt;
        Run the specified distribution.

    --user, -u &lt;UserName&gt;
        Run as the specified user.

Arguments to manage Windows Subsystem for Linux:

    --export &lt;DistributionName&gt; &lt;FileName&gt;
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import &lt;DistributionName&gt; &lt;InstallLocation&gt; &lt;FileName&gt;
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are currently
                being installed or uninstalled.

            --running
                List only distributions that are currently running.

    -setdefault, -s &lt;DistributionName&gt;
        Sets the distribution as the default.

    --terminate, -t &lt;DistributionName&gt;
        Terminates the distribution.

    --unregister &lt;DistributionName&gt;
        Unregisters the distribution.

    --upgrade &lt;DistributionName&gt;
        Upgrades the distribution to the WslFs file system format.

    --help
        Display usage information.
PS C:\WINDOWS\system32&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#troubleshooting)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Based on the output that you listed, it looks like to me that you may be running a build before Windows 18917. You need to be running Windows build 18917 or higher to access WSL 2 (you can get access to this build by joining the Windows Insider program and selecting the fast ring!) 

Please check your build by running `ver` inside of CMD. If it's greater than 18917 please reopen this issue over in our [WSL repo](https://github.com/microsoft/wsl) and we will help you there as this repo is just for the documentation! Thank you!

**Comment by Msadr471** [comment]
Thank you for help...
I joined the Windows Insider Program, But still, I don't have access "Windows build 18917 or higher"
what can I do??

![image](https://user-images.githubusercontent.com/49529241/71644251-8ee3ae00-2cda-11ea-8dc9-47b052183248.png)

**Comment by craigloewen-msft** [comment]
@Msadr471  Please check for an update in Windows Update. It should arrive to you within a day or so, and that update should update you to the latest build which will give you access to WSL2!

**Comment by soerendip** [comment]
I am running

Version	10.0.19041 Build 19041

Virtualization is enabled, but still:
```

C:\WINDOWS\system32>wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Stopped         1

C:\WINDOWS\system32>wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2

```

Even after reboot wsl is running version 1.

**Comment by ratnesh-gupta** [comment]
> I am running
> 
> Version 10.0.19041 Build 19041
> 
> Virtualization is enabled, but still:
> 
> ```
> 
> C:\WINDOWS\system32>wsl -l -v
>   NAME            STATE           VERSION
> * Ubuntu-20.04    Stopped         1
> 
> C:\WINDOWS\system32>wsl --set-default-version 2
> For information on key differences with WSL 2 please visit https://aka.ms/wsl2
> ```
> 
> Even after reboot wsl is running version 1.

Hi @soerendip ,
Did you resolve the issue ? 
I am also facing the same issue.
Let me know how have you resolved the issue
Thanks in advance

**Comment by DogtorDoggo** [comment]
> 
> 
> I am running
> 
> Version 10.0.19041 Build 19041
> 
> Virtualization is enabled, but still:
> 
> ```
> 
> C:\WINDOWS\system32>wsl -l -v
>   NAME            STATE           VERSION
> * Ubuntu-20.04    Stopped         1
> 
> C:\WINDOWS\system32>wsl --set-default-version 2
> For information on key differences with WSL 2 please visit https://aka.ms/wsl2
> ```
> 
> Even after reboot wsl is running version 1.

'wsl --set-default-version 2' will only set new installations after this command to use wsl 2. What you want is to convert current distro aka Ubuntu-20.04 from wsl 1 to wsl 2 by this command:

wsl --set-version Ubuntu-20.04 2

**Comment by ratnesh-gupta** [comment]
Thanks @DogtorDoggo . This works for me.

**Comment by luispaulopinto** [comment]
I was facing the same issue and this link helped me:

https://ubuntu.com/blog/ubuntu-on-wsl-2-is-generally-available

Basically:

Open Powershell:
1. wsl.exe --set-version Ubuntu 2
2. wsl.exe --set-default-version 2

**Comment by LoneRegister** [comment]
Looks like the wsl --set-version Ubuntu 2 is convering my 18 up to wsl 2.

Thanks.
