### ISSUE TITLE
Constantly Get the error "Deployment failed with HRESULT: 0x80073CF6, Package could not be registered."

### ISSUE THREAD

**Issue by snigdho123** [MicrosoftDocs/WSL#501]
PS C:\Users\snigdho.das\Downloads&gt; Add-AppxPackage Ubuntu_1604.2019.523.0_x64.appx
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF6, Package could not be registered.
error 0x80070002: Cannot register the CanonicalGroupLimited.Ubuntu16.04onWindows_79rhkp1fndgsc package due to the following error: The system cannot find the file specified.
.
NOTE: For additional information, look for [ActivityId] 9b1681cc-850b-0003-e5b3-169b0b85d501 in the Event Log or use the command line Get-AppxLog -ActivityID 9b1681cc-850b-0003-e5b3-169b0b85d501
At line:1 char:1
+ Add-AppxPackage Ubuntu_1604.2019.523.0_x64.appx
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\snigdh....523.0_x64.appx:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

PS C:\Users\snigdho.das\Downloads&gt; Add-AppxPackage .\Ubuntu_1604.2019.523.0_x64.appx
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF6, Package could not be registered.
error 0x80070002: Cannot register the CanonicalGroupLimited.Ubuntu16.04onWindows_79rhkp1fndgsc package due to the following error: The system cannot find the file specified.
.
NOTE: For additional information, look for [ActivityId] 9b1681cc-850b-0003-dcb5-169b0b85d501 in the Event Log or use the command line Get-AppxLog -ActivityID 9b1681cc-850b-0003-dcb5-169b0b85d501
At line:1 char:1
+ Add-AppxPackage .\Ubuntu_1604.2019.523.0_x64.appx
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\snigdh....523.0_x64.appx:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

PS C:\Users\snigdho.das\Downloads&gt; Add-AppxPackage C:\Users\snigdho.das\Downloads\Ubuntu_1604.2019.523.0_x64.appx
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF6, Package could not be registered.
error 0x80070002: Cannot register the CanonicalGroupLimited.Ubuntu16.04onWindows_79rhkp1fndgsc package due to the following error: The system cannot find the file specified.
.
NOTE: For additional information, look for [ActivityId] 9b1681cc-850b-0003-edb5-169b0b85d501 in the Event Log or use the command line Get-AppxLog -ActivityID 9b1681cc-850b-0003-edb5-169b0b85d501
At line:1 char:1
+ Add-AppxPackage C:\Users\snigdho.das\Downloads\Ubuntu_1604.2019.523.0 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\snigdh....523.0_x64.appx:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

PS C:\Users\snigdho.das\Downloads&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Closing this issue out as we do a repo clean up, if you still see this please file it at https://github.com/microsoft/wsl
