### ISSUE TITLE
Clarification as to when wsl.conf is used to initialise WSL

### ISSUE THREAD

**Issue by gdevacc12** [MicrosoftDocs/WSL#502]
I propose adding a clarification to [Set WSL launch settings](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#set-wsl-launch-settings)

The section says:
Automatically configure certain functionality in WSL that will be applied every time you launch the subsystem using wsl.conf.

This is true but when launching multiple Linux shells for the same distribution the wsl subsystem for that distribution type is not stopped until some time (e.g. approximately 8 seconds) after closing the last instance of the distributions shell. 

i.e. one could (I did) assume that launching the distribution, modifying the wsl.conf, closing the distribution and re-launching would mean changes to  wsl.conf were in effect. This is not currently the case. The subsystem could still be running. Relaunching the same Linux distribution without waiting means the changed in wsl.conf are not in effect.

After closing the Linux Distribution (shell) one must wait until the WSL subsystem for that distribution is no longer running i.e. with `wsl --list --running`

**Comment by craigloewen-msft** [comment]
Sounds like a good fix to me!

I'll try and add this change when I have cycles. Alternatively if you make a pull request I'll also be happy to look at that.

Thank you for filing! :)

**Comment by mattwojo** [comment]
Just found this and made the update: https://github.com/MicrosoftDocs/WSL/commit/77390c0fba7fdb6657d1ebbe63fc721829425bd8#diff-541b84f25ec8814d5a284202d3676efd58b732f46079dffb2dbd02dd7d4f492d
Closing as resolved. Thanks gdevacc12!!!
