### ISSUE TITLE
WSL2: Virtual hard disk files must be uncompressed and unencrypted and must not be sparse

### ISSUE THREAD

**Issue by jovton** [MicrosoftDocs/WSL#506]
Some people (including me) gets the error titled above, but other's have found a workaround for it in this thread: "https://github.com/microsoft/WSL/issues/4103". Perhaps you can include it in the documentation. Kind regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Added! Thank you for the submission. :)
