### ISSUE TITLE
Need information on WSL2 networking - VLAN ID

### ISSUE THREAD

**Issue by jovton** [MicrosoftDocs/WSL#507]
Hi

Do you have any information on the inner workings of the Microsoft "Virtual Machine Platform" feature? I want to know if it is possible to assign a VLAN ID to a virtual switch/adapter that was created by Microsoft's Virtual Machine Platform.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3be148fb-e4a9-83b5-5b5a-7834eed7052f
* Version Independent ID: f583bc11-fe60-bb2c-af2b-dc0dae9fe81f
* Content: [Learn about the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about#feedback)
* Content Source: [WSL/about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/about.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Hi @jovton !

There are docs which cover the Host Compute Network (HCN) service which is used by the Virtual Machine Platform feature. 

[Here's a link](https://docs.microsoft.com/en-us/windows-server/networking/technologies/hcn/hcn-top). 

These should be able to tell you if that is possible. Thanks!

**Comment by jovton** [comment]
@craigloewen-msft Thank you! I was actually trying to figure our if there is a way to make the network "Private" so as to not allow "Public" things via the host firewall, because currently the network for the virtual  switch/adapter is "Public", and the only way to have WSL2 communicate with the host (other than via localhost forwarding) is to make a hole in the firewall.

**Comment by craigloewen-msft** [comment]
Awesome! Glad this could help you out.
