### ISSUE TITLE
Access Basler USB cameras through ubuntu 18.04 in windows

### ISSUE THREAD

**Issue by SpangeJ** [MicrosoftDocs/WSL#512]
Hello, 
I am trying to connect to two Basler cameras through an Ubuntu18.04 terminal in Windows 10. 
The setup is described here:
[Windows Subsystem for Linux Installation Guide for Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
I have two cameras connected and I can see them in pylon viewer and python on windows,
`from pypylon import pylon
devices = pylon.TlFactory.GetInstance().EnumerateDevices()
len(devices)`
prints: `2`
If I run the same commands in the ubuntu18.04 terminal it prints `0`
So that the terminal cannot find the cameras. 
I have installed pylon viewer for Linux X86 in the terminal also: 
[pylon-5-2-0-linux-x86-64-bit ](https://www.baslerweb.com/en/sales-support/downloads/software-downloads/pylon-5-2-0-linux-x86-64-bit/)
  
Basler have some C/C++ examples for in their [README](https://www.baslerweb.com/fp-1552911090/media/downloads/documents/readme/README~3.txt)
If I try to run their example it prompts:
`An exception occurred.
No device is available or no device contains the provided device info properties.`
  
I can connect my serial object (Arduino) found among ttyS* so I hope that my other USB devices are also found.
  
P.S. I have also published this question here: 
https://github.com/basler/pypylon/issues/163 
Maybe someone has put out an answer there before this one is answered.

**Comment by craigloewen-msft** [comment]
Hi @SpangeJ as of right now WSL doesn't support access to USB cameras.

Please see this thread on the WSL Github Repo to keep track of this request as we are tracking it there! 
https://github.com/microsoft/WSL/issues/412

Thank you.
