### ISSUE TITLE
how to disable bash command running in wsl

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [MicrosoftDocs/WSL#513]
i am using linux commands on windows for a while now. I managed to add tools, installed with git for windows, to my PATH and then run all sorts of linux commands like ps, pwd, ls, and also bash.

Since I activated WSL I cannot run my bash anymore, since windows now tries to run bash from inside one of the wsl linux distros.

Is there a way to disable the link between the bash command and a wsl linux distro?

**Comment by craigloewen-msft** [comment]
This is related to your PATH, and most likely your issue can be solved by editing your PATH variable in the environment you're working in.

What was `bash.exe` running before you installed WSL? Are you trying to call `bash` from in a WSL distro or from in a Windows environment like PowerShell or CMD?

And for future reference this repo is only for issues with the docs, you'll get much more help if you post to the official [WSL repo](https://github.com/microsoft/wsl). Thanks!

**Comment by ThomasSchoenbeck** [comment]
my initial bash.exe came from here `C:\Users\tschoenb\tools\PortableGit-2.22.0-64-bit.7z\usr\bin\bash.exe`

i have now created an alias in order to call this bash, rather than the wsl.
