### ISSUE TITLE
Docker on WSL Questions

### ISSUE THREAD

**Issue by dextersrini** [MicrosoftDocs/WSL#515]
The doc says we must be able to install tools like docker on WSL 2, with the new translation or adapting layer development between Linux Kernal and the Windows OS.
If we do so, how do we enable Shared Drive? We will get Options as C:/ native or the WSL /home ?

**Comment by StefanScherer** [comment]
@dextersrini The recommended way for using Docker on WSL2 is to install the Docker Desktop Edge release, we've released 2.1.5.0 yesterday.
You can find all details in https://engineering.docker.com/2019/10/new-docker-desktop-wsl2-backend/ how to enable the experimental WSL2 based engine.

**Comment by mattwojo** [comment]
Sounds like this has been resolved. You can find more info about using Docker Desktop with WSL in this tutorial doc: https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers

Please re-open if this issue persists and could benefit from an update to the docs. Thanks! ~Matt
