### ISSUE TITLE
Add markup for some example commands, so it can be translated correctly.

### ISSUE THREAD

**Issue by echoix** [MicrosoftDocs/WSL#516]
If we could add some markup to the line where there is "git clone, npm install, apt update, apt upgrade", it would probably help the translation in other languages. In french, these commands are translated as a sentence...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c94eeb-5969-cb2d-fc63-1d4074070812
* Version Independent ID: def2349f-07a2-e772-0583-e5e3ce5983d4
* Content: [About WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-about)
* Content Source: [WSL/wsl2-about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-about.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Added! https://github.com/MicrosoftDocs/WSL/commit/5c92b820f84de57a04ab11faf4dd0d24fff6b320

Thank you for filing this. :)
