### ISSUE TITLE
this doc assumes you already have a distro installed

### ISSUE THREAD

**Issue by m3dos** [MicrosoftDocs/WSL#520]
I started following this on a newly built computer, which I didn't have a distro installed on.  Beginning at the "Set a distro to be backed by WSL 2 using the command line" section its assuming you have a distro already

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by bryanloeper** [comment]
At the beginning of the document it states
> Ensure that you have WSL installed
and provides a link to steps that include installing a distro.

**Comment by jcowgar** [comment]
Some of the steps are repeated, for example, if you had WSL installed already then this step isn't necessary, right?

```Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux```

but this doc states to do it.

**Comment by craigloewen-msft** [comment]
We're trying to walk a fine line between giving out detailed information, and not repeating the docs. I've added a quick sentence to the Install WSL 2 docs page to explain where to go if you still need to install a distro. 

cf6d8e2

Thank you for filing this! :)
