### ISSUE TITLE
Readme links to Microsoft/Console

### ISSUE THREAD

**Issue by 102** [MicrosoftDocs/WSL#521]
There's a link in readme that links _Windows Console: https://github.com/Microsoft/Console/_ as a related repo, but GitHub redirects it to _Windows Terminal: https://github.com/microsoft/terminal_, should this link be updated?

**Comment by mattwojo** [comment]
Looks like this was completed: https://github.com/MicrosoftDocs/WSL/commit/0986e58539f3d6370b9becbec2e4fdaa6aa18b6e#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
...but the issue never closed. Thanks for brining this to attention! :) Matt
