### ISSUE TITLE
How do I change apt-update & apt-upgrade server to my country

### ISSUE THREAD

**Issue by shunjid** [MicrosoftDocs/WSL#522]
Hi, I am using the WSL. In the original ubuntu, I can change the server to download from http://archive.ubuntu.com/ to the cache server located in my country let's say, for Bangladesh, this is http://bd.archive.ubuntu.com/ which allows me to download the latest updates faster for : **sudo apt-get update** and **sudo apt-get upgrade**

When I tried those commands in WSL, It's downloading the updates from http://archive.ubuntu.com/ which seems too slower. 

Is it possible to change somehow? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
You can change the server in WSL Ubuntu as you've done in actual Ubuntu distribution, no difference.

**Comment by shunjid** [comment]
Got it.
It was so simple. https://askubuntu.com/questions/104695/how-do-i-change-mirrors-in-ubuntu-server-from-regional-to-main
