### ISSUE TITLE
Cannot access nginix server running on ubuntu guest from windows/firefox

### ISSUE THREAD

**Issue by mwoodpatrick** [MicrosoftDocs/WSL#523]
I'm running firefox on windows trying to access an nginix server running on latest ubuntu

ip addr|grep eth0

reports:

4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 172.30.172.231/20 brd 172.30.175.255 scope global eth0

so I'm using URL https://172.30.172.231

But firefox reports:

    Firefox can’t establish a connection to the server at 172.30.172.231.

Firefox running on the Ubuntu distribution connects just fine and displays the page however sound is not working is this expected on WSL-2?

If I run:

 wget https://172.30.172.231

in windows power shell I get:

wget : Unable to connect to the remote server
At line:1 char:1
+ wget https://172.30.172.231
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by craigloewen-msft** [comment]
What version of Windows are you running? Can you open CMD and run `ver` and paste the output? 

And what do you mean by 'sound isn't working'? What sound are you trying to pass through? Could you elaborate some more on your usecase?

Thanks!

**Comment by mattwojo** [comment]
Looks like there wasn't any follow up here so closing this issue. Please re-open if the issue persists and can benefit from an update to the documentation. Thanks! ~Matt
