### ISSUE TITLE
Networking issues on alpine distribution under WSL 2

### ISSUE THREAD

**Issue by mwoodpatrick** [MicrosoftDocs/WSL#524]
I'm running on windows 10 pro 10.0.19018 N/A Build 19018 and have been running on the Ubuntu distribution under WSL 2 for a while now and have no problems accessing the internet. I just installed the alpine distribution and can access sites based on ip address but not by hostname

So 

     traceroute www.google.com

gives

    traceroute: bad address 'www.google.com'

but

     traceroute 172.217.164.100

works correctly (same for other commands like ping & wget). So 

    wget 216.58.194.196

gives:

     Connecting to 216.58.194.196 (216.58.194.196:80)
     wget: bad address 'www.google.com'

and

    wget www.google.com

gives

    wget: bad address 'www.google.com'

 I did notice that the system log as reported by dmesg gives:
    
    [359389.822951] init: (1) ERROR: UtilMkdir:1247: mkdir(, 755) failed 2
    [359389.822979] init: (1) ERROR: InitEntryUtilityVm:2363: InitUpdateNetworkInformation failed

But on looking at my ubuntu distribution I'm seeing the same issue

This causes problems when trying to update the system using

     apk update

Any suggestions on how to debug

**Comment by Biswa96** [comment]
How did you import Alpine in WSL? Where did you get it? Did you try to delete the `/etc/resolv.conf` file?

**Comment by mwoodpatrick** [comment]
Alpine was installed from Microsoft store

deleting /etc/resolv.conf did not help

**Comment by mattwojo** [comment]
I realize that I'm wayyyyy late on addressing this issue, but I just ran through some of these commands and it looks like the issue has been resolved in the more modern Windows/WSL builds. I'm running Windows Build 21322.1000.
If you try again and find that this issue persists, please let me know and I'll investigate further to see whether there is more info to document here.
Thank you!!
