### ISSUE TITLE
Failed to connect to internet in my Ubuntu

### ISSUE THREAD

**Issue by shengyunyao** [MicrosoftDocs/WSL#526]
I have installed my ubuntu into windows 10 and I can run Linux command in the ubuntu. But I can not connect to the internet in my ubuntu. So what should I do? My windows 10 can surf the internet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This repo is for the documentation for WSL, could you please reopen your issue on the actual [WSL repo](https://github.com/microsoft/wsl)? You'll find more of a community there to help you out! :)

And in that new issue please be sure to specify your build number, whether you're running WSL 2 or WSL 1, and whether you have a VPN enabled on your machine as I suspect it could be VPN related. 

Thank you!
