### ISSUE TITLE
--set-version replaced by -setdefault?

### ISSUE THREAD

**Issue by bnb** [MicrosoftDocs/WSL#528]
Judging by the output of WSL2 when trying to run the `wsl --set-version &lt;Distro&gt; 2` command provided by the docs, it seems that the more accurate command may be `wsl -setdefault &lt;DistributionName&gt;`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by wzin** [comment]
Same here `--set-version` is not there anymore

**Comment by craigloewen-msft** [comment]
@bnb and @wzin what do you mean by `--set-version` is not there anymore? If you run `wsl.exe --help` what command lists do you see? What versions of Windows are you running? 

Thanks!

**Comment by bnb** [comment]
Here is my terminal output with that command. Specifically, see `-setdefault` which produced the desired outcome defined as `--set-version`.

https://gist.github.com/bnb/5172c7dabaed5c9c3a7da46d7fb86df8

Running the latest fast-track build.

**Comment by craigloewen-msft** [comment]
@bnb could you open a CMD window and type in `ver` and paste the output?

FYI I'm on Windows version 19013 and this is my output of `wsl --help`

https://gist.github.com/craigloewen-msft/ce0130501863e718fd204936f7606e20

**Comment by bnb** [comment]
Windows 10.0.18362.476

**Comment by craigloewen-msft** [comment]
@bnb yes you need to be on the Windows Insider program to access WSL2! [Here are the instructions](https://insider.windows.com/en-us/getting-started/) on how to do so. Sorry for the confusion. :)

I'll close this issue out, since the resolution is upgrading, but if you have any more questions please feel free to comment more!
