### ISSUE TITLE
no EXE for kali Linux distro

### ISSUE THREAD

**Issue by munir94** [MicrosoftDocs/WSL#529]
i did not find any .exe file after i extract the kali linux . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
You're right! Just extracted the package as well and didn't see a .exe either. I'll ping Kali about it!

**Comment by craigloewen-msft** [comment]
So the kali.exe is actually there, just buried one layer deeper. If you unzip the original package you should see something like this: 
![image](https://user-images.githubusercontent.com/42221804/69754904-e4d99a80-110b-11ea-8b5f-34aa3048e6c8.png)

Then rename ‘DistroLauncher-Appx_1.1.9.0_x64.appx’  to ‘DistroLauncher-Appx_1.1.9.0_x64.zip’ , unzip it, and you'll find the kali.exe inside of there.

![image](https://user-images.githubusercontent.com/42221804/69754927-f4f17a00-110b-11ea-9e29-5b736d100f51.png)

Thanks for filing this!
