### ISSUE TITLE
Installation instructions missing for Linux

### ISSUE THREAD

**Issue by paddotk** [MicrosoftDocs/WSL#530]
This page offers packages for various Linux distributions, but no instructions on how to actually install them. The link "installation instructions" there just scrolls the page down where it only has instructions for Windows 10..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual#feedback)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
We have an installation instructions section that goes over how to install it on Windows 10, or on Windows Server.
![image](https://user-images.githubusercontent.com/42221804/69987255-f2b86280-14f3-11ea-8c74-300c7a4fde2d.png)

Here are the [Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server) instructions. 

Does this address your feedback? Is there anything you'd want to see changed there? Thanks!

**Comment by paddotk** [comment]
No, I'm using Ubuntu, and I now know where the confusion came from. I was trying to get it installed on a *native Ubuntu* installation and on several places (on different pages) there are links leading to instructions to install it on Linux, or so it seems. What I now learned is that Windows 10 offers a way to install Linux distros *inside* Windows and that all those aforementioned links refer to that, specifically. 

MS seems to assume that everyone knows that 'Windows subsystem for Linux` is the name for a specific linux-inside-Windows integration, and that everyone knows that integration even exists. My suggestion would be to make this more clear to people visiting the MS docs trying to do what I was trying.

I guess there is no way to install WSL in a native Linux then?

**Comment by KharmaScribbles** [comment]
But @paddotk if you have a native Linux install, why in the world would you want to install WSL inside of it?

**Comment by craigloewen-msft** [comment]
I see the confusion! I'll look into ways to make that clearer. Thank you for filing an issue! :)

**Comment by paddotk** [comment]
@KharmaScribbles So that I can run our development stack locally..
