### ISSUE TITLE
Page could use explanation of how to access WSL2 files from Windows

### ISSUE THREAD

**Issue by mkislik** [MicrosoftDocs/WSL#533]
Page could use explanation of how to access WSL2 files from Windows.
The problem I have is the following:

The command mentioned in this article:
Get-AppxPackage -Name "*&lt;distro&gt;*" | Select PackageFamilyName

Produces no output when run from PowerShell.
I am successfully running WSL2.
I tried looking up my AppData/Local/Packages in windows explorer, and I have such a long list I'm not sure what to look for.

I am trying to access the Linux code I have from Windows.  I can successfully use windows explorer running on Ubuntu 18.04 to view files with notepad, but would prefer to use an IDE from Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [UX Changes between WSL 1 and WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#feedback)
* Content Source: [WSL/wsl2-ux-changes.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-ux-changes.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by cpuchip** [comment]
They mention using `explorer.exe .` in wsl2 to pull open an explorer window from that directory.

If you're looking for using an IDE, then the easiest solution is with Visual Studio code with the remote development extension installed. Then all you'd have to do to launch VS Code from within wsl2 is `code .`
That works in both wsl 1 and wsl 2.

https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack

**Comment by mkislik** [comment]
I already started using the Linux-based VSCode, but I didn't know if I should be running VSCode under WSL or in Windows, until I went through several articles about VSCode on WSL2.

Same question could arise when it comes to using any other development tool that exists in both Linux and Windows, such as PyCharm.  And what if someone wants to use Visual Studio on Windows to develop web apps?

My suggestion to improve the article is for it to mention that the WSL2 file system is either:
1. Non easily accessible from Windows (my impression of it because WSL2's explorer.exe seems to point to a virtual network drive).
2. Accessible from Windows.  If so, how do I access it.

**Comment by craigloewen-msft** [comment]
For the command, keep in mind that you need the wildcard `*` before and after to see the full package name!
Get-AppxPackage -Name "*<distro>*" | Select PackageFamilyName

![image](https://user-images.githubusercontent.com/42221804/70653064-9d253980-1c08-11ea-9512-a4cd3a3f4090.png)

And that's a great suggestion. At the bottom of that section we have a note of telling you not to access your files in AppData with Windows tools.

![image](https://user-images.githubusercontent.com/42221804/70653140-bded8f00-1c08-11ea-9c08-6bf56049c7b6.png)

I can add: `If you would like to access your Linux files from Windows that is possible via the path \\wsl$\<distroName>\ please visit [this blog post](https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-windows-10-version-1903/) to learn more.` 

Would that address your feedback?

**Comment by mkislik** [comment]
Yeah, you suggested addition makes sense to me: \\wsl$ seems to work for me.
I would mention that even ahead of all the info about AppData, which like you said might corrupt the data.  I'm guessing people might want to access data from windows even before they try to increase disk space.
