### ISSUE TITLE
Suggestion to change title to "Linux subsystem for Windows documentation" ?

### ISSUE THREAD

**Issue by ortymd** [MicrosoftDocs/WSL#535]
It is unfortunate that the product is called "Windows subsystem for Linux". Such a name misleads the developer to think that
a Win subsystem is somehow installed on Linux. It is better to swap OS names in my opinion...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3be148fb-e4a9-83b5-5b5a-7834eed7052f
* Version Independent ID: f583bc11-fe60-bb2c-af2b-dc0dae9fe81f
* Content: [Learn about the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about#feedback)
* Content Source: [WSL/about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/about.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Yes I can understand the confusion! The intention behind the title is the subsystem that runs in Windows which is for Linux applications, aka 'Windows' Subsystem for Linux' aka 'The Windows Subsystem for Linux'. It isn't possible to change the name now as it has been established for a few years, but thank you for the suggestion.
