### ISSUE TITLE
Accessing Windows applications from WSL?

### ISSUE THREAD

**Issue by kid1412621** [MicrosoftDocs/WSL#537]
I saw the example picture, starting a node app on Windows and request from WSL. But the ports aren't the same? (Win's 8000 and WSL's 5000?) 
I started a node app from Windows on my own machine, and get ip from WSL via `cat /etc/resolv.conf`, then request, it doesn't work. WSL side failed to connect. But I can ping this IP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [UX Changes between WSL 1 and WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#)
* Content Source: [WSL/wsl2-ux-changes.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-ux-changes.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Good catch! That was a bug in my print statement on my node.js app. I'll take this on to fix it. :) 

If you're still seeing an error on connecting to the Windows side, please consider filling a bug on the [WSL Github Repo](https://github.com/microsoft/wsl). Thanks!

**Comment by kid1412621** [comment]
ok, reported https://github.com/microsoft/WSL/issues/4793
