### ISSUE TITLE
Ubuntu WSL does not start default distro

### ISSUE THREAD

**Issue by rmgmediaval** [MicrosoftDocs/WSL#538]
I switched computers and exported my Ubuntu WSL to use on the new one. I followed the process [here](https://docs.microsoft.com/en-us/windows/wsl/wsl-config) and set my imported distribution as default. 

However, when I start my Ubuntu app (by clicking on the Ubuntu icon), it starts installing a new distribution. Is there something I am missing? How can I fix this?

**Comment by craigloewen-msft** [comment]
If you run `wsl.exe -l -v` what's the name of your distro? Did you use the same name as the one seen by the app? If you are running regular Ubuntu it will be `Ubuntu` and if you are running Ubuntu 18.04 it will be `Ubuntu-18.04`.  Make sure the names are the same and then it should work!

**Comment by rmgmediaval** [comment]
> If you run `wsl.exe -l -v` what's the name of your distro? Did you use the same name as the one seen by the app? If you are running regular Ubuntu it will be `Ubuntu` and if you are running Ubuntu 18.04 it will be `Ubuntu-18.04`. Make sure the names are the same and then it should work!

I used Ubuntu this time and I think it's starting as default. However, it is starting as root and not with the default user.

**Comment by craigloewen-msft** [comment]
We added in the ability to change your default user by adding in a line to your /etc/wsl.conf file in [build 18980](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18980). What version of Windows are you running? If you are using the latest version on Windows Insiders you should have access to this feature. (You can check your Windows version by running `ver` from command prompt)

**Comment by rmgmediaval** [comment]
Thanks Craig.
I actually found a way to fix that by running `Ubuntu config --default-user ted` in PS.
However, it looks like root has lost a lot of permissions?? (not sure why)
`root@TheBeast:~# su ted
bash: popd: /root: Permission denied
root@TheBeast:~#`
`root@TheBeast:~# sudo su ted
bash: popd: /root: Permission denied
root@TheBeast:~#`

**Comment by craigloewen-msft** [comment]
I'm not sure why that would have that result either. 

In interest of housekeeping for this Github issue, if the original issue is resolved (which I think it is) could you close it out, otherwise I'm more than happy to help keep troubleshooting!

And for further issues please post them at [the WSL Github repo](https://github.com/microsoft/wsl) as this repo is just for the docs, and you'll get more eyes on your issue with better responses, and you can always link to this issue so we can follow up there! :) Thanks!

**Comment by rmgmediaval** [comment]
Thanks for your help.
