### ISSUE TITLE
Add-AppxPackage

### ISSUE THREAD

**Issue by omidkrad** [MicrosoftDocs/WSL#539]
On Windows Server 2019 you can just use `Add-AppxPackage` command like in Windows 10. The steps [here](https://docs.microsoft.com/en-us/windows/wsl/install-on-server) to rename the package to `.zip` and extract and install are not needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install the Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server#feedback)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-on-server.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hey @craigloewen-msft -- if you could confirm this, I'll update the server install doc.
