### ISSUE TITLE
To correct a problem, you can only choose the fast loop, the slow loop update is less than 18917 or later

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/WSL#540]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/WSL.zh-CN/issues/7

The comments below were machine-translated
@qujian commented 10 hours ago — with docs.microsoft.com
"To ensure that you are using version 18917 or later, join the Windows Insider Program and select either the" fast "ring or the" slow "ring."
You can only choose the fast ring, not the slow ring, otherwise the update will not be possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
WSL 2 is now available in the slow ring! 

See [this article](https://blogs.windows.com/windowsexperience/2019/11/11/releasing-windows-10-insider-preview-build-19013-into-the-slow-ring/) announcing that build 19013 is available, and [this article](https://blogs.windows.com/windowsexperience/2019/10/29/announcing-windows-10-insider-preview-build-19013/) showing that WSL2 is in build 19013. 

Thank you for filing this! :)
