### ISSUE TITLE
Information wrong

### ISSUE THREAD

**Issue by ArchPrime** [MicrosoftDocs/WSL#541]
The term 'wsl' is not recognized as the name of a cmdlet, function, script file, or operable program.
Neither 'Ensure that the Windows Subsystem for Linux Optional Component is installed.'
or 'Additionally, if you are using an Arm64 device and running this command from PowerShell, you will receive this error. Instead run wsl.exe from PowerShell Core, or Command Prompt.' make a differnce

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Are you sure that you have the Windows Subsystem for Linux optional feature enabled? 

Could you please run this command from a PowerShell prompt with Administrator privileges and share the results? 

```powershell
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
```

Thanks!

**Comment by ArchPrime** [comment]
Hi - result is 
PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux            

Path          :
Online        : True
RestartNeeded : False

However when I attempt to use the wsl command as instructed here https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#finish-with-verifying-what-versions-of-wsl-your-distro-are-using, I get errors

**Comment by craigloewen-msft** [comment]
If the feature is enabled, then you should have access to WSL. The error you're seeing is PowerShell not being able to identify what command you're trying to run.

Can you check your Windows Path to make sure that C:\Windows\system32 is included there? You can see your path in PowerShell by running:

```powershell
echo $env:PATH
```

As well, do you have an executable called `wsl.exe` in C:\Windows\system32 ?

**Comment by ArchPrime** [comment]
Hi, looks like answer to both questions is ‘yes’

That said, I can access a linux shell, and from that,  even though I don’t seem able to execute those commands in the link, just typing ‘wsl’ invokes some help on usage

paul@YETI:/root$ wsl
WSL
Wsman Shell commandLine, version 0.2.1

USAGE: wsl COMMAND [PARAMS...]

COMMANDS:
identify  - WS-Identify
enum      - WS-Enumerate
get       - WS-Get
put       - WS-Put
invoke    - WS-Invoke
xclean    - Delete all files generated by this tool set
xcred     - Create or display credential file
xcert     - Get server certificate (saved to <IPADDRESS>.crt)

PARAMS specification is specific to a COMMAND.

Output will be saved to ./response.xml. If you want to run parallel
executions in the same directory, define RTFILEPREFIX in the environment.
Doing so may significantly increase files generated.

Requires: curl, xmllint, GNU core utilities.
Optional: xsltproc for output formatting, gpg for encrypted credential.
Optional: wget as alternate for curl when not available.
paul@YETI:/root$



Has the way wsl command works been changed since that guide was written? Or is there more than one version?

Cheers
Paul

**Comment by craigloewen-msft** [comment]
Running `wsl` inside of a Linux distribution will call out to a different process. Please run `wsl.exe` if you are inside of a LInux distro.

And it seems like you can access your distro fine, what version of Windows are you using? If you run `ver` in CMD it should tell you.

It's possible you could be on an earlier version of Windows. You need to be on build 18917 or higher to gain access to WSL2. You can get on these builds by becoming a Windows Insider. Instructions on how to do that are [here](https://insider.windows.com/en-us/getting-started/)! :)
