### ISSUE TITLE
Command for retrieving windows version is incorrect

### ISSUE THREAD

**Issue by Structed** [MicrosoftDocs/WSL#543]
The docs specify to run the `ver` command to retrieve the Windows build version (added via Issue #451 . However, this command does not exist.

The correct command is `winver`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install?source=docs#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by jeffstokes72** [comment]
C:\WINDOWS\system32>ver

Microsoft Windows [Version 10.0.18363.535]

**Comment by jeffstokes72** [comment]
You may want to try ver in command prompt as the doc suggests, instead of a ps prompt.

**Comment by craigloewen-msft** [comment]
That's correct, CMD's command is `ver` and PowerShell's is `winver`. Since the documentation states open Command Prompt we'll stick with `ver`. Thanks!
