### ISSUE TITLE
[SOLUTION] "The attempted operation is not supported for the type of object referenced." error after Windows Update

### ISSUE THREAD

**Issue by Vinigas** [MicrosoftDocs/WSL#547]
Windows Pro Insider Preview Build 19541.rs_prerelease.200102-1216.
WSL 2.0 Ubuntu.
All commands directed to any wsl-linux end up with instant echo "The attempted operation is not supported for the type of object referenced." and instant exit (Linux Subsystem Terminal closes itself, PowerShell just completes the command).

Fixed by uninstalling Ubuntu in store, disabling WSL feature, restarting PC and enabling WSL again, installing wsl-Ubuntu.

Uninstalling Ubuntu in store may be unnecessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#feedback)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/troubleshooting.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Seems to be related to this issue: https://github.com/microsoft/WSL/issues/4177

Glad you found a solution! I'll close this specific issue out, as we are tracking this error over on the main repo. Thank you for filing! :)

**Comment by assist726** [comment]
@craigloewen-msft How is uninstalling WSL and losing all data an acceptable solution? Currently running into the same problem

**Comment by amtriorix** [comment]
Same issue.  This is clearly another issue that Microsoft is developing like schoolboys in 1st grade.  They do create a subsystem running on HyperV, then it fails after an upgrade, you try to launch a shell, it crashes without leaving a note. Then they give you a solution like, well if your windows os does crash, format the drive ! Just lose all your data.  Microsoft, the day you wrote software was a black day for IT

**Comment by esunilkumare** [comment]
The solution mentioned in this link https://jon.sprig.gs/blog/post/2140 helped me solve the issue.



1. Copy below snippet 
2. Save it as a file wsl.reg
3. Execute the file to update the registry
4. Launch Ubuntu again
5. Issue resolved

`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinSock2\Parameters\AppId_Catalog\0408F7A3]
"AppFullPath"="C:\\Windows\\System32\\wsl.exe"
"PermittedLspCategories"=dword:80000000`

**Comment by dmgolembiowski** [comment]
> Same issue. This is clearly another issue that Microsoft is developing like schoolboys in 1st grade. They do create a subsystem running on HyperV, then it fails after an upgrade, you try to launch a shell, it crashes without leaving a note. Then they give you a solution like, well if your windows os does crash, format the drive ! Just lose all your data. Cygwin does not have all those issues. It runs native on the OS. Microsoft, the day you wrote software was a black day for IT, we would have a far better world and safer in terms of IT without Your crappy software and solutions that try to reinvent the wheel.

You do realize that there's another human being on the receiving side of this, right? The WSL contributors have collectively spent years of their lives away from friends and family to make something nice. I don't think it's appropriate to gaslight @craigloewen-msft when they've done nothing wrong here. Instead, we should probably be appreciative for those who work on this complex application. Can you imagine how daunting this project is? For how young it is, it's doing surprisingly well, don't you think?

Moreover, many individuals who work at Microsoft likely have no connection to those who wrote the "crappy software and solutions" you're referencing, because they're on different teams, perhaps at different companies, or maybe retired.

**Comment by maczamora** [comment]
As mentioned by @esunilkumare the article mentioned worked for me. Once there is a fix for this is there a way to remove this registry key edit? I'm guessing just to delete it but will that break anything going forward on my machine?

**Comment by randomgraphics** [comment]
> The solution mentioned in this link https://jon.sprig.gs/blog/post/2140 helped me solve the issue.
> 
> 1. Copy below snippet
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinSock2\Parameters\AppId_Catalog\0408F7A3]
> "AppFullPath"="C:\\Windows\\System32\\wsl.exe"
> "PermittedLspCategories"=dword:80000000
> ```
> 
> 2. Save it as a file wsl.reg
> 3. Execute the file to update the registry
> 4. Launch Ubuntu again
> 5. Issue resolved

nice fix. solved my issue too.

**Comment by mastervash** [comment]
> The solution mentioned in this link https://jon.sprig.gs/blog/post/2140 helped me solve the issue.
> 
>     1. Copy below snippet
> 
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinSock2\Parameters\AppId_Catalog\0408F7A3]
> "AppFullPath"="C:\\Windows\\System32\\wsl.exe"
> "PermittedLspCategories"=dword:80000000
> ```
> 
>     2. Save it as a file wsl.reg
> 
>     3. Execute the file to update the registry
> 
>     4. Launch Ubuntu again
> 
>     5. Issue resolved

Did the trick for me as well, thank you kindly.

**Comment by klesio123** [comment]
the suggestion of @esunilkumare worked out for me, thank you @esunilkumare!

**Comment by tekintopuz** [comment]
> 2\. wsl.reg

this works for me. Thanks a lot.

**Comment by salehov** [comment]
Thanks to @esunilkumare for solution, wsl.reg partially solved problem,
But running Ubuntu 20, not working properly. For example network doesn't work. 
Any can suggest solution this also?

**Comment by block-hac** [comment]
**OS:** _Windows 11_
**WSL:** _Ubuntu-20.04_

Run `PowerShell` as administrator then run follow commands.

(Maybe you need to download and install [wsl_update_x64.msi](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi) manually.)
```
C:\Windows\system32> wsl --shutdown
C:\Windows\system32> netsh winsock reset
```
Then, you should reboot computer then it works properly.

C:\Windows\system32> wsl --install -d Ubuntu-20.04

**Comment by iammunir** [comment]
> The solution mentioned in this link https://jon.sprig.gs/blog/post/2140 helped me solve the issue.
> 
> 1. Copy below snippet
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinSock2\Parameters\AppId_Catalog\0408F7A3]
> "AppFullPath"="C:\\Windows\\System32\\wsl.exe"
> "PermittedLspCategories"=dword:80000000
> ```
> 
> 2. Save it as a file wsl.reg
> 3. Execute the file to update the registry
> 4. Launch Ubuntu again
> 5. Issue resolved

thank you, I had the same issue and this solution worked for me

**Comment by saifabel** [comment]
After editing the registry with no success, I add the solution in this link https://github.com/microsoft/WSL/issues/5351#issuecomment-645298068  and it worked.


> > The solution mentioned in this link https://jon.sprig.gs/blog/post/2140 helped me solve the issue.
> > ```
> > 1. Copy below snippet
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > Windows Registry Editor Version 5.00
> > 
> > [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinSock2\Parameters\AppId_Catalog\0408F7A3]
> > "AppFullPath"="C:\\Windows\\System32\\wsl.exe"
> > "PermittedLspCategories"=dword:80000000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 2. Save it as a file wsl.reg
> > 
> > 3. Execute the file to update the registry
> > 
> > 4. Launch Ubuntu again
> > 
> > 5. Issue resolved
> > ```
> 
> Did the trick for me as well, thank you kindly.

**Comment by farzadkb** [comment]
> The solution mentioned in this link https://jon.sprig.gs/blog/post/2140 helped me solve the issue.
> 
> 1. Copy below snippet
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinSock2\Parameters\AppId_Catalog\0408F7A3]
> "AppFullPath"="C:\\Windows\\System32\\wsl.exe"
> "PermittedLspCategories"=dword:80000000
> ```
> 
> 2. Save it as a file wsl.reg
> 3. Execute the file to update the registry
> 4. Launch Ubuntu again
> 5. Issue resolved

Thanks man.
You saved my life

**Comment by asyarifstudio** [comment]
> PermittedLspCategories

can anyone explain what this solution does? I guess it's giving some permission for WSL but what permission?

**Comment by q2333gh** [comment]
> 
it worked! immediately ! thanks !
