### ISSUE TITLE
This UserVoice instance is no longer available.

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/WSL#548]
Under Where can I provide feedback?

&gt;Our command-line UserVoice portal

https://wpdev.uservoice.com/forums/266908-command-prompt/filters/top

produces:

&gt;This UserVoice instance is no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd5bfb4-8a38-1f09-0d36-6b9abe9b8b08
* Version Independent ID: 156d9535-c2a5-bc8d-af24-342a13832abf
* Content: [Frequently Asked Questions (FAQ)](https://docs.microsoft.com/en-us/windows/wsl/faq)
* Content Source: [WSL/faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Fixed! :) Thanks for filing.

https://github.com/MicrosoftDocs/WSL/commit/33290fd88a461a1a36d6106e737490bd57dc77bd

**Comment by spottedmahn** [comment]
cool, thanks!

---

Why does GitHub think there are so many changes 🤔?  It looks like only that bit was changed.

![image](https://user-images.githubusercontent.com/14079228/72451436-ed546600-3789-11ea-8279-e56cf7999b02.png)

Line endings? 🤔  Reference: https://github.com/aspnet/AspNetCore.Docs/issues/7485

**Comment by craigloewen-msft** [comment]
Yes likely a line endings change in that file. Changes are at the bottom.
