### ISSUE TITLE
Turned on Windows Subsystem for Linux yesterday, I assume it must be WSL2

### ISSUE THREAD

**Issue by PetRose** [MicrosoftDocs/WSL#551]
The --Help advise given by the wsl.exe (both in plain CMD as well as PS) does not mention the mechanism of closing WSL sessions using the:` --shutdown <distro>`
Nor does is not explain how one picks up the distro name, since my Ubuntu 18.04 LTS seems only to be known as (using uname-a): Linux 
None of the commands explained here, [wsl-config...](https://docs.microsoft.com/en-us/windows/wsl/wsl-config) seems to work either.
I have never installed any beta nor WSL 1. I do have the Cygwin, installed, but cannot imagine there's a command similar to wsl.exe taking precedence.

Several in various blogs seems also to mention switch: -t or `--terminate`

None of the above works for me, in my Win10 HOME 64bit with above Ubuntu.
Gives syntax error message: **Invalid command line option** 

I want to ensure my filesystem is exposed to the distro i'm running, without remembering the mount points and commands, using the WSL.conf. And for now, its seems one has to reboot (or hard kill tasks) in order to make it run...Hoped an easier way was to run wsl.exe to gracefully shut down instances.

Also, it would be useful (best practice, I guess) to have the version build, put into the --Help output.

Suggested to file an issue here, from below first bullet:
* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

Btw. My docker is running fine using the Oracle vbox.

**Comment by craigloewen-msft** [comment]
The instructions on how to install WSL2 are here: https://docs.microsoft.com/en-us/windows/wsl/wsl2-install which shows you how to get started with WSL2!

As WSL2 gets closer to release we'll be revamping the docs to include all the new command line references with it, etc.
