### ISSUE TITLE
exiting from cmd.exe ran from within wsl

### ISSUE THREAD

**Issue by datocrats-org** [MicrosoftDocs/WSL#557]
Your example of running cmd.exe from within WSL is cool, but when I send multiple lines of script to cmd.exe including a final line of `exit` it does not exit back into the WSL bash.  I don't want to open wsl again from the cmd within WSL, and I think the eof or key settings are what may be causing an issue.  I imagine you could script more windows based things using native linux tools were this not a limitation (if it is) or bug (I can't tell which).

**Comment by craigloewen-msft** [comment]
Try running `cmd.exe /c echo 123` this runs the `echo` command and exits afterwards. Thanks for filing!
