### ISSUE TITLE
When will WSL 2 be available for regular Windows 10 channels?

### ISSUE THREAD

**Issue by shaunluttin** [MicrosoftDocs/WSL#558]
Currently, WSL 2 is available through the Windows Insiders Program. When will it be available through regular (non-Insider) Windows 10 channels?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq?source=docs#feedback)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
In the first half of 2020! In other words, soon! I'll take this on as an issue to add that answer to the docs.

**Comment by pieterlukasse** [comment]
that is great news. Waiting anxiously for this!

**Comment by aetherical** [comment]
Are there any updates?

**Comment by Kaos-Industries** [comment]
Would also like to know whether there are any updates, and whether the COVID-19 situation affects the scheduled rollout at all.

**Comment by craigloewen-msft** [comment]
WSL2 will be available in [Windows 10 version 2004](https://devblogs.microsoft.com/commandline/wsl2-will-be-generally-available-in-windows-10-version-2004/). This will release in the upcoming months! There isn't a set date yet, but please stay tuned for any Microsoft announcements. :)

**Comment by davidAg9** [comment]
please add the issues of network connection problem with wsl 2
