### ISSUE TITLE
Test Compile times

### ISSUE THREAD

**Issue by K2AAE** [MicrosoftDocs/WSL#559]
I created a Ubuntu 18.04 WSL 2 image, added the tools and source needed to compile Microphthon for NUCLEO-H743ZI and compiled it. It took around 20 to 30 minutes to build, I must have fallen asleep for a few minutes. 
Using WSL 1 I had done same and the compile was complete it 2:45 that is 2 minutes and 45 second, you can't read any of the output it is going by so fast, on WSL 2 you could read the entire screen waiting for the next line.... I am trying to determine why, is it where I located my source files? I have a 512GB M.2 C: drive (NOT SATA) and a USB 3.2 6TB D: drive also a 100GB E: SSD SATA drive. I just learned that WSL lives in my C:\~\APPDATA from what I can tell so everything that was saved to /home/me/micropython is on the C: drive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c94eeb-5969-cb2d-fc63-1d4074070812
* Version Independent ID: def2349f-07a2-e772-0583-e5e3ce5983d4
* Content: [About WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-about#feedback)
* Content Source: [WSL/wsl2-about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-about.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hi @K2AAE - One thing to look at / consider is where you are installing / compiling your files. You'll have MUCH better performance and speed if you keep all of your files on the same operating system --- using BASH (Ubuntu) tools on files that are stored on Windows (C: drive) will make things very slow. Storing all of your files in the Ubuntu directory: \\wsl.localhost\Ubuntu-18.04\home\<your-user-name> will make things MUCH faster to use with Bash/Ubuntu tools. A quick way to check the directory your in is to open File Explorer from your command line with: `explorer.exe .` (don't forget the period)

If I'm misunderstanding your issue, I recommend reopening it in the product development repo: https://github.com/microsoft/WSL/issues/  ...unless it does relate to a request for updating the documentation, in which case please re-open this issue with more details. 

Thank you!
