### ISSUE TITLE
Confirm WSL is enabled should mention that an elevated (admin) powershell should be used

### ISSUE THREAD

**Issue by dennisvanderpool** [MicrosoftDocs/WSL#562]
Confirm WSL is enabled
You can confirm that the Windows Subsystem for Linux is enabled by running the following in Windows PowerShell (admin):

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#feedback)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/troubleshooting.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Fixed !  https://github.com/MicrosoftDocs/WSL/commit/fb2d8d23f1592190e1fc3b30ad6443152455bcbe
