### ISSUE TITLE
Debian GNU/Linux manual download link downloads Debian Stretch instead of Debian Buster

### ISSUE THREAD

**Issue by tdashroy** [MicrosoftDocs/WSL#563]
The Microsoft Store version of Debian has been updated to the Debian Buster release (aka Debian 10), but the manual download link (which is the following aka.ms: https://aka.ms/wsl-debian-gnulinux) still downloads Debian Stretch (aka Debian 9). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual#feedback)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by hauntingEcho** [comment]
to add context, Buster became the stable release on July 6th, 2019

**Comment by bendyson** [comment]
Any progress on this?

**Comment by RobThree** [comment]
The Stretch URL is https://wsldownload.azureedge.net/DebianGNULinux_1-1-3-0_x64__76v4gfsz19hv4.Appx

Meanwhile I figured out the Buster version is 1.1.8 and the "id" is _probably_ `9msvkqc78pk6` but the following URL doesn't work:

https://wsldownload.azureedge.net/DebianGNULinux_1-1-8-0_x64__9msvkqc78pk6.Appx

I am creating a script that installs WSL2 and Debian but I need a way to be able to install Buster, not Stretch.

**Comment by asvc** [comment]
According to Salsa, there was a [new package published to the store](https://salsa.debian.org/debian/WSL/-/commit/8ab121fd954e4744acf82cf7b8a925cefdcdeabd) a month ago. I don't immediately see the *.Appx though.

Perhaps this should be updated in MS documentation as it indeed points to the older, Stretch-based `DebianGNULinux_1-1-3-0_x64__76v4gfsz19hv4.Appx`.

**Comment by asvc** [comment]
Downloaded from the store:
```
TheDebianProject.DebianGNULinux_1.2.0.0_neutral_~_76v4gfsz19hv4.appxbundle
05610d20e38dc419f617e0c340426a927a3abca3
```

**Comment by geniejhang** [comment]
No one fixes this

**Comment by geniejhang** [comment]
appxbundle: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/0c70e5e3-5dc2-4d89-b288-caf5d2a8829e?P1=1604337813&P2=402&P3=2&P4=CEKs2S%2fsGIFwtMJcukYtw5uxLtf3g08tS9EYr%2fKAr24lo1Vj3fErmeqeAUES3AIrQmlnPvR1qcUr1AMQXHi5mA%3d%3d
BlockMap: http://dl.delivery.mp.microsoft.com/filestreamingservice/files/f6ab2796-2cef-406f-816a-bcd7237d14f4

**Comment by duaneking** [comment]
Close issue, this is clearly fixed as I just downloaded buster yesterday for WSL and it loaded debian 10.5 aka buster fine.

**Comment by hauntingEcho** [comment]
@duaneking did you do so via the manual link in the instructions for Windows Server (which this ticket is about), or via the store (which is not supported on Windows Server)?

**Comment by duaneking** [comment]
Via the store on win10Pro; The above issue does not make the scope limit you mentioned fully clear, so I'm trying to be helpful because I got here from a google search that had results that seemed to show that this was a win10 issue.

**Comment by tdashroy** [comment]
@duaneking the scope is mentioned in the issue description as well as via the link to the docs.microsoft page the issue was created for (which is the link next to Content in the Document Details). 

I went ahead and updated the title to make it clearer there.

**Comment by duaneking** [comment]
Its not listed in the title or the OP and so to google and people who come from it, that doesn't matter.  Individual comments have value for scope, sure, but from the view I have of this issue its not mentioned anywhere in the defect or current assignment or collected data that this is not a win10 issue.

![image](https://user-images.githubusercontent.com/569341/103701058-392f8a80-4f5a-11eb-81de-17bc86dbca65.png)

**Comment by tdashroy** [comment]
It's possible we're misunderstanding what each of us is referring to as the scope. What is the scope you're referring to that is missing from the title/OP?

The scope I intended for the issue is just that the manual download link for WSL Debian downloads Debian Stretch. Which is mentioned in the original OP here;
![image](https://user-images.githubusercontent.com/2366235/103703898-3e420900-4f5d-11eb-9539-c1963c32e11f.png)
and is now also mentioned in the title.

**Comment by nmaas87** [comment]
The manual download link on https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions for Debian GNU/Linux still points to Debian 9 Stretch, however, it should point to Debian 10 Buster's appx file. Please fix this.

**Comment by SomeWritesReserved** [comment]
Has anyone found a way to download the Microsoft Store Debian 10.z Buster package some other way? My Windows 10 LTSC devices do not have Microsoft Store but I need Debian 10.x Buster releases, thus I need a manual download link to Debian 10.x Buster releases.

**Comment by tdashroy** [comment]
@SomeWritesReserved before the Microsoft Store updated to Debian 10, I had luck upgrading from Debian 9 following instructions similar to those found here: https://davidsmith.is/2019/07/11/updating-your-wsl-debian-image-to-buster/.

**Comment by Biswa96** [comment]
You could use Docker image (single layer) as installation tarball in WSL.

**Comment by tdashroy** [comment]
Here's another [workaround](https://github.com/MicrosoftDocs/WSL/issues/877#issuecomment-683338384), provided by @dimithras in #877.

**Comment by craigloewen-msft** [comment]
Hi @tdashroy thanks for the pings here! I've updated the Debian offline package to be the latest Debian version on the store: 10.8. 

I'll add some more context here on the delay, and add my thanks here for your patience! The WSL team doesn't create the .appx's for the WSL distros, these are created by the distro maintainers themselves (Debian, Canonical, etc.). So we usually can only update the CDN where we store these .appx files for offline download when a maintainer sends us over the .appx files. Unfortunately the Debian maintainer wasn't able to send us a signed .appx file, and my investigation of how to get one petered out. I restarted it, found a method, and have now updated the Debian package and will be able to update packages more easily in the future. :) I'll close this issue out, thanks again!

**Comment by tdashroy** [comment]
Awesome, thanks @craigloewen-msft! In case you want to close out another issue, #792 looks like a dupe of this one to me.

**Comment by iranvir** [comment]
@craigloewen-msft Just checked with the Microsoft Store. Debian Bullseye is available there, however, the manual download link is now stuck at Buster.
I guess a lot of people would want both the links. Can you please suggest any long-term solution for this?
