### ISSUE TITLE
Please add links for the github issues

### ISSUE THREAD

**Issue by sgammill** [MicrosoftDocs/WSL#566]
e.g., it would be great for references like "GH 4629" to be hyperlinked to the github issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2faa612c-2d90-b3c4-0f01-e5d23c42bc04
* Version Independent ID: 3ed15eb4-f9d4-ae63-c0e6-354674e301b2
* Content: [Release Notes for Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/release-notes#feedback)
* Content Source: [WSL/release-notes.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @benhillis
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Closing as WSL has moved to being release via the Microsoft Store. You can find release notes for the most recent versions of WSL here (and includes links to issues and PRs): https://github.com/microsoft/WSL/releases
