### ISSUE TITLE
Commands don't work

### ISSUE THREAD

**Issue by leonavery** [MicrosoftDocs/WSL#567]
Most of the wsl commands on this page don't work on my system. For instance, when I type 

wsl --set-default-version 2

I just get the wsl help text. No --set-default-version option is listed in the help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Please make sure you're on the right version of Windows. You need to be on build 18917 or higher. You can do this by joining Windows Insiders, there are instructions on the Install WSL2 page on the docs. :) 

You can also check your Windows version by running `ver` in CMD.
