### ISSUE TITLE
Suggestion: One addition to the FAQ page

### ISSUE THREAD

**Issue by sna-scourtney** [MicrosoftDocs/WSL#570]
Where in the native Windows file system is the container for the WSL Linux root filesystem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd5bfb4-8a38-1f09-0d36-6b9abe9b8b08
* Version Independent ID: 156d9535-c2a5-bc8d-af24-342a13832abf
* Content: [Frequently Asked Questions (FAQ)](https://docs.microsoft.com/en-us/windows/wsl/faq)
* Content Source: [WSL/faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
These files are in your Appdata folder. Please do not access and try and change these files as they could corrupt your system and lead to data loss. 

I'd recommend using `\\wsl$\` in File explorer to access your Linux files. For more info please [read this article](https://devblogs.microsoft.com/commandline/do-not-change-linux-files-using-windows-apps-and-tools/).
