### ISSUE TITLE
Create and update user accounts for WSL distributions

### ISSUE THREAD

**Issue by kwsGit** [MicrosoftDocs/WSL#583]
f you need to update the forgotten password on a distribution that is not your default, use the command: wsl -d Debian -u root, replacing Debian with the name of your targeted distribution.

wsl -d Debian -u root   DIDN'T work
wsl -u root -d Debian DID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Create and update user accounts for WSL distributions](https://docs.microsoft.com/en-us/windows/wsl/user-support#feedback)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/user-support.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Can you double check if the command was put in correctly? What error did you get when you ran it? I'm unable to reproduce the error with Ubuntu.

![image](https://user-images.githubusercontent.com/42221804/76354741-47783000-62d0-11ea-97f5-0afdbd710182.png)

**Comment by kwsGit** [comment]
I have just tried this on all my distributions and it works, it does not
matter what order I type -d & -u. Maybe I had a typo in it when I was using
it, but it's definitely ok now

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
