### ISSUE TITLE
Hyper-V does not have accelerated graphics

### ISSUE THREAD

**Issue by kriston** [MicrosoftDocs/WSL#584]
I don't want to use Hyper-V under VirtualBox because Hyper-V does not support accelerated graphics. Surely we can figure out some way for the two engines to coexist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#feedback)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
If you are able I'd recommend trying out Linux GUI app support in WSL on Windows 11 as this does have accelerated graphics support.

https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps
