### ISSUE TITLE
How can I revert from WSL 2 to the earlier version of WSL?  (Need to remove conflict with VirtualBox)

### ISSUE THREAD

**Issue by eliotmoss** [MicrosoftDocs/WSL#590]
I had WSL 1 running fine and co-existing with VirtualBox.  I then upgraded my OS (that was due anyway) and upgraded to WSL 2, because I wanted to try it out and check the performance benefits.  That caused VirtualBox to stop working (as described in various VB forum threads, etc.).  I really needed VB, so I turned off Hyper-V (which is the thing that interferes with VB, apparently).  Of course that breaks WSL 2.  Just doing --set-version Ubuntu 1 is not enough to revert (though it "worked", i.e., the command did not complain, because I turned Hyper-V back on temporarily).  But I would like to the run the "old" WSL version 1.

How do I revert?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
Command `wsl.exe --set-version <Distro> <Version>`

**Comment by charounsons** [comment]
From the command shell, run: wsl.exe --set-version Ubuntu 1
From Windows Powershell, run: wsl --set-version Ubuntu 1

This assumes you are using Ubuntu.

**Comment by eliotmoss** [comment]
That will downgrade the distro, but it does not downgrade the wsl /program/.  The program still insists on having VirtualMachineExtensions turned on, which is what interferes with VirtualBox.

**Comment by GoldenHashtag** [comment]
BTW if your goal was to run WSL and VirtualBox at the same time:
Latest release(6.1.4) of VirtualBox is now compatible with Hyper-V hypervisor again, as [changelog](https://www.virtualbox.org/wiki/Changelog) describes. 

> Windows host: Restore the ability to run VMs through Hyper-V, at the expense of performance

**Comment by eliotmoss** [comment]
Yes, I had seen that.  Supposedly the performance penalty is _really_ bad.  Sigh.  Doesn't someone know how to revert the WSL _program_?

**Comment by eliotmoss** [comment]
Sorry, didn't mean to close it - clicked wrong option.

**Comment by Arkhaeon** [comment]
@eliotmoss you just need to disable the Virtual Machine Platform feature.
Also don't forget to set the default version back to one.

dism.exe /online /disable-feature /featurename:VirtualMachinePlatform /norestart
wsl --set-default-version 1

**Comment by soconn** [comment]
I'm assuming turning VirtualMachinePlatform to on enabled Hyper-V. Try to disable hyperV in Windows Services.

**Comment by eliotmoss** [comment]
I know people are trying to be helpful, but the steps Arkhaeon suggested do not accomplish what is required.  After doing them, when I try to start wsl I get:

`Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install`

So it seems wsl itself is still version 2, which requires VMP.  The _distro_ is version 1 (fine), but the newer wsl won't run it without VMP.

**Comment by Arkhaeon** [comment]
@eliotmoss That's odd, I managed to do this yesterday because I needed to use VMWare virtualisation again...  Perhaps check to see if you have installed any other distros that are on WSL2 with `wsl -l -v`.

Might also be worth trying converting your distro back to wsl2 `wsl.exe --set-version Ubuntu 2` and back again `wsl.exe --set-version Ubuntu 1`.   

My WSL is definitely working again with Virtual Machine Platform, Hyper-V and Windows Hypervisor platform features all disabled.

**Comment by eliotmoss** [comment]
Ah!  I _thought_ I had revert the Ubuntu distro to version 1, but it was still at version 2.  I see a path forward, but I have a long backup running and can't reboot for while to test.  I'll edit this comment when I can ...

**Comment by b-hayes** [comment]
Yeah I tried WSL2 before and hyper-v made my system unstable.


I heard WSL2 didn't need hyper-v anymore and now so tried again but got stuck and now I'm this position. Hyper -v wasn't installed but VMware can no longer run because of something else.

I created a system restore point before setting up but restoring doesn't change anything.

I reversed what I did `dism.exe /online /disable-feature /featurename:VirtualMachinePlatform /all /norestart`
And restarted and still no effect.

I really hate that some feature prevents me from running applications and can't be undone without re-installing windows.

**Comment by eliotmoss** [comment]
I found that a recent change to Windows mean there is an additional setting I had to change.  It seems that some new security features are supported by running the kernel under Hyper-V -- it's called virtualization-based security.  I ended up having to go down into bcdedit.  I think the entry I change was nx, and I set it to OptIn.  This is the no-execute feature (prevent executing instructions fetched from data-only pages), also called DEP (data execution prevention).  Then you can turn off Windows Defender Advanced Threat Protections.  (Settings->Windows Security->Core Isolation->Memory integrity, and Memory access protection.  To make the nx change you mat need to turn Secure Boot off temporarily.  In that case, if it is off and your disk it BitLocker encrypted, you'll need the BitLocker key for the drive.  This is from memory, but I think it is the setting in question.  In any case, the goal is to get the virtualization at boot not done, because that is what turns Hyper-V on, even when you've apparently turned it off.  (What we really need is proper virtualization sharing between Windows and VirtualBox, but I don't know if that's in the cards).

**Comment by Jeoxs** [comment]
> From the command shell, run: wsl.exe --set-version Ubuntu 1
> From Windows Powershell, run: wsl --set-version Ubuntu 1
> 
> This assumes you are using Ubuntu.

This was the solution for me. I'm on Win10 Home insiders preview Build 20226. All ports on WSL were closed. rolling back to WSL 1 solved the issue for me. Thank you!

**Comment by lc5415** [comment]
None of these options are working for me. When I try to run any variant of `wsl --set-version Ubuntu 1` I get:
```sh 
Error: Oxffffffff
```

**Comment by davidljuba15031979** [comment]
```bash 
> wsl --set-version Ubuntu 1

Conversion in progress, this may take a few minutes...
Conversion complete.
```
It successfully uninstalled/downgraded to WSL1.

This fixed my problem related to `/mnt` folder slowness:

https://github.com/microsoft/WSL/issues/4197

**Comment by hapticPaper** [comment]
What if the reason for downgrading is to get direct LAN access to the VM? It's my understanding that was possible without proxying in v1 - will setting a distribution to v1 have any effect on the way networking is handled or will I just have a VM running on wsl1 in its virtual network?

**Comment by ray-johannsson** [comment]
Thank-you!

**Comment by bananabr** [comment]
Anybody has a working solution to rollback WSL to version 1?

**Comment by owlstead** [comment]
I think you need to temporarily enable virtualization to be able to downgrade to WSL 1. Let me check...

**Comment by goshante** [comment]
Don't use this command: `wsl --set-version Ubuntu 1`
This won't help you if you want to use version 1 before installing distro. Use this command instead, it has global effect: `wsl --set-default-version 2`

**Comment by Erich-Chen** [comment]
`VirtualMachinePlatform` is not required for running WSL 1. You may turn off the feature "WSL 1 does not requires" after installing a Linux distro with WSL 1.

Now turn off "Memory integrity" in ms-settings and reboot the system. Check in "msinfo32", ensuring `Virtualization-Based Security` is `Not enabled`.
VMWare Workstation or VirtualBox is happy with your system now, co-existing with WSL 1.
