### ISSUE TITLE
I have installed the Linux kernel update package,but when run " wsl --set-version Ubuntu 2" I still have this message :"WSL 2 需要更新其内核组件。有关信息，请访问 https://aka.ms/wsl2kernel"

### ISSUE THREAD

**Issue by 717009629** [MicrosoftDocs/WSL#591]
I have installed the Linux kernel update package,but when run " wsl --set-version Ubuntu 2" I still have this message :"WSL 2 需要更新其内核组件。有关信息，请访问 https://aka.ms/wsl2kernel"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Updating the WSL 2 Linux kernel](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel?source=docs#feedback)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by blackfan23** [comment]
Please try running `wsl --set-version Ubuntu-18.04 2` or with the version you are using

**Comment by 717009629** [comment]
> Please try running `wsl --set-version Ubuntu-18.04 2` or with the version you are using

![image](https://user-images.githubusercontent.com/16289643/76693169-d05de580-669b-11ea-8ac0-ae9fc209dd68.png)

**Comment by blackfan23** [comment]
Uninstall Ubuntu again. And choose another flavor/distribution and try once more.

**Comment by 717009629** [comment]
> Uninstall Ubuntu again. And choose another flavor/distribution and try once more.

I uninstall Ubuntu and then reinstall it ,I have the same message.

![image](https://user-images.githubusercontent.com/16289643/76701683-3a0edb80-66fe-11ea-8d06-0f15f2fe4e26.png)

**Comment by blackfan23** [comment]
Then I am at a loss. You could try to install the kernel update again as well (link in the error message). Have you activated virtualization?

**Comment by 717009629** [comment]
> Then I am at a loss. You could try to install the kernel update again as well (link in the error message). Have you activated virtualization? I cant read the exact message due to my language shortcomings though.

I have reinstalled the kernel update and activated virtualization ,but  it do not work.


The message is " The WSL2 requires an update to its kernel component .For more information pLease visit https: / aka. ms/wsl2kernel"

**Comment by blackfan23** [comment]
Alright, but I am at a loss, sorry. Hope this gets resolved for you soon.

**Comment by eHealtho** [comment]
C:\Users\user1>ver
Microsoft Windows [Version 10.0.19041.153]

C:\Users\user1>wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel

::Install the WSL2 Linux kernel update package
https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

C:\Users\user1>wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes... (takes 6 minutes at least)
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion complete.

C:\Users\user1>wsl --list --verbose
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         2

:: open Windows Terminal (Preview) and start a Ubuntu session
https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab  

user1@SURFACE:/mnt/c/Users/user1$

C:\Users\lemay>wsl --list --verbose
  NAME            STATE           VERSION
* Ubuntu-18.04    Running         2

**Comment by 717009629** [comment]
> C:\Users\user1>ver
> Microsoft Windows [Version 10.0.19041.153]
> 
> C:\Users\user1>wsl --set-version Ubuntu-18.04 2
> Conversion in progress, this may take a few minutes...
> WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel
> 
> ::Install the WSL2 Linux kernel update package
> https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi
> 
> C:\Users\user1>wsl --set-version Ubuntu-18.04 2
> Conversion in progress, this may take a few minutes... (takes 6 minutes at least)
> For information on key differences with WSL 2 please visit https://aka.ms/wsl2
> Conversion complete.
> 
> C:\Users\user1>wsl --list --verbose
> NAME STATE VERSION
> 
> * Ubuntu-18.04    Stopped         2
> 
> :: open Windows Terminal (Preview) and start a Ubuntu session
> https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab
> 
> user1@SURFACE:/mnt/c/Users/user1$
> 
> C:\Users\lemay>wsl --list --verbose
> NAME STATE VERSION
> 
> * Ubuntu-18.04    Running         2

My windows version is  10.0.19041.153.
I have installed "wsl_update_x64.msi",but I still have the mssage:"WSL 2 requires an update to its kernel component. "

**Comment by worcode** [comment]
I got the same problem @[Version 10.0.19041.153]

I have run `bash.exe` (or distro execution) on powershell. it will work again.

**Comment by worcode** [comment]
I have the same problem @10.0.19041.153.
When I have check with `wsl -l -v`. All wsl are stop running so I run `bash.exe` (maybe ubuntu.exe) on the powershell. It will work. I got the wsl back and still work file.

**Comment by aramis4791** [comment]
I am also facing the same issue. I tried to update the version before and after stopping the distro without any luck. I try to install the wsl2 update again I get the error message that update is applicable only for machines with Windows Subsytem for Linux as shown below
![Annotation 2020-03-15 234457](https://user-images.githubusercontent.com/8780753/76707648-02605d80-6717-11ea-85d4-4075dcb695ba.png)

**Comment by mario-lukic** [comment]
In case you have problem launching WSL2 after Kernel Update (saying it needs an update). Right click on MSI -> Uninstall. Then you can install Kernel update again and you should be able to launch WSL2 again.

https://www.reddit.com/r/bashonubuntuonwindows/comments/fi4d34/insiders_on_slow_ring_you_will_need_this/

**Comment by 717009629** [comment]
> In case you have problem launching WSL2 after Kernel Update (saying it needs an update). Right click on MSI -> Uninstall. Then you can install Kernel update again and you should be able to launch WSL2 again.
> 
> https://www.reddit.com/r/bashonubuntuonwindows/comments/fi4d34/insiders_on_slow_ring_you_will_need_this/

I tried to unistall and install Kernel update ,it does not work .
When i run " wsl --set-default-version 2" ,I still have the message "WSL 2 需要更新其内核组件。有关信息，请访问 https://aka.ms/wsl2kernel"

**Comment by 717009629** [comment]
I have solved the problem

I Install and reinstall the Kernel Update ,but there is no "kernel" file in "C:\Windows\System32\lxss\tools".
I Extract  the "wsl_update_x64.msi" file, then  I get The "Kernel" file ,then I copy it to "C:\Windows\System32\lxss\tools". Then I can update wsl2.



The extract command is :  `  msiexec /a "wsl_update_x64.msi" /qb TARGETDIR="D:\xx"`

**Comment by aramis4791** [comment]
Thanks. It solved the issue I was facing in upgrading to WSL 2.

**Comment by lwqwag** [comment]
> 
> 
> I have solved the problem
> 
> I Install and reinstall the Kernel Update ,but there is no "kernel" file in "C:\Windows\System32\lxss\tools".
> I Extract the "wsl_update_x64.msi" file, then I get The "Kernel" file ,then I copy it to "C:\Windows\System32\lxss\tools". Then I can update wsl2.
> 
> The extract command is : ` msiexec /a "wsl_update_x64.msi" /qb TARGETDIR="D:\xx"`

I met the same problem and solved by this way.

**Comment by karol-preiskorn** [comment]
> wsl --set-version Ubuntu

I think that 

> 
> 
> I am also facing the same issue. I tried to update the version before and after stopping the distro without any luck. If I try to install the wsl2 update again I get the error message that update is applicable only for machines with Windows Subsytem for Linux as shown below
> 
> ![Annotation 2020-03-15 234457](https://user-images.githubusercontent.com/8780753/76707648-02605d80-6717-11ea-85d4-4075dcb695ba.png)

Run from cmd as admin (I have the same confiuson)...

**Comment by khpatel4991** [comment]
> I have solved the problem
> 
> I Install and reinstall the Kernel Update ,but there is no "kernel" file in "C:\Windows\System32\lxss\tools".
> I Extract the "wsl_update_x64.msi" file, then I get The "Kernel" file ,then I copy it to "C:\Windows\System32\lxss\tools". Then I can update wsl2.
> 
> The extract command is : ` msiexec /a "wsl_update_x64.msi" /qb TARGETDIR="D:\xx"`

This should be added to the instructions page. PLEASE! or fix the installer to copy the `kernel` file over and apply changes. This saved a lot of time.

**Comment by UkrainianCitizen** [comment]
@khpatel4991 This is a bug, this should be fixed not put on the instructions page.

**Comment by Bdoom** [comment]
Same thing, still haven't tried fix yet though

**Comment by UkrainianCitizen** [comment]
@Bdoom It seems that it worked for everyone who has tried it in this thread.

**Comment by PasqualeT-Git** [comment]
The extract command is : msiexec /a "wsl_update_x64.msi" /qb TARGETDIR="D:\xx"

I can't extract the kernel, can someone help me please?

**Comment by nadddy** [comment]
Use ZIP to extract to any folder. Copy FID_LXSS_KERNEL from extracted location to C:\Windows\System32\lxss\tools\ and rename this file to "kernel"
After this wsl2 works.

**Comment by etrimbymchd** [comment]
I had this issue. Now fixed..
HOWEVER I was wanting to move all my dev work from 18.04 to 20.04 anyway. so
I uninstalled all distros.
Disabled WSL in windows features.
Rebooted
Re-enabled WSL
Re-booted
Install Distro and all is good.

**Comment by nadddy** [comment]
> 
> 
> I had this issue. Now fixed..
> HOWEVER I was wanting to move all my dev work from 18.04 to 20.04 anyway. so
> I uninstalled all distros.
> Disabled WSL in windows features.
> Rebooted
> Re-enabled WSL
> Re-booted
> Install Distro and all is good.

I tried this but still installer did not detect WSL and I had to copy file manually.
Strange that MS is not fixing the installer even after GA release.

**Comment by etrimbymchd** [comment]
> > I had this issue. Now fixed..
> > HOWEVER I was wanting to move all my dev work from 18.04 to 20.04 anyway. so
> > I uninstalled all distros.
> > Disabled WSL in windows features.
> > Rebooted
> > Re-enabled WSL
> > Re-booted
> > Install Distro and all is good.
> 
> I tried this but still installer did not detect WSL and I had to copy file manually.
> Strange that MS is not fixing the installer even after GA release.

When you say installer are you referring to the kernel upgrade installer? If you are on 2004 the kernel would be up to date, and running the upgrade with an up to date kernel seems to give the error that WSL is not installed.

I did not run the kernel upgrader after disabling and re-enabling WSL.

**Comment by ajensenwaud** [comment]
I had the same issue after upgrading to the latest Windows 10 (Enterprise) today. For those of you who are struggling to extract the MSI file from the command line or using Winzip, you [can download 7zip instead ](https://www.7-zip.org/download.html)and right-click extract. It works well.

**Comment by SquidPony** [comment]
I had the same issue and moving the unzipped contents did not resolve the issue for me.

Uninstalling Ubuntu, Deactivating the wsl feature, and reactivating and reinstall worked. (System reboots between each step)

The only "weird" thing in my setup is that I don't have my storage/location settings to C: drive, in case that matters to figure it out (if it's still getting looked at)

Ubuntu 20.04 as well, in case that matters.

**Comment by KayLeung** [comment]
@717009629,

If you don't mind, this issue should be re-opened. Upstream has not fixed this bug yet.

**Comment by Akshayhackman** [comment]
### **Download the Linux kernel update package**
Please download the latest [WSL2 Linux kernel update](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi) package for x64 machines.

Note;
If you're using an ARM64 machine, please [download the ARM64 package](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_arm64.msi) instead.
Install the Linux kernel update package

**To install the Linux kernel update package:**
1. Run the update package downloaded in the previous step.
2. You will be prompted for elevated permissions, select ‘yes’ to approve this installation.
3. Once the installation is complete, you are ready to begin using WSL2!

**Comment by tigercosmos** [comment]
same problem. I've tried all method above but still fail.

**Comment by Esteban1891** [comment]
es solo actualizar https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

**Comment by LeonardoSSev** [comment]
> Use ZIP to extract wsl_update_x64.msi to any folder. Copy FID_LXSS_KERNEL from extracted location to C:\Windows\System32\lxss\tools\ and rename this file to "kernel"
> After this wsl2 works.

That really worked for me! Thanks a lot. I've been trying just reinstalling the .msi kernel updating file but I was getting the message to install de kernel update every time. Thanks a lot. This steps for extracting the .msi and manually "installing" on the lxss folder helped me.

**Comment by solider245** [comment]
> ### `**Download the Linux kernel update package**`
> 请下载适用于x64计算机的最新[WSL2 Linux内核更新](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi)程序包。
> 
> 注意;
> 如果您使用的是ARM64计算机，请改为[下载ARM64软件包](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_arm64.msi)。
> 安装Linux内核更新程序包
> 
> **要安装Linux内核更新软件包：**
> 
> 1. 运行在上一步中下载的更新程序包。
> 2. 系统将提示您提升权限，选择“是”以批准此安装。
> 3. 安装完成后，就可以开始使用WSL2了！

thank you! 这解决了我的问题。
