### ISSUE TITLE
WSL command has no --verbose option

### ISSUE THREAD

**Issue by ianmaddox** [MicrosoftDocs/WSL#592]
I've joined insider and installed all the updates, but I'm still not sure I have WSL2. When I run the commands suggested here, I get an error indicating that the wsl command does not support --verbose or -v.  Output:

```
PS C:\Windows\system32&gt; wsl -l -v
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments to run Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e &lt;CommandLine&gt;
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d &lt;DistributionName&gt;
        Run the specified distribution.

    --user, -u &lt;UserName&gt;
        Run as the specified user.

Arguments to manage Windows Subsystem for Linux:

    --export &lt;DistributionName&gt; &lt;FileName&gt;
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import &lt;DistributionName&gt; &lt;InstallLocation&gt; &lt;FileName&gt;
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are currently
                being installed or uninstalled.

            --running
                List only distributions that are currently running.

    -setdefault, -s &lt;DistributionName&gt;
        Sets the distribution as the default.

    --terminate, -t &lt;DistributionName&gt;
        Terminates the distribution.

    --unregister &lt;DistributionName&gt;
        Unregisters the distribution.

    --upgrade &lt;DistributionName&gt;
        Upgrades the distribution to the WslFs file system format.

    --help
        Display usage information.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by charounsons** [comment]
Try running the command from Windows Powershell instead. If you must use the command shell, you'll need to write wsl.exe instead of wsl.

**Comment by ianmaddox** [comment]
The command was run through powershell.
However, I found that I needed to go through about 4 more update/reboot cycles to complete the insiders process. After that WSL completed the upgrade.

**Comment by DanielGoldfarb** [comment]
@ianmaddox 
>However, I found that I needed to go through about 4 more update/reboot cycles to complete the insiders process. After that WSL completed the upgrade.

Can you please explain "update/reboot" cycles?  Are you talking about regular windows update, or something else??  Thanks.  --Daniel

(I'm having the same problem.  `wsl -l` works fine, but `wsl -l -v` does not work.)

**Comment by itmuckel** [comment]
@DanielGoldfarb

Have you activated the Windows Insider Build and ran Windows Update?

**Comment by DanielGoldfarb** [comment]
> @DanielGoldfarb 
> Have you activated the Windows Insider Build and ran Windows Update?

@itmuckel 
Not that i know of.  Can u point me to a good document on how to do that.

**Comment by itmuckel** [comment]
No. Go to Settings and type "insider" into the search bar and you will find the insider options. My OS isn't set to english, but it is probably Settings -> Updates and Security -> Windows Insider Program. There you can register your Microsoft Account for getting access to Insider Preview Builds. If that has been activated (probably needs a restart?), the next time you search for updates it will download a preview build for you.

WSL2 is currently only part of the preview build afaik.

**Comment by DanielGoldfarb** [comment]
Got it.  Thanks!
