### ISSUE TITLE
Question about risk of data lost

### ISSUE THREAD

**Issue by willyjchen** [MicrosoftDocs/WSL#593]
I'm worried about data lost when updating the kernel because I put my data in the ~/ folder to workaround the performance issue. Is there anyone successfully migrated from insider program?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Updating the WSL 2 Linux kernel](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel#feedback)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by willyjchen** [comment]
[SOLVED] Rollback the windows update `KB4541738` (the last one).

**Comment by hez2010** [comment]
I migrated successfully without any data lost.
