### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/WSL#596]
Hi team, 
There's a format bug reported here: https://github.com/MicrosoftDocs/WSL.zh-CN/issues/11
It looks like the code is cont correctly fenced and when localized the format is broken

the comments below were machine-translated
@dragon-archer commented yesterday
The code box in the "Installing the Linux Kernel Update Package" section on this page fails to render html properly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Updating the WSL 2 Linux kernel](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel#feedback)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
That block is just 
`>[NOTE!] Text`

Is there something we can change there to fix the rendering?

**Comment by CeciAc** [comment]
Hi team, 
The issue was reported again from the fr-fr page: https://github.com/MicrosoftDocs/WSL.fr-FR/issues/7
@nokura

**Comment by craigloewen-msft** [comment]
Hi @CeciAc how should we fix this error? Remove the `[NOTE!]` piece infront of the text?

**Comment by CeciAc** [comment]
@nokura can you please check this?
was reported again in ru-RU https://github.com/MicrosoftDocs/WSL.ru-RU/issues/7
