### ISSUE TITLE
Is there a way to update this component automatically?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/WSL#597]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/WSL.zh-CN/issues/10

@pikadun commented 2 days ago
I checked that there is no related update for windows update and microsoft store

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Updating the WSL 2 Linux kernel](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel#feedback)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
@pikadun we wont' have updates yet in Windows Update. If you follow the instructions on that page you'll be all set with the latest kernel!

**Comment by Chiramisu** [comment]
I missed it too... read the blog post associated with that article: 😉
https://devblogs.microsoft.com/commandline/wsl2-will-be-generally-available-in-windows-10-version-2004

**Comment by ahmadkakarr** [comment]
we still have to update it in version 2004 manually. sad.

**Comment by helshabini** [comment]
For updating: https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#set-a-distro-to-be-backed-by-wsl-2-using-the-command-line

**Comment by KalleOlaviNiemitalo** [comment]
"Windows Subsystem for Linux Update - 4.19.104" is on Windows Update now.

**Comment by craigloewen-msft** [comment]
WSL is now available in the Microsoft Store and can be updated automatically:
https://aka.ms/wslstorepage
