### ISSUE TITLE
WSL2 Steps for regular virtual machine

### ISSUE THREAD

**Issue by kyuumeitai** [MicrosoftDocs/WSL#601]
Hi there.

In this paragraph

> as WSL2 has a virtualized ethernet adapter with its own IP address. Currently, to enable this workflow you will need to go **through the same steps as you would for a regular virtual machine.** We are looking into ways to improve this experience!

What are those steps?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [UX Changes between WSL 1 and WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#accessing-network-applications)
* Content Source: [WSL/wsl2-ux-changes.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-ux-changes.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by titogarcia** [comment]
A possible way here:
https://github.com/microsoft/WSL/issues/4150#issuecomment-504209723

Would be best if Microsoft would offer a way officially.

**Comment by Biswa96** [comment]
It depends on your workflow and no one can provide thousands of ways...

**Comment by JuhJuhButts** [comment]
I believe that if you go into your network adapters, there should be a hyper-v adapter.
