### ISSUE TITLE
Followed steps, still getting "Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS."

### ISSUE THREAD

**Issue by udderchaos** [MicrosoftDocs/WSL#602]
I have enabled virtualisation on my BIOS and double checked this.

WSL 1 (Ubuntu-18.04 from the marketplace) is installed, initialised and works.

both 
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
completed with no errors.

my windows build is 19041.153

I restarted my pc after every step. 

Motherboard is Gigabyte B75m-d3v
Processor: Intel core i5-3450

Here is the error in power shell (ran as admin):
PS C:\WINDOWS\system32> wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by cyril-barragan** [comment]
What worked for me :
* Upgraded to Windows 10 pro
* Turn on windows functionnalities : Hyper-V, Windows Hypervisor platform, Virtual computer platform (not sure of the translation from french)
* restart
* type bcdedit /set hypervisorlaunchtype auto start  in an admin powershell
* restart

I hope il will help you too.

**Comment by leewin12** [comment]
In my case, I missed enabling virtualization BIOS config in SECURITY menu.
I did not think that extra virtualization option would be exists in SECURITY menu.
I hope it would be help to others.

**Comment by 1nfinity-5starZ** [comment]
I was having trouble upgrading from version 1 to version 2 running 'wsl --set-version Ubuntu 2', but I was not getting any errors at all.
The output was success-like but when i checked using 'wsl -l -v', the version was still 1.

Turns out I had to enable virtualization in my BIOS. That fixed it and now I'm running on version 2 correctly.

**Comment by craigloewen-msft** [comment]
Please try the troubleshooting steps here:
https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed
