### ISSUE TITLE
Incorrect Powershell Command

### ISSUE THREAD

**Issue by cawrites** [MicrosoftDocs/WSL#608]
This is not correct for Powershell
Rename-Item ./Ubuntu.appx ./Ubuntu.zip
Expand-Archive ./Ubuntu.zip ./Ubuntu

Powershell
Rename-Item Ubuntu_.appx Ubuntu.zip
Expand-Archive Ubuntu.zip Ubuntu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install the Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-on-server.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Great catch! I've fixed them to be `.\Ubuntu.appx` now. Thank you for the contribution!

https://github.com/MicrosoftDocs/WSL/commit/0a001ada2131f80dd77b114fc14f2fde43c947ad
