### ISSUE TITLE
Update content for WSL2?

### ISSUE THREAD

**Issue by cawrites** [MicrosoftDocs/WSL#609]
Will there be any updates to this page for WSL2
https://devblogs.microsoft.com/commandline/wsl2-will-be-generally-available-in-windows-10-version-2004/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Yes! :) We're working on it! We plan to pull those changes in before WSL2 becomes generally available.

**Comment by cawrites** [comment]
We should probably chat online at some point as our paths keep crossing. I am big user of WSL! 👍

**Comment by cawrites** [comment]
#please-close

**Comment by cawrites** [comment]
Thanks
