### ISSUE TITLE
I'm getting "This update only applies to machines with the Windows Subsystem for Linux" when try to update my system.

### ISSUE THREAD

**Issue by mazingaz** [MicrosoftDocs/WSL#611]
Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

**Comment by mazingaz** [comment]
I was using the tool downloaded from https://aka.ms/wsl2kernel

**Comment by mazingaz** [comment]
Below link have the solution:
I have to manually create the "kernel" file and copy into system folder.

[WSL 2 requires an update / The update only applies to machines with WSL #5014](https://github.com/microsoft/WSL/issues/5014)

**Comment by sonook** [comment]
Working solution for this issue.
https://youtu.be/4czn-4uu65c
