### ISSUE TITLE
Vim ubuntu1804.exe + conhost reverse problem

### ISSUE THREAD

**Issue by kshji** [MicrosoftDocs/WSL#614]
![vim_reverse](https://user-images.githubusercontent.com/6870358/78455436-16103b80-76a7-11ea-8563-ba110b7d7c99.png)

ubuntu1803.exe and  vim when insert new line, you got reverse line.

Win10 18363.

This problem has been open over year.

If you Console, then it works. 

conhost.exe tty/wrapper problem ?

On the beginning use of Ubuntu 18.04 this works fine.

Ubuntu1804.exe has updated 2020-03-09. Still same problem.

conhost.exe is over 1 year old. I'ms sure that that update give this problem and stll user are waiting fixing.

**Comment by WSLUser** [comment]
So why are you filing a docs issue? You should be filing your issue on the Windows Terminal github page (where the conhost code lives): https://github.com/microsoft/terminal.

**Comment by craigloewen-msft** [comment]
Please file this at the Terminal page where it will have a better audience. Thank you for filing!
