### ISSUE TITLE
Version / OS build.  i'm confused

### ISSUE THREAD

**Issue by qwabra** [MicrosoftDocs/WSL#615]
> Ensure that you have WSL installed ... and ... Windows 10 build 18917 or higher

Version / OS build

https://docs.microsoft.com/windows/release-information/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
Versions are like a milesotone and builds are like every step to walk between milestones.

**Comment by Biswa96** [comment]
Versions are like a milestone and builds are like every step to walk between milestones.

**Comment by craigloewen-msft** [comment]
@Biswa96 is correct, WSL has not yet been officially released as part of a general release. Once it is we'll update the documentation indicating which general release it's available in. 

I'll close this question out for our own bookkeeping, but feel free to respond if you have more questions (Just make sure to tag my name!) Thanks.
