### ISSUE TITLE
Disable Legacy Console prior to starting installation

### ISSUE THREAD

**Issue by kwf26** [MicrosoftDocs/WSL#618]
Please update the installation documents to advise users to disable the legacy console option in cmd.exe's properties otherwise the distro will fail initial installation. 
the exact error message is "Unsupported console settings. In order to use this feature, the legacy console must be disabled." and occurs when trying to set up the initial userid. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
The option to enable legacy console is disabled by default at the time of installation. So, if any user enable legacy console option its upto them.

**Comment by kwf26** [comment]
Installation of what? Windows or WSL or a Linux Distro? 
That setting was likely inherited across upgrades from win2k -> XP -> 7 -> 10 if its a windows system. 
I don't recall choosing to use or not use the legacy console when I installed WSL as a bash shell when that first came out.
The Microsoft store that I pulled the Ubuntu distro from never asked me about it either.
The point of my post was that people should know to check that before running the downloaded Linux distro for the first time. I guarantee you that there are millions (or at least several thousands) of windows users who'll eventually try WSL who have no idea whatsoever about the legacy console setting itself let alone what it's set to.  I never had to look at it before and I've been using PCs since DOS 2.11 and Linux since 1993.

I was really saying to have the users check their legacy console setting and make sure it's disabled otherwise they will experience unhappiness and setup failure.

**Comment by Gl4di470r** [comment]
Blaming the user for an easily unintentional console setting without any warning or pre-check is a really bad user experience.

**Comment by stuckj** [comment]
> Blaming the user for an easily unintentional console setting without any warning or pre-check is a really bad user experience.

Agree with this. I just hit this because I enabled the legacy console days before even installing WSL (to support an older console app). I had no idea this would affect WSL installation.
