### ISSUE TITLE
There should be an Ubuntu.appx link (not just 16, 18)

### ISSUE THREAD

**Issue by udubnate** [MicrosoftDocs/WSL#619]
I see a link for the windows store page, but a direct link to the appx would be nice for this document.

https://aka.ms/wsl-ubuntu (link to download, not windows store link)

Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

**Comment by craigloewen-msft** [comment]
Fixed!
https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions
