### ISSUE TITLE
wsl --set-default-version 2

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/WSL#625]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/WSL.zh-CN/issues/16

The comments below were machine-translated

@alabohai commented 10 hours ago — with docs.microsoft.com

This command is not valid.
PS C: slwsl--set-default-version 2
Command-line option sits invalid: --set-default-version
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe (parameters) (options... ) (CommandLine)

Arguments for running Linux binaries:

If no command line is provided, wsl.exe starts the default shell.

--exec, -e and commandLine
Execute the specified command without using the default Linux shell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by cotneit** [comment]
Your version of Windows doesn't support WSL 2. For now, it's only available in Slow ring of Windows Insider builds (Current version - 2004, OS Build 19041). 
You can check your version of Windows by running "winver" (without quotes) in cmd or Run window.

As far as I know, version 2004 is expected to be released to public in May 2020.

**Comment by liuyongAlive** [comment]
Execute wsl --set-version <Distro> 2 in cmd, only the following prompts are not effective.
```
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
```
When cmd was executed as administrator, the command worked.

**Comment by OvrCafn8d** [comment]
@cotneit - you mention that 19041 is required but the page says 18917.. I also found that I could not execute wsl -l -v until i moved myself to the insiders ring as the verbose option was not being recognized.

**Comment by JDoes** [comment]
Are there videos of this being done successfully? I dont think these instructions are correct. I would like to see it actually happen with my own eyes. Gotta see it to believe it.

**Comment by cotneit** [comment]
@OvrCafn8d page says "build 18917 or higher", I said that current Windows Insider build in the Slow ring is 19041.

**Comment by OvrCafn8d** [comment]
Ugh.. I got mixed up with version and build numbers for windows.

**Comment by parkerault** [comment]
I'm having the same issue and I'm on the required build number:

![image](https://user-images.githubusercontent.com/78856/81209200-d3879a80-8f95-11ea-8468-fb1a489fbd6e.png)

My features config:

![image](https://user-images.githubusercontent.com/78856/81210294-50674400-8f97-11ea-9175-aea2b958ee7e.png)
