### ISSUE TITLE
Error date time

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/WSL#626]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/WSL.zh-CN/issues/17

@dragon-archer commented 14 hours ago — with docs.microsoft.com
In the wsl and wsl command section, part of the code block is below:

```
PS C:\Users\sarah&gt; wsl
scooley@scooley-elmer:/mnt/c/Users/sarah$ date
Sun Mar 11 19:56:57 DST 2018
scooley@scooley-elmer:/mnt/c/Users/sarah$ exit
logout

PS C:\Users\sarah&gt; wsl date
Sun Mar 11 19:55:47 DST 2018
```

The date in the first command is later than it in the second command! Is this a mistake or the time setting is error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#feedback)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Seems to just be a typo! I've switched the dates around. :)
