### ISSUE TITLE
WSL2 ERROR: The virtual machine or container with the specified identifier is not running.

### ISSUE THREAD

**Issue by jiangslee** [MicrosoftDocs/WSL#628]
![image](https://user-images.githubusercontent.com/27892476/79413694-390dea00-7fdb-11ea-8164-8abb46072da6.png)

![image](https://user-images.githubusercontent.com/27892476/79413774-6d81a600-7fdb-11ea-9fd5-9bc8d4b5bdea.png)

![image](https://user-images.githubusercontent.com/27892476/79413455-8ccc0380-7fda-11ea-8a6b-df30a0c4411f.png)

**SYSTEM:**
Windows 10 Pro     2004           10.0.19041.1

**ERROR:**
The virtual machine or container with the specified identifier is not running.
Press any key to continue...

After I updated Windows to 19041, WSL2 ubuntu1804 could not run,

I tried to reinstall my ubuntu from Windows Store, but it didn't work.

This error message is still reported when running ubuntu

Please help to see how to solve this problem

**Comment by craigloewen-msft** [comment]
If you're still seeing this error please file it on the WSL repo (this repo is just for tracking doc changes)

You can find the instructions to file an issue here: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#file-an-issue-bug-report-feature-request
