### ISSUE TITLE
iis

### ISSUE THREAD

**Issue by ubbc** [MicrosoftDocs/WSL#635]
Attempting to serve WSL 2 filesystem content through a Windows 10 build 2004 IIS virtual directory with UNC path fails.
e.g. \\\\wsl$\Ubuntu\Websites\TestWeb
where  \\Websites\\TestWeb on WSL 2 host has been granted unrestricted access 777 (read/write/executable access for user/group/all) 

Testing the connection within IIS reports:
 * Pass through authentication succeeds.
 * Authorization fails ( but reports "The application pool identity is valid." )

Exploring the UNC path shows the files but browsing to content reports:

| Detailed Error Information | |
|--|--|
| Module | IIS Web Core|
|Notification | BeginRequest |
|Handler | Not yet determined|
|Error Code| 0x80070043|
|Config Error | Cannot read configuration file|
|Config File | \\?\UNC\wsl$\Ubuntu\Websites\TestWeb\web.config|

This fails using the built in account or supplying credentials for a local account with access to the path. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 233355e5-2fe3-a827-a1bf-ef1ae3ee5f36
* Version Independent ID: 991e4422-12dc-68a6-21a6-9741710fd47a
* Content: [WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-index)
* Content Source: [WSL/wsl2-index.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-index.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This is a good issue! Could you please open it in the official WSL repo so we can follow up there? This is the docs repo, so you're likely to get a much better response on the official repo:

https://github.com/microsoft/wsl/issues

Thank you!

**Comment by ubbc** [comment]
Hi, 
Thank you. Please accept my apologies for raising it in the wrong place. I’ll open it in the other repo.
Kind regards,
Graham Deane

**Comment by ubbc** [comment]
Done.
