### ISSUE TITLE
Need update

### ISSUE THREAD

**Issue by PaleNeutron** [MicrosoftDocs/WSL#637]
`wsl --set-default-version 2` is outdated. 

```
PS C:\WINDOWS\system32&gt; wsl --set-default-version 2
Invalid command line option: --set-default-version
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
What version of Windows are you on? If you're on build 18917 or higher you should have access to that command.

**Comment by PaleNeutron** [comment]
@craigloewen-msft, my mistake, I have not check my winver since I remember build 18917 comes into preview a year ago.

But today, it is still a preview version.

**Comment by craigloewen-msft** [comment]
Yup! I'll mark this as resolved. It will soon be part of the general release of Windows in Windows 10 version 2004.
