### ISSUE TITLE
Accessing Windows applications from Linux

### ISSUE THREAD

**Issue by klunko** [MicrosoftDocs/WSL#640]
You write:
To access a Windows network application you'll need to use the IP address of your host machine. You can do so with these steps:
-- Obtain the IP address of your host machine by running the command cat /etc/resolv.conf and copying the IP address following the term nameserver.
-- Connect to any Windows server using the copied IP address.

In my case the command cat /etc/resolv.conf prints
nameserver 192.168.1.254
which is an IP of my wi-fi router, not host machine.

Environment:
Host: Windows 10 Home, version 1909, build 18363.778.
WSL: Ubuntu 18.04.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [UX Changes between WSL 1 and WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#feedback)
* Content Source: [WSL/wsl2-ux-changes.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-ux-changes.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
The nameserver is where you're getting your DNS info, if you have default WSL network settings that will point to your host machine. If you have custom settings you can make it point somewhere else.
