### ISSUE TITLE
Select network interface

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/WSL#641]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/WSL.es-ES/issues/3
The comments below were machine-translated

@PoleG97 commented 5 hours ago — with docs.microsoft.com
In case we have several WSLs, if they both have the same ip as the host, how can they communicate with each other?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd5bfb4-8a38-1f09-0d36-6b9abe9b8b08
* Version Independent ID: 156d9535-c2a5-bc8d-af24-342a13832abf
* Content: [Frequently Asked Questions (FAQ)](https://docs.microsoft.com/en-us/windows/wsl/faq#feedback)
* Content Source: [WSL/faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
All WSL instances run on the same virtual machine, with the same (virtual) network interface card, interacting with the host over NAT. The WSL instances are separated by namespaces.

They can communicate with eachother through localhost networking. 

@PoleG97
