### ISSUE TITLE
Keyboard Stop Working

### ISSUE THREAD

**Issue by camilotorresmestra** [MicrosoftDocs/WSL#642]
I just installed Ubuntu 16.04 and it lets me type the username but the keyboard seems to stop working when I have to type the password. Apparently if I press ENTER it doesn't recognize it as a blank password either. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Create and update user accounts for WSL distributions](https://docs.microsoft.com/en-us/windows/wsl/user-support#feedback)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/user-support.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by anonymusunkown** [comment]
Your keyboard didn't stop working. Ubuntu just doesn't show you your password. Just type your password in like normal and it will accept it. Then it will ask you to type it in again and type in your password again. Your keyboard didn't actually stop working, Ubuntu just doesn't show you the password as your typing.

**Comment by superkid200** [comment]
It is the case with console applications. If you type in passwords in console apps, it won't show up. net user in Windows also does that.

**Comment by camilotorresmestra** [comment]
Thanks, I haven't had any previous contact with Linux so far, thus I didn't knew this issue. Thanks, is there any way to bypass this 'security feature' so Ubuntu actually shows my password while I type it? thnx in advance

**Comment by superkid200** [comment]
Well I think that this article can help you. I have never tried it so you might have to make my words for it. And also I think it only works for sudo.
[https://www.omgubuntu.co.uk/2016/08/make-sudo-password-visible-terminal](url)
