### ISSUE TITLE
Using Docker without enable vt-x

### ISSUE THREAD

**Issue by KC2016** [MicrosoftDocs/WSL#643]
[Enter feedback here]
Can I use Docker in WSL without having vt-x enabled?
I need to work with Docker, but my machine is an Acer Aspire R14, that hides the vt-x from its BIOS. I am not able to enable this.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by TGinger01** [comment]
Had similar issue, this worked for me. docker-machine create default --virtualbox-no-vtx-check

**Comment by TBBle** [comment]
Without VT-x, you can't run Hyper-V, and hence won't be able to use WSL2, which is what Docker uses for its WSL-based mode integration.
