### ISSUE TITLE
Please add download link to Ubuntu 20.04

### ISSUE THREAD

**Issue by smholvoet** [MicrosoftDocs/WSL#645]
Please add a download link for [Ubuntu 20.04 (LTS)](https://t.co/M5NZIjn40F?amp=1s), for people who have no access to the Microsoft Store.

If anyone supplies me with a valid aka.ms link to Ubuntu 20.04, I can create the PR to update the docs.

Suggestion: https://aka.ms/wsl-ubuntu-2004

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
Download the `ubuntu-20.04-server-cloudimg-amd64-wsl.rootfs.tar.gz` file from here https://cloud-images.ubuntu.com/releases/focal/release/ then isntall it with `wsl.exe --import` command.

**Comment by Biswa96** [comment]
Download the `ubuntu-20.04-server-cloudimg-amd64-wsl.rootfs.tar.gz` file from here https://cloud-images.ubuntu.com/releases/focal/release/ then install it with `wsl.exe --import` command.

**Comment by AlanACruz** [comment]
I've been waiting on the https://aka.ms/wsl-ubuntu-2004 link as well.

I can install 20.04 on my personal machine using the Microsoft Store.  However I cannot use the Microsoft store on my work machine so I need to be able to download the appx file.

**Comment by wsbak** [comment]
Download ubuntu-20.04-server-cloudimg-amd64-wsl.rootfs.tar.gz on https://cloud-images.ubuntu.com/releases/focal/release/
mkdir Ubuntu_2004
wsl --import  Ubuntu-20.04  Ubuntu_2004  ubuntu-20.04-server-cloudimg-amd64-wsl.rootfs.tar.gz
wsl --list
--> Ubuntu-20.04 appears in the list

wsl -d Ubuntu_20.04
--> logged root
adduser <my_name>
usermod -aG sudo <my_name>
exit

wsl -d Ubuntu-20.04 -u <my_name>
--> logged <my_name>
cd

You can then create a Windows shortcut targeting    C:\WINDOWS\system32\cmd.exe /C "wsl -d Ubuntu-20.04 -u <my_name>"

**Comment by smholvoet** [comment]
@Biswa96 

> Download the `ubuntu-20.04-server-cloudimg-amd64-wsl.rootfs.tar.gz` file from here https://cloud-images.ubuntu.com/releases/focal/release/ then install it with `wsl.exe --import` command.

I'm unable to run `--import`, probably cause my work machine uses an old build (1809 LTSC, currently on build 17763), see issue https://github.com/MicrosoftDocs/WSL/issues/419.

A download link where I can manually install the O/S (as is the case with 18.04) seems like the only solution, especially for enterprise users who are on the Long-Term Servicing Channel which doesn't support the `--import` parameter or don't have access to the Windows Store.

**Comment by Biswa96** [comment]
If possible, [WslRegisterDistribution function][1] can be use to install it.
 
[1]: https://docs.microsoft.com/en-us/windows/win32/api/wslapi/nf-wslapi-wslregisterdistribution

**Comment by iggyvolz** [comment]
I am able to get it to work locally by downloading https://aka.ms/wsl-ubuntu-1804 and replacing the install.tar.gz file with ubuntu-20.04-server-cloudimg-amd64-wsl.rootfs.tar.gz as described above.  Of course all the metadata still points to 18.04, but the distro launches.

**Comment by Biswa96** [comment]
@iggyvolz I didn't mention it because the ubuntu-18.04.exe will find the distribution name (which is Ubuntu-18.04) if that distro name is registered/installed Ubuntu-20.04 tarball will not be installed. To circumvent this, one can edit the distro name in registry Or install it with WslRegisterDistribution function.

**Comment by voyager-gold** [comment]
Please try this one.
http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/49c0e483-ef7f-4b80-a3aa-50b13c4cb405?P1=1589790938&P2=402&P3=2&P4=Zjww4Z%2Bi7vWakf%2Bydg0jPB48TBLoyw2xDoeFxiBm1XSgPrt0vJTnuOBp95CTEt9VYNlMS2hZZ%2BkB8E6T3VDuKA%3D%3D

**Comment by maoxs2** [comment]
@voyager-gold I have tried your method.

It successfully downloaded `CanonicalGroupLimited.UbuntuonWindows_2004.2020.418.0_neutral_~_79rhkp1fndgsc.AppxBundle` and got `Ubuntu_2004.2020.416.0_x64.appx` from it. 

BUT after installing appx, I CANNOT OPEN the Ubuntu no matter inputing `ubuntu` in cmd nor click the app icon.

Maybe this is because of my windows environment which is LSTC.

**Comment by singhkpratham** [comment]
> I will explain how above link was generated.

I used your method to get appx download link for 20.04. The download file size was around 832 MB. Which seemed a bit large, so I got the PID of 18.04, pasted, and got the size to br 532 MB. While, appx i downloaded from https://docs.microsoft.com/en-us/windows/wsl/install-manual has size 218MB. 

Any idea why this difference?

**Comment by singhkpratham** [comment]
Downloaded the file and found that file size difference of about 2x is because the PID method to download downloads package with both ARM and x64 version. If I extract only the X64 appx file that is of expected file size (452MB).

**Comment by JSamir** [comment]
Is it really that hard to provide an .appx file for download now that Ubuntu 20.04 is in the store for some time?

It really sucks having to work from corporate workstations....

**Comment by maoxs2** [comment]
I have migrated my WSL from ubuntu18.04 to kali, in which I can get ubuntu-style commands and latest packages like ubuntu20. It's too hard for ltsc user waiting for such a simple appx.

**Comment by biiiipy** [comment]
+1 . How is this still not fixed?

**Comment by sevickson** [comment]
Just found this on https://docs.microsoft.com/en-us/windows/wsl/install-manual.
Direct link for appx: https://aka.ms/wslubuntu2004
And for ARM: https://aka.ms/wslubuntu2004arm

**Comment by craigloewen-msft** [comment]
Yes I've added a fix for this! My apologies on not notifying this issue board as well for it.

https://github.com/MicrosoftDocs/WSL/commit/e67eb4aedff57a304188ca3360aba25605f8bdb1

Thank you for filing your feedback! :)

**Comment by luisdev** [comment]
So, the simple fox is that the https://docs.microsoft.com/en-us/windows/wsl/install-win10 page should contain a link to the 
https://docs.microsoft.com/en-us/windows/wsl/install-manual page and an explanation that you can get the manual Ubuntu installer from that page when you are not able to download Ubuntu from the Microsoft Store (e.g. when a Corporate Policy prevents installations from the Windows Store on corporate computers.)

**Comment by Biswa96** [comment]
Here are some direct links from wslapi.dll:

1. https://wsldownload.azureedge.net/Ubuntu_1604.2019.523.0_x64.appx
2. https://wsldownload.azureedge.net/Ubuntu_1804.2019.522.0_x64.appx
3. https://wsldownload.azureedge.net/Ubuntu_2004.2020.424.0_x64.appx

**Comment by vxllvnuxvx** [comment]
try https://aka.ms/wslubuntu2004

**Comment by lukeaust** [comment]
> try https://aka.ms/wslubuntu2004

It works to me, thanks a lot

**Comment by Biswa96** [comment]
Check with curl like this:

```
$ curl -I "https://aka.ms/wslubuntu2004"
HTTP/1.1 301 Moved Permanently
Location: https://wsldownload.azureedge.net/Ubuntu_2004.2020.424.0_x64.appx
Server: Kestrel
Request-Context: appId=cid-v1:b47e5e27-bf85-45ba-a97c-0377ce0e5779
X-Response-Cache-Status: True
Content-Length: 0
Expires: Tue, 04 Jan 2022 15:41:13 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 04 Jan 2022 15:41:13 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
```

**Comment by LinoBarreca** [comment]
Any idea about the link for 2204?
I tried https://aka.ms/wslubuntu2204 but it didn't work.

**Comment by antonio-quarta** [comment]
> Any idea about the link for 2204? I tried https://aka.ms/wslubuntu2204 but it didn't work.

you can use https://wslstorestorage.blob.core.windows.net/wslblob/Ubuntu2204-220117.appx

from
https://github.com/MicrosoftDocs/WSL/issues/1741
and 
https://github.com/microsoft/WSL/blob/master/distributions/DistributionInfo.json
