### ISSUE TITLE
wsl --set-version Ubuntu-18.04 2  not working

### ISSUE THREAD

**Issue by girish2477** [MicrosoftDocs/WSL#646]
Hi,
I tried following step-by-step instruction from -https://docs.microsoft.com/en-us/windows/wsl/wsl2-install
winver : Microsoft windows version 1909 (OS Build 18363.778)
When i am step to execute "wsl --set-version Ubuntu-18.04 2" get  "Invalid command line option: --set-version". I noticed that --set-version option is not available.
Can you suggest what am i missing ?

Thanks

**Comment by Biswa96** [comment]
Quote from that article: 

> WSL 2 is only available in Windows 10 builds 18917 or higher

**Comment by maietta** [comment]
> Quote from that article:
> 
> > WSL 2 is only available in Windows 10 builds 18917 or higher

To make it more clear, apparently at this point in time we must opt-in to handing over browser history and other "diagnostic" data to Microsoft and switch to the Insider Program. This is less than ideal and even worse, not going to be an option for businesses like mine. I pay for the Pro version of Windows for business, i would think I wouldn't have to hand over data in exchange to be able to help develop software under WSL.
