### ISSUE TITLE
Not clear if WSL will run on a Windows VM. 

### ISSUE THREAD

**Issue by svoorakk** [MicrosoftDocs/WSL#647]
I am trying to understand if WSL will run on a Windows VM. There seems to be no mention of it in any docs or forums.

**Comment by craigloewen-msft** [comment]
Yes WSL 2 distros run using a virtual machine.

**Comment by mattwojo** [comment]
https://docs.microsoft.com/en-us/windows/wsl/faq#can-i-run-wsl-2-in-a-virtual-machine-
