### ISSUE TITLE
Generic Ubuntu link

### ISSUE THREAD

**Issue by doctorjei** [MicrosoftDocs/WSL#650]
Would be great if there were a generic Ubuntu link too (for the unversioned "Ubuntu" that always points to latest). There are some tools that only work out-of-the-box with the unversioned install (like IntelliJ' WSL integration).

Edit to add Suggested link: https://aka.ms/wslubuntu

The reason for this request is that the "versioned" link / appx doesn't work with all tools, some of which depend on the generic appx.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual#feedback)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by WSLUser** [comment]
Rename or alias the executible.
