### ISSUE TITLE
Location of WSL VM

### ISSUE THREAD

**Issue by kabnfever** [MicrosoftDocs/WSL#651]
I have successfully installed WS2 on Windows 10 Pro (ver: 10.0.19041.208) using Ubuntu as the OS.  It is my understanding that the VM used for WSL is located on the C: drive, but Microsoft does not provide any visibility to the configuration of the VM used by WSL at all nor is the VM used by WSL shown in the Hyper-V Manager.

Questions:
1) How does one find the VM (.vhdx file) used by WSL?
2) How does one move the VM (.vhdx file) used by WSL from the C: drive to a different drive?
    The reason for question #2, is that I wish to move the VM (.vhdx file) to a faster disc on a RAID controller.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd5bfb4-8a38-1f09-0d36-6b9abe9b8b08
* Version Independent ID: 156d9535-c2a5-bc8d-af24-342a13832abf
* Content: [Frequently Asked Questions (FAQ)](https://docs.microsoft.com/en-us/windows/wsl/faq#feedback)
* Content Source: [WSL/faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by SaifBoras** [comment]
You can find the vhdx file inside the following path :

C:\Users\<username>\AppData\Local\Packages\<WSL Distro>\LocalState

**Comment by kabnfever** [comment]
Thanks for the info SaifBoras. Now for the obvious followup:

Does Microsoft intend to allow the installer/user the ability to configure/set the target location to place these fairly heavy virtual disc files and all associated accoutrements?  Microsoft does this on other programs, including Hyper-V, why not WSL?


Take care.
Kevin Baroni

**Comment by craigloewen-msft** [comment]
The WSL VM is created using the vhdx that has a default location shown in an earlier comment. If you want to change the vhdx location you can use the wsl --import command. Here's an example:

https://craigloewen-msft.github.io/WSLTipsAndTricks/tip/install-different-drive.html
