### ISSUE TITLE
WSL2 installation prompt Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS

### ISSUE THREAD

**Issue by iam-ankit** [MicrosoftDocs/WSL#652]
when i try to upgrade wsl to version 2 it prompts:
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
even though i have virtualization enabled in both windows and bios

![msinfo32_Kxhl3VASRp](https://user-images.githubusercontent.com/27309592/80599564-c2e09d00-8a48-11ea-9274-60f0ef91e712.png)
![OptionalFeatures_Ug013wZDHm](https://user-images.githubusercontent.com/27309592/80599567-c411ca00-8a48-11ea-8cc2-7723861533ff.png)

**Comment by parkerault** [comment]
I'm having this issue as well; I left a comment on this issue: https://github.com/MicrosoftDocs/WSL/issues/625#issuecomment-624792510

**Comment by iam-ankit** [comment]
> ~I'm having this issue as well; I left a comment on this issue: https://github.com/MicrosoftDocs/WSL/issues/625#issuecomment-624792510~
> 
> Edit: I discovered that my BIOS had two different settings for virtualization, one in the CPU "Virtual Machine Support" and another in advanced settings "VT-d". Turning on VT-d solved the issue.

Yes.... I had it turned on too, but now suddenly, out of the blue it worked...

**Comment by craigloewen-msft** [comment]
Please check the troubleshooting steps listed here to help remedy this:

https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed
