### ISSUE TITLE
Another virtualizations crashed! VMware and virtualbox!

### ISSUE THREAD

**Issue by prettyamfora** [MicrosoftDocs/WSL#660]
Lost 4 virtual machines. When was installed WSL 1 all was fine, fut when was try to get second version WSL 2...virtual bux die
and now after 4 hours crazy reanimation my wm's  ....still nothing
and i cant to disable WSL. One good and fun thing...ubuntu terminal live!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by pechter** [comment]
Damned Microsoft Defender Device Guard.
WSL2 has some serious advantages over WSL1.  However, WSL2 doesn't coexist with VMware Player/Workstation or VirtualBox unless you have a fairly new cpu on the box.  VMware's betaing a version that works with the new Device Guard...  The dual 6 core Westmere-EP 5606  Xeons on the box here used for testing has to have WSL2 removed to test the same thing in Windows Subsystem  for Linux and VMware/Virtualbox... Ugh.
