### ISSUE TITLE
How to disable ALL WSL s ?

### ISSUE THREAD

**Issue by prettyamfora** [MicrosoftDocs/WSL#661]
Cant disable. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/troubleshooting.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
If you search for "Turn Windows features on or off" you can disable the "Windows Subsystem for Linux" option to disable WSL on your machine.

Thanks for filing!
