### ISSUE TITLE
Might include that WSL1 is not compatible with Ubuntu20.04 

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [MicrosoftDocs/WSL#662]
Setting up WSL, when I reached "Install your Linux Distribution of Choice" I went with the latest Ubuntu LTS - 20.04. After running into [this issue[(https://github.com/microsoft/WSL/issues/5125) trying to run `apt-key add`, I was pointed to [this warning that Ubuntu 20.04 is not yet compatible with WSL1](https://discourse.ubuntu.com/t/ubuntu-20-04-and-wsl-1/15291). 

I think this would be helpful to have highlighted in this install instructions page, as absent this warning, I think many people would probably assume choosing the latest LTS Ubuntu is a safe distro choice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by pechter** [comment]
WSL2 has some serious advantages over WSL1.  However, WSL2 doesn't coexist with VMware Player/Workstation or VirtualBox unless you have a fairly new cpu on the box.  VMware's betaing a version that works with the new Device Guard...  The dual 6 core Xeons on the box here used for testing has to have WSL2 removed to test the same thing in Windows Subsystem  for Linux.  Ugh.

**Comment by cgaolei** [comment]
Having this problem when adding `apt-key add` in 20.04LTS Sublinux system:

> gpg: can't connect to the agent: IPC connect call failed

**Comment by zico2211** [comment]
i removed gpg and installed gnupg1, and it worked...

$sudo apt-get remove gpg
$sudo apt-get install gnupg1

**Comment by MaxPowerWasTaken** [comment]
Interesting - thanks zico. Would you be willing to post that workaround on the ubuntu forum and MS/WSL github issue page I linked above? I'd be interested to see if the maintainers there agree that workaround is 'safe'. But sounds awesome, thanks!
