### ISSUE TITLE
How to Uninstall Ubuntu on Windows Server 2019 ???

### ISSUE THREAD

**Issue by brusezot** [MicrosoftDocs/WSL#663]
HELP ??

**Comment by EwertonJordao** [comment]
You can try to use [remove-appxpackage](https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=win10-ps), but first, you can get-appxpackage and list all appx installed on your environment. 

If you list won't return values of Ubuntu install, find where the location of ubuntu.exe and remove all files I think it's working to remove all ubuntu.
