### ISSUE TITLE
Not correct if you have legacy install of a distro

### ISSUE THREAD

**Issue by imcdnzl** [MicrosoftDocs/WSL#666]
I went to do this and it didn't upgrade from version 1 to version 2 and then see that it's because I have a really old WSL install (legacy). This can't be upgraded and should probably be covered. Instructions on removing are at https://docs.microsoft.com/en-us/windows/wsl/install-legacy

PS C:\Users\imcdn&gt; wsl --set-version Legacy 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The Legacy distribution does not support WSL 2.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Updating the WSL 2 Linux kernel](https://docs.microsoft.com/en-gb/windows/wsl/wsl2-kernel#feedback)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks for letting me know about this @imcdnzl. I just added a note linking to the uninstall instructions for these sort of legacy distros. Appreciate your help!
Here's my commit: https://github.com/MicrosoftDocs/WSL/commit/d76b69bfeb7df7d67658eef0ff2dfc2f9b70a405

Closing. Please reopen if I missed anything.   ~Matt
