### ISSUE TITLE
It seems this page contains quite ambiguous information

### ISSUE THREAD

**Issue by rkttu** [MicrosoftDocs/WSL#677]
AFAIK, WSL 2 is not available on the latest version of Windows Server LTSC because WSL 2 only available after the build 2004 release. Still, the server version of 2004 will be released only on the SAC channel. So the phrase 'You will need to update your Windows version and join the Windows Insider Program on the "Release Preview" ring until the public release in late May.' can be misled due to the below reasons, I think.

- LTSC version of Windows Server cannot upgrade to the latest version of the SAC channel. 
- SAC version of Windows Server also cannot be upgraded to the newest version of the SAC channel because Windows Server does not support the "in-place" upgrade.

So I suggest that this phrase should point that you need to evaluate the next version of SAC (2004) separately for WSL 2.

Also, If the Windows Server runs on the non-Microsoft Cloud, such as AWS, WSL 2 might not be available due to missing support nested virtualization (except bare metal class). So this documentation should mention this point to prevent further misunderstood.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install the Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server#feedback)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-on-server.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
This page has since been updated to represent the improved Windows Server support: https://github.com/MicrosoftDocs/WSL/commit/6d496e45a4ca046315363e4fe72297b396bc037c
