### ISSUE TITLE
Highlight that conversion might take long time

### ISSUE THREAD

**Issue by mohamedsaif** [MicrosoftDocs/WSL#679]
It would be good if we added a note that says conversion might take several mins or even hours depending on the target distro size (I migrated a heavily used Ubuntu distro from 1 to 2 and it took around 1 hour to complete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by cswoods6** [comment]
A progress bar would be nice to make sure it is working.

**Comment by mattwojo** [comment]
Thanks @mohamedsaif -- added a note. https://github.com/MicrosoftDocs/WSL/pull/709/commits/218542e01d21e3073b22a19e994667fd0c843806

Your migration took an hour?! ...that seems pretty excessive..?
