### ISSUE TITLE
If multiple users on the same Windows machine, use WSL2, will they use the same distro, or will they be duplicated on installation?

### ISSUE THREAD

**Issue by plastikfan** [MicrosoftDocs/WSL#682]
I imagine that this question will easily be misinterpreted. I have multiple user accounts on my windows 10 machine. I would like to use WSL2 (when available) for more than 1 windows account, but the first thing that worries me is duplications of the linux distro and hence inefficient disk space usage. Please tell me this isn't so. I haven't performed the installation yet, but will do ASAP, once 2004 is available. I know that the execution environments from different users will be on different instances, but this is not wwhat I getting at. What I want t know is, having installed WSL2 for the first windows account and let's say the Ubuntu distro, when I go to install WSL2 and Ubuntu for the second user's account, will it share the Ubuntu that's already been downloaded and stored for the first windows account for the second one? I would hope that would be the case otherwise that's a lot of disk wastage since those distros are not insignifant in size.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hi @plastikfan -- Thanks for the question. Have you tried this yet? WSL 2 is now available without requiring the Insider's preview. You just need to update to v2004 if you haven't already. If this isn't working the way that you think it should, please re-open this issue and let us know.

**Comment by homerobse** [comment]
I have ubuntu installed in my WSL (mine is WSL1, not 2) in one windows user. I have recently created a new user and WSL appears to be installed (the command exists in Powershell), but it doesn't start when I run it (neither from powershell, nor cmd, nor from the windows start menu).

How can I use (from my new windows user) the Ubuntu distribution I have installed in my old user?
