### ISSUE TITLE
Now VMWare workstation preview 20H1 can be used with WSL2

### ISSUE THREAD

**Issue by SmartPolarBear** [MicrosoftDocs/WSL#684]
It's time to update compatibility information on  https://github.com/MicrosoftDocs/WSL/blob/live/WSL/compare-versions.md

**Comment by mattwojo** [comment]
Thanks @SmartPolarBear -- same issue as https://github.com/MicrosoftDocs/WSL/issues/719
I'm confirming with the PM and will update. Closing this, but will keep the other open until the update goes live. Appreciate your contribution!
