### ISSUE TITLE
Can I install WSL 2 directly (WSL 1 don't need to be installed first) after the public release in late May?

### ISSUE THREAD

**Issue by wacow** [MicrosoftDocs/WSL#685]

**Comment by mattwojo** [comment]
No, currently you first need to enable WSL, then install WSL 1, then update to WSL 2. There is no way to install WSL 2 without installing WSL 1. (For now... the team is working on all sorts of updates and really appreciates feedback from the community on what's working and not working well... but that's better to share in the product repo: https://github.com/microsoft/wsl/issues)
