### ISSUE TITLE
"Set your distribution version to WSL 1 or WSL 2" code sections

### ISSUE THREAD

**Issue by LukaZeleznik** [MicrosoftDocs/WSL#686]
"Set your distribution version to WSL 1 or WSL 2" code parts are tagged to be inserted into Bash, when it should say Powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Great catch. Thanks @LukaZeleznik ...I believe I noticed this already and fixed it, but still appreciate the callout... sorry it's taken me a bit to get to addressing these issues. Please keep contributing via issues and PRs! :) ~Matt
