### ISSUE TITLE
link dead

### ISSUE THREAD

**Issue by Cleroth** [MicrosoftDocs/WSL#687]
Link in here is dead:
Choose your favorite GNU/Linux distributions from the Microsoft Store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3be148fb-e4a9-83b5-5b5a-7834eed7052f
* Version Independent ID: f583bc11-fe60-bb2c-af2b-dc0dae9fe81f
* Content: [An overview on the the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about#feedback)
* Content Source: [WSL/about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/about.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Cleroth** [comment]
Oh, maybe it just doesn't work on Windows LTSC?

**Comment by mattwojo** [comment]
Yes, guessing that link just doesn't work on LTSC because it aims to open the installed version of Microsoft Store... but here's a URL link: https://www.microsoft.com/en-us/search/shop/apps?q=linux

:)
