### ISSUE TITLE
some link is out of date

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/WSL#691]
The comments below were machine-translated

@bennylii commented 5 hours ago — with docs.microsoft.com
Some of the links above are outdated, and the new release has not yet been added

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual#feedback)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hi @CeciAc - Thanks for filing this issue. Could you be more specific about what links you're finding to be out of date?  I just looked through and they all seemed fine. I did add a link to the WSL 2 update instructions. (They are the same for manual download). https://github.com/MicrosoftDocs/WSL/pull/709
Closing this issue... but if I missed something that needs to be fixed... please reopen and let me know. :) ~Matt

**Comment by bennylii** [comment]
@mattwojo 
![image](https://user-images.githubusercontent.com/13807507/83379922-3e01ee00-a40f-11ea-85cc-d5679d99ba2b.png)
We have known ubuntu has released the ubuntu 20.04 and newer version, and I guess many read this document don't want to use 18.04 in this time.
So can you stick a 20.04 package on there?

**Comment by mattwojo** [comment]
Hey @bennylii - We have an ask for the 20.04 .appx package open to Canonical, but unfortunately don't have it available to add for downloading yet. Hopefully soon -- working on it! :)
