### ISSUE TITLE
Set default version

### ISSUE THREAD

**Issue by KevinBurton** [MicrosoftDocs/WSL#692]
The command 'wsl --set-default-version 2' gives me an error 
PS C:\Users\RKevi&gt; wsl --set-default-version 2
Invalid command line option: --set-default-version
Copyright (c) Microsoft Corporation. All rights reserved.
even though I have the proper version:
winver =&gt; 1909

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by MrDejwik** [comment]
AFAIK, it only works on winver 2004. I'm on insiders slow ring and it works fine.

**Comment by resonancedesigns** [comment]
I don't want to enroll in Windows Insider edition but we shouldn't have to wait too much longer hopefully for the public release. From the "important" note near the top of this document:
"The public release should arrive by late May."

**Comment by MrDejwik** [comment]
There is also an option to opt out of the insider program when the next major release of Windows is released. That's what I'm doing.

**Comment by WindyCityCassie** [comment]
So, to confirm, this page is incorrect and to actually set the version we currently need to run an insider version before we can set wsl version to 2.0?

**Comment by MrDejwik** [comment]
Well on the official Microsoft page it says that you need at least winver 2004, build 19041. Which you can currently only get by being in the insider program. But the update should be available to others by the end of this month.

**Comment by WindyCityCassie** [comment]
It does indeed, I have read it a few times and it just was not clicking to me. Forgot my other machine is on the insider programme, too, so I'll change this one and then try.  Appreciate your comment!

**Comment by MrDejwik** [comment]
No problem, glad I could help.

**Comment by mattwojo** [comment]
Windows 10 May Update version 2004 / build 19041 is now officially released... so no more need for an Insiders preview. :) Closing this issue.
