### ISSUE TITLE
date

### ISSUE THREAD

**Issue by DarthMuppet54** [MicrosoftDocs/WSL#693]
The modification date on this page is 05/12/2020 - quite obvious what that date is, but a year from now i have to guess May or December. not sure it matters what the format is, but it must be unambiguous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
We use the American date format for our docs, which is: `MM/DD/YYYY`. 
As a Canadian myself I also found it a bit out of order at first as well 😁.

**Comment by DarthMuppet54** [comment]
I should add that my comment was not to do with whose format is best or
worst, it's purely about conveying correct information. Having said that
though, MDY will only be observably correct to people in the US, Ghana and
Kenya.  *Everyone* else uses YMD or DMY.  Microsoft is an international
company, addressing an international audience, and it should reflect that.
Bet your lawyers don't use that date format ;-)
