### ISSUE TITLE
Admin Right Requirements

### ISSUE THREAD

**Issue by AkosBakos** [MicrosoftDocs/WSL#694]
Does this solution have any admin privilege requirements?
Can Docker mount with a limited user right as well?

**Comment by mattwojo** [comment]
Hi @AkosBakos - thanks for filing this issue. I'm closing as it needs to be more specific. Please reopen if you're able to be more specific with your question. 

Regarding admin privilege, you can open any WSL distribution with admin priviledges by finding the distribution in your Windows menu and right-clicking it's icon, then selecting "Run as administrator".  Here's an article with instructions on using Docker with WSL: https://code.visualstudio.com/blogs/2020/03/02/docker-in-wsl2

Again, please re-open if you're able to be a bit more specific with this question and we'll do our best to help. :) ~Matt
