### ISSUE TITLE
Typo in description of processors option

### ISSUE THREAD

**Issue by geek2focus** [MicrosoftDocs/WSL#700]
There's a typo for the description of the `processors  global option:
"How many processors to assign ot the WSL 2 VM" should be 
"How many processors to assign **to** the WSL 2 VM"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This is now fixed! Thank you for the feedback.
