### ISSUE TITLE
Upgrading WSL option invalid

### ISSUE THREAD

**Issue by invertium** [MicrosoftDocs/WSL#704]
I'm running Windows 19041 (just updated 2004) and ran:

https://docs.microsoft.com/de-de/windows/wsl/wsl2-kernel

and

https://docs.microsoft.com/de-de/windows/wsl/install-win10

my current wsl is version 1

```
wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         1
```

but when I run `wsl --set-version Ubuntu-18.04 2` I  get:

```
Die Konvertierung wird ausgeführt. Dieser Vorgang kann einige Minuten dauern...
Informationen zu den wichtigsten Unterschieden zu WSL 2 finden Sie unter https://aka.ms/wsl2
Die Anforderung wird nicht unterstützt.
```

Which basically says the option is invalid.

**Comment by invertium** [comment]
Solved, needed to restart the machine :/

**Comment by darioxz** [comment]
@invertium How long did it actually take to run this command after restarting?

**Comment by invertium** [comment]
@darioxz couple of minutes tops
