### ISSUE TITLE
This Article needs to be updated as May has arrived and ended and 2004 version is now GPA

### ISSUE THREAD

**Issue by vnextcoder** [MicrosoftDocs/WSL#705]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 233355e5-2fe3-a827-a1bf-ef1ae3ee5f36
* Version Independent ID: 991e4422-12dc-68a6-21a6-9741710fd47a
* Content: [WSL 2](https://docs.microsoft.com/en-gb/windows/wsl/wsl2-index)
* Content Source: [WSL/wsl2-index.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-index.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Fixed! Thank you for the feedback. :)
