### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by vvaznais** [MicrosoftDocs/WSL#707]
Thanks for letting know that it not compatible with VMware!
Is any plans to support WSL1 in future. I use VMWare and my tools now a mix of windows / Linux

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [An overview on the the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Yes! VMWare has released a [preview](https://blogs.vmware.com/workstation/2020/01/vmware-workstation-tech-preview-20h1.html) that will work with WSL 2. :)
