### ISSUE TITLE
`wsl --set-default-version 2` is not a valid Powershell command.

### ISSUE THREAD

**Issue by frasermarlow** [MicrosoftDocs/WSL#710]
`wsl --set-default-version 2` is not a valid Powershell command.

It returns:
```
PS C:\Windows\system32> wsl --list --verbose
Invalid command line option: --list
Usage: wsl.exe [option] ...
Options:
    -d, --distribution <DistributionName>
        Launch the specified distribition.

    -e, --exec <CommandLine>
        Execute the specified Linux command. The remainder of the arguments are
        used as the command line to execute.

    -u, --user <UserName>
        Run as the specified user.

    --help
        Display this usage information.

    --
        Stop parsing arguments and pass the remainder to the Linux process.
```
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Please make sure you are on the latest version of Windows to use `wsl --list --verbose`! You can check it by running `ver` from Command Prompt, and you need to be on build `19041` and higher. I'll investigate making this clearer in the doc :)
