### ISSUE TITLE
Missing powershell wsl command parameters

### ISSUE THREAD

**Issue by ken-murray-by** [MicrosoftDocs/WSL#716]
Docs show powershell wsl command parameters such as "-set-version", "--set-default-version", and "-v", but most recent install shows these are invalid parameters.

**Comment by mattwojo** [comment]
Hi @ken-murray-by - These parameters should work fine. Just to clarify, you're opening a PowerShell command line and entering: wsl --list --verbose  (or you could use wsl -l -v)
...and it's not returning a list of the WSL distributions that you have installed?

**Comment by benwtks** [comment]
This isn't working for me either

**Comment by ken-murray-by** [comment]
The instruction docs found here https://docs.microsoft.com/en-us/windows/wsl/install-win10  do not match the actual params. It breaks down with the step to "Set your distribution version to WSL 1 or WSL 2". The  --set-default-version param does not exist.
