### ISSUE TITLE
VMware Workstation 15.5.5 & wslv2 work together, update docs

### ISSUE THREAD

**Issue by Ciberth** [MicrosoftDocs/WSL#719]
In the table it is stated that wslv2 will not work with VMware. Last update from VMware Workstation supports it. I tested it and works like a charm. This means that you can run docker desktop, wslv2 and have a VMware workstation virtual machine running at the same time. 

_"Windows 10 host VBS support: VMware Workstation 15.5.5 now runs on Windows hosts with Hyper-V features (For example: virtualization based security) enabled."_

Release notes: https://docs.vmware.com/en/VMware-Workstation-Pro/15.5/rn/VMware-Workstation-1555-Pro-Release-Notes.html 

Might be interesting to add the requirements and links to the documentation:
- Windows version 2004, build 19041
- VMware Workstation Pro 15.5.5

Kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [An overview on the the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @Ciberth -- I'm confirming with the PM whether we need to add any additional notes or context and will get this updated. :)  Appreciate you pointing this out.
