### ISSUE TITLE
WSLENV documentation improvements

### ISSUE THREAD

**Issue by ghouston** [MicrosoftDocs/WSL#720]
WSLENV documentation needs examples of how to use WSLENV and its flags.  https://docs.microsoft.com/en-us/windows/wsl/interop#wslenv-flags

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea49528-e5c5-4f64-841e-9fe036de304e
* Version Independent ID: edeb7cb5-afcf-1410-4966-f48ce5f6a19a
* Content: [Windows interoperability with Linux](https://docs.microsoft.com/en-us/windows/wsl/interop)
* Content Source: [WSL/interop.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/interop.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by dustinevan** [comment]
Same question. I closed #721 in favor of this.

**Comment by dustinevan** [comment]
I set WSLENV=TMP on the windows side. In ubuntu neither $WSLENV or $TMP exist after restarting the shell.

**Comment by mattwojo** [comment]
Thanks @ghouston and @dustinevan. I just added a link to this blog that contains WSLENV examples: https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/

Does that cover the examples you are wanting to see? Is anything missing?

My update commit: https://github.com/MicrosoftDocs/WSL/commit/cfb64228e1b82a70ee04eb504484affaa4746402

**Comment by ghouston** [comment]
@matthojo,

thanks! your blog post is very helpful.  it was easy to understand and the examples are very helpful.

why is this information separated into a blog post?  long-term its better to include this information directly within the WSL documentation.

the one thing that I don't see documented is information about _when_ the environment variables are translated and transferred between environments.  for example, if I have WSLENV setup to share windows PATH into a WSL linux.  if the windows PATH is changed in windows while the linux is running, will the linux immediately see the updated PATH? if not, when?

**Comment by dustinevan** [comment]
@matthojo Great! thanks. I second @ghouston's comment about having that info here in the readme. Having that here in github means that it's being versioned and maintained, rather than something that may be out of date. Also, if blog post does go out of date, it would be odd to open an issue here to ask someone to change the blog post. 

Many thanks for this!
