### ISSUE TITLE
Use a PowerShell cmdlet to enable the windows feature

### ISSUE THREAD

**Issue by ViperTG** [MicrosoftDocs/WSL#724]
In the first instruction you have us open PowerShell as admin and run dism.exe .. Why not use the PowerShell cmdlets to set a good example? The command is even easier thant the dism one.

I used:

    Enable-WindowsOptionalFeature -FeatureName VirtualMachinePlatform -Online -All -NoRestart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
We're also now waiting on the rollout of `wsl --install` which will hopefully be a big improvement for all.
Closing as this does not seem to require a doc update.
