### ISSUE TITLE
Update to question: Will I be able to run WSL 2 and other 3rd party virtualization tools such as VMware, or VirtualBox?

### ISSUE THREAD

**Issue by Beguiled** [MicrosoftDocs/WSL#726]
Due to some third-party solutions (VirtualBox, VMWare) now having more support for WSL-2, I would suggest a change to how this section reads.

Instead of
>We are investigating ways to help resolve this issue.

I would suggest

>We are constantly working on solutions to support third-party integration of Hyper-V.

Additionally, the following "Hyper-V's" should be changed to "Hyper-V" (apostrophe s does not apply):
>third-party virtualization providers can use to make their software compatible with Hyper-V's

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks for the suggestions @Beguiled. Implemented: https://github.com/MicrosoftDocs/WSL/commit/57487862d84f5760001a3537878f8d11a7bbcc13
