### ISSUE TITLE
Documentation suggests Windows 10 version 2004 is available

### ISSUE THREAD

**Issue by njbmartin** [MicrosoftDocs/WSL#735]
Looking at the documentation, it's nice to see that WSL2 is no longer limited to Insider Preview and that build 2004 should now available in a Windows Update.

Unfortunately, I'm still on build 1909 and there is no update available as the documentation seems to suggest.

Had a quick google and it seems the general rollout of 2004 may have been paused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by WSLUser** [comment]
You need to install the Update-Assistant, which is available in winget if anybody is using it already. Otherwise wait until MS releases specific patches pertaining to your particular device along with the upgrade.

**Comment by TBBle** [comment]
See https://docs.microsoft.com/en-us/windows/release-information/status-windows-10-2004 for status of known issues that may temporarily block Windows 10 2004 from being offered to specific machines as an update. At this time, there's 7 open "compatibility holds" around various specific drivers.

There's also a link on the page to the [Windows Update Assistant](https://www.microsoft.com/software-download/windows10) which I _think_ will let you bypass the compatibility hold.

I'd suggest no changes are needed.

**Comment by mattwojo** [comment]
Closing as this doesn't appear to require an update to the docs. Thanks for raising the issue and for the 'Known 2004 Update issues" link TBBle!
