### ISSUE TITLE
Cannot convert WSL1 to WSL2 - The operation timed out because a response was not received from the virtual machine or container.

### ISSUE THREAD

**Issue by avinashs24** [MicrosoftDocs/WSL#740]
I am trying to convert WSL1 to WSL2 with the following command. But I am getting the error - **The operation timed out because a response was not received from the virtual machine or container.**
Below is the output from PowerShell,

PS C:\WINDOWS\system32> wsl --set-version Ubuntu-18.04 2 --verbose
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The operation timed out because a response was not received from the virtual machine or container.

**Comment by siordache** [comment]
I get the same error. Any workaround?

**Comment by hajimurtaza** [comment]
@siordache I faced same issue. I deleted the created linux distro and set default wsl version as 2. Then created the linux distro again.

`wsl --unregister <linux distro>`
`wsl --set-default-version 2`
`wsl --import <distro>` or use Microsoft store to install linux distro.

**Comment by siordache** [comment]
@hajimurtaza Thanks, I will try your suggestion.

**Comment by craigloewen-msft** [comment]
Hi @avinashs24 and @siordache , could you please open a Github issue on our [WSL Github repo](https://github.com/microsoft/wsl) for this error? The bug template has all the key info we need to help diagnose and resolve your issue, and many more folks (including myself and the dev team) monitor that repo compared to this one. I'll close this specific issue out as we track only docs related issues on this repo, thank you for filing it! :)
