### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by dragon-archer** [MicrosoftDocs/WSL#742]
The link to the release page of kernel version 4.9.121-microsoft-standard links to version 4.9.104

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 657ce15d-3385-5d58-d836-2d147266e6bd
* Version Independent ID: bab7575b-205e-1700-2d7c-ff14c6cf4797
* Content: [Release Notes for Windows Subsystem for Linux kernel](https://docs.microsoft.com/en-us/windows/wsl/kernel-release-notes)
* Content Source: [WSL/kernel-release-notes.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/kernel-release-notes.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @crloewen
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Fixed here!
https://github.com/MicrosoftDocs/WSL/pull/766

Thank you for filing this.
