### ISSUE TITLE
Help page out of date

### ISSUE THREAD

**Issue by NiklasBr** [MicrosoftDocs/WSL#743]
Help text doesn't work as advertised:

```powershell
PS C:\WINDOWS\System32> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart            
Deployment Image Servicing and Management tool
Version: 10.0.19041.329

Image Version: 10.0.19041.329

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.
PS C:\WINDOWS\System32> wsl --list --verbose
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         1
  UbuntuFocal     Stopped         2
PS C:\WINDOWS\System32> wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
{Application Error}
The exception s (0x
PS C:\WINDOWS\System32> wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
PS C:\WINDOWS\System32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

Path          :
Online        : True
RestartNeeded : False


PS C:\WINDOWS\System32> wsl --list --verbose
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         1
  UbuntuFocal     Stopped         2
PS C:\WINDOWS\System32> wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
PS C:\WINDOWS\System32> wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
{Application Error}
The exception s (0x
PS C:\WINDOWS\System32>

```

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/sv-se/windows/wsl/install-win10#update-to-wsl-2)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Hmm it seems like your error codes are getting improperly truncated. We have a fix incoming for this that may fix this. 

Please follow this thread for news on our fix: https://github.com/microsoft/WSL/issues/5438 
We will post there once we have an update on what build this fix is available in, and I believe it will resolve your error. Could you then please try again and let us know if you're still stuck by filing an issue on the [WSL Github repo](https://github.com/microsoft/WSL)? Thank you! :)
