### ISSUE TITLE
This page is missing 20.04 

### ISSUE THREAD

**Issue by anirugu** [MicrosoftDocs/WSL#744]
[Enter feedback here]

Ubuntu 20.04 has released in april. I think it should also be updated on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Fixed! Thank you for filing this. 

https://github.com/MicrosoftDocs/WSL/commit/e67eb4aedff57a304188ca3360aba25605f8bdb1
