### ISSUE TITLE
Invalid command line option: --set-default-version

### ISSUE THREAD

**Issue by rDunn28** [MicrosoftDocs/WSL#747]
This command in PowerShell does not work;
PS C:\WINDOWS\system32> wsl --set-default-version 2                                                                                                                                                                                          Invalid command line option: --set-default-version

Version 1909 OS Build 18363.900

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Thank you for including the Windows version, to use those commands you need to be on Windows version 19041 or higher! Please try updating your Windows version and then using the commands again. :)
