### ISSUE TITLE
WSL2 not connecting to Internet

### ISSUE THREAD

**Issue by aaemon** [MicrosoftDocs/WSL#748]
I used wsl2 on windows version 19035, but after the update to 19041 I can not connect to the internet, not the sudo apt-get update working, I do not use any VPN. The broadband line is connected to the router, and I am using laptop using wifi. I first thought maybe something wrong in windows so I clean installed windows and the problem still there. I can connect internet in wsl1 but wsl2 not connecting. I tried different distros as well as tried the dns troubleshooting, none solving this issue.
I think there is some issue in the wsl2 config file,

![Screenshot (31)](https://user-images.githubusercontent.com/30506675/84585367-017fba80-ae31-11ea-80aa-b256117b0e33.png)
![Screenshot (32)](https://user-images.githubusercontent.com/30506675/84585369-03e21480-ae31-11ea-8bcb-9c5161f7e7c7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/troubleshooting.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by hajimurtaza** [comment]
Can you post output of `wsl -l -v` in powershell?

**Comment by aaemon** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\ammer> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Stopped         1
  docker-desktop         Stopped         2
  docker-desktop-data    Stopped         2
  Ubuntu-18.04           Stopped         2
PS C:\Users\ammer>


I am using the ubuntu wsl v1 distro as wsl 2 not working. I have used wsl --set-default-version 2 already

**Comment by aaemon** [comment]
clean installed windows again today, somehow wsl2 is working again.
