### ISSUE TITLE
Please provide more examples for every flag

### ISSUE THREAD

**Issue by hajimurtaza** [MicrosoftDocs/WSL#751]
[Enter feedback here]
Please change default memory allocation to 50%. Same like a dual boot environment. 
Also please include more info about the kernel path. Just by passing `C:\\Temp\\myCustomKernel` is not enough.
Also should I restart laptop or wsl service to ensure my `.wslconfig` changes are applied, that information is also missing. 
This WSL 2 is good , please be thorough with docs so people actually want to use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Added in a commit here to help address this!

https://github.com/MicrosoftDocs/WSL/commit/32c46df61e80e5a7e8cc766f0905b9fdb4f0a84e

What more info would you want to see on the kernel path part?

**Comment by hajimurtaza** [comment]
So I am having this discussion on stackoverflow regarding memory allocation to containers. https://stackoverflow.com/q/62405765/7515189

Can you see if this type of flag exists? Can we add it to documentation if it exists?
