### ISSUE TITLE
instructions for setting default user are wrong

### ISSUE THREAD

**Issue by bbulkow** [MicrosoftDocs/WSL#764]
This page states that you can simply execute "distribution_name" then "config --default-user <user>". This is incorrect, because "distribution_name" is not a command. The config subcommand must be under wsl.exe somehow, although I don't see it documented.

This is extraordinearily useful, because without that command, it is very hard to revive a distro that you are reviving through --import.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hey @bbulkow - It looks like we didn't specifically point out in the doc that this command needs to be run in PowerShell. If you run: `ubuntu config --default-user YourName` in PowerShell... substituting "ubuntu" for whichever distro you're targeting and "YourName" for a username that exists in that repo, you should successfully change the default. Please let me know if this isn't the case.
![image](https://user-images.githubusercontent.com/7566797/85346469-54e5ae80-b4aa-11ea-88e8-b6fd4c052d60.png)
