### ISSUE TITLE
Show example on how to bind ASP.NET application to 0.0.0.0

### ISSUE THREAD

**Issue by softveda** [MicrosoftDocs/WSL#770]
To connect from WSL2 to windows the advice is "you may need to bind your application to 0.0.0.0 instead of 127.0.0.1" and an example is provide for Python.
Please provide an example on how to do this for an ASP.NET core application running in windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [An overview on the the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#accessing-network-applications)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This is now resolved, if you use localhost you should be able to connect directly without the need of changing the listening addresses.
