### ISSUE TITLE
Wrong port number in image

### ISSUE THREAD

**Issue by mdunicorn** [MicrosoftDocs/WSL#771]
The [image for the section "Accessing Windows networking apps from Linux"](https://github.com/MicrosoftDocs/WSL/blob/master/WSL/media/wsl2-network-l2w.png) has a small problem. The ports in Windows PowerShell and WSL console do not match. One says 8000 and the other says 5000.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [An overview on the the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Fixed! Had the console outputting the wrong port. :) 

https://github.com/MicrosoftDocs/WSL/commit/f1b049a1276782d4f2754f46a8d2025b598a0784 

Thank you!
