### ISSUE TITLE
localhost doesn't work for servers running in WSL2

### ISSUE THREAD

**Issue by dpaakash** [MicrosoftDocs/WSL#772]
I tried connecting to Kafka server and NodeJS server running in WSL2 via Windows app, but it doesn't seem to work with localhost or 127.0.0.1.
here is a little more detail on the kafka server issue
https://stackoverflow.com/questions/62511091/error-connecting-to-kafka-server-via-ide-in-wsl2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [An overview on the the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by bhanuprakashd** [comment]
I too had same issue on wsl2.Giving same error bootstrap server localhost:9092 disconnected.I tried to change server.properties listeners with IP address and Hostname still no luck.

**Comment by dpaakash** [comment]
> 
> 
> I too had same issue on wsl2.Giving same error bootstrap server localhost:9092 disconnected.I tried to change server.properties listeners with IP address and Hostname still no luck.

This might help for now. But not sure if it's a fix for the issue.
https://stackoverflow.com/questions/61995150/kafka-producer-not-able-to-connect-via-code

**Comment by bhanuprakashd** [comment]
yes. If I run run Logstash on Ubuntu I am able to access localhost:9092. Thanks

**Comment by Debapriya-source** [comment]
To use kafka server in WSL from a app of windows sometimes I faced the same type of issue. I tried disabling IPV6 in WSL2 and it worked for me. Here's how to do it: https://askubuntu.com/questions/958876/how-to-disable-ipv6-on-windows-subsystem-for-linux
