### ISSUE TITLE
wsl2 can use sshfs mount remote server, but the Resource Manager of win10 can't access the folder.

### ISSUE THREAD

**Issue by klusfq** [MicrosoftDocs/WSL#773]
Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

![xxx](https://klusfq.cn/img/life/problem_of_wsl2_issue.png)

Tht alert means like follow:
> <MOUNT_FOLDER> is not accessible. You may not have access to network resources. Please contact the administrator of this server to find out if you have access.
> Try to access an invalid address.

**Comment by klusfq** [comment]
Supplementary explanation: I can access the folder in CLI enviroment such as windows-terminal.

**Comment by craigloewen-msft** [comment]
Any access to your LInux files from file explorer is through your default user. If you don't have access as the default user, then file explorer won't have access. Please consider making sure that your Linux user has access without using sudo (or change your default user to root). Thanks for filing!
