### ISSUE TITLE
Command-line UserVoice portal

### ISSUE THREAD

**Issue by Thell** [MicrosoftDocs/WSL#777]
![image](https://user-images.githubusercontent.com/2185020/85939688-44d03380-b8dd-11ea-97a9-1dde287898fb.png)

As linked from `Provide Feedback` on https://docs.microsoft.com/en-us/windows/wsl/build-custom-distro

**Comment by craigloewen-msft** [comment]
Please see instructions here for filing feature requests for WSL: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#file-an-issue-bug-report-feature-request
