### ISSUE TITLE
Incorrect instructions on how to update wsl password and how to fix it. 

### ISSUE THREAD

**Issue by azdaly** [MicrosoftDocs/WSL#779]
The instruction on how to update the lost password is incorrect. What is currently listed is the following:  
`wsl -u root`  
What SHOULD be typed in is:   
`wsl -u root passwd username`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Create and update user accounts for Linux distributions](https://docs.microsoft.com/en-us/windows/wsl/user-support)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/user-support.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by dimithras** [comment]
Indeed. Just wanted to post this issue, but found yours already present 😏
As there is no such a thing as **wsl password**, I guess the title should be changed to:
###### Incorrect instructions on how to reset forgotten user password in distro
<br>
Article in current state is misleading as by typing `passwd` _without user name_ the password is changed for **root** account in distro.

Changing root password is generally a bad manner in linux, as it breaks the backbone of `sudo`:
> By default, the root account password is locked in Ubuntu. This means that you **cannot login as root directly** or use the `su` command to become the root user. However, since the root account physically exists it is still possible to run programs with root-level privileges. This is where `sudo` comes in – **it allows authorized users to run certain programs as root without having to know the root password**. This means that **in the terminal you should use** `sudo` for commands that require root privileges; simply prepend sudo to all the commands you need to run as root.
[Wiki page](https://help.ubuntu.com/community/RootSudo) for reference

**Comment by craigloewen-msft** [comment]
Fixed! Thank you for spotting this.

https://github.com/MicrosoftDocs/WSL/commit/367639717cbbce99a25478acadb4b2c8bb5e581e
