### ISSUE TITLE
Running Blender on WSL installed ubuntu retrun "unable to open display"

### ISSUE THREAD

**Issue by rohitdavas** [MicrosoftDocs/WSL#780]
[ Thanks for these FAQs. They were helpful. What I am stuck at is, I want to run the blender on ubuntu using WSL, but it seems I am unable to open it. It throws an error " Unable to open display ". 

1.  I tried to install using sudo apt install blender also, but same results.
2. I was trying to run it from the zip file of blender for linux 
3. I tried to install using the snap 

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Oberurseler** [comment]
See:     
 "https://github.com/MicrosoftDocs/WSL/issues/758#issuecomment-646166110"
 for opening the display..

**Comment by craigloewen-msft** [comment]
Seconding @Oberurseler 's comments, please see the attached comment for instructions on getting it working. 

I'll close this issue out as we track only docs issues on this repo, for further technical issues please open a new issue on the [WSL Github Repo](https://github.com/microsoft/wsl). Thank you! :)
