### ISSUE TITLE
--set-default-version not recognized as an argument to wsl

### ISSUE THREAD

**Issue by JaKXz** [MicrosoftDocs/WSL#783]
```
wsl --set-default-version 2
```

is mentioned multiple times in the linked doc, but does not work at time of writing for what I believe to be the latest updates to my system. Please let me know if/how I can provide any more needed information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Ahmad-Al-Ali** [comment]
the correct syntax is "--setdefault 2"

**Comment by shortpoet** [comment]
`wsl --setdefault`

throws an error 
"There is no distribution with the supplied name"

I have follow the docs to the T and deleted and reinstalled 3 times now.  WSL works, but it doens't seem to be WSL 2 no matter how many times and which way I run the update.

**Comment by jonaskuske** [comment]
@shortpoet 
`--set-default` (or `-s`) is not what you're looking for here, it's to specify which distro should be your default distro (that launches if you run `wsl` without specifying one), that's why it wants you to supply a name.

`--set-default-version` should work though, if your Windows version is new enough 🤔

**Comment by JaKXz** [comment]
Yeah - I tried using the windows update assistant tool, but I wasn't able to install the latest updates for some reason. I think the regular Windows Update tool from the control panel (settings) said that my computer is compatible but 🤷

**Comment by jonaskuske** [comment]
If you press `(Windows) + R`, type `winver` and hit Enter it should display both the Windows version and Build number.
To use WSL2 you need Version 2004 (should be Build 19041), so you could check that :)

**Comment by ulziibat-n** [comment]
![image](https://user-images.githubusercontent.com/42606441/88211441-4c8aba00-cc88-11ea-9f8d-0ddf164da7b4.png)

I have problem for update wsl 1 to wsl 2

**Comment by craigloewen-msft** [comment]
This is likely due to your Windows verison, please make sure you are on the latest version and you should have access to this command. Thank you for filing!
