### ISSUE TITLE
Use cases for WSL2

### ISSUE THREAD

**Issue by pisees** [MicrosoftDocs/WSL#784]
Can you clarify the use cases for WSL2?
1. Development
This seem clear with support for WSL2 in Docker Desktop
2. Automation, scripting, CICD
3. Run production workload on Linux containers on Windows
It is not clear whether WSL2 is intended for this, or if instead one should run a Linux container on a Linux VM on Windows Host, or Linux container on Linux Host. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#can-i-run-wsl-2-in-a-virtual-machine)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
WSL 2 is targeted toward developer audiences. We intend for users to use it as part of their inner dev loop, and once they’ve verified the process on their machine they can move their application to a production ready environment like a VM in Azure. An example workflow could be: “Benedict is creating a CI/CD pipeline and wants to test it first on his local machine before deploying it to the cloud. He uses WSL 2 to get an Ubuntu version and verifies that the pipeline behaves correctly in a Linux environment on his machine. HE then pushes that CI/CD pipeline up to the cloud by making it into a Docker container and pushing it to the cloud, where it runs on a production ready Ubuntu VM.”

Does that help answer your question?

**Comment by mattwojo** [comment]
Thanks for asking this question @pisees -- closing this issue, but adding the example Craig describes to our FAQ doc. :) https://github.com/MicrosoftDocs/WSL/pull/804
