### ISSUE TITLE
System has not been booted with systemd as init system (PID 1). Can't operate. Failed to create bus connection: Host is down

### ISSUE THREAD

**Issue by Paxscale** [MicrosoftDocs/WSL#785]
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

**Comment by mattwojo** [comment]
Hi @Paxscale - I'm not quite clear what the issue / request is here. Could you elaborate?

**Comment by dimithras** [comment]
> Hi @Paxscale - I'm not quite clear what the issue / request is here. Could you elaborate?

Running any command referencing linux **systemd** / **init** inside a distribution will result in an error. For example `reboot`:
>C:\Users\Admin>wsl -u root
> root@DESCTOP:/mnt/c/Users/DiMithras# reboot
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> Failed to talk to init daemon

I guess it's not really an issue, as linux distros boot the other way, a **wsl** way using bootstrap.
Details can be seen by `cat /var/log/bootstrap.log`.
