### ISSUE TITLE
Updating Default WSL to WSL 2

### ISSUE THREAD

**Issue by Kylebrown9** [MicrosoftDocs/WSL#788]
When I attempt to update the default version using the provided command, it errors and informs me that the command line argument name used is not valid.

**Provided Command**
```PowerShell
wsl --set-default-version 2
```

**Error Message**
```PowerShell
Invalid command line option: --set-default-version
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10?redirectedfrom=MSDN)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by jkmorais** [comment]
Hi @Kylebrown9 !
See #471

**Comment by licanhua** [comment]
type `wsl --help`, if you can't see `--set-default-version`, that mean you OS doesn't support it. 
You have to update to [version 2004, Build 19041 or higher](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2)

**Comment by mattwojo** [comment]
Thanks @licanhua. Adding this note to the docs. 
@Kylebrown9 - closing this issue, but please reply if you have further questions or if Canhua's solution doesn't resolve your issue.

**Comment by mattwojo** [comment]
Note added: https://github.com/MicrosoftDocs/WSL/commit/be5ca217e588c1f5a50a1031b878180f62535f19

**Comment by angelotrivelli** [comment]
As of today, [the docs that @licanhua linked](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2) shows ...

> To update to WSL 2, you must meet the following criteria:
> 
> Running Windows 10, updated to **version 1903 or higher, Build 18362** or higher.
> 
> Check your Windows version by selecting the Windows logo key + R, type winver, select OK. (Or enter the ver command in Windows Command Prompt). Please update to the latest Windows version if your build is lower than 18361. Get Windows Update Assistant.

My version+build is 1909 + 18363, and I get the same error as the OP when entering "`wsl --set-default-version 2`"

Are the docs wrong? Where did you guys find that version + build must be at least "2004, build 19041" ?

**Comment by licanhua** [comment]
[WSL 2 Support is coming to Windows 10 Versions 1903 and 1909](https://devblogs.microsoft.com/commandline/wsl-2-support-is-coming-to-windows-10-versions-1903-and-1909/).
In your case, the supported number is 18363.1049, so please check Windows Update to see you can update to that version.
You can follow link https://support.microsoft.com/en-us/help/4566116 to update it.
I guess the download link to manually install it is: http://www.catalog.update.microsoft.com/Search.aspx?q=KB4566116

**Comment by mmasmoudi** [comment]
i have the same error : invalid command line option.
i'm running windows 1903, build 18363.30.
