### ISSUE TITLE
Small typo under the 'Increased File IO Performance' section

### ISSUE THREAD

**Issue by jch8ri** [MicrosoftDocs/WSL#791]
"File intensive operations like git clone, npm install, apt update, apt upgrade, and more are all *be* noticeably faster with WSL 2."

Prolly don't need the 'be' unless you're going for that nyc slang documentation - it do be like that doe!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [An overview on the the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#feedback)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
LoL. It do be like that, but we'll keep the NYC slang to our Teams chat. Thansk @jch8ri. Updated commit f5043c0
