### ISSUE TITLE
Add bcdedit's hypervisorlaunchtype as a point under "Troubleshooting Installation"

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [MicrosoftDocs/WSL#793]
I would recommend adding [this ](https://github.com/microsoft/WSL/issues/4930#issuecomment-591483194)to the section [Troubleshooting Installation](https://docs.microsoft.com/en-us/windows/wsl/install-win10#troubleshooting-installation), as quite a bit of time may pass between people disabling Hyper-V like this and them wanting to use WSL2 and they may have forgotten that they did that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
We've added that here:
https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed

Thank you for the contribution!
