### ISSUE TITLE
Yeah I tried WSL2 before and hyper-v made my system unstable.

### ISSUE THREAD

**Issue by eliotmoss** [MicrosoftDocs/WSL#795]
Yeah I tried WSL2 before and hyper-v made my system unstable.

I heard WSL2 didn't need hyper-v anymore and now so tried again but got stuck and now I'm this position. Hyper -v wasn't installed but VMware can no longer run because of something else.

I created a system restore point before setting up but restoring doesn't change anything.

I reversed what I did `dism.exe /online /disable-feature /featurename:VirtualMachinePlatform /all /norestart`
And restarted and still no effect.

I really hate that some feature prevents me from running applications and can't be undone without re-installing windows.

_Originally posted by @b-hayes in https://github.com/MicrosoftDocs/WSL/issues/590#issuecomment-658083346_

**Comment by eliotmoss** [comment]
Sorry I didn't mean to close the issue.  See the previous thread for my recollection of how I solved it recently.

**Comment by b-hayes** [comment]
Think my problem was that I didn't have the feature update 2004. This is why I stopped halfway. I spend the next 2 hours making sure I had it via windows update.

Then I ran:
`dism.exe /online /disable-feature /featurename:VirtualMachinePlatform /norestart`

Again and then disabled the credential guard:
Press Windows Key + R to open Run.
Type gpedit.msc and click OK. This will open the Group Policy Editor.
In the Group Policy Editor, navigate to the following location:
 Computer Configuration -> Administrative Templates -> System -> Device Guard
Select Device Guard.
On the right pane, double-click the “Turn on Virtualization Based Security” policy.

After a final rebooting I was able to run VMware again.

**Comment by eliotmoss** [comment]
Ah, yes, thar was another thing :-)  ... although I turned it _off_ as I recall.

**Comment by craigloewen-msft** [comment]
There's been a lot of improvements to Hyper-V and WSL since then please reopen this at the WSL Github repo if you're seeing issues. Thank you for filing!

Instructions to open a technical issue for WSL are here: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#file-an-issue-bug-report-feature-request

**Comment by eliotmoss** [comment]
AFAIK WSL2 is still essentially incompatible with VirtualBox because they virtualize in "opposite" ways.  VirtualBox claims to be able to run on a Windows system sets for WSL2's style of virtualization, but at possibly reduce performance.  I that running VirtualBox under those conditions was actually dangerous in the sense that it could results is BSOD (or I guess these days, GSOD).  I really need to be able to run VirtualBox well, so for now I'm locked out of WSL2 and run WSL1.  I don't get the impression that either vendor is committed to doing away with this conflict in approaches to virtualization ...
