### ISSUE TITLE
Can I run WSL 2 in a virtual machine?

### ISSUE THREAD

**Issue by AntonioPeixoto** [MicrosoftDocs/WSL#796]
I follow the orientation to enable nested virtualization:

> Set-VMProcessor -VMName <VMName> -ExposeVirtualizationExtensions $true
I put: 
  Set-VMProcessor -VMName "D:\VirtualBox\CentOS-6.9-x86_64\CentOS-6.9-x86_64.vbox" -ExposeVirtualizationExtensions $true

But I got an error:

> Set-VMProcessor : O Hyper-V não pôde localizar uma máquina virtual com o nome
"D:\VirtualBox\CentOS-6.9-x86_64\CentOS-6.9-x86_64.vbox".
No linha:1 caractere:1
+ Set-VMProcessor -VMName "D:\VirtualBox\CentOS-6.9-x86_64\CentOS-6.9-x ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Set-VMProcessor], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.SetVMProcessor 

Can somwone help me.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
The option is VMName not VM file path. Add a VM with that CentOS VHD or VHDX file. Then use that registered VM name with the powershell command.

**Comment by AntonioPeixoto** [comment]
Thanks for your attention,

Antonio Peixoto,
(91)99103-8438


Em qua., 15 de jul. de 2020 às 01:22, Biswapriyo Nath <
notifications@github.com> escreveu:

**Comment by 8secz-johndpope** [comment]
N.B.  if anyone arrives here from google - 
and you run this command and get Command not found
_Set-VMProcessor -VMName -ExposeVirtualizationExtensions $true_

you have to enable HyperV first - 
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

_Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All_

**Comment by Biswa96** [comment]
If you're using a VM,  why not use a GNU/Linux distrbution in that VM?

**Comment by craigloewen-msft** [comment]
Please see this troubleshooting step for instructions on how to run WSL 2 distros in a VM:
https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed
