### ISSUE TITLE
WSL setting default version is an invalid command

### ISSUE THREAD

**Issue by KevinBurton** [MicrosoftDocs/WSL#800]
[Enter feedback here]

`wsl --set-default-version 2` is not valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hi @KevinBurton - This is a valid command, but there are a few requirements for it to work on changing the default WSL version used when installing a new distro:

- you need to enter the command using PowerShell (or Windows Command Prompt)... not a wsl distro
- you need to be running Windows 10, updated to version 2004, Build 19041 or higher
- you need to have enabled the "Virtual Machine Platform" optional feature
- you need to have restarted your machine after enabling WSL 2

I'm closing this issue as it doesn't require an update to the docs (as far as I can tell)... but please check that you've met those criteria and let us know if you still are having trouble.

~Matt
