### ISSUE TITLE
Remote-WSL extension location changed

### ISSUE THREAD

**Issue by marckassay** [MicrosoftDocs/WSL#801]
The extension location seems to no longer be where it is mentioned in this doc:

> In order to install the Remote-WSL extension, you will need the 1.35 May release version or later of VS Code. We do not recommend using WSL in VS Code without the Remote-WSL extension as you will lose support for auto-complete, debugging, linting, etc. Fun fact: this WSL extension is installed in $HOME/.vscode-server/extensions.

But it is at the following:
```
~\source\repos\acme > ls $HOME\.vscode\extensions\


    Directory: C:\Users\marckassay\.vscode\extensions

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         7/18/2020 10:28 AM                ms-azuretools.vscode-docker-1.3.1
d-----         7/17/2020  1:43 PM                ms-python.python-2020.7.94776
d-----         7/18/2020  2:45 PM                ms-vscode-remote.remote-containers-0.128.0
d-----         7/18/2020  2:45 PM                ms-vscode-remote.remote-ssh-0.51.0
d-----         7/18/2020  2:45 PM                ms-vscode-remote.remote-ssh-edit-0.51.0
d-----         7/18/2020  2:45 PM                ms-vscode-remote.remote-wsl-0.44.4
d-----         7/18/2020  2:45 PM                ms-vscode-remote.vscode-remote-extensionpack-0.20.0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 782a4458-6a56-63e5-efaf-d1868762ed06
* Version Independent ID: 312f71d9-db7d-52a5-b03d-9b6d4c680c2a
* Content: [Get started using VS Code with Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode)
* Content Source: [WSL/tutorials/wsl-vscode.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-vscode.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @marckassay! Making this update now. :)

**Comment by mattwojo** [comment]
Updated: commit 5de87af
