### ISSUE TITLE
no need to use grep in iproute2

### ISSUE THREAD

**Issue by rchildre3** [MicrosoftDocs/WSL#803]
instead of `ip addr | grep eth0` just use `ip address show dev eth0` to:
* Prevent the "if grep is installed" clause
* Use the full form `address` over `addr` to prevent confusion among Linux newcomers

It would need regenerating the associated image on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [An overview on the the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This picture has been removed from this page, and we assume that users have basic Linux tools like grep installed (or can easily install them). Thank you for the suggestion! :)
