### ISSUE TITLE
Problems with installation of WSL 2 on Ubuntu 20.04

### ISSUE THREAD

**Issue by Godofnothing** [MicrosoftDocs/WSL#816]
I am trying to update the existing subsystem Ubuntu 20.04 on WSL1 to WSL2. However, after running  

`wsl.exe --set-version Ubuntu-20.04 2`

The power shell writes - wait. It may take a several minutes. But after short time my laptop stops responding to anything, and I have to turn off the laptop by force. I have made a several attempts. What can be the reason for such a behaviour, and what measures can be done? I would strongly appreciate any response!

**Comment by craigloewen-msft** [comment]
What is the size of your distribution? How many GBs of space are your Linux files inside of it? 

We have also made some changes to this behaviour to help limit memory usage so I'd urge you to try this command again and if you run into technical issues please file them at https://github.com/microsoft/wsl as this repo is just for the docs. Thank you!
