### ISSUE TITLE
this doc could include 'how to uninstall wsl 1 after installing wsl 2'

### ISSUE THREAD

**Issue by bnegrao** [MicrosoftDocs/WSL#819]
I followed the instructions to upgrade to wsl 2. But as I understood, wsl 1 is still here and I don't need it anymore.
If that's the case, I wan't to uninstall wls 1 completely. If this is not the case the document could have a note telling that wsl1 cannot be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Updating the WSL 2 Linux kernel](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
If you'd like to uninstall WSL 1 you can now use the Store preview version of WSL at https://aka.ms/wslstorepage , we'll update the docs once that Store app goes out of preview and I will add a note for this then. I'll close this issue out as I believe the core issue is solved, thank you for filing!

**Comment by StephaneMM** [comment]
@craigloewen-msft What if we/I do not have a W11 22000.0 or higher version to be able to use this app ? I am stuck as well

**Comment by Biswa96** [comment]
The Store preview version of WSL is not mandatory. You can keep using system provided WSL.
