### ISSUE TITLE
`Git Credential Manager setup` section should indicate for HTTPS only

### ISSUE THREAD

**Issue by GoFightNguyen** [MicrosoftDocs/WSL#821]
The section `Git Credential Manager setup` should indicate that it only works for HTTPS, and not SSH.
Since it mentions SSH, I assumed it would work for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31aade8d-62a2-6d91-b0bd-3bc5880042f8
* Version Independent ID: 12e275fa-8010-5e5a-af8c-120f11ab0932
* Content: [Get started using Git on Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git)
* Content Source: [WSL/tutorials/wsl-git.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-git.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @GoFightNguyen - finally added some Git Credential Manager updates, including the SSH differentiation.
https://github.com/MicrosoftDocs/WSL/pull/1474
