### ISSUE TITLE
Reboot needed after DSIM commands

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/WSL#822]
After running
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
and
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
a reboot is then needed before one can run
wsl --set-default-version 2

then came confusion - i downloaded Debian and then was prompted to install new kernel.
did that from  https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi
then when i restarted debian it went into setup

does the kernel updated need to be done before or after trying to install the dsitro

this isn't clear on this page i am bugging or on this page https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

no wonder people say they have hard time installing....
maybe test your docs on fresh installs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by dimithras** [comment]
It's stated [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10):
> To only install WSL 1, you should now restart your machine and move on to Install your Linux distribution of choice, otherwise wait to restart and move on to update to WSL 2. Read more about Comparing WSL 2 and WSL 1.

and

> Restart your machine to complete the WSL install and update to WSL 2.

**Comment by craigloewen-msft** [comment]
We've improved this with the command `wsl --install` to automate this process. Thank you for the feedback!
