### ISSUE TITLE
Obsolete info on max RAM usage

### ISSUE THREAD

**Issue by arencambre** [MicrosoftDocs/WSL#827]
The table at bottom says the default value for the **memory** setting is "80% of your total memory on Windows".  That contradicts https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20175, which says it is "50% of host memory or 8GB, whichever is less". 50% is also mentioned in #4166.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Great call out! I added a note to call out that this could be different in Windows Insiders builds

**Comment by blackliner** [comment]
Hi, for me this change is a problem. I need 80% of host memory inside WSL2, now its only 8Gb (instead of 24Gb). I want the old defaults back.
