### ISSUE TITLE
WSL Installation Guide for Windows 10

### ISSUE THREAD

**Issue by johne53** [MicrosoftDocs/WSL#828]
It might be worth mentioning that setting up WSL and installing Linux doesn't seem possible if you're running Win10 on Mac hardware and dual booting. Basically, it requires Virtualisation to be enabled (in the BIOS) but Macs don't seem to give access to the BIOS. If I'm wrong about that, do please let me know:- john@creativepost.co.uk

Thanks, John Emmas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
There seems to be instructions online on how to set up a Mac with dual booting and virtualization enabled. For example I found [this article](https://dea.nbird.com.au/2017/02/24/enabling-vt-x-on-mac-book-air-in-bootcamp/).

**Comment by johne53** [comment]
Wow, what a great find!  I've just woken up so still a bit bleary eyed - but I'll definitely give that a try later today... thanks!!

**Comment by johne53** [comment]
I've just managed to fix the problem with Virtualisation and I can now run Debian from within Windows 10 (I've only tried the bash shell, so far. but it seems to be working..)

But when I launch VS2019 it still only shows me my previous compilers (MSVC and Clang). So presumably I need to install a compiler for Debian somehow?? Are there any instructions for this anywhere?

**Comment by emanueol** [comment]
I have updated windows 10 to build 2015, enabled WSL2, downloaded ubunto from microsoft store, and been happily coding with vs code.

Regarding updates..
1. is WSL2 windows being automatically updated by windows 10 or do i need to manually do something ?
2. same for ubunto ms store wsl2 image, do i manually check and update it myself while logged in shell or is there some other way ?
thanks, to point me out some reference answering these basic wonders of mine, thanks.

**Comment by johne53** [comment]
> I have updated windows 10 to build 2015, enabled WSL2, downloaded ubunto from microsoft store, and been happily coding with vs code.
> 

How did you install the Linux compiler? In the past I've  installed new compilers from within Visual Studio itself  (**Tools->Get Tools and Features** ). 

But when I do that after installing WSL2 and Debian Linux (from Microsoft) it only shows me the compilers I already knew about - I'm not seeing any new options that'd let me build Linux apps. What am I doing wrong?

**Comment by emanueol** [comment]
> > I have updated windows 10 to build 2015, enabled WSL2, downloaded ubunto from microsoft store, and been happily coding with vs code.
> 
> How did you install the Linux compiler? In the past I've installed new compilers from within Visual Studio itself (**Tools->Get Tools and Features** ).
> 
> But when I do that after installing WSL2 and Debian Linux (from Microsoft) it only shows me the compilers I already knew about - I'm not seeing any new options that'd let me build Linux apps. What am I doing wrong?

What compiler ? the "C" compiler ? used to compile kernel etc or something else ?
Anyway i been updating Ubunto via shell with simple:
--update ubunto repositories info only!! It doesnt download or update anything.
$ sudo apt update
78 packages can br upgraed.

--to list the 78 packages that can be upgraded
$ apt list –upgradable

--upgrade all packages
$ sudo apt upgrade

--check and update - 2 in 1
$ sudo apt update && sudo apt upgrade -y

--to cleanup/remove packages no longer needed
$ sudo apt autoremove

**Comment by johne53** [comment]
Sorry **emanueol** - I just realised you're building with VS Code, rather than Visual Studio itself.

Maybe I've misunderstood something.... my understanding was that after following [the instructions here](https://docs.microsoft.com/en-us/windows/wsl/install-win10) I'd be able make Visual Studio C/C++ projects compile and build for Linux (in addition to their normal Windows targets).

But before doing that, I'd presumably need to make Visual Studio aware that WSL2 and Linux are now installed and available. That's the bit I don't understand...

1) I've followed the above instructions.
2) Linux (e.g. a Debian bash shell) can be launched from within Windows 10.
3) But Visual Studio doesn't behave any differently (it doesn't seem to know that WSL2 and Debian are now available).

**Comment by craigloewen-msft** [comment]
Closing out this issue as we talk about nested virtualization here: 
https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed

Thank you for filing this!
