### ISSUE TITLE
add alpine to manual download list

### ISSUE THREAD

**Issue by pohart** [MicrosoftDocs/WSL#829]
I would like to manually download alpine wls, but that shows up only in the store, not in the manual download list in this article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distros)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
The [Alpine WSL][1] in Windows Store is not provided from official Alpine creators. All the manual downloads are provided from official sources. If you want to download a compressed tarball (.tar.gz) file of Alpine rootfs you can get it from here https://alpinelinux.org/downloads/, see the _mini root filesystem_ section. Or you can download it using `docker pull alpine` and create a tarball using `docker save` command (I think Craig L. has a video about this).

[1]: https://www.microsoft.com/en-us/p/alpine-wsl/9p804crf0395

**Comment by dimithras** [comment]
Alpine is a commercial product, which means either buy it in MS Store or with the link provided by @Biswa96 
Otherwise it's piracy.

**Comment by scresante** [comment]
@dimithras  that is incorrect. per their [website](https://alpinelinux.org/about/):
> Alpine Linux is an independent, non-commercial, general purpose Linux distribution designed for power users who appreciate security, simplicity and resource efficiency.

It's worth noting that the source code for the product available in the MS Store is [available on github](https://github.com/agowa338/WSL-DistroLauncher-Alpine).

**Comment by craigloewen-msft** [comment]
The decision to provide us at Microsoft with an Alpine Linux distro for offline hosting is up to the Alpine team. Please file this as a request to the Alpine Linux team! Thank you!
