### ISSUE TITLE
I am sick and tired of having to type exe.  Can I run windows commands in bash without .exe?

### ISSUE THREAD

**Issue by seantshen** [MicrosoftDocs/WSL#832]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea49528-e5c5-4f64-841e-9fe036de304e
* Version Independent ID: edeb7cb5-afcf-1410-4966-f48ce5f6a19a
* Content: [Windows interoperability with Linux](https://docs.microsoft.com/en-us/windows/wsl/interop)
* Content Source: [WSL/interop.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/interop.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Yes you can just type in `wsl` and it will recognize it! 

Or you can also use Windows Terminal which has nice profiles that you can set up so you don't have to type at all. :)

![image](https://user-images.githubusercontent.com/42221804/90272082-b292d900-de11-11ea-8114-d3f95084aaa7.png)

**Comment by Biswa96** [comment]
OP means running like notepad.exe in WSL i.e. the binfmt thing.

**Comment by craigloewen-msft** [comment]
GOt it! For that I'd just create aliases myself :)
