### ISSUE TITLE
Spelling mistake on documentation page

### ISSUE THREAD

**Issue by BlueJay113** [MicrosoftDocs/WSL#837]
[https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel#this-update-only-applies-to-machines-with-the-windows-subsystem-for-linux](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel#this-update-only-applies-to-machines-with-the-windows-subsystem-for-linux)

> To install MSI kernel, WSL is required and should be enabled first. If it fails, it you will see the message: This update only applies to machines with the Windows ***Subsytem*** for Linux.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Updating the WSL 2 Linux kernel](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Fixed! Thanks for the spot. 
https://github.com/MicrosoftDocs/WSL/commit/ed7fbda8e5b76108d797de4a739e27c53661a65d
