### ISSUE TITLE
Uninstalling a distro

### ISSUE THREAD

**Issue by johne53** [MicrosoftDocs/WSL#839]
WSL is currently offering around 12 x distros - so let's say I installed Debian but now I want to try one of the others... is it possible to uninstall Debian??

I can't find it in Control Panel (i.e. under **Add/Remove Programs**) so how would I go about removing it??

**Comment by johne53** [comment]
A bit more info....

1. AFAICT Debian installed itself into a top-level folder called **C:\Program Files\WindowsApps**

2. Almost nothing has any modification rights to that folder - even Administrators are only allowed to list the folder contents!!

3. **TrustedInstaller** and **System** are the only items with full control

This implies that I can only remove Debian via **Add/Remove Programs** or some other installer.  But there's no entry in **Add/Remove Programs**. So where do I find the uninstaller??

**Comment by johne53** [comment]
Sorry for posting twice - I just added this to another thread and then realised it was closed (so I don't know if it'll get a reply). Anyway... here's what I posted: after reading the following-

> There are two ways to uninstall a distro:
> 
> * If you downloaded it from the store, right click on the icon in your start menu (or search bar) and click 'Uninstall'.
> * You can also run `wsl --unregister <distroName>` to uninstall a distro which will remove those files for you.
> 


In my case I'm not seeing 'Uninstall' (in the 1st example) so I'd need the 2nd method - and I'm assuming that the line would need to get run form a Windows Command Prompt?

So I tried running it here to uninstall Ubuntu:-

- wsl --unregister ubuntu 

but it gives me this error:-  **There is no distribution with the supplied name**

I've tried upper case / lower case / capitalized etc but I see the same error each time. So how do I find the correct name to use? (presumably it's a bit more complicated than just **ubuntu** ??)

**Comment by dimithras** [comment]
**Ubuntu** is a generic name, when trying to unregister distro, one should specify **full name**.

To get a list of all current distributions type `wsl -l -q` in either **cmd** or **PowerShell**. In my case the output is:
- Debian
- Ubuntu-20.04

</br>

As you can see it's not just _Ubuntu_, but _Ubuntu_**-20.04**. You may have some other version. Now copy and paste this name to unregister:
> C:\Users\Admin>wsl --unregister **Ubuntu-20.04**
> Unregistering...

If the output is **Unregistering...** it should be a success!

**Comment by craigloewen-msft** [comment]
Added docs here:
https://docs.microsoft.com/en-us/windows/wsl/basic-commands#unregister-or-uninstall-a-linux-distribution

Thank you for filing this!
