### ISSUE TITLE
Add Hash for Integrity Check of the WSL 2 Linux kernel update

### ISSUE THREAD

**Issue by udubnate** [MicrosoftDocs/WSL#840]
Hi Craig/WSL Support

Would request if you could add a SHA256 hash of the update on the page, then I can add a script to download and check integrity of the file from the website.

Thank you!

Nate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Updating the WSL 2 Linux kernel](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
We have a command line option for you to use that might help solve your problem if you're looking to script this: `wsl --update` will download and install the latest Linux kernel update. Does that help solve your issue?

**Comment by udubnate** [comment]
yeah that should work - didn't realize it was already scripted. thanks!

**Comment by udubnate** [comment]
couldn't get the command to run in 2004
'''
PS C:\git\dev-workstation> wsl --update
Invalid command line option: --update
'''

any ideas?
