### ISSUE TITLE
the separate package for amd64 didn't work. the regular one did.

### ISSUE THREAD

**Issue by bizframe** [MicrosoftDocs/WSL#841]
i am on a AMD athlon II x3 440 CPU and "wsl_update_arm64.exe" says "installation is not supported for this processor type." So i installed the regular package...and it worked. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Updating the WSL 2 Linux kernel](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
I'd double check if your configuration is using ARM, glad to see it worked, if you see this issue again please file it at http://github.com/microsoft/wsl 

Thank you!
