### ISSUE TITLE
Please include a link to the ARM version

### ISSUE THREAD

**Issue by kwe** [MicrosoftDocs/WSL#842]
[Enter feedback here]
it's https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_arm64.msi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Updating the WSL 2 Linux kernel](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
There is a link, for it, is it just unclear that it's in the "Note" section?

![image](https://user-images.githubusercontent.com/42221804/90442451-87b5b880-e08f-11ea-9a38-40e09348d747.png)

**Comment by kwe** [comment]
Missed this with my browser/font settings. Thanks for the clarification.
