### ISSUE TITLE
wsl Error: 0x1bc

### ISSUE THREAD

**Issue by Yozora21** [MicrosoftDocs/WSL#843]
I followed the instuctions to update to wsl 2 but i cant. first the kranel for linux is installed but it appears as not, also i tried to re install the kranel but it say that is not compatible

C:\WINDOWS\system32>wsl --set-version Ubuntu-20.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel

PS C:\WINDOWS\system32> wsl --set-default-version 2
Error: 0x1bc
For information on key differences with WSL 2 please visit https://aka.ms/wsl2

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

**Comment by FUTC-Coding** [comment]
I'm having the same problem when running `wsl --set-default-version 2`

**Comment by FUTC-Coding** [comment]
I think I fixed it, download the latest wsl2 kernel from [here](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel) and install the .msi and it should work.
