### ISSUE TITLE
wsl2 issues System has not been booted with systemd as init system (PID 1). Can't operate. Failed to create bus connection: Host is down System has not been booted with systemd as init system (PID 1). Can't operate. Failed to create bus connection: Host is down 

### ISSUE THREAD

**Issue by 14kaitou** [MicrosoftDocs/WSL#845]
when I try to run` gufw `
I run the command inside a remote desktop via xrdp and it gives me this error 

```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
/usr/bin/gufw: line 2: [: =: unary operator expected
Error getting authority: Error initializing authority: Could not connect: No such file or directory

```
I know why but.
I really want to run the full Linux environment on wsl2 is there any suggestion to solve the problem above?

**Comment by craigloewen-msft** [comment]
This isn't yet supported as WSL doesn't yet have systemd support. There are some community projects that are investigating closing this gap like this one: https://github.com/arkane-systems/genie

Thank you for filing!
