### ISSUE TITLE
sharing external resources

### ISSUE THREAD

**Issue by umsaenga** [MicrosoftDocs/WSL#849]
Hello, installed WSL and Debian on Windows 10. Now trying to run a program that requires the use of a usb microphone.
However debian does not recognize the microphone. How can I share the resource with debian wsl?
cheers

**Comment by mattwojo** [comment]
Unfortunately, it looks like using a USB microphone with WSL is still currently unsupported. Closing this issue -- please follow / comment on the product development repo issues -- there are two currently open relating to this same question:
https://github.com/microsoft/WSL/issues/5158
and 
https://github.com/microsoft/WSL/issues/2195

**Comment by therealkenc** [comment]
> USB microphone with WSL

You want #5816
