### ISSUE TITLE
Incorrect version requirement to update from wsl 1 to wsl 2

### ISSUE THREAD

**Issue by rickardlindahl** [MicrosoftDocs/WSL#850]
> To update to WSL 2, you must meet the following criteria:
> Running Windows 10, updated to version 1903 or higher, Build 18362 or higher.

This is inaccurate. I have Version 1909, Build 18363.904 but the argument to set default version does not exist.
I think I read somewhere else that version 2004 is needed. This page should be updated with the correct information.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by holger-waldmann** [comment]
I found a solution for 1903 and 1909:
Look here #863

**Comment by craigloewen-msft** [comment]
You'll need to make sure you have the backport, I've updated the docs to give more info regarding this!

https://github.com/MicrosoftDocs/WSL/commit/05d04f851ca3eefbc9f83e462a7792fd61f1ae1e

Thank you @holger-waldmann for cross linking. :)

**Comment by craigloewen-msft** [comment]
@adegeo I also updated the FAQ, thank you for the heads up.

https://github.com/MicrosoftDocs/WSL/commit/910845e9b3f980b2c5b9b4968331a706720603c6
