### ISSUE TITLE
WSL 2 and serial port access - any updates

### ISSUE THREAD

**Issue by d-c-d** [MicrosoftDocs/WSL#853]
[Enter feedback here]

Well - it's almost 2 months since the last update - I would be grateful to here more about the timeline for serial port access from wsl 2.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#can-i-access-the-gpu-in-wsl-2-are-there-plans-to-increase-hardware-support)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This is being tracked here:
https://github.com/microsoft/WSL/issues/4322
