### ISSUE TITLE
Needs to specify .exe extension to start VS Code from Ubuntu with WSL 2

### ISSUE THREAD

**Issue by nbros** [MicrosoftDocs/WSL#855]
The [Get started using VS Code with Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode#feedback) documentation says to enter `code .` to open a WSL folder in Visual Studio Code.

But with the latest Ubuntu distribution at least it does not work:

```
user:~$ code .

Command 'code' not found, did you mean:

  command 'cdde' from deb cdde (0.3.1-1build1)
  command 'ode' from deb plotutils (2.6-10build1)
  command 'tcode' from deb emboss (6.6.0+dfsg-7ubuntu2)
  command 'node' from deb nodejs (10.19.0~dfsg-3ubuntu1)
  command 'cde' from deb cde (0.1+git9-g551e54d-1.1build1)

Try: sudo apt install <deb name>
```

What works is:
```code.exe .```

Could you indicate this in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 782a4458-6a56-63e5-efaf-d1868762ed06
* Version Independent ID: 312f71d9-db7d-52a5-b03d-9b6d4c680c2a
* Content: [Get started using VS Code with Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode#feedback)
* Content Source: [WSL/tutorials/wsl-vscode.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-vscode.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
You can do this just by running `code` it is likely that this has been fixed in the latest version.
<img width="504" alt="image" src="https://user-images.githubusercontent.com/42221804/154574857-5a7daec4-2ae2-40f0-aad0-c99eea894e17.png">


Thank you for filing this!
