### ISSUE TITLE
Add workaround for Error 0x1bc when setting wsl 2 version

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/WSL#857]
After running
> wsl --set-default-version 2

I see following output:
> Error: 0x1bc
> For information on key differences with WSL 2 please visit https://aka.ms/wsl2

Workaround to solve the error:

Follow these existing instructions:
>Please follow the link (https://aka.ms/wsl2kernel) and install the MSI from that page on our documentation to install a Linux kernel on your machine for WSL 2 to use
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by vanillamice** [comment]
Same issue here
