### ISSUE TITLE
Version 1903 or 2004?

### ISSUE THREAD

**Issue by bclrk** [MicrosoftDocs/WSL#858]
The note under the [Set WSL 2 as your default version](https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-wsl-2-as-your-default-version) section, is "version 2004, Build 19041 or higher" correct or do you mean version 1903 or higher, Build 18362 or higher?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Fixed! Thank you for filing this! 👍 

https://github.com/MicrosoftDocs/WSL/commit/499d16bdc531a652721e72aafdb4d45a460778b9
