### ISSUE TITLE
ws1 has "--setdefault", not "--set-default-version" - is there a better option than 2004

### ISSUE THREAD

**Issue by jkwilborn** [MicrosoftDocs/WSL#859]
Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

**Comment by jkwilborn** [comment]
I have installed the 1903 (OS Build 18362.1016).  After the restart, the command `wsl --set-default-version 2` gives me the available options,   The closest I can come is `-setdefault, -s <DistributionName>` which sounds like what you want.  However there is no 'DistributionName' that seems acceptable to the software.  I also noticed that there are NO options that are hyphenated.  Seems to me, sometimes python chokes on hyphenated things..., maybe???  I found where it stated that if that command failed I should upgrade to 2004.  Reading the installation and other information about it, there seems to be many bugs and one of the [Microsoft independent advisors](https://answers.microsoft.com/en-us/windows/forum/all/windows-10-update-from-1903-to-2004/fcdb44bd-39ee-470c-9a8e-c8973e86e5d5) recommends to give it a few months, that was July, 2020. I'm having enough problems with stability...  I don't see a way for the wsl software to give me a version...?  It also indicates a 32 bit window.  Any suggestions?  Thanks for your time.  Here is a copy of the output:

C:\Windows\system32>wsl --set-default-version 2
Invalid command line option: --set-default-version
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments to run Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.
    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.
    --
        Pass the remaining command line as is.
Options:
    --distribution, -d <DistributionName>
        Run the specified distribution.
    --user, -u <UserName>
        Run as the specified user.
Arguments to manage Windows Subsystem for Linux:

    --export <DistributionName> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.
    --import <DistributionName> <InstallLocation> <FileName>
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.
    --list, -l [Options]
        Lists distributions.
        Options:
            --all
                List all distributions, including distributions that are currently
                being installed or uninstalled.
            --running
                List only distributions that are currently running.
    -setdefault, -s <DistributionName>
        Sets the distribution as the default.
    --terminate, -t <DistributionName>
        Terminates the distribution.
    --unregister <DistributionName>
        Unregisters the distribution.
    --upgrade <DistributionName>
        Upgrades the distribution to the WslFs file system format.
    --help
        Display usage information.
C:\Windows\system32>

Sorry about the format, tried to enter it as 'code' but it took out all the formatting.  Again, thanks for the help.

**Comment by holger-waldmann** [comment]
I found a solution for 1903 and 1909:
Look here #863

**Comment by craigloewen-msft** [comment]
You'll need to make sure you have the backport, I've updated the docs to give more info regarding this!

https://github.com/MicrosoftDocs/WSL/commit/05d04f851ca3eefbc9f83e462a7792fd61f1ae1e

Thank you @holger-waldmann for cross linking. :)
