### ISSUE TITLE
Global config file mentioned, so local also possible?

### ISSUE THREAD

**Issue by KoenDG** [MicrosoftDocs/WSL#861]
The page describes:

"You can configure global WSL options by placing a .wslconfig file into ..."

It specifically mentions a "global" options file. The mere mention of this makes me wonder if there's a per-VM possiblity?

If not, clarification would be a good idea, to avoid misunderstandings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
> The mere mention of this makes me wonder if there's a per-VM possiblity?

Yes. It's `/etc/wsl.conf`.

**Comment by KoenDG** [comment]
`/etc` on a Windows machine?

I was thinking of a scenario where I move the VHDX to another disk, like described here: https://github.com/MicrosoftDocs/WSL/issues/412

So, I can put it on an external SSD, for instance. At which point, I'd want to still set a config file specifically for that disk/distribution only.

Sorry if that wasn't clear, that's my question basically, in considering this scenario.

**Comment by Biswa96** [comment]
>  I'd want to still set a config file specifically for that disk/distribution only.

That's how `/etc/wsl.conf` works. You basically put it in a specific distribution as you want and it will be in the VHDX file. Also paths with `/` are for Unix and Unix-like system e.g. here it's the GNU/Linux distribution.

**Comment by KoenDG** [comment]
I had a bit of a look around and it turns out that `/etc/wsl.conf` is actually inside the running VM, which is then to be restarted for them to take effect.

I was going on the assumption that any such configs are to be made with the VM shut down, somewhere on the windows host.

**Comment by KoenDG** [comment]
Ok, this turns out to be a non-issue, as the page does actually mention this and I apparently just skipped it. Closing ticket.
