### ISSUE TITLE
Wrong minimum version listed for WSL2

### ISSUE THREAD

**Issue by adiun** [MicrosoftDocs/WSL#862]
This page says:

>If wsl --set-default-version results as an invalid command, enter wsl --help. If the --set-default-version is not listed, it means that your OS doesn't support it and you need to update to version 1903, Build 18362 or higher.

I have **version 1909, Build 18363.1016** and I don't see `--set-default-version` after running the `dism.exe` command in the doc and restarting. However I do see `-setdefault`. I also tried updating my kernel via https://aka.ms/wsl2kernel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by holger-waldmann** [comment]
I found a solution:
Look here #863

**Comment by craigloewen-msft** [comment]
You'll need to make sure you have the backport, I've updated the docs to give more info regarding this!

https://github.com/MicrosoftDocs/WSL/commit/05d04f851ca3eefbc9f83e462a7792fd61f1ae1e

Thank you @holger-waldmann for cross linking. :)
