### ISSUE TITLE
Upgrade to WSL2 on Windows 1909 does not work as described in the docs

### ISSUE THREAD

**Issue by holger-waldmann** [MicrosoftDocs/WSL#863]
On Windows Version 1909 the upgrade from WSL1 to WSL2 does not work as described in the docs:
https://docs.microsoft.com/en-us/windows/wsl/install-win10

In the docs it says:
> To update to WSL 2, you must meet the following criteria:
> Running Windows 10, updated to version 1903 or higher, Build 18362 or higher.

`winver.exe` tells me that I am running Windows Version 1909 (Build 18363.1016).
The file `C:\Windows\System32\wsl.exe` is Version 10.0.18362.239

Steps to reproduce the issue:

I started the upgrade from an up and running WSL1 with distro Ubuntu-18.04.

I did the following steps to upgrade to WSL2:
* Enable VTx and VTd in BIOS
* Enable the following features using PowerShell as Administrator: 
```
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
```
* Restart Windows.

I checked in the "Enable Windows Features" GUI that all three features are now enabled.

On PowerShell as Administrator I get the following:
```
> wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu-18.04 (Default)

> wsl --set-default-version 2
Ungültige Befehlszeilenoption: --set-default-version
```

This looks like output from an old version of `wsl.exe` that does not know about the new WSL2 command line options.

In the docs it says:
> If `wsl --set-default-version` results as an invalid command, enter `wsl --help`.
> If the `--set-default-version` is not listed, it means that your OS doesn't support it
> and you need to update to version 1903, Build 18362 or higher.

`wsl --help` does **not** list `--set-default-version` is an option.
I am on Windows Version 1909 Build 18363 (see above).
Now I am completely confused.

On several 3rd party pages (not Microsoft) I find contradictory information about the minimum version.
Some say its build 18917, some say its build 19041.
**Can someone please double-check that the minimum Windows version in the docs is correct?**
If it is not correct then please update the docs accordingly.
If it is correct then please provide a working upgrade description.

Note: I am working in a corporate environment and cannot upgrade Windows to a more recent version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by elupus** [comment]
Yup. Same here.

**Comment by holger-waldmann** [comment]
Today I am one step further.
I got it working 👍

[This blog post](https://devblogs.microsoft.com/commandline/wsl-2-support-is-coming-to-windows-10-versions-1903-and-1909/) by Microsoft describes that WLS2 was not originally part of Windows Version 1903 and 1909 but was backported in August 2020 as a patch.
> This backport has the minor build number: 1049.
> To summarize, if your minor build number is 1049 or higher on Windows builds 18362 or 18363, then you have the backport and the ability to run WSL 2 distros.

It took some further googling to locate the patch.
The patch that updates 1903 and 1909 to the required minimum version is [KB4566116](http://www.catalog.update.microsoft.com/Search.aspx?q=KB4566116)
After I installed this patch, everything works as described.
Note: The description of the patch does not say anything about WSL2. Therefore it is easy to miss.

So my summary is:
Yes, the WSL docs are faulty.
They do not properly describe the minimum required Windows version.

@craigloewen-msft 
Please update the docs to reflect this.

**Comment by craigloewen-msft** [comment]
This is a good call out! I've updated the docs to reflect this. 

https://github.com/MicrosoftDocs/WSL/commit/05d04f851ca3eefbc9f83e462a7792fd61f1ae1e

**Comment by elupus** [comment]
I did not get KB4566116 by windows update. I had to manually install it by the link mentioned above. After that WSL started allowing me to set wsl version.

**Comment by unphased** [comment]
KB4566116 refuses to install for me. "The update is not applicable to your computer."
