### ISSUE TITLE
Running Linux command Direct on CMD

### ISSUE THREAD

**Issue by DeathNet123** [MicrosoftDocs/WSL#864]
Hello, Everyone, my name is Arslan Iftikhar and today my question is pretty odd.

So, you see I am using Windows Subsystem for Linux for over a year now with Kali Linux installed on my windows 10 with WSL right now I have WSL2 on my insider build 20197.

The problem is somehow I don't know how it happened but I was able to use Linux commands on command prompt. 

I was able to use clear, ls, touch, mv, and some other Linux command directly on Command Prompt (CMD) I was not using it on bash, Git, or something like this.

I was Like CMD -> then use the Commands of Linux.

So yesterday I factory reset my laptop and I was not able to use them on CMD again so my first thought was that I have to enable to WSL so Enabled the WSL and installed the Distribution from Store but still I am not able to use the command on CMD.

any idea how it happened because using Linux command on CMD was convenient.

**Comment by craigloewen-msft** [comment]
Please try running `wsl.exe` to access your Linux distro, and you can run things like `wsl.exe -u root apt update` to execute Linux commands from a CMD prompt. 
Thank you for filing!
