### ISSUE TITLE
Note on upgrade incorrect

### ISSUE THREAD

**Issue by wowfood** [MicrosoftDocs/WSL#865]
Note next to how to upgrade to WSL 2 reads the following

If wsl --set-default-version results as an invalid command, enter wsl --help. If the --set-default-version is not listed, it means that your OS doesn't support it and you need to update to version 1903, Build 18362 or higher.

My OS is fully updated and winver reads the following

![image](https://user-images.githubusercontent.com/6247711/91302362-4b284200-e79e-11ea-8420-78a44eae6e4b.png)

However in powershell if I type wsl --help there is no mention of --set-default-version

![image](https://user-images.githubusercontent.com/6247711/91302474-79a61d00-e79e-11ea-8223-47ff99c4305c.png)

I'm assuming there's another component that needs to be installed to enable this option but no idea what it is.  Any answers would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#install-the-windows-subsystem-for-linux)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by wowfood** [comment]
https://docs.microsoft.com/en-us/windows/wsl/compare-versions

This page states

WSL 2 is only available in Windows 10, Version 2004, Build 19041 or higher

It may be that the documentation on the issue page needs updating to the correct version.

**Comment by holger-waldmann** [comment]
I found a solution for 1903 and 1909:
Look here #863

**Comment by craigloewen-msft** [comment]
You'll need to make sure you have the backport, I've updated the docs to give more info regarding this!

https://github.com/MicrosoftDocs/WSL/commit/05d04f851ca3eefbc9f83e462a7792fd61f1ae1e

Thank you @holger-waldmann for cross linking. :)
