### ISSUE TITLE
The Microsoft Store location returns no content

### ISSUE THREAD

**Issue by yecril71pl** [MicrosoftDocs/WSL#868]
There are no distributions to be retrieved from [Microsoft Store](https://aka.ms/wslstore).  Distributions, but unfortunately lots of other things too, can be retrieved from [Microsoft Store](https://www.microsoft.com/pl-pl/store/top-free/apps/pc?category=Developer+tools%5cUtilities&cid=msft_web_chart).
---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/pl-pl/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by dimithras** [comment]
### One can download distros without even using [Microsoft Store](https://www.microsoft.com/en-us/store/apps/windows).
The [link for manual download](https://docs.microsoft.com/en-us/windows/wsl/install-manual) is not eye-catching and is kinda hidden on [Windows Server Installation Guide](https://docs.microsoft.com/en-us/windows/wsl/install-on-server) page.

</br>

#### In case you still want to do it with [Microsoft Store](https://www.microsoft.com/en-us/store/apps/windows)
I would suggest you checking **hosts** file:
`C:/WIndows/System32/drivers/etc/hosts`
There should be no _Microsoft_ hosts listed there.

To make it simple, make sure there is nothing below these lines:
>\# &nbsp;&nbsp; 127.0.0.1 &nbsp; &nbsp; &nbsp;  &nbsp; localhost
>\# &nbsp; &nbsp; ::1 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; localhost

In case there are other lines, make a backup of **hosts** file and delete it under above mentioned path, try to access [Microsoft Store](https://www.microsoft.com/en-us/store/apps/windows) again.

Also keep in mind, that some providers may block access to _Microsoft_ services, at least I've seen such behavior sharing internet connection from phone.

If none of the above works, try to analyze traffic with [Fiddler](https://www.maketecheasier.com/download-appx-files-from-windows-store/) or WireShark to see what prevents you from accessing [Microsoft Store](https://www.microsoft.com/en-us/store/apps/windows).

**Comment by yecril71pl** [comment]
Who said I can access [Microsoft Store](https://aka.ms/wslstore) but there are no distributions over there.

**Comment by dimithras** [comment]
> I can access [Microsoft Store](https://aka.ms/wslstore) but there are no distributions over there.

Well, somehow you found it #877, right?

**Comment by yecril71pl** [comment]
I found it in [Microsoft Store](https://www.microsoft.com/pl-pl/store/top-free/apps/pc?category=Developer+tools%5cUtilities&cid=msft_web_chart).  However, that location contains things that are not distributions, so it is hard to discover.

**Comment by dimithras** [comment]
> I found it in [Microsoft Store](https://www.microsoft.com/pl-pl/store/top-free/apps/pc?category=Developer+tools%5cUtilities&cid=msft_web_chart). However, that location contains things that are not distributions, so it is hard to discover. Also, it is questionable whether Linux distributions are development tools; certainly Microsoft would like them to stay there but openSUSE is in fact my favourite _desktop_.

Distributions found in [MS Store](https://www.microsoft.com/en-us/store/apps/windows) are pre-made to use with **wsl** as they use bootstrap and other settings to run under **wsl**.

You are right, actually **appx** applications are a kind of container featuring special distro and tools to reset it, repair and etc.

</br>

Preparation of a custom distro is not covered by [Windows Subsystem for Linux Documentation](https://docs.microsoft.com/en-us/windows/wsl/).
To get deeper into custom distros you can take a look at following links:
1. [_Fedora_ istallation in wsl with **.iso image**](https://gist.github.com/artman41/858450e2c29b239d8692213b684ada25)
2. [_Fedora_ distro out of **rootfs**](https://dev.to/bowmanjd/install-fedora-on-windows-subsystem-for-linux-wsl-4b26)

**Comment by yecril71pl** [comment]
[Microsoft Store](https://www.microsoft.com/en-us/store/apps/windows) sells all kinds of things, including Linux distributions.  [Microsoft Store](https://aka.ms/wslstore) is supposed to get me to the shelf with Linux distributions.  But that shelf is empty.

**Comment by craigloewen-msft** [comment]
This Microsoft Store link works, and if needed you can run `wsl -l -o` to see online distros and install them with `wsl --install -d <DistroName>`

**Comment by yecril71pl** [comment]
> This Microsoft Store link works

I have just tried it and got an error:

> Something happened on our end.

**Comment by craigloewen-msft** [comment]
Is the microsoft store enabled on your machine? Can you access the Store normally?

**Comment by yecril71pl** [comment]
Microsoft Store works, the hyperlink does not.
