### ISSUE TITLE
WSL 2 is only available in builds higher than 19041 

### ISSUE THREAD

**Issue by gundarev** [MicrosoftDocs/WSL#871]
WSL 2 requires Windows 10 2004 (https://docs.microsoft.com/en-us/windows/wsl/wsl2-index)
this page incorrectly says that 1903 is needed for upgrade
https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Fixed this in the master branch! Thanks for filing this! 👍 

https://github.com/MicrosoftDocs/WSL/commit/40dd3bc6dc4bfc31da314be19dcd02bae3911380

**Comment by gundarev** [comment]
Hello, I think the doc fix is incorrect. Docs should say that WSL 2 is only available in 2004 or later

--Denis

**Comment by craigloewen-msft** [comment]
The fix is correct, we backported support for WSL 2 to Windows 10 version 1903 and higher!

https://github.com/MicrosoftDocs/WSL/commit/6ff046993e9f196cdfa04f5f91130e0e4ff1e7fa
