### ISSUE TITLE
wsl_update_x64.msi is not signed!

### ISSUE THREAD

**Issue by MicahZoltu** [MicrosoftDocs/WSL#873]
https://aka.ms/wsl2kernel redirects to https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel which has a download link pointing at https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi.  If you try to run that update you get a prompt warning you that the the package is not signed by Microsoft.

Signed packages help protect users from MITM attacks and by not having a signed package I cannot easily be sure that the thing I downloaded and ran is actually the package from Microsoft that I intended to run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Updating the WSL 2 Linux kernel](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by MicahZoltu** [comment]
![image](https://user-images.githubusercontent.com/886059/91569876-7f575a80-e978-11ea-97d2-7c0f82a916d7.png)

**Comment by cedral** [comment]
It's been more than a year why isn't this fixed?

**Comment by craigloewen-msft** [comment]
This has been fixed in the latest version!

**Comment by mmercan** [comment]
![image](https://github.com/MicrosoftDocs/WSL/assets/5808371/c6915897-b167-49e2-99f5-f79e88210e01)
September Release we have the same issue.
