### ISSUE TITLE
wsl --set-default-version 2

### ISSUE THREAD

**Issue by DavidAThomas** [MicrosoftDocs/WSL#876]
[Enter feedback here]
 wsl --set-default-version 2
When I enter this I get the following
Invalid command line option: --set-default-version
etc?
doing something dumb trying to install WSL 2
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by nickoralias** [comment]
The same thing happens to me.  I'm following the [instructions in the docs](https://docs.microsoft.com/en-us/windows/wsl/install-win10#:~:text=If%20wsl%20%2D%2Dset%2Ddefault,1903%2C%20Build%2018362%20or%20higher.) and I don't understand what could be wrong after restarting multiple times.  I am already using Ubuntu with WSL 1 and I am on version 1903 build 18362.1016

**Comment by lord-aerion** [comment]
I too am on the required minimum build, yet run into this error. Thankfully I'm on real Linux 99% of the time; it just works.

**Comment by nickoralias** [comment]
I found this: https://devblogs.microsoft.com/commandline/wsl-2-support-is-coming-to-windows-10-versions-1903-and-1909/#how-do-i-get-it

Looks like I'm on a build that doesn't have the patch yet after all (1049 min build required).  Please update your [docs](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2)!  

> To update to WSL 2, you must meet the following criteria:
> 
> Running Windows 10, updated to version 1903 or higher, Build 18362 or higher for x64 systems.

The above information just isn't true.  I am on build 1016 and struggled to find any additional information online  once I realized it wasn't working.

**Comment by lord-aerion** [comment]
Yep, same blog I found and used.

Just goes to show that Microsoft and Linux are strange bedfellows indeed.

**Comment by mecjack** [comment]
I still get the same error on Build 19042.572:   
PS U:\> wsl --set-default-version 2

wsl : Die Benennung "wsl" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren
Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und
wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ wsl --set-default-version 2
+ ~~~
    + CategoryInfo          : ObjectNotFound: (wsl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by throatwobblermangrove3** [comment]
Try this:

1, Open a DOS prompt with an account with administrator privilege.
2. CD C:\WINDOWS\SYSTEM32\
3. Run the command

wsl --set-default-version 2

I too used that article and noticed that the picture used a DOS prompt but the article said use Powers-hell.

**Comment by hpsem** [comment]
> 
> 
> Try this:
> 
> 1, Open a DOS prompt with an account with administrator privilege.
> 2. CD C:\WINDOWS\SYSTEM32
> 3. Run the command
> 
> wsl --set-default-version 2
> 
> I too used that article and noticed that the picture used a DOS prompt but the article said use Powers-hell.

@throatwobblermangrove3 answer worked for me

**Comment by craigloewen-msft** [comment]
This is a stale issue, there have been many improvements to WSL since this was created. Please upgrade to latest and try again, if you're still seeing this issue please report it at the microsoft/wsl GitHub repo. We'll close this to help our bookkeeping. Thank you!
