### ISSUE TITLE
Please add a direct download link for openSUSE 15.1

### ISSUE THREAD

**Issue by yecril71pl** [MicrosoftDocs/WSL#877]
See [openSUSE-Leap-15-1](https://www.microsoft.com/pl-pl/p/opensuse-leap-15-1/9njfzk00fgkv)!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by dimithras** [comment]
While it's not provided by MS team, you can use this workaround for now:
1. Access [**MS Store**](https://www.microsoft.com/en-us/store/apps/windows) page and search for [openSUSE-Leap-15-1!](https://www.microsoft.com/en-us/p/suse-linux-enterprise-server-15-sp1/9pn498vpmf3z#activetab=pivot:overviewtab)
You already have the [link](https://www.microsoft.com/pl-pl/p/opensuse-leap-15-1/9njfzk00fgkv).
2. On this [website](https://store.rg-adguard.net/) paste the link and click checkbox.
Website will provide 2 links for download.

</br>

In my case:
> [46932SUSE.openSUSE-Leap-15-1_1.1.0.0_x64__022rs5jcyhyac.appx](http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/acc7c94c-6fb1-4dc2-ae8a-36d0bf951d4a?P1=1598738230&P2=402&P3=2&P4=OChIyGagTEGVzoCyj1XRsTZY3uboX3jfrQAR7QaFF0qt8dLpwTSr72hZnsVk%2bRe9AvWiTPzZO8xKWyAAjJ49FQ%3d%3d)
> Link expires: &nbsp; &nbsp; _2020-08-29 21:57:10 GMT_
> Size: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 276.97 MB

The other link with **.BlockMap** is not really needed.

After downloading proceed as described [here](https://docs.microsoft.com/en-us/windows/wsl/install-on-server) or just double click on downloaded **appx**.

**Comment by craigloewen-msft** [comment]
Added!
