### ISSUE TITLE
Does Linux links work for Windows in WSL?

### ISSUE THREAD

**Issue by khtan** [MicrosoftDocs/WSL#879]
Linux can create hard and soft links using "ln". Does these links work transparently when accessed from the Windows side?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by khtan** [comment]
Another way of putting it is :  What I wanted to know is not how they work now but what is the intent/support policy. Does Microsoft intend for links from Linux and Windows to be transparent or to be non inter-operable.

**Comment by dimithras** [comment]
Symlinks created inside Linux distribution being accessed from Windows via File Explorer `\\wsl$\` behave same way as soft links in Windows, opening a link and making changes will change the linked file.

**Comment by khtan** [comment]
Very nice, thanks. What about symlinks to folders? Do they also work transparently as expected?

**Comment by dimithras** [comment]
> Very nice, thanks. What about symlinks to folders? Do they also work transparently as expected?

In case of **folders** from Windows side unfortunately not.
Link created in distro `ln -s /etc/ link_to_etc` works as expected inside distro, but in File Explorer is shown as a file.
Attempt to reference folder symlink as a path in FE leads to opening a file which results in an error.

However folder link created in Windows with `mklink /J "C:/winlink_folder" "C:/Users/Admin/Desktop"` is seen by Linux exactly as a folder symlink `~winlink_folder` and can be accessed to get to destionation.
