### ISSUE TITLE
WSL 2 for  version 1903, Build 18362 or not?

### ISSUE THREAD

**Issue by tauinger-de** [MicrosoftDocs/WSL#882]
The page states: "If wsl --set-default-version results as an invalid command, enter wsl --help. If the --set-default-version is not listed, it means that your OS doesn't support it and you need to update to version 1903, Build 18362 or higher."

However, I do have that version installed: "Version 1903 (Build 18362.1016)" according to winver.exe

So is your documentation wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hi @tauinger-de, I'm not quite understanding this issue. Could you clarify? 

Are you saying that you have Windows 10 "Version 1903 (Build 18362.1016)" but wsl --set-default-version is resolving as an invalid command?

**Comment by tauinger-de** [comment]
Hi,

 

yes, correct. However, by now I have upgraded my Windows and cannot reproduce.

 

But exactly that was the case and the reason for me to submit the issue.

 

 

 

Von: Matt Wojciakowski [mailto:notifications@github.com] 
Gesendet: Freitag, 25. September 2020 21:10
An: MicrosoftDocs/WSL <WSL@noreply.github.com>
Cc: tauinger-de <thomas@auinger.de>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/WSL] WSL 2 for version 1903, Build 18362 or not? (#882)

 

Hi @tauinger-de <https://github.com/tauinger-de> , I'm not quite understanding this issue. Could you clarify?

Are you saying that you have Windows 10 "Version 1903 (Build 18362.1016)" but wsl --set-default-version is resolving as an invalid command?

**Comment by mattwojo** [comment]
Oh - I just noticed the issue. We've [noted this in the docs](https://docs.microsoft.com/windows/wsl/install-win10#requirements), but I believe this was after you filed the issue... the Build number must be 18362.1049+ ...with the minor build # over .1049. You can read more about this in Craig's blog: [WSL 2 Support is coming to Windows 10 Versions 1903 and 1909](https://devblogs.microsoft.com/commandline/wsl-2-support-is-coming-to-windows-10-versions-1903-and-1909/).

Glad you've got it working now and apologies for the trouble! Closing this issue.
