### ISSUE TITLE
Instructions should mention updating WSL2 kernel

### ISSUE THREAD

**Issue by paulbatum** [MicrosoftDocs/WSL#883]
Following the instructions on this page resulted in `Error: 0x1bc` when performing the ` wsl --set-default-version 2` step.

I was able to resolve the problem after discovering [this github issue](https://github.com/microsoft/WSL/issues/5651), and following the update instructions for the WSL 2 Linux kernel [here](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel).

My recommendation is that these instructions should mention the need to update WSL 2 Linux kernel if this error is encountered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by dimithras** [comment]
This error is listed in [troubleshooting](https://github.com/MicrosoftDocs/WSL/blob/master/WSL/troubleshooting.md#error-0x1bc-when-wsl---set-default-version-2)
