### ISSUE TITLE
accessing a Windows web server from WSL2 cli example is misleading

### ISSUE THREAD

**Issue by uishon** [MicrosoftDocs/WSL#891]
The example you give [here](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#accessing-windows-networking-apps-from-linux-host-ip) is a bit misleading (that is, unless I'm missing something...). This doesn't work without opening the Windows Firewall respective port (5000 in your example) for access from *public* networks. I've learned it the hard way. See also [this](https://github.com/microsoft/WSL/issues/4139) issue on github.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [Comparing WSL 2 and WSL 1](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by valentijnscholten** [comment]
I found out the hard way too, and this is undesirable that we need to allow public access to ports.

**Comment by NumberPiOso** [comment]
Would you mind sharing how to do this? This has not worked for me.

**Comment by uishon** [comment]
Sure. What have you tried and what did not work for you?

**Comment by NumberPiOso** [comment]
> Sure. What have you tried and what did not work for you?

It resulted that my computer used another firewall different from Windows Firewall.
Opening ports there also worked for me.

Thanks.

**Comment by uishon** [comment]
👍
