### ISSUE TITLE
WSL2 is not available although I updated 1909 to build 18363

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/WSL#892]
```
If wsl --set-default-version results as an invalid command, enter wsl --help. If the --set-default-version is not listed, it means that your OS doesn't support it and you need to update to version 1903, Build 18362 or higher.
```

If I run a cmd prompt, I get the following:
```
Microsoft Windows [Version 10.0.18363.1016]
(c) 2019 Microsoft Corporation. All rights reserved.
C:\WINDOWS\system32>wsl --set-default-version 2
Invalid command line option: --set-default-version
```

As you can see I am running version 10.0.18363.1016. That is one higher than the required 18362.

I have run the following dism commands and rebooted:
```
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
```

What do I need to do further to get it working?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
I've updated troubleshooting.md to include help for this issue! Please let me know if the instructions there resolve your issue or if we could improve them. Thanks!

https://github.com/MicrosoftDocs/WSL/commit/6ff046993e9f196cdfa04f5f91130e0e4ff1e7fa
