### ISSUE TITLE
incorrect description

### ISSUE THREAD

**Issue by dawn-knight** [MicrosoftDocs/WSL#893]
According to [https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v]
hyper-v cann't be enabled on win10 home, so wsl2 is not supported by win10 home either.
Pls corret the description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
WSL 2 is supported on Windows 10 home, we rely on the 'Virtual Machine Platform' optional component which exposes a subset of Hyper-V features. 
However that original link is correct, the 'Hyper-V' optional feature is not on Windows 10 home.
