### ISSUE TITLE
Install WSL2 on 18363 fails despite official docs say it should work

### ISSUE THREAD

**Issue by burzum** [MicrosoftDocs/WSL#894]
The [official docs here](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2) say WSL2 works from build 18362 or greater.

> Running Windows 10, updated to version 1903 or higher, Build 18362 or higher for x64 systems.

I've got: 1836**3**

```sh
WmiObject -Class Win32_OperatingSystem | % Buildnumber
18363
```

System information shows the same:

[![enter image description here][1]][1]

The required features are enabled:

```sh
C:\WINDOWS\system32> Get-WindowsOptionalFeature -Online -FeatureName "Microsoft-Windows-Subsystem-Linux"


FeatureName      : Microsoft-Windows-Subsystem-Linux
DisplayName      : Windows Subsystem for Linux
Description      : Provides services and environments for running native user-mode Linux shells and tools on Windows.
RestartRequired  : Possible
State            : Enabled
CustomProperties :
                   ServerComponent\Description : Provides services and environments for running native user-mode Linux
                   shells and tools on Windows.
                   ServerComponent\DisplayName : Windows Subsystem for Linux
                   ServerComponent\Id : 1033
                   ServerComponent\Type : Feature
                   ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
                   ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux




C:\WINDOWS\system32> Get-WindowsOptionalFeature -Online -FeatureName "VirtualMachinePlatform"


FeatureName      : VirtualMachinePlatform
DisplayName      : Virtual Machine Platform
Description      : Enables platform support for virtual machines
RestartRequired  : Possible
State            : Enabled
CustomProperties :
```

[![enter image description here][2]][2]

However, when I run 

```sh
wsl --set-default-version 2
```

I'm getting:

```sh
C:\WINDOWS\system32> wsl --set-default-version 2
Invalid command line option: --set-default-version
```

Any idea what I've missed?

  [1]: https://i.stack.imgur.com/UWgYA.png
  [2]: https://i.stack.imgur.com/Pcv06.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by FMauroy** [comment]
Just had the exact same issue. By Googling a bit, I found that I needed an "optional" Windows Update: kb4566116.
After a reboot, the command above works.
But still not out of the bush, a new installation of Ubuntu 20.04 LTS from the store doesn't start: `WslRegisterDistribution failed with error: 0xffffffff`
Will post back if I find something...
HTH

**Comment by craigloewen-msft** [comment]
I've updated the docs to be clearer here and link to the troubleshooting section for those on 1903 and 1909! :) 

https://github.com/MicrosoftDocs/WSL/commit/321c83838639cb3cd9cc90752f9ed8dcfc596585

**Comment by craigloewen-msft** [comment]
I'm marking this as resolved since I believe that should help resolve your issue, please let me know if those instructions don't work for you and I can add further fixes.
