### ISSUE TITLE
Pulseaudio in WSL2 Kali linux can not rise any sound

### ISSUE THREAD

**Issue by qnoyzone** [MicrosoftDocs/WSL#895]
I have done many much more tricks to setup pulseaudio whether in Windows 10 or Kali linux frim WSL 2, but Pulseaudio can not rise any sound in Kali linux... Once can connect to pulseadio mixer but still there's no sound, it seemed that WSL 2 kali linu x can not read / mounting the Sound driver in windows 10...

There are so many users have bad experience about pulseaudio in WSL2 Linux, please wen need your ultimate tools adn tricks, tks

**Comment by Alcheri** [comment]
[#5816](https://github.com/microsoft/WSL/issues/5816)

**Comment by craigloewen-msft** [comment]
Please see this tutorial: https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

Thank you for filing!
