### ISSUE TITLE
Is Hyper-V necessary or not for WSL2? Can it be activated on Windows 10 Home?

### ISSUE THREAD

**Issue by Oxfos** [MicrosoftDocs/WSL#899]
## SITUATION
**I'm trying to install WSL 2.**

I have Microsoft Windows 10 Home [Version 10.0.19041.508]
I already have WSL 1 and Ubuntu 18.04 working.

I have followed all instructions [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and tried solutions explained [here](https://github.com/microsoft/WSL/issues/5363) to no avail (see results below).

### My features
![windowsfeatures](https://user-images.githubusercontent.com/39594453/92714420-7db86a00-f35c-11ea-801e-d2f2236620dd.PNG)

### Some trials and outcomes
![Capture](https://user-images.githubusercontent.com/39594453/92714390-709b7b00-f35c-11ea-9a55-c6d0f2d24bf7.PNG)
![noHvpresent](https://user-images.githubusercontent.com/39594453/92715097-4f875a00-f35d-11ea-9031-0e1410e094f7.PNG)

## REMARKS
If Hyper-V is indeed required for WSL 2, I discovered [here](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v) that on Windows 10 Home it cannot be activated:

![notonhome](https://user-images.githubusercontent.com/39594453/92718128-a727c480-f361-11ea-95ca-35536fd5624f.PNG)

However, the FAQ [here](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq) says:

![includinghome](https://user-images.githubusercontent.com/39594453/92718016-7b0c4380-f361-11ea-8848-f1d94bef6a92.PNG)

## QUESTIONS
1. Is Hyper-V required or not for WSL 2?
2. Can Hyper-V be activated or not on Windows 10 Home?

Thank you for any suggestion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by onomatopellan** [comment]
1. No, for WSL2 you only need "Virtual Machine Platform" (a subset of Hyper-V) and "Windows Subsystem for Linux" features, both available in Home edition.
2. No. Full Hyper-V is not available in Home.

"Please enable the Virtual Machine Platform windows feature and ensure virtualization is enabled in the BIOS" could be a misleading error message. What's your CPU?
If the CPU lacks some capabilities like SLAT it won't work. https://github.com/microsoft/WSL/issues/4709

**Comment by Oxfos** [comment]
@onomatopellan thank you.
CPU: Intel Core i5-8265U CPU @ 1.60 GHz
In addition:
![image](https://user-images.githubusercontent.com/39594453/92871645-6f725880-f405-11ea-8921-8c636864f2ca.png)

I run the [Intel Processor Identification Utility](https://downloadcenter.intel.com/download/28539?v=t). It indicates that SLAT is supported:
![image](https://user-images.githubusercontent.com/39594453/92872197-0a6b3280-f406-11ea-8881-1cfa4edc6890.png)

**Comment by Oxfos** [comment]
I found the solution.

The virtualization technology was disabled and had to be enabled in the BIOS:
![InkedIMG_20200911_082120809_copy_LI](https://user-images.githubusercontent.com/39594453/92878069-0e01b800-f40c-11ea-82cd-bc6f1b90af0f.jpg)

Now it works:
![image](https://user-images.githubusercontent.com/39594453/92878273-40131a00-f40c-11ea-9607-3d27c42f8e49.png)

Btw you don't see any changes in the enabled features:
![image](https://user-images.githubusercontent.com/39594453/92879335-405fe500-f40d-11ea-915a-ee8c23e224a8.png)


@onomatopellan Thank you again for pointing me in the right direction.

**Comment by thecriticalpoint** [comment]
This was helpful. Thank you.

**Comment by tinoweb** [comment]
thanks gays help  me a lot

**Comment by osm2po** [comment]
There is a working hack which gives you this here.
(my box is a 10 years old AMD/Asus-Board with Win-Home-10)
![grafik](https://user-images.githubusercontent.com/5272367/189544285-c37fcf17-81df-402e-8c8f-cc5120668185.png)

**Comment by hannah23280** [comment]
So based on the above, can we conclude, to run linux containers, we don't need windows 10 pro, since windows 10 home already have WSDL + Virtual Machine Platform" (a subset of Hyper-V)  (with Virtualization Technology enabled in the bios). 

To run windows containers , we will need windows 10 pro.  With windows 10 pro, it either use Hyper-V to run windows containers OR natively run windows containers without Hyper-V.  The latter requires us to enable the "containers" checkbox in the "Turn Windows Feature on or off"

Hope my understand is right.

**Comment by picofaradpjf** [comment]
@laoshaw my research into this says you need nested virtualization to run kvm inside wsl2 and that only is possible in Windows 11 at this time.

**Comment by DanKaplanSES** [comment]
In my opinion this should be reopened. The FAQ is as unclear today as it was then. @onomatopellan 's information should be included in the FAQ to clarify for others. I'll submit a PR.
