### ISSUE TITLE
Extend documentation showing how to mount a vhdx file with wsl --mount

### ISSUE THREAD

**Issue by ad-on-is** [MicrosoftDocs/WSL#902]
https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk currently does not describe how to create an vhdx file and mount it into WSL.

**Comment by craigloewen-msft** [comment]
Added! https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#mount-a-vhd-in-wsl

Thank you for filing!
