### ISSUE TITLE
GIT repos are not compatible between Windows and WSL

### ISSUE THREAD

**Issue by blakemcbride** [MicrosoftDocs/WSL#904]
If you create a git repo on Windows and try to access it (git status) under WSL, first it states "Refresh index" and then gives you the wrong results.  You can't go back and forth between Windows and WSL with git.  You should either state this or fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31aade8d-62a2-6d91-b0bd-3bc5880042f8
* Version Independent ID: 12e275fa-8010-5e5a-af8c-120f11ab0932
* Content: [Get started using Git on Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git)
* Content Source: [WSL/tutorials/wsl-git.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-git.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by WSLUser** [comment]
You actually can. I've cloned the same code from both no issues.

**Comment by craigloewen-msft** [comment]
It is possible to access git repos across WSL and Windows, could you please try this again on latest and if you see an issue file it at https://github.com/microsoft/wsl
