### ISSUE TITLE
Mandatory component Virtual Machine Platform is mandatory for WSL2, NOT optional.

### ISSUE THREAD

**Issue by rafaelpac** [MicrosoftDocs/WSL#908]
The second step of the instalation says:

`Enable the 'Virtual Machine Platform' optional component`

Well, when I read it, I thought: "Is it some kind of optional component? So, if this is optional, I might not want to install it, right? What difference does it make? What is it used for?".

But then I think I got it. It is an optional Windows component, BUT IT IS NOT OPTIONAL for WSL2. It is mandatory for WSL2. Although it is MANDATORY, the title says OPTIONAL component.

Well, it was a problem for me, I got confused. I sorted it out in a few minutes, but it looks like a simple fix to clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by WSLUser** [comment]
If the word optional is removed would that suffice for you? Most Windows users think of it from the perspective of being Windows Optional. Obviously you did not for some reason.

**Comment by rafaelpac** [comment]
I think so.
Or, to clarify even better, it could say: "You must enable the 'Virtual Machine Platform' component. This component is a part of Windows but it is not enabled by default on regular installations of the system."
