### ISSUE TITLE
French page translation doesn't have the msi package

### ISSUE THREAD

**Issue by Charlie-Lucas** [MicrosoftDocs/WSL#918]
Steps:
- go on https://docs.microsoft.com/fr-fr/windows/wsl/install-win10
- run `dism.exe` commands
- run `wsl --set-default-version 2`
- Error message telling me to go on https://aka.ms/wsl2kernel to update my kernel
- redirected to https://docs.microsoft.com/fr-fr/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package

I can't find msi package. 

Solution 
- go on https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package

**Comment by mattwojo** [comment]
Hi @Charlie-Lucas - Thanks so much for bringing this to our attention!! 

Looking into this right now -- looks like our localization team hasn't picked up the change yet. Apologies! 

Here's the links in the meantime:
[WSL2 Linux kernel update package for x64 machines](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi)
[WSL2 Linux kernel update package for ARM64 machines](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_arm64.msi)

And we just filed a temporary fix (PR: [MicrosoftDocs/WSL#933](https://github.com/MicrosoftDocs/WSL/pull/933)) to point that aka link for the kernel install to the English instructions: 
https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

**Comment by mattwojo** [comment]
Checked with our localization team and the install page should be translated to be the same across all languages as the English/US page by the middle of next week. I guess they are super backlogged because of the Ignite conference.
