### ISSUE TITLE
wsl --mount Invalid command

### ISSUE THREAD

**Issue by ADNewsom09** [MicrosoftDocs/WSL#926]
on my instance: W10 Pro x64 2004 running wsl --mount <anything> gives an invalid command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e255b0-71c7-adc6-cac0-6df3b76a971f
* Version Independent ID: a9d73ca3-7026-5b5a-f3fe-3511e976cde4
* Content: [Get started mounting a linux disk in WSL 2 (preview)](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk)
* Content Source: [WSL/wsl2-mount-disk.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-mount-disk.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by bcbywale** [comment]
I had the same problem but then noticed that is is only available in Windows Preview Build 20211. The document doesn't make that clear except for the (preview) in the title.

**Comment by craigloewen-msft** [comment]
Fixed in the latest version!
