### ISSUE TITLE
Russian version is missing step with wsl_update_x64

### ISSUE THREAD

**Issue by mkanev** [MicrosoftDocs/WSL#928]
I almost got crazy because this document is linked to itself in step 5 with step 4 missed in Russian version. Please fix this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#enable-the-virtual-machine-platform-optional-component)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by dimithras** [comment]
It's not missing, but for some reason is stated in [this paragraph](https://github.com/MicrosoftDocs/WSL.ru-RU/blob/live/WSL/install-win10.md#%D0%B7%D0%B0%D0%B4%D0%B0%D1%82%D1%8C-wsl2-%D0%B2-%D0%BA%D0%B0%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B5-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8-%D0%BF%D0%BE-%D1%83%D0%BC%D0%BE%D0%BB%D1%87%D0%B0%D0%BD%D0%B8%D1%8E).

I have to admit, Russian version is suffering lot's of discrepancies, but it's not maintained by any human, just a bot.
Raised this in comments under #880, upvoting may help get things moving.
