### ISSUE TITLE
Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0xc03a001a Error: 0xc03a001a The requested operation could not be completed due to a virtual disk system limitation. Virtual hard disk files must be uncompressed and unencrypted and must not be sparse. I have got this error please help in fixing this error.

### ISSUE THREAD

**Issue by Aman-rishu** [MicrosoftDocs/WSL#929]
Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/

**Comment by dimithras** [comment]
Duplicate #420 
Duplicate #404 
Follow [microsoft/WSL#4103](https://github.com/microsoft/WSL/issues/4103) for resolution

**Comment by Aman-rishu** [comment]
I couldn't understand what did you say.
...

**Comment by dimithras** [comment]
@Aman-rishu follow the last link to see how to resolve your problem.
Use search before posting an issue.

**Comment by Aman-rishu** [comment]
I got a very big Problem.
Please help me in solving that
Because I have solved the above error.
Now another problem
So please.

Thank you.
...

**Comment by Aman-rishu** [comment]
Please!!!!!

...

---------- Forwarded message ---------
From: Aman Rishu <amanrishu2003@gmail.com>
Date: Thu 24 Sep, 2020, 6:24 PM
Subject: Kali Linux and Ubuntu have met update errors
To: <notifications@github.com>


Sir,
      I have got an error in updating Kali Linux and Ubuntu as
err:1 http://http.kali.org/kali kali-rolling InRelease Temporary failure
resolving 'http.kali.org' reading package lists... done
w: failed to fetch http://http.kali.org/kali/dists/kali-rolling/inrelease
temporary failure resolving 'http.kali.org'

w: some index files failed to download. they have been ignored, or old ones
used instead.

Please help me.

...
