### ISSUE TITLE
wsl --set-default-version 2 not working in win 10 pro version 1909 (build 18363.836)

### ISSUE THREAD

**Issue by anthonydagondon** [MicrosoftDocs/WSL#932]
trying to follow this tutorial and it's not working in step 5 (set default wsl version) using the command 
`wsl --set-default-version 2`

i have build 1909 and document states that it should work with version 1903 or higher.

any suggestions how to resolve?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by dimithras** [comment]
What's the exact error?

There was one mentioned in [troubleshooting](https://github.com/MicrosoftDocs/WSL/blob/master/WSL/troubleshooting.md#error-0x1bc-when-wsl---set-default-version-2), please check if this helps.

**Comment by anthonydagondon** [comment]
> What's the exact error?
> 
> There was one mentioned in [troubleshooting](https://github.com/MicrosoftDocs/WSL/blob/master/WSL/troubleshooting.md#error-0x1bc-when-wsl---set-default-version-2), please check if this helps.

here is the full error.
`PS C:\Windows\system32> wsl --set-default-version 2
Invalid command line option: --set-default-version
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments to run Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d <DistributionName>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

Arguments to manage Windows Subsystem for Linux:

    --export <DistributionName> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import <DistributionName> <InstallLocation> <FileName>
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are currently
                being installed or uninstalled.

            --running
                List only distributions that are currently running.

    -setdefault, -s <DistributionName>
        Sets the distribution as the default.

    --terminate, -t <DistributionName>
        Terminates the distribution.

    --unregister <DistributionName>
        Unregisters the distribution.

    --upgrade <DistributionName>
        Upgrades the distribution to the WslFs file system format.

    --help
        Display usage information.`

**Comment by dimithras** [comment]
What's your build?
Settings -> System -> About -> OS Build

**Comment by dimithras** [comment]
Indeed it meets the requirements yet uses wsl version 1. I would suggest cross-posting this issue to [WSL](https://github.com/microsoft/WSL/issues).

**Comment by anthonydagondon** [comment]
this is already fixed with a couple of restart and windows updates
