### ISSUE TITLE
centos

### ISSUE THREAD

**Issue by web521** [MicrosoftDocs/WSL#934]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e953ca-c1d6-68bc-097c-f750ae3d2852
* Version Independent ID: 9ca5e58c-5f05-f36f-242e-8b1bd1d113cb
* Content: [An overview on the Windows Subsystem for Linux](https://docs.microsoft.com/en-au/windows/wsl/)
* Content Source: [WSL/index.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/index.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Adding CentOS to the Windows Store is up to the distro maintainers themselves, and not to the WSL team. We'll make sure your request to add it gets heard! Thank you!
