### ISSUE TITLE
unable to access network

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/WSL#938]
using wsl 2 (ubuntu 20.04 LTS), 
i try to download something like "curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip", it does not work. it keeps getting connection time out. even executing "sudo apt install net-tools" times out too.

doing "ping google.com" seems to work fine.

**Comment by craigloewen-msft** [comment]
Networking issues can happen for a variety of reasons, and if you're still seeing this issue please file it on the WSL Github repo at https://github.com/microsoft/wsl where the WSL devs can take a look and we'll have the necessary info to give actionable solutions! This repo is just for issues related to the docs. I'll close this issue for our bookkeeping. Thank you for filing!
