### ISSUE TITLE
Step 5 "wsl --set-default-version 2" does not work.

### ISSUE THREAD

**Issue by TheCodeFiend** [MicrosoftDocs/WSL#941]
I followed the instructions to enable WSL 2 on 1909.  I have Windows 10 1909 Build 18363.1016.  I have WSL as well as Virtual Machine Platform installed.  I've gone through Windows Update.  I installed the Linux kernel update MSI with no errors.  Step 5 says I should run "wsl --set-default-version 2" but the command line option "--set-default-version" is not recognized.

"❯ wsl --set-default-version 2
Invalid command line option: --set-default-version
Copyright (c) Microsoft Corporation. All rights reserved."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Your build needs to be on `18363.1049+`. Please hit 'Check for updates' in Windows settings and you should download the latest Windows update. More troubleshooting instructions an be found [here](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#im-on-windows-10-version-1903-and-i-still-do-not-see-options-for-wsl-2).

**Comment by TheCodeFiend** [comment]
This update is listed as a preview build?  When will it be released as stable?
