### ISSUE TITLE
wsl --set-default-version 2

### ISSUE THREAD

**Issue by albgen** [MicrosoftDocs/WSL#943]
command wsl --set-default-version 2 is not recognized.
The output on ps is: 
Invalid command line option: --set-default-version
Usage: wsl.exe [option] ...
Options:
    -d, --distribution <DistributionName>
        Launch the specified distribition.

    -e, --exec <CommandLine>
        Execute the specified Linux command. The remainder of the arguments are
        used as the command line to execute.

    -u, --user <UserName>
        Run as the specified user.

    --help
        Display this usage information.

    --
        Stop parsing arguments and pass the remainder to the Linux process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Please verify you're on the right Windows version to use WSL 2! You can find the instructions [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10#requirements).

**Comment by albgen** [comment]
![image](https://user-images.githubusercontent.com/7231968/95067458-29f33380-0704-11eb-8a8f-089c6db5d59e.png)
i'am on the right version.

**Comment by aalberto01** [comment]
> ![image](https://user-images.githubusercontent.com/7231968/95067458-29f33380-0704-11eb-8a8f-089c6db5d59e.png)
> 
> i'am on the right version.
> 
> Could it be the issue because this is a virtualised win2019 on vmware?

Try running it on cmd instead of powershell.
