### ISSUE TITLE
Documentation update suggestion

### ISSUE THREAD

**Issue by segin** [MicrosoftDocs/WSL#944]
On the page https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk, under limitations, mention that filesystems not directly supported by the kernel can be mounted via a `--bare` attach and then invoking the relevant FUSE driver.

**Comment by mattwojo** [comment]
Thanks @segin! Appreciate the contribution. Added: https://github.com/MicrosoftDocs/WSL/pull/1477
