### ISSUE TITLE
port forwarding does not work for UDP

### ISSUE THREAD

**Issue by mirabilos** [MicrosoftDocs/WSL#950]
I’ve tried your `netsh` command, and it only works for TCP, which is a showstopper.

(WSL 2 also lacks IPv6 support, only doing Legacy IPv4, which is also kinda problematic…)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [Comparing WSL 2 and WSL 1](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#accessing-network-applications)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This is a fair request! I've made sure it's noted by the team. This repo is just for the docs page so I'll close this for our bookkeeping. Thank you for filing!

**Comment by husakja** [comment]
Hello, if this is still a case I think this page: https://learn.microsoft.com/en-us/windows/wsl/networking should mention that it is TCP networking only.
