### ISSUE TITLE
Cannot enable WSL on Windows 10 Pro Build 19041

### ISSUE THREAD

**Issue by dmtrinh** [MicrosoftDocs/WSL#953]
![WSL_Feature_not_available_on_Build_19041](https://user-images.githubusercontent.com/1691596/95425518-04377b80-090a-11eb-88b8-5c3b85c5b006.PNG)

**Comment by torksrevol** [comment]
Check if appear in the feature list
Dism /online /Get-Features

**Comment by craigloewen-msft** [comment]
Please try this through GUI as well by searching for `Turn Windows Features on or Off` and then enabling it there:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/42221804/156653797-dce4f97d-991d-4d6a-a5f4-46cbae885c54.png">

/product
