### ISSUE TITLE
Strongly wish to add a `CentOS` distribution

### ISSUE THREAD

**Issue by ijliym** [MicrosoftDocs/WSL#956]
Strongly wish to add a `CentOS` distribution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
Maybe https://github.com/yuk7/CentWSL ??

**Comment by ijliym** [comment]
@Biswa96 Think you! I will try it.
