### ISSUE TITLE
Suggestion: update OpenSSH link

### ISSUE THREAD

**Issue by vitalkanev** [MicrosoftDocs/WSL#957]
In section [OpenSSH-Server connection issues](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#openssh-server-connection-issues), the Ubuntu Help link goes to a index page for server documentation in general. I'd suggest updating the link to https://ubuntu.com/server/docs/service-openssh, which has pretty much the same content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#im-on-windows-10-version-1903-and-i-still-do-not-see-options-for-wsl-2)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/troubleshooting.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by WSLUser** [comment]
Since it's regarding issues, it's actually more convenient to go straight to the troubleshooting page.

**Comment by mattwojo** [comment]
Hmm.... thanks @vitalkanev. It looks like the tutorial that we pointed to previously is now redirecting to that more general page. I've updated the link with your suggestion: [cd202e4](https://github.com/MicrosoftDocs/WSL/commit/cd202e4ed6867311346fc3c1a52b4f25a18e0ebf)
@WSLUser - I did a quick search and didn't see anything that I found more appropriate to link to than Vitaliy's recommendation. This link is based more on getting the initial config correct for the OpenSSH connection, even though it's in the WSL troubleshooting... in any case, if you have a better link, please share it and I can update again.
Thank you both!
