### ISSUE TITLE
Why can't I use systemd? 

### ISSUE THREAD

**Issue by HendrikFagel** [MicrosoftDocs/WSL#963]
Why can't I use systemd?

**Comment by craigloewen-msft** [comment]
This is being tracked as a feature request on the WSL repo!
/product

**Comment by mattwojo** [comment]
Closing as systemd is now supported in WSL, see the announcement for info on how to enable it: https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/
