### ISSUE TITLE
Git credential helper does not work

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/WSL#964]
On my system the credential helper is located on another location. I configured git as follows:

`credential.helper=/mnt/c/Users/myusername/AppData/Local/Programs/Git/mingw64/libexec/git-core/git-credential-manager.exe`

The authentication fails and I still need to provide username/password.

What can I do to diagnose?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31aade8d-62a2-6d91-b0bd-3bc5880042f8
* Version Independent ID: 12e275fa-8010-5e5a-af8c-120f11ab0932
* Content: [Get started using Git on Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git)
* Content Source: [WSL/tutorials/wsl-git.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-git.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Are you still seeing this issue? Do you have Git set up correctly on Windows?

**Comment by paul-vd** [comment]
@craigloewen-msft not sure if it's exactly related to the OP, but I just did a clean install:
- Windows 11 pro
- Git for windows
- Ubuntu

I followed the guide, and ran into the following error when trying to clone a private git repo:
```bash
/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe get: 1: /mnt/c/Program Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe: not found
```

I then searched my `Git` folder in windows for `git-credential-manager-core.exe` and found it's under `bin` and not `libexec/git-core`, so it might be good to update the docs to reflect that as well?
![image](https://user-images.githubusercontent.com/39598117/173825210-133e6e1c-3118-4d57-838a-42d1a635c117.png)
