### ISSUE TITLE
WSL2 distro manual install instructions are incomplete

### ISSUE THREAD

**Issue by johnmreynolds** [MicrosoftDocs/WSL#965]
There are install instructions for installing distros for WSL2 without using the Microsoft Store.

However, the instructions are incomplete, as they don't actually initialize the distro, and the page about initializing the distro doesn't cover this case (as the initialization isn't started automatically).

See issue:

https://github.com/microsoft/WSL/issues/4865

which wasn't fully answered.

It looks like there is a slightly awkward workaround, but not a clear way of doing this properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment]
What do you mean by "initialization"?

**Comment by johnmreynolds** [comment]
If you install it via the windows store, then on

https://docs.microsoft.com/en-us/windows/wsl/install-win10

Then step 7 actually sets up the distro and sets the new username and password, which I think is also the step described in:

https://docs.microsoft.com/en-us/windows/wsl/user-support

The issue is that the instructions on the page:

https://docs.microsoft.com/en-us/windows/wsl/install-manual

Don't actually trigger this step, so using the command

Add-AppxPackage .\app_name.appx

doesn't fully set things up.

It looks like the page:

https://docs.microsoft.com/en-us/windows/wsl/install-on-server

does have an alternate version of the install instructions, which probably would work on non-server systems too.

**Comment by Biswa96** [comment]
> Don't actually trigger this step, so using the command

That's what **manual** installation literally means. `Add-AppxPackage` only downloads and installs the Appx package which contains mainly an executable (e.g. ubuntu.exe), a compressed GNU/Linux distribution tarball. One has to manually execute the executable, then setup user with proper commands.

In this context, Windows Store is a babysitter which feeds those who can not eat food with their hands.

**Comment by Biswa96** [comment]
> Don't actually trigger this step, so using the command

That's what **manual** installation literally means. `Add-AppxPackage` only downloads and installs the Appx package which contains mainly an executable (e.g. ubuntu.exe), a compressed GNU/Linux distribution tarball. One has to manually execute the executable, then setup user with proper commands.

**Comment by johnmreynolds** [comment]
Indeed. This issue is just that there is a step missing between the instructions on

https://docs.microsoft.com/en-us/windows/wsl/install-manual

and the next page linked from that:

https://docs.microsoft.com/en-us/windows/wsl/user-support

in that it doesn't actually say you need to run the executable, or how to find where it is or what it is called.

It only needs an extra sentence to cover that.

Or alternatively, it looks like the much easier process is to ignore the appx install step entirely and just unzip and run the executable.

**Comment by Biswa96** [comment]
> how to find where it is or what it is called.

Hmm... That's I am agree with. There are some hint in the [Windows Server Installation Guide][1] but it is not fully explained.

[1]: https://docs.microsoft.com/en-us/windows/wsl/install-on-server

**Comment by chaim1221** [comment]
`Add-AppxPackage` does literally nothing. The "manual" instructions are frustrating. "Manual" does not mean "dig for information literally not in the docs or that does not apply to your situation." Manual like transmission; you select the gears when you're ready. This is more like an Ikea manual for a product you didn't buy; it doesn't apply.

**Comment by craigloewen-msft** [comment]
Looking at this doc now, we do have this text here describing that you need to run the app:
https://docs.microsoft.com/en-us/windows/wsl/install-manual#:~:text=The%20first%20time%20you%20launch%20a%20newly%20installed%20Linux%20distribution%2C%20a%20console%20window%20will%20open%20and%20you%27ll%20be%20asked%20to%20wait%20for%20a%20minute%20or%20two%20for%20files%20to%20de%2Dcompress%20and%20be%20stored%20on%20your%20PC.%20All%20future%20launches%20should%20take%20less%20than%20a%20second.

Does this address the issue?
