### ISSUE TITLE
Step 5 return "Access is denied"

### ISSUE THREAD

**Issue by davidebelloni** [MicrosoftDocs/WSL#968]
Step 5 of the guide return "Access is denied" (as Administrator and also unprivileged user)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#troubleshooting-installation)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Could you please file this as a [bug report on the WSL Github repo?](https://github.com/microsoft/WSL/issues/new/choose) I'd be very curious to see your logs on this and why access is being denied here (it shouldn't be). Please make sure to include the logs via feedback hub as that's what will help us debug this!

I'll close this issue out as it's not explicitly docs related, and we'll follow up with you over on the other repo :) Thanks for filing!
