### ISSUE TITLE
WSL2: Sqlite not working

### ISSUE THREAD

**Issue by oxidaan** [MicrosoftDocs/WSL#972]
I followed the steps for sql lite (at https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database) , with only difference I have Ubuntu 20.4.1. Gives error 'unable to read database header'.
Sqlite doesn't seem to work at all on wsl2 (also tried on Debian, same issue)
This is a fresh and empty Ubuntu installation, and yes it is WSL2.
A copy of my commands + output

$ sudo apt update
... output skipped...
$ sudo apt install sqlite3
...
$ sqlite3 --version
3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1
$ sqlite3 example.db
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> .databases
main: /home/daan/example.db
sqlite> .dbinfo ?DB?
**unable to read database header**
sqlite> .exit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 080023f0-501e-b638-b22c-9d2cbcbdb66a
* Version Independent ID: 88516d79-15be-0cf2-bb25-d20a17d1a37e
* Content: [Get started using MySQL MongoDB, PostgreSQL, SQLite, Microsoft SQL Server, or Redis to set up a database on Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database)
* Content Source: [WSL/tutorials/wsl-database.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-database.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by oxidaan** [comment]
Never mind, database is empty after creation, hence the 'unable to read database header' error. When adding a table first, it works: eg:
CREATE TABLE empty (kol INTEGER);
before the  .dbinfo ?DB? command.
Maybe update instructions at https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database ?

**Comment by mattwojo** [comment]
Thanks @oxidaan - appreciate the suggestion. Updated! :)
