### ISSUE TITLE
/etc/resolve.conf generateResolvConf instructions should state the need to shutdown WSL for setting to take effect

### ISSUE THREAD

**Issue by bersbersbers** [MicrosoftDocs/WSL#973]
The need to shutdown WSL for `generateResolvConf = false` to take effect should be stated as a comment in the default `/etc/resolv.conf`.

_Originally posted by @bersbersbers in https://github.com/microsoft/WSL/issues/5611#issuecomment-716326445_

I was sent here by https://github.com/microsoft/WSL/issues/5611#issuecomment-716686166

**Comment by therewillbeblood** [comment]
hi @craigloewen-msft , was this issue fixed or closed with "won't fix" ?

**Comment by craigloewen-msft** [comment]
This text is present here on the doc page:
https://docs.microsoft.com/en-us/windows/wsl/wsl-config#:~:text=The%20command%20wsl%20%2D%2Dshutdown%20is%20a%20fast%20path%20to%20restarting%20WSL%202%20distributions%2C%20but%20it%20will%20shut%20down%20all%20running%20distributions%2C%20so%20use%20wisely.
