### ISSUE TITLE
missing info about prerequisities

### ISSUE THREAD

**Issue by martindz** [MicrosoftDocs/WSL#974]
Hi Craig,

Have W10 installed WSL and upgraded to version 2, registered different distros, however wsl with mount switch is not available. It will be great to ensure all prerequisites are mentioned on the page. Is there any docu somewhere else I could follow to be able to mount a disk.

###
wsl --mount
Invalid command line option: --mount
###

Thanks
Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e255b0-71c7-adc6-cac0-6df3b76a971f
* Version Independent ID: a9d73ca3-7026-5b5a-f3fe-3511e976cde4
* Content: [Get started mounting a Linux disk in WSL 2 (preview)](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk)
* Content Source: [WSL/wsl2-mount-disk.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-mount-disk.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Hi @martindz you need to be on the right Windows build to be able to access the --mount feature! Specifically build 20211 or higher! You can get to this build number by joining the Windows insiders program on the 'Dev Channel' to try the latest Insiders builds.

I'll update the docs to include this build number and instructions on how to get there. Thanks for filing this!

**Comment by martindz** [comment]
Hi Craig,

Thanks, I thought it might be something like that.
I’m om 18363, it’s enough for WSL2, but obviously not for --mount feature

Martin
