### ISSUE TITLE
wsl_update_x64.msi should be downloaded from a microsoft domain

### ISSUE THREAD

**Issue by nickharris** [MicrosoftDocs/WSL#977]
the download link for the wsl update comes from an arbitrary azure storage account that could be owned or swapped out by anyone submitting a PR to the doc. Please provide the download from a microsoft domain.

https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
The domain itself points to an Azure blob storage CDN that is owned by our team. Would having it point to an aka.ms link address your feedback?

**Comment by nickharris** [comment]
yes aka.ms is better



Kind Regards,

Nick Harris

Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by craigloewen-msft** [comment]
Fixed this finally! :) 
https://github.com/MicrosoftDocs/WSL/commit/291c6767954e3d5034ea0099e5c1e1f1ea5b577d

**Comment by nickharris** [comment]
note still susceptible supply chain vector if you ever delete the storage account wslstorestorage1 and someone else takes it. best place for these types for downloads microsoft downloads - https://www.microsoft.com/en-us/download/developer-tools.aspx

**Comment by front48** [comment]
Thannks man , case solved !

**Comment by patricioparga** [comment]
Thanks so much for this change. I found this issue after looking at many webpages linking to the previous URL. Any security aware user would think 2 times before randomly downloading something from that link.

**Comment by SiddhantSadangi** [comment]
Is this link down? [http://aka.ms/wsl2kernelmsix64](http://aka.ms/wsl2kernelmsix64)

I am getting a 

> Secure Connection Failed
> 
> An error occurred during a connection to wslstorestorage.blob.core.windows.net. PR_END_OF_FILE_ERROR

**Comment by Awesomolocity** [comment]
@SiddhantSadangi Yeah I'm getting about ~10 MB into the download and it'll just freeze on me. Not just you.

**Comment by dancing-groot** [comment]
Have you tried https://aka.ms/wsl2kernelmsix64 instead? (HTTP**S**)

**Comment by ixe013** [comment]
This is somewhat of an unusual download. I can guarantee my mother will not download that.

Could it be that a desktop anti-virus or corporate proxy of some kind is blocking it?

**Comment by ArnoldVanN** [comment]
I still can't download wsl_update_x64.msi through either https://aka.ms/wsl2kernelmsix64 
or https://docs.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package
Anyone know if there's another way to download the kernel update package?
