### ISSUE TITLE
Troubleshooting section incorrect: "Bash loses network connectivity once connected to a VPN"

### ISSUE THREAD

**Issue by thernstig** [MicrosoftDocs/WSL#978]
The section _"Bash loses network connectivity once connected to a VPN"_ (https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#bash-loses-network-connectivity-once-connected-to-a-vpn) seems outdated.

**Problem 1**
5a says:
> Delete the first line from the file, which says "# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.".

However, looking inside `/etc/resolv.conf` it reads:
> This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
> [network]
> generateResolvConf = false

**Problem 2**
I actuall tried both to remove the line, and to add this to my /etc/wsl.conf (only thing I have in there):

```
[network]
generateResolvConf = false
```

but neither worked. The `/etc/resolv.conf` is updated once I exit/enter Ubuntu WSL2 again. Is problem 2 a documentation issue, or a real problem? For reference, my `/etc/wsl.conf` has permission 644.

**Comment by craigloewen-msft** [comment]
This is a known issue that we're working on, tracked here: https://github.com/microsoft/WSL/issues/8030

**Comment by thernstig** [comment]
@craigloewen-msft when that is solved, will the docs problems described above then be correct?

**Comment by craigloewen-msft** [comment]
Oh great call out! I've updated the docs to be more accurate in this commit.
https://github.com/MicrosoftDocs/WSL/commit/4b396801f938383c04131fb4493c50549b1d39fa

Thank you for the suggestion!
