### ISSUE TITLE
metadata not listed in mount option table

### ISSUE THREAD

**Issue by therealkenc** [MicrosoftDocs/WSL#980]
The list of drvfs [mount options](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#mount-options) does not include `metadata`, yet is identified in the `[automount]` example [just above](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-per-distro-launch-settings-with-wslconf). That makes it difficult to link when directing people to enable metadata.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-per-distro-launch-settings-with-wslconf)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Added a change for this! Thanks for the spot Ken :) 

https://github.com/MicrosoftDocs/WSL/pull/983
