### ISSUE TITLE
the wsl.exe command has no --mount option

### ISSUE THREAD

**Issue by jerryasher** [MicrosoftDocs/WSL#985]
[Enter feedback here]

In powershell I typed:

     wsl --mount \\.\PHYSICALDRIVE3 --partition 4 --type ext4

what wsl told me was

    PS C:\Users\jerry> wsl --mount \\.\PHYSICALDRIVE3 --partition 4 --type ext4
    Invalid command line option: --mount
    Copyright (c) Microsoft Corporation. All rights reserved.

    Usage: wsl.exe [Argument] [Options...] [CommandLine]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e255b0-71c7-adc6-cac0-6df3b76a971f
* Version Independent ID: a9d73ca3-7026-5b5a-f3fe-3511e976cde4
* Content: [Get started mounting a Linux disk in WSL 2 (preview)](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk)
* Content Source: [WSL/wsl2-mount-disk.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl2-mount-disk.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Please make sure you're on the right Windows version! You can view the version requirements at the top of the doc, and you likely will need to update your Windows build to be a build on the Windows Insiders preview program.
