### ISSUE TITLE
this doesn't work on surface x home with version 2004

### ISSUE THREAD

**Issue by timcwilson** [MicrosoftDocs/WSL#989]
I see a bunch of people have this issue, but even following the rabbit hole of issue to issue because it is supposedly a duplicate there is no helpful answers.

C:\WINDOWS\system32>debian
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070057
Error: 0x80070057 The parameter is incorrect.

Press any key to continue...

Best guess is it has something to do with virtual networking, but how do I fix it? As Microsoft knows, I can't install Hyper-V because I have home edition. Do I need Windows Pro just to get WSL2 going?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/troubleshooting.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
We've put out fixes for this on the latest versions, please try again this scenario should work and is supported!
