### ISSUE TITLE
Possible solution? WSL setting default version2

### ISSUE THREAD

**Issue by MelissaHendersongiteasy** [MicrosoftDocs/WSL#993]
I was having a problem setting the default for WSL2. ]
I went to Powershell and looked at the commands and what function they execute. I came across the one that said "Set-WinDefaultInputMethod" I didn't put this command in the Powershell, myself. I went to my own settings and went to "Settings," and then "Time and Language" and then I clicked on "Languages"  and then clicked on "choose an input method to always use a default." It should say - Advanced keyboard settings on the top of the page. There are only two language settings. Click on the one that says that says recommended. Below that, click the one that says, " let me use a different input method for each app window." After I had done this, I had no problems at all. Before, I tried EVERY possible wording that I could try. I also switched the words around in the Powershell. I put, set --default-version2. 
Hey everyone, if I'm kind of late on this, meaning, if everyone has already figured out the problem without having to uninstall things and then install again, please don't laugh at me. Lol. I AM NOT TECH SAVY AT ALL. But I'm learning and I hope this helps someone. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
What's the exact command that you were inputting here? It should be: 
`wsl --set-default-version 2` 
And did you make sure you have already installed the WSL optional components?
