### ISSUE TITLE
WSL kex is not responding 

### ISSUE THREAD

**Issue by linuxUser10111** [MicrosoftDocs/WSL#994]
hello,

i have been working with wsl2 for few days i have never had  any problem with it until recently when i wanted to start it by using the kex UI i got the following error:
Use of uninitialized value in pattern match (m//) at /usr/bin/tigervncserver line 490.

tigervncserver: Can't parse pid file '/home/x/.vnc/DESKTOP-EO0M44Q.localdomain:1.pid'!

Use of uninitialized value in pattern match (m//) at /usr/bin/tigervncserver line 490.

tigervncserver: Can't parse pid file '/home/x/.vnc/DESKTOP-EO0M44Q.localdomain:1.pid'!

do you have any idea on how to resolve this issue?

**Comment by jhaprashant079** [comment]
I am getting the same problem,if you was able to resolve it please help.

**Comment by craigloewen-msft** [comment]
This is a problem related to the Kex Linux binaries. Please reach out to Kali Linux for help with this exact problem. Thank you for filing!
