### ISSUE TITLE
Reference to VSCODE-REMOTE should be REMOTE-WSL

### ISSUE THREAD

**Issue by hhulsman** [MicrosoftDocs/WSL#997]
In the section `From VS Code`, the second line reads: `If you then type VSCODE-REMOTE`. This should be: `If you then type REMOTE-WSL`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 782a4458-6a56-63e5-efaf-d1868762ed06
* Version Independent ID: 312f71d9-db7d-52a5-b03d-9b6d4c680c2a
* Content: [Get started using VS Code with Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode#from-vs-code)
* Content Source: [WSL/tutorials/wsl-vscode.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-vscode.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Thanks @hhulsman! Fixed it! https://github.com/MicrosoftDocs/WSL/commit/1b1ababeaed0091058398fac7414e7248a448dea
